### ISSUE TITLE
Dependabot Email re: add issue to project failure when filing a ticket in dependabot-core?

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#10075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

n/a

### Package manager version

n/a

### Language version

n/a

### Manifest location and content before the Dependabot update

n/a

### dependabot.yml content

n/a

### Updated dependency

n/a

### What you expected to see, versus what you actually saw

I filed a [ticket in this repo for support ](https://github.com/dependabot/dependabot-core/issues/10074) on dependabot but got a failure email, linking to https://github.com/dependabot/dependabot-core/actions/runs/9664272755

I don't think it's related to me, should this email/failure even go to bug filers? anything I need to do?

<img width="750" alt="image" src="https://github.com/dependabot/dependabot-core/assets/24306571/27096fc7-a444-43e7-93d4-ce30fc6d073c">

**Comment by broksonic21** [comment]
Got same failure email when filing this issue

**Comment by jakecoffman** [comment]
Thanks for reporting that, it should be fixed now!
