### ISSUE TITLE
Bundler changing the specified platform

### ISSUE THREAD

**Issue by saturnflyer** [dependabot/dependabot-core#10085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

bundler 2.5.5

### Language version

Ruby 3.3.1

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      production:
        dependency-type: 'production'
      development:
        dependency-type: 'development'
      patches:
        update-types:
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

### Updated dependency

from:
- ffi (1.17.0)

to:
- ffi (1.17.0-x86_64-linux-gnu)

### What you expected to see, versus what you actually saw

There should be no change to this gem.
But the platform was updated

Expected:
```
PLATFORMS
   ruby
```

Actual:
```
PLATFORMS
   x86_64-linux
```

### Native package manager behavior

```
> bundle update ffi
Fetching gem metadata from https://rubygems.pkg.github.com/sofware/..
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler attempted to update ffi but its version stayed the same
Bundle updated!
```

### Images of the diff or a link to the PR, issue, or logs

<img width="1002" alt="Screenshot 2024-06-26 at 10 07 02 AM" src="https://github.com/dependabot/dependabot-core/assets/4271/c179536e-d21c-41bd-8108-1cdc7a405592">

**Comment by saturnflyer** [comment]
This issue seems to reflect the same problem with the platform changing https://github.com/dependabot/dependabot-core/issues/10034

**Comment by deivid-rodriguez** [comment]
Can you share a public PR with this problem? I'd like to have a look.

**Comment by saturnflyer** [comment]
@deivid-rodriguez this is in a private repository. I'll see if I can recreate it in a public one

**Comment by saturnflyer** [comment]
Had this come up in _another_ private repo when updating the `clearance` gem

<img width="1010" alt="Screenshot 2024-06-28 at 3 02 44 PM" src="https://github.com/dependabot/dependabot-core/assets/4271/b237e9b2-8a0f-432e-a706-60c3f1205161">

I don't understand how it would get `x86_64-darwin`

**Comment by saturnflyer** [comment]
@deivid-rodriguez I'm trying to recreate this over here https://github.com/saturnflyer/dependabot-bug/pull/1/files but dependabot isn't changing the platform.
I'll see if adding additional dependencies makes a difference

**Comment by jorg-vr** [comment]
we are having the same issue in our dependabot prs.

Examples:
- https://github.com/dodona-edu/dodona/pull/5657/commits/659907d16c04ce294b4cd5b5a85d99670c2efe5b
- https://github.com/dodona-edu/dodona/pull/5658/commits/ba3ee1b8e497c8cf867e2bc324c38faf8c919675
- https://github.com/dodona-edu/dodona/pull/5659/commits/157a4cb1e4798c941d78319a40c89ca0c5ea5586

The added system specification breaks building in for example our github actions

**Comment by jdongelmans** [comment]
I can also report we have the same in **some** of our repositories, it removes the `ruby` platform and adds the `x86_64-darwin` for seemingly no apparent reason.

Weird thing is that with the exact same `dependabot.yml` it works fine in other repo's.

**Comment by deivid-rodriguez** [comment]
Thanks for sharing those PRs, will look into this.

**Comment by deivid-rodriguez** [comment]
I identified this as a problem in Bundler. Will work on a solution upstream and propose an update of the Bundler version used by Dependabot once ready.

**Comment by deivid-rodriguez** [comment]
I have an [upstream fix](https://github.com/rubygems/rubygems/pull/7833)! Probably won't be included in the next release, but in the one after.

**Comment by deivid-rodriguez** [comment]
So some updates here, upstream PR is merged and I plan to release it by the end of next week.

**Comment by deivid-rodriguez** [comment]
Fixes are now released, so this issue should be gone (🤞) once Dependabot upgrades through #10246.

**Comment by deivid-rodriguez** [comment]
Let me know if you're still seeing issues after this update, thanks!

**Comment by laasem** [comment]
Hello @deivid-rodriguez! Has this update been released? Can't find it in latest [tag](https://github.com/dependabot/dependabot-core/releases/tag/v0.266.0).

**Comment by jdongelmans** [comment]
@laasem Yeah it looks like it missed the release indeed.

I also still have the issue persisting in my repo's after the latest Dependabot runs so hopefully it will catch the next one!

**Comment by deivid-rodriguez** [comment]
mmmm I guess if you're using Dependabot as a standalone tool you need to wait for the next release, but if you're using Github.com's dependabot updates service, I'd say this has already been deployed. Maybe there are still some issues? Can you point to a public PR where this is still happening?

**Comment by jorg-vr** [comment]
This resolved for me in most but not all prs.

It still persisted here: https://github.com/dodona-edu/dodona/pull/5706/commits/fc0dd9d9e2cc941c98da13ad98dc3e45808244a3

**Comment by deivid-rodriguez** [comment]
In that case, `ffi` is actually a transitive dependency of `image_processing`, so it's expected.

It's not clear whether bundler should "upgrade platforms" when running `bundle update`. It currently does so, so from dependabot-core's point of view, this is expected.

The behavior could be changed upstream, but I'm not fully sure if we want to change it, because otherwise if a gem author releases a platforms specific variant of a gem that you do want to use, you' won't be able to pick up that upgrade if we change the behavior.
