### ISSUE TITLE
Dependabot is not superseeding existing prs with earlier versions

### ISSUE THREAD

**Issue by OwenPattison** [dependabot/dependabot-core#10103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm, nuget

### Package manager version

latest

### Language version

nodejs v20

### Manifest location and content before the Dependabot update

n/a

### Updated dependency

the symptom is across multiple packages

### What you expected to see, versus what you actually saw

I would expect a new version of the pull request to superseed an existing open pull request

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/5864244/e01050a4-9f8c-4b58-8f1e-10408ba48efe)

### Smallest manifest that reproduces the issue

version: 2
updates:
- package-ecosystem: npm
  directories:
  - "/app"
  - "/infrastructure"
  - "/user-docs"
  schedule:
    interval: daily
  ignore:
  - dependency-name: "nx"
    versions:
    - 9999.0.1
  versioning-strategy: increase

**Comment by juliojgd** [comment]
Same problem detected with package-ecosystem: maven

**Comment by adamjstewart** [comment]
And pip: https://github.com/dependabot/dependabot-core/issues/10126

**Comment by adamjstewart** [comment]
@OwenPattison @juliojgd out of curiosity, is there anything special about the specific dependencies you're seeing this issue with? For example, in the Python ecosystem, I'm only seeing this issue with `lightning[pytorch-extra]` which has an extra attached to it. I'm also seeing other issues with this dependency too, so I wonder if it's something to do with more complicated dependencies.

**Comment by OwenPattison** [comment]
> @OwenPattison @juliojgd out of curiosity, is there anything special about the specific dependencies you're seeing this issue with? For example, in the Python ecosystem, I'm only seeing this issue with `lightning[pytorch-extra]` which has an extra attached to it. I'm also seeing other issues with this dependency too (#10180), so I wonder if it's something to do with more complicated dependencies.

I would not consider the duplicates I've been seeing as special dependencies, Since first noticing this issue I can also confirm this seems to be happening in both npm and nuget packages

**Comment by juliojgd** [comment]
@adamjstewart nothing special, it was a AWS SDK version upgrade (Maven). See 
![image](https://github.com/dependabot/dependabot-core/assets/28807086/a8205203-eff1-4813-aa7f-0503cb5e074d)

Sorry but it's a private repository, I can't share the link.

**Comment by jakecoffman** [comment]
This should be fixed now, I was able to reproduce the problem and verify the fix.

The Dependabot service had a bug preventing superseding but it only affected non-root directories when wildcards weren't in use (e.g. **/*).

Going forward, PRs should be superseded correctly. You're welcome to leave them open to verify yourself that it's solved.

Thanks for you patience!

**Comment by ngan** [comment]
I think this issue has come back. We’re noticing mulptiple PRs open from dependabot with multiple versions of the same gem.

**Comment by juliannguyen4** [comment]
I have this issue with `pip`. These 2 PR's are updating the same dependency:

https://github.com/aerospike/aerospike-client-python/pull/950
https://github.com/aerospike/aerospike-client-python/pull/952

This is my dependabot config: https://github.com/aerospike/aerospike-client-python/blob/19.0.0/.github/dependabot.yml#L14
