### ISSUE TITLE
Dependabot opening multiple PRs for a single dependency

### ISSUE THREAD

**Issue by adamjstewart** [dependabot/dependabot-core#10126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip 23.0.1

### Language version

Python 3.10–3.12

### Manifest location and content before the Dependabot update

https://github.com/microsoft/torchgeo/blob/main/requirements/required.txt

### dependabot.yml content

https://github.com/microsoft/torchgeo/blob/main/.github/dependabot.yml

### Updated dependency

lightning 2.2.5 to 2.3.0 or 2.3.1.

### What you expected to see, versus what you actually saw

Normally, when a new version is released, dependabot updates an existing unmerged PR. However, in this case, dependabot opened 2 PRs instead.

### Images of the diff or a link to the PR, issue, or logs

* https://github.com/microsoft/torchgeo/pull/2119
* https://github.com/microsoft/torchgeo/pull/2141

**Comment by OwenPattison** [comment]
@adamjstewart This looks like a duplicate of: https://github.com/dependabot/dependabot-core/issues/10103.
Although your ecosystem is slightly different I hope one fix resolves both our issues.

**Comment by adamjstewart** [comment]
Closing as a duplicate
