### ISSUE TITLE
@dependabot recreate not recreating

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#10135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

Over the last week, we've seen @dependabot recreate work less than before

Specifically, in grouped PRs

Scenario:

* Have a grouped dependabot PR
* with a conflict in package.json/package-lock.json vs main
* comment as `@dependabot recreate`
* the rebase logs (for dependabot on github action) show it attempts to create a PR, but there's no change to the PR made - so it stays conflicted

I've noticed this specifically when the group PR wouldn't change what dependency versions it has, but I wanted to recreate to fix up the conflicts.

This is in private repositories, so I don't have direct logs, but definitely seen this happen more and more. Anything you are tracking or have on your end?

**Comment by jpaakko** [comment]
It looks like this might be a duplicate of https://github.com/dependabot/dependabot-core/issues/10118.

**Comment by broksonic21** [comment]
@jpaakko thanks - confirmed, similar issue - hadn't seen that one. Agreed, this is broken on grouped ones, I'll comment there too.
