### ISSUE TITLE
`@dependabot recreate` stopped doing anything

### ISSUE THREAD

**Issue by martinpitt** [dependabot/dependabot-core#10162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

10.5

### Language version

Node.js 20.12

### Manifest location and content before the Dependabot update

https://github.com/cockpit-project/cockpit-files/blob/main/package.json

Content is not really relevant for this bug

### dependabot.yml content

https://github.com/cockpit-project/cockpit-files/blob/main/.github/dependabot.yml

### Updated dependency

esbuild (but not relevant)

### What you expected to see, versus what you actually saw

We configured dependabot to update our npm modules once a week. For technical reasons (we put `node_modules/` into git), we have to land the resulting set of PRs serially: land the first one, then `@dependabot recreate` the second one, let node_modules/ get rebuilt and commited, land it, etc.

A few weeks ago this broke: aside from reacting with :+1: to the github comment, [like here](https://github.com/cockpit-project/cockpit-files/pull/632#issuecomment-2212442446), it does absolutely nothing any more. Previously it recreated the PR from scratch, i.e. started again from current main branch and re-applied the corresponding npm module update.

`@dependabot rebase` does not work for our purposes, as a workflow always amends the `node_modules/` submodule change to the dependabot commit, so it treats it as "user modified".

### Smallest manifest that reproduces the issue

This happens to all our projects, and all recent dependabot PRs. The manifest or package.json seem to be irrelevant.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-podman/pull/1786 is another example. If you need more, we can easily give you a dozen more URLs, but this doesn't feel very specific to the project, npm module, or configuration.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-ostree/pull/651 is a case where we don't even have an extra node_modules workflow amending the commit. This is a pure, pristine dependabot PR which refuses to `recreate`.

**Comment by taylorthurlow** [comment]
Probably same issue as https://github.com/dependabot/dependabot-core/issues/10118.

**Comment by martinpitt** [comment]
Right, #10135 was about `recreate` and was closed as a duplicate. That's fine.

Closing as duplicate of #10118. Thanks!
