### ISSUE TITLE
Incorrect version update in Gemfile

### ISSUE THREAD

**Issue by connorshea** [dependabot/dependabot-core#1022]
I just noticed this problem with a change dependabot made to my `Gemfile` when upgrading [webpacker](https://rubygems.org/gems/webpacker). This was almost a month ago, so it may have been fixed since then.

```ruby
# Before
gem 'webpacker', '~> 4.0.0-rc.5'

# After
gem 'webpacker', '~> 4.0.0.rc.rc.7'
```

Admittedly I wasn't right either (the version should've been [4.0.0.rc.5](https://rubygems.org/gems/webpacker/versions/4.0.0.rc.5)), but I expect dependabot to make up for my stupidity ;)

The change it should have made would've been this:

```ruby
gem 'webpacker', '~> 4.0.0.rc.7'
```

Either way, Bundler managed to get the right version in the end so I guess it doesn't matter _too_ much.

Dependabot's commit with the problem is here: https://github.com/connorshea/ContinueFromCheckpoint/commit/1d198d71fe481373dcf24ac60c139998391368f0#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

**Comment by greysteil** [comment]
Oh, good catch, and thanks for reporting. I'll take a look.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/e19fc1fd61ff63584f52c3017ecddd5815cfbef7.

**Comment by connorshea** [comment]
Thanks for the quick turnaround as always!
