### ISSUE TITLE
Dependabot closes some of its own terraform PRs with no human intervantion

### ISSUE THREAD

**Issue by totherme** [dependabot/dependabot-core#10276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Related issues include:
- https://github.com/dependabot/dependabot-core/issues/439  -- closed in 2018
- https://github.com/dependabot/dependabot-core/issues/10019 -- still open, but doesn't exactly describe this issue, and is for a different package ecosystem (npm)

### Package ecosystem

terraform

### Manifest location and content before the Dependabot update

You can see a minimal reproduction in [this git repo](https://github.com/totherme/dependabot-testing).

I have **two** `main.tf` files, one in `/production` and one in `/staging`.

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
```

### What you expected to see, versus what you actually saw

I expected to get two similar PRs, one for `staging`, and one for `production`.

I actually got the two PRs I expect, but then without any human intervention, dependabot closed the production one.

Looking at [the closed PR](https://github.com/totherme/dependabot-testing/pull/1), we can see why:

> Superseded by [#2](https://github.com/totherme/dependabot-testing/pull/2).

To be clear, PR 2 did **not** accurately supersede PR 1. Both PRs were needed. One updated staging, the other updated prod. Dependabot incorrectly believed that if we updated staging, prod would be fine.

I would like for Dependabot to open the two PRs exactly as it did, but for it *not* to then immediately close one of them.

### Smallest manifest that reproduces the issue

The smallest reproduction I could come up with is at https://github.com/totherme/dependabot-testing

**Comment by jakecoffman** [comment]
I rewrote the superseding logic the other day, this is fixed now: https://github.com/jakecoffman/dependabot-testing/pulls

Thanks for the minimal reproduction!
