### ISSUE TITLE
GitHub compare link broken for Terraform module with 'v' tag prefix

### ISSUE THREAD

**Issue by domcleal** [dependabot/dependabot-core#1029]
Example pull request: https://github.com/domcleal/terragrunt-infrastructure-live-example/pull/1

![image](https://user-images.githubusercontent.com/482089/53555021-fcfa9a00-3b38-11e9-9677-3d340e53b138.png)

The _compare view_ link to GitHub's diff points to:

    https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/compare/0.0.1...0.0.2

But the 'v' prefix for the tags hasn't been detected, or has been stripped off. The link should be:

    https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/compare/v0.0.1...v0.0.2

The list of commits in the PR is also missing. The GitHub release notes were picked up correctly though.

**Comment by greysteil** [comment]
Thanks - I'll take a look.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/f22e88c24993582a79fb0f815ab744f3a34e415e.

**Comment by domcleal** [comment]
Thanks @greysteil!
