### ISSUE TITLE
Support for CloudFormation's SolutionStackName

### ISSUE THREAD

**Issue by stig** [dependabot/dependabot-core#1031]
Would be fantastic if you could find a way to suggest updating SolutionStackName in CloudFormation templates that you may encounter. (I.e. in YAML or JSON files.) This is tedious to update by hand, IMO, so it would help a lot. 

One complicating factor is that there's no standard files used to list dependencies / versions for CloudFormation. However, because [the version strings are so long](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.docker) (e.g. `64bit Amazon Linux 2018.03 v2.12.9 running Docker 18.06.1-ce` for the current one) and the [past versions are known](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-docker-single.html), coupled with them updating infrequently (so there's not that many of them) one could conceivably attempt a series of string replacements from all the old versions to the most recent one across all the YAML/JSON files in a repo and do a PR if any files changed (and stays syntactically correct).

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.
