### ISSUE TITLE
Dependabot recreate / rebase not working

### ISSUE THREAD

**Issue by darkdragon-001** [dependabot/dependabot-core#10310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

_It was requested to create new, separate issues in https://github.com/dependabot/dependabot-core/issues/1645#issuecomment-1231162232._

### Package ecosystem

npm, Cargo

### dependabot.yml content

https://github.com/axolotl-chat/axolotl/blob/main/.github/dependabot.yml

### Updated dependency

- [Bump bootstrap from 5.3.2 to 5.3.3](https://github.com/axolotl-chat/axolotl/pull/1264) (npm)
- [Bump env_logger from 0.11.1 to 0.11.5](https://github.com/axolotl-chat/axolotl/pull/1274/) (Cargo)

### What you expected to see, versus what you actually saw

Commenting `@dependabot rebase` or `@dependabot recreate` to rebase/recreate on top of latest `main`, force push and and in turn resolve the conflict.

Dependabot added the thumbs-up emoji, I can see a successfully "rebase" job run in [Dependabot logs](https://github.com/axolotl-chat/axolotl/network/updates) but there are no changes pushed to the branches.

**Comment by Renari** [comment]
https://github.com/Renari/saber-alter/pull/1066

One such PR, I noticed this start today with no changes to this repo from me.

**Comment by jakecoffman** [comment]
Thanks for the reports! Should be fixed now, sorry about that!

**Comment by darkdragon-001** [comment]
I confirm it is working again. Thanks for the quick fix.

**Comment by zyv** [comment]
@jakecoffman it seems that it's broken again :(

https://github.com/rdamazio/efis-editor/pull/290#issuecomment-3314601684

The job run completes successfully, but there is no push:

https://github.com/rdamazio/efis-editor/actions/runs/17882432020

**Comment by Renari** [comment]
I've noticed that sometimes when this happens you can simply close and reopen the PR and that works.

**Comment by rdamazio** [comment]
Closing and re-running dependabot worked for the first PR which didn't need rebase:
https://github.com/rdamazio/efis-editor/pull/292

but then the second that dependabot created was again stuck in rebase (the action completes, but doesn't do the rebasing):

PR: https://github.com/rdamazio/efis-editor/pull/293

Action: https://github.com/rdamazio/efis-editor/actions/runs/17887445280
which says in its logs:
```
updater | 2025/09/21 01:49:59 INFO Results:
+-----------------------------------------------------------------------------+
|                     Changes to Dependabot Pull Requests                     |
+---------+-------------------------------------------------------------------+
| created | jspdf ( from 3.0.2 to 3.0.3 ), svg2pdf.js ( from 2.5.0 to 2.6.0 ) |
+---------+-------------------------------------------------------------------+
```
except nothing happened.
