### ISSUE TITLE
[Go] Dependabot updates to not existing version

### ISSUE THREAD

**Issue by janisz** [dependabot/dependabot-core#10339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.21

### Manifest location and content before the Dependabot update

https://github.com/stackrox/stackrox/blob/master/operator/tools/operator-sdk/go.mod

### dependabot.yml content

https://github.com/stackrox/stackrox/blob/master/.github/dependabot.yaml

### Updated dependency

https://github.com/operator-framework/operator-lifecycle-manager/

### What you expected to see, versus what you actually saw

Expected: `v0.28.0`
Got: `v3.11.0+incompatible`

### Native package manager behavior

```
go get -u github.com/operator-framework/operator-lifecycle-manager     
go: downloading github.com/operator-framework/operator-lifecycle-manager v0.28.0
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/stackrox/stackrox/pull/12213

**Comment by jakecoffman** [comment]
Dependabot uses `list` to get the available versions, and I see:

```console
$ go list -m -versions -json github.com/operator-framework/operator-lifecycle-manager
{
	"Path": "github.com/operator-framework/operator-lifecycle-manager",
	"Versions": [
		"v0.17.0",
		"v0.18.0",
		"v0.18.1",
		"v0.18.2",
		"v0.18.3",
		"v0.19.0",
		"v0.19.1",
		"v0.20.0",
		"v0.21.0",
		"v0.21.1",
		"v0.21.2",
		"v0.22.0",
		"v0.23.0",
		"v0.23.1",
		"v0.24.0",
		"v0.25.0",
		"v0.26.0",
		"v0.27.0",
		"v0.28.0",
		"v3.11.0+incompatible"
	]
}
```

It looks like they deleted the tag: https://github.com/operator-framework/operator-lifecycle-manager/issues/2253

But it's still in the Go Proxy:

```console
$ GOPROXY=direct go list -m -versions -json github.com/operator-framework/operator-lifecycle-manager
{
	"Path": "github.com/operator-framework/operator-lifecycle-manager",
	"Versions": [
		"v0.17.0",
		"v0.18.0",
		"v0.18.1",
		"v0.18.2",
		"v0.18.3",
		"v0.19.0",
		"v0.19.1",
		"v0.20.0",
		"v0.21.0",
		"v0.21.1",
		"v0.21.2",
		"v0.22.0",
		"v0.23.0",
		"v0.23.1",
		"v0.24.0",
		"v0.25.0",
		"v0.26.0",
		"v0.27.0",
		"v0.28.0"
	]
}
```

They might have to do a version [retraction](https://go.dev/ref/mod#go-mod-file-retract) to fix it.

Alternatively you can ignore that version of the dependency.
