### ISSUE TITLE
Dependabot update error when encountering a Visual Studio Installer project file (*.vdproj)

### ISSUE THREAD

**Issue by jamaa** [dependabot/dependabot-core#10372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.NET Framework 4.8

### Manifest location and content before the Dependabot update

Project file producing the error:
https://github.com/bluemodel/BlueM.Wave/blob/master/setup/Wave.Setup.vdproj

(I don't actually need dependabot to process this file but am unable to prevent it without unwanted side effects, see below)

### dependabot.yml content

Link to dependabot.yml (version that causes the error): https://github.com/bluemodel/BlueM.Wave/blob/3b245d30d60b7826f4bfa38917dc18928c4e298a/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Recently, dependabot has started returning an error when trying to update dependencies for a .NET framework project:
>Error: Dependabot encountered an error performing the update

Looking at the logs, the underlying cause seems to be an attempt by dependabot to read dependencies from a Visual Studio Installer project (*.vdproj):
>Unhandled exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.  /home/dependabot/dependabot-updater/repo/setup/Wave.Setup.vdproj

Link to log: https://github.com/bluemodel/BlueM.Wave/actions/runs/10249564040/job/28353228379#step:3:47

The *.vdproj installer project file is not actually the main target for the dependabot update, it should mainly be looking at the other *.vbproj project files in the repo. What I expect:
* dependabot should skip the *.vdproj file if it is unable to handle it
* or it should be possible to exclude this file from being processed by dependabot using the dependabot.yml configuration file

Regarding the second option, I have tried specifying only specific `directories` in the dependabot config, thus avoiding the problematic file, but the disadvantage is that dependabot then creates separate pull-requests for each of the specified directories. I would prefer an option to just exclude the *.vdproj file and dependabot creating a single pull-request per dependency, but applicable to multiple project files.

Something must have changed because dependabot was able to handle this repo and make sensible pull requests until not too long ago ([May 2024](https://github.com/bluemodel/BlueM.Wave/pull/150)).

**Comment by brettfo** [comment]
@jamaa For the time being the NuGet updater is focusing only on `.csproj`, `.vbproj`, and `.fsproj`.  Once we're in a more stable state we'll take a look at supporting other project file types.

However, from the error you mentioned, it appears that your `.vdproj` isn't valid MSBuild.  We're using the MSBuild libraries to load project files and the error you're seeing is MSBuild itself reporting that it can't load the file.

**Comment by jamaa** [comment]
Thanks for the feedback, @brettfo. Yes I understand that `.vdproj` is not supported, but how do I prevent dependabot from trying to process it? The `.vdproj` file has always been there, just since recently dependabot seems to have a problem with it. I want dependabot to process the `.vbproj` files only and ignore the `.vdproj` file, which is how I assume it used to work before.

**Comment by brettfo** [comment]
@jamaa Ahh, thanks for the clarification, I misunderstood the original issue.

Yes, you're correct we should filter out anything that's not explicitly supported, so in this case we shouldn't even _try_ to read that file.  In some places we do restrict the project file types, but I apparently missed some, I'll double check those.

**Comment by brettfo** [comment]
@jamaa Thank you for your help and for filing an issue with logs, links, etc., it made this easy to address.  I've submitted PR #10451 that fixes this issue.  With those changes I'm able to process updates for your repo.  I'll start the process to get this reviewed, merged, and deployed.

**Comment by jamaa** [comment]
Thank you @brettfo for the quick response and fix!
