### ISSUE TITLE
Add support for references to NuGet packages in global.json

### ISSUE THREAD

**Issue by alexanderkozlenko** [dependabot/dependabot-core#1044]
Add support for references to [MSBuild project SDKs](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017#how-project-sdks-are-resolved) NuGet packages in [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) for .NET Core solutions.

```json
{
  "sdk": {
    "version": "2.2.104"
  },
  "msbuild-sdks": {
    "Microsoft.Build.Traversal": "1.0.45"
  }
}
```

**Comment by greysteil** [comment]
Sorry for the slow reply. This makes sense to me, and should be easy to implement - I'll try to get it done today!
