### ISSUE TITLE
any way to update all my config.yml?

### ISSUE THREAD

**Issue by fisker** [dependabot/dependabot-core#1065]
I have several repos using dependabot with `config.yml` settings files.

I found It's hard to change something in all this files.

Do I have to edit those files one by one ? Or is there another way to do this easier ?

If not, Is there a plan to support a extendable config like `renovate` does.

**Comment by greysteil** [comment]
Nominate @feelepxyz on future plans, but I’m afraid we don’t have inheritance at the moment.

**Comment by fisker** [comment]
Thanks any way. 

Should I close this, or leave it as a feature request ?

**Comment by greysteil** [comment]
Let’s at least leave until a Phil has a chance to review. 🙂

(Not to pre-empt his thoughts too much, but I think we’re planning to move to allowing configuration in a .github repo that applies organisation wide (in the same way other GitHub settings are configurable).)

Thanks for the feedback on this!

**Comment by feelepxyz** [comment]
@fisker yes as Grey said, we'll probably allow org wide settings through a org .github folder. We don't have any plans on adding more complex inheritance/overriding functionality so would only work for the simple/default cases.

If you're using exactly the same languages across a bunch of repos you could share the config by adding a `.dependabot` folder as a git submodule and then configuring Dependabot to update your git submodules.

**Comment by ldemailly** [comment]
Did the org wide dependabot config happen?

Any doc/example on sharing/including across repos (in same org) maybe like actions?

ps: stepped on this closed issue as the top hit from google search

**Comment by ldemailly** [comment]
found https://github.com/dependabot/dependabot-core/issues/3360 still open further down the search results
