### ISSUE TITLE
Maven downgrading a SNAPSHOT dependency from a *.Final-SNAPSHOT to a *.Beta1

### ISSUE THREAD

**Issue by jamezp** [dependabot/dependabot-core#10668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### Manifest location and content before the Dependabot update

https://github.com/wildfly/wildfly/blob/main/pom.xml

### dependabot.yml content

https://github.com/wildfly/wildfly/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

The version was updated from `34.0.0.Final-SNAPSHOT` to `34.0.0.Beta1`. I would expect no version upgrade to be detected as per https://maven.apache.org/pom.html#version-order-specification a `*.Final-SNAPSHOT` should be greater than a `*.Beta*`.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/wildfly/wildfly/pull/18242

**Comment by amazimbe** [comment]
@jamezp  this issue should now be resolved. Can you retest and let me know please.

**Comment by jamezp** [comment]
Thank you @amazimbe. Looks fixed https://github.com/wildfly/wildfly/pull/18242#issuecomment-2411711750.
