### ISSUE TITLE
Enable NuGet updater image to support arm64

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#10689]
The NuGet updater image depends on `powershell` but currently only an amd64 package is provided, not arm64.  While production is on amd64 machines, contributors might be on ARM and could benefit from being able to build and run locally.

As of PowerShell version 7.4.5, there is no arm64 `.deb` file provided for installation, but there is a `.tar.gz` with pre-built binaries that could be extracted to the image.  Docker supports predefined values that can be used to determine the architecture of the underlying machine: https://docs.docker.com/build/building/variables/#multi-platform-build-arguments

**Comment by andrcuns** [comment]
FYI, I have added PR to fix this issue. It's fairly straight forward, `TARGETARCH` variable is already used in quite a few other dockerfiles
