### ISSUE TITLE
Add an option to only create an update PR if dependency is older than X days

### ISSUE THREAD

**Issue by moimael** [dependabot/dependabot-core#1069]
Hi,

It would be great to be able to create an update PR only if the dependency has been published for a set amount of time. This would be particularly useful for auto merge feature to make sure nothing critical breaks if the dependency update has just been released.

Thanks !

**Comment by greysteil** [comment]
Thanks for the feedback @moimael. We've got an issue tracking this one [here](https://github.com/dependabot/feedback/issues/295), so I'm going to close this but I agree it would be a useful option.
