### ISSUE TITLE
Can I use this project at work? License question.

### ISSUE THREAD

**Issue by bradleygolden** [dependabot/dependabot-core#1099]
I've been going over your license, read your readme, and read this issue #491. I've also [contributed](https://github.com/dependabot/dependabot-core/issues/399#issuecomment-480978407) a tiny amount to your project as well! I'm a little confused about your license and would like to make sure I'm not violating it in any way.

I work at start up with a small handful of engineers. We don't have a ton of money and try to go open source whenever possible. We don't want to use your software to make money and only would use it to help unburden ourselves from checking for outdated dependencies across our many projects (what your project aims to do). I'd love to support you monetarily but that might not be an option for us until later on.

I'm sure I speak for others as well and would love to hear from you, what do you mean by `add Dependabot's functionality to your for-profit company's offering`? Do you mean a) use it as it's intended or b) actually add it to our product offering and directly make money from it? An example of b) would be: I'm GitLab (which I'm not) and I want to add it to my auto devops pipeline to make my product more competitive.

I hope this is clear and please let me know if you have any questions. Thank you so much for your hard work and contributions!

**Comment by greysteil** [comment]
It’s b) we’re trying to protect ourselves from - you’re very welcome to use it to update your own dependencies! We have a note in our readme trying to make that clear, too, but I understand your caution.

Thanks for using Dependabot Core, and for contributing! :octocat:
