### ISSUE TITLE
Gradle plugin suggests updates to commented lines

### ISSUE THREAD

**Issue by nie7321** [dependabot/dependabot-core#1100]
The (beta) Gradle plugin has suggested updating a commented-out line for updating. From my `build.gradle`:

![Screen Shot 2019-04-08 at 3 43 53 PM](https://user-images.githubusercontent.com/27235866/55755651-37e3cd80-5a15-11e9-8550-7eec66a72ec1.png)

Oddly enough, that's just a Maven command -- not a dependency!

**Comment by greysteil** [comment]
Ha! We do some work to strip out comments before regex-parsing (yes, 😞 I know) the `build.gradle` file. I'll take a look at what went wrong here. Thanks for reporting it!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/47a3013de0ea946190e3fa21cde2cc4e8362e9f7. Thanks for the heads up!
