### ISSUE TITLE
'+' not accepted in maven version

### ISSUE THREAD

**Issue by matthewmcgarvey** [dependabot/dependabot-core#1101]
The [`ANCHORED_VERSION_PATTERN`](https://github.com/dependabot/dependabot-core/blob/master/maven/lib/dependabot/maven/version.rb#L32) in maven's `Version` class should match `2.1.5+32`.

We recently changed our versioning strategy to use the number after the `+` to represent the build number.  This probably isn't normal but this is keeping us from running dependabot for our internal libraries.

**Comment by greysteil** [comment]
Thanks for this, and for the associated PR. Are you aware of any published packages that use this setup? I'm slightly nervous about including it as there are no details about it in the [docs](https://maven.apache.org/pom.html#Version_Order_Specification).

**Comment by matthewmcgarvey** [comment]
I admit that this is slightly unusual.  We are following semantic versioning and including build number in the metadata as specified here: https://semver.org/#spec-item-10 and have found maven to handle it fine.  I don't know if there would be public libraries that use it.  Here's a library that has built handling around metadata https://github.com/zafarkhaja/jsemver#incrementing-versions though.  I was looking more into this with ruby and it looks like RubyGems does not support build metadata currently but can't find the article I saw that.  Nevertheless, in my local tweaking it looks like the PR I made is all that we need for it to work.  Otherwise, our library versions are considered incorrect.

Here's the link to the regex for RubyGems around versioning which doesn't seem to handle build metadata: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/version.rb#L159

**Comment by svanschooten** [comment]
@matthewmcgarvey Do you also use the build number when publishing your project/library to your maven repo? Otherwise I would recommend dependabot to omit these versions, especially since adding build numbers usually implies development/unstable builds. **Maybe** SNAPSHOT builds, but I would also omit these unless specified otherwise.

**Comment by matthewmcgarvey** [comment]
Yea, I think I will be closing these.  Even after fixing this regex there were too many other problems that I ultimately had to give up
