### ISSUE TITLE
Bumping gradle version too

### ISSUE THREAD

**Issue by TobiasRoland** [dependabot/dependabot-core#1103]
The [gradle versions plugin](https://github.com/ben-manes/gradle-versions-plugin) informs that there is a new gradle version available - it would be amazing if dependabot similarly could bump the version of gradle in addition to the project dependencies.

I have not looked into how to achieve this in practice, but If projects are based on the [Gradle Wrapper](https://gradle.org/install/#with-the-gradle-wrapper) it seems doable - although there's some complexity to consider with distribution-type `bin` or `all`.

**Comment by RohanNagar** [comment]
There is some discussion of this here too: https://github.com/dependabot/feedback/issues/237

**Comment by TobiasRoland** [comment]
Apologies, I thought I'd searched for it - I will close this
