### ISSUE TITLE
Dependabot doesn't seem to be working

### ISSUE THREAD

**Issue by CodeBlanch** [dependabot/dependabot-core#11113]
I recently enabled dotnet-sdk updates via Dependabot: https://github.com/open-telemetry/opentelemetry-dotnet/pull/6011

I was just checking on this today to see if it is working.

* I don't see any dotnet-sdk updates. I was expecting a PR to bump to 9.0.101.
* I noticed checking the below job Dependabot seems to be _trying_ to open PRs to update some actions but I don't see those PRs anywhere. Not sure why they aren't being opened?

https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/12302636230/job/34335934746

I'm trying to figure out how to troubleshoot this. Any help would be appreciated.

**Comment by jakecoffman** [comment]
There is a branch protection rule on the repo that is preventing Dependabot from creating PRs. 

We need to do a better job at surfacing that information. I'll file an internal issue to track that change.

**Comment by CodeBlanch** [comment]
@jakecoffman Makes sense, thanks. How do I allow Dependabot to push to restricted branches? I tried to add it as a user but nothing comes up in the search box.

**Comment by jakecoffman** [comment]
Dependabot should appear in the bypass dropdown list: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/creating-rulesets-for-a-repository#granting-bypass-permissions-for-your-push-ruleset

<img width="331" alt="Screenshot 2024-12-13 at 12 13 20 PM" src="https://github.com/user-attachments/assets/6a93c1f0-7a57-4798-8a29-f5edf2671a43" />

**Comment by CodeBlanch** [comment]
That worked thank you!
