### ISSUE TITLE
"Affected versions" from NPM security advisory not parsed correctly

### ISSUE THREAD

**Issue by rajivshah3** [dependabot/dependabot-core#1130]
We recently received a PR from Dependabot advising us that we were using an insecure version of Electron: https://github.com/iotaledger/trinity-wallet/pull/1388

From the NPM security [advisory](https://github.com/nodejs/security-wg/blob/master/vuln/npm/495.json):
> Affected versions: <2.0.18 || <3.0.16 || <3.1.6 || <4.0.8 || <5.0.0-beta.5
> Patched versions: ^2.0.18 || ^3.0.16 || ^3.1.6 || ^4.0.8 || ^5.0.0-beta.5

It seems like Dependabot didn't interpret the `||` correctly, because we are currently using 3.1.8, a non-vulnerable version. It suggested an upgrade to 5.0.0 (and opened this PR on the same day that 5.0.0 was released -- not sure if that played a role) even though it probably should have suggested the closest version (which we were already using anyway).

**Comment by greysteil** [comment]
Thanks for the heads up. I've updated our logic to prioritise the array of patched versions, although I think node security working group should also update the affected versions array in the above, as it's confusing!
