### ISSUE TITLE
Error: Dependabot::DependencyFileNotParseable on npm_and_yarn

### ISSUE THREAD

**Issue by gencer** [dependabot/dependabot-core#1133]
I get following error when  trying to parse a `npm_and_yarn`.
```
Error
Dependabot::DependencyFileNotParseable
```

Related `package.json` and `yarn.lock` is here: https://gist.github.com/gencer/e94d1108c3d077b19f2756ae74dde165

There is no package.lock. Just `json` and `yarn.lock`

**Comment by greysteil** [comment]
That error should have a file associated with it - can you call `file_path` on the error?

**Comment by gencer** [comment]
```
  begin
    dependencies = parser.parse
  rescue Dependabot::DependencyFileNotParseable => e
    puts e.file_path
  end
```

**prints:**

```
/yarn.lock
```

**Comment by greysteil** [comment]
Huh. That parses fine on my machine. What eversion of Yarn do you have installed? Can you try running `e.cause.message` (might not work), too?

**Comment by gencer** [comment]
`e.cause.message` gives nothing. I am using Node.js **v11.9.0** and Yarn **1.15.2**

**Comment by gencer** [comment]
In addition, This is how I installed npm_and_yarn


```
mkdir -p $(pwd)/native-helpers/npm_and_yarn
export DEPENDABOT_NATIVE_HELPERS_PATH="$(pwd)/native-helpers"
cd "$(bundle show dependabot-npm_and_yarn)"
helpers/build "$DEPENDABOT_NATIVE_HELPERS_PATH/npm_and_yarn" && cd -
```

Gemfile:

**Comment by greysteil** [comment]
I'm not sure how to help you with this one. Your error is coming from [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb#L175-L189) but given that the lockfile parses fine on my machine (and I presume on hosted Dependabot, too, but creating a test repo would be a good way to check) I can only assume something is different with your local setup. If you followed the instructions in the README to do the npm helper install then I'm not sure what that could be 😞.

**Comment by gencer** [comment]
Well, In here: https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb#L186

I see that, you rescue from `HelperSubprocessFailed`. I also have problems with golang's dep. Dep gives me `HelperSubprocessFailed` error. I was going to report that too.

Now it makes sense. It seems Dependabot cannot find required file (bin) or similar to this. This makes me wonder if I did something wrong with installation.

I was following dependabot-script repository. All depended helpers are installed in `native-helpers` directory. (_see below image_):

![image](https://user-images.githubusercontent.com/1711576/56906086-381e3880-6aaa-11e9-8505-790ca110fd5b.png)


How can i get an info about where dependabot is looking for subprocess and fails?

**Comment by greysteil** [comment]
The code that does the lookup is [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb). Sounds like we might have the instructions wrong in dependabot-script 😞.

(When I run locally I don't use that setup, so @hmarr or @feelepxyz might be able to better help debug. I run the script using the following Gemfile, and having done the install steps specified in dependabot-core's README)

```
ruby "2.6.2"
source "https://rubygems.org"

gem "irb"
gem "dependabot-omnibus", path: "../dependabot-core/omnibus"
gem "dependabot-bundler", path: "../dependabot-core/bundler"
gem "dependabot-cargo", path: "../dependabot-core/cargo"
gem "dependabot-common", path: "../dependabot-core/common"
gem "dependabot-composer", path: "../dependabot-core/composer"
gem "dependabot-dep", path: "../dependabot-core/dep"
gem "dependabot-docker", path: "../dependabot-core/docker"
gem "dependabot-elm", path: "../dependabot-core/elm"
gem "dependabot-git_submodules", path: "../dependabot-core/git_submodules"
gem "dependabot-go_modules", path: "../dependabot-core/go_modules"
gem "dependabot-gradle", path: "../dependabot-core/gradle"
gem "dependabot-hex", path: "../dependabot-core/hex"
gem "dependabot-maven", path: "../dependabot-core/maven"
gem "dependabot-npm_and_yarn", path: "../dependabot-core/npm_and_yarn"
gem "dependabot-nuget", path: "../dependabot-core/nuget"
gem "dependabot-python", path: "../dependabot-core/python"
gem "dependabot-terraform", path: "../dependabot-core/terraform"
```

**Comment by gencer** [comment]
I see. README's are mess. Script repository tells something, core says another. npm_and_yarn README says totally another story.

We need a proper README. I would be gladly help on this, however, even above sample you gave me i cannot make it work. I also installed helpers inside gems. Did not helped either.

Kindly, awaiting a response from @hmarr or @feelepxyz.

**Comment by feelepxyz** [comment]
@gencer hey sorry for the poor documentation! Setting up from scratch on my machine now and will see if I can figure out what's gone wrong.

**Comment by feelepxyz** [comment]
@gencer hey I've updated the readme to install native helpers in the script repo: https://github.com/dependabot/dependabot-script#native-helpers

This is pretty much what we do in the dependabot-core Dockerfile.

Let me know if you run into any issues.

**Comment by feelepxyz** [comment]
Just FYI, the readme in core is mostly geared towards development without Docker.

**Comment by gencer** [comment]
@feelepxyz Thank you so much for your help. It is fixed now. It just works.

**Comment by androdel** [comment]
I'm also having this issue. Couple of weeks ago it worked fine and now it's broken.

Gemfile:
```
# frozen_string_literal: true

ruby "2.7.1"
source "https://rubygems.org"

gem "irb"
gem "dependabot-omnibus", "~> 0.113.28"
```

Is the native helper the key to fix it?
