### ISSUE TITLE
Configurable branch deletion

### ISSUE THREAD

**Issue by evenh** [dependabot/dependabot-core#1150]
I would love for an option (either in the web UI or in the config file (or both :-)) for a configuring a delay for when to delete branches.

Something like:
 - 1 minute
 - 1 hour
 - Custom delay?
 - When dependabot scans next time for new dependencies

My use case is that when I merge a PR (that has successfully been built), a new build of `master` and the dependabot-managed update branch is triggered. I can't seem to configure my way around this, but then it marks the PR as failed because the dependabot-managed branch is deleted, and thus the build fails.

**Comment by greysteil** [comment]
Ack, that sounds really frustrating.

It's the first time I've heard this request, and my policy with Dependabot is generally to wait until I know there are a number of users who want an option before adding it. If this is affecting others then I'm 👍 on making it configurable.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by danbenton-mojdt** [comment]
I'm experiencing the same issue of the branch being deleted before the workflow (triggered by the pr being closed) has time to start up
