### ISSUE TITLE
Cargo lib with name 'examples` incorrectly classified as binary

### ISSUE THREAD

**Issue by prasannavl** [dependabot/dependabot-core#1156]
Hi there! We've started using `dependabot` for [Rust Async Working Group](https://github.com/rustasync/). However with one of our project restructure in our http server, [tide](https://github.com/rustasync/tide/), our experience was brought to halt very quickly hitting a bug that caused dependabot to fail our repo: 

https://github.com/rustasync/tide/

## Context

Issue here: https://github.com/rustasync/tide/issues/225

It appears `dependabot` currently validates Cargo manifest by adding dummy code to both `lib.rs` and `main.rs` for every crate. This behaviour is different from how `cargo` handles it, and we ended up hitting into a case where we have `examples` crate, but it doesn't have a binary (which is disallowed by cargo).

Source of the bug: [version_resolver.rb L310-L325](https://github.com/dependabot/dependabot-core/blob/eb7db25250ad9ee7f49f9da9c71c3d98de3e260f/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb#L310-L325)

Would be super cool if you could take a look at this soon! Thanks! :)

**Comment by greysteil** [comment]
Oh, interesting. Thanks for this feedback.

That's definitely a bug in Dependabot. Any recommendations on how we fix it? As you can probably tell, our current approach for fooling Cargo into thinking we have some code is pretty crude (but effective)...!
