### ISSUE TITLE
Go module update indirect dependencies

### ISSUE THREAD

**Issue by saschagrunert** [dependabot/dependabot-core#1158]
I would take dependencies with `// indirect` into account when checking for updates, WDYT?

**Comment by wwuck** [comment]
Any update on this?  It would be a useful feature for dependabot when there are security vulnerabilities in the indirect dependencies.

**Comment by mctofu** [comment]
Support for this was added in https://github.com/dependabot/dependabot-core/pull/6361.

For indirect dependencies in your `go.mod` file you'll now get security updates. You can also enable version updates for them by [configuring](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) your `dependabot.yml` to allow all dependency types (default is direct only).
