### ISSUE TITLE
Tracking: New ecosystem requests

### ISSUE THREAD

**Issue by rurban** [dependabot/dependabot-core#1162]
There are many individual requests to support to new package managers. Since it's now integrated into github I made my own list TODO:
*(in order of importance)*

* cmake
* pkg-config
* perl:EUMM
* perl:cpanfile
* perl:MB
* ~~nuget~~
* c:ccan
* deb
* rpm
* c:clib

but there are many more. I'll start working on some as need arises

**Comment by greysteil** [comment]
NuGet is already supported! 🎉 

I'm keen to add support for the others, too. But first I want to get PHP support into GitHub security alerts, so that we can start creating automated security fixes for it for all GitHub users.

**Comment by rojepp** [comment]
For .Net, I'd like to see [Paket](https://fsprojects.github.io/Paket/) support. Most of my repos use Paket as a NuGet replacement.

**Comment by greysteil** [comment]
@rojepp agreed! There's an old issue for it [here](https://github.com/dependabot/feedback/issues/363), but Dependabot-Core is the place to add it.

**Comment by malramsay64** [comment]
There are a number of additional issues requesting support for new package managers which I thought  might be useful to collate here.

- Crystal #1237 
- Swift #1245 
- Conda #1249 
- Java:Bazel #1215 
- asdf #1033 
- appraisal #978 
- rpm #847 
- cake-build #733 WIP #958 
- CocoaPods #416 WIP #731 
- Docker compose #390

**Comment by orj** [comment]
Swift package support would be great.

**Comment by brl0** [comment]
Just a quick note that the issue listed for conda above was closed as a duplicate in favor of #2227.  

IMHO conda support, and possibly the derivative or related miniconda, miniforge, mamba as well, would be very helpful for the python ecosystem.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

I'm going to close this, as essentially it's identical to what you get by searching for the `T: new-ecosystem` label: https://github.com/dependabot/dependabot-core/labels/T%3A%20new-ecosystem

Having individual issues for each requested ecosystem makes it easier to track / discuss them individually.
