### ISSUE TITLE
missing package_managers (summary):

### ISSUE THREAD

**Issue by rurban** [dependabot/dependabot-core#1163]
There are many individual requests to support to new package managers. Since it's now integrated into github I made my own list TODO:
*(in order of importance)*

* cmake
* pkg-config
* perl:EUMM
* perl:cpanfile
* perl:MB
* nuget
* c:ccan
* deb
* rpm
* c:clib

but there are many more. I'll start working on some as need arises

**Comment by greysteil** [comment]
Dup of https://github.com/dependabot/dependabot-core/issues/1162!
