### ISSUE TITLE
Python: requirements-dev.txt not recognised as dev dependencies

### ISSUE THREAD

**Issue by sneakypete81** [dependabot/dependabot-core#1165]
### STR:
* Set up a Python project containing a requirements_dev.txt file. (https://github.com/sneakypete81/usb_iss/blob/master/requirements_dev.txt)
* Configure dependabot to automerge development dependencies.
* Wait for a dependency update

### Expected:
Update PR is automatically merged by dependabot.

### Actual:
Dependency treated as a production dependency, and not automerged.

https://github.com/sneakypete81/usb_iss/pull/77
> Dependabot will not automatically merge this PR because it includes a minor update to a production dependency.

**Comment by sneakypete81** [comment]
BTW: congrats on the acquisition!

**Comment by greysteil** [comment]
This should be fixed by https://github.com/dependabot/dependabot-core/commit/98503905edd191bafd1a701e8eb698175d867edd. It's tricky to get this one perfect, but I think that'll be a decent improvement.

Thanks for the feedback!
