### ISSUE TITLE
yarn workspace with git submodule

### ISSUE THREAD

**Issue by benoitdion** [dependabot/dependabot-core#1166]
In our setup some of the yarn workspaces live in a git submodule. It seems like dependabot runs yarn before (or without) pulling down the submodules. Portions of our `yarn.lock` come from packages in the submodule so this causes dependabot to delete thousands of line in each Bump PR. 

What do you think about adding an option to initialize the submodules before running yarn?

**Comment by benoitdion** [comment]
Is there any workaround for this issue?

**Comment by jeffwidman** [comment]
This is a super old ticket... we'e made a lot of code changes since then, so is this still relevant/reproducible for folks?

 And if so, what version of Yarn are you running?

**Comment by isaacpovey** [comment]
Reproducible for me. Yarn 3.1.1 have a submodule that is a common library. Dependabot correctly applies updates to package.json but the yarn.lock file gets regenerated with all the submodules dependencies removed.

**Comment by deivid-rodriguez** [comment]
@isaacpovey Can you create a public repository that reproduces the problem? That would make resolution easier for us.

**Comment by isaacpovey** [comment]
Can do. Will try and get this done this week.

**Comment by isaacpovey** [comment]
Here is an example PR where dependabot is trying to update a dependency in the repo but it is removing libraries from the submodule in the yarn.lock https://github.com/isaacpovey/yarn-workspace-example/pull/1/files. The repo for the main project is https://github.com/isaacpovey/yarn-workspace-example/ and the submodule is https://github.com/isaacpovey/yarn-workspace-git-submodule-example. The use case we have here is a shared library for node services that is a submodule.

**Comment by kleinfreund** [comment]
I’m running into this issue as well and wanted to point out a detail that I noticed that others might run into as well:

We use yarn workspaces and one workspace is a git submodule (this is where the majority of the project’s come from). Other workspaces in the project (not git submodules) refer to the git submodule workspace in their respective package.json file via `"submodule-project": "*"`.

This works well overall, but dependabot can’t resolve the dependency:

```
ERROR <job_632424606> Couldn't find package "submodule-project@*" required by "regular-non-submodule-project@0.0.0" on the "npm" registry.
```

However, this can be solved using `"submodule-project": "file:../submodule-project"` instead.

At this point we started to get dependabot updates working but with the caveat of the lock file being incomplete on account of this issue.

**Comment by kleinfreund** [comment]
Generally asking, is there any reason why Dependabot shouldn’t _always_ (i.e. by default) check-out repositories including their submodules? To date, this is only the case for Go ...

https://github.com/dependabot/dependabot-core/blob/34e5f771d330acb86a428c20739c266b3aa70c93/go_modules/lib/dependabot/go_modules/file_fetcher.rb#L60-L62

... and perhaps in the near future for npm (via https://github.com/dependabot/dependabot-core/pull/6718).

**Comment by deivid-rodriguez** [comment]
I just deployed this fix, in case someone wants to verify it's working as expected.
