### ISSUE TITLE
Incorrect commit messages

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#1168]
For some reason `dependabot` started to produce incorrect commit messages:

- `Build(deps): bump ts-node from 8.1.0 to 8.1.1`, notice the `B`. It is not correct due to the existing `conventional-commits` standard where lower letters are used

It started ~2 days ago.

I am using `0.107.12`: https://github.com/wemake-services/kira-dependencies/blob/master/Gemfile

**Comment by sobolevn** [comment]
@greysteil any updates on this? It is still failing for me.

```
Parsing dependencies information
  - Updating @nuxtjs/auth (from 4.5.3)…/builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: Commit message does not follow the pattern '^(revert: )?(feat|fix|docs|build|refactor|chore)(\(.+\))?:.{1,50}(refs #\d+)?'. Request URI: https://gitlab.com/api/v4/projects/wemake%2Eservices%2Ftimeless_is/repository/commits (Gitlab::Error::BadRequest)
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/client/commits.rb:158:in `create_commit'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:83:in `retry_connection_failures'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator/gitlab.rb:107:in `create_commit'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator/gitlab.rb:41:in `create'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator.rb:59:in `create'
	from ./update.rb:130:in `block in <main>'
	from ./update.rb:78:in `each'
	from ./update.rb:78:in `<main>'

```

**Comment by greysteil** [comment]
Sorry, been a brutal week, as you might imagine! :octocat: 

I'll try to take a look at this today, but if I don't then I should be able to do it over the weekend.

**Comment by greysteil** [comment]
OK, it's tricky to know exactly why Dependabot is doing this because commit prefix is looked up dynamically. The logic to do so is [here](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/message_builder.rb#L171-L184). Is the repo you're running on here open source? Will make debugging a bunch easier if so.

**Comment by sobolevn** [comment]
It is not open-source, but it is not a secret either. I call it "internal-sourced".

I can send you an access on gitlab, please provide your username.

**Comment by sobolevn** [comment]
In case you want to have a look at the commit history. Here it is:
<img width="1209" alt="Снимок экрана 2019-06-01 в 2 23 25" src="https://user-images.githubusercontent.com/4660275/58739684-4d251900-8414-11e9-994b-5a2bfa1f3503.png">

**Comment by greysteil** [comment]
I think someone is having a similar issue on a GitHub public repo, so just digging into that. Will let you know what I find.

**Comment by greysteil** [comment]
Can you give `0.107.36` a go? Think it should be fixed by https://github.com/dependabot/dependabot-core/commit/2bd0e67c789cfd6bdf455faa28f2c406dd84f36a...

**Comment by sobolevn** [comment]
It works now. Thanks!

**Comment by greysteil** [comment]
Hurrah! Thanks for reporting and sorry for the delay fixing!

**Comment by sobolevn** [comment]
That's happening again:

```
- Updating @nuxtjs/auth (from 4.6.6)…/builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: Commit message does not follow the pattern '^(revert: )?(feat|fix|docs|build|refactor|chore)(\(.+\))?:.{1,50}(refs #\d+)?'. Request URI: https://gitlab.com/api/v4/projects/wemake%2Eservices%2Ftimeless_is/repository/commits (Gitlab::Error::BadRequest)
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/gitlab-4.11.0/lib/gitlab/client/commits.rb:158:in `create_commit'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:83:in `retry_connection_failures'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator/gitlab.rb:107:in `create_commit'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator/gitlab.rb:38:in `create'
	from /builds/wemake.services/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.106.20/lib/dependabot/pull_request_creator.rb:59:in `create'
	from ./update.rb:130:in `block in <main>'
	from ./update.rb:78:in `each'
	from ./update.rb:78:in `<main>'
```

**Comment by sobolevn** [comment]
@greysteil friendly ping. Dependabot is not working for me this week.

**Comment by greysteil** [comment]
Sorry for the delay. My job at GitHub doesn't include writing code (I'm in product, not engineering), and Dependabot Core doesn't have a team to replace me yet, so I'm not getting as much time to spend here as I'd like.

This is tricky to debug from the above alone. Is the repo this is occurring on public? Without a way to replicate I'm not sure what to suggest.

**Comment by sobolevn** [comment]
> My job at GitHub doesn't include writing code (I'm in product, not engineering), and Dependabot Core doesn't have a team to replace me yet, so I'm not getting as much time to spend here as I'd like.

Ok, I see. 😞 

Hm, I guess the easiest way is to invite you to the repo on Gitlab I am using right now. Is it fine?
If so, I can send you an invite, I just need your Gitlab account.

**Comment by greysteil** [comment]
👍 I'm @greysteil there, too.

**Comment by sobolevn** [comment]
Added! 

Control panel: https://gitlab.com/wemake.services/kira-dependencies
Target repo: https://gitlab.com/wemake.services/timeless_is

**Comment by greysteil** [comment]
Awesome - I'll take a look today

**Comment by greysteil** [comment]
Relevant: https://github.com/dependabot/dependabot-core/pull/1227

**Comment by greysteil** [comment]
Hang on, this says you're using `v0.106.20` of Dependabot Core. That pre-dates the previous fix...

**Comment by sobolevn** [comment]
<img width="1212" alt="Снимок экрана 2019-06-25 в 17 24 04" src="https://user-images.githubusercontent.com/4660275/60106541-0eae2000-976e-11e9-9d10-0030d5623fbf.png">

As you can see the commit hash is unchanged, but it had started failing one week ago.

**Comment by greysteil** [comment]
Can you try using `v0.108.20`?

**Comment by sobolevn** [comment]
It is now working again! I am using `0.108.22`.

Sorry for the inconvenience.
Can I buy you a beer / coffee / pizza? 😄

**Comment by sobolevn** [comment]
<img width="641" alt="Снимок экрана 2019-06-25 в 17 34 54" src="https://user-images.githubusercontent.com/4660275/60107413-92b4d780-976f-11e9-8bf1-b1c1ce6e9100.png">

**Comment by greysteil** [comment]
Haha, no worries! 🎉

**Comment by greysteil** [comment]
I'll try to get #1227 in tomorrow (want to get 24 hours for feedback) which will make commit messages more robust :-)
