### ISSUE TITLE
Not updating gem listed in Gemfile with version

### ISSUE THREAD

**Issue by mockdeep** [dependabot/dependabot-core#1169]
We have Rails listed in our `Gemfile` like so:

```rb
gem 'rails', '~> 5.2.2'
```

Right now the version in the `Gemfile.lock` is `5.2.2.1`, and the most recent version that is available is `5.2.3`. If I run `bundle update` it update Rails appropriately to `5.2.3`, but I don't see any PRs from Dependabot updating it, even after clicking the "Bump now" button. I've got no Filters enabled and it's scheduled for daily updates.

**Comment by greysteil** [comment]
Hi @mockdeep, can you link to the repo? Very hard to debug otherwise!  😉

**Comment by mockdeep** [comment]
@greysteil It's a private repo, https://github.com/mockdeep/questlog. Let me know if you need it and I can add you.

**Comment by greysteil** [comment]
Great - I’ll have a look into it

**Comment by mockdeep** [comment]
This issue is still relevant.

**Comment by feelepxyz** [comment]
@mockdeep sorry for the neglect! Is this working for you now? Looks like all dependencies are up to date on your repo at the moment.

**Comment by feelepxyz** [comment]
> This issue is still relevant.

Which dependency are you seeing this issue for?

**Comment by mockdeep** [comment]
@feelepxyz sorry, I was responding to stalebot. Didn't realize you were following up. I manually upgraded the dependencies, but I'll keep an eye out for similar behavior.

**Comment by feelepxyz** [comment]
@mockdeep sweet, just ping us when you see it again and we can debug against your Gemfile.

**Comment by BobbyMcWho** [comment]
I also encounter this issue when using dependabot-core with a custom script based off of dependabot-script. It does not update rails like I would expect it to.
