### ISSUE TITLE
Daily updates haven't processed in several days

### ISSUE THREAD

**Issue by mockdeep** [dependabot/dependabot-core#1170]
I have my projects configured to update daily, but for some reason they haven't updated in 3 days.

![bump](https://user-images.githubusercontent.com/80543/58398628-80c60480-800a-11e9-84f2-f4eb49154e39.png)

![daily](https://user-images.githubusercontent.com/80543/58398682-b0750c80-800a-11e9-8d8c-797efdd3199f.png)

**Comment by greysteil** [comment]
Dependabot doesn't create `daily` updates at the weekend. (It will create security patch PRs, though.)

**Comment by mockdeep** [comment]
@greysteil is there any way to configure this? For most of my projects if I specify `daily` I generally want it to update on weekends, too.

**Comment by greysteil** [comment]
Not at the moment - if I hear lots of folks ask for it I’ll reconsider, but in the meantime I’d recommend using `live`.

The switch away from creating PRs at the weekend was because lots of folks said backlogs we’re building up on their projects.
