### ISSUE TITLE
Bot does not sign commits any more

### ISSUE THREAD

**Issue by saschagrunert** [dependabot/dependabot-core#1184]
It looks like that dependabot does not sign `commit -s` any more. I'm seing this since some time, like here:
- https://github.com/saschagrunert/webapp.rs/pull/287/commits/63cf9e1bfd3f5b4784baf55c103ff18f166400ac

Is there any reason why this has been disabled? Or is it now optional somehow? Thanks in advance!

**Comment by greysteil** [comment]
Ooh, that is a mistake. It's changed because we no longer pass author details for commit signing, but we still want to include the `signed-off` line. I'll get that fixed.

**Comment by saschagrunert** [comment]
Thanks, great!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/a8499ddf0aef2305d4d860432bfe52ddd673f65f, which I'm deploying now.
