### ISSUE TITLE
Open PRs limit doesn't apply to security updates

### ISSUE THREAD

**Issue by anym0us** [dependabot/dependabot-core#1189]
Rate limiting settings don't take any effect on security-related updates.

-----

For instance, with the following settings, Dependabot will create 2 regular PRs for each technology PLUS an unlimited number of security PRs.

<img width="519" alt="Screen Shot 2019-06-06 at 11 55 01 AM" src="https://user-images.githubusercontent.com/5333431/59020246-43efde00-8852-11e9-82fd-328af1f259b6.png">

Please make the above numbers apply to security updates as well
or introduce a new field for security updates.

**Comment by greysteil** [comment]
I think the majority of users wouldn't want the above to apply to security updates, but we could introduce a new field that throttles those, too.

**Comment by anym0us** [comment]
It would be nice for our company because usually one team works on several projects.
So after enabling Dependabot we've got too many PRs assigned to one team (and we can't limit that number).

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.
