### ISSUE TITLE
package.json not always updated for monorepo with Lerna

### ISSUE THREAD

**Issue by loremaps** [dependabot/dependabot-core#1197]
copied from wemake-services/kira-dependencies#39

> I have a lerna monorepo and the MRs do not always include updates for the package.json files. The dependencies seems to be tracked correctly and the package-lock.json files are always updated.
> 
> For example:
> ![image](https://user-images.githubusercontent.com/18003912/59098785-f21a8700-8929-11e9-877a-aefc56fa4b5b.png)
> Here only one package.json got updated, although both packages have exactly the same version. The other was not updated.
> 
> For other dependencies I get only updates on the package-lock.json only.
> For some other dependency everything got updated correctly.
>

**Comment by greysteil** [comment]
This one's a Kira Dependencies issue - I've commented over there.
