### ISSUE TITLE
`use these reviewers` command doesn't work for GH teams

### ISSUE THREAD

**Issue by anym0us** [dependabot/dependabot-core#1198]
Reviews don't get assigned to GitHub teams when using `use these reviewers` command.

-----

Here's a screenshot to improve understanding:
<img width="312" alt="Screen Shot 2019-06-07 at 3 22 19 PM" src="https://user-images.githubusercontent.com/5333431/59104165-7aecef00-8939-11e9-83eb-7626b18eb1d5.png">

BTW, in Dependabot preferences teams appear without organization prefix (probably it's a cause):
<img width="241" alt="Screen Shot 2019-06-07 at 3 35 29 PM" src="https://user-images.githubusercontent.com/5333431/59104309-efc02900-8939-11e9-8a34-f99bae38d5d3.png">

**Comment by greysteil** [comment]
This is a GitHub bug I have wanted to fix for over a year. Now that I work for GitHub it is going to get fixed **very soon**! :octocat:

**Comment by anym0us** [comment]
👋  @greysteil
Any updates?

**Comment by greysteil** [comment]
It's with the GitHub Ecosystem Apps team, and they have a long note from me laying out my thoughts. Should be resolved in the next week. 🤞

**Comment by greysteil** [comment]
Update: just got the 👍 from the Ecosystem Apps team, which means this should be resolved soon. (The tricky part of this one was thinking through permissioning, which is now done - only implementation remains.) It will fix this for all GitHub apps that interact with PRs.

**Comment by rdohms** [comment]
@greysteil you have any updates? or maybe a release blog somewhere i can keep an eye on?

**Comment by greysteil** [comment]
The Ecosystem Apps team are going to size this today. Hopefully it's small and will be fixed imminently. 🙏

**Comment by glyph** [comment]
How did it get sized? :)

**Comment by greysteil** [comment]
Sized as small and high impact, but that team is swamped so we're going to have to take it on in our team. We have one person working across this and the branch protection issue, so it might take a couple of weeks for us to get this done. Painful I know, but we'll get there.

**Comment by nie7321** [comment]
@greysteil, I really appreciate your openness on the status of this, thank you! 👍

**Comment by rdohms** [comment]
Before this gets closed, I'm still hoping to get some insight into timelines? Still a big feature request for us.

**Comment by rebelagentm** [comment]
Sorry for the confusion!  We installed Stale to help us manage our backlog and some issues got closed before I had the chance to triage them.

There is a PR on the GitHub side to fix the bug.  It is currently awaiting review.

**Comment by kilbergr** [comment]
@rebelagentm Any update on this? I looked for a PR in this repo but I think it might be in another one. Thanks!

**Comment by rebelagentm** [comment]
@kilbergr The PR is with GitHub and not Dependabot Preview.  I will check with GitHub on the status.

**Comment by rebelagentm** [comment]
@kilbergr They are hoping to finish this shortly after Universe finishes this week.

**Comment by esacteksab** [comment]
Any update @rebelagentm? Thanks!

**Comment by rebelagentm** [comment]
@feelepxyz Any info on the status of this?

**Comment by feelepxyz** [comment]
@rebelagentm sadly still outstanding! We've been swamped working on integrating Dependabot Preview with GitHub so haven't had a chance to look at this yet.

**Comment by pranav-bagree** [comment]
Any updates? I see that the linked issue is still open. This feature is so critical, assigning individual users is a PITA and difficult to manage.

**Comment by mark-btmt** [comment]
Hey yall, appreciate all the work on Dependabot, truly an amazing feature for everyone.

I've been working on rolling it out org-wide, and not being able to assign teams as reviewers is a blocker. There's another thread here https://github.com/dependabot/feedback/issues/546 and they mentioned the `CODEOWNERS` workaround does not work.

Any chance this can be reprioritized so we get the fix soon? It's the only thing preventing me from smoothly rolling this out across the org.

Thank you so much for all your great work!

**Comment by feelepxyz** [comment]
@mark-btmt we've just launched a new version of Dependabot that's natively integrated into GitHub: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

We've fixed assigning team reviews in this version. FYI there is currently no support for private registries or private git dependencies. We're working on adding support for this over the next few months.

**Comment by mark-btmt** [comment]
@feelepxyz Yall are legends. Really happy about the newly readded config file support too! Thank you so much!

**Comment by bak** [comment]
@feelepxyz is there any chance this fix can be backported to dependabot v1 for those of us that need to hang on for private registries for now?

**Comment by infin8x** [comment]
@bak it can't, unfortunately, we're stretched quite thin. but, private registry support in GitHub-native Dependabot is coming along nicely - shouldn't be too much longer

**Comment by bak** [comment]
:heart: understood. Thanks!
