### ISSUE TITLE
Finding Python requirements files that aren't called requirements.txt

### ISSUE THREAD

**Issue by darrenburns** [dependabot/dependabot-core#1200]
Hi,

Our project has multiple requirements files inside a `requirements` directory, but none of them are called `requirements.txt`. Is there a way I can have Dependabot find these files?

An example of one of the names is `requirements/testing.txt`.

Thanks :)

**Comment by greysteil** [comment]
Hmmm, Dependabot should be picking up all of those files by default - fetcher logic is [here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_fetcher.rb)
