### ISSUE TITLE
Make gpgme optional

### ISSUE THREAD

**Issue by arthurnn** [dependabot/dependabot-core#1201]
Can we make `gpgme` gem optional? If you are not signing commits on the common side, and letting GitHub do the signing (assuming you are using common with GitHub), I don't think you need the gem. 
The gem has native extensions and takes a bit longer to install. So, removing if not using it would be a win.

**Comment by greysteil** [comment]
We can, but option gems are a pain in Ruby, and I don't think it's worth the effort. Very happy for anyone who's feeling more pain from it do so, though - approach would probably be to handle this everywhere `CommitSigner` is loaded.
