### ISSUE TITLE
pip-compile support seems broken

### ISSUE THREAD

**Issue by craigds** [dependabot/dependabot-core#1213]
We have a project with these files

```
requirements/base.in
requirements/base.txt
requirements/local.in
requirements/local.txt
requirements/production.in
requirements/production.txt
```

local.in includes base.txt, and production.in includes base.txt also.

Another of our apps has the same layout but there's additionally a test.in/test.txt. local.in includes test.txt, and test.in includes base.txt.

This is a very *normal* way to use pip-compile (having .in files that include previously-compiled .txt files), and is very effective if scripted properly. You have to compile the files in a particular order to get it right (in this case, base.in before either of the other .in files.) It's described here: https://jamescooke.info/a-successful-pip-tools-workflow-for-managing-python-package-requirements.html

For some reason dependabot opens PRs for just one of the txt files at a time. It doesn't touch the .in files (despite being configured to do so), and it doesn't update a dependency in *all* of the .txt files, only one of them.

e.g. in this example, `slacker` was bumped in `base.txt`, but not in `base.in`, and not in any of the other txt files (which all are generated from .in files that include `base.txt`):

<img width="1156" alt="Screen Shot 2019-06-12 at 9 07 06 PM" src="https://user-images.githubusercontent.com/32112/59339041-8dab5d80-8d57-11e9-8814-1ceca6d7e11a.png">

PRs like this aren't helpful at all as they just break things because now the dependencies don't have their correct subdependency versions, and additionally production doesn't match local because only one file got altered. In this case _nothing_ actually got altered, because base.txt isn't actually used by any app environments...

I don't think dependabot is running pip-compile at all. It's just literally finding a line in the .txt file and replacing the version number. Subdependencies don't get updated either.

**Comment by greysteil** [comment]
Thanks for the heads up - I'll take a look

**Comment by greysteil** [comment]
Can you @-mention Dependabot in a faulty PR so I can find it in our backend?

**Comment by craigds** [comment]
Cheers. I've tagged dependabot in all five PRs

**Comment by greysteil** [comment]
That's definitely a bug! Deploying https://github.com/dependabot/dependabot-core/commit/47044ae5057620546134a0c4500de45139b48cdc which will fix it.

**Comment by craigds** [comment]
I don't think this is fixed, or not deployed in any case. I tried it again and it did the exact same thing. 

* `.in` files untouched
* _only_ changed `base.txt`, not the other .txt files
* didn't detect python version (it upgraded ipython to 7.x though the repo is still using python 2.7)

I've just tagged dependabot in a couple of the new PRs

**Comment by craigds** [comment]
tried again with slightly different config, same thing. Tagged dependabot again in the PR.

This time it seemed to completely ignore the .in file, and updated a dependency in the .txt file to a version that was prohibited by the pin in the .in file. Which says to me maybe it doesn't even think we're using pip-compile at all?

**Comment by greysteil** [comment]
Taking another look. Seemed to be working fine when I dry ran it yesterday but perhaps I missed something.

**Comment by greysteil** [comment]
Looks very much like the fix hadn't been deployed. Looking into why...

**Comment by greysteil** [comment]
Oof, this is completely my fault - I bumped to the penultimate version of Dependabot Core when I did yesterday's deploy, not to the latest version. As a result the commit with the fix mentioned above didn't go out until three hours ago.

This *is* now fixed in production - apologies for the mixup, and the bug.
