### ISSUE TITLE
Packages on PyPI preferred to ones on our private devpi instance

### ISSUE THREAD

**Issue by craigds** [dependabot/dependabot-core#1216]
Dependabot seems to be having trouble with one of our internal packages in our private Devpi instance.

It was configured in our account to use `{baseurl}/root/dev/+simple/`

But for one of our packages (daisy) it's getting an error:

```
Could not find a version that satisfies the requirement daisy==4.0.127 (from versions: 0.1)
```

I suppose because it's preferring the _public_ daisy project in PyPI, which is a totally different project.

In case it's relevant, our devpi setup has a mirror of pypi included, although that's on a different URL (`{baseurl}/root/pypi/+simple/`) so I wouldn't expect it to be used. Looking at devpi's logs, I don't think it is used 👍 but I thought I'd mention it.

**Comment by craigds** [comment]
I should mention also that the `Only use this index (instead of augmenting the base PyPI index)` option doesn't appear to have any impact on this behaviour; I've tried both possibilities

**Comment by craigds** [comment]
any movement on this?

**Comment by craigds** [comment]
status: not fixed AFAIK though I haven't tested it in a while. We gave up on dependabot due to this and a couple other pip-compile-related issues, but would happily test again if there was some motion towards fixing this.

**Comment by rebelagentm** [comment]
@feelepxyz Do we have the ability to tell Dependabot to prefer a specific instance?

**Comment by feelepxyz** [comment]
Sorry for the slow response on this! We're been super busy integrating Dependabot at GitHub so many things have fallen through the cracks 😢 Could you set up a test repo with Dependabot using your private index? Would be super helpful to test against your setup as it might be an easy fix on our side.

**Comment by craigds** [comment]
I can't do a public repo with access to our private index, but perhaps a private repo is still useful? I can do that easily.

**Comment by craigds** [comment]
Not sure I'm doing it right. Created repos (dependabot IDs 540521 and 218154804). One's a real app with a pip-compile workflow, the other is a test repo with a minimal requirements.txt containing just the private daisy package that errored here before.

Clicking 'bump now' on either does _not_ result in any hits to our devpi server, but nor are there any linked logs or error messages. So I'm not sure what dependabot is doing.

**Comment by craigds** [comment]
I posted too early - the test repo with the minimal requirements.txt (218154804) _did_ work when I bumped it a second time, and submitted a PR for the correct version of daisy 👍 

No response from the pip-compile one yet (540521)

**Comment by craigds** [comment]
Any ideas with that one (540521) ?

**Comment by feelepxyz** [comment]
@craigds sorry for the delay! Done some digging and looks like we are not properly authenticating all requests to your devpi python index. I'm looking into it.

**Comment by feelepxyz** [comment]
@craigds think this is fixed now, successfully created a PR for daisy 🎉 will close this out. Let us know if you run into any further issues.
