### ISSUE TITLE
Ruby: tag-based upgrade regressed at v0.104.1

### ISSUE THREAD

**Issue by qnighy** [dependabot/dependabot-core#1217]
We use dependabot a lot in my company's private repositories, and it's very helpful in updating dependencies on public libraries. However, we're experiencing difficulties in upgrading in-company dependencies.

## Version

I've bisected using `dependabot-core` and I suspect the version `v0.104.1` is the point of regression.

## Reproduction

I've made a pair of small repositories for reproduction.

```
$ bin/dry-run.rb bundler qnighy/test_gem_2
```

In v0.104.0, `test_gem_1` is bumped.

```
=== test_gem_1 (a8c11a3c8b3dfc1ede2e6885395c3409d60975a6)
 => checking for updates
 => requirements to unlock own
 => updating to 9e643df696ba42e553d547fd596421410c22239f

    ± Gemfile
    ~~~
    5c5
    < gem 'test_gem_1', git: 'https://github.com/qnighy/test_gem_1.git', tag: 'v0.1.0'
    ---
    > gem 'test_gem_1', git: 'https://github.com/qnighy/test_gem_1.git', tag: 'v0.2.0'
    ~~~

    ± Gemfile.lock
    ~~~
    3,4c3,4
    <   revision: a8c11a3c8b3dfc1ede2e6885395c3409d60975a6
    <   tag: v0.1.0
    ---
    >   revision: 9e643df696ba42e553d547fd596421410c22239f
    >   tag: v0.2.0
    6c6
    <     test_gem_1 (0.1.0)
    ---
    >     test_gem_1 (0.2.0)
    ~~~
```

In 0.104.1, `test_gem_1` isn't bumped.

```
=== test_gem_1 (a8c11a3c8b3dfc1ede2e6885395c3409d60975a6)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)
```

**Comment by qnighy** [comment]
I've figured out why specs didn't work -- whether the gem is in the compact index matters. The specs mock responses for `/versions/business.json`, but don't mock responses for `/versions`.

**Comment by qnighy** [comment]
And `$HOME/.bundle/cache` being reused.

**Comment by greysteil** [comment]
Thanks for the detailed bug report here, and for the PR attempting to fix it.

Is the repo this is happening on using the hosted Dependabot app (i.e., https://dependabot.com)? If so, could you email support@dependabot.com with details of the repo and package name this is happening on? I'd like to take a quick look at an alternative fix and make sure it works.

**Comment by qnighy** [comment]
> Is the repo this is happening on using the hosted Dependabot app (i.e., https://dependabot.com)?

Yes.

I sent an email from ackie.h.gmai@gmail.com with relevant information.

**Comment by qnighy** [comment]
Any update on this?

**Comment by greysteil** [comment]
Just replied to your email with a clarifying question.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/f1f1ace673c214e20760153473582743ef343a9f. Thanks so much for reporting this, and for bearing with us!

**Comment by qnighy** [comment]
Thanks for fixing! It started to work again.
