### ISSUE TITLE
Python: Package variants break the parser

### ISSUE THREAD

**Issue by ginogravanis** [dependabot/dependabot-core#1220]
Required package variants like `requests[security]` aren't parsed correctly.

In the following example the dependency `click` is invisible to the setup file parser, because it stops at the first `]` it encounters:
```
install_requires = [
    "requests[security] == 2.0",
    "click == 6.0",
]
```

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/9f750f9478850a337c7e6427487df7aa5e182f26, which I'm deploying now.
