### ISSUE TITLE
docker: not fetching latest images

### ISSUE THREAD

**Issue by webratz** [dependabot/dependabot-core#1226]
We are using dependabot core to update docker images from an AWS ECR registry.
We noticed that the even there were newer images (image tags) availlable dependabot seems to think everything is fine.
After digging a bit further it turns out the response from ECR is paginated:
`https://123456789012.dkr.ecr.eu-west-1.amazonaws.com/v2/my-imgage-name/tags/list`
responds with a `Link` header.

From a first check it seems the used ruby library https://github.com/deitch/docker_registry2 does not support following those responses.
With that the response is not complete, dependabot never know about all the availlable latest tags

**Comment by greysteil** [comment]
Oh interesting! We should definitely fix that. `DockerRegistry2` is maintained by @deitch who is super responsive - would you be up for putting together a PR to it / raising it there?

**Comment by webratz** [comment]
as my ruby knowledge is very limited i'd just create the issue and hope for a fix from him ;)

**Comment by webratz** [comment]
created issue there: https://github.com/deitch/docker_registry2/issues/34

**Comment by LarsFronius** [comment]
https://github.com/deitch/docker_registry2/pull/35 has just been merged and pagination information is now available in the client.

**Comment by greysteil** [comment]
Nice! I've just submitted https://github.com/deitch/docker_registry2/pull/38, which will give us what we need for Dependabot. Once that's in I'll get us upgraded.
