### ISSUE TITLE
Support fetching versions from authenticated sources in Gradle

### ISSUE THREAD

**Issue by JimNero009** [dependabot/dependabot-core#1232]
Hi!

My team and I were playing around with dependabot the other day and were generally very impressed. One thing we did notice, however, is that there does not seem to be any functionality coded to make authenticated calls to a custom maven repository when running the bot for gradle files. This is an absolute must for what we would like to use it for and would even consider contributing the code ourselves if you were willing to accept it?

**Comment by greysteil** [comment]
Hi! Thanks for giving Dependabot a try.

We'd be delighted to accept a PR to allow Dependabot to handle custom maven repositories for gradle. The only reason we don't support it currently is that we didn't have any users to beta test it for us.

Hopefully the `Dependabot::Maven::UpdateChecker::VersionFinder` class provides what is needed here and can act as a good template?

**Comment by JimNero009** [comment]
Awesome! Yep, I'm sure we can suss it out. Thanks!

**Comment by jurre** [comment]
Thanks to @GeorgiosGoniotakis this should now work as expected 🥇
