### ISSUE TITLE
python latest version finder failing when additional metadata included in links 

### ISSUE THREAD

**Issue by michael-booth** [dependabot/dependabot-core#1236]
Hi!

Firstly thanks for all the work on dependabot it's great.
My team and I have been playing around with dependabot-core looking to hook it up to our internal artifactory instance which serves amongst other things pypi artifacts.
During testing we found some of our internal artifacts where not being picked up for bumping.
We tracked this down to `latest_version_finder.rb` (python) - where it [parses the html page to determine the available versions.](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/update_checker/latest_version_finder.rb#L156)

It appears the regex being used is not comprehensible enough for our use case. 
Some of the links which are parsed includes additional metadata in the tag which throws the regex
e.g.
```
<a data-requires-python=">=3.5.3" href="my_artifact-1.0.0.tar.gz" rel="internal" >my_artifact-1.0.0.tar.gz</a>
```

Note the `>=3.5.3`, the `>` causes the regex to match too early and fail to correctly find the version.

I believe this data is present as the artifact in question specifies the `python_requires=">=3.5.3"` property in setup.py.

In our local testing, we simply amended the code to be parsed with the `Nokogiri` library in order to correctly find the `a` text and removed the regex.

We are happy to contribute a fix to this but wanted to validate you agree it's a bug.

Thanks!

**Comment by greysteil** [comment]
Thanks for this. I think it should be fixed by [this commit](https://github.com/dependabot/dependabot-core/commit/e08d3afb3a36f1cb5b0bcc4588434768699fc1b8), which I'm releasing now.
