### ISSUE TITLE
Conda Environment Support

### ISSUE THREAD

**Issue by joshowen** [dependabot/dependabot-core#1249]
It would be very helpful if this supported Conda Environment files for Python environments.  Conda is used widely in the Python ecosystem: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Example Environment File:
https://github.com/enigmampc/catalyst/blob/master/etc/python3.6-environment.yml

I don't know much Ruby, but I'm happy to help however I can.

**Comment by rickard-von-essen-iz** [comment]
Still very much needed

**Comment by rebelagentm** [comment]
Sorry for the confusion!  We installed Stale to help manage our backlog and some issues got closed before I had the chance to triage them.

**Comment by Zethson** [comment]
Is there any progress on this issue?

**Comment by alexvicegrab** [comment]
Yes, this would be useful indeed

**Comment by ajschmidt8** [comment]
also think this would be a great addition

**Comment by RoyTrudell** [comment]
yes, this would help in my workflow also.

**Comment by infin8x** [comment]
Duplicate of #2227
