### ISSUE TITLE
Azure PR creation silently fails when permissions are missing

### ISSUE THREAD

**Issue by acraven** [dependabot/dependabot-core#1256]
If the `Create branch` permission is missing from the user (*1), the `create_commit` method (that calls the `pushes` API) fails. It returns a response object, but the `create_pull_request` method (*2) is still called and fails with a not found type error.

Would it be appropriate to throw an exception if either of these don't return a 2xx response?

*1 When running in Azure DevOps Pipelines, this was `Project Collection Build Service` for me.
*2 The `create_pull_request` method needs the `Contribute to pull requests` permission.

**Comment by greysteil** [comment]
Sure would be - I'd be happy for it to just raise a standard error with the response code and message. [This](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/clients/bitbucket.rb#L79-L85) is a good example of where we do that.
