### ISSUE TITLE
Java/Maven: Detect submodules declared in a profile

### ISSUE THREAD

**Issue by ThorbenLindhauer** [dependabot/dependabot-core#1263]
https://github.com/dependabot/dependabot-core/issues/222 added support for multi-module Maven projects which is great. It looks like submodules are only detected when the `modules` element is a direct child of `project` in `pom.xml`. In consequence, submodules that are included in profiles are not picked up, e.g.:

```xml
<project>
  ...
    <profiles>
        <profile>
            <id>multi-module</id>
            <modules>
                <module>util</module>
                <module>business-app</module>
                <module>legacy</module>
            </modules>
        </profile>
    </profiles>
  ...    
</project>
```

Example project: https://github.com/ThorbenLindhauer/maven-multimodule-sample

**Comment by greysteil** [comment]
Thanks for reporting! Fixed in https://github.com/dependabot/dependabot-core/commit/9860e2dd18521b7516d870225d19ac8edc0ec5b0, which I'll deploy later today.

**Comment by ThorbenLindhauer** [comment]
Awesome, thanks a lot!
