### ISSUE TITLE
Library is detected as application, package.json version is not widened

### ISSUE THREAD

**Issue by aiwilliams** [dependabot/dependabot-core#1264]
I cannot readily discover how Dependabot determines whether a project is a library or an application. What mechanism drives the `version_requirement_updates` decision? I'd like to avoid a config file and do not want to configure each project in the Dependabot UI, since Dependabot seems to be running against all GH projects now. If I can change something in the package.json so it knows it should widen the version in package.json, that would be great. Thanks!

**Comment by aiwilliams** [comment]
Seems I just needed a rubber 🦆 The `yarn.lock` is being changed because there is no direct `dependencies` in the `package.json`. Still, it would be nice to have docs indicate what makes for an app vs. library 😁

**Comment by greysteil** [comment]
Awesome. The code for doing that detection for JS is [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/library_detector.rb), btw.
