### ISSUE TITLE
No PRs opened for potential updates in requirements.txt

### ISSUE THREAD

**Issue by philippotto** [dependabot/dependabot-core#1271]
Hi there,

I hope this is the right place to open this issue. I configured dependabot to keep track of two python packages. See config [here](https://github.com/scalableminds/webknossos-cuber/blob/master/.dependabot/config.yml).

For example, the `requirements.txt` (see [here](https://github.com/scalableminds/webknossos-cuber/blob/master/requirements.txt)) demands `cluster_tools>=1.18
`, but [version 1.29](https://pypi.org/project/cluster-tools/) already exists. Why doesn't dependabot open a PR to bump this version? Explicitly clicking "bump now" does not help either.

Any help is very appreciated!

**Comment by greysteil** [comment]
Dependabot won't update that requirement because it already supports the latest version. If you instead pin it (i.e., `cluster_tools==1.18`) then Dependabot will create PRs to update it.

**Comment by philippotto** [comment]
Thanks for your fast response! However, I followed your suggestion to use `cluster_tools==1.18` and dependabot still doesn't open a new PR to bump to 1.27?

**Comment by greysteil** [comment]
Hmmm, it looks like Dependabot is normalising the name to `cluster-tools` and that's causing problems. Let me take a loook.

**Comment by greysteil** [comment]
This will be fixed by https://github.com/dependabot/dependabot-core/commit/2aef0dc5aa837c173d698687d9dc302e40376472, but it's going to take me 15 mins to get that deployed. Hand tight, and thanks for reporting this!

**Comment by greysteil** [comment]
Fixed!

**Comment by philippotto** [comment]
Awesome, thank you!
