### ISSUE TITLE
gitea / gogs support

### ISSUE THREAD

**Issue by alexanderadam** [dependabot/dependabot-core#1272]
It would be nice to have support for [gitea](https://gitea.io/en-us/) and [gogs](https://gogs.io/) (they share the same API afaik).

I guess another API client library like [`megam_gogs`](https://github.com/megamsys/megam_gogs.rb) or [a Swagger client](https://github.com/swagger-api/swagger-codegen#online-generators) for [the exposed API](https://try.gitea.io/api/swagger) would be required for that.

For others seeking dependency update support: you could use [renovatebot](https://github.com/renovatebot/renovate/issues/4042), for now.

**Comment by greysteil** [comment]
Happy to accept PRs for this, but the core team won't be undertaking this.

**Comment by alexanderadam** [comment]
No need to close it. I'm still interested in it. 😉

**Comment by infin8x** [comment]
Due to current resourcing, we're not accepting PRs on `dependabot-core`. However, we expect to accept PRs in the future and would be open to a PR to add this functionality. Closing this issue for now.

**Comment by alexanderadam** [comment]
But can't you keep this issue open even if you don't accept a PR right now?
This way other users can find and track this issue as well.
