### ISSUE TITLE
Puppet Dependency Support

### ISSUE THREAD

**Issue by jpogran** [dependabot/dependabot-core#1281]
I would like to submit a PR that introduces `Puppetfile` and `metadata.json` support to dependabot. I have working code for Puppetfiles, working on metadata.json next. I realize this is a completely new type of dependency, but hopefully the spec tests, code, and the following background prove this worthwhile. I would like to submit this as a WIP PR, and work to get it into a state to be approved if that is acceptable.

### Puppetfile

A [Puppetfile](https://puppet.com/docs/pe/2019.1/puppetfile.html) lists [Puppet module](https://puppet.com/docs/puppet/6.7/modules_fundamentals.html) dependencies for a Puppet environment.  Each module listed can be from the [Puppet Forge](https://forge.puppet.com/) or from a git reference. There is no lock file for a Puppetfile.

Accepted Puppet Forge module versions are `major.minor.patch` or `:latest` and the resolution strategy is exact match. The general update strategies 'update to latest major' and 'update to latest minor'. There are no ranges supported.

Git references are configurable to use a branch, commit, tag, or sha reference. Their version is evaluated at deployment time not in the Puppetfile. In general, it is not expected for an automated system to be able to 'update' a git reference.

The [Puppetfile](https://puppet.com/docs/pe/2019.1/puppetfile.html) is regarded as Ruby, so it allows data or Ruby code to be included, but is considered a code smell. This means that when it is parsed, it should be in a manner that does not execute untrusted code in the Puppetfile, but just parses the module lists.

### Puppet Modules

A Puppet Module [metatdata.json](https://puppet.com/docs/puppet/6.7/modules_metadata.html) lists required [Puppet modules](https://puppet.com/docs/puppet/6.7/modules_fundamentals.html) that are to be _installed_ with it in order for the module to function. There is no lock file for a metadata.json file.

The resolution strategy is modeled after Ruby gems, in that it supports ranges and exact matches. See the [requirements](https://puppet.com/docs/puppet/6.7/modules_metadata.html#specifying-puppet-version-requirements) section.

**Comment by greysteil** [comment]
I am 100% 👍on adding support for Puppet to Dependabot. I would love to help with putting together a PR.

What assistance do you need? Would it help if I put together a template PR, or are you already beyond that point?

One point to note is that the licensing on this repo is currently in flux (the intent of the license is unlikely to change, but GitHub / Microsoft want the option to change the implementation) so at some point I'll need you / Puppet labs to say you're signing over the IP for any contributions to Dependabot Core to Dependabot.

**Comment by jpogran** [comment]
Awesome! I want to clean up the commits a bit more, then I'll push a WIP PR up today.

Thanks for the offer of a template PR, but as you guessed I'm beyond that. I used the bundle, cargo and go_module providers as examples. However that does not mean I got any of it close to how you want things, only that `bin/dry-run` works and the `dependabot/dependabot-script` works to create a [PR](https://github.com/jpogran/control-repo/pull/3). There's still some work left to do for Puppetfiles and nothing done yet for metadata.json, but I have that much going. I do have some questions though. 

Regarding spec testing, specifically `vcr`. I see it's required for any tests that make http calls, but I only see `go_module` actually use it. Do I commit the vcr-cassette files or are they transitory files? Do you prefer instead I try to stub and mock out all the calls like the bundler provider does?

I intend for this to update Puppetfiles and metadata.json files, which are two different 'projects' for lack of a better term. Is it OK to have them both in one 'provider' called 'puppet'? Or should I be making two different 'providers'? Maybe I should ask for a template PR first, it's still early enough to move code and I want to get structure right.

I'll double check with legal, but normally Puppet employees allows OSS contributions without issue.

**Comment by greysteil** [comment]
Dashing to a meeting but:
1) I prefer webmock, but @hmarr prefers `vcr`. Take your pick 🤷‍♂ 
2) One provider called `puppet` makes sense if that's what users would expect when selecting what kind of update config they're configuring

**Comment by jpogran** [comment]
I put up the PR, sorry for delay things got busy.

**Comment by greysteil** [comment]
Nice! Closing this - let's continue to discussion on the PR (and sorry for the slow response  - was my birthday yesterday so had the day off).

**Comment by elfranne** [comment]
So #1287 has been closed due to various resource constrains, I also see that most of the involved parties have moved to other projects, 4-5 years have passed and probably a lot has changed in the dependabot code and how to integrate different systems... 

A fresh view on this would be greatly appreciated.

**Comment by genebean** [comment]
I was involved and interested back then and would still very much like to see this happen.

**Comment by aerickson** [comment]
> Nice! Closing this - let's continue to discussion on the PR (and sorry for the slow response - was my birthday yesterday so had the day off).

Reopen this since the PR has been closed? This is the one thing pushing me to Renovate.

The plugin/non-core approach mentioned on the PR sounds cool.
