### ISSUE TITLE
Do not use registry I set after I set `config.yml`

### ISSUE THREAD

**Issue by xPixv** [dependabot/dependabot-core#1305]
Hello there,
I've set JS registry in account - config-variables
![image](https://user-images.githubusercontent.com/9652227/62839026-fb6ff900-bcb6-11e9-8893-9bf5483a508e.png)
Also there is a `.yarnrc` file in my project
```text
registry "https://registry.npm.taobao.org"
disturl "https://npm.taobao.org/dist"
sass_binary_site "https://npm.taobao.org/mirrors/node-sass"
```

Then I config dependabot **in dashboard**.
It worked fine. And PR me a **correct** one with the registry I set.
![image](https://user-images.githubusercontent.com/9652227/62839073-c31cea80-bcb7-11e9-9cc6-027f4c0c85a8.png)

Hours later, I followed [dependabot doc](https://dependabot.com/docs/config-file/) and added a `.dependabot/config.yml` file.
![image](https://user-images.githubusercontent.com/9652227/62839101-1727cf00-bcb8-11e9-81f2-5572b1a6f8f7.png)

But it PR me a **wrong** registry :/
![image](https://user-images.githubusercontent.com/9652227/62839129-5e15c480-bcb8-11e9-92bf-30cbfbbe539f.png)

Did I miss something? o.O

I'm sorry to bother you. Thank you for your attention.

**Comment by greysteil** [comment]
Apologies for the slow reply here. Can you @-mention Dependabot in a PR that has done this wrong so we can  dig into it? Thanks!

**Comment by xPixv** [comment]
> Apologies for the slow reply here. Can you @-mention Dependabot in a PR that has done this wrong so we can dig into it? Thanks!

Sure. It is a private repo. PR: xPixv/WeAuth#2
![image](https://user-images.githubusercontent.com/9652227/63279493-a7c76600-c2db-11e9-856e-6af7cf5c4e49.png)
(BTW, if you do not have access to it, I'm willing to add you to collaborators)

The first commit did not respect the registry in `account - config-variables`.
![image](https://user-images.githubusercontent.com/9652227/62839129-5e15c480-bcb8-11e9-92bf-30cbfbbe539f.png)

Due to this glitch, and more important I love dependabot and I want to make my project up to date. So I have to change my registry to Yarn's default(registry.yarnpkg.org). Then recreate it and bump dependencies again. So the latest commit I merged was using registry.yarnpkg.com.
