### ISSUE TITLE
Dependabot Core "free license" for commercial project ?

### ISSUE THREAD

**Issue by Bertk** [dependabot/dependabot-core#1306]
The repository `README.md` has this statement:
>If you would like to add Dependabot's functionality to your for-profit company's offering then we DO NOT give you permission to use Dependabot Core to do so. Please contact us directly to discuss a partnership or licensing arrangement.

The [license file](https://github.com/dependabot/dependabot-core/blob/master/LICENSE) also has this section.
>This license lets you use and share this software for free, with a trial-length time limit on commercial use

but here [Dependabot is joining GitHub](https://dependabot.com/blog/hello-github/)  I find
>Dependabot is now free. You'll no longer be billed for it, and if you paid for future months, we'll be in touch to refund you.

Please clarify the different statements. I am not sure whether I can use  `Dependabot Core` for my Azure DevOps project.

**Comment by greysteil** [comment]
The key statement on `dependabot-core` licensing is the README. The license is a close approximation to implement that - you're welcome to use `dependabot-core` for your Azure DevOps project, as long as you're planning to use it to bump only your own / your company's repos (not to provide it as a service to others).

**Comment by jeffwidman** [comment]
See also https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100
