### ISSUE TITLE
python3.7.4 support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#1307]
Dependabot cannot resolve dependencies for `python3.7.4`. Because:

> Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000056434cb8eb48 @requirements=[["=", #<Dependabot::Python::Version 3.7.4>]]>]]'.

> Currently, the following Python versions are supported in Dependabot: 3.8-dev, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, 2.7.16, 2.7.15, 2.7.14, 2.7.13.

But, it is released: https://www.python.org/downloads/release/python-374/
Original issue: https://github.com/wemake-services/wemake-django-template/issues/863

**Comment by greysteil** [comment]
Good point. Will be fixed by https://github.com/dependabot/dependabot-core/commit/cfb884dfb2adb3b497b1942724f3610751c7dbb8.

**Comment by greysteil** [comment]
New version is released so I'm closing this. Will be deployed in the next hour. Thanks for the heads up!
