### ISSUE TITLE
Host name for Github Enterprise not in configured known hosts

### ISSUE THREAD

**Issue by juanjoqmelian** [dependabot/dependabot-core#1344]
The problem we're having is that it seems that the GitMetadataFetcher is configured to only accept some known hosts:

https://github.com/dependabot/dependabot-core/blob/61cba023cc91bbba66d7d55b50d080fac603f342/common/lib/dependabot/git_metadata_fetcher.rb#L8

Raising an exception if it doesn't match:

https://github.com/dependabot/dependabot-core/blob/61cba023cc91bbba66d7d55b50d080fac603f342/common/lib/dependabot/git_metadata_fetcher.rb#L57

Our Github Enterprise url doesn't match with those, is there any reason for that?

Our company's host is something like `github.*.company.org`

**Comment by greysteil** [comment]
Hmmm, that shouldn't be causing issues, but it might be masking them.

The `KNOWN_HOSTS` constant is only used in error handling. Basically, if Dependabot sees a non-200 response (after following redirects) from a host that isn't one of the above, it give up and raises a `Dependabot::GitDependenciesNotReachable` error. Presumably that's what's happening in your case, and the thing to understand is why a non-200 response is being raised.

Can you give any more  context on where in the update run script this error is occurring? A backtrace would be great. I'd also recommend adding some logging to see what response is coming back from your server.

I'm going to close as I'm pretty sure this is going to turn out to be an auth issue with your GHE setup, but happy to answer any more questions if I can help.
