### ISSUE TITLE
rust/cargo: "default-run target not found" with implicit bin targets

### ISSUE THREAD

**Issue by kolen** [dependabot/dependabot-core#1352]
I have repository with Cargo project which causes this error: https://github.com/kolen/mm_map_tools/issues/30.

```
error: failed to parse manifest at `/home/dependabot/dependabot-updater/dependabot_tmp_dir/Cargo.toml`

Caused by:
  default-run target `viewer` not found

```

There's [`default-run = "viewer"` option in `Cargo.toml`](https://github.com/kolen/mm_map_tools/blob/5ea5b8e76ce794a4819f4f0d36e3e8985f85a1a9/Cargo.toml#L5), and `viewer` target is not specified in `Cargo.toml`, it's implicitly defined by presence of [`src/bin/viewer.rs` file](https://github.com/kolen/mm_map_tools/blob/master/src/bin/viewer.rs).

This works with standard Cargo tooling (locally on my machine and on CI), but fails with custom logic in Dependabot, which probably does not checkout full repository and therefore does not have `src/bin/viewer.rs`, or by some other reason.

`default-run` is recent functionality appeared in Rust 1.37.

**Comment by greysteil** [comment]
Thanks for reporting this. Should be fixed by https://github.com/dependabot/dependabot-core/commit/2dce536ad04bc0d24c8461df4e687e5eb519e8e8, which I'll get deployed this evening.
