### ISSUE TITLE
Custom security label

### ISSUE THREAD

**Issue by roblabla** [dependabot/dependabot-core#1358]
I don't see any way to configure the `security` label that gets applied automatically for security-critical PRs. I'd like to rename it to `safety` to match my existing labels. Am I missing something?

**Comment by greysteil** [comment]
We don't have a way to configure that label at the moment, and this is the first time it's been requested. It's certainly something we could add in future, but our immediate roadmap is packed pretty full with scaling.

**Comment by infin8x** [comment]
Closing this as GitHub-native Dependabot no longer adds a `security` label and instead shows a note to authorized users that the PR in question is a security PR.
