### ISSUE TITLE
Support multiple properties (maven, gradle, nuget)

### ISSUE THREAD

**Issue by NargiT** [dependabot/dependabot-core#1370]
Hello,

I noticed that in maven/gradle and nuget manifest there are no support for multi dependency property `version_comes_from_multi_dependency_property?`.

I do not know who nuget manifest works but in maven and gradle ecosystem, when a project uses a property to define version of different libraries, it's because all the libraries have the same release lifecycle. There a new version of one will generate a new version for the other one. The only case it does not work it's when the project is misconfigured.

So I would like to propose to add a configuration to open instead open 1 PR for the group of libraries using the property name.

**Comment by greysteil** [comment]
I'm pretty sure that's exactly what happens - what makes you think otherwise?

**Comment by NargiT** [comment]
I ran the update-script.rb and this piece of code is always sending false.

```
      def latest_resolvable_version
        # Maven's version resolution algorithm is very simple: it just uses
        # the version defined "closest", with the first declaration winning
        # if two declarations are equally close. As a result, we can just
        # return that latest version unless dealing with a property dep.
        # https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies
        return nil if version_comes_from_multi_dependency_property?
        
        latest_version
    end
```
dependabot-maven-0.112.32/lib/dependabot/maven/update_checker.rb
but I am using the update-script.rb from dependbot-script, not public dependabot because I am in an entreprise context.

**Comment by greysteil** [comment]
The method you need here is `latest_version_resolvable_with_full_unlock?`. That's not used in the update script, but it is what Dependabot's hosted version runs. I'm happy to accept PRs on the update script to improve it, but don't want that script to get *too* complicated.

**Comment by NargiT** [comment]
> dependabot-maven-0.112.32/lib/dependabot/maven/update_checker.rb

The code snippet I used is actually from dependabot-core and dependabot-maven logic. `update-script.rb` 
```ruby
# where dep and files are correctly configured
checker = Dependabot::UpdateCheckers.for_package_manager(package_manager).new(
    dependency: dep,
    dependency_files: files,
    credentials: @credentials
)
updated_deps = checker.updated_dependencies(requirements_to_unlock: :own)
```

I do belive that there is something that I am missing.  Here you can find the stack of calls.

![stack](https://user-images.githubusercontent.com/3153333/64405255-d3d63b80-d07e-11e9-86d1-af30119b93ce.png)

**Comment by greysteil** [comment]
Cool -  the trouble here is that you need to change `(requirements_to_unlock: :own)` to `(requirements_to_unlock: :all)` (because doing this update requires updating more than one dependency at once).

**Comment by greysteil** [comment]
More generally, please remember that Dependabot Script is really only provided as an example of how to use Dependabot Core to implement basic Dependabot-like functionality locally. It isn't as fully featured as the Dependabot app and isn't intended to be something that works out of the box for complex use cases.

**Comment by NargiT** [comment]
I see, `:own` is only used for unique dependency update whereas `:all` works for multiple one.
Thx, now it's more clear. I was able to make it work as expected.

It's just hard to figure how to provided some feature available in dependabot app from raw dependabot-core.
