### ISSUE TITLE
Sometimes the package.json is not upgraded

### ISSUE THREAD

**Issue by marco-carvalho** [dependabot/dependabot-core#1382]
I have several repositories that use Dependabot to updated the package.json/package-lock.json, but some repos like [this](https://github.com/marco-carvalho/csg/pulls) only update the package-lock.json and I can't understand why. 
Why this is happening?

**Comment by feelepxyz** [comment]
@marco-carvalho 👋 your `csg` project is being detected as a library and therefore we try to widen the version requirements in `package.json` and in your case for the updates that are open the version requirement from your `pacakge.json` doesn't need to be updated to match the new version (for example `eslint ^6.2.2` matches the new version `6.3.0 `). When detected as an application that isn't published to npm it will always increase the version in your `package.json` to match the lockfile version.

This is being detected by checking your `package.json` which looks like a published library, you could change this by adding `private: true`, e.g. like you've done here: https://github.com/marco-carvalho/calculadora-juros-compostos/blob/master/package.json#L4 

You can also change this update strategy in your [dependabot dashboard](https://app.dependabot.com/):
<img width="666" alt="Screenshot 2019-09-16 at 09 50 45" src="https://user-images.githubusercontent.com/20165/64944998-8e2c2680-d867-11e9-96e7-029695bf0099.png">

**Comment by marco-carvalho** [comment]
thank you for the feedback @feelepxyz
