### ISSUE TITLE
Dependabot undo ignore minor version

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dependabot/dependabot-core#1384]
Hi,

I've accidentally ignored the wrong dependency, how can I unde this action?

**Comment by feelepxyz** [comment]
@alexandru-calinoiu sorry for the slow response! No easy way to undo but can sort it out for you. Which pull request did you issue the command on?

**Comment by villelahdenvuo** [comment]
@feelepxyz Is there still no way to unignore dependencies? I accidentally ignored all versions and not the major versions.

**Comment by feelepxyz** [comment]
@villelahdenvuo you should be able to re-open the pull request and this will remove any ignore conditions created for the updated dependency. I don't think it's documented anywhere 😅

**Comment by walro** [comment]
> I don't think it's documented anywhere

As I jus tfound out myself, at https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#creating-ignore-conditions-from-dependabot-ignore it states:

> If you wish to un-ignore a dependency ignored this way, re-open the pull request.

**Comment by wheeler** [comment]
It's really frustrating that this `@ignore` experience is not easy to manage. It states clearly that you can clear the ignore if you `... re-open this PR or update to a 5.x.x release yourself.`. The latter seems to be the most logical resolution but in my experience it doesn't always work. Then you're stuck with the very unintuitive task of finding and reopening an old PR.

I'm stuck in a catch-22 now where the old PR cannot be reopened for an unrelated reason (root branch was renamed).

Additionally there is no easy way to "list" what ignores are currently active other than crawling through the detailed dependabot execution logs *sigh.

**Comment by andrii-kovalenko-celonis** [comment]
now there is  `@dependabot unignore`
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#ignoring-specific-dependencies-for-dependabot-version-updates

**Comment by HaraldNordgren** [comment]
Dependabot is awesome, but it's also very frustrating to use sometimes!

**Comment by jeffwidman** [comment]
For anyone who stumbles across this through search, here's some more recent docs breadcrumbs:
* https://github.blog/changelog/2023-08-10-ignore-or-unignore-updates-for-grouped-dependabot-pull-requests/
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates
