### ISSUE TITLE
Dependabot thinks a dependency is not used anymore

### ISSUE THREAD

**Issue by bhathiya** [dependabot/dependabot-core#1386]
In the following PR, @dependabot-bot says `Looks like these dependencies are no longer a dependency, so this is no longer needed.`.

https://github.com/wso2/product-apim/pull/4228

But that dependency is used. See [1]. Any idea why the bot can't see it?

_[Note: this has been closed before and reopened recently. Now it's using a lower dependency range than earlier (6.x instead of 7.x). Maybe that's the reason?]_

[1] https://github.com/wso2/product-apim/blob/master/pom.xml#L571

**Comment by bhathiya** [comment]
umm.. so is this not going to be fixed? :-/

**Comment by de-code** [comment]
This happened for me as well in [this PR](https://github.com/elifesciences/sciencebeam-airflow/pull/43), the requirements.prereq.txt file hadn't changed at all after rebase. Still showing `apache-airflow[crypto,celery,ssh]==1.10.5`

**Comment by deivid-rodriguez** [comment]
This issue is older but let's close this in favor of #2522 since there's a repro in our own repository there that can help us track this down. Please subscribe to that issue for updates!
