### ISSUE TITLE
PR rebasing by bot is stuck

### ISSUE THREAD

**Issue by bhathiya** [dependabot/dependabot-core#1389]
The following 2 PRs are waiting to be rebased/updated but it seems that it's not going to happen any sooner. 

https://github.com/wso2/carbon-apimgt/pull/6443
https://github.com/wso2/product-apim/pull/4991

@greysteil What do you think is the reason?  

Thanks in advance.

**Comment by greysteil** [comment]
One of those is merged and the the other is closed - it would be nice if Dependabot would update the PR text in those cases, but it currently just leaves them be.

**Comment by bhathiya** [comment]
Today, I closed/merged them. I found it was stuck because of a merge conflict. I resolved it myself and merged. 

Thanks for the response.
