### ISSUE TITLE
NPM / Yarn support does not respect registries for scoped packages in .npmrc

### ISSUE THREAD

**Issue by charleskorn-x** [dependabot/dependabot-core#1396]
We have an `.npmrc` in our project that looks like this:

```
@mycompany:registry=https://artifactory.mycompany.com/api/npm/npm
registry=https://artifactory.mycompany.com/api/npm/npm-upstream
```

When we run the script from `dependabot-scripts` on our project, it correctly updates all non-`@mycompany` dependencies, but fails to update `@mycompany` dependencies. 

The process fails with error messages like these:

```
The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): artifactory.mycompany.com/api/npm/npm-upstream
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:316:in `check_npm_response'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:267:in `npm_details'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:95:in `valid_npm_details?'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:35:in `latest_version_from_registry'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker.rb:164:in `latest_released_version'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker.rb:191:in `latest_version_details'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.111.59/lib/dependabot/npm_and_yarn/update_checker.rb:22:in `latest_version'
/usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/update_checkers/base.rb:197:in `numeric_version_up_to_date?'
/usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/update_checkers/base.rb:155:in `version_up_to_date?'
/usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
update.rb:96:in `block in <main>'
update.rb:83:in `each'
update.rb:83:in `<main>'
```

As you can see in the error message there, it looks like Dependabot isn't considering the registry for the scoped package in our `.npmrc` and is instead using the default registry we've defined. Is there something we need to do to get this working, or is this an issue in Dependabot?

**Comment by feelepxyz** [comment]
@anotherxdeveloper 👋 have you passed both registries with credentials?

You need to add the artifactory credentials here: https://github.com/dependabot/dependabot-script/blob/master/update-script.rb#L17-L23

```
credentials =
  [{
    "type" => "git_source",
    "host" => "github.com",
    "username" => "x-access-token",
    "password" => "a-github-access-token"
  }, {
     "type" => "npm_registry",
     "registry" => "artifactory.mycompany.com/api/npm/npm",
     "token" => "token"
  }, {
     "type" => "npm_registry",
     "registry" => "artifactory.mycompany.com/api/npm/npm-upstream",
     "token" => "token"
  }]
```

**Comment by anotherxdeveloper** [comment]
Hi @feelepxyz, the private registry doesn't require authentication - it looks like Dependabot is incorrectly using the upstream registry (artifactory.mycompany.com/api/npm/npm-upstream) when asking for `@mycompany` packages when it should be using the internal package registry that we've defined in our `.npmrc` for `@mycompany` packages (artifactory.mycompany.com/api/npm/npm). I've debugged the code and `curl`ed the endpoint it's using, and it returns a 404 because the internal package doesn't exist in the upstream registry. Modifying the URL it's using to use the correct registry returns a reasonable-looking response and doesn't require authentication. 

Non-`@mycompany` packages available in the upstream repository work fine.

**Comment by feelepxyz** [comment]
Oh I see. Unfortunately not going to be able to provide much support for
private auth using Dependabot script 😢 Would need access to some
reproducible manifest file where you’re seeing this issue. You could email
support@dependabot.com if you want to send anything over.

I’m guessing it’s something being picked up from your lockfile. I would
check all scoped packages are resolved from the right registry url in your
lockfile.

**Comment by anotherxdeveloper** [comment]
Here's a snippet of our `yarn.lock` (albeit anonymised):

```
"@mycompany/mypackage@^2.4.4":
  version "2.4.4"
  resolved "https://artifactory.mycompany.com/api/npm/npm/mypackage/mycompany-mypackage-2.4.4.tgz#snipped"
  integrity sha1-snipped

"react@^15.6.1 || ^16.0.0", react@^16.4.2, react@^16.9.0:
  version "16.9.0"
  resolved "https://artifactory.mycompany.com/api/npm/npm-upstream/react/-/react-16.9.0.tgz#40ba2f9af13bc1a38d75dbf2f4359a5185c4f7aa"
  integrity sha1-QLovmvE7waONddvy9DWaUYXE96o=
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.2"
```

We're able to get dependency updates for React correctly, but we see the error message I originally posted when it tries to find updates for `@mycompany/mypackage`.

**Comment by feelepxyz** [comment]
@charleskorn-x 👋 could you put together a minimal test case using your private registry and install [Dependabot Preview](https://github.com/marketplace/dependabot-preview) on that repository? We could then easily debug this for you and see what Dependabot is doing on your setup.

**Comment by charleskorn-x** [comment]
@feelepxyz unfortunately it's an internal GitHub Enterprise instance so I can't - is there any information from our setup I can share with you?
