### ISSUE TITLE
Approving PR causes Dependabot to automatically merge

### ISSUE THREAD

**Issue by DouglasBlumeyerOmadaHealth** [dependabot/dependabot-core#1403]
I cannot find any documentation that this is expected behavior, or any documentation about how to configure it using the `.dependabot/config.yml` file.

My team will not be able to use Dependabot if this is the case. We have a company policy that requires human names attached to all commits. We need to make sure Dependabot's PRs get merged manually.

**Comment by jacobpgn** [comment]
Hey @DouglasBlumeyerOmadaHealth! I think that's something set on the account level, not in per-project config – head to https://app.dependabot.com/, click the drop-down in the top right then head to Settings. It's there as "Treat PR approval as a request to merge".

**Comment by DouglasBlumeyerOmadaHealth** [comment]
Great, thanks Jacob!
