### ISSUE TITLE
Support for React Native updates

### ISSUE THREAD

**Issue by PombeirP** [dependabot/dependabot-core#1425]
I have an interesting - and I imagine, common - scenario where I've added a Javascript dependabot watcher on a React Native repo, but when a 3rd party package like `react-native-camera` gets updated, the iOS `Podfile.lock` which [also references](https://github.com/status-im/status-react/blob/f34012a8154a515f002b8db39526e654e4755446/ios/Podfile.lock#L134) the Node.js package doesn't get updated at all. Maybe we could have a special React Native updater which would also run `pod install` to update the `Podfile.lock` file?

**Comment by feelepxyz** [comment]
@PombeirP thanks for the suggestion! Cocoapods support was started here https://github.com/dependabot/dependabot-core/pull/731 but currently on hold. We'll probably not add special cases for packages across packages managers but you could work around this by building your own GitHub action to run `pod install` based on pull requests opened by Dependabot.

**Comment by IgorGanapolsky** [comment]
Is dependabot working for React Native in 2024?
