### ISSUE TITLE
Custom gradle dependencies file name

### ISSUE THREAD

**Issue by rosolko** [dependabot/dependabot-core#1428]
Hi there.

For first, thanks for great tool! 
For second - can you please help with some problem?

In project [selenide](https://github.com/selenide/selenide) we are using separate file where we describe all project dependencies and place it in `/gradle/dependencies.gradle` folder and then include it in main `build.gradle`. But unfortunately now dependabot can check updates only from main gradle file.

Trying to additional `gradle` directory for update checker but got an issue https://github.com/selenide/selenide/issues/984 - that `/build.gradle` file is missing.

Can you please add an ability to specify custom file name with gradle dependencies or check all files with `.gradle` extension for updates?

Thanks!

**Comment by romainpiel** [comment]
👋 I too would love to use dependabot but I can't because of the way it parses the dependencies. Large Gradle projects use separate `dependencies.gradle` files or some others have them specified in buildSrc.
I think a more solid way to parse the dependencies would be to either have a Gradle plugin or to parse the output of `gradle dependencies`.

**Comment by rosolko** [comment]
Hi, @feelepxyz, can you please tell me, are there any updates in this issue?

**Comment by feelepxyz** [comment]
@rosolko hey sorry for the hiatus. We're working on integrating Dependabot natively into GitHub so have had to pause on most product improvements due to a small team size. We're hopefully getting back on top of things in a few months.

**Comment by androideveloper** [comment]
Any updates on this? 
In our case the setup is` dependencies.gradle` file in the root folder, but the structure of the file is 

```
ext {
    kotlinCoroutines = [
            core   : "library:$coroutines_version",
            rx2    : "library:$coroutines_version", 
            android: "library:$coroutines_version"
    ]
}
```

Dependabot doesn't check any of these libraries. How can we make it work?

**Comment by morantavori** [comment]
Any updates on this?
We also have a separate `dependencies.gradle` file in the project root.

**Comment by zbynek** [comment]
@asoIntsev simple `apply from:` should work, try replacing
```
apply from: rootProject.file('gradle/dependencies.gradle')
```
with
```
apply from: 'gradle/dependenies.gradle'
```
The included filename must contain the word `dependencies`.
@morantavori which project did you try to update?
