### ISSUE TITLE
"Can't resolve your JavaScript dependency files" - for "npm link"ed package

### ISSUE THREAD

**Issue by PzYon** [dependabot/dependabot-core#1439]
I'm using an npm package that I maintain myself and that is only used for my one specific [project](https://github.com/PzYon/engraved). It contains code that is shared between the server and the client. I do not want to publish it to npm, because
- Nobody else will use it.
- It makes it much easier for me to do the development, CI and CD by simply "npm link"ing it without always having to publish a new version to npm. I also use "npm link" to execute the unit tests in GitHub actions and to build it on heroku.

Problem is that apparently the depandabot [cannot deal with this](https://github.com/PzYon/engraved/issues/96). I understand that it doesn't work because obviously that version isn't published in npm. However it would be great if I could still use depandabot.

Possible solutions could be to
- provide a config option of packages to exclude
- provide a config option to skip errors or something like that

Does that make any sense? Or am I on the wrong path with using "npm link" as I do anyways?

**Comment by feelepxyz** [comment]
@PzYon 👋 good spot, this is currently unsupported in Dependabot and probably will be for a while because we always try and resolve your manifest + lockfile to make sure we haven't broken anything in the update and this fails if we haven't done the appropriate links. You can work around this using a file import, something like: `file:../shared`. Let me know if that doesn't work for you.

**Comment by PzYon** [comment]
Excellent. Thanks a lot for your quick reply. Just tried it out and it works. Plus it also makes my setup simpler and the execution of CI- and CD-task faster. 👍 

Does that mean Dependabot simply ignores those packages (well, what else should it do anyway?).

**Comment by feelepxyz** [comment]
@PzYon nice one! Dependabot will make sure your `file:` requirements resolve to files on your repo but other than that it won't do anything with these dependencies.
