### ISSUE TITLE
PR name suffix configuration

### ISSUE THREAD

**Issue by ndench** [dependabot/dependabot-core#1446]
From [the documentation](https://dependabot.com/docs/config-file/#commit_message), it's possible to add a custom prefix to commit messages and PR names. It would be nice to add the ability to have a custom suffix as well.

For example, we suffix all PR names with the support request ticket number (this is different from the github issue number which we add in the PR description). This then allows us to use scripts to parse commit messages in master and automatically extract which support requests are closed in a release.

However, not all PRs actually close a support request. So we have a static string that is appended to every PR name that does not close a support request.

I'm sure there are many other use cases and commit message conventions that require commit message suffixes too.

**Comment by rebelagentm** [comment]
👋 Thanks for submitting this suggestion!  The team is heads down scaling Dependabot for all of GitHub :octocat:, so, unfortunately, it may be a while before we can get to adding new features like this.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by TheRealWaldo** [comment]
This is critical to being able to use dependabot with a commit messaging (or PR naming) standard requiring prefixes instead of suffixes, or combinations of prefixes and suffixes (as such is the case with many of my clients).

Also see #2091

**Comment by milkcask** [comment]
We need this for certain automation fine-tuning, eg a `[skip ci]` tag.
