### ISSUE TITLE
Handle .nvmrc

### ISSUE THREAD

**Issue by dbrgn** [dependabot/dependabot-core#1462]
Dependabot currently does not consider an `.nvmrc` file. The result is a change in how the `package-lock.json` looks, because a different NodeJS version was originally used to generate the lockfile: https://github.com/gfroerli/web/pull/55/files

These `optional` fields will be removed again in the next PR that touches the `package-lock.json` file when using Node 10 (as specified in `.nvmrc`), causing a lot of unnecessary back-and-forth changes.

Could dependabot run `nvm use` in the project directory if an `.nvmrc` file is found, prior to running the updates?

Related: #1455

**Comment by feelepxyz** [comment]
@dbrgn we currently only run using the latest stable version of node and npm. I believe the `optional` flapping is due to the npm version used which was an issue in an old version. Which version are you using?

**Comment by dbrgn** [comment]
We used Node 10 (through `.nvmrc`) because one of the packages used was not compatible with Node 12. This will be solved eventually, but the issue that `package-lock.json` format changes in some way will probably happen again in a future version.

**Comment by feelepxyz** [comment]
@dbrgn we're also on Node 10 but use npm version `6.10.3`, could you try installing the specific npm version: `npm install -g npm@6.10.3` (the latest version `6.12.0` should also work fine but caused some issues for the way Dependabot uses it so we're holding off on updating).

**Comment by dbrgn** [comment]
Oh, I thought that npm is always bundled with node. Is that not the case?

If they are not bundled, then this issue can probably be closed, since one can use Node 10 with the latest npm.

**Comment by feelepxyz** [comment]
@dbrgn it's always bundled but might be an out of date version which had a bug causing lockfiles to change between linux and mac installs. Will close this out as we don't currently plan on supporting multiple node versions unless this becomes necessary.
