### ISSUE TITLE
Support Gradle updates that use dependencies on GitLab

### ISSUE THREAD

**Issue by rebelagentm** [dependabot/dependabot-core#1467]
See this [PR](https://github.com/dependabot/dependabot-core/pull/1434) and its comments for more context.

**Comment by zbynek** [comment]
@rebelagentm with #1434 merged, is there a reason for this issue to be open? (Same for #1468 and #1466)

**Comment by rebelagentm** [comment]
@zbynek These can probably be closed, but I'm no longer working on Dependabot, so I'll defer to @asciimike.

**Comment by asciimike** [comment]
Closing per https://github.com/dependabot/dependabot-core/issues/1467#issuecomment-927323527
