### ISSUE TITLE
Mix of docker tags for the same image and file results in missed dependency updates

### ISSUE THREAD

**Issue by michael-booth** [dependabot/dependabot-core#1479]
Firstly, thank you for dependabot! - we've been making use of dependabot-core on our Github enterprise instance and it's been great.

We have found the following issue:

Given a Dockerfile which has multiple FROM lines each with the same image **but** different tags.

```Dockerfile
FROM node:10.9.2-alpine AS BUILD

WORKDIR /application

FROM node:10.9.1-alpine AS ANOTHERBUILD

RUN echo "hi dependabot!"

FROM node:10.9.2-alpine

ENTRYPOINT ["/dependabot/node_modules/.bin/dependabot"]
```

Dependabot will only update image tags which match the first found version (in the case above 10.9.2-alpine) and will not apply updates to any other versions (e.g. 10.9.1-alpine)

The resulting diff of a for the file above is:
```diff
    ± Dockerfile-example
    ~~~
    1c1
    < FROM node:10.9.2-alpine AS BUILD
    ---
    > FROM node:13.0.1-alpine AS BUILD
    9c9
    < FROM node:10.9.2-alpine
    ---
    > FROM node:13.0.1-alpine
    ~~~
```

It appears this happens as currently only the first previous tag is retrieved for replacing in a file rather than taking them all into consideration https://github.com/dependabot/dependabot-core/blob/master/docker/lib/dependabot/docker/file_updater.rb#L122.

I wanted to check that this wasn't expected behaviour or just a missed use case?

We have a patch on our fork of dependabot-core which retrieves all previous tags for a dependency in a file and iterates over them to mutate the target file. I'm happy to open a PR for this issue if you think it's valid.

**Comment by rebelagentm** [comment]
👋 We're glad you're enjoying Dependabot!

I think this is a limitation of the way that we currently have our file parsing implemented.  @feelepxyz, can you confirm I am correct?

We're certainly open to PRs!  We're pretty swamped right now, but we'd be happy to review any PRs as soon as we can.

**Comment by feelepxyz** [comment]
@rebelagentm oh yeah, might be related but haven't had a chance to dive into the code yet. @michael-booth would love any help fixing this, most certainly a use case we've missed in the implementation 🙌

**Comment by michael-booth** [comment]
PR raised to try and address this issue!
