### ISSUE TITLE
Dashboard continually shows "‎checking now, hold tight!"

### ISSUE THREAD

**Issue by mkrump** [dependabot/dependabot-core#1489]
I setup a test repo to experiment with Dependabot preview at https://github.com/mkrump/depupdate-test. The repo shows up in the dashboard, but I'd expect a single update when the job eventually runs, but the dashboard continually shows 

> ‎checking now, hold tight!

if I "Bump now", nothing happens. Is this something with my setup?

**Comment by mkrump** [comment]
nvm. looks like it finally ran.

**Comment by rebelagentm** [comment]
👋 Our queue had been a bit backed up, so that may have been the reason.  It should not normally take that long.  Let us know if you run into this again.  Thank you!
