### ISSUE TITLE
Python3.7.5 support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#1491]
Dependabot says that `python3.7.5` is not supported. 
https://github.com/wemake-services/wemake-django-template/issues/940

But, it should be: https://www.python.org/downloads/release/python-375/

**Comment by hmarr** [comment]
Thanks for reporting! Looks like we needed to pull in the new version of pyenv, which I've done in #1492. Hopefully we can make this automatic in the future, or perhaps convince a dependable robot to do it for us ;-)
