### ISSUE TITLE
Missing changelog for monorepo

### ISSUE THREAD

**Issue by frangio** [dependabot/dependabot-core#1494]
Updates for the NPM package `truffle` are not showing a Changelog section. I suspect this is because it's a monorepo.

Example PR: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1982.

The package repo does have [release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.0.43) for the version tag. I haven't dug into how the changelog is picked up but it sounds like it should be possible to do in this case.

**Comment by rebelagentm** [comment]
Thanks for submitting this!  We'll look into it as soon as we can.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by robin-awx** [comment]
we have the same issue
