### ISSUE TITLE
Duplicated dep with different versions

### ISSUE THREAD

**Issue by crazy-max** [dependabot/dependabot-core#1498]
Hi,

I have 2 PRs for the same dependency and different versions and I would like to know if it's possible for dependabot to close or update the old one instead?

Here is an example: https://github.com/crazy-max/ddns-route53/pulls

![image](https://user-images.githubusercontent.com/1951866/68206841-00023000-ffce-11e9-8150-a42b08f28dde.png)

Config: https://github.com/crazy-max/ddns-route53/blob/master/.dependabot/config.yml

Thanks!

**Comment by rebelagentm** [comment]
Interesting.  I thought that Dependabot should close the old one automatically.  @feelepxyz, is there a setting that needs to be turned on?

**Comment by crazy-max** [comment]
@rebelagentm That's strange, I just receive this notification of dependabot:

> [@dependabot-preview[bot]](https://github.com/dependabot-preview) pushed 1 commit.
> 
>  [375e923](https://github.com/crazy-max/ddns-route53/commit/375e9231f924754a79781b4f34077ad37bb1062f) Bump github.com/aws/aws-sdk-go from 1.19.41 to 1.25.23

And looks like commit [375e923](https://github.com/crazy-max/ddns-route53/commit/375e9231f924754a79781b4f34077ad37bb1062f) has bumped 1.25.23 to 1.25.26 on the old PR.

Aye you currently working on it guys? :smiley:

**Comment by feelepxyz** [comment]
@crazy-max sorry about this! Looks like we lost track of the newer PR: https://github.com/crazy-max/ddns-route53/pull/10

We recently had an outage that meant jobs got queued for a long time and we lost a few jobs in the process of fixing the outage. You'll have to close the newer one manually (https://github.com/crazy-max/ddns-route53/pull/10). We should pick this up in the future. I think our logic got confused with the existing PR causing the old one to be updated instead of super-seeded as we normally do (hence the pr body and title still mentioning the old version).

**Comment by feelepxyz** [comment]
> Aye you currently working on it guys? 😃

Yup just triggered a recheck on your PRs which caused the update.

**Comment by crazy-max** [comment]
@feelepxyz 

> sorry about this! Looks like we lost track of the newer PR: crazy-max/ddns-route53#10

Don't be sorry, you're doing a great job :)

> We recently had an outage that meant jobs got queued for a long time and we lost a few jobs in the process of fixing the outage.

Oh, I was just about to tell you about the incident "increase in queue backlogs" I received earlier from GitHub Status.

> We should pick this up in the future. I think our logic got confused with the existing PR causing the old one to be updated instead of super-seeded as we normally do (hence the pr body and title still mentioning the old version).

Yes that's right.

I'll keep you informed if I have any other issues.

Keep it up guys!

**Comment by feelepxyz** [comment]
@crazy-max nice one! Will close this out in that case, let us know if anything crops up!
