### ISSUE TITLE
Rewrite go sum after merge?

### ISSUE THREAD

**Issue by crazy-max** [dependabot/dependabot-core#1502]
Hi,

I wonder if it would be feasible for you to recreate  `go.sum` file after merging a bump dep?
Because today it kept older versions of deps.

Quick example with crazy-max/diun#12 which bumps github.com/rs/zerolog from 1.14.3 to 1.16.0. Looking at [the changes](https://github.com/crazy-max/diun/pull/12/files), zerolog 1.14.3 [is still in go.sum](https://github.com/crazy-max/diun/pull/12/files#diff-f949e2d81c8076ebbf8af38fcbb72c1fR140-R141).

My current workaround is using [this workflow](https://github.com/crazy-max/diun/blob/master/.github/workflows/gosum.yml) to [remove `go.sum` and exec a `go mod tidy`](https://github.com/crazy-max/diun/blob/master/.github/workflows/gosum.yml#L26-L27) and push changes.

Is there a better way to do this or is it a limitation linked to Go modules? Dependabot?

**Comment by hmarr** [comment]
Definitely keen to support this. We're already tracking this here: https://github.com/dependabot/feedback/issues/215, so feel free to subscribe to that issue for updates about this.

**Comment by crazy-max** [comment]
@hmarr Ok thanks for your reply
