### ISSUE TITLE
NPM / Yarn support moves public packages to private registry

### ISSUE THREAD

**Issue by gustavkj** [dependabot/dependabot-core#1506]
In our project we have an `.npmrc` file that looks like this:

```
registry = https://registry.npmjs.org/

# Private scopes
@scope1:registry = https://artifacts.companyname.com/artifactory/api/npm/npm-virtual/
@scope2:registry = https://artifacts.companyname.com/artifactory/api/npm/npm-virtual/
@scope3:registry = https://artifacts.companyname.com/artifactory/api/npm/npm-virtual/

//artifacts.companyname.com/artifactory/api/npm/npm-virtual/:email=${ARTIFACTORY_EMAIL}
//artifacts.companyname.com/artifactory/api/npm/npm-virtual/:always-auth=true
//artifacts.companyname.com/artifactory/api/npm/npm-virtual/:_auth=${ARTIFACTORY_AUTH}
```

Before we've fetched all packages through Artifactory as a proxy, but in order to get the most out of Dependabot we moved to this setup. Since this way all public packages are listed as public and will therefore get rich info PRs with changelogs etc, unlike those that update private packages. 

The PRs we get now looks good, but they move our packages from `registry.npmjs.org` to `artifacts.companyname.com`. My guess is that the problem stems from `first_registry_with_dependency_details` which will start by looking at the private registry and since my company has a proxy setup it will always get a hit from there.

https://github.com/dependabot/dependabot-core/blob/11c25c77073639e6872c1210e01d2957507e70b5/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L42-L60

https://github.com/dependabot/dependabot-core/blob/11c25c77073639e6872c1210e01d2957507e70b5/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L108-L120

I would prefer that either: 
1. it looks at the scopes specified in the `.npmrc` file and goes by that, or 
2. tries to update from the current registry for the particular package.

Any thoughts? 

*Side note:* Our setup is based on the dependabot-script `generic-update-script`.

Also, I feel this is semi-related to: https://github.com/dependabot/dependabot-core/issues/1396

**Comment by rebelagentm** [comment]
@feelepxyz I'll let you comment here, as you're more familiar with the NPM/Yarn support.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
