### ISSUE TITLE
Unable to use private artifactory maven repository

### ISSUE THREAD

**Issue by craigbensemann** [dependabot/dependabot-core#1507]
Hi,

Not sure if this is really the right place to ask but I've had dependabot-preview integrated with our private github repo for a few months. Our code is primarily java/maven and java/gradle. It is a pretty large project consisting of several hundred modules and most modules inherit from parent poms. 

It successfully finds third party dependencies but I've been unable to get it to create PRs for internal dependencies - reusable modules written by us and published to artifactory. 

We have artifactory available at a url like: http://art.companydomain.com/repo and I have created a username with read-only access for dependabot to use. To complicate things our pom files reference artifactory using a couple of variations of that url but they all point to the same artifactory.

I have created a maven repository in config variables in the UI - I created one for each of the variations of url I found in our pom files.

Looking at the access logs in artifactory I cant see any attempts from the user I set up.

I'm not really sure what snippets of poms or anything else would he helpful here. I may have simply set something up wrong but I couldn't find any examples of using private maven repos.

Like I said I'm not sure if this is the right place to ask this question. Thanks

**Comment by feelepxyz** [comment]
@craigbensemann are you by any chance setting this up for a Gradle build project?

**Comment by craigbensemann** [comment]
> @craigbensemann are you by any chance setting this up for a Gradle build project?

The repo is essentially a mono-repo with a bunch of projects in it. There is a mix of gradle and maven projects configured in the .dependabot.yml. I see there is an open issue for adding credentials to gradle builds so I dont expect them to work but I would have thought the maven ones would.

I got a little lost in the code - I'm not a native ruby speaker :) so whats the basic flow here? Will it check repos defined in your config variables or will it only use them if they match repos in your poms?

**Comment by rebelagentm** [comment]
@craigbensemann I believe that it should work for your Maven projects.  I wonder if Dependabot is failing on the Gradle ones and then not properly moving on to the Maven ones?

Basically, Dependabot should check both your config variables and your poms and, depending on how the package manager handles prioritizing repos, follow the package manager's behavior.

To help us troubleshoot further, you can e-mail us the user/org name and the repo name at `dependabot-support@github.com` and reference this issue number.

@feelepxyz Please correct me if I have any of the above wrong.

**Comment by hfuss** [comment]
Hello, any chance someone could more detailed instructions for setting this up for private Maven repos hosted in Artifactory? This would be for Maven projects only.

Reading along the issue I'm not sure what is meant by "a maven repository in config variables in the UI" or "config variables" in general. I'm new to dependabot and am just following along with the config docs: https://dependabot.com/docs/config-file/

I wouldn't need to commit a `settings.xml` or anything like that correct?
