### ISSUE TITLE
Run `go mod tidy` after a module dependency change

### ISSUE THREAD

**Issue by rcrowe** [dependabot/dependabot-core#1508]
We received the following PR...
`Bump github.com/lyft/protoc-gen-star from 0.4.11 to 0.4.12`

After running `go mod tidy` manually, we saw a diff of...
```patch
- github.com/lyft/protoc-gen-star v0.4.11 h1:zW6fJQBtCtVeSiO/Kbpzv32GO0J/Z8egSLeohES202w=	
- github.com/lyft/protoc-gen-star v0.4.11/go.mod h1:mE8fbna26u7aEA2QCVvvfBU/ZrPgocG1206xAFPcs94=
```

We would like to see this happen automatically as part of a Dependabot PR.

**Comment by hmarr** [comment]
Agreed. We're tracking here, so subscribe to this issue for updates: https://github.com/dependabot/feedback/issues/215

**Comment by rcrowe** [comment]
Ah sorry. Thanks @hmarr for pointing out correct repo 👍

**Comment by hmarr** [comment]
No worries - these kind of things are slightly scattered between the two repos so it’s not your fault at all :-)
