### ISSUE TITLE
Pull in changelog for Rails

### ISSUE THREAD

**Issue by tijmenb** [dependabot/dependabot-core#151]
The method to show changelogs apparently doesn't work for Rails (example: https://github.com/alphagov/policy-publisher/pull/172). They would be particularly useful there.

**Comment by greysteil** [comment]
Yeah, I'd really like to do this, but Rails doesn't keep a changelog for the master gem, only for the constituent parts. I might be able to persuade them to start doing GitHub releases, though - which would make things a lot better. Let me try...

**Comment by tijmenb** [comment]
Have you considered including the changelog of the transitive dependencies as well? If it worked like that, you'd get the changelogs for activemodel, actionview, etc. Could be a generic solution for this particular problem.

**Comment by greysteil** [comment]
Yeah, we don't add much detail of the sub-dependencies that get updated alongside the main one at the moment, but I'd be quite keen on doing so. The changes required to this repo would be to store the sub-dependencies that change in the `UpdateChecker` and then use those details in the `PullRequestCreator` class. (The alternative would be comparing diffs in the `PullRequestCreator` class to get the changed dependencies, but that wouldn't be language agnostic.)

**Comment by greysteil** [comment]
Closing in favour of https://github.com/dependabot/dependabot-core/issues/446. Good suggestion @tijmenb!
