### ISSUE TITLE
Dependabot can't parse your go.mod

### ISSUE THREAD

**Issue by mkrump** [dependabot/dependabot-core#1514]
Wasn't sure that I was following what was going on here. Dependabot has been running fine over the past few weeks. Is there a way to reproduce this locally?

https://github.com/transcom/mymove/issues/3008

```
The error Dependabot encountered was:

go: github.com/spf13/viper@v1.5.0 requires
	github.com/grpc-ecosystem/grpc-gateway@v1.9.0 requires
	gopkg.in/yaml.v2@v2.0.0-20170812160011-eb3733d160e7: invalid version: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /opt/go/gopath/pkg/mod/cache/vcs/748bced43cf7672b862fbc52430e98581510f4f2c34fb30c0064b7102a68ae2c: exit status 128:
	fatal: The remote end hung up unexpectedly
```

I was able run `go get gopkg.in/yaml.v2@v2.0.0-20170812160011-eb3733d160e7` locally, but I couldn't tell if that was the package causing the error.

**Comment by hmarr** [comment]
It looks like that was a temporary blip - while the Go tool was trying to fetch one of the modules its connection to gopkg.in was interrupted.

I'll close this for now, but if it reoccurs, feel free to reopen this and we'll see if we can handle transient failures more elegantly.

**Comment by Stebalien** [comment]
I'm getting on average 3 of these issues filed per month (3 in December, 4 in January, 2 this month) across all the repos I maintain. They're mostly from gopkg.in but there's one from golang.org as well.

Is there any way dependabot could check for this specific error and either retry or just not report an issue?
