### ISSUE TITLE
Ability to assign a team as reviewer

### ISSUE THREAD

**Issue by mynkow** [dependabot/dependabot-core#1515]
In github web UI it is possible to assign a team as a reviewer.

It will be great if this is also supported by dependabot

```
default_reviewers:
  - orgname/team
```

**Comment by rebelagentm** [comment]
👋 Thanks for writing in!  We'll add this to our backlog of items to consider.

**Comment by jbergstroem** [comment]
Relevant references:
- "dupe" of https://github.com/dependabot/feedback/issues/546
- tangential to #1198

**Comment by infin8x** [comment]
This is now possible in GitHub-native Dependabot! https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#reviewers

**Comment by tboddyspargo** [comment]
@infin8x - Could you comment on whether this feature is case sensitive/insensitive and whether it fails to respect case in its API request? My organization name contains capital letters and dependabot is unsuccessful at assigning a team from the organization as a review on its generated PRs. It claims `POST https://api.github.com/repos/OrgName/repo-name/pulls/5555/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the OrgName/repo-name repository.`

**Comment by ulgens** [comment]
It seems this is no longer working. We started having

> Assignees
> The following users could not be added as assignees: myperfectstay/developers. Either the username does not exist or it does not have the correct permissions to be added as an assignee.
> 
> Please fix the above issues or remove invalid values from dependabot.yml.

issue around a month ago, without any changes on our end. It seems that no matter is the assignee value, dependabot fails to add them.

**Comment by ulgens** [comment]
It seems this is no longer working. We started having

> Assignees
> The following users could not be added as assignees: <redacted>. Either the username does not exist or it does not have the correct permissions to be added as an assignee.
> 
> Please fix the above issues or remove invalid values from dependabot.yml.

issue around a month ago, without any changes on our end. It seems that no matter is the assignee value, dependabot fails to add them.

**Comment by jeffwidman** [comment]
FYI: [`reviewers` is getting deprecated](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
