### ISSUE TITLE
Bug: setup.py drops dependency extras

### ISSUE THREAD

**Issue by keirlawson** [dependabot/dependabot-core#1517]
if a dependency is defined in a setup.py file with an extra defined (ie `aiocache[redis]==0.10.1`) dependabot ignores strips the specified extra, even when bumping unrelated dependencies, ie it becomes `aiocache==0.10.1`.  This appears to be due to the Python setup.py parser helper ignores these extra values and they are not passed in to the Ruby code.

**Comment by JimNero009** [comment]
Just to let anyone know that may be watching this -- I'm looking to tackle this within the next week.

**Comment by JimNero009** [comment]
This is how I've solved it in our fork, WDYT? https://github.com/dependabot/dependabot-core/pull/1552

**Comment by m-aciek** [comment]
Shouldn't this issue be closed after merge of #1552?

**Comment by JimNero009** [comment]
Yes, this should be closed now.
