### ISSUE TITLE
[docker] dependabot suggest only certain version pattern?

### ISSUE THREAD

**Issue by jetersen** [dependabot/dependabot-core#1522]
I'd like to tame dependabot to only suggest certain version schema

So instead of

```
Bump jenkins/jenkins from 2.190.1-alpine to 2.205-alpine
```
I'd like to only bump with 3 digits `x.x.x`
```
Bump jenkins/jenkins from 2.190.1-alpine to 2.x.x-alpine
```

**Comment by rebelagentm** [comment]
@feelepxyz Is this configurable?

**Comment by feelepxyz** [comment]
@casz 👋 are you hoping to effectively ignore all path releases? Do you know if `2.190.1` is considered a minor version? We had some feedback asking for this recently so might be something we can work on soon but would only work if we can reliably tell if a release is a major/minor/path.

**Comment by casz** [comment]
@feelepxyz 2.190.1 or 2.176.1 is consider major version of the next LTS.
Where 2.190.2 is considered minor version to 2.190.1

https://jenkins.io/changelog-stable/

**Comment by feelepxyz** [comment]
@casz ah cheers! Yeah currently Dependabot just supports basic semver so 2.190.1 to 2.190.2 would be considered a patch update and 2.176.1 to 2.190.1 a minor and 2.190.1 to 3.190.1 a major. We're currently focusing on integrating Dependabot with GitHub and bug fixing so not sure when we'll get to this.

**Comment by casz** [comment]
To try and define the problem at the moment is that dependabot suggests the weekly releases of Jenkins. I'd like to only get the stable/LTS releases

**Comment by AnthonyHerman** [comment]
Another example where Dependabot default behavior can be problematic: `Bump python from 2.7.16-jessie to 3.6.9-jessie`

**Comment by AnthonyHerman** [comment]
Cool didn't know that, thanks @jetersen!

**Comment by infin8x** [comment]
Right now, the `@dependabot ignore...` commands are the way to go here.

**Comment by jetersen** [comment]
That's awful amount of ignore that in Jenkins case one would have to do weekly.
