### ISSUE TITLE
Add support for OCaml

### ISSUE THREAD

**Issue by smorimoto** [dependabot/dependabot-core#1534]
https://opam.ocaml.org/doc/Packaging.html

**Comment by imbsky** [comment]
https://esy.sh/docs/en/configuration.html#specify-dependencies

**Comment by imbsky** [comment]
To support both, get the version from the opam repository and update esy or opam file.

**Comment by XVilka** [comment]
See also https://github.com/dependabot/feedback/issues/642

**Comment by infin8x** [comment]
Duplicate of #2116
