### ISSUE TITLE
Python 3.8.0 support

### ISSUE THREAD

**Issue by le717** [dependabot/dependabot-core#1542]
Dependabot cannot resolve dependencies for Python 3.8.0. Issue filed on my project at https://github.com/le717/vss365-today/issues/61.

```
Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000056286e1d7ee0 @requirements=[[">=", #<Dependabot::Python::Version 3.8>], ["<", #<Dependabot::Python::Version 4.0.0.a>]]>]]'.

Currently, the following Python versions are supported in Dependabot: 3.8-dev, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, 2.7.17, 2.7.16, 2.7.15, 2.7.14, 2.7.13.
```

Py 3.8.0 was released on October 14, 2019. https://www.python.org/downloads/release/python-380/

Thank you! 😃

**Comment by feelepxyz** [comment]
@le717 thanks for the ping! Sadly Dependabot can't yet keep its Python version up to date.. here's the PR https://github.com/dependabot/dependabot-core/pull/1544
