### ISSUE TITLE
Ignore Dependency Forever

### ISSUE THREAD

**Issue by bhathiya** [dependabot/dependabot-core#1555]
While `@dependabot ignore this dependency` works fine to ignore a dependency, it resets after a manual upgrade. 

But there are cases where we always need to upgrade manually. In such cases a command like below is very useful.

`@dependabot ignore this dependency forever`

**Comment by infin8x** [comment]
You can do this now via the GitHub-native Dependabot configuration file: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore
