### ISSUE TITLE
[Bug] Python parsing fails if requirements.txt has '-e' at start

### ISSUE THREAD

**Issue by quezlatch** [dependabot/dependabot-core#1570]
My **requirements.txt** file starts with the line:
```
-e file:shared
```
and I see the following error in the logs:
```
fetcher | ERROR <job_17570573> Error during file fetching; aborting
```

My assumption is that line https://github.com/dependabot/dependabot-core/blob/master/python/helpers/lib/parser.py#L52 only takes account of `-c` and `-r`

**Comment by feelepxyz** [comment]
@quezlatch 👋 looks like Dependabot might not be dealing with the syntax properly and is looking for a  file named: `file:shared/setup.py`. Is `shared` a folder?

**Comment by quezlatch** [comment]
Hi! it is, yes

**Comment by feelepxyz** [comment]
@quezlatch this looks like a bug in our file fetching logic. Adding it to our backlog 👌
