### ISSUE TITLE
Dependabot scan can't auth to our private devpi

### ISSUE THREAD

**Issue by craigds** [dependabot/dependabot-core#1577]
Scans for our last python 2 project are failing.

The project is a python 2 project (`.python-version` has `2.7` in it) and it uses a private devpi server via basic auth.

The logs show this:

```
updater | <job_17641869> pip._internal.exceptions.InstallationError: Could not install requirement six==1.13.0 from https://{PRIVATE_REPO}/root/pypi/%2Bf/1f1/b7d42e254082a/six-1.13.0-py2.py3-none-any.whl#sha256=1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd (from -r base.in (line 29)) because of HTTP error 403 Client Error: Forbidden for url: https://{PRIVATE_REPO}/root/pypi/%2Bf/1f1/b7d42e254082a/six-1.13.0-py2.py3-none-any.whl for URL https://{PRIVATE_REPO}/root/pypi/%2Bf/1f1/b7d42e254082a/six-1.13.0-py2.py3-none-any.whl#sha256=1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd (from https://{PRIVATE_REPO}/root/dev/+simple/six/) (requires-python:>=2.6, !=3.0.*, !=3.1.*)
```

This repeats for many (probably all?) dependencies it tries to install from the devpi server. The scan takes ages.

Full log (is behind auth, so I figured I can share it here, and hopefully dependabot devs can access it):

* https://app.dependabot.com/accounts/koordinates/update-logs/17786500

All the other apps in the same org are on python 3.7 and work fine. I wonder if dependabot's python 2.7 environment isn't passing auth to the server at all, or something.

~~I've looked at the nginx logs in front of the devpi instance and I *don't* seem to see any 403 errors in there. So maybe dependabot isn't even sending the request, or is sending it to the wrong place, or ... something?~~

**Comment by craigds** [comment]
I was looking at the wrong nginx log. The correct log *is* seeing these requests. The index pages are fetched with basic auth present, as are the successful package download requests from scans of other apps. 

However the 403'd requests don't appear to have any HTTP auth present (we log the username, and these just have a `-` in that slot)


```
3.94.32.93 - - [15/Dec/2019:21:56:09 +0000] {PRIVATE_REPO} GET /root/pypi/%2Bf/4e0/2be61ffaaab59/django_cors_headers-2.1.0-py2.py3-none-any.whl HTTP/1.1" 403 31 "-" "pip/19.3.1 {\x22ci\x22:null,\x22cpu\x22:\x22x86_64\x22,\x22distro\x22:{\x22id\x22:\x22bionic\x22,\x22libc\x22:{\x22lib\x22:\x22glibc\x22,\x22version\x22:\x222.27\x22},\x22name\x22:\x22Ubuntu\x22,\x22version\x22:\x2218.04\x22},\x22implementation\x22:{\x22name\x22:\x22CPython\x22,\x22version\x22:\x222.7.17\x22},\x22installer\x22:{\x22name\x22:\x22pip\x22,\x22version\x22:\x2219.3.1\x22},\x22openssl_version\x22:\x22OpenSSL 1.1.1  11 Sep 2018\x22,\x22python\x22:\x222.7.17\x22,\x22setuptools_version\x22:\x2241.2.0\x22,\x22system\x22:{\x22name\x22:\x22Linux\x22,\x22release\x22:\x224.14.101-91.76.amzn2.x86_64\x22}}" 0.001
```

**Comment by craigds** [comment]
this might not be specific to py2 - just encountered on another app which is using 3.7.

https://app.dependabot.com/accounts/koordinates/update-logs/17791303

**Comment by craigds** [comment]
this is now failing all the time for all apps. I'm going to close this and raise via private support since it seems like it must be specific to us.

**Comment by olivierlefloch** [comment]
I am encountering a similar issue. Dependabot has recently started failing to update our private Devpi hosted packages after hitting a 404 on PyPy for those packages…
