### ISSUE TITLE
Add a user-agent

### ISSUE THREAD

**Issue by craigds** [dependabot/dependabot-core#1578]
Trying to debug #1577, it's a little hard to see what traffic on our devPI instance is dependabot and what isn't. 

Can I suggest adding a unique user-agent? Something like this would be helpful:

```
Dependabot/{VERSION} {python=3.7.0; pip-compile=2.0.1} scan-log: https://app.dependabot.com/.../update-logs/17712345
```

**Comment by feelepxyz** [comment]
@craigds great idea! Would you be up for submitting a patch for it? I think we'd want to extend this method to take a optional `headers` hash and merge the user agent header into it: https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/shared_helpers.rb#L130-L138

We don't have much spare capacity so any help would be much appreciated! 🙏

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
