### ISSUE TITLE
[Python] Hashes not updated

### ISSUE THREAD

**Issue by BoboTiG** [dependabot/dependabot-core#1587]
I have a couple of PR that updated the version number of a given module, but not associated hashes:
```patch
    --hash=sha256:0943b65fb41b7403a9def6214061fdd9ab9afd0bbc581e553c72eebe60bded36 \
    --hash=sha256:11ce5fec5990e34e3981ed14897ba601c83957b577d77d395f1f8f878a179f98 \
    --hash=sha256:22d970cee5c096b9123415e183ae03702b2cd4d3ba3f0ced25c4e1aba3967167
-pyobjc-core==5.2 ; sys_platform == "darwin" \
+pyobjc-core==6.1 ; sys_platform == "darwin" \
    --hash=sha256:046449f510c1f33d41bdd0d4c8eb2f084593a2ee4573a25d604bdccabb7a909e \
    # via pyobjc-framework-Cocoa
pyobjc-framework-Cocoa==5.2 ; sys_platform == "darwin" \
```

In the other hand, some other PRs are working fine (version + hashes updated).

I think the parser does not like this schema:
```
module==version \
    --hash=sha256:hash \
    # some comment
```

If the comment is on the same line, it works:
```
module==version \
    --hash=sha256:hash  # some comment
```

**Comment by BoboTiG** [comment]
Well, I am not sure this is the error. I updated the files to remove trailing comments and PRs are stil lshowing only the version number changed.

**Comment by BoboTiG** [comment]
The issue seems to be fixed since a while. Closing it.

**Comment by BoboTiG** [comment]
I reopen the issue: it is still there, but only for `pyobjc-*` modules. Which seems weird.
Here are a couple of PRs:
- https://github.com/nuxeo/nuxeo-drive/pull/1506
- https://github.com/nuxeo/nuxeo-drive/pull/1502
- https://github.com/nuxeo/nuxeo-drive/pull/1501
- https://github.com/nuxeo/nuxeo-drive/pull/1500
- https://github.com/nuxeo/nuxeo-drive/pull/1499
- https://github.com/nuxeo/nuxeo-drive/pull/1498

**Comment by mayeut** [comment]
Same kind of thing appears on a [manylinux PR](https://github.com/pypa/manylinux/pull/560/files)
```diff
  # pip requirements for python2.7
  # NOTE: pip has GPG signatures; could download and verify independently.
- pip==20.0.2 ; python_version=='2.7' \
+ pip==20.1 ; python_version=='2.7' \
     --hash=sha256:4ae14a42d8adba3205ebeb38aa68cfc0b6c346e1ae2e699a0b3bad4da19cef5c \
     --hash=sha256:7db0c8ea4c7ea51c8049640e8e6e7fde949de672bfa4949920675563a5a6967f
  wheel==0.34.2 ; python_version=='2.7' \
```

**Comment by BoboTiG** [comment]
Another one with atomicwrites (from 1.3.0 to 1.4.0): https://github.com/nuxeo/nuxeo-drive/pull/1620
