### ISSUE TITLE
Question about the commit message

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#159]
Why do you start the commit message with:
`chore(dependencies): ...`

Is there a specific reason or could you make it configurable?

**Comment by greysteil** [comment]
We made it semantic after [this issue](https://github.com/dependabot/feedback/issues/50), and I didn't think anyone would feel strongly enough about having it as anything else for it to warrant a setting. Is there a different convention you'd like us to follow?

**Comment by OskarStark** [comment]
Hey @greysteil , thanks for the feedback!

To be honest I've never heard about it and it looks strange to me and I'm not a big fan of using the git history as a Changelog.

I prefer the name of the commit before you applied this change.

Maybe not a Config of the Prefix, but "Shall use semantic commit messages?" as true/false ?

Anyway, I use Squash merge on github.com and remove the prefix manually and just wanted to know more about the background! 😃

**Comment by greysteil** [comment]
Awesome, thanks for the feedback. To be honest, I think I prefer the non-semantic version, too.

I'll update Dependabot to read through the last few commits on the branch it's targeting and decide whether to use semantic commits automatically.

**Comment by OskarStark** [comment]
> I'll update Dependabot to read through the last few commits on the branch it's targeting and decide whether to use semantic commits automatically.

sounds like a smart idea 👍

**Comment by greysteil** [comment]
Updated in https://github.com/dependabot/dependabot-core/commit/77bd3b823d740c65d3a89f1e7027a3ca4fbf09e9 which is being deployed on Dependabot now. 🎉
