### ISSUE TITLE
Python 3.7.6 support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#1597]
New python version is out: https://www.python.org/downloads/release/python-376/

But, dependabot does not know about it: https://github.com/wemake-services/wemake-django-template/issues/1029

Can you please add a support for it?

**Comment by feelepxyz** [comment]
@sobolevn yup will add it to our backlog 👍

**Comment by polothy** [comment]
Think this can be closed: https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/python_versions.rb
