### ISSUE TITLE
Which Mailaddress do you use?

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#160]
![screenshot 2017-12-08 09 30 31](https://user-images.githubusercontent.com/995707/33757452-80dea84c-dbfa-11e7-8b08-40045007f845.png)

Which Mailaddress do you use for the commits? Could you associate it which the Bot-Account to get the avatar?

**Comment by greysteil** [comment]
I think this one needs to be fixed on the GitHub side. Would be amazing if you could give the team a prod [here](https://platform.github.community/t/commit-avatars-for-bots/2332) - I've been trying for months...

**Comment by greysteil** [comment]
Gravatar hack works! All Dependabot PRs will now have the email address `support@dependabot.com` and appear with an avatar. Thanks for the tip @OskarStark.
