### ISSUE TITLE
Cannot parse URL with variables in pom.xml

### ISSUE THREAD

**Issue by jetersen** [dependabot/dependabot-core#1606]
Used a variable in their `scm.url` property https://github.com/jenkinsci/jenkins-test-harness
`<url>https://github.com/jenkinsci/${project.artifactId}</url>`

which fails to parse and show release notes on PRs
see for example: https://github.com/jenkinsci/plugin-pom/pull/281

workaround: https://github.com/jenkinsci/jenkins-test-harness/pull/191

**Comment by casz** [comment]
Seems like it should handle it
https://github.com/dependabot/dependabot-core/blob/08e851cdf8477e041b61e5c8a6cdd3eb341b79f4/maven/lib/dependabot/maven/metadata_finder.rb#L68-L88

**Comment by hmarr** [comment]
@jetersen are you still experiencing this issue? I'll close for now but feel free to reopen if so.
