### ISSUE TITLE
Python: Is it possible update versions up to a max version?

### ISSUE THREAD

**Issue by quezlatch** [dependabot/dependabot-core#1607]
Say my `requirements.in` file is:
```
aws-xray-sdk==2.*
```

and my current `requirements.txt` is:
```
aws-xray-sdk==2.4.2
```

I want dependabot to update the minor versions, but stop at major version changes. Ie. in this example, keep updating `aws-xray-sdk` when it's version is 2 but stop when it goes to 3. Is this possible?

Many thanks

**Comment by m-aciek** [comment]
@quezlatch Wouldn't `was-xray-sdk<3` in `requirements.in` do exactly what you want to achieve?

**Comment by quezlatch** [comment]
possibly... i think possible I'm confused by what works and what doesn't. ie i think the following would all be mostly equivalent:
```
aws-xray-sdk<3
```

```
aws-xray-sdk==2.*
```

```
aws-xray-sdk~=2.0.0
```
