### ISSUE TITLE
Dependabot couldn't authenticate with npm.pkg.github.com/<Organization>

### ISSUE THREAD

**Issue by ttruongatl** [dependabot/dependabot-core#1613]
Hi,
I recognized the last release v0.116.0 that causes the authentication issue with npm.pkg.github.com.
Here is my scenario:

1. Private Repo
2. Private github package: npm.pkg.github.com/@smisy
@smisy is my organization.

Yarn is not working with **npm.pkg.github.com** and my repo only works with npm.

dependabot worked well with my **github token** until the team release v0.116.0. I wonder dependabot only use yarn at v0.116.0?

**Comment by feelepxyz** [comment]
@ttruongatl there shouldn't be any breaking changes in v0.116.0 and haven't changed anything around npm auth so not sure what's gone wrong. Have you tried authenticating to a package hosted on `npm.pkg.github.com/@smisy` using your token? Just testing with curl or similar.

**Comment by ttruongatl** [comment]
@feelepxyz I tested the token and it worked fine on my local and JenkinsCI. As I said, yarn is not working on my project. Do you think it may cause the issue?

**Comment by ttruongatl** [comment]
I have seen the issue for the last couple of days. Closed the ticket.
