### ISSUE TITLE
issue with pip-compile and relative paths

### ISSUE THREAD

**Issue by mst-ableton** [dependabot/dependabot-core#1635]
Hello, and thanks for Dependabot!

We have `.` in our `requirements.in` file, so things from our local package get installed properly. Dependabot interprets this strangely, and we end up with `file:///home/dependabot/dependabot-updater/tmp/dependabot_<date and random string>` in our `requirements.txt`. This breaks our install. Is there a workaround for this, or should we wait for a fix?

Thanks!

**Comment by nre-ableton** [comment]
Bump, I'm reopening this issue because our team still sees this bug quite often. Surely we aren't the only ones in this situation?
