### ISSUE TITLE
Gradle (Java) - Dependabot doesn't recognize new version

### ISSUE THREAD

**Issue by Andre601** [dependabot/dependabot-core#1636]
When checking for new versions does dependabot not recognize a new update version, even tho it is set in the metadata.xml's `<latest>` tags.

The dependency in general is JDA (`net.dv8tion:JDA`) on bintray.
The bot does retrieve the metadata.xml from the site, to check what the latest version is.
And even tho the file has `<latest>4.1.0_100</latest>` and the current version in the repo is set to `4.1.0_99` does the bot not recognize that the version has changed and sees it as "up to date"

Here's the output of the relevant logs:
```
updater | INFO <job_20942363> Checking if net.dv8tion:JDA 4.1.0_99 needs updating
  proxy | 2020/01/20 09:52:15 GET https://repo.maven.apache.org:443/maven2/net/dv8tion/JDA/maven-metadata.xml
  proxy | 2020/01/20 09:52:15 200 https://repo.maven.apache.org:443/maven2/net/dv8tion/JDA/maven-metadata.xml
  proxy | 2020/01/20 09:52:15 GET https://jcenter.bintray.com:443/net/dv8tion/JDA/maven-metadata.xml
  proxy | 2020/01/20 09:52:15 200 https://jcenter.bintray.com:443/net/dv8tion/JDA/maven-metadata.xml
updater | INFO <job_20942363> Latest version is 4.1.0_99
updater | INFO <job_20942363> No update needed for net.dv8tion:JDA 4.1.0_99
```

**Comment by Andre601** [comment]
This is still a thing

**Comment by Andre601** [comment]
I would be happy if there would be *any* response to this as this is (to my knowledge) still an issue.

**Comment by jurre** [comment]
@Andre601 thanks for reporting, we don't currently have capacity to look into this but it's on our radar and we're hoping to get to it soon

**Comment by zbynek** [comment]
@Andre601 I created a PR (#4257), but it might be also useful if the JDA devs implemented the  [semantic versioning standard](https://semver.org/) for their releases.

**Comment by Andre601** [comment]
> @Andre601 I created a PR (#4257), but it might be also useful if the JDA devs implemented the [semantic versioning standard](https://semver.org/) for their releases.

They for the most part do follow the SemVer standard, which in their case is `major.minor.patch_build`
But they plan to go away from the build number and instead use a release candidate system instead.

**Comment by zbynek** [comment]
@Andre601 using a hyphen instead of underscore (`major.minor.patch-build`) would be enough to avoid this issue.
