### ISSUE TITLE
SSL certificate of github-redirect.dependabot.com seems invalid

### ISSUE THREAD

**Issue by y-yagi** [dependabot/dependabot-core#1653]
When accessed https://github-redirect.dependabot.com/ with Chrome, `NET::ERR_CERT_COMMON_NAME_INVALID` error is showed.

Error detail is belows.

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.netlify.com

Issuer: DigiCert SHA2 Secure Server CA

Expires on: 2020/07/07

Current date: 2020/01/27
```

**Comment by hmarr** [comment]
Thanks for reporting this! We're working on it.

We're also tracking this in https://github.com/dependabot/feedback/issues/832, so I'll close this out as a duplicate - please subscribe to that issue for updates :-)
