### ISSUE TITLE
Consider upgrading "engines" version in package.json

### ISSUE THREAD

**Issue by papakai** [dependabot/dependabot-core#1655]
when a dependency  or dev-dependency deprecates a nodejs version e.g. `@semantic-release/changelog 5.0.0`, would be cool to also automatically include upgrading the engines version in package.json if applicable.

No idea if that can be reached somehow, at least this would have saved a lot of time on our side right now while upgrading 10 repositories to that mentioned module version. (could be taken from defined engines version in dependency's package.json though)

At least it should influence the compatibility check (to not show in green or so) when the dependency's engines version doesn't any longer fit the repository's engines version requirement.

Maybe an idea to offer this feature by configuration setting.

**Comment by yeldiRium** [comment]
This issue is still relevant and stale bots do not contribute to project health.

**Comment by papakai** [comment]
Why should people continue reporting ideas and bugs, if bots are used to auto-close gh issues after a certain point of time?
Just the best way to let people switch to other dependency management tools where their opinion is of more interest.
If you don't have the resources to work on all the feature requests / issues, well then you have already identified the root cause. I'll add to our backlog to check for alternatives in future.
