### ISSUE TITLE
Elixir dependency parsing fails with latest `mix.lock` format

### ISSUE THREAD

**Issue by glenwinters** [dependabot/dependabot-core#1675]
Dependabot opened an issue called "Dependabot can't evaluate your Elixir dependency files" with the following error:

```
** (FunctionClauseError) no function clause matching in Parser.parse_lock/1    
    
    The following arguments were given to Parser.parse_lock/1:
    
        # 1
        {:hex, :libcluster, "3.1.1", "cbab97b96141f47f2fe5563183c444bbce9282b3991ef054d69b8805546f0122", [:mix], [{:jason, "~> 1.1.2", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm", "8eaf6b0ca713f70ff588596743becba3e0ddda9ec14873adf7634ea705afc6f3"}
    
    parse_deps.exs:69: Parser.parse_lock/1
    parse_deps.exs:19: Parser.build_dependency/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    parse_deps.exs:101: (file)

{"error":""}
```

This appears to be due to an update to [the hex package to `v0.20.2`](https://github.com/hexpm/hex/releases). Specifically, [this PR](https://github.com/hexpm/hex/pull/708) adds `outer_checksum` to the end of the `mix.lock` dependency tuple. This issue is still present in the latest version, `v0.20.4`.

The error shown above is occurring because `parse_lock` pattern matches against the `mix.lock` tuple and it doesn't have a match for the new tuple format with the new checksum at the end.

---

There isn't a straightforward way to roll back the version of `hex` for a given project. You run `mix local.hex` and it goes and finds the latest version for your version of elixir. I looked in the code for that mix task and found that it identifies the latest version by looking at the CSV https://repo.hex.pm/installs/hex-1.x.csv. hex `v0.20.4` is listed for all Elixir versions from `1.0.0` to `1.10.0`, so this isn't limited to the latest version of Elixir. However, the problem does not occur until you run `mix local.hex` and commit the updated `mix.lock` file.

**Comment by anthonator** [comment]
We're seeing this as well.

```
** (FunctionClauseError) no function clause matching in Parser.parse_lock/1    
    
    The following arguments were given to Parser.parse_lock/1:
    
        # 1
        {:hex, :ex_doc, "0.21.3", "857ec876b35a587c5d9148a2512e952e24c24345552259464b98bfbb883c7b42", [:mix], [{:earmark, "~> 1.4", [hex: :earmark, repo: "hexpm", optional: false]}, {:makeup_elixir, "~> 0.14", [hex: :makeup_elixir, repo: "hexpm", optional: false]}], "hexpm", "0db1ee8d1547ab4877c5b5dffc6604ef9454e189928d5ba8967d4a58a801f161"}
    
    parse_deps.exs:69: Parser.parse_lock/1
    parse_deps.exs:19: Parser.build_dependency/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    parse_deps.exs:101: (file)

{"error":""}
```

**Comment by anthonator** [comment]
Also being discussed on Elixir Forum.

https://elixirforum.com/t/dependabot-recently-broke/28919

@ericmj  also mentioned Dependabot should ignore extra tuple fields it does not recognize so they do not fail again if we add more fields.
