### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by TerensTare** [dependabot/dependabot-core#1679]
Dependabot looks like a well-built utility for Github. 
I am sure it would be better if it would support C++.
This can probaly be achieved by using C++ package managers such as vcpkg, Conan, hunter or buckaroo.

**Comment by okainov** [comment]
Even though it was submitted earlier, there are much more discussions and detailed description in #2027

**Comment by TerensTare** [comment]
Then I will close this, and wait for sth to be done on the other issue.
