### ISSUE TITLE
Custom registry contining an environment variable appears to be broken

### ISSUE THREAD

**Issue by orf** [dependabot/dependabot-core#1681]
dependabot-omnibus version `0.116.6`

Hello,
I'm trying to use the [dependabot standalone script](https://github.com/dependabot/dependabot-script/blob/master/generic-update-script.rb) with a repository that contains a Pipfile with the following lines:

```toml
[[source]]
url = "https://${CREDENTIALS}@private.repo/repository/pypi/simple"
name = "some-name"
```

I've configured the credential like so:

```ruby
  {
    "type" => "python_index",
    "index-url" => "https://private.repo/repository/pypi/simple",
    "token" => ENV['CREDENTIALS'],
  }
```

**Note:** `CREDENTIALS` contains both a **username** and a **password**, i.e `user:pass`, not a token.

However this throws the following Ruby error:

```
x/dependabot/vendor/ruby/2.6.0/gems/dependabot-python-0.116.6/lib/dependabot/python/update_checker/index_finder.rb:183:in `clean_check_and_remove_environment_variables': 
The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): 
https://${CREDENTIALS}@private.repo/repository/pypi/simple/ (Dependabot::PrivateSourceAuthenticationFailure)
```

Now I've done some debugging and I cannot seem to see how this works at all, so I must be doing something really stupid:

1. [The clean_check_and_remove_environment_variables method](https://github.com/dependabot/dependabot-core/blob/224d29f57716d165c5624f208939362f8a691766/python/lib/dependabot/python/update_checker/index_finder.rb#L152) is called with the url `https://${CREDENTIALS}@private.repo/repository/pypi/simple/`
2. [The config_variable_urls](https://github.com/dependabot/dependabot-core/blob/224d29f57716d165c5624f208939362f8a691766/python/lib/dependabot/python/update_checker/index_finder.rb#L159-L165) variable contains the _correctly authenticated url_, i.e `https://username:password@private.repo/...`
3. The [regexp created](https://github.com/dependabot/dependabot-core/blob/224d29f57716d165c5624f208939362f8a691766/python/lib/dependabot/python/update_checker/index_finder.rb#L167-L171) strips out the environment variables, and so becomes a value like `https://private\.repo/repository/pypi/simple/`
4. This does not match any of the values in `config_variable_urls`
5. [`cleaned_url`](https://github.com/dependabot/dependabot-core/blob/224d29f57716d165c5624f208939362f8a691766/python/lib/dependabot/python/update_checker/index_finder.rb#L175) becomes a value `https://@private.repo/...`
6. [`credential_for`](https://github.com/dependabot/dependabot-core/blob/224d29f57716d165c5624f208939362f8a691766/python/lib/dependabot/python/update_checker/index_finder.rb#L189-L195) fails to match, as `https://@private.repo/` isn't in any defined python repository credential

Now if I set `index-url` like so: `https://@private.repo/repository/pypi/simple` it passes the authentication and makes a request, however the credential is **invalid** as it contains a percent-encoded `@` character - i.e the URL is created as `https://user:pass@@private.repo/...` with two `@` characters.

In total I've tried:
1. `https://@private.repo/repository/pypi/simple`
2. `https://private.repo/repository/pypi/simple`
3. `private.repo/repository/pypi/simple`
4. `@private.repo/repository/pypi/simple`
5. `https://USER:PASS@private.repo/repository/pypi/simple`
6. `https://${CREDENTIALS}@private.repo/repository/pypi/simple`

And nothing seems to work. Am I doing something completely wrong here?

**Comment by feelepxyz** [comment]
@orf hey sorry about this. We currently don't use credentials directly with dependabot-core so this path won't be well tested. Would gladly accept a patch if you spot the bug.

**Comment by jeffwidman** [comment]
I'm pretty sure this was fixed by https://github.com/dependabot/dependabot-core/pull/5452, so closing this. Please comment if for some reason I misunderstood the root issue here and I'll happily re-open.
