### ISSUE TITLE
Support for .net core local tool files

### ISSUE THREAD

**Issue by xt0rted** [dependabot/dependabot-core#1697]
In newer versions of .net core global tools can be installed locally to a project. I'm not sure where the documentation is for this, it seems to be missing from the site right now.

The tools are installed from nuget.org and are saved to a `.config/dotnet-tools.json` file in the root of your project. This is the file format:

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-format": {
      "version": "3.1.37601",
      "commands": [
        "dotnet-format"
      ]
    }
  }
}
```

**Comment by xt0rted** [comment]
The documentation for this is now available at https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool

**Comment by ejball** [comment]
Would love to see this implemented. `dotnet-tools.json` also works at the root of the project (i.e. not in `.config`).

**Comment by xt0rted** [comment]
Now that I'm using local tools more I put some action workflows together that look for local tools and update them if needed. A demo of this can be found in [xt0rted/dotnet-tool-update-test](https://github.com/xt0rted/dotnet-tool-update-test).
