### ISSUE TITLE
[BUG] Dependabot Docker does not update Ubuntu tags correctly

### ISSUE THREAD

**Issue by aliculPix4D** [dependabot/dependabot-core#1708]
Hi,

we have noticed an issue with Dependabot when trying to bump a docker image tags from ubuntu. In example, the PR is not being opened when trying to bump the version from `ubuntu:bionic-20190912.1` to for example `ubuntu:bionic-20200219`. There is no issue when trying to update the Docker tag from `ubuntu:bionic-20190912` to `ubuntu:bionic-20200219` as it can be seen in the following PR (https://github.com/Pix4D/dependabot-docker-bug-test/pull/3).
Additionally, we have found an issue when two Dockerfiles are in the same folder (https://github.com/Pix4D/dependabot-docker-bug-test/pull/3/files) were we expected to correctly update from `ubuntu:bionic-20190912.1` to `ubuntu:bionic-20200219` instead the proposed update by Dependabot is `ubuntu:xenial-20200212`

We have prepared the following repository to verify the bug: 
https://github.com/Pix4D/dependabot-docker-bug-test

 Expected:
 - 4 opened PRs, one for each of the folders monitored
 - in the PRs with two Dockerfiles per folder that both Docker images updates are proposed correctly

 Found:
 - 1 missing PR while trying to bump the version from from `ubuntu:bionic-20190912.1` to for example `ubuntu:bionic-20200219`
 - in PR with two Dockerfiles we expected to correctly update from `ubuntu:bionic-20190912.1` to `ubuntu:bionic-20200219` instead we got `ubuntu:xenial-20200212`
   (https://github.com/Pix4D/dependabot-docker-bug-test/pull/3/files)
 - previous example showed us the update in both files in this PR (https://github.com/Pix4D/dependabot-docker-bug-test/pull/2/files) is an happy accident

**Comment by deivid-rodriguez** [comment]
Just tried this and got the expected result I think

```
=> parsing dependency files
=> updating 1 dependencies: ubuntu

=== ubuntu (bionic-20190912.1)
 => checking for updates 1/1
 => latest available version is bionic-20210615.1
 => latest allowed version is bionic-20210615.1
 => requirements to unlock: own
 => requirements update strategy: 
 => updating ubuntu from bionic-20190912.1 to bionic-20210615.1

    ± Dockerfile
    ~~~
    1c1
    < FROM ubuntu:bionic-20190912.1
    ---
    > FROM ubuntu:bionic-20210615.1
    ~~~
🌍 Total requests made: '0'
```

So it sounds that we have fixed this :)

Please reopen if this is not the case 🍻.
