### ISSUE TITLE
Dependabot doesn't understand fastlane Gemfile

### ISSUE THREAD

**Issue by tianhaoz95** [dependabot/dependabot-core#1720]
This is the Gemfile with plugin generated by Fastlane:

https://github.com/tianhaoz95/photochat/blob/39c30f4d7164f8819b9f59a8fff68d5e697e0c8f/photochatapp/android/Gemfile#L5-L6

Dependabot panics at the plugin definition and opens this:
https://github.com/tianhaoz95/photochat/issues/41

**Comment by jurre** [comment]
We do not support passing anything other than a string to `eval_gemfile` and the Gemfile that Fastlane has generated passes a path object, but I believe that this change to your Gemfile should fix the issue for you:

```ruby
eval_gemfile('fastlane/Pluginfile') if File.exist?(plugins_path)
```

**Comment by tianhaoz95** [comment]
Thanks for the solution, will try is asap and comment. However, that means every time I add a new pluginn, there is a manual step required to change the impl. Will the team consider adding support for passing an path object or is there any critical blocker?

**Comment by jurre** [comment]
New plugins should be picked up that way, it will still load the gemfile in `fastlane/Pluginfile`, just using a string instead of a path.

**Comment by tianhaoz95** [comment]
Yes string works. Thanks! SGTM
