### ISSUE TITLE
Support submodule rubygem which hosted on github enterprise 

### ISSUE THREAD

**Issue by iguchi1124** [dependabot/dependabot-core#1724]
I'm trying to introduce dependabot into my ruby project on github enterprise, but it didn't work for my project.

The project is using internal rubygem which hosted on github enterprise. The gem is installed by using git submodule. 

When I execute [dependabot-script](https://github.com/dependabot/dependabot-script), I got `Dependabot::PathDependenciesNotReachable` error. There is my code structure example below.

__Project tree__
```
project
├── app
├── mygem
├── Gemfile
└── .gitmodules
```

__Gemfile__
```rb
gem 'mygem', path: './mygem'
```

__.gitmodules__
```
[submodule "mygem"]
        path = mygem
        url = git@ghe.example.com:iguchi1124/mygem.git
```

Now, I find out that `DependaBot::Source` class doesn't supports github enterprise source, and so that why my submodule gem isn't processed as submodule source. 

- https://github.com/dependabot/dependabot-core/blob/08c679d/common/lib/dependabot/source.rb
- https://github.com/dependabot/dependabot-core/blob/d5240b0/common/lib/dependabot/file_fetchers/base.rb#L181

Then I wrote a patch that to be able to pass github enterprise url to `Dependabot::Source.from_url` method.

https://github.com/dependabot/dependabot-core/compare/master...iguchi1124:support-github-enterprise-submodule

But there are a lot of codes using `Dependabot::Source.from_url` class, so I'm not sure this is a correct way to resolve this problem.

I'd like to get a piece of advice from authors for this issue.

**Comment by jeffwidman** [comment]
👋 Sorry for the super slow response here. The team has been buried for a while, so we're just now finally starting to dig through our backlog.

This is a really old issue, and we've since shipped _much_ better support for GHES. So I'm going to close, assuming this is resolved. If it's not, please comment and we can reopen.
