### ISSUE TITLE
Authentication failure for private Maven repositories in a Gradle project

### ISSUE THREAD

**Issue by CarrotCodes** [dependabot/dependabot-core#1725]
## What 

In #1717, support for privately authenticated Maven repositories, when using Gradle projects, was added, which is awesome 👍 

Previously, Dependabot would not attempt to authenticate when connecting to private Maven repositories.

Now, Dependabot does attempt to authenticate, but at least in the case of GitHub Package Registry (GPR), fails to do so with credentials that work in a browser.

## Reproduction Steps

* Choose/make a private Gradle library, and publish it to GPR
* Choose/make a private Gradle project, which imports this library from GPR

For example, the salient bits of the project configuration:
```
repositories {
    maven {
        url 'https://maven.pkg.github.com/kalecharity/adoptanimals-service'
        credentials {
            username = GPR_MAVEN_USER
            password = GPR_MAVEN_ACCESS_TOKEN
        }
    }
}

dependencies {
    implementation 'animals.adopt.service:adoptanimals-service:0.0.30'
}
```

* Add a Dependabot configuration variable for the Maven library (in this case, `https://maven.pkg.github.com/kalecharity/adoptanimals-service`)
* Run Dependabot on the project repository
* Open the Dependabot log - find the 401 relating to your project, and copy the URL for the file that failed (for example: `https://maven.pkg.github.com:443/kalecharity/adoptanimals-service/animals/adopt/service/adoptanimals-service/maven-metadata.xml` )
* Open the copied URL in your browser, and use the same credentials as you configured in Dependabot
* Observe that basic auth succeeds

## Logs

```
  proxy | 2020/03/07 11:03:46 401 https://maven.pkg.github.com:443/kalecharity/adoptanimals-service/animals/adopt/service/adoptanimals-service/maven-metadata.xml

updater | INFO <job_25578831> Handled error whilst updating animals.adopt.service:adoptanimals-service: private_source_authentication_failure {:source=>"https://maven.pkg.github.com/kalecharity/adoptanimals-service"}
```

**Comment by SkyeWelch** [comment]
I got loads of pull requests for private Gradle repositories today, so this looks to be resolved. Thanks again for adding the feature! 🙌

**Comment by CarrotCodes** [comment]
Had chance to confirm all my repositories are behaving as expected, so I'll close this for now 👍

**Comment by jurre** [comment]
🎉 most of the work was contributed by @GeorgiosGoniotakis, but I'm really happy to hear it's working as expected!

**Comment by parisapo** [comment]
Hey folks is there an example on how this will work? Do you have add the username and pwd of the repository on the project as secret and just reference them from the build.gradle?

**Comment by jurre** [comment]
Private registries are not supported yet in the github native version of Dependabot. If you need this feature I'd recommend using dependabot.com for now, and we'll let you know once it's ready to migrate over

**Comment by parisapo** [comment]
Thanks for the clarification.
