### ISSUE TITLE
Question: support for .github/dependabot.yml config file

### ISSUE THREAD

**Issue by coreyfarrell** [dependabot/dependabot-core#1726]
I was going to request that dependabot consider supporting config in `.github/dependabot.yml` but I see that this repository has moved the configuration to that filename.  Can anyone tell me the status of this configuration location?

**Comment by feelepxyz** [comment]
@coreyfarrell it's coming in a beta soon 🤠what's your email? Can invite you once we launch it.

**Comment by coreyfarrell** [comment]
My address is git@cfware.com

**Comment by RichiCoder1** [comment]
I'd also be interested in this if possible. rsimpson at uship.com

**Comment by mbrevda** [comment]
+1, username @gmail.com

**Comment by feelepxyz** [comment]
🎉  https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
