### ISSUE TITLE
PHP: syntax error on update

### ISSUE THREAD

**Issue by kubawerlos** [dependabot/dependabot-core#1730]
Hello,

I'm getting this error in [logs](https://app.dependabot.com/accounts/kubawerlos/update-logs/25976837) when updating:
```
updater | ERROR <job_25976837> Error processing vimeo/psalm (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_25976837> syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
updater | ERROR <job_25976837> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/shared_helpers.rb:111:in `run_helper_subprocess'
```

Config: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/master/.dependabot/config.yml

**Comment by pehbehbeh** [comment]
I have the same issue. I think this is related to PHP 7.4.

It also seems that Dependabot does not respect the `"php": "^7.4",` settings in `composer.json`.

**Comment by pehbehbeh** [comment]
I just found out, that PHP 7.3 is hardcoded. So Dependabot is unusable with PHP 7.4 right now. 😢 

https://github.com/dependabot/dependabot-core/blob/9d61e6e5ffb25a1df09f7a8a06497b6ac9b2791e/Dockerfile#L99-L107

**Comment by kubawerlos** [comment]
@pehbehbeh I've missed it somehow, let's try to fix this ☝️ .
