### ISSUE TITLE
Support for paket dependency manager

### ISSUE THREAD

**Issue by tforkmann** [dependabot/dependabot-core#1738]
Hi there,

I really like how dependabot is taking care of your packages. It works really well!

But as an F# user I usally use Paket (https://fsprojects.github.io/Paket/) as my prefered package manager.

Right now dependabot is only watching the referenced packages in the fsproj files. For example like this:
![image](https://user-images.githubusercontent.com/4168951/76701751-3f4f3480-66c4-11ea-95a1-bc2531b64999.png)

It would be great if dependabot could also watch the paket.lock file:
![image](https://user-images.githubusercontent.com/4168951/76701769-673e9800-66c4-11ea-9a7c-cdd82506d0a8.png)

Any idea if that could be possible?

Best,

Tim

**Comment by nojaf** [comment]
Would you accept a community PR for this?
With some guidance, I might want to look into this.

**Comment by tforkmann** [comment]
Any news on that?

**Comment by nojaf** [comment]
Hello, could we please get an update on this?

**Comment by jamesmcguirepro** [comment]
Possible duplicate: https://github.com/dependabot/dependabot-core/issues/2190

**Comment by tforkmann** [comment]
Any news on that? Can that PR be merged?

**Comment by jeffdoolittle** [comment]
This is something my team needs. Can we get this PR merged?

**Comment by jurre** [comment]
https://github.com/dependabot/dependabot-core/issues/2190 is a duplicate of this, but given that issue has a bit more discussion I'm going to close this in favor of that one.

**Comment by 64J0** [comment]
Is it supported now?

**Comment by jeffdoolittle** [comment]
I'm confused as to why this is closed since dependabot still does not provide paket support.

This has come up again as a need for teams that I work with. How do we get this re-opened and completed?
