### ISSUE TITLE
Question:  When is the next release?

### ISSUE THREAD

**Issue by a1flecke** [dependabot/dependabot-core#1746]
When is the next planned release of dependabot to Github?  We are experimenting with using dependabot with for our Java dependencies and are currently blocked because Github is still using release 0.117.2 which does not include [this change](https://github.com/dependabot/dependabot-core/commit/9d61e6e5ffb25a1df09f7a8a06497b6ac9b2791e)

**Comment by jurre** [comment]
Hi @a1flecke, I'll try to cut a new release of the gem and bump the versions internally soon 👍

**Comment by a1flecke** [comment]
Thanks!

**Comment by ulgens** [comment]
The new version is released, i think this issue can be closed :slightly_smiling_face:

**Comment by a1flecke** [comment]
@jurre  Any guidance on when the version that Github uses will be bumped?  I just kicked off a new run of dependabot against our repo and it is still using 117.2.

**Comment by jurre** [comment]
Hey @a1flecke, the new version should be available now, I rolled out the new version earlier today.

**Comment by a1flecke** [comment]
@jurre 

Thank you.  With this release Dependabot was able to pick up our internal Java dependencies being hosted on Github Package registry

**Comment by jurre** [comment]
Awesome, happy to hear it, and thanks for your contribution 🎉
