### ISSUE TITLE
2 dependencies should be updated

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#175]
Hey @greysteil 

I manually bumped my repo but I got no PR.

locally I got this:
![screenshot 2017-12-15 07 32 06](https://user-images.githubusercontent.com/995707/34029681-138b9b5e-e16a-11e7-88d7-e980995a0d48.png)

Can you please check this?

**Comment by OskarStark** [comment]
I added my composer.json/.lock as a gist here:

https://gist.github.com/OskarStark/715cd909576b5ce4a2ee2971ee196f53

**Comment by greysteil** [comment]
Thanks @OskarStark. Can you let me know the name of your repo, so I can take a look at Dependabot's logs? If you don't want to put it here then you can ping me on support@dependabot.com.

**Comment by OskarStark** [comment]
its called `OskarStark/acd`

**Comment by greysteil** [comment]
OK, I can replicate. Digging into this now. Thanks for the report!

**Comment by OskarStark** [comment]
Thank you for the great support 👍

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/77406d5d220ce7c61c7d68d1bacb8b8fadf59277, which I'm deploying now. Thanks again for the heads up!

**Comment by OskarStark** [comment]
Works like a charme, I already got the first PR 😄

**Comment by greysteil** [comment]
FYI, it looks like the `symfony/phpunit-bridge` issue is actually a separate one, which I'm fixing now.

**Comment by greysteil** [comment]
And that issue is fixed now too. 🎉
