### ISSUE TITLE
4-character hex prefix on branch names

### ISSUE THREAD

**Issue by j3parker** [dependabot/dependabot-core#1752]
Hello,

On most of our repos (configured via the UI) dependabot creates branch names such with the format `dependabot/*`.

We have another repo, configured via YAML (I'm not sure if this is relevant) which is creating branch names like `25d1dependabot/nuget/System.Threading.Tasks.Dataflow-4.11.0`.

This makes it difficult to select all the dependabot branches with a refspec.

Is this due to using YAML? Is there any way around it?

**Comment by voda** [comment]
Hi, I am experiencing the same issue, some PRs have this random prefix in the branch name.

We have all repositories configured with `.github/depedabot.yml` (same configuration in all repositories) and today we got PRs for "Bump lint-staged from 11.1.1 to 11.1.2" where some PRs have the prefix and some don't.

[The documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#pull-request-branch-nameseparator) doesn't mention any prefix, only the separator.

We are relying on the branch name to run some actions and this random prefix is breaking it.

**Comment by jurre** [comment]
Could you share a PR where this happens? I've not seen it before

**Comment by voda** [comment]
@jurre I have seen it only on private repos so I sent them to you via email.

**Comment by jurre** [comment]
Thanks @voda, unfortunately (or maybe, fortunately actually 😄) we're not able to see PRs or content in private repo's. Would you mind sending a request via [support](https://support.github.com/contact), they have tooling available to open this up and then route it to someone on our team, I think that'll be the best route to debug this.

**Comment by brrygrdn** [comment]
Hi @j3parker @voda, apologies for the delay in replying.

This random prefix is added in cases where a branch named just `dependabot` already exists, see:
https://github.com/dependabot/dependabot-core/blob/84a82a62e1b27cc1b8fe0aa7f3c508e8b0aded23/common/lib/dependabot/pull_request_creator/github.rb#L245-L247

The use of `dependabot/` as a 'folder' in git means our PRs are blocked on using their default naming scheme if this exists, so the prefix is a workaround to avoid failing to create the PR.

This is behaviour is fairly opaque so I'll add something to our backlog to make it more obvious when this is happening and how it can be corrected.

**Comment by voda** [comment]
> This random prefix is added in cases where a branch named just dependabot already exists.

Yes, that makes sense. Thanks for looking into it.

**Comment by j3parker** [comment]
Ah of course. Thank you!
