### ISSUE TITLE
[bundler] Platform specific dependencies don't get updated

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#1753]
In our `Gemfile`, we specify `pry-byebug` only for `:mri`:

https://github.com/activeadmin/activeadmin/blob/47ace788812cf0022e6c8afbac636cea8ad4521b/Gemfile#L6

But `dependabot` doesn't create PRs for it.

I think it's related to being a platform specific dependency.

References: https://github.com/activeadmin/activeadmin/pull/6155.

Thanks!

**Comment by feelepxyz** [comment]
@deivid-rodriguez 👋  we've just launched support for bundler v2 in Dependabot Version and Security Updates. This should just work if your lockfile has been `BUNDLED WITH 2.x`. Let us know if this fixes the above issue for you.

Dependabot Preview support is coming next week.

**Comment by deivid-rodriguez** [comment]
Thank you, that's great, I'll report back!

**Comment by jurre** [comment]
I'm fairly shure this is fixed now, but please feel free to reopen if you run into things!
