### ISSUE TITLE
Can't resolve JavaScript dependency on Github Package Registry

### ISSUE THREAD

**Issue by dislick** [dependabot/dependabot-core#1756]
Dependabot keeps creating an issue with the following error message in my lerna monorepo:

```
Error whilst updating fs-extra in /packages/api/package-lock.json:
404 Not Found - GET https://registry.npmjs.org/@myorg/package - Not found
```

The weird thing is that @myorg/package is not listed in `/packages/api/package-lock.json` (it is however in `package.json`). Additionally it is not hosted on `registry.npmjs.org`, but on `npm.pkg.github.com`.

```bash
$ grep "@myorg/package" packages/api/package-lock.json
$ 
```

I have added credentials to Github Package Registry in https://app.dependabot.com using a personal access token with `read:packages` permissions.

Should I try adding an `.npmrc` file with `@myorg` scope to the repo?

```
@myorg:registry=https://npm.pkg.github.com
```

Edit: Adding the `.npmrc` file did not help.

**Comment by BraveLilToaster** [comment]
Would love to know if anyone has some insight on this. We have a bunch of linked packages.

**Comment by The-Code-Monkey** [comment]
I'm stuck on this too `circleci` just reads my `.npmrc` file and everything is fine why can't dependabot do the same thing.

**Comment by ashley-hurkoo** [comment]
Getting the same issue

**Comment by thiagozanetti** [comment]
Same for me

**Comment by thiagozanetti** [comment]
I created a new personal token with those rights:
![Screenshot from 2020-07-15 16-01-55](https://user-images.githubusercontent.com/333482/87584938-a6054e80-c6b4-11ea-989d-fb8666a7df8e.png)

Pasted in the dependabot var config form:
![Screenshot from 2020-07-15 16-04-19](https://user-images.githubusercontent.com/333482/87585077-dfd65500-c6b4-11ea-8a3f-b5f453163365.png)

And worked like a charm. I just don't know which of the selected rights did the trick. :smile:

**Comment by georgekrax** [comment]
This did not work for me unfortunately

**Comment by jurre** [comment]
Are you still running into this with the GH native version of Dependabot? It _seems_ like a configuration issue, because this feature works as expected for other users and some internal test repo's we have.

**Comment by georgekrax** [comment]
> Are you still running into this with the GH native version of Dependabot? It _seems_ like a configuration issue, because this feature works as expected for other users and some internal test repo's we have.

No, I managed to fix it. Thank you for your consideration.
