### ISSUE TITLE
python 3.7.7 support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#1768]
I got this error from dependabot:

```
Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000055a6253952d0 @requirements=[["=", #<Dependabot::Python::Version 3.7.7>]]>]]'.

Currently, the following Python versions are supported in Dependabot: 3.8.2, 3.8.1, 3.8.0, 3.7.6, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, 2.7.17, 2.7.16, 2.7.15, 2.7.14, 2.7.13.
```

But, `python@3.7.7` is released: https://www.python.org/downloads/release/python-377/

Original issue: https://github.com/wemake-services/wemake-django-template/issues/1096
Related: https://github.com/dependabot/dependabot-core/commit/c11629edcd2f78794bb0a13c5a5f6d22d6b49a15

**Comment by jurre** [comment]
Thanks for reporting this, it seems like a regression that was recently introduced, I’ll try to find time to look into it soon

**Comment by sobolevn** [comment]
@jurre I have sent a PR with the fix 👍
