### ISSUE TITLE
Dependabot incorrectly freezing Poetry path dependencies, causing schema validation failure

### ISSUE THREAD

**Issue by jtbeach** [dependabot/dependabot-core#1771]
Now that Dependabot has support for Poetry 1.x (🎉 ), some of my projects are now working, which is fantastic. I investigated the logs of the projects that are failing and they seem to contain the following logs:

```
updater | ERROR <job_27758849> Error processing typeguard (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_27758849> 
updater | <job_27758849> [RuntimeError]
updater | <job_27758849> The Poetry configuration is invalid:
updater | <job_27758849>   - [dependencies.blaze_util] {'path': '../blaze_util/', 'version': '0.1.0'} is not valid under any of the given schemas
updater | <job_27758849> 
```

My hypoethesis is that Dependabot has generated a new file that violates the Poetry JSON schema. Looking at the current schema for path dependencies (https://github.com/python-poetry/poetry/blob/44c60c4caed0c4474ca5dde205fe92f9a95b3e26/poetry/json/schemas/poetry-schema.json#L368), you can see that the `version` property is not allowed on path dependencies.

I am not a Ruby programmer, but I think the problematic function is here: https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_updater/pyproject_preparer.rb#L39. It is trying to freeze the versions of every dependency except the dependency being updated. It is always called with a list of exactly one dependency, the dependency to be updated.

We need to stop this line of code being executed for path dependencies (and probably others as well): https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_updater/pyproject_preparer.rb#L62

I will raise a PR with want I think is a fix -- I think even my novice Ruby skills should suffice for a code fix, but might need help with writing tests in rspec, etc.

**Comment by jtbeach** [comment]
Have one-line fix for this, but struggling to write the `rspec` tests

**Comment by jurre** [comment]
Hi @jtbeach feel free to open a draft PR with those changes and ping me on it, I'm not sure when I'll have time to look into it but I'd love to see it resolved so I'll see what I can do

**Comment by jtbeach** [comment]
> Hi @jtbeach feel free to open a draft PR with those changes and ping me on it, I'm not sure when I'll have time to look into it but I'd love to see it resolved so I'll see what I can do

Thanks @jurre -- that would be amazing! My draft PR is #1788
