### ISSUE TITLE
Python: mark test requirements as developer dependencies

### ISSUE THREAD

**Issue by iamogbz** [dependabot/dependabot-core#1784]
## Description
In our project we have 3 requirement lock files
1. `requirements.txt` for production dist
2. `test_requirements.txt` for running tests in ci
3. `dev_requirements.txt` which includes all of the above for local development

We also have auto merge configured for development dependencies

However dependabot fails to execute the auto merge because it marks `test_requirements.txt` file as a production dependency.

### Examples
- https://github.com/tophat/syrupy/pull/174
- https://github.com/tophat/syrupy/pull/175

### Related
- https://github.com/dependabot/dependabot-core/issues/1165

**Comment by mattt** [comment]
Hi @iamogbz. Automatic Merging is a feature of Dependabot Preview, which was [deprecated in April](https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/) and [shut down on August 3rd](https://github.blog/changelog/2021-08-03-dependabot-preview-is-shutting-down/). There are no current plans to add this functionality to GitHub-native Dependabot. See: [#1973 (comment)](https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321).
