### ISSUE TITLE
Use dependabot to distribute centralized github settings and actions

### ISSUE THREAD

**Issue by sheldonhull** [dependabot/dependabot-core#1785]
I have 80+ repos. 
I have some common github actions I'd like to apply across them and if I update or patch these actions I'd like to distribute to all these repos. 

For example: 
- Auto Assign Assignee
- PR Title Lint
- Merged on pr comment of shame 😁 

Could I leverage dependabot to point my `.github` folder directory updates from an upstream repo and merge these updates updates automatically on repos I've configured this with? I can script this locally of course, but think perhaps a better approach to grab common actions and pull back into the repo might be better.

**Comment by jurre** [comment]
I don't think Dependabot is the way to go for this, I do think some other teams within the company are looking at solving this, so I'm going to close out this issue here, and I'd suggest opening an issue in https://github.com/github/feedback/discussions instead.

**Comment by beatngu13** [comment]
@sheldonhull you might want to check out [GitHub Safe-Settings](https://github.com/github/safe-settings), "an app to manage policy-as-code and apply repository settings across an organization".
