### ISSUE TITLE
Package name conflict between private and public packages

### ISSUE THREAD

**Issue by ghost** [dependabot/dependabot-core#1796]
Currently we are facing a problem where we have package name conflict between public and private PyPi.
Dependabot finds first the package from public PyPi instead of looking first in the additional private PyPi that we added in settings.
This leads to Dependabot detects wrong version for a package by chosing the public one instead of the private.
It would be nice to have option to define wether Dependabot looks for packages inside private PyPi before public PyPi.

**Comment by jeffwidman** [comment]
Support for private registries was added a while ago (although after this issue was originally filed). Here's the blog post: https://github.blog/2021-03-15-dependabot-private-dependencies/
