### ISSUE TITLE
Invalid JSON in package.json results in Dependabot closing pull requests

### ISSUE THREAD

**Issue by StephanBijzitter** [dependabot/dependabot-core#180]
I was foolish enough to commit directly to master and i accidentally typed part of the commit message into `package.json`. Needless to say, this meant the JSON was invalid. The result: Dependabot closed the one pull request that was still open, stating it detected that the dependency is now up to date and the PR is no longer needed.

So this seems to be a small bug which occurs when it tries to parse invalid JSON. Or, of course, it's completely unrelated and the timing is just coincidental... you never really know.

If you type my github username in your email client you'll find previous conversations which will direct you to our github organisation, the repository in question ends with `-Tests` and the pull request number is 47. Hopefully you'll be able to pull some data and fix this if it really is caused by invalid JSON.

**Comment by greysteil** [comment]
Definitely a bug! Fixed, and with a regression spec to ensure it can't happen again. Thanks for reporting.
