### ISSUE TITLE
[bundler] Better library support

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#1805]
Hello! :wave:

Thanks so much for maintaining dependabot, I use it _all_ the time :)

I just got this PR to my library: https://github.com/deivid-rodriguez/pry-byebug/pull/295.

I would've expected dependabot to detect that it was only a development dependency update, and automerge it.

I think dependabot should be able to detect that it's creating a PR for a library (a criteria could be that there's a `gemspec` file in the root of the project), and in that case consider any update not touching the `gemspec` file as a development dependency update.

Thanks!

**Comment by jeffwidman** [comment]
Closing, as we [aren't doing native automerge](https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321), although there is a [workaround you can setup leveraging GitHub actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request).

**Comment by deivid-rodriguez** [comment]
Hei @jeffwidman. My issue was not related to automerge per se, but about detection of development vs production dependencies in the Ruby ecosystem. Even if automerge is no longer a thing, this can still be used for things, for example: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow.

That said, I'm not sure whether this is still an issue. If it is, I'll make sure to reopen!
