### ISSUE TITLE
Dependabot not identifying new versions of Dockerfiles with -rc-

### ISSUE THREAD

**Issue by lsnetsinger** [dependabot/dependabot-core#1819]
We are running into an issue on how dependabot looks at versions with -rc-

Here is a log file from dependabot showing it looking for a new version:
```
updater | INFO <job_25727523> Checking if ****/debian-ruby-2.6.5/db-libraries 1.0.5-rc-20200225145640 needs updating
proxy | 2020/03/09 18:20:42 GET *****/debian-ruby-2.6.5/db-libraries/tags/list
proxy | 2020/03/09 18:20:42 * authenticating docker ecr request (host: *****
proxy | 2020/03/09 18:20:43 200 *****/debian-ruby-2.6.5/db-libraries/tags/list
updater | INFO <job_25727523> Latest version is 1.0.5-rc-20200225145640
updater | INFO <job_25727523> No update needed for novu/debian-ruby-2.6.5/db-libraries 1.0.5-rc-20200225145640
```

However in the ECR Repo this file exists:
New:
1.0.6-rc-20200309163854 *****/debian-ruby-2.6.5/db-libraries:1.0.6-rc-20200309163854 03/09/20, 11:39:49 AM

Old:
1.0.5-rc-20200225145640 ****/debian-ruby-2.6.5/db-libraries:1.0.5-rc-20200225145640 02/25/20, 08:57:30 AM

The relevant code:

https://github.com/dependabot/dependabot-core/blob/master/docker/lib/dependabot/docker/update_checker.rb#L104-L131

It looks like this is what is happening:

```
'1.0.5-rc-20200225145640'.match(NAME_WITH_VERSION).named_captures
=> {"prefix"=>"1.0.5-rc-", "version"=>"20200225145640", "suffix"=>nil}
```

If I replace the -rc- with a -rc. everything works as expected.  If possible we would rather not change our naming convention as this would be a huge effort.

**Comment by jurre** [comment]
Hi @leo-novu, this is indeed an issue with Dependabot and it's on our backlog to fix this. However, we're currently working on integrating Dependabot natively into GitHub we've slowed down on package ecosystem support while we do this.

**Comment by leo-novu** [comment]
@jurre Thanks for the update.

**Comment by deivid-rodriguez** [comment]
Are you still having this issue @lsnetsinger?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
