### ISSUE TITLE
Dependabot links to the wrong project and changelog

### ISSUE THREAD

**Issue by cjolowicz** [dependabot/dependabot-core#1833]
**Package manage/ecosystem**
Python
**Manifest contents prior to update**
N/A: The manifest update is correct.
**Updated dependency**
Bump darglint from 1.2.3 to 1.3.0
**What you expected to see, versus what you actually saw**
The project name `darglint` should be linked to:

- https://github.com/terrencepreilly/darglint

Instead it is linked to:

- https://github.com/raddessi/SublimeLinter-contrib-darglint

darglint provides the correct `url` in its setup.py.

The changelog also comes from the wrong project.

Dependabot PR: https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/148

**Comment by pavera** [comment]
This is a pretty old issue, I wonder if this is still happening or if it is reproducible with any current packages? I know we've fixed a number of issues around metadata gathering, so unless I hear otherwise in the next week I'll be closing this issue.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
