### ISSUE TITLE
Dependabot user for Github Actions

### ISSUE THREAD

**Issue by staticdev** [dependabot/dependabot-core#1844]
**Package manage/ecosystem**
python and github_actions
**Manifest contents prior to update**
https://github.com/staticdev/humanizer-portugues/blob/master/.dependabot/config.yml
**Updated dependency**
Any.
**What you expected to see, versus what you actually saw**
I have created an action to automerge PRs from dependabot. The user is/was dependabot[bot], but the opened PRs by this user is never triggered. I saw that PRs have this dependabot-preview user/app associated (did it change?). I saw it working on this event: https://www.youtube.com/watch?v=0ahRkhrOePo&list=PLbBkH8AQhXxHDEVFC6Fjoq7jX79Lb05RJ&index=31&t=900s
**Images of the diff or a link to the PR, issue or logs**
Example PRs: https://github.com/staticdev/humanizer-portugues/pull/39

**Comment by thepwagner** [comment]
👋 

- `dependabot-preview` PRs are opened by https://dependabot.com - https://dependabot.com/blog/hello-github/#what-is-happening-to-the-existing-dependabot-product
- `dependabot` PRs are opened by the GitHub-integrated version of Dependabot - https://help.github.com/en/github/managing-security-vulnerabilities/viewing-and-updating-vulnerable-dependencies-in-your-repository


It looks like your repository is setup with `dependabot-preview` (as https://github.com/staticdev/humanizer-portugues/pull/39 was opened by `dependabot-preview[bot]`), but your automerge action is configured for `dependabot` ( https://github.com/staticdev/humanizer-portugues/blob/master/.github/workflows/dependabot.yml#L12 ) 

You should be able to match against both usernames, the pattern is relatively common: https://github.com/search?q=github.actor+%3D%3D+%27dependabot%5Bbot%5D%27&type=Code

**Comment by staticdev** [comment]
Thanks a lot @thepwagner, I will try that now and give feedback here!

**Comment by staticdev** [comment]
Wonderful! That was the problem @thepwagner!!
