### ISSUE TITLE
Config file doesn't validate Maven versions.

### ISSUE THREAD

**Issue by blakemorgan** [dependabot/dependabot-core#1845]
**Package manage/ecosystem**

`java:maven`

**What you expected to see, versus what you actually saw**

When I use a correct [version requirement string](https://maven.apache.org/pom.html#dependency-version-requirement-specification) in Maven, I expect my comfig.yml file to be validated, however instead I get the following error (both as an issue in a repo and using the config validator online): 

```
The property '#/update_configs/0/ignored_updates/0/version_requirement' is an invalid version requirement for a java:maven ignore condition
```

If I were to remove the `version_requirement` line from that section of the config file, it works fine. Below is an example of the `ignored_updates` section of a config file I'm testing.

```yml
ignored_updates:
  - match:
      dependency_name: "org.springframework:spring-core"
      version_requirement: "[4.0.0.RELEASE,)"
```

_In this example, all updates greater than Spring 3 should be ignored._

One workaround to please the config validator is to remove the comma, but looking at the source code, I think Dependabot Core would treat that as an "equals" constraint as opposed to a "range" constraint".

I've taken a look at the [requirement.rb](https://github.com/dependabot/dependabot-core/blob/master/maven/lib/dependabot/maven/requirement.rb) file for the Maven part of the Dependabot core and tested the functions. The core handles version ranges as expected; it's just the config validator that is throwing issues. I tried to look at its code, but I couldn't find it. I am happy to take a look at this issue some more if someone can point me in the right direction.

**Comment by eager** [comment]
@blakemorgan we’ve run into this, too, and I think I have a fix in #2273. 

I haven’t actually tried this in a real `config.yml`, but I’m fairly certain you can work around the issue by using the Gem format, `version_requirement: ">=4.0.0.RELEASE".

**Comment by blakemorgan** [comment]
@eager Thank you for your PR. Hopefully that fixes it. I have tried using the Gem format for the past couple months, but seem to get intermittent success. It could well be user error when using Gem format, but I haven't been able to fully observe if it's functioning properly.

**Comment by blakemorgan** [comment]
I can confirm that even after including the following code segment in the `ignored_updates` section of the config.yml file, I still get dependency updates for the packages:

```yml
- match:
    dependency_name: "swagger.annotations.version"
    version_requirement: ">= 1.5.9" # Requires Java 8
```
