### ISSUE TITLE
commit_message exclude_directory

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#1853]
It would be neat if the `commit_message` configuration option documented on https://dependabot.com/docs/config-file/#commit_message had an option I would name e.g. `exclude_directory` which would let it ditch that "... in $DIRECTORY" which is appended to the commit message and PR title.

This would be "nicer" in repos such as https://github.com/vorburger/fineract/pulls/app%2Fdependabot-preview (but see https://github.com/dependabot/feedback/issues/933 ...) where I had to configure the "/fineract-provider" (because it wasn't able to it figure out from the `settings.gradle`), but because that's really the only "module", having that in title is just "noise".

@greysteil

**Comment by greysteil** [comment]
Thanks for the feedback @vorburger. I'm not responsible for @dependabot anymore - that honour goes to @infin8x and @mayakacz, so I'll leave this with them. (I work on GitHub's code scanning and secret scanning these days.)
