### ISSUE TITLE
Disable package-lock.json update when nothing changes in package.json

### ISSUE THREAD

**Issue by nikolas** [dependabot/dependabot-core#1867]
Hello,
I would like to prevent dependabot from opening pull requests that only update the package-lock.json, when there are no changes in package.json. For example: https://github.com/ccnmtl/anticipatoryguidance-pack/pull/95

Is there a configuration option for this?

**Comment by IncPlusPlus** [comment]
You might want to take a look at this comment. https://github.com/dependabot/dependabot-core/issues/2601#issuecomment-704050892

**Comment by mattt** [comment]
As mentioned by @IncPlusPlus, it sounds like the `versioning-strategy` option should allow you to configure this behavior. See: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy
