### ISSUE TITLE
I got 2 comments back

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#189]
Hey @greysteil 

I closed a PR like this:
![screenshot 2017-12-22 09 13 27](https://user-images.githubusercontent.com/995707/34290568-756757da-e6f8-11e7-80e7-8d006632ecdb.png)

But I got 2 comments afterwards, maybe one is too much?
![screenshot 2017-12-22 09 13 33](https://user-images.githubusercontent.com/995707/34290575-824e6042-e6f8-11e7-9725-377da63a9449.png)

Cheers, Oskar

**Comment by greysteil** [comment]
Sounds sensible - we'll now only give those close instructions once per PR.

**Comment by OskarStark** [comment]
Super, thank you for the fast feedback 👍
