### ISSUE TITLE
Understanding Typescript DefinitelyTyped `@types/package` pattern

### ISSUE THREAD

**Issue by simonrussell** [dependabot/dependabot-core#1892]
It would be great if Dependabot understood the Typescript DefinitelyTyped packages pattern.  So if I have `my-package` and `@types/my-package` in my project it would know to keep (at least) the major versions aligned.  Obviously if the versions are specified in the `package.json` properly this isn't a huge problem, but sometimes Dependabot likes to get ambitious and jump to the next major version.  It would be good to have the types and the main package updated in the same PR.

A side problem is `@types/node`, which should always match(ish -- at least major version) the version of Node you're using.  Even if I have this specified with `^12.12.42` I only get PRs trying to update it to the next major release (and I'm missing out on minor updates).

I'm assuming I can configure this in the dependabot config file? But it would be great it if was the default; this is a pretty common pattern.

**Comment by zxxc** [comment]
Not sure we can address it config file. at least I haven't found how.
I was trying to exclude @types, but i think it's bad as we don't have tsc checks

**Comment by exvuma** [comment]
@zxxc You can ignore packages starting with @types in your config file by adding the [`ignore` flag](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore). Could you share why you want to exclude @types? Do you prefer to update them manually?

**Comment by exvuma** [comment]
The Dependabot team is exploring how to tackle this problem. We'd love your input! Please fill out [this form](https://forms.gle/x8N4rTENHPnN1AbW8) to schedule time to chat with us. ❤️

**Comment by mattt** [comment]
👋 Greetings from the Dependabot team! I'm happy to report that we're actively working on this functionality. We just opened our first PR with some (pending, currently failing) end-to-end tests describing the expected behavior here: https://github.com/dependabot/dependabot-core/pull/4992. 

I'll be sure to link to all the follow-up PRs that build out the remaining functionality. Please let us know if you have any thoughts or questions about what we should be doing. Thanks!

**Comment by exvuma** [comment]
Thanks for all the patience and input folks! We are excited to announce that Dependabot will now sync @types with the corresponding package. See more details on our [changelog](https://github.blog/changelog/2022-05-10-dependabot-keeps-types-dependencies-in-sync-with-updated-packages/). We can't wait to hear your feedback on this [thread](https://github.com/github/feedback/discussions/16339) 😄
