### ISSUE TITLE
Dependabot opened a PR with no files changed

### ISSUE THREAD

**Issue by SebastiaanNijland** [dependabot/dependabot-core#190]
We currently have an open pr with an empty commit by dependabot. I'm not sure why it happened (the commit message etc seems to be fine). There are two other PRs open in which only the lock file was updated, not the package.json - but I was told this has to do with carets (^) before our versions and an opt-in feature of dependabot. I'm not aware of any changes on our end, so this might be a bug as well?

You have had previous conversations with @StephanBijzitter - you should be able to find our github organisation, the repository in question ends with -Frontend and the pull request number is 512.

**Comment by greysteil** [comment]
Thanks. This is definitely a bug on our end and I’m looking into it now

**Comment by greysteil** [comment]
This should be fixed - can you confirm?

**Comment by SebastiaanNijland** [comment]
Yes, it's fixed for both cases! Thanks 👍
