### ISSUE TITLE
Add support for private git(hub) repos

### ISSUE THREAD

**Issue by OmgImAlexis** [dependabot/dependabot-core#1902]
Opening an issue to track this independently from  https://github.com/dependabot/dependabot-core/issues/1461

@feelepxyz can you please close this when it's added?

**Comment by jeffwidman** [comment]
Can someone explain what this issue is about?

I read the linked thread, but unfortunately still not comprehending... is it somehow related to https://github.com/dependabot/dependabot-core/issues/6015 ?

**Comment by jeffwidman** [comment]
It looks like this was referring to https://github.com/dependabot/dependabot-core/issues/1461#issuecomment-638899033 where at the time we didn't support private git repos. That has since shipped in https://github.blog/2021-03-15-dependabot-private-dependencies/ and documented in
