### ISSUE TITLE
List affected files in your repo for version bump

### ISSUE THREAD

**Issue by mattstrayer** [dependabot/dependabot-core#1904]
It'd be incredibly useful to have a list of affected files in the dependabot PR.

Example:

**PR: Bump uuid from 7.0.3 to 8.1.0**
<details>
  <summary>Affected Files</summary>

-    www.github.com/me/myrepo/src/utils.js
-    www.github.com/me/myrepo/src/core.js

</details>

Or even more detail, showing where the package is used:

**PR: Bump uuid from 7.0.3 to 8.1.0**
<details>
  <summary>Affected Files</summary>

-    www.github.com/me/myrepo/src/utils.js
```javascript
import { v4 as uuidv4 } from 'uuid'
// ...
const ID = v4()
```

</details>

**Comment by feelepxyz** [comment]
@mattstrayer you should get something close to this if you click on the compare link under `> Commits`, from there you can view the files that have changed: e.g https://github.com/axios/axios/compare/v0.17.1...v0.19.2

**Comment by mattstrayer** [comment]
@feelepxyz yeah, that'll work for the package changes. I was thinking that the `Affected Files` would list out my repo's files that could be affected by the update's version bump. At a very high level, showing direct links to files in my repo where I'm importing / using the package. It would help pinpoint files that would need checking before the PR should be merged.

**Comment by feelepxyz** [comment]
Ah I see that would be super cool! Definitely something we’d like to be able to do but it’s a significant piece of work. We’re thinking of similar features around security updates where we could highlight if your code uses some of the vulnerable methods.

**Comment by mattstrayer** [comment]
I'd be happy to put some work in on this. Will keep you posted.

**Comment by feelepxyz** [comment]
@mattstrayer nice one, I just wanted to caution that we'll probably not solve this on Dependabot's side and instead leverage a lot of the existing GitHub infrastructure around code-scanning and semantic analysis.

**Comment by mattstrayer** [comment]
@feelepxyz that makes sense. I forget you're on the inside now! Well, I'd appreciate it if this idea could be floated around internally as an additional improvement alongside your planned work with security scanning. 🚀

**Comment by abdulapopoola** [comment]
Closing out as stale
