### ISSUE TITLE
dependabot.yml for Github problems with prettier

### ISSUE THREAD

**Issue by staticdev** [dependabot/dependabot-core#1907]
**Package manage/ecosystem**
any on github

**Manifest contents prior to update**
n/a

**Updated dependency**
n/a

**What you expected to see, versus what you actually saw**
When I ask app.dependabot.com to create or update config file it creates a /.github/dependabot.yml with single quotes, giving error to prettier pre-commit hooks. I expected these file to use double quotes and indentation to be compatible with most YAML common linters.
 
See a fix commit example: https://github.com/staticdev/django-sorting-bootstrap/commit/5bc6ce011b7647b5c01f4d6c2fae35e06e773055

**Images of the diff or a link to the PR, issue or logs**
n/a

**Comment by feelepxyz** [comment]
@staticdev thanks for the feedback, will look into changing this. For some reason the default Ruby YAML formatted outputs both single and double quotes.

**Comment by staticdev** [comment]
@feelepxyz maybe you should open an issue for them. The YAML is also missing spaces for standard indentation.

I will be happy to retest it if you manage to change that.

**Comment by feelepxyz** [comment]
@staticdev pushed a fix for this 👍

**Comment by staticdev** [comment]
@feelepxyz I've tested it. The double quotes are now correct, but there is still missing indentation. I tryed on this sandbox repo:
See the fix commit now just added spaces:
https://github.com/staticdev/sandbox/commit/bf7b8f493e97847683752c883399e3e03eab3074

**Comment by feelepxyz** [comment]
> @feelepxyz I've tested it. The double quotes are now correct, but there is still missing indentation. I tryed on this sandbox repo:

Ah cool, will take a look, hopefully a quick fix.

**Comment by feelepxyz** [comment]
Hm struggling with this, Ruby Psych doesn't seem to indent the `-` when setting the indentation, you can only control the indentation between the `-` and the key, e.g.

```yml
updates:
-      package-ecosystem: npm
       ...
```

Similarly, doesn't seem entirely straight forward to run Ruby Prettier as a library 😕

**Comment by staticdev** [comment]
@feelepxyz one workaround is to setup a Github Action for dependabot that uses pre-commit, then it is very simple:

```
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
```
