### ISSUE TITLE
Stop generating report for deleted package.json

### ISSUE THREAD

**Issue by trollepierre** [dependabot/dependabot-core#1917]
Hello,
On the Github of my package, I am receiving dependabot alert for a deleted package.json.
You can see in the screenshot that no folder /client exist in the https://github.com/trollepierre/recontact_travel_blog project. (It has been renamed in /front several months ago)
This is kind of frustrated, and I don't know how to prevent that.
Feel free to ask more precision.

**Package manage/ecosystem**
Javascript
**Manifest contents prior to update**
https://github.com/trollepierre/recontact_travel_blog/network/alerts

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Images of the diff or a link to the PR, issue or logs**

<img width="943" alt="Capture d’écran 2020-06-17 à 23 21 48" src="https://user-images.githubusercontent.com/8363334/84951931-741ebd80-b0f1-11ea-8081-7bc3f2ab54b8.png">

<img width="593" alt="Capture d’écran 2020-06-17 à 23 22 32" src="https://user-images.githubusercontent.com/8363334/84951940-7719ae00-b0f1-11ea-84bf-20b5691c54af.png">

**Comment by feelepxyz** [comment]
@trollepierre looks like the Dependency Graph had these files cached. I've re-detected your manifest files and the client files are no longer showing up so will close this out. Let me know if you have any further issues.
