### ISSUE TITLE
Does dependabot support making conventional commits when updating?

### ISSUE THREAD

**Issue by felixfbecker** [dependabot/dependabot-core#192]
I couldn't find this on the docs page.
I.e. when the update was a semver-patch update, prefix the commit message with `fix: `, if it was a semver-minor update, prefix the commit message with `feat: `, if it was a semver-major update use `chore: `. That allows automatic semantic releases of the depending module

https://conventionalcommits.org/

**Comment by greysteil** [comment]
Interesting. We create [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages) for those who use them (see https://github.com/wireapp/wire-web-packages/pull/142 for an example). Would that work?

If not, I could update Dependabot to detect the above style and use it if appropriate.

**Comment by felixfbecker** [comment]
`chore` unfortunately doesn't trigger a new release with semantic-release. Taking my example from #191:

- editor extension depends on language service

The editor extension needs to get a new feature release with all the dependencies zipped if the language server gets a new feature. If the language server gets a bug fix, the editor extension needs to get a bug fix release.

**Comment by greysteil** [comment]
Interesting. Looks like there's some non-trivial thinking to be done on this one - Angular themselves use `chore` for all their [package updates](https://github.com/angular/angular.js/commits/master/package.json), for example... 

My hunch is that Dependabot is best off staying neutral on this, but do you want to port the issue over to https://github.com/dependabot/feedback and see if anyone else chimes in?

**Comment by felixfbecker** [comment]
Yeah, a library like Angular doesn't need to (and shouldn't) do this, because when I `npm install angular` npm will install the latest version of transitive dependencies. But at some point you always have to bundle your dependencies, for application deployments, building installers, building a Docker image, bundling+minification, or in my example for the VS Code marketplace.

**Comment by felixfbecker** [comment]
This issue was moved to dependabot/feedback#67

**Comment by greysteil** [comment]
Awesome, thanks!

**Comment by oprogramador** [comment]
@felixfbecker 

Isn't dependabot/feedback#67 a quite different issue?
