### ISSUE TITLE
Native Dependabot breaks when transferring a repo

### ISSUE THREAD

**Issue by MrBartusek** [dependabot/dependabot-core#1923]
**Package manage/ecosystem**
javascript

**What you expected to see, versus what you actually saw**
So, I recently switched from depenabot-preview to native and it was working fine. A couple of days after that I moved my repo from a personal account to organization (from `MrBartusek/ReplacementBot` to [ReplacementBot/ReplacementBot](https://github.com/ReplacementBot/ReplacementBot)) After that, even when I have [depnabot.yaml](https://github.com/ReplacementBot/ReplacementBot/blob/master/.github/dependabot.yml) depenabot is not starting and prompting me to create a depenabot file

**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/23432278/85163658-730d9d80-b263-11ea-80b5-ed693c66a78f.png)

EDIT: Updating file fixes issue https://github.com/ReplacementBot/ReplacementBot/commit/13d54b70ccd607e9389e05e63ca01bfc029b2398

**Comment by jeffwidman** [comment]
Sorry about this! Glad it's fixed though.

**Comment by MrBartusek** [comment]
Today is finally the day that my oldest issue is closed, after 2 years and 2 months 🥳 Thanks @jeffwidman ❤️
