### ISSUE TITLE
Trouble with Python with pip-tools

### ISSUE THREAD

**Issue by polothy** [dependabot/dependabot-core#1945]
**Package manage/ecosystem**
python:pip-compile

**Manifest contents prior to update**
https://github.com/polothy/dependabot-python-test/blob/master/requirements.in
https://github.com/polothy/dependabot-python-test/blob/master/requirements.txt

**Updated dependency**
Expected CDK packages to upgrade from 1.44.0 to 1.47.0

**What you expected to see, versus what you actually saw**
No PRs were sent, but via the logs, dependabot did seem to figure out the current version and the new version, but was unable to update _something_ with the new version. I'm not actually sure what dependabot is trying to modify, I guess I assumed it would modify `requirements.txt` in addition to `requirements.in` if those were pinned.

Also, if you go to here, https://github.com/polothy/dependabot-python-test/network/updates it looks like dependabot is trying to do dependency updates in the `pyproject.toml`, but I'm using `pip-tools` and a `requirements.in` file.  If I remove the `pyproject.toml`, then it does switch to `requirements.in`, but the same problem still occurs.  Fails to update _something_ with the new updates.

**Images of the diff or a link to the PR, issue or logs**
Logs: https://github.com/polothy/dependabot-python-test/network/updates/32669292

My problem was originally discovered in a private repository but I made this one to reproduce the problem: https://github.com/polothy/dependabot-python-test

I'm not entirely sure what dependabot is expecting in the `requirements.in` file.  I originally had contents like:
```
aws-cdk.aws-cloudformation==1.44.0
aws-cdk.aws-codebuild==1.44.0
aws-cdk.aws-codepipeline-actions==1.44.0
aws-cdk.aws-codepipeline==1.44.0
aws-cdk.aws-kms==1.44.0
aws-cdk.aws-lambda==1.44.0
aws-cdk.aws-s3==1.44.0
aws-cdk.core==1.44.0
pyyaml==5.3.1
```
Guess I was expecting dependabot to update the pins and run `pip-compile` to update `requirements.txt`.

Any help or advice would be appreciated, cheers!  And I can update my test repository with whatever you like or you can even send PRs and I'll try to merge them ASAP!

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by polothy** [comment]
I'm not really sure, feel free to close if you want.
