### ISSUE TITLE
Add configuration flag for commit message style

### ISSUE THREAD

**Issue by HendrikThePendric** [dependabot/dependabot-core#1949]
We are rewriting an old app on the `next` branch of an existing repo. We've only introduced semantic commit messages in the new app a few commits ago and we now noticed our dependabot PRs can't be auto-merged because the bot isn't producing semantic messages.

My colleague pointed me to [this blog post](https://dependabot.com/blog/little-touches/) and commit https://github.com/dependabot/dependabot-core/commit/77bd3b823d740c65d3a89f1e7027a3ca4fbf09e9. So the problem is that:
- We want to use semantic commit messages, and have just started to do so
- But we also have a vast amount of non-semantic messages from the past
- The logic that determines the commit message style is based on the historic commit message style
- This logic doesn't really fit with re-writes, or more generally speaking when introducing semantic commit messages to a project at a later stage

So my feature request would be to introduce a configuration flag to explicitly set the commit message style for situations where inferring the preferred style from past commits fails.

**Comment by jurre** [comment]
I think this should be possible:

https://dependabot.com/docs/config-file/#commit_message

Or if you're using the github native version:

https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message

Let me know if that's not what you were looking for

**Comment by HendrikThePendric** [comment]
Sorry, should have read the docs more carefully. Thanks for the quick reply.
