### ISSUE TITLE
Dependencies specified in plugin configurations are missed out

### ISSUE THREAD

**Issue by PyvesB** [dependabot/dependabot-core#1950]
**Package manage/ecosystem**

Maven

**Manifest contents prior to update**

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>test</groupId>
    <artifactId>test-dependabot</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <java.version>8</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.google.dagger</groupId>
            <artifactId>dagger</artifactId>
            <version>2.28.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.dagger</groupId>
                            <artifactId>dagger-compiler</artifactId>
                            <version>2.28.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
**Updated dependency**

The Dagger dependency is expected to be updated to version 2.28.1 in the above example.

**What you expected to see, versus what you actually saw**

Only the version specified in the `dependency` block is updated, the one in the Maven Compiler `configuration` is missed out which creates an inconsistent _pom.xml_.

**Images of the diff or a link to the PR, issue or logs**

Real life PR demonstrating the issue: https://github.com/PyvesB/AdvancedAchievements/pull/766
Note that the POM structure is more complicated that the aforementioned example but leads to the same problem.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

We've shipped a number of fixups to Maven parsing lately, even a couple in the last week.

Additionally, our underlying Maven parsing is all regex/ruby, and we want to long term move to using Maven itself as that's much less brittle. So while we're happy to fix bugs that are currently affecting folks, we're not adding new features and for bugs that aren't currently affecting folks we'd rather invest that energy into figuring out how to switch to Maven long term.

I'm going to close, as I assume this either isn't reproducible or isn't currently affecting you. But if I'm wrong please comment and we can re-open.
