### ISSUE TITLE
Dependabot config: Remove (or relax) the limit on number of `update` nodes

### ISSUE THREAD

**Issue by BillWagner** [dependabot/dependabot-core#1952]
We run into to the limit on number of update nodes in our sample code repositories:

https://github.com/dotnet/samples
https://github.com/dotnet/dotnet-api-docs
https://github.com/dotnet/docs

Each of these repositories have many more than 100 project files.

We understand that this is an edge case, but hopefully it's not a difficult change. 

Also, in the meantime, we have a workaround to filter out project files where the only dependency is the `TargetFramework`. See dependabot/feedback#975 for details on that request.

**Comment by jeffwidman** [comment]
@BillWagner is this issue still happening? I'm triaging some old issues and noticed this is over 2 years old... and I just looked at the recent commit log and appears that Dependabot is opening PR's: https://github.com/dotnet/samples/commits/main

**Comment by BillWagner** [comment]
Thanks @jeffwidman 

Yes, this has been fixed.

I'll close it.
