### ISSUE TITLE
NuGet / .NET Core: Update `TargetFramework` to latest LTS version

### ISSUE THREAD

**Issue by BillWagner** [dependabot/dependabot-core#1953]
This is similar to:
* https://github.com/dependabot/dependabot-core/issues/2165

We would like to have dependabot find and suggest changes to the Target Framework node in our .NET Core project files.

In time, we'd like to have all our samples project on the latest LTS release (currently .NET Core 3.1) and snap forward when the next LTS release ships. 

Currently, dependabot does not create PRs or issue any updates for the target framework.

**Comment by jeffwidman** [comment]
Related:
* https://github.com/dependabot/dependabot-core/issues/2651
* https://github.com/dependabot/dependabot-core/issues/2247

**Comment by abdulapopoola** [comment]
Closing out as stale
