### ISSUE TITLE
Can't validate version 2 of configuration files

### ISSUE THREAD

**Issue by gnarea** [dependabot/dependabot-core#1957]
The [online validator](https://dependabot.com/docs/config-file/validator/) doesn't support version 2 files. Here's a file that Dependabot itself [created](https://github.com/relaycorp/relaynet-pong/pull/85):

![dependabot](https://user-images.githubusercontent.com/369863/85227191-cd2d7080-b3d3-11ea-8b90-0a1adb9741f8.png)

**Comment by EmaSuriano** [comment]
@feelepxyz is it possible to add this link into the official [Github Documentation](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message), thanks to this tool I found the typo I was having! I think it will help other people too 😄

**Comment by GMartinez-Sisti** [comment]
> @gnarea we have one here: https://dependabot.com/docs/config-file-beta/validator/
> We also add a status check to the commit when you change the file in github validating the config file.

Hi @feelepxyz, the status check is not being executed with the MR. Can you please confirm, or let me know where I can configure this?

Thanks

**Comment by asciimike** [comment]
Closing this, as there is a validator. I'm going to see about linking it from https://docs.github.com (we won't be able to embed it, but can link).

If there are other issues (e.g. status checks), please create a new issue with an MCVE and we can triage!
