### ISSUE TITLE
Request for multiple update schedules against the same package manager/branch/directory

### ISSUE THREAD

**Issue by glichtenISP** [dependabot/dependabot-core#1961]
For our Go projects, we have both internal and external dependencies. We'd like to be able to update them on separate schedules, doing internal daily, and external monthly. Due to the fact that all dependencies are kept in `go.mod` at the root directory, we are unable to use dependabot for both. Eg, the following fails:

``` 
 - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "github.com/companyname/*"
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          update_type: "all"

**Comment by asciimike** [comment]
Closing as a dupe of #1778
