### ISSUE TITLE
Security update on stabilisation branches

### ISSUE THREAD

**Issue by sbrunner** [dependabot/dependabot-core#1962]
With the new GitHub Dependabot I didn't find any way to configure the branches on which one the security updates was applied. 

For us, is a real need to be sure that our stabilization versions (not on the main (master) branch) doesn't contain security issue.

Thanks in advance.

**Comment by jeffwidman** [comment]
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2767
