### ISSUE TITLE
Ruby updates appeared to get permanently stuck when gem was temporarily unavailable

### ISSUE THREAD

**Issue by geoffharcourt** [dependabot/dependabot-core#1964]
The repository is private: https://github.com/commonlit/commonlit. We've filed a ticket with the suggested form that links to this issue.

Hi, we saw an issue that persisted for over a day with Ruby that we're not sure our workaround has solved or just sidestepped.

In the last 1-2 weeks, it seems that immediately after Rubygems gets a new gem version published that some pulls of the gem will fail with the gem not being found. (Not sure if this is related to database replication, sharding, etc. on their end.) We've seen this happen in our CI system, our review applications, and locally. It looks like this happened in Dependabot, and then the state with the gem not being available somehow got cached and stuck.

![Screenshot 2020-06-12 08 28 58](https://user-images.githubusercontent.com/319471/84502936-3d771c00-ac87-11ea-819b-e1f1d19e5981.png)

This issue started happening just as the referenced version of the aws-sdk-polly gem was published, and attempts to re-bump our repository reproduced this same error over and over again despite the gem being available (not yanked) on Rubygems generally.

We manually updated the package today, but wanted to flag this in case it blocked future updates.

**Package manage/ecosystem**
ruby:bundler
**Manifest contents prior to update**

**Updated dependency**

aws-sdk-polly 1.31.0 -> 1.31.1. 

Because this was a failure before the PR opened, it's not clear if this was an attempt to specifically update the polly gem or it it was an attempt to update a different gem.

**What you expected to see, versus what you actually saw**

We bumped our application several times manually at the Dependabot config page hoping that it would either update aws-sdk-polly or move on to another gem (we have Dependabot set to only open one Ruby-related PR at a time.

**Comment by jeffwidman** [comment]
Closing as this appeared to be a localized issue to a particular yanked gem that happened two years ago.
