### ISSUE TITLE
Contributor link broken

### ISSUE THREAD

**Issue by mpurnell1** [dependabot/dependabot-core#1966]
**Package manage/ecosystem**

**Manifest contents prior to update**

**Updated dependency**

**What you expected to see, versus what you actually saw**

At the home page of a repository that dependabot has contributed to, hovering on Contributors and clicking dependabot's profile picture redirects to https://github.com/dependabot%5Bbot%5D instead of https://github.com/dependabot-bot
**Images of the diff or a link to the PR, issue or logs**

https://github.com/johnhh2/django-forum

**Comment by jurre** [comment]
I believe this has since been resolved and we now link to the dependabot docs so I'll close out this issue.
