### ISSUE TITLE
DIRECTORY_PATH not working with gitlab-ci and kubernetes runner // Relative path in requirements.in

### ISSUE THREAD

**Issue by MaxWinterstein** [dependabot/dependabot-core#1967]
I am setting up dependabot on a private gitlab instance by using dependabot-script.  
It works great for some flat python project, having one module and one requirements.txt in its root.

The problem repository has some other structure, like
```
README.MD
frontend/
backend/
backend/requirements.in
backend/module1
backend/module2
...
```

When running it just llike the working scheduled pipeline, i end up with this error:

```
$ bundle exec ruby ./generic-update-script.rb
 NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
 Faraday::Error::ClientError.inherited called from /builds/myProjectNameSpace/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
 /builds/myProjectNameSpace/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/file_fetcher.rb:274:in `path_setup_files': The following path based dependencies could not be retrieved: file:./module1/setup.py, file:./module2/setup.py, (Dependabot::PathDependenciesNotReachable)
 	from /builds/myProjectNameSpace/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/file_fetcher.rb:50:in `fetch_files'
 	from /builds/myProjectNameSpace/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:55:in `files'
 	from ./generic-update-script.rb:115:in `<main>'
 Fetching pip dependency files for  #myProjectNameSpace/myProject
```

**Package manage/ecosystem**
pip-compile
**Manifest contents prior to update**
requirements.in
```
-e module1[test]
-e module2[test]
```

Sadly usind `DIRECTORY_PATH=backend/` does not work. Now there is no file found to proceed.

What am i missing out? 

---
# Update
Tried it w/ a ember.js repo, that also has the main code inside a subdirectory. DIRECTORY_PATH did the trick here, fine.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

Gitlab support is very much community driven. If you are able to identify a bug, we're happy to review a PR, or if it's an issue that affects all all dependabot users, not just gitlab users, we can potentially help resolve it.

Given the description, this looks like a config/setup problem, not a depenedabot-core problem. Espeically since you added an update indicating that you seemed to have figured it out. So I'm going to close this.
