### ISSUE TITLE
Ignore Docker Tag Suffix via Configuration

### ISSUE THREAD

**Issue by tymartin-novu** [dependabot/dependabot-core#1968]
My organization would like to leverage Dependabot to propagate Docker images downstream; however, our image tags have a format of `<version>-<build-timestamp>` (e.g. `1.0.4-20200608160520Z`). The build timestamp is just a simple piece of metadata that we tack on to our Docker images to show build time, but we do not care to have that play a role the update check process. Our current tag format doesn't appear to fit into the current Dependabot capabilities, but I feel like something that could work for us and provide extra Dependabot flexibility for other folks could be to leverage a configuration flag to ignore Docker tag suffixes from the Docker `update_checker.rb`. Pair that with something like:

```
diff --git a/docker/lib/dependabot/docker/update_checker.rb b/docker/lib/dependabot/docker/update_checker.rb
index df3280597..494a6ad13 100644
--- a/docker/lib/dependabot/docker/update_checker.rb
+++ b/docker/lib/dependabot/docker/update_checker.rb
@@ -131,13 +133,22 @@ module Dependabot
         original_prefix = prefix_of(dependency.version)
         original_suffix = suffix_of(dependency.version)
         original_format = format_of(dependency.version)
+
+        filtered_tags = tags_from_registry.
+                        select { |tag| tag.match?(NAME_WITH_VERSION) }.
+                        select { |tag| prefix_of(tag) == original_prefix }.
+                        select { |tag| format_of(tag) == original_format }.
+                        reject { |tag| commit_sha_suffix?(tag) }
+
+        unless @skip_suffix
+          filtered_tags = filtered_tags.
+                          select { |tag| suffix_of(tag) == original_suffix }
+        end

-        tags_from_registry.
-          select { |tag| tag.match?(NAME_WITH_VERSION) }.
-          select { |tag| prefix_of(tag) == original_prefix }.
-          select { |tag| suffix_of(tag) == original_suffix }.
-          select { |tag| format_of(tag) == original_format }.
-          reject { |tag| commit_sha_suffix?(tag) }
+        filtered_tags
       end

       def remove_version_downgrades(candidate_tags)
```

I would be happy to contribute a PR, but I am having difficulty finding where the configuration spec is defined. If folks think this would be beneficial and someone could point me to the place in the code where that configuration spec is defined, I could whip up a PR for review.

**Comment by deivid-rodriguez** [comment]
@tymartin-novu Are you still having this issue? As of today, I suspect your tags are handled just fine automatically.

**Comment by jeffwidman** [comment]
Yeah, I think this is probably working fine now after your improvements to the docker tag parsing / version comparison.

I'm going to close, but if for some reason we're wrong please comment and we can re-open.
