### ISSUE TITLE
Django 2.2.13 security release not being triggered.

### ISSUE THREAD

**Issue by YPCrumble** [dependabot/dependabot-core#1970]
Django recently released a [security fix](https://docs.djangoproject.com/en/3.0/releases/2.2.13/) to their LTS version that isn't being triggered by Dependabot.

I have my settings set to security fixes only and have not received PR's for any of my repos.

Is the issue that Django has a 3.0.x release and so Dependabot cannot find security releases for version 2.0.x? Or should this release have triggered a PR?

**Package manage/ecosystem**

**Manifest contents prior to update**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Images of the diff or a link to the PR, issue or logs**

**Comment by jurre** [comment]
Given that these CVEs are now in the advisory DB (which Dependabot Alerts needs to be triggered, which Dependabot Updates needs to be triggered), I'm going to assume that this has been resolved and close out the issue.
