### ISSUE TITLE
Semver 2.0 versions not handled correctly for nuget pre-release dependencies

### ISSUE THREAD

**Issue by andreasohlund** [dependabot/dependabot-core#1972]
When the bot open PRs for pre-releases the version parsing doesn't work properly for semver 2.0 versions.

https://github.com/Particular/NServiceBus.Gateway.Sql/pull/34 shows this where `3.2.0-alpha.66` is a higher version than `3.2.0-alpha0014` so no PR should have been created.

**Comment by gitfool** [comment]
I just hit a variant of this:
```
Bump coverlet.collector from 1.3.1-preview.24.g6479f627e4 to 1.3.1-preview.8.ge848786b0d
```

**Comment by gitfool** [comment]
A quick look at the relevant [Dependabot source](https://github.com/dependabot/dependabot-core/blob/089b6974508610ffa05fe9f44f41123cd6c3f72c/nuget/lib/dependabot/nuget/version.rb#L60-L81) confirms that the prerelease part of the version is still compared _lexically_, without considering dot separated identifiers consisting of only digits that should be compared _numerically_:
```ruby
prerelease_string.<=>(other_prerelease_string)
```

**Comment by andreasohlund** [comment]
Any updates on this? (we had this happen again recently - https://github.com/Particular/NServiceBus.Callbacks/pull/198)

**Comment by adamralph** [comment]
and again - https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/269/files

**Comment by adamralph** [comment]
and again - https://github.com/Particular/NServiceBus.AmazonSQS/pull/807, https://github.com/Particular/NServiceBus.AmazonSQS/pull/808, https://github.com/Particular/NServiceBus.AmazonSQS/pull/809

Is there any likelihood of this being prioritised? This behaviour is killing the entire purpose of dependabot.

**Comment by adamralph** [comment]
This keeps biting again and again and again.

Is there any intention of fixing it?

**Comment by adamralph** [comment]
Have the maintainers even acknowledged that the problem exists? I noticed that it has not been marked as a bug, like other issues have — https://github.com/dependabot/dependabot-core/issues?q=is%3Aissue+is%3Aopen+label%3A%22T%3A+bug+%F0%9F%90%9E%22

**Comment by josesimoes** [comment]
This keeps being a _tad_ annoying... 😉
