### ISSUE TITLE
Link to wrong package in tifffile PR description 

### ISSUE THREAD

**Issue by Czaki** [dependabot/dependabot-core#1974]
**Package manage/ecosystem**

python
**Manifest contents prior to update**

https://github.com/4DNucleome/PartSeg/pull/64
**Updated dependency**

tifffile
**What you expected to see, versus what you actually saw**
when creating PR with new version of tifffile i description it links to https://github.com/pearu/pylibtiff instead of https://github.com/cgohlke/tifffile. Second one is different package than tifffile on pypi. 

**Images of the diff or a link to the PR, issue or logs**

https://github.com/4DNucleome/PartSeg/pull/64

**Comment by abdulapopoola** [comment]
Closing out as stale
