### ISSUE TITLE
How to use Dependabot on a large GitHub Org such as https://github.com/apache/ (without write access)

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#1980]
https://issues.apache.org/jira/browse/FINERACT-961

It's such a shame that my favourite of all Bots requires to be installed as a GitHub App with write access. While this works great for personal repos, and on small GH Orgs where ones is or can easily get an Org Admin to Accept, it's a apparently Hard Stop Road Blocker preventing to use Dependabot e.g. on https://github.com/apache/fineract - open source fintech software reducing poverty one line of code a time! (I'm running https://www.fineract.dev, if you want to try it out.)

This because Apache Software Foundation (ASF) Infrastructure team, rightfully I guess, cannot accept install GitHub Apps granting Bots write access to any one of their thousands of Git repos (note e.g. [TAMAYA-390](https://issues.apache.org/jira/browse/TAMAYA-390) and [INFRA-19685](https://issues.apache.org/jira/browse/INFRA-19685) referring to dependabot/feedback#22. I've also seen dependabot/feedback#193.

I love Dependabot so much ;-) that I'm using it a complicated cumbersome manual workflow using which I "transfer" https://github.com/vorburger/fineract/pulls/app%2Fdependabot-preview onto https://github.com/apache/fineract/pulls?q=is%3Aopen+is%3Apr+author%3Avorburger+bump with 
I hacked (had, from a past life) [a small personal github2github.sh script](https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/master/bin/github2github.sh), but that just seems so dumb...
 
*Is there really NO way that we could somehow figure out a pragmatic way to make this possible?*

@greysteil hope you don't mind I tag you for visibility and feedback on this, as [we had been in touch in the past](https://github.com/dependabot/dependabot-core/issues?q=author%3Avorburger+) - hope you're well?  I'm using Dependabot again - now in a completely different new context then when I last reached out... ;-)

https://issues.apache.org/jira/browse/FINERACT-961

**Comment by feelepxyz** [comment]
Closing this as fixed with Dependabot Version updates, which recently reached GA: https://github.blog/changelog/2021-03-31-dependabot-version-updates-are-now-generally-available/
