### ISSUE TITLE
Logs indicate unable to get latest version of a dependency

### ISSUE THREAD

**Issue by MysterAitch** [dependabot/dependabot-core#1981]
**Package manage/ecosystem**
Java / Gradle - dependency on maven central

**What you expected to see, versus what you actually saw**
One specific dependency hasn't been updating. 

Dependabot seems to recognise that the dependency is outdated and needs updating (note the logs quoted below), but the logs indicate that it is not picking up the version number (`Latest version is `).

PRs are being setup for other dependencies, so it seems it is specific to this one dependency _(note that the [latest version on maven central is 3.15.21](https://mvnrepository.com/artifact/com.github.javaparser/javaparser-symbol-solver-core/3.15.21) and has been up for a while now)_.

**Images of the diff or a link to the PR, issue or logs**
I presume that the job # quoted below is sufficient to point towards the relevant logs. If additional information is needed, please do let me know.

```
updater | INFO <job_32307966> Checking if com.github.javaparser:javaparser-symbol-solver-core 3.15.18 needs updating

updater | INFO <job_32307966> Latest version is 

updater | INFO <job_32307966> Requirements to unlock update_not_possible

updater | INFO <job_32307966> Requirements update strategy 

updater | INFO <job_32307966> No update possible for com.github.javaparser:javaparser-symbol-solver-core 3.15.18
```

**Comment by abdulapopoola** [comment]
Closing out as stale
