### ISSUE TITLE
Dependabot didn't add label to PR

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#1982]
I just noticed that in https://github.com/panorama-ed/nds/pull/5571, `app/dependabot-preview` created the PR but didn't add the `dependencies` label as usual. (We did not override the default in our configuration.)

Did something go wrong there?

**Comment by jeffwidman** [comment]
Closing as no longer reproducible per ☝️ . If it re-occurs please file a new issue.
