### ISSUE TITLE
Missing current version field in GitHub action output

### ISSUE THREAD

**Issue by jsoref** [dependabot/dependabot-core#1985]
**Package manage/ecosystem**
GitHub Actions
**Manifest contents prior to update**
An outdated version of `actions/checkout`

**Updated dependency**

**What you expected to see, versus what you actually saw**
I saw this:
```
updater | INFO <job_31581840> Checking if actions/checkout  needs updating
  proxy | 2020/04/30 22:26:29 GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2020/04/30 22:26:29 * authenticating git server request (host: github.com)
  proxy | 2020/04/30 22:26:29 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_31581840> Latest version is 01aecccf739ca6ff86c0539fbc67a7a5007bbc81
updater | INFO <job_31581840> Requirements to unlock own
updater | INFO <job_31581840> Requirements update strategy 
updater | INFO <job_31581840> Updating actions/checkout from  to 01aecccf739ca6ff86c0539fbc67a7a5007bbc81
updater | INFO <job_31581840> Submitting actions/checkout pull request for creation
```
There are two things that strike me as suspicious:

* `if actions/checkout  needs`
* `Updating actions/checkout from  to`

Specifically the two spaces (` ` and `  `) in a row.

I half expect the first one to include some form of a version.
I definitely expect a version between `from` and `to`.

**Images of the diff or a link to the PR, issue or logs**

**Comment by deivid-rodriguez** [comment]
Hi, sorry for the delay.

This is probably working fine now, please double check.

If not, what's the original content of the `actions/checkout` line in the workflow?

**Comment by jsoref** [comment]
(I'm pretty sure I actively lost the identity of the original request's repository, and I'm not sure I could find one that's currently behind for that action...)

Hi @deivid-rodriguez, here's an example from the last 24 hours (I think):
```
updater | INFO <job_511354460> Checking if google-github-actions/auth 0 needs updating
  proxy | 2022/11/14 05:01:37 [066] GET https://github.com:443/google-github-actions/auth.git/info/refs?service=git-upload-pack
  proxy | 2022/11/14 05:01:37 [066] * authenticating git server request (host: github.com)
  proxy | 2022/11/14 05:01:37 [066] 200 https://github.com:443/google-github-actions/auth.git/info/refs?service=git-upload-pack
updater | INFO <job_511354460> Latest version is 1
updater | INFO <job_511354460> Requirements to unlock own
updater | INFO <job_511354460> Requirements update strategy 
  proxy | 2022/11/14 05:01:37 [068] GET ...
  proxy | 2022/11/14 05:01:37 [068] * authenticating github api request
updater | INFO <job_511354460> Updating google-github-actions/auth from 0 to 1
```

This is technically an improvement over the originally reported behavior..

It'd be nice if this change be applied if you could:
```diff
-updater | INFO <job_511354460> Checking if google-github-actions/auth 0 needs updating
+updater | INFO <job_511354460> Checking if google-github-actions/auth@0 needs updating
```
i.e. the floating `0` in the output really should be tied to the action as it would appear in a workflow. You obviously can't do that for the `from ... to ...` form, but there's more prose there, and thus it's ok.

**Comment by deivid-rodriguez** [comment]
> This is technically an improvement over the originally reported behavior..

Is this correct? What's the current version in your workflow?

I created a WIP for the message tweak although not fully sold this is worth changing: https://github.com/dependabot/dependabot-core/pull/6143.

**Comment by jsoref** [comment]
I don't have a workflow. We're using the `/network/updates/` endpoint.

**Comment by deivid-rodriguez** [comment]
Mmmm, I don't get it. Dependabot needs some dependency files to update, it should be picking that v0 from somewhere 😅.

In any case, I see that the action you're using has a [v0 tag](https://github.com/google-github-actions/auth/releases/tag/v0), so this looks correct now!

Closing as fixed, but let me know if you still have issues!
