### ISSUE TITLE
[Node] not all deps get updated

### ISSUE THREAD

**Issue by gengjiawen** [dependabot/dependabot-core#1989]
https://github.com/gengjiawen/graphql-ts-server

`apollo-server` and `graphql` not sending pull request.

![image](https://user-images.githubusercontent.com/3759816/79717016-fb76cd00-830a-11ea-887e-53dc529e74cc.png)

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

This ticket is nearly three years old and we've shipped a lot of features/improvements since then, particularly to node.

I assume this is no longer reproducible, so I'm going to close but if for some reason I'm wrong please comment and we can reopen.
