### ISSUE TITLE
[PHP] Add support for PEcL package

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#1990]
Hi,

Some `php` components are distributed as pecl package (since require a compilation step).

It thinks it could be very useful (for 
https://www.iceframework.org/ for example) to be tracked by **dependabot**.

Also it could be accurate when you are using some new engines as https://www.swoole.co.uk or 
https://roadrunner.dev/

Regards,

**Comment by mattt** [comment]
Hi, @waghanza. We don't currently have plans to add support for PECL packages. However, since you opened this issue, it looks like Ice Framework has [added Composer support](https://github.com/ice/framework/blob/dev/composer.json), so hopefully that resolves your underlying issue.

**Comment by waghanza** [comment]
Hi @mattt,

You mean that having 
```json
{
  "require": {
    "iceframework/framework": "~1.8.0"
  }
}
```

will install (compile) `ice`.

Not sure this could be done like this

@mruz

**Comment by mruz** [comment]
@waghanza it should work like this, and you're right, it will compile `ice`, not install it from pecl.

**Comment by waghanza** [comment]
I have this @mruz when I run `composer install --no-dev --prefer-dist --classmap-authoritative`

**Comment by mattt** [comment]
@waghanza @mruz In the interest of keeping the conversation specific to `dependabot-core`, please consider moving this thread to [a new issue on `ice/framework`](https://github.com/ice/framework/issues/new).
