### ISSUE TITLE
Go: dependabot doesn't remove old version of package from go.sum when updating

### ISSUE THREAD

**Issue by echarrod** [dependabot/dependabot-core#1995]
dependabot correctly updates the go.mod, and adds the new version to go.sum. But it doesn't remove the old version from go.sum.

Recent examples of this (see dependabot original commit):
- https://github.com/getyoti/yoti-go-sdk/pull/111
- https://github.com/getyoti/yoti-go-sdk/pull/112
- https://github.com/getyoti/yoti-go-sdk/pull/120

_Created https://github.com/dependabot/dependabot-core/issues/1707, but looks like this is a better place to report bugs_

**Comment by yp05327** [comment]
It seems that this issue is not fixed yet:
https://github.com/TeaChart/teachart/pull/7
https://github.com/TeaChart/teachart/pull/8
https://github.com/TeaChart/teachart/pull/9
