### ISSUE TITLE
Way to view all security PRs

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#1998]
It's been almost a year since [this conversation](https://github.com/dependabot/feedback/issues/493#issuecomment-497760182) and we still don't have a way to view all security PRs that Dependabot creates in one place. We regularly see two types of security PRs:

1. Tickets created by `dependabot` in response to a GitHub Security Alert. These do **_not_** use the `security` label. Example: https://github.com/panorama-ed/intersect/pull/148
2. Tickets created by `dependabot-preview` that **_do_** include the `security` label. Example: https://github.com/panorama-ed/intersect/pull/151

From our end there is often very little rhyme or reason to whether a ticket falls into category 1 or 2 (I assume it has to do with whether the GitHub Security Alert infrastructure or the Dependabot security infrastructure finds the CVE first). However, the result is annoying—GitHub gives no way through the UI to view all of these in one place, because we can't limit our search to the `app/dependabot` user or to the `security` label.

At the very least, could they just all be labeled with `security`?

**Comment by mwaddell** [comment]
We also would like a way to see all of the historical dependabot security alerts that we've addressed.  Currently, when a security issue is no longer present in the code, the security alert does not just change to "Closed" - it is deleted entirely.

I would either like to see all of the previously addressed security alerts as "Closed" or have a way to filter for their corresponding PRs using a label such as "security"

**Comment by jeffwidman** [comment]
Related:
* #5825

**Comment by jeffwidman** [comment]
This was filed back when Dependabot was still getting migrated to GitHub. Now there's only one way, not two as described in the ticket.

And as requested, let's track this under adding labels:
* https://github.com/dependabot/dependabot-core/issues/4761

So closing.
