### ISSUE TITLE
Impossible to add email in Codacy. Can you remove symbols from auto generated email?

### ISSUE THREAD

**Issue by lapanton** [dependabot/dependabot-core#2002]
HI! 
But I saw when dependabot generate new PR it also generate email like this: 27856297+dependabot-preview[bot]@users.noreply.github.com, but in this case we cannot pass validation HTML5 specification for email. And when i am trying to add email to Codacy i can't do it. 
Is there anyway that dependabot can use a valid HTML5 specification email address? 
Do you have any workaround for this?

**Comment by deivid-rodriguez** [comment]
I think this was probably fixed by the migration from and app to being built into GitHub, so I'll close this. But please reopen if still an issue!
