### ISSUE TITLE
Dependabot has stopped updating requirements.in after recent update

### ISSUE THREAD

**Issue by echarrod** [dependabot/dependabot-core#2005]
An update in the last few days has caused the requirements.in to not be updated by dependabot, which is then used by pip-compile (from [pip-tools](https://pypi.org/project/pip-tools/)) to generate the requirements.txt. 

Working examples previously (which updated the requirements.in):
- https://github.com/getyoti/yoti-python-sdk/pull/172
- https://github.com/getyoti/yoti-python-sdk/pull/173
- https://github.com/getyoti/yoti-python-sdk/pull/176

Updates which haven't updated the requirements.in
- https://github.com/getyoti/yoti-python-sdk/pull/179 (I did it manually on this one)
- https://github.com/getyoti/yoti-python-sdk/pull/180

**Comment by jurre** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since, is this still happening, or has this problem been resolved and can we close this issue?

**Comment by echarrod** [comment]
Looks fine now, thanks. I'll close
