### ISSUE TITLE
Match Docker -slim tags when updating

### ISSUE THREAD

**Issue by legowerewolf** [dependabot/dependabot-core#2006]
My repo is at https://github.com/legowerewolf/discordbot.ts

The problem that keeps happening is when Dependabot tries to update my Dockerfile - I have a multi-stage build set up, depending on two different tags of the same image. 

In this repo, I depend on `node:x.y.z` as a builder, and `node:x.y.z-slim` as the final image source. Dependabot keeps on changing the slim image to the full image, as in https://github.com/legowerewolf/discordbot.ts/pull/395/commits/a99f989166c535bd4c451a15d665e763afce1f2d

**Comment by deivid-rodriguez** [comment]
I think this was actually fixed by https://github.com/dependabot/dependabot-core/pull/5560, so let me close this. If still happening, please reopen!
