### ISSUE TITLE
Don't forcefully add the rust label for rust dependency upgrades

### ISSUE THREAD

**Issue by bjorn3** [dependabot/dependabot-core#2007]
The only other kind of dependency I have setup dependabot for are github actions. The full repo is written in rust, so the label `rust` adds no value. I tried removing the label completely, but dependabot just creates it again.

**Comment by jurre** [comment]
Latest docs are https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#labels, but seems like this has been resolved, so I'm going to close out this issue
