### ISSUE TITLE
[composer] Support for COMPOSER_ROOT_VERSION

### ISSUE THREAD

**Issue by localheinz** [dependabot/dependabot-core#2008]
When working with packages that depend on themselves, Dependabot currently cannot resolve dependencies.

For an example, see:

- https://github.com/sebastianbergmann/phpunit/issues/4152
- https://app.dependabot.com/accounts/sebastianbergmann/update-logs/27685096

In build environments that can be controlled by us, we can solve this problem by specifying a `COMPOSER_ROOT_VERSION` environment variable.

For related documentation, see:

- https://getcomposer.org/doc/03-cli.md#composer-root-version

For related code in `composer/composer`, see:

- https://github.com/composer/composer/search?q=COMPOSER_ROOT_VERSION

For an example where this problem is fixed on GitHub Actions, see:

- https://github.com/sebastianbergmann/phpunit/pull/4154

I have no idea how this could be solved on your side, but perhaps this is a scenario that could consider?

/cc @sebastianbergmann

**Comment by jurre** [comment]
This seems like a dupe with https://github.com/dependabot/dependabot-core/issues/3888, given that issue has a bit more info, even though this was opened sooner, I'll keep the other issue open and close this one out.
