### ISSUE TITLE
Unparseable go (module) file

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#2009]
Hi @feelepxyz,

The following file https://github.com/the-benchmarker/web-frameworks/blob/fdc3b6f02f698b54fc4d24b554f70990c3bec5f1/go/chi/go.mod#L3
is not parseable.

Issue raise in https://github.com/the-benchmarker/web-frameworks/issues/2405

However a `go get` is working ?

I think it could be a good idea, during the `alpha` period, to redo the parsing, with the `+incompatible` flag adde ?

Regards,

**Comment by jurre** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since, is this still happening, or has this problem been resolved and can we close this issue?
