### ISSUE TITLE
Archived repositories should be excluded

### ISSUE THREAD

**Issue by LeoColomb** [dependabot/dependabot-core#201]
Since [GitHub let archiving repos](https://github.com/blog/2460-archiving-repositories) (and GitLab too), dependabot should take care of [the _archived_ property](https://developer.github.com/v3/repos/#response-3) to:
* Avoid listing archived repo when creating a new dependabot project.
* Kill any attempt to bump dependencies on an archived repo.

🌈

**Comment by greysteil** [comment]
Great feedback - just saw an error on our side from this.

I'll get this done today. Thanks!

**Comment by greysteil** [comment]
Done and deployed. Thanks again!

**Comment by kofemann** [comment]
Looks like this issue is re-appeared https://github.com/javaee/grizzly/pull/2002

**Comment by brrygrdn** [comment]
Hi @kofemann Sorry for the delay in follow-up - it seems javaee/grizzly was very briefly unarchived around the time this PR was created. I can confirm that Dependabot considers it inactive now and shouldn't open any further PRs.

**Comment by kofemann** [comment]
@brrygrdn Hm...I have my doubts there, but I can't prof the opposite :) (Thanks for the bot, btw)
