### ISSUE TITLE
Not updating point releases for Javascript dependencies when current versions are exactly major numbers

### ISSUE THREAD

**Issue by amclin** [dependabot/dependabot-core#2010]
I've noticed a pattern with dependencies not updating if the current version is a major X.0.0 release.

#### Example:
Current version in package.json: [`"read-config-file": "^5.0.0"`](https://github.com/amclin/aem-packager/blob/master/package.json#L64)
Latest version (22 days old) according to NPM: [5.0.2](https://www.npmjs.com/package/read-config-file)

I've seen this happen with a bunch of different dependencies across several different NPM-based projects. It seems that if a dependency updates to `X.0.0`, then dependabot doesn't trigger updates to `X.0.1`, `X.0.2`, etc. But if you manually update to `X.0.1`, then dependabot correctly resumes with `X.0.2`

Based on the symptoms, I would wager something is amiss in the regex pattern matching for versions.

#### Example Repo:
https://github.com/amclin/aem-packager

#### Dependabot config:
https://github.com/amclin/aem-packager/blob/master/.dependabot/config.yml

**Comment by jurre** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since, is this still happening, or has this problem been resolved and can we close this issue?
