### ISSUE TITLE
GET repos endpoint error. Incompatible with "IP allow" rules?

### ISSUE THREAD

**Issue by byjrack** [dependabot/dependabot-core#2014]
So using GHEC with SSO and IP Allow whitelisting. I believe the PAT issued on my User is properly scoped for SSO in that Org, but my gut is telling me the IP allow is blocking your call into our Org?  Only see a 500 on my side so hard to tell.

Any chance you have a dedicated CIDR block for dependabot I could whitelist to test?

**Comment by turnopil** [comment]
Hm. I have the same question for a GitHub-native Dependabot.
I thought that is consuming Git CIDR IPs - https://api.github.com/meta
But it's not like that, see the output of `dig app.dependabot.com`

**Comment by jurre** [comment]
You should now be able to use the IPs listed in the `dependabot` section in  https://api.github.com/meta

**Comment by KeisukeYamashita** [comment]
@jurre @feelepxyz Hi team! My GitHub Organization has IP restrictions and the Dependabot can't reach my org. As jurre posted (https://github.com/dependabot/dependabot-core/issues/2014#issuecomment-979984720), we can get the IP ranges of the Dependabot from the meta API but in the official doc, it says

> We do not recommend allowing by IP address

Ref: [About GitHub's IP addresses](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses)

I want to allow the Dependabot to get allowed without adding an IP range entry to my org's allowlist. Is it possible?
If so, it will help users maintain the Dependabot access and will reduce toil for monitoring the IP range changes by calling the meta API. 

Thank you in advance!
