### ISSUE TITLE
Dependabot couldn't parse the go.mod found at /go.mod. (github.com/mholt/certmagic)

### ISSUE THREAD

**Issue by sabatale** [dependabot/dependabot-core#2017]
Hello,

I've started to use dependabot but get a weird issue now. Would anyone be able to point me to some documentation that could help me prevent this issue from happening? Does this mean my go.mod file is corrupted?

```
Dependabot couldn't parse the go.mod found at /go.mod.

The error Dependabot encountered was:

go: github.com/mholt/certmagic@v0.10.0: parsing go.mod:
	module declares its path as: github.com/caddyserver/certmagic
	        but was required as: github.com/mholt/certmagic
```

**Comment by jurre** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since, is this still happening, or has this problem been resolved and can we close this issue?
