### ISSUE TITLE
Ignore / Check in-range updates

### ISSUE THREAD

**Issue by hrueger** [dependabot/dependabot-core#2019]
Is there a way to make dependabot work like `greenkeeper`? I'd like to have in-range updates checked by the CI and if they don't pass, an issue should be created. If they pass, no pull request should be created as it is in-range.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

I realize this model would be helpful for libraries, but it doesn't really fit the model of Dependabot, which is about bumping packages through PR's... So I don't see us rolling this out in Dependabot on GitHub.

You could wire up something like this in a GitHub Action by running `dependabot-core` yourself using an entrypoint like the https://github.com/dependabot/cli/ or https://github.com/dependabot/dependabot-core/#dry-run-script, both of which are currently more focused on debugging, so they'll show when packages need to be updated but won't actually create PR's... and then wire the output of them into another action that parses the output, checks if it's in range and triggers your CI.
