### ISSUE TITLE
Not tracking some maven artifacts? Accidental exclusion perhaps?

### ISSUE THREAD

**Issue by planetf1** [dependabot/dependabot-core#2022]
I am a maintainer on a public repo: https://github.com/odpi/egeria . A recent PR opened by dependabot was: https://github.com/odpi/egeria/pull/2677

This PR updates spring boot, but it failed during our PR build (verification) as we enforce upper bounds checking, and had backlevel org.apache.tomcat.embed:tomcat-embed-core, needing to bump from 9.0.29 to :9.0.30

What surprised me was that dependabot doesn't seem to be noticing the updates to tomcat-embed-core. I'm wondering if in the past perhaps they were ignored, or if something else is amiss. I'm not sure how to check?

This artifact has been updated, so I updated the PR to add it in - no problem, but thought dependabot would have at least created that other PR too, which I would then have merged first?

Thanks

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

We've shipped a number of fixups to Maven parsing lately, even a couple in the last week.

Additionally, our underlying Maven parsing is all regex/ruby, and we want to long term move to using Maven itself as that's much less brittle. So while we're happy to fix bugs that are currently affecting folks, we're not adding new features and for bugs that aren't currently affecting folks we'd rather invest that energy into figuring out how to switch to Maven long term.

I'm going to close, as I assume this either isn't reproducible or isn't currently affecting you. But if I'm wrong please comment and we can re-open.
