### ISSUE TITLE
Using a property for the version of an already defined dependency is interpreted as removed dependency

### ISSUE THREAD

**Issue by ingogriebsch** [dependabot/dependabot-core#2023]
If we have defined an explicit version for a dependency in a Maven project and then use a property for the version it looks like Dependabot is interpreting this change as if the dependency is removed.

* We have a repository containing a Spring Boot service which is build through Maven,
* We define a dependency with an explicit version.
* If we push the changes Dependabot will check the version and create a Pull Request if the version is outdated.
* We reconfigure the pom.xml and define the version as a property to use the property as a placeholder in the version element of the dependency.
* If we build the project locally, Maven realize the property placeholder and use the correct version for the dependency.
* If we push the changes, Dependabot will check the pom and close the open Pull Request with the comment '_Looks like <dependency> is no longer a dependency, so this is no longer needed_'.

**Comment by jeffwidman** [comment]
👋 This is a three-year old ticket, and we've shipped a lot of changes since this.

I'm going to close assuming it's no longer reproducible as I don't see any additional 👍 on the ticket... but if you're still affected, please comment and we'll happily reopen.
