### ISSUE TITLE
Pull Request not created if former pull request closed through Dependabot

### ISSUE THREAD

**Issue by ingogriebsch** [dependabot/dependabot-core#2024]
It looks like that Dependabot is not creating a new Pull Request for a dependency which was first used, removed and then used again, at least if it closed the first Pull Request on it's own.

* We have a repository containing a Spring Boot service which is build through Maven,
* We used a dependency (which was outdated).
* Dependabot created a Pull Request to update that dependency (because it found out that it is outdated).
* We removed the dependency from the dependency list and pushed the changes.
* Dependabot realized the push, checked again and closed the Pull Request because it thinks that the Pull Request is not necessary anymore.
* Some time later we added the same dependency again.
* If Dependabot checks the dependencies it logs that it realized the outdated dependency but it won't create a Pull Request because there is already one available (the closed one?!).

```
updater | INFO <job_24666348> Checking if org.flywaydb.flyway-test-extensions:flyway-spring-test 6.0.0 needs updating
  proxy | 2020/02/27 12:43:51 GET https://repo.maven.apache.org:443/maven2/org/flywaydb/flyway-test-extensions/flyway-spring-test/maven-metadata.xml
  proxy | 2020/02/27 12:43:51 200 https://repo.maven.apache.org:443/maven2/org/flywaydb/flyway-test-extensions/flyway-spring-test/maven-metadata.xml
  proxy | 2020/02/27 12:43:51 HEAD https://repo.maven.apache.org:443/maven2/org/flywaydb/flyway-test-extensions/flyway-spring-test/6.1.0/flyway-spring-test-6.1.0.jar
  proxy | 2020/02/27 12:43:51 200 https://repo.maven.apache.org:443/maven2/org/flywaydb/flyway-test-extensions/flyway-spring-test/6.1.0/flyway-spring-test-6.1.0.jar
updater | INFO <job_24666348> Latest version is 6.1.0
updater | INFO <job_24666348> Pull request already exists for org.flywaydb.flyway-test-extensions:flyway-spring-test with latest version 6.1.0
```

**Comment by jurre** [comment]
I think you can just reopen that old PR? This is mostly working as intended, when you close a PR manually Dependabot treats that as a signal to ignore it. It would be pretty annoying if Dependabot would keep opening PRs for versions that you closed the PR for already.
