### ISSUE TITLE
Add support for Yarn v2

### ISSUE THREAD

**Issue by Basaingeal** [dependabot/dependabot-core#2030]
The lockfile that yarn v2 generates is different from the lockfile that yarn v1 generates. Dependabot currently always creates Yarn v1 lockfiles, but yarn v2 can't run `yarn install` using a v1 yarn lockfile. This is the error message received:

```
 YAMLException: bad indentation of a mapping entry at line 4, column 15:
       dependencies:
                   ^
       dependencies:
                   ^
```

**Comment by ylemkimon** [comment]
For the time being, I'm using a GitHub Actions workflow to fix and update PRs created by Dependabot. See https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-671131912.

**Comment by feelepxyz** [comment]
Closing in favour of https://github.com/dependabot/dependabot-core/issues/1297
