### ISSUE TITLE
Live update support for go.mod

### ISSUE THREAD

**Issue by alex** [dependabot/dependabot-core#2031]
Some languages support Live Updates, where dependabot sends PRs as the updates are released, instead of on a cron-like schedule. go.mod only supports updates on the cron-schedule (with Daily being the most frequent).

I'd be most grateful if this was implemented for go!

I suspect this could be implemented by "tailing" https://index.golang.org/ to know when updated packages are available.

**Comment by jurre** [comment]
Given that this issue if for a feature that is (at least for now) not supported in the GitHub-native version of Dependabot and Dependabot Preview has been shut down, I'm going to close this issue. If we decide to bring live updates back in the future, we'll make sure to keep this in mind.
