### ISSUE TITLE
Improve upgrade version for VS Code extensions

### ISSUE THREAD

**Issue by apupier** [dependabot/dependabot-core#2035]
Inside a [VS Code extension project](https://code.visualstudio.com/api), when upgrading the [@types/vscode version inside the package.json](https://github.com/camel-tooling/vscode-wsdl2rest/blob/0f96c4e941dac1ee163eac1790972f55c89cf537/package.json#L74). It is required to also upgrade (when specified), the [VS Code engine version](https://github.com/camel-tooling/vscode-wsdl2rest/blob/0f96c4e941dac1ee163eac1790972f55c89cf537/package.json#L37).

Otherwise, the build is failing with:
`ERROR  @types/vscode ^1.42.0 greater than engines.vscode ^1.41.0. Consider upgrade engines.vscode or use an older @types/vscode version`

**Comment by cklim4405** [comment]
> Inside a [VS Code extension project](https://code.visualstudio.com/api), when upgrading the [@types/vscode version inside the package.json](https://github.com/camel-tooling/vscode-wsdl2rest/blob/0f96c4e941dac1ee163eac1790972f55c89cf537/package.json#L74). It is required to also upgrade (when specified), the [VS Code engine version](https://github.com/camel-tooling/vscode-wsdl2rest/blob/0f96c4e941dac1ee163eac1790972f55c89cf537/package.json#L37).
> 
> Otherwise, the build is failing with:
> `ERROR  @types/vscode ^1.42.0 greater than engines.vscode ^1.41.0. Consider upgrade engines.vscode or use an older @types/vscode version`
>

**Comment by abdulapopoola** [comment]
Closing as stale
