### ISSUE TITLE
Add update_schedule : "fortnightly" 

### ISSUE THREAD

**Issue by andycarrell** [dependabot/dependabot-core#2038]
I've searched issues quickly and don't think there's a duplicate.

Basically, allow the update schedule to be every 2 weeks - as an extension to this feature it would be awesome to be able to specify the number of days, or weeks.

I'd love to be able to contribute but don't even know where to start with @depedabot/dependabot-core

**Comment by mwarkentin** [comment]
Any updates on this? It would be nice to be able to define schedules on a per-project basis (which it sounds like the cron option might do) - some teams might want an early monday PR to review, other teams might want to get things at a different time.

**Comment by EwoutH** [comment]
@feelepxyz Do you have any updates to share about moving Dependabot to a cron schedule?

**Comment by lovemybabygirl42000** [comment]
Yes I got the money just trying to get a play everyone want me to have a
job for 6 mtg or More

**Comment by LukaPrebil** [comment]
@feelepxyz have there been any updates regarding this functionality?

**Comment by feelepxyz** [comment]
Nothing planned around this yet unfortunately. I think we'll move towards a solution that can leverage actions down the line, where we could then piggy back of actions cron syntax. It's going to be a good while before we can get to this though.

**Comment by jeffwidman** [comment]
As mentioned above, we're unlikely to add this specifically, more likely to add support for cron, which is tracked here:
* https://github.com/dependabot/dependabot-core/issues/6339

**Comment by jeffwidman** [comment]
Also, implementing this/cron schedule isn't within `dependabot-core` which is a library... but would instead have to happen in the Dependabot service at GitHub. 

If you want this now, you can always run Dependabot standalone using an entrypoint like https://github.com/dependabot/dependabot-script and then schedule that to execute on whatever custom schedule suits your fancy.
