### ISSUE TITLE
Support private GitHub packages

### ISSUE THREAD

**Issue by BuonOmo** [dependabot/dependabot-core#2045]
We switched from Gemfury to GitHub private packages thinking that you would be able to make a PR for a project using a GitHub package. It looks like it is not the case.

Do you plan on supporting GitHub private packages since Dependabot is part of GitHub? 

By supporting I mean supporting having a Gemfile containing private repositories, not filing security issues for those dependencies.

If you do not, do you have any alternative to offer for us to have automated security PRs?

![example](https://user-images.githubusercontent.com/11378424/73061004-71e56980-3e99-11ea-91d0-b48594e78619.png)

**Comment by jurre** [comment]
It's coming! Please follow https://github.com/github/roadmap/issues/67 for updates 🎉
