### ISSUE TITLE
Doesn't detect updated deps

### ISSUE THREAD

**Issue by abitrolly** [dependabot/dependabot-core#2047]
https://github.com/minsk-hackerspace/hackerspace.by/pull/401

the change is already committed https://github.com/minsk-hackerspace/hackerspace.by/commit/f318af9ed6ddb7943aede15f223e1e0cb6c978a0 but @dependabot doesn't detect it.

**Comment by jeffwidman** [comment]
My guess is this was a timing issue, and the job that was checking dependencies had already fired and so was using a snapshot that was out of date by the time the PR was actually created.

The race is inevitable, possibly just before opening the PR, we coulddoublecheck that the relevant lockfile hasn't changed... if it has, we bail out. But that's a bigger discussion and there may be reasons it won't work... Given that this ticket is 2.5 years old, so I'm going to close it as stale for now. If the race starts happening with more frequency, then I'm sure we'll see it in our metrics and support tickets, and then we'll prioritize taking a deeper look at how to mitigate it.
