### ISSUE TITLE
Add option to auto-increment the package.json version number as a patch when anything is changed.

### ISSUE THREAD

**Issue by chriseyre2000** [dependabot/dependabot-core#2048]
I would like to have the option to have dependabot auto-increment the package.json version number as a patch which anything is changed.

This would allow the dependencies in libraries to be pushed out to client applications quicker.

**Comment by dangoslen** [comment]
This could also be done for most package managers supported by Dependabot. 

As an alternative, supplying a callable script from within the repository that bumps the version number would be really useful.

**Comment by jurre** [comment]
I think https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy `increase` might be what you're looking for?

**Comment by dangoslen** [comment]
@jurre thanks for providing that link.

However, I don't believe that is what this is about (though I could be wrong). This is to with the version of the application, not the version of the dependencies. From what I read in that documentation, the `versioning-strategy` is the versioning strategy for the dependencies.

**Comment by jurre** [comment]
Ah yeah, I definitely misread this, apologies.

We don't have anything in the pipeline to support this in the near future, but you mentioned a callable script as an alternative, and I would suggest looking into setting up an [Action](https://docs.github.com/en/free-pro-team@latest/actions) to do this.

**Comment by dangoslen** [comment]
Thanks @jurre!

My team is looking at making an action just for that. If we are successful, we will consider making it an OSS action for others to use.

**Comment by jurre** [comment]
I'm going to close this out, we think using an Action to do this is the right way to go, and we don't have any plans to add this to Dependabot.

**Comment by alper** [comment]
This is not a great call for anybody using Dependabot seriously.

What does it mean if we have a library whose dependencies have been upgraded but whose own version stays the same? Does that make any kind of sense?

Pointing people to patch together more Github actions and create a swamp of yaml code that nobody can understand or debug when at some point it breaks, is really not a workaround.
