### ISSUE TITLE
dependabot does not pick up config for branches (Dockerfile)

### ISSUE THREAD

**Issue by davidkarlsen** [dependabot/dependabot-core#2049]
repo: https://github.com/evryfs/node-dev-docker
UI: https://app.dependabot.com/accounts/evryfs/repos/110023395

Even though there exists a DB-config per branch (see node10, node12, master) only one branch is shown in the UI, and there is no option to add more (since it is handled by file).

also - would it make sense to set target branch to the given branch, rather than always rely on default-branch?

**Comment by jurre** [comment]
It seems like you're using the GitHub native version of Dependabot, so it won't show up in the UI on dependabot.com (they are separate apps, the native version doesn't have a UI). It seems like everything is working and you're getting PRs to the right branches, so I'm going to close this out. Feel free to reach out if there's anything else.
