### ISSUE TITLE
Repo not getting scanned?

### ISSUE THREAD

**Issue by evenh** [dependabot/dependabot-core#205]
Hi!

I've tried setting up [evenh/coffeebot](https://github.com/evenh/coffeebot) for dependency bumping, but it seems like it is never getting scanned (just stuck in a queue)?

**Comment by greysteil** [comment]
Just saw an exception for it. I’m out but will get it fixed this afternoon

**Comment by evenh** [comment]
No hurry! Since the Java support is early alpha I suggest you enjoy your Saturday :-)

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/bb6fa7c4fa910a509436117b51b69816f54e29c4, which I'm pretty sure is right. I've also added a spec for it [here](https://github.com/dependabot/dependabot-core/commit/af2f537c77f304136c062aa2261c9cf12e428e70).
