### ISSUE TITLE
Prioritize by vendor?

### ISSUE THREAD

**Issue by marcaddeo** [dependabot/dependabot-core#2050]
Hi all,

It would be great to have the ability to prioritize dependency updates based upon the vendor prefix.

For example, we are primarily using Dependabot on our Drupal sites. All Drupal modules are prefixed with the `drupal/*` vendor. If we could prioritize our module updates, that would be ideal for our purposes.

**Comment by jonathanong-houzz** [comment]
i would like to prioritize first party modules that are published via GitHub Packages

**Comment by hmarr** [comment]
Can you expand on what you mean by "prioritize"? Are you running into the max number of open PRs, so want a specific subset of dependencies to be updated when you run into the limit? If so, can you configure Dependabot to ignore some of dependencies you're less interested in updating?

**Comment by sashuk** [comment]
@hmarr I think the idea is to make `dependabot` more predictable – first it checks dependencies that are marked as "prioritised", and if they are up-to-date **or** after creating pull requests for them the pull requests limit us not hit, the regular (not prioritised) dependencies are checked. This would be super-useful indeed!
