### ISSUE TITLE
shap 0.34.0 is not detected

### ISSUE THREAD

**Issue by marco-c** [dependabot/dependabot-core#2051]
I have "shap" as a dependency of my bugbug project: https://github.com/mozilla/bugbug/blob/54287adf0d313b35a314380ccfda4a96e24db356/requirements.txt#L18.

Dependabot used to open PRs to update the dependency: https://github.com/mozilla/bugbug/pulls?utf8=%E2%9C%93&q=shap+.

Since 0.33.0, Dependabot has not opened any new PR for updating shap, but a new version (0.34.0) has been released on December 27.

**Comment by hmarr** [comment]
Looks like this is working now as I can see some recent update PRs.
