### ISSUE TITLE
Doesn't detect dependency's latest version released to Maven central

### ISSUE THREAD

**Issue by dannil** [dependabot/dependabot-core#2052]
I have the dependency ```org.junit.platform:junit-platform-launcher``` in my project (relevant config file [here](https://github.com/dannil/scb-java-client/blob/dev/.dependabot/config.yml)), that 5 days ago were bumped from ```1.5.2``` to ```1.6.0-RC1```, which Dependabot doesn't recognize.

What's odd is that the run log says the latest version is ```1.5.2```even though ```1.6.0-RC1``` has been released for a while now, so maybe a caching issue somewhere? Manually browsing to the metadata XML gives the correct version ```1.6.0-RC1``` as the latest.

```
updater | INFO <job_20161195> Checking if org.junit.platform:junit-platform-launcher 1.5.2 needs updating
  proxy | 2020/01/11 20:34:39 GET https://repo.maven.apache.org:443/maven2/org/junit/platform/junit-platform-launcher/maven-metadata.xml
  proxy | 2020/01/11 20:34:39 200 https://repo.maven.apache.org:443/maven2/org/junit/platform/junit-platform-launcher/maven-metadata.xml
  proxy | 2020/01/11 20:34:39 HEAD https://repo.maven.apache.org:443/maven2/org/junit/platform/junit-platform-launcher/1.5.2/junit-platform-launcher-1.5.2.jar
  proxy | 2020/01/11 20:34:39 200 https://repo.maven.apache.org:443/maven2/org/junit/platform/junit-platform-launcher/1.5.2/junit-platform-launcher-1.5.2.jar
updater | INFO <job_20161195> Latest version is 1.5.2
updater | INFO <job_20161195> No update needed for org.junit.platform:junit-platform-launcher 1.5.2
```

**Comment by hmarr** [comment]
Dependabot doesn't update dependencies to prereleases unless you're already on a prerelease.
