### ISSUE TITLE
references to other requirements files are removed

### ISSUE THREAD

**Issue by bhearsum** [dependabot/dependabot-core#2053]
Some of my projects use `-r foo.txt` in requirements files to reference/inherit requirements from another. When dependabot bumps them, it removes that reference, which breaks them. Example: https://github.com/mozilla-releng/balrog/pull/1125

**Comment by hmarr** [comment]
We recently updated our pip-compile support so I'll (optimistically) close this out. If this is still a problem, feel free to reopen!
