### ISSUE TITLE
Support Terraform provider version bump

### ISSUE THREAD

**Issue by siddharthgoel88** [dependabot/dependabot-core#2054]
Dependabot still does not support version bump in the provider (specially `aws` provider). Issue is that `aws` release verify often and it is quite hard to keep up with its pace there. It would be amazing if provider version bump for Terraform module could be provided.

**Comment by iiro** [comment]
Looking forward to this as well... Same applies with Google provider (weekly releases).

**Comment by adzuci** [comment]
Hey friends, it looks like Renovate has a similar feature: https://docs.renovatebot.com/modules/datasource, could someone help me understand how much work it would be to implement something similar?

**Comment by jurre** [comment]
Heya, just wanted to let y'all know that I'm currently working on this. If any of you have a public repo they can share that I can verify my implementation against that'd be great, and I'll keep you posted here when it lands.
