### ISSUE TITLE
Possibility to add dependabot as an external collaborator

### ISSUE THREAD

**Issue by danielmarbach** [dependabot/dependabot-core#2055]
We are using TeamCity to build branches and PRs. TeamCity has a Pullrequest plugin that allows filtering PRs based on "members of the organization and external contributors". If a PR is sent to the repository not coming from external collaborators the PR is not build and has to be manually triggered on the build server. 

It is possible to add certain users to the outside collaborator roles in github, see https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization

Can you make it possible that the dependendabot user can be added there as well so that we can make sure the bot PRs are built?

**Comment by hmarr** [comment]
Closing this out as it sounds like the workaround suggested will do the job, and there's currently no way of adding apps as repo collaborators.
