### ISSUE TITLE
Dependabot repeatedly raises pull requests for the same dependency

### ISSUE THREAD

**Issue by matthewfranglen** [dependabot/dependabot-core#2061]
### Issue

Dependabot opens a PR to upgrade python Pillow to 6.2.0.
I take the time to perform that upgrade, with associated dependencies, and then test it. I merge the fix.
Dependabot _immediately_ opens another PR to upgrade python Pillow to 6.2.1.
I hate it.

### Expected Results

Upgrades should consider all problems not just the current problem. Dependabot should not perform upgrades to unsafe versions.

**Comment by infin8x** [comment]
We think this is now fixed - please reopen if you're still seeing the issue.
