### ISSUE TITLE
List all updated transient/sub-dependencies in PR

### ISSUE THREAD

**Issue by gingerlime** [dependabot/dependabot-core#2062]
Some sub-dependency updates cause unintended consequences and can happen "silently" and only visible if viewing the diff. For example when updating `rubocop-rails`, `rack` got bumped to a non-vulnerable version which has this issue: https://github.com/rack/rack/issues/1432

![Screenshot_2019-12-26_at_16_30_12](https://user-images.githubusercontent.com/524274/71469910-250c6580-27fd-11ea-9ca7-5a481025010e.png)

It would be helpful to list all updated dependencies in the PR body. This might have to be an option as npm/yarn often updates all sub-dependencies which would result in a huge list of dependencies being updated.

**Comment by infin8x** [comment]
Duplicate of #2090
