### ISSUE TITLE
Dependabot can't deal with PHP git updates (Requirements to unlock update_not_possible)

### ISSUE THREAD

**Issue by ElijahLynn** [dependabot/dependabot-core#2066]
Breaking out of https://github.com/dependabot/feedback/issues/799 with @feelepxyz. 

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/composer.json has a dependency on 
https://github.com/department-of-veterans-affairs/vets-website/blob/master/composer.json (https://packagist.org/packages/va-gov/web)

and we have a https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.dependabot/config.yml set to update the `va-gov/web` package _and_ automerge it, but we never get any PRs for it, and the logs say:

```
updater | INFO <job_18255722> Latest version is aac333ed6a49c91c66bef7cd4815437d4526c239
updater | INFO <job_18255722> Requirements to unlock update_not_possible
updater | INFO <job_18255722> Requirements update strategy bump_versions_if_necessary
updater | INFO <job_18255722> No update possible for va-gov/web e17a3cc82ac8a80b67704f205b44cfd1026e425f****
```

We discussed in https://github.com/dependabot/feedback/issues/799 already a fair bit. `composer update va-gov/web` locally works fine.

**Comment by damienwebdev** [comment]
I took a look at this -- https://github.com/dependabot/dependabot-core/commit/898c8d109506e9140c76fbe144087caaec4416ff is the offending commit with the offending line being https://github.com/dependabot/dependabot-core/blob/main/composer/lib/dependabot/composer/update_checker.rb#L51
