### ISSUE TITLE
Pip-compile: Libraries with requirements in devpi not found

### ISSUE THREAD

**Issue by alecbrick** [dependabot/dependabot-core#2067]
In our repository, our requirements.in file includes a library (call it A) which is in our company's Devpi server. Library A contains, as a requirement, another library (call it B) which is also in the Devpi server. When Dependabot runs pip-compile, it is unable to find library B.

Looking in the update logs, it doesn't look like Dependabot is looking in devpi for library B. It looks in pypi for the library, can't find it, and then throws an error.

It may be relevant that this occurs when Dependabot is attempting to update tensorflow from 1.14 to 2.0. Library A sets tensorflow to 1.14; however, our base repository (which requires library A) does not include tensorflow. It's possible that this is occurring as part of a security update, since our config allows indirect version updates for security updates.

My guess is that the issue is caused by the indirect update, which is incompatible with library A. However, a) this is not the error message that is given - rather, the error message says that library B has no compatible versions, and b) this shouldn't be an error, since library A has pinned tensorflow.

(yes I know we should update tensorflow but that's not under my control)

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

This is a really old issues... is it still happening or should we close this?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.
