### ISSUE TITLE
Allow to configure the creator for the pull requests

### ISSUE THREAD

**Issue by jraoult** [dependabot/dependabot-core#2072]
We would like to be able to define a registered (GitHub) user as the author of the dependabot PR.

We are using Heroku's review apps for your CI (cf. https://devcenter.heroku.com/articles/github-integration-review-apps). They recently changed the rules to only automatically create an environment if the author of the PR is part of the team owning the pipeline. For us, it means the version bump PR created by Dependabot are not automatically deployed anymore, and we tend to skip the manual check phase (because waiting for the review app to start is long, impatient developers 😬). If we were able to configure the author of the PR (and use a real Github user), it would solve our problem.

**Comment by infin8x** [comment]
Unfortunately we can't do this in GitHub's security model.
