### ISSUE TITLE
Libraries with Composer and type "path" + wildcard

### ISSUE THREAD

**Issue by DavG** [dependabot/dependabot-core#2074]
Hello,

We have a (private) MonoRepository with multiples services and some "components" (shared libraries).
We install these components with the following option in composer 

```
    "repositories": [
        {
            "type": "path",
            "url": "../../components/*/",
            "options": {
                "symlink": true
            }
        },
```

Apparently Dependabot cannot work because of this.

But the "path" option in Composer is the recommended way for doing this.

Is it a bug ?
Is there an alternative ?

Thanks ! 

Logs here: https://app.dependabot.com/accounts/Comiteo/update-logs/17088850

**Comment by infin8x** [comment]
Closing this as it's working now

**Comment by jenkoian** [comment]
I don't think this is working now (other than via the workaround mentioned)? I'm getting the following error when using a wildcard path: `The `url` supplied for the path (./patched-plugins/*) repository does not exist`

Relevant composer config is...

```
"repositories": [
    ...
    {
        "options": {
            "symlink": false
        },
        "type": "path",
        "url": "./patched-plugins/*"
    }
    ...
]
```

The workaround isn't really viable when you have more than a handful of libraries.

**Comment by jenkoian** [comment]
Sorry, just an update on the above. I've got it working now but via another workaround (I think it's a workaround anyway).

* `patched-plugins/*` was empty and thus you'd get the error
* If I put an example sub-folder with valid `composer.json` in then I don't get the error.

So the path wildcard stuff works fine as long as the path isn't empty, maybe that's expecting I'm not sure 🤷

**Comment by navarr** [comment]
@infin8x Requesting a re-open.  Currently experiencing this issue.

```
The `url` supplied for the path (modules/*/*) repository does not exist
```

I have composer packages in the format `modules/VENDOR/PACKAGE` and this path repository works fine for regular composer.

**Comment by TwanVermeulen** [comment]
I experienced the same error for a path containing a wildcard. In my case the path was having a backslash at the end, which wasn't necessary.

The example below resulted in a dependabot error, but worked for composer: 
```
    "repositories": [
        {
            "type": "path",
            "url": "../src/packages/*/"
        },
    ],
```

Without a ending backslash it works for both
```
    "repositories": [
        {
            "type": "path",
            "url": "../src/packages/*"
        },
    ],

```

**Comment by jeffwidman** [comment]
@TwanVermeulen do you want to file ☝️ as a new issue here? Comments on old issues don't get looked at/tracked...
