### ISSUE TITLE
Dependabot wrongly removes many dependencies from requirements.txt

### ISSUE THREAD

**Issue by epa095** [dependabot/dependabot-core#2075]
We are using a requirements.in to pip-compile a requirements.txt file. Dependabot used to handle this ok. But lately we have had many PRs where dependabot generates requirements.txt-files with a lot of the requirements missing. 

One example is [this](https://github.com/equinor/gordo-components/pull/761/files), where a simple bump of pyyaml removes a lot of completely unrelated things, like tensorflow.

Labels: 
python:pip

**Comment by deivid-rodriguez** [comment]
Hi!

We haven't got any similar reports recently. Is this still reproducible?

**Comment by epa095** [comment]
2 years since I worked on that project, so IDK:-p But I think the only reasonable thing is to close this and assume its fixed.
