### ISSUE TITLE
Dependabot can't find non-default base branch

### ISSUE THREAD

**Issue by rmainseas** [dependabot/dependabot-core#2077]
Currently trying to add dependabot to github.com/seas-computing/course-planner, however I'm setting `develop` as the base branch like so:

![image](https://user-images.githubusercontent.com/50675045/69983570-0a4c1700-1505-11ea-92dc-0c5da58fe133.png)

The default branch in that repo is actually `master`, but I don't want dependabot interacting with `master`. However it seems not to be able to find the `develop` branch...and I notice an API client warning in that debug output. Perhaps the two are related?

Debug output from dependabot:

      proxy | time="2019-12-02T18:05:35Z" level=info msg="proxy starting" commit=3308419dc43ac70fd31b522ee66e52c793464d5d
      proxy | 2019/12/02 18:05:35 Listening (:1080)
    fetcher | yarn config v1.19.2
    fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
    fetcher | Done in 0.02s.
    fetcher | NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
    fetcher | Faraday::Error::ClientError.inherited called from /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
    fetcher | INFO <job_16640942> Starting job processing
      proxy | 2019/12/02 18:05:39 GET https://api.github.com:443/repos/seas-computing/course-planner/git/refs/heads/develop
      proxy | 2019/12/02 18:05:39 * authenticating github api request
      proxy | 2019/12/02 18:05:39 404 https://api.github.com:443/repos/seas-computing/course-planner/git/refs/heads/develop
    fetcher | ERROR <job_16640942> Error during file fetching; aborting
    fetcher | INFO <job_16640942> Finished job processing

**Comment by infin8x** [comment]
Not 100% sure I understand the issue - in GitHub-native Dependabot you can set the target branch for PRs: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#target-branch. Are you already using that setting and still having this issue?

**Comment by hmarr** [comment]
Closing as you can set the `target_branch` in the config file (as described above). Feel free to reopen if it's not working as expected.

**Comment by sokun-chorn-webjet** [comment]
I'm testing dependabot target-branch config but when I switch branch to develop I've got warn "**Cannot configure Dependabot. To configure Dependabot, you must use this repository’s default branch.**"

![image](https://user-images.githubusercontent.com/32442785/122843185-34ad3180-d342-11eb-97be-59c2dbfab390.png)

**Comment by jurre** [comment]
> I'm testing dependabot target-branch config but when I switch branch to develop I've got warn "**Cannot configure Dependabot. To configure Dependabot, you must use this repository’s default branch.**"

The config file needs to be in the base branch, the `target-branch` can be configured to point to whatever you like, it's just not pulled _from_ there
