### ISSUE TITLE
Run validator against PR's with config changes

### ISSUE THREAD

**Issue by WyriHaximus** [dependabot/dependabot-core#2078]
We recently ran into an issue where we PRed an invalid changed in the `.dependabot/config.yml` file. It would be really handy to have Dependabot watch for PR's that make changes to that file and run it through https://dependabot.com/docs/config-file/validator/ so it can report back any issues that might be in there.

**Comment by jeffwidman** [comment]
This is from the old dependabot-preview code, before it was moved to GitHub.

We now automatically run checks on the config file, although it has some issues: https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting

So closing this in favor of https://github.com/dependabot/dependabot-core/issues/4605
