### ISSUE TITLE
Support overriding version requirement updates strategy for a given dependency

### ISSUE THREAD

**Issue by Lctrs** [dependabot/dependabot-core#2081]
Sometimes, you may want to use another version requirement updates strategy for one or more dependencies of your project. Could be cool if dependabot add support for this, similar to what has been done for `allowed_updates`, `ignored_updates`, and `automerged_updates`.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
