### ISSUE TITLE
CLI to bump all versions at once

### ISSUE THREAD

**Issue by rafaelrocha-hotmart** [dependabot/dependabot-core#2083]
Context:
As project's dependencies grow, handle all opened PR by each dependency gets difficult and boring. So a way to handle it at once would make our daily job easier. 

Solution A:
* Have a configuration option to make Dependabot open only one PR with all the versions bumped instead of one by each dependency.

Solution B:
* Provide a CLI tool to run it locally for a specific project. So we can bump the versions locally, test, fix, test and then push the new versions.

**Comment by infin8x** [comment]
Duplicate of #1190 

Solution A would be satisfied by #1190. It's unlikely we'd take solution B.
