### ISSUE TITLE
Docker release notes

### ISSUE THREAD

**Issue by g-k** [dependabot/dependabot-core#2085]
Currently, PRs that update an official golang image e.g. https://github.com/mozilla-services/autograph-edge/pull/39 just show:

> Bumps golang from 1.13.1-buster to 1.13.4-buster.

but ideally it'd surface:

* notes from the official changelog e.g. https://golang.org/doc/devel/release.html#go1.13.minor with relevant issues and a diff of the code in the release
* a link to the image tag layers e.g. https://hub.docker.com/layers/circleci/golang/1.13.4-buster/images/sha256-9c9b931b360a469dde4344c660b1e7a0b4cb6a8231c8aa8de61014d19978ac21
* a diff of the dockerfile used to build it https://github.com/CircleCI-Public/example-images/commits/master/golang/Dockerfile (though this doesn't look like it has tags)

**Comment by mctofu** [comment]
I took a quick look at this and one of the missing pieces is a way to resolve the source repo for the docker image in https://github.com/dependabot/dependabot-core/blob/main/docker/lib/dependabot/docker/metadata_finder.rb

One way to get that could be to look for the `org.opencontainers.image.source` label on the image (https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys)

**Comment by mctofu** [comment]
I added support for linking a docker image to a source repo in https://github.com/dependabot/dependabot-core/pull/6864. Once a source repo is linked Dependabot will use it's standard methods to detect relevant releases/changelogs/commits for PRs. This generally requires there be matching tags on the docker image and repo to assist in detecting relevancy.
