### ISSUE TITLE
Ignore updates when there is no modification

### ISSUE THREAD

**Issue by Spomky** [dependabot/dependabot-core#2086]
Hi,

I manage several projects using a very nice tool that splits the main repository to sub repositories [as explained in this talk](https://www.dotconferences.com/2016/05/fabien-potencier-monolithic-repositories-vs-many-repositories).

When a commit is pushed or a tag is set on a branch, the sub repositories are updated.
Tags are always set even if there is no modification on the sub-repository. This way the sub-package versions are identical to the main package one.

The problem is that dependabot will do its job and create a PR even if there is no commit 1etween the versions.

The question is: **How could we ignore version updates when there is no commit?**

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by Spomky** [comment]
Hi @infin8x,

Not critical, but annoying.
