### ISSUE TITLE
Add support for private repositories in Gradle

### ISSUE THREAD

**Issue by rebelagentm** [dependabot/dependabot-core#2087]
We currently don't support private repositories as a dependency source in Gradle.  This will serve as the main tracking issue.

If you would like to see support for this in Dependabot Core, please add your comments here.

Thank you!

**Comment by infin8x** [comment]
This seems to be done

**Comment by parisapo** [comment]
Is there an example how this works? Thanks

**Comment by mitchjust-finocomp** [comment]
@feelepxyz @infin8x is this definitely done?

Trying to generate a yml config file from app.dependabot.com still shows

![Screenshot from 2021-03-03 10-31-22](https://user-images.githubusercontent.com/64878492/109729414-f1507b00-7c0b-11eb-9e88-24435648499c.png)
