### ISSUE TITLE
Incorrect release notes for typescript

### ISSUE THREAD

**Issue by michaelmior** [dependabot/dependabot-core#2088]
In [this PR](https://github.com/michaelmior/relational-playground/pull/245) dependabot included release notes for a beta release while checking typescripts' [releases page](https://github.com/microsoft/TypeScript/releases), I can see the correct notes.

**Comment by jeffwidman** [comment]
Sorry for the glacially slow reply... This issue is nearly 3 years old and the metadata fetching code has changed a lot since then. So I'm going to close, but if you still see issues with fetching release notes, please file a ticket and we'll try to be a lot quicker to dig into it.

**Comment by michaelmior** [comment]
Recent PRs seem fine. Thanks!
