### ISSUE TITLE
Support for .net core local tools

### ISSUE THREAD

**Issue by xt0rted** [dependabot/dependabot-core#2089]
.net core now supports a `dotnet-tools.json` file where cli tools from nuget.org can be installed. Since these are pulled from NuGet they're versioned just like any other NuGet dependency. I'm not seeing documentation for this at https://docs.microsoft.com but the file format can be seen near the end of the issue at https://github.com/dotnet/cli/issues/10288 and the file can exists under a `.config` folder or any sub folder in your repo.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
