### ISSUE TITLE
[Idea] Open an issue when a dependency has a conflict to be updated

### ISSUE THREAD

**Issue by carusogabriel** [dependabot/dependabot-core#2092]
Hello team 👋 

First of all: thanks for this amazing project. Since we've merged dependabot/dependabot-core#1230, @usabilla have been using `Dependabot` form both frontend and backend teams, and it has saved us a lot of time 🎉❤️ 

Last week, we were expecting some PRs from `Dependabot` that didn't arrive and we've figured that the problem was dependency conflicts.

I remember once that we had a misconfigured `config.yml` and Dependabot opened an issue reporting that.

So, my idea: Dependabot could open an issue saying: `Hey, I'm trying to update dependency foo/bar but it has conflicts with foo/quox. Can you fix it so I can continue my work`? 😄

If you think this is a nice idea and shouldn't be that difficult to implement, please let us know. We'd love to contribute back to you 😉

Keep up the good work 🤖

**Comment by infin8x** [comment]
Similar to #2242
