### ISSUE TITLE
add update_schedule "manual"

### ISSUE THREAD

**Issue by lucienbertin** [dependabot/dependabot-core#2093]
I'd like to have the possibility to set the update schedule to `manual` so dependabot only creates PR when i click the `bump now` button on the app dashboard

my reason is that dependencies update should be something planned with the different steakholders of the product (prioduct owner, devs, ...) and be integrated in the release process. having dependabot create PRs in background just made the team ignore them, and thats not what we want

where i work we have a semi regular release process with sprint dedicated to debt reduction and dependencies management, i'd like to be able to integrate dependabot in this workflow

security updates should still be created as asap as possible

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
