### ISSUE TITLE
Allow specifying commit footers

### ISSUE THREAD

**Issue by CameronDiver** [dependabot/dependabot-core#2094]
I took a look at https://github.com/dependabot/feedback/issues/443 and it appears it's not possible to add a footer to the commit message. Our CI requires a `signed-off-by` and `change-type` footer, when change type can be `patch|minor|major`.

Currently it looks like I'll have to add these manually, but will there be support for something like this?

Footers in this case are defined:
```
commit title

commit body
which can have

multiple newlines

# footers here:
signed-off-by: ...
change-type: patch
```

**Comment by jeffwidman** [comment]
Let's track this in the more generalized ticket that tracks templates for commit messages:
* https://github.com/dependabot/dependabot-core/issues/1460

Closing as a duplicate.
