### ISSUE TITLE
Support accounts with lots of repositories and configured projects

### ISSUE THREAD

**Issue by wtanaka** [dependabot/dependabot-core#2095]
Currently the dashboard times out if you have a lots of repositories and configured projects because there is no pagination on the API requests.

<img width="433" alt="Screen Shot 2019-10-28 at 5 36 26 PM" src="https://user-images.githubusercontent.com/35872/67720090-805eda80-f9a9-11e9-8263-cef39b7266c8.png">

*Edited by @feelepxyz*

**Comment by feelepxyz** [comment]
@wtanaka there's a workaround for this, you can migrate to the GitHub-native version of Dependabot. It doesn't yet support private git dependencies or private registries (we've also deprecated automerging). 

https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates
