### ISSUE TITLE
Two co-dependendent updates not being reported (deadlock)

### ISSUE THREAD

**Issue by marekdedic** [dependabot/dependabot-core#2099]
Hi, I have the repo [skaut/wordpress-verison-checker](https://github.com/skaut/wordpress-version-checker) and I noticed some updates not being reported by dependabot on d94ee5f. I have an idea about why this might happen:

I have both `@typescript-eslint/parser` on version 1.13 and `eslint` on version `5.16.0` - both lagging behind by a major version (to `2.4.0` and `6.5.1` respectively at the moment). However, `@typescript-eslint/parser` 1.X depends on `eslint` 5.X and `@typescript-eslint/parser` 2.X depends on `eslint` 6.X.

So, effectively, updating only `@typescript-eslint/parser` to version 2 is broken because the requirement on `eslint` would no longer be satisfied. But updating `eslint` to version 6 is also broken because the requirement on `eslint` by `@typescript-eslint/parser` would also not be satisfied. The only valid path is to update both at the same time.

AFAIK, Dependabot doesn't support this at the moment and I think detecting all the ways to update multiple dependencies at once would be rather hard. So I'm not asking for that. What I would like to see is for Dependabot to let me know in some way that the updates couldn't be done - open an issue or whatever. Because now I'm in a situation where I just noticed several packages are outdated while depending on dependabot (no pun intended) to sort this kind of thing automagically...

Disclaimer: The reason why the packages aren't being updated is just a hypothesis, I haven't tested it out...

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by marekdedic** [comment]
I wouldn't think of the issue as being critical to any particular workflow, but it diminishes the trust in dependabot a lot - you can no longer think of it as giving you the peace of mind of having all dependencies up-to-date. For smaller and hobby projects, that's the big value proposition of dependabot - a lot of the projects I use dependabot for are largely done and dependabot gives me the ability not to have to check up on them periodically to check what's stale or broken. This issue breaks that assurance...

**Comment by marekdedic** [comment]
Oh and as for demand, this issue manifested for me in the twin packages `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` They seem to always bump major versions together and thus dependabot can't upgrade them. That's pretty sure to be a lot of users, but probably they just haven't noticed...
