### ISSUE TITLE
A way to bump a group of repositories with a webhook

### ISSUE THREAD

**Issue by skalero01** [dependabot/dependabot-core#2100]
Hi, right now my packages are not being updated via the live updates, not sure if there is a normal delay. I'd like to know if there is any way to bump automatically a group of repositories.

I have a package on packagist and have a bunches of repositories that use this package. Can i set a webhook on github for the package repository so this webhook could make dependabot to bump some repositories?

I think that could be a good idea :)

**Comment by infin8x** [comment]
Closing this as the API `@feelepxyz` mentioned is the best way to achieve scenarios like these today.
