### ISSUE TITLE
Automatically open a PR that modifies the `ignore` section of the configuration file for `@dependabot ignore this dependency` comments

### ISSUE THREAD

**Issue by thomaseizinger** [dependabot/dependabot-core#2103]
Today, I wanted to use the `@dependabot ignore this dependency` comment [here](https://github.com/comit-network/comit-rs/pull/1492) and was told by dependabot that this doesn't work because I am using a config file in this repository.

It would be great if dependabot, instead of commenting, would just open a pull request that modifies the `ignore` section accordingly :)

**Comment by infin8x** [comment]
Closing this as it's unlikely we'll get to it in the foreseeable future. Please feel free to reopen if this work is critical to your scenario.
