### ISSUE TITLE
Support multiple lock files for Bundler

### ISSUE THREAD

**Issue by paulsturgess** [dependabot/dependabot-core#2106]
The [BootBoot](https://github.com/Shopify/bootboot) gem makes it very easy to run tests against against future versions of Rails. 

When running `bundle install` it produces a `Gemfile_next.lock` alongside the usual `Gemfile.lock`. At the moment Dependabot only checks in the `Gemfile.lock` and I guess it ignores the `Gemfile_next.lock` as this is a non-standard file. The result is an error is raised when the CI attempts run bundler before running the tests.

Here's an example of the error output:

```
Using bundler 2.0.2
Installed plugin bootboot

You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile_next.lock to version control.

The dependencies in your gemfile changed
You have added to the Gemfile:
* activeadmin (~> 2.3.1)
You have deleted from the Gemfile:
* activeadmin (~> 2.2.0)

The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed.
```

It would be great if there was some way to specify any custom lock files (or maybe just any non-standard output) that should be committed by Dependabot. Does this sound like a sane idea?

**Comment by infin8x** [comment]
Looks like you've got this working via multiple `update_configs`, so closing for now.

**Comment by ashkulz** [comment]
@infin8x it doesn't work for us, see my latest comment in #2231

**Comment by davidwessman** [comment]
I solved this problem by adding a Github Action workflow which updates `Gemfile.next.lock` everytime Dependabot updates `Gemfile.lock`. It does not have as nice update logic as Dependabot but help keeping the `Gemfile.next` deployable!

I wrote it up in a blog post:
https://wessman.co/rails-dual-boot-with-dependabot

**Comment by davidwessman** [comment]
@infin8x Can we open up this issue again?
Now my solution and my tests fail since the change to only read-permissions from the 1st of March.
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

Or should I create a new PR?

**Comment by infin8x** [comment]
Unfortunately I'm not on the Dependabot team anymore. @hmarr or @feelepxyz may be able to get you in the right direction.
