### ISSUE TITLE
"Bump all" button

### ISSUE THREAD

**Issue by Konard** [dependabot/dependabot-core#2109]
I have a lot of packages that are interconnected with each other. And I don`t remember which packages depend on which packages. And after updating every single package I find my self manually clicking all packages in the organization with "bump now" button.

So maybe there is a way to add "Bump all" button for organizations and user profiles?

Or maybe there is a way to "Bump" as soon as each NuGet package was pushed? This way I will never have to touch any buttons at all.

**Comment by infin8x** [comment]
There's an API that can provide similar functionality: https://github.com/dependabot/api-docs#notify-dependabot-of-a-private-dependency-release, so I'm going to close this for now.
