### ISSUE TITLE
Support Private Terraform Registries

### ISSUE THREAD

**Issue by johncblandii** [dependabot/dependabot-core#2112]
Private Terraform registries allow for internal modules: https://www.terraform.io/docs/registry/private.html.

Our Terraform projects on Dependabot do not work properly when there is a private registry in use.

In our specific case, we're using the Terraform Cloud private registry: https://www.terraform.io/docs/cloud/registry/index.html. More about the configuration can be seen here: https://www.terraform.io/docs/cloud/registry/using.html.

**Comment by iiro** [comment]
Maybr Hashicorp could also participate on this one... Would support their customers very nicely...

**Comment by asciimike** [comment]
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta, but I don't believe we have a terraform specific provider (just private Git based registries).

Let me know if the `git` based flows work, and if they don't (or there are other features that are needed), please re-open this and I'll get it prioritized.

**Comment by philipbankier** [comment]
We are trying to use Dependabot with Terraform stored in a private repo that used private modules from Terraform cloud so support for private Terraform cloud modules would be extremely helpful. Does anyone have a workaround in the meantime? Currently we are receiving the following error from Dependabot:
```
Error: Error accessing remote module registry

Failed to retrieve available versions for module "reporting"
(infrastructure/reporting/main.tf:46) from app.terraform.io: error looking up
module versions: 401 Unauthorized.

```
