### ISSUE TITLE
Allow to specify time windows for when dependabot is allowed to operate

### ISSUE THREAD

**Issue by thomaseizinger** [dependabot/dependabot-core#2115]
I've been a big fan of dependabot for a while and we are also fairly happy users of it at work :)
As with several other people on here, we have had our issues with the amount of work that comes with handling dependabot PRs. Recently, we tried to allow automerging but sadly, without much benefit.
Concretely, we observed that even with automerging, dependabot doesn't update PRs if they are outdated. We have autorebase turned off because it would cause too much load on CI while we are working.

In the end we want two things from dependabot:
1. Not be in the way while we are working (i.e. not keep the CI busy when we need it)
2. Not requiring too much manual interaction

Ideally, we would like to specify time windows when dependabot can operate. For example:
Friday 6pm till Monday 6am. Within that time, dependabot can go wild and rebase as often as it wants to, open PRs etc (unless the max number is reached of course) and merge them if the build passes.

This feature while certainly not ideal would definitely solve all problems that we currently have with dependabot. Also, from reading the other issues around rebasing and automerging, it looks like it would help other people as well!

**Comment by infin8x** [comment]
This is fixed in GitHub-native Dependabot: use the new `schedule` values to set when Dependabot runs https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleday
