### ISSUE TITLE
Display number of outdated dependencies

### ISSUE THREAD

**Issue by bauerd** [dependabot/dependabot-core#2117]
Hi,
there currently seems to be no way to tell how many PRs @dependabot has in stock for a repository. The only option to learn about this number seems to be bumping the value of the "Limit of open pull requests per repo" setting to a large number, however that will also open all those PRs, rendering our CI useless for the day.

Is it possible to learn about the number of updates per repository?

Thanks

**Comment by infin8x** [comment]
Closing this as it's unlikely Dependabot will take this directly - knowledge like this is the domain of the GitHub dependency graph.
