### ISSUE TITLE
K8s, Helm, Repos as Code recommendations

### ISSUE THREAD

**Issue by dominikmeyersap** [dependabot/dependabot-core#2118]
Dear Dependabot Team
We are starting to use dependabot and are super happy! Thanks for creating this awesome tool!

That said, our Repo will soon be migrated into a GitHub enterprise account.

We can no longer use the hosted application and need to host a dependabot ourselves.

Given:

- Kubernetes landscape
- Helm charts
- Mostly node/java developers

Wanted:

- Helm deployed dependabot using your `.Dockerfile`
- Reading GH token from side car mounted Vault container
- Checking repos which are defined "as code", like a config file that lists all repos to check

Seen:

I've checked your code `.Dockerfile` and your `dependabot-script` repo. I think what we want is somewhere between but we have like not too much clue how to start but should have it if possible on Aug 26th.
Can you point us in the right direction for the wanted-bullets? Happy to provide more information if needed!

Thanks and best regards

**Comment by infin8x** [comment]
Closing due to age
