### ISSUE TITLE
Missed updates for a large Lerna repo

### ISSUE THREAD

**Issue by RomainMuller** [dependabot/dependabot-core#2120]
Hello,

I am surprised @dependabot did not submit PR's for a number of `package.json` files at are monitored in our repository, while there are newer versions available for certain of our direct dependencies, as can be seen in aws/aws-cdk#3545.

I want to count on @dependabot for not having to manually cater for dependency upgrades, so I'd like to get an understanding of why I didn't get automated PRs for those dependencies (even after manually clicking "bump now").

Thank,
Romain.

**Comment by jeffwidman** [comment]
👋 This is a pretty old ticket and we've shipped a lot of changes / improvements since then.

Is this still happening or should this issue be closed?
