### ISSUE TITLE
Automatic Merging on a Schedule

### ISSUE THREAD

**Issue by jondavidjohn** [dependabot/dependabot-core#2122]
I love the idea of the automatic merging, but this conflicts with my CD processes, as they are asynchronous, if I have 5 version updates that all pass around the same time, my CI tool tries to deploy 5 times in a short span of time and gets all confused.

I'd love to be able to do something like

> Automatically merge all passing update PRs at 12:00am every day as one merge

This would help with the above issue, but would also help alleviate the CI load as mentioned in quite a few other feedback issues

- https://github.com/dependabot/feedback/issues/427
- https://github.com/dependabot/feedback/issues/455

And also, slightly related to the idea of grouping as requested here

- https://github.com/dependabot/feedback/issues/318

**Comment by infin8x** [comment]
We've removed automerging from GitHub-native Dependabot, so closing this issue.
