### ISSUE TITLE
Split pull requests for different base versions

### ISSUE THREAD

**Issue by LankyLou** [dependabot/dependabot-core#2123]
I am working within a Lerna monorepo using a yarn workspace and dependabot is great for keeping our dependencies up to date. There are some situations where I have to manually change a PR and it would be great if dependabot handled these differently.

We have 3 packages that all use the same dependency (let's use webpack as an example), but for some reason we cannot upgrade through a breaking change on package A. So the current state of our dependencies is
- A uses webpack 3.12.0
- B uses webpack 4.37.0
- C uses webpack 4.37.0

When a new version is released dependabot creates a commit and a PR for `build(deps-dev): bump webpack from 3.12.0 to 4.38.0` that updates all 3 packages to use the latest version. Due to the known issue in package A, this breaks and our CI fails as expected. I then manually alter this commit to only perform the update in package B and C, leaving A on the older version.

It would be nice if dependabot could in some way split these updates up to make it more obvious what's breaking. Ideally they could be two separate PRs, one for `3.12.0 to 4.38.0` and one for `4.37.0 to 4.38.0`. If that isn't possible then perhaps there would still be some value to having them as 2 separate commits within the PR.

**Comment by jeffwidman** [comment]
This is a pretty old ticket, and we've pushed a lot of changes / improvements / bugfixes since then.

Is this still a problem, or can this be closed?

**Comment by t3-aoki** [comment]
I'm using npm workspace and have the same problem.
I also think there should be a way to set `ignore` config per workspace.

**Comment by jeffwidman** [comment]
Let's keep the scope of this ticket about `lerna`, not `npm`. Please file a new issue for that (unless there's already one in the backlog).

**Comment by LankyLou** [comment]
@jeffwidman I'm not longer working on the project that was having this issue, so I don't know if it's still a problem or not.

**Comment by jeffwidman** [comment]
I'm going to close for now but if someone encounters this in the future please file a new ticket with details on what specifically you're seeing... ideally include an example repo so that we can test/reproduce and feel free to cross link with this issue.
