### ISSUE TITLE
Assign specific dependencies to specific assignees

### ISSUE THREAD

**Issue by liorheber** [dependabot/dependabot-core#2124]
Hi,

It would be really useful to have the ability to assign specific dependencies to specific people.
For example, assign all PRs to the default assignees but have the ability to assign someone else if a specific dependency has a new version.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by Undin** [comment]
Actually, it would be nice to have this feature. In large projects, different libraries may be related to different subsystems that have different owners. So it's quite convenient to assign the particular PR to the corresponding owner

**Comment by jurre** [comment]
> Actually, it would be nice to have this feature. In large projects, different libraries may be related to different subsystems that have different owners. So it's quite convenient to assign the particular PR to the corresponding owner

You should be able to do this using [code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

**Comment by Undin** [comment]
@jurre How will it help if all dependencies are declared in a single file, for example, `build.gradle`?

**Comment by jurre** [comment]
> @jurre How will it help if all dependencies are declared in a single file, for example, `build.gradle`?

Ah yeah you're right, it wouldn't work with a single file. We currently don't have a good answer for assigning different reviewers, as mentioned demand for this feature has been really low so unlikely to be able to prioritize it anytime soon.
