### ISSUE TITLE
Need to be able to specify checks required for merge.

### ISSUE THREAD

**Issue by chriseyre2000** [dependabot/dependabot-core#2132]
It would be useful if we could specify the minimum required checks before a merge happens.

We use Jenkins for unit test and our platform team have been experimenting with snyk.
The problem is if snyk responds first then a build can be merged that has failing tests.

We either need to be able to do this in the UI or in the config file.
All I really need to to be able to see that the unit tests have passed.
Snyk should also be able to fail the build.

**Comment by infin8x** [comment]
Closing this as we don't expect to implement anything in Dependabot outside the GitHub notion of required checks.

**Comment by eps1lon** [comment]
> Closing this as we don't expect to implement anything in Dependabot outside the GitHub notion of required checks.

@infin8x Was there an existing issue that tracked this? I can only see https://github.com/dependabot/dependabot-core/issues/2661 which was opened after you closed this issue here.
