### ISSUE TITLE
Create backlinks from upstream PRs to dependency bump PRs

### ISSUE THREAD

**Issue by jglick** [dependabot/dependabot-core#2134]
Consider https://github.com/jenkinsci/jenkins-test-harness/pull/144 which was integrated in https://github.com/jenkinsci/plugin-pom/pull/214. The POM PR links to the library PR in its **Release notes** section. However, there is no backlink from the library PR to the POM PR. This means that someone who stumbled across the library PR (say, while debugging the issue it purported to fix) would not have an easy way to see which POM version bundled the fix; you would need to `git blame` the `pom.xml` to see when the fixed version was integrated, then `git describe --contains` to see which POM version contained that fix.

Normally this kind of thing is handled quite nicely on GitHub via backlinks. If one PR mentions another, then the mentionee gets a backlink, so you can easily navigate a complex web of changes. Unfortunately this does not currently work in Dependabot-generated PRs, I think because of the way it renders the upstream changelog in Markdown. For example, it uses

```markdown
> * Fix concurrent access to LoggerRule#getMessages ([#144](https://github-redirect.dependabot.com/jenkinsci/jenkins-test-harness/issues/144)) [@&#8203;Vlatombe](https://github.com/Vlatombe)
```

which renders as

> * Fix concurrent access to LoggerRule#getMessages ([#144](https://github-redirect.dependabot.com/jenkinsci/jenkins-test-harness/issues/144)) [@&#8203;Vlatombe](https://github.com/Vlatombe)

whereas if it simply used

```markdown
> * Fix concurrent access to LoggerRule#getMessages (https://github.com/jenkinsci/jenkins-test-harness/issues/144) @Vlatombe
```

which renders as

> * Fix concurrent access to LoggerRule#getMessages (https://github.com/jenkinsci/jenkins-test-harness/issues/144) @Vlatombe

you would not only get the backlink automatically, something like

> **dependabot-preview** referenced this pull request 1 hour ago
> Bump jenkins-test-harness from 2.51 to 2.52 – # 214 – Merged

but the _forward_ hyperlink looks nicer since it will have a hover preview.

**Comment by infin8x** [comment]
Closing this as we don't expect to get to it in the foreseeable future.

**Comment by jglick** [comment]
> I'd like to implement a better solution for [backlinks] from within GitHub. References could be bundled up and displayed clearly in the PR timeline, for example.

Do you happen to know if this is on the radar for the core GitHub team?
