### ISSUE TITLE
Allow teams to be set as default reviewers

### ISSUE THREAD

**Issue by idm-ryou** [dependabot/dependabot-core#2135]
It seems like it is not possible for now.
(Sorry if I am wrong!)

It is necessary for Pull Panda [Pull Assigner](https://pullpanda.com/assigner) to automate review assignment.

**Comment by infin8x** [comment]
This is fixed in GitHub-native Dependabot - see https://github.com/dependabot/dependabot-core/issues/1198#issuecomment-638172068 for more info
