### ISSUE TITLE
PR should close when manifest file is deleted

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#2139]
I deleted a subdirectory `Gemfile` in a project, and Dependabot [appears to be stuck trying to rebase its PR for that `Gemfile`](https://github.com/panorama-ed/henchman/pull/96).

**Comment by jeffwidman** [comment]
I just checked this, and deleting a `Gemfile` causes Dependabot to close any PR's created against that Gemfile. So sometime in the last few years this has been fixed.
