### ISSUE TITLE
Support for Google Cloud Build's `cloudbuild.yaml`

### ISSUE THREAD

**Issue by hazcod** [dependabot/dependabot-core#2140]
Google Cloud Build is a widely used CI/CD pipeline that integrates with Github, is automatically picks up a `cloudbuild.yaml` file.
One can define build steps:
```
- steps:

- name: '<IMAGE>'
....
```

where name will be a docker image, residing on a public and/or private registry.

**Comment by steebchen** [comment]
not stale!
