### ISSUE TITLE
Changelog support for private packages on Gemfury

### ISSUE THREAD

**Issue by bobvanderlinden** [dependabot/dependabot-core#2141]
We're currently using Dependabot for private Ruby gems that are hosted on Gemfury. This works great, however we were not able to get a changelog to show up in the Dependabot PRs.

We have set the `changelog_uri` in the gemspec file. It indeed shows up when I have the gem installed and query its specification:

```
$ gem specification xxx
...
metadata:
  changelog_uri: https://github.com/xxx/xxx/blob/master/CHANGELOG.md
...
```

I also made sure Dependabot has rights to the private repository so it should be able to fetch `https://github.com/xxx/xxx/blob/master/CHANGELOG.md`.

Are private gems on Gemfury just not supported? Or are we missing something in our private gems?

**Comment by infin8x** [comment]
Closing this due to age and inactivity.
