### ISSUE TITLE
Could yarn.lock update PRs include the dependency they come from?

### ISSUE THREAD

**Issue by johnnyreilly** [dependabot/dependabot-core#2142]
Heya,

Dependabot is awesome! 

I wonder if when a PR is raised relating to a `yarn.lock` file, the message could also indicate which `dependencies` / `devDependencies` in the `package.json` this relates to? 

This PR tells me just about the `yarn.lock` file. If I knew which package this came from up front that would be helpful / interesting. Also, I'm likely to attach greater urgency to shipping a new release if this is a  `dependency` rather than a  `devDependency` 

https://github.com/TypeStrong/ts-loader/pull/947

**Comment by mwaddell** [comment]
I created a reusable workflow that does this:

https://github.com/pangaeatech/.github/blob/main/.github/workflows/annotate-npm-dependencies.yml

See also #2702

**Comment by jeffwidman** [comment]
Closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2125
