### ISSUE TITLE
Feature Request: merge into other branch from PR

### ISSUE THREAD

**Issue by danielpowell4** [dependabot/dependabot-core#2147]
Hello! First off, congrats on joining GitHub. 🎊 

It seems like this (Issues) is where you want feedback and feature requests. If this is not the case, I apologize.

My team likes to test out all upgrades in our nearly-production, staging environment before they go out. As such I find myself often checking out the dependabot branches to merge then into staging

```
# me locally most mornings
git fetch
git checkout dependabot/npm_and_yarn/dependency-4.6.1
git checkout staging
git merge dependabot/npm_and_yarn/dependency-4.6.1
```

I was wondering if adding a PR comment command to automate this process is/could be on the feature list

```
@dependabot merge target_branch # general
@dependabot merge staging # us specific

# OR

@dependabot merge_into target_branch
```

Thanks for all you do

**Comment by infin8x** [comment]
Closing this as we don't expect to build the functionality into Dependabot. We recommend considering GitHub Actions or other merge-specific bots.

**Comment by tommed** [comment]
But when you close the PR after merging, dependabot sends you an email saying "ok I won't tell you about this release again" suggesting closing the PR has somehow been interpreted as a mute request, despite merging the changes into the other brach (in our case 'dev'). Makes the workflow feel less than idea - would it be so hard just to have a project-wide setting allowing you to choose what the default merge branch is for the PR?

**Comment by chrift** [comment]
> would it be so hard just to have a project-wide setting allowing you to choose what the default merge branch is for the PR?

This is what I would prefer. I have a pipeline which triggers when I merge to master, and about 20 dependabot prs all against master. If I was to merge all of them one by one, it would trigger a load of pipelines which I am keen to avoid.
