### ISSUE TITLE
Timeline for availability on Github Enterprise?

### ISSUE THREAD

**Issue by montrealist** [dependabot/dependabot-core#2149]
Hi - will Dependabot be available on Github Enterprise and if yes what is the timeline?

**Comment by wangyun1517** [comment]
It's the end of July, any update on this?

**Comment by greysteil** [comment]
The team got pulled onto some other things, but this is now on the [GitHub public roadmap](https://github.com/github/roadmap/projects/1), targeting January to March.

**Comment by KaiSforza** [comment]
Github actions are now in beta on GHES. Is there any update on how to run this in enterprise yet?

**Comment by greysteil** [comment]
Not beyond it still being on the [public roadmap](https://github.com/github/roadmap/projects/1#card-42486655) for Jan-March next year :-)

**Comment by KaiSforza** [comment]
Just putting this here so others can also track it: github/roadmap#86 and github/roadmap#58

**Comment by patoi** [comment]
https://github.com/github/roadmap/issues/58

![Uploading image.png…]()

**Comment by Zefiro** [comment]
For the record, the two roadmap items referenced by @KaiSforza are now placed in "Q3/21" (for beta) and unspecified "Future" (for ga), unfortunately.

**Comment by yanowitz** [comment]
😞 🐼  thanks for clarifying this. I've sort of given up :)

**Comment by busches** [comment]
> 😞 🐼 thanks for clarifying this. I've sort of given up :)

You're able to run dependabot in a docker image and point it to your GHE. We do this and it works great. Example https://github.com/dependabot/dependabot-script

**Comment by KaiSforza** [comment]
I ran into some issues last time I used that script, where it would not check for open issues already and would open new ones the nest time it ran. This is one of the things heavily pushing me to gitlab instead. There is an actual gitlab dependably service you can use very easily that does check for already opened issues.

https://gitlab.com/dependabot-gitlab/dependabot

**Comment by yanowitz** [comment]
> > 😞 🐼 thanks for clarifying this. I've sort of given up :)
> 
> You're able to run dependabot in a docker image and point it to your GHE. We do this and it works great. Example https://github.com/dependabot/dependabot-script

Agreed, I should've said that I did do that, and got the docker version to work on my GHE, many thanks to those who have worked on it. I just wish I could orchestrate it all within GHE, because I am engineering lazy.

**Comment by jimmybrancaccio** [comment]
> You're able to run dependabot in a docker image and point it to your GHE. We do this and it works great. Example https://github.com/dependabot/dependabot-script

Please correct me if I am wrong, but you'd need a Docker container per repository?

**Comment by busches** [comment]
@jimmybrancaccio No, you can use the dependabot-script docker image and then pass in the configuration with environment variables.

**Comment by KaiSforza** [comment]
You would need a separate container, iirc, though they can use the same image.

**Comment by jimmybrancaccio** [comment]
@busches Ah right, I think I was thinking the container ran 24/7, but you basically just run it whenever you want it to check for updates.

**Comment by philBrown** [comment]
> You're able to run dependabot in a docker image and point it to your GHE. We do this and it works great

We're doing this too with some success however is there any way to use a configuration file? We're trying to change the default PR labels

**Comment by asciimike** [comment]
Chiming in with an update on timeline: we're spinning up work on this now, with the goal of shipping in the Github Enterprise Server 3.3 release later this year.

A few notes for those interested:
 - We're planning on offering both Security Updates and Version Updates, but only for [Security Updates ecosystems](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems)
 - We'll initially only support alerts from public sources (no alerting based on internal sources)
 - We do plan on leveraging GitHub Actions, so you'll be required to set up self-hosted runners with certain parameters (we'll publish guidelines on minimum requirements as we get closer)
 - Those runners must have access to either the public internet (if fetching from public registries) or the network private registries are on, as we don't plan to do any fancy network traversal

Please let me know if you're interested in testing this out when we're ready.

**Comment by bgrainger** [comment]
willing to test, and our setup meets those requirements.

**Comment by pavera** [comment]
Closing as Dependabot is now available in GHES.
