### ISSUE TITLE
Problem with dependabot accessing public github repositories to update Pipfile

### ISSUE THREAD

**Issue by weiji14** [dependabot/dependabot-core#2150]
Hi there,

I've been getting this weird permissions issue a little over a month now (since mid April?) on pipenv VCS dependencies in my `Pipfile` which looks something like below:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
...
pygmt = {editable = true, ref = "0.0.1a0-16-g7004aa0", git = "https://github.com/GenericMappingTools/pygmt.git"}

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true
```
It's started showing up in https://github.com/weiji14/deepbedmap/issues/137 asking for me to:

> ... provide additional git credentials in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'. If you use a custom token for the host `github.com` make sure it has read access to this repo, too.

which I couldn't quite understand as the [`pygmt`](https://github.com/GenericMappingTools/pygmt) package in question was hosted as a public repository. I created an access token but that didn't solve the problem, so I thought maybe it was an issue with [`GenericMappingTools/pygmt`](https://github.com/GenericMappingTools/pygmt) itself, so I switched to my personal fork at [`weiji14/pygmt`](https://github.com/weiji14/pygmt), and then dependabot started complaining about another VCS dependency `geopandas` in https://github.com/weiji14/deepbedmap/issues/140 which is also publicly hosted.

That was when I realized it wasn't an issue with `pygmt`, but something with dependabot accessing github repository packages in general. I thought I resolved it in https://github.com/weiji14/deepbedmap/issues/142 by installing the dependabot-preview app on my personal pygmt fork, but the issue kept popping up (see https://github.com/weiji14/deepbedmap/issues/143 and https://github.com/weiji14/deepbedmap/issues/144).

Could you examine the logs and see what is going on, as I feel like I've exhausted every possibility on my side. Let me know if you need any additional information.

Thanks

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.
