### ISSUE TITLE
Enable configuration of a minimum package age required before a PR is created

### ISSUE THREAD

**Issue by fisker** [dependabot/dependabot-core#2151]
I like the idea of Renovate's unpublish-safe check, we should implement this feature.

**Comment by fisker** [comment]
Any updates?

**Comment by jeffwidman** [comment]
Duplicate of https://github.com/dependabot/dependabot-core/issues/3651. I realize this is the earlier issue, but that one has more discussion/fleshed out, so let's use it instead.
