### ISSUE TITLE
Support bundler package cache

### ISSUE THREAD

**Issue by paul** [dependabot/dependabot-core#2152]
Our app uses the `bundle package` feature to cache the gem files in the repo, which speeds up CI and deploys (since it doesn't have to download any files from rubygems or elsewhere). 

It looks like the PRs that dependabot open only update the Gemfile and Gemfile.lock, but don't add/remove the changed .gem files from `./vendor/cache`. Could support for this be added?

https://bundler.io/v1.6/bundle_package.html

**Comment by dentarg** [comment]
I think this is now solved? https://github.blog/changelog/2020-09-23-dependabot-supports-vendoring-for-ruby-bundler/

**Comment by jurre** [comment]
> I think this is now solved? https://github.blog/changelog/2020-09-23-dependabot-supports-vendoring-for-ruby-bundler/

Yep! 🎉 

> There's a small gotcha with it, if you ask dependabot to rebase after the workflow has run, the commit that the workflow pushed will be lost – it is because the commit is made with the same email/username as dependabot, and then dependabot doesn't understand that changes have been made.

FYI, nowadays, if you want dependabot to ignore/rebase over a(n) (automated) commit you made, you can include `[dependabot skip]` in the PR message and dependabot will force push changes over it.
