### ISSUE TITLE
Feature Request: gradual upgrades

### ISSUE THREAD

**Issue by mockdeep** [dependabot/dependabot-core#2154]
It would be nice if we could somehow specify how far a jump in versions is acceptable. Maybe this is more a problem in projects that are just starting out with Dependabot, but it would be helpful if rather than jumping 2-3 major versions, we could first have a PR to upgrade to the latest minor version, and once that is passing and merged, another to upgrade to the next major version, and so forth.

Often times there are several packages that depend on each other, especially when it comes to TypeScript, so this could help gradually wrangle deprecations and sort through code changes that need to be made in smaller chunks. Another minor benefit is that the "Release notes" and "Changelog" sections in the PR wouldn't need to be truncated as much.

Maybe a further extension would be if Dependabot could narrow in on a version that does work if a particular version does not pass the build.

**Comment by infin8x** [comment]
Closing this as we don't expect to get to it in the foreseeable future. You could use the ignore syntax: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore to selectively ignore major versions you're not ready to take yet.
