### ISSUE TITLE
Circle CI >Check docker images versions from .circleci/config.yml

### ISSUE THREAD

**Issue by adriens** [dependabot/dependabot-core#2156]
# Concept

In [CircleCI](https://circleci.com/) you can build workflows on Docker images. This is a very powerful tool.
What would be 💯 cool is to bet PR from dependabot on these docker images so I'm sure to maintain my workflow up-to-date.

What do you think about that guys ❔ Let me know 🙏

**Comment by infin8x** [comment]
Duplicate of #2172
