### ISSUE TITLE
Support a filter option on the repository list while adding repos

### ISSUE THREAD

**Issue by captn3m0** [dependabot/dependabot-core#2157]
This is how the GitHub repository list page looks:

![image](https://user-images.githubusercontent.com/584253/57578748-b964ca80-74af-11e9-93ed-679bafb4056a.png)

![image](https://user-images.githubusercontent.com/584253/57578749-c08bd880-74af-11e9-88b6-e2f85bc359ff.png)

![image](https://user-images.githubusercontent.com/584253/57578753-ced9f480-74af-11e9-92dc-1601732685b9.png)

There are 3 different ways to filter the list:

1. By Name. This happens live, and doesn't require a reload.
2. By Language
3. By repo kind (Public/Private/Source/Fork)

When I'm setting up Dependabot, I don't care so much about the forks as I do about my personal repositories. Having a way to filter so I can see my public/private owned repositories first will let me setup Dependabot much faster across the org/user account.

This is the corresponding Dependabot page that needs filtering:

![image](https://user-images.githubusercontent.com/584253/57578776-16f91700-74b0-11e9-87c4-f721fdbfb39d.png)

**Comment by infin8x** [comment]
Closing this as we're deprecating Dependabot.com in favor of management UI and config files inside GitHub.
