### ISSUE TITLE
Per repo PR limits

### ISSUE THREAD

**Issue by stevenwilliamson** [dependabot/dependabot-core#2158]
Feature request to be able to specify a PR limit for an entire Github repository. 

The specific use case I have where this would be useful is for Terraform configurations.

Terraform configurations are often structured as one or more git repositories that contain multiple terraform "modules". Our example case which is not a large example contains 170 modules. As a side note we have to generate the configuration file using a script due to the large number.

```
grep terraform config.yaml  | wc -l
     170
```

Because the limit appears to work for each of the individual "update_configs/directories" directives, the first run of dependabot against this repo generated 240+ PR's, along with causing issues hitting GitHub API limits.

As such we have had to disable dependabot for Terraform. I believe a global PR limit for a repo plus a resolution for dependabot/feedback#459, would make dependabot usable for Terraform configurations following this standard pattern. For reference a good overview of the rough structure of our Terraform code can be found [here](https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa)

**Comment by infin8x** [comment]
This is mostly solved by the new config file: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit, which allows you to set an open PR limit per repository, per ecosystem.

**Comment by DavidSpek** [comment]
@infin8x I'd like to re-open this issue as I am busy discussing using dependabot for the Kubeflow project. Each PR will create an EKS cluster to run testing on, and some repositories have very many folders with dependencies. While it is possible to set a low limit for every folder, having a global maximum PR limit that overrides the per folder limit would help to prevent reaching the 100 cluster EKS limit and prevent the devs from having an overload of PRs. Another option that has been discussed to try and reduce the overhead of dependabot for large projects or repositories is to have dependabot to group multiple dependencies together into a single PR.

**Comment by infin8x** [comment]
I'm no longer on the Dependabot team, sorry. @hmarr can get you pointed in the right direction.
