### ISSUE TITLE
Ignore Terraform releases for unchanged subdirectories

### ISSUE THREAD

**Issue by domcleal** [dependabot/dependabot-core#2160]
In Terraform, we can reference a module stored in a subdirectory of another Git repo which makes it easy to group together related modules into one repo rather than a large number of repos each containing one module.

When tagging one of these repos, Dependabot updates every dependency on it even if the module source is specifying a path that hasn't been changed between releases. Ideally for us, Dependabot would always ignore these updates as they're no-ops or have the option to ignore them.

Example PR: https://github.com/domcleal/terragrunt-infrastructure-live-example/pull/2

The module source is specifically the `mysql` subdirectory of the repo:

    source = "git::git@github.com:gruntwork-io/terragrunt-infrastructure-modules-example.git//mysql?ref=v0.0.1"

But the [git diff](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/compare/v0.0.1...v0.0.2) from v0.0.1 to v0.0.2 shows there have been no changes to `mysql/`, only to `consul/`.

It's both an issue for these Terragrunt tfvars style configs referring to a module and also for regular Terraform HCL files referring to modules, as both support specifying a path/subdirectory in a git source.

Here's another example repo containing 19 small CloudWatch alarm modules: [module-aws-monitoring-public](https://github.com/gruntwork-io/module-aws-monitoring-public/tree/master/modules/alarms/) (sorry, just the layout, the actual code's only subscribers). Whenever one module gets updated and released, any reference to the other 18 modules also trigger Dependabot PRs.

**Comment by jeffwidman** [comment]
I understand the feature request, and it makes complete sense... I've encountered a similar issue with Ansible in one of my personal projects.

However, I don't think Dependabot is the right place to solve this. We're trying to move toward having the package version detection / version-resolving logic live in the native package managers (in this case Terraform), and then Dependabot becomes the glue code for handling config/cron/PR creation.

So for this case, while I think this is a legit issue, I think this should be filed against upstream Terraform for them to provide a way to solve. If they ever offer a way to handle this, then we should definitely plumb it into Dependabot here. But we shouldn't re-implement that filtering logic ourselves here in Dependabot's Ruby code.
