### ISSUE TITLE
Add setting for assigning team members only for PRs that fail

### ISSUE THREAD

**Issue by JustArchi** [dependabot/dependabot-core#2162]
Hello.

I'd like from dependabot to find out when the PR fails (due to CI checks) and automatically assign the appropriate person to manually verify the PR, and fix it if needed.

I believe this could be very simple boolean checkbox on dependabot website, below "Assignees" with "Assign only when PR can't be merged automatically", or perhaps it could be even built-in automatic feature of not assigning people to PRs created by dependabot, unless they need to review it (either because of no auto-merges configured, CI failures or other reasons preventing dependabot from merging automatically).

Thank you for considering this enhancement.

**Comment by jeffwidman** [comment]
👋 sorry for the slow reply.

I understand the rationale here, but given that we currently don't support automerge (#1973) this isn't currently relevant.

I'm going to close as it's also not a commonly requested feature.
