### ISSUE TITLE
Rate Limit Improvements

### ISSUE THREAD

**Issue by simlu** [dependabot/dependabot-core#2163]
I'm looking at the organization settings. I have set the pr limit per repository to one (see screenshot).

![rate_limit](https://user-images.githubusercontent.com/1539747/56604641-4efaf180-65b7-11e9-8b73-12812dfe9dd5.png)

When enabling live updates I would expect the next pr to be opened automatically directly after an existing one is merged (if there are further ones pending). However that is unfortunately not the case.

What would be needed to support that?

Cheers, L~

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by tonydehnke** [comment]
So the use case for me on this is to reduce CI "looping" for new PR's that Dependabot creates.  If it opens 10, the checks start at all 10, then 1 is merged, the remaining 9 get bumped and rechecked, and this keeps happening as it works through all the PR's.  So it ends up using a lot of CI time - which can get costly. 
If it did it 1 by 1, you wouldn't have so many check, merge, check, merge loops happening.
