### ISSUE TITLE
Support for Dart/Flutter languages

### ISSUE THREAD

**Issue by privettoli** [dependabot/dependabot-core#2166]
I'm developing Flutter Dart app https://flutter.dev/
Are there any plans to support those?
As an example https://github.com/privettoli/socia-reto

Thanks in advance!

**Comment by Niek** [comment]
> FYI Dart 2.8 now includes a `pub outdated` command which might be helpful in implementing dependabot support https://medium.com/dartlang/announcing-dart-2-8-7750918db0a

I want to add to this: ``pub outdated --json`` returns an easily parsable JSON tree with the information.

**Comment by nstrelow** [comment]
FYI, There is now a `flutter pub outdated --json` command

**Comment by IchordeDionysos** [comment]
@greysteil do I understand this correctly, that dependabot, will not get Dart support in the first half of the year even if community contributions would be made?

> We are not currently accepting new ecosystems into dependabot-core, starting in December 2020 until at least June 2021.

**Comment by greysteil** [comment]
I don't have any more context on that one - @feelepxyz and @asciimike are the best folks to talk to give more details on when the Dependabot team will have capacity to take on support for more languages.

I will say that from my experience adding languages to Dependabot: It's always quicker when there's are community contributions, and folks who can answer questions. Given how modern Flutter is, I would imagine Dart will be a relatively straightforward language to add support for when the team has capacity.

**Comment by jurre** [comment]
> _greysteil do I understand this correctly, that dependabot, will not get Dart support in the first half of the year even if community contributions would be made?

That's right, we've paused adding/accepting support for new ecosystems so we can focus on improving the ones we have, and on rolling those out to GitHub. We want to make sure that we can confidently run such a new ecosystem at GitHub scale, and provide the support for them that our users deserve. 

For now, if someone would like to work on this I would recommend building a standalone gem on top of dependabot-core and running it on actions for example. Once we open things up we'd love to pull that into dependabot-core, flutter seems like an ecosystem we'd definitely want to support at some point, but @asciimike is probably the best person to give a definitive answer on that.

I'd be happy to chat a little more about how such a standalone gem could work etc!

**Comment by IchordeDionysos** [comment]
I've started implementing support for Dart in this PR: https://github.com/dependabot/dependabot-core/pull/3438

Would appreciate any help and feedback. 🚀 

I am especially unsure about the data that gets passed to the next layers, for example, if the source/requirements objects are properly created, etc.

**Comment by exvuma** [comment]
👋🏼 We have started testing out pub support for version updates on Dependabot! If you're interested in early access, please take a moment to fill out this [form](https://forms.gle/3N2q85acdHD95YSM6) and our team will reach out with the next steps to get your repo working with Dart 😄

**Comment by exvuma** [comment]
Today we released pub support as a public beta 🥳  See details in the [changelog post](https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/).

**Comment by jeffwidman** [comment]
I'm going to close this as support for Dart/Flutter _version_ updates is complete so we've removed the need for the feature flag mentioned in the above blog post.

There's still work being done in areas beyond version updates, such as security alerts, so we're not moving the ecosystem entirely out of beta, but for the perspective of this ticket the work is complete.
