### ISSUE TITLE
Restrict changing settings, config variables, plan to Github admins

### ISSUE THREAD

**Issue by cabello** [dependabot/dependabot-core#2168]
Hi 👋 

We just had an incident where someone or something removed the default rate limit from a value to unlimited, in the last 3 days we got 1000+ PRs from dependabot. We don't know what or who did it. Can we at least for the moment, restrict access to these pages: settings, config variables, plan to Organization admins only please?

Thanks 💜

**Comment by infin8x** [comment]
Closing this as the Dependabot.com dashboard is going away in favor of the Dependabot config file: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates, which can be controlled and protected via PR policies.
