### ISSUE TITLE
How to avoid security vulnerabilities introduced in packages from compromised accounts

### ISSUE THREAD

**Issue by connorshea** [dependabot/dependabot-core#2170]
Given the bootstrap-sass Ruby gem backdoor that was introduced a week ago, I figure it'd be good to talk about ways this kind of attack can be mitigated: https://snyk.io/blog/malicious-remote-code-execution-backdoor-discovered-in-the-popular-bootstrap-sass-ruby-gem/

I'd like to propose a few possible things that would have prevented dependabot from updating anyone to this version:

- The version was only pushed to RubyGems, not to GitHub. Therefore, there was no mention of a 3.2.0.3 version in the Changelog or Releases/Tags. If Dependabot doesn't detect a Changelog or Release for that version, maybe it should ignore it, or at least not merge it automatically?
- Compare the SHA hash of the gem to the SHA hash of the actual git tag it corresponds to. Unfortunately this isn't very easy because Ruby gems frequently remove things from the repo (e.g. tests) when packaging the gem, and also because the SHA hash of the git commit is determined from the git history as well as the contents of the repository, so you'd need to 1) pull down the repo and get the SHA of its contents, and possibly 2) actually build the gem yourselves to get an actual comparable SHA hash for the gem. And there's not really a standard command that'd build every possible gem, and also this'd be quite compute-intensive.

Also, this all assumes the gem is open source, which is only the case >99% of the time. For closed source gems this wouldn't really work (though, does RubyGems actually host closed source gems themselves?)

Obviously, there's only so much that can be done on dependabot's side of things. If the attacker gains access to the maintainer's GitHub account as well, or if the maintainer were themselves malicious, these wouldn't actually mitigate the issue at all.

Thanks for reading, this isn't an easy problem but I wanted to bring it up :)

**Comment by infin8x** [comment]
This is a problem we think about in Dependabot, but we don't yet have a specific solution in mind. I'm going to close this issue for now.
