### ISSUE TITLE
Support for Docker image references in CircleCI config

### ISSUE THREAD

**Issue by merwok** [dependabot/dependabot-core#2172]
Similar to dependabot/feedback#346 but for CircleCI.  CI pipelines are named workflows and made of jobs + rules (run on branch, run on tag, etc).  A job is a series of commands run within a docker container with a checkout of the code.  People use images provided by CircleCI, regular images or company-specific images (to preinstall tools etc).  When I push new docker tags for my company’s builder images, I would love to get a dependabot PR to upgrade my jobs config!

Some of the config file parsing could be shared with dependabot/feedback#362, but detecting new versions would be different (getting DockerHub tags vs. CircleCI orb registry API).  Also the images are only specified with one version, there is no set of files with dependencies vs locked dependencies, so an update scheme would need to be devised (can’t assume image tags are semver-style X.Y.Z or X.Y or calendarver).  For my case, I would be happy with a PR updating e.g. builder-python:1.4 to builder-python:1.5, and if I release builder-python:2.0 which requires human changes in the config, I’d be OK with a dependabot PR that fails, or with no PR and manual version upgrade required.

Not sure about how to find release notes, but at least links to the registry tag page would allow people to see the Dockerfile, build log if applicable, source code repo if linked.

Also a note that tags can be overwritten, but I think it would be OK to ignore changes to an existing tag.  (I take advantage of this in my ci-tools repo: every commit pushed to a PR that updates 1.4 → 1.5 creates tags 1.5-rc so that I can test with one real consumer project, then merging to the main branch publishes the 1.5 tag, which I don’t change.)

Regarding security implications, I think it’s a good practice to use images you control or from sources you trust, and we’d also have control with the `@dependabot ignore` commands, so I’m not worried about rogue updates stealing envvars or similar.

CircleCI config can reference custom registries and private images, but IMO it would be OK (even great!) to support the official DockerHub and only public images.

**Comment by infin8x** [comment]
Closing this as we don't expect to get to it in the foreseeable future. We're not accepting PRs at the moment due to capacity limitations, but in the future we expect to accept contributions, including those adding CircleCI support in Dependabot Core, as long as they don't damage the maintainability of Dependabot Core.

**Comment by merwok** [comment]
That’s too bad.
