### ISSUE TITLE
Need a better method to validate config variables

### ISSUE THREAD

**Issue by osman** [dependabot/dependabot-core#2173]
We have had an issue where dependabot is unable to connect to our private ruby gem server.

<img width="507" alt="Screen Shot 2019-04-02 at 10 18 09 AM" src="https://user-images.githubusercontent.com/122702/55409889-db724100-5530-11e9-9aa8-b464d455e4e5.png">

It would be nice to have a validate button on the config variables page to tell us what is wrong with the setting, if anything.

**Comment by jeffwidman** [comment]
This is an ancient ticket and the way that Dependabot configures/stores secrets has totally changed, as has the error messages. So closing as simply no longer relevant/completely outdated.
