### ISSUE TITLE
Dependabot to run a "full" `cargo update`

### ISSUE THREAD

**Issue by D4nte** [dependabot/dependabot-core#2174]
Hi,

Because our builds are quite lengthy, we are planning to do regular manual `cargo update` for the full lock file and let dependabot handle the `Cargo.toml` updates.

Thinking about it, it would be great if dependabot could do that for us: open 1 PR that does a full `cargo update` (not specific to one dependency). In other words, do all dependencies at once for cargo lock file updates only.

Then, for `Cargo.toml` dependencies update, do it dependency per dependency as usual.

What do you think?

Thanks.

**Comment by AArnott** [comment]
I want one aggregate PR for npm updates as well. Same for NuGet. With the option (say, when the PR build fails) `@dependabot split` to split the one PR into individual PRs for each package update.

It's quite alright (preferred even) if each top-level dependency update was in its own commit for that aggregate PR.

**Comment by abdulapopoola** [comment]
**Update**: We've started doing some grouped updates work! This particular issue might not be part of the first ship but if you want to track our updates, do follow #1190.

**Comment by abdulapopoola** [comment]
Closing this out as we've officially[ released grouped version updates](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/); please feel free to reopen or reach out if there are more questions or feedback.
