### ISSUE TITLE
Gradle: Possible to add a folder twice

### ISSUE THREAD

**Issue by mueller-ma** [dependabot/dependabot-core#2175]
Looking at the dashboard, I saw that /mobile (https://github.com/openhab/openhab-android) isn't added:
![grafik](https://user-images.githubusercontent.com/22525368/55253861-bd69bf80-5256-11e9-90d0-81eb49ac0189.png)
So I added Java/Gradle with the directory /mobile, but then I realized, that /mobile is covered by the already existing entry:
![grafik](https://user-images.githubusercontent.com/22525368/55253930-f144e500-5256-11e9-8d52-aa03428cd005.png)

This seems to be a bug for me (adding a directory twice).

After adding the directory Dependabot did it's job and opened a PR for each not-up-to-date lib. Most of them are not up-to-date with intent, except https://github.com/openhab/openhab-android/pull/1272. I haven't seen any closed PR or any other reason why Dependabot ignores this dependency before.
https://github.com/openhab/openhab-android/pulls?utf8=%E2%9C%93&q=auto-value+from+1.6.2+to+1.6.3

**Comment by infin8x** [comment]
Closing this as the Dependabot.com dashboard is being replaced by a configuration filehttps://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
