### ISSUE TITLE
Update versions in different Dockfiles separately (not together)

### ISSUE THREAD

**Issue by connorshea** [dependabot/dependabot-core#2179]
In [this PR](https://github.com/connorshea/ContinueFromCheckpoint/pull/251), Dependabot updates two separate Dockerfiles that use Alpine and Debian base images respectively, but it changes the distro of one of them from Debian to Alpine. (All are from [the official Ruby images](https://hub.docker.com/_/ruby))

`Dockerfile`:

```diff
- FROM ruby:2.6.1-alpine3.9
+ FROM ruby:2.6.2-alpine3.9
```

`Dockerfile.ci`:
```diff
- FROM ruby:2.6.1
+ FROM ruby:2.6.2-alpine3.9
```

Now, `Dockerfile.ci` intentionally uses Debian, while the production `Dockerfile` uses Alpine. I'm not sure if this is a weird/bad setup, but I was struggling to get Alpine working with all the test dependencies in CI (specifically chromedriver, but that's a whole other thing), so I ended up just using Debian instead for CI.

I'd say there are two issues here:

- Dependabot updates both Dockerfiles at the same time, when I'd probably expect it to update them as separate PRs.
- Dependabot changes the base image from `ruby:2.6.1` to `ruby:2.6.2-alpine3.9`. I would guess that it assumes that the Dockerfile base images should match each other, but I'm not sure.

Sorry I keep running into edge cases :P I love dependabot, and it usually works great for me :)

**Comment by atc0005** [comment]
I encountered this today.

Example PR: https://github.com/atc0005/go-ci/pull/98, https://github.com/atc0005/go-ci/pull/98/files
Config file: https://github.com/atc0005/go-ci/blob/master/.github/dependabot.yml

Another case of multiple Dockerfiles in the same path, but with different base images.

- [correct](https://github.com/atc0005/go-ci/pull/98/files#diff-2fab805bf622f99bb583a0f6cda64ed81505ad6db79cd8d0735c047673a382cf)
- [incorrect](https://github.com/atc0005/go-ci/pull/98/files#diff-69aca40757625027a2a90a72a8e7ba7dffa593b1149641383ba600056b5ccaa0)
- [incorrect](https://github.com/atc0005/go-ci/pull/98/files#diff-de5127f66510994b558b884581dc3c3fc58a91d3ec82aabb3e6e38968b9a36f6)

**Comment by kevinpapst** [comment]
[Here is another example](https://github.com/tobybatch/kimai2/pull/179), a Dockerfile with multiple stages (using different base images).
Dependabot is using the first found image and applies its update to all usages, effectively changing 
```
FROM php:7.4.11-apache-buster AS apache-debian-php-ext-base
```
into
```
FROM php:7.4.12-fpm-alpine3.12 AS apache-debian-php-ext-base
```
@greysteil you mentioned that this bug might be hard to tackle. Seeing this bug now being at least 1,5 years old, can we assume this won't be fixed anytime soon? I am asking, because in that case I would propose to disable dependabot for our repo in the meantime.

**Comment by atc0005** [comment]
> @greysteil: In future, the best solution here is probably for you to be able to specify to Dockerfile you want Dependabot to be running on (rather than the directory), so you get separate PRs and the above problem doesn't occur.

Do you have an example of this? Based on the documentation here:

https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

it appears that a directory path is required, instead of a specific file.

**Comment by greysteil** [comment]
Tagging in @feelepxyz and @jurre to make sure you get an answer.

**Comment by feelepxyz** [comment]
> Do you have an example of this? Based on the documentation here:
> 
> https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

@atc0005 yeah we haven't made any changes to this and still only support specifying a directory. We have some plans to allow globbing for manitest files for a particular ecosystem so will keep this in mind when we start looking at that.

**Comment by MCStreetguy** [comment]
Is there any update on this topic? This particular problem currently renders dependabot useless for most of my docker images and as far as I understand correctly, there is also no workaround available. Any chance this will still be addressed?

**Comment by deivid-rodriguez** [comment]
Pretty sure this was actually fixed by https://github.com/dependabot/dependabot-core/pull/5560, so let me close this. If still happening, please reopen!
