### ISSUE TITLE
how to target multiple composer.json in the same folder

### ISSUE THREAD

**Issue by tobybellwood** [dependabot/dependabot-core#2184]
Hi - we've got two composer.json files in the same folder (named differently obvs)

I know you can target multiple folders per project, but can you specify individual files to target (given that one of them is called composer-somethingelse.json)?

**Comment by benoitchantre** [comment]
@greysteil Any progress on this?

Another use case is to have a different configuration / reduced list of packages to speed up some CI jobs.

The desired Composer file can be selected for these jobs using a `COMPOSER` environment variable.
