### ISSUE TITLE
Splitting config files

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#2188]
Hi,

As you know https://github.com/the-benchmarker/web-frameworks/blob/master/.dependabot/config.yml is a very huge config files.

It could be helpful to split configuration into multiple files.

If I may, I think of a solution : having a service plugged as a `github ` or `gitlab` **hook** that store the configuration found in repository (so as an issue could be created if configuration is not valid)

Regards,

**Comment by infin8x** [comment]
Closing this as it's unlikely we'll get to this work.
