### ISSUE TITLE
Default org-wide repo settings

### ISSUE THREAD

**Issue by ocxo** [dependabot/dependabot-core#2193]
I'd like to be able to set a default "security only" setting for Dependabot. We turned it on for a lot repos this morning and it opened a flood of non-security PRs that we had to go back and close. Caused noise for our teams, put pressure on our build server, and as a side-effect caused us to exceed our GitHub API rate limit.

**Comment by deivid-rodriguez** [comment]
Not sure about other ideas for allowing it to be configured through the `.github` org repo, but the original request in this PR is now available. See https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories.

I'll close this given that the original request is implemented, and we can track more improvements as separate issues.

**Comment by dalepgrant** [comment]
Allowing it to be configured through the `.github` org repo is tracked in #3360, for anyone else like me looking for it.
