### ISSUE TITLE
Branch name generated are breaking SonarCloud scans

### ISSUE THREAD

**Issue by gkohen** [dependabot/dependabot-core#2195]
NPM updates such as the one below are breaking NPM scans because of "illegal" branch names.
We need a way to have these dots replaces with another character:

> ERROR: Error during SonarQube Scanner execution
ERROR: 'dependabot/npm_and_yarn/@babel/runtime-7.3.1' is not a valid branch name. It can only contain 'A-Z', 'a-z', '0-9', '-', '_', '.', and '/')

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
