### ISSUE TITLE
update_type improvements

### ISSUE THREAD

**Issue by cihati** [dependabot/dependabot-core#2197]
Per https://github.com/dependabot/dependabot-core/issues/956 , I learned that `update_type` can have only `security` and `all` values in `allowed_updates`. But for `automerged_updates`, it can have other values such as `security:patch`, `semver:minor`, `semver:patch`. I think `update_type` should behave predictably to allow for more intuitive use and extra features (e.g. only allowing non-major version jumps in dependabot PRs)

**Comment by infin8x** [comment]
Duplicate of #2219
