### ISSUE TITLE
Better diff for DefinitelyTyped packages

### ISSUE THREAD

**Issue by ybiquitous** [dependabot/dependabot-core#2200]
Could you please make the diff of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) NPM packages (e.g., `@types/react`) better?

For example, the "compare diff" link in the following PR description points to <https://github.com/DefinitelyTyped/DefinitelyTyped/commits>.
This URL can tell us nothing about what the update changed. 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/473530/51292463-201c2f00-1a4e-11e9-9db5-fd21f6677d7f.png)

Now, we're using own tool to output the diff and then commented the diff manually. It is troublesome work. 😕 

![image](https://user-images.githubusercontent.com/473530/51292629-ce27d900-1a4e-11e9-931b-5be0bcf44349.png)

If Dependabot would do similar tasks instead of us, we would be more happy!

**Comment by radeksimko** [comment]
Thank you everyone involved in making progress towards better dependabot!

I can see that packages were updated to reflect the new `repository.directory` field, including the ones in `DefinitelyTyped`, e.g.

```sh
curl -s $(npm view @types/mocha@8.2.2 dist.tarball) | tar -xvzf - && cat ./mocha/package.json | jq .repository
x mocha/LICENSE
x mocha/README.md
x mocha/index.d.ts
x mocha/package.json
{
  "type": "git",
  "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
  "directory": "types/mocha"
}
```

However despite this it seems that dependabot still currently only provides link to the `HEAD`, see for example this recent PR https://github.com/hashicorp/vscode-terraform/pull/731#issue-963687145

Am I right that there is still work left to do somewhere here in this repository to reflect the upstream npm changes?

**Comment by radeksimko** [comment]
I assume that the ongoing challenge is still reliably associating revisions with npm verisons, isn't it?

i.e. without `package.json` and/or npm API providing the git hash for each version I don't see how could dependabot point to a diff between any particular revisions. 🤔
