### ISSUE TITLE
Option to group all updates into a single PR for a repo

### ISSUE THREAD

**Issue by tomyan** [dependabot/dependabot-core#2203]
This is similar to dependabot/feedback#5, but would be an option to raise a single PR (or update a PR if there is one open already) whenever there are updates available for a repo. Making this tradeoff for a repo would have the advantage of having fewer PRs to deal with, so less time dealing with dependency updates - particularly if you manage a lot of repos.

**Comment by infin8x** [comment]
Duplicate of https://github.com/dependabot/dependabot-core/issues/1190
