### ISSUE TITLE
Java Maven Artifact Migration

### ISSUE THREAD

**Issue by davidgoate** [dependabot/dependabot-core#2205]
When running my build, spotbugs appears to have suggested:

> [WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2

I'm not sure internally how spotbugs knows this, but I think it'd be awesome if dependabot were able to handle this type of PR. We were using:

```xml
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-io</artifactId>
    <version>1.3.2</version>
</dependency>
```

and now we can use instead

```xml
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.6</version>
</dependency>
```

**Comment by jeffwidman** [comment]
Duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1947
