### ISSUE TITLE
"Live" support for git submodules

### ISSUE THREAD

**Issue by JustArchi** [dependabot/dependabot-core#2207]
I've set up dependabot today for several of my open-source projects and I'm loving it so far, thank you a lot! ❤️

I'm wondering if it could be possible to ask about potential enhancement to submodules feature by giving it "live" updates if dependabot can receive proper webhooks.

Let me explain my setup, I have a core repo C that includes several submodules:
- reference to wiki of repo C (on GitHub)
- a subproject that is a part of core project C
- a tool that is being used during building of project C

Right now dependabot is limited to fetching all of submodules and checking them in periods, but it's totally possible to use GitHub's webhooks for other projects, as long as:
- it's a wiki of the project (that we already have access to)
- or it's other repo under same account/organization that we can access, even if it's not configured by dependabot right now

This way dependabot could configure all found submodules via webhooks and receive live submodules triggers for all the projects that it has access to. It'd basically be a trigger for "Bump now", appropriately optimized to handle only the submodule that the webhook has referenced. Moreover, in the future it could be used even in cross-account scenario where user could get this output even while referencing somebody's else repo, as long as that other person is using dependabot for his own repo too (as you're able to receive webhooks from it in this case, and use them for first user's advantage).

Is there any interest for making something like this happen? I'm mostly interested in the wiki part personally, but I believe that this feature can shine in a lot of different aspects, especially considering that dependabot already has access to everything that is needed, it only requires a bit more logic to add.

Thank you in advance for considering this suggestion. I hope that we can see it happen 🤞

**Comment by AraHaan** [comment]
This can be done easily using simple github actions now, take a look at https://github.com/Elskom/Sdk/

I think it could be changed however to always check for live updates though, currently it updates on mine after the 1st 20 minutes of every hour instead of every 20 minutes like I intended to avoid spamming github actions every second on that.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the slow response... we've been a bit buried.

The "live" feature was not built out when Dependabot preview was migrated to native GitHub, so this isn't currently supported on any ecosystem, not just git submodules. It's unclear when/if we will support this in the future in the native GitHub service. For details/updates, subscribe to this issue:
* https://github.com/dependabot/dependabot-core/issues/3488

However, as a workaround, you can always run Dependabot yourself in a custom GitHub action. I haven't thought through the details, but it's probably not that difficult to wire up the bits necessary to simulate "live" updates via polling... You can also wire up pub/sub if you're willing to run your own service that listens for events. But the gist of it is `dependabot-core` is just a library... you can run it whatever way you wish.

**Comment by jtbandes** [comment]
> you can always run Dependabot yourself in a custom GitHub action

Are there any examples of what it would take to do this? It would really help to see a minimal working example that could be modified to individual needs. 🙌

**Comment by jglick** [comment]
If you are running the tool yourself in GHA anyway, you can also consider the likes of https://www.updatecli.io/.
