### ISSUE TITLE
Lag time before release

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/dependabot-core#2208]
Given the social engineering attacks that we've been hearing about lately, it would be nice to be able to delay an update. maybe something like:

1. open an issue according to current bump schedule rules
2. after 1 week, open pull request

alernatively, 

1. open PR according to current bump schedule 
2. automerge after delay

**Comment by infin8x** [comment]
We've removed automerge from GitHub-native Dependabot due to precisely the sorts of concerns raised in this thread. If/when we bring back auto-merge, we expect to do so in a way that addresses these concerns.

Duplicate of #2243
