### ISSUE TITLE
Please auto-merge pre-1.0 rust dependencies

### ISSUE THREAD

**Issue by konstin** [dependabot/dependabot-core#2209]
While semver itself allows any breaking changes in `0.x.y` release, cargo treats `0.x.y` as if `x` was the major version and `y` was the minor version. This means that in the rust ecosystem, `0.5.2` is considered to be compatible to `0.5.1`.

Currently, pre-1.0 rust dependencies are not automatically merged, even though most crates are `0.x.y` versions and behave according to the cargo semver rules. Please enable auto-merging for pre-1.0 crates.

**Comment by infin8x** [comment]
Automerge is no longer supported in GitHub-native Dependabot, so closing this issue.
