### ISSUE TITLE
Version bumping to something that isn't supported in python 2

### ISSUE THREAD

**Issue by matthewdeanmartin** [dependabot/dependabot-core#2210]
I have a few projects that I am trying to keep 2.x 3.x compatible. Dependabot keeps hitting 3.x only versions and my 2.x build starts to fail. When a release is being dependabot-bumped to a version that used to be 2.x + 3.x and the new version is only 3.x then the requirements file should have the version tag stuff included

e.g. 
https://travis-ci.com/matthewdeanmartin/find_known_secrets

I think this would work, but I haven't tested it.
foo>=3.0.5; python_version >= '3.0'
foo>=3.0.4; python_version < '3.0' 

pipenv has its own syntax, too.

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.
