### ISSUE TITLE
If target branch gets rebased dependabot will not re-open PRs

### ISSUE THREAD

**Issue by smithtopher** [dependabot/dependabot-core#2214]
If a target branch gets force pushed to after a dependency has been merged in and that dependency update got lost, is it possible to tell dependabot to reopen PRs for lost updates? Currently it seems to wait for the next version before opening another PR.

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.

**Comment by thetayloredman** [comment]
> Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.

I think this is the same problem?

I rebased main on my repo today to clean up commits, and accidentally also rebased onto all other branches (oops!), but now I want to reopen a dependabot PR. I tried `@dependabot recreate`, but dependabot says that it can just reopen it with `@dependabot reopen`, which I tried and I get "Dependabot tried to reopen this PR, but was told that it no longer has any history in common with the base branch (and therefore couldn't be reopened)."

![image](https://vulpro.is-inside.me/IVXwTbCy.png)
