### ISSUE TITLE
Graphs or statistics!

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#2216]
We'd find it **enormously** helpful if Dependabot's web UI could give us some insight into some basic statistics for our apps. We're thinking of things like either a graph or just raw stats on:

- the amount of time Dependabot PRs are left open before merging
    - This would be especially useful if we could see it along any of these dimensions:
        - min. time left open, max. time left open, avg. time left open
        - per-app vs. overall
        - security PRs vs. non-security PRs vs. all PRs
        - overall vs. sliding window of the past ~month
- the number of dependencies that are out-of-date over time (per-app and overall)
    - This would help us see if when we start using Dependabot on a repo with a lot of out-of-date dependencies, are we merging Dependabot PRs faster than new ones are coming in? (This is especially useful for apps that still see this message: `This repo was added to Dependabot recently, so you'll receive a maximum of 5 PRs for your first few update runs.`)

I get that this is probably a big ask, but even just a CSV dump would be hugely helpful for answering the big questions like:

1. Are we "keeping up" with Dependabot, or are we getting further and further behind?
2. How prompt are we with security patches?

These questions aren't necessarily hard to answer with one or two apps using Dependabot, but as we expand to dozens of apps with hundreds or thousands of recursive dependencies each, it gets really hard to know if we're prioritizing our time effectively here.

While we could potentially get this data ourselves via the GitHub API, we'd have to be mindful of lots of edge cases that Dependabot might have more insight into (for example, when an open Dependabot PR is closed because Dependabot opens a newer one that supersedes it, should that be treated as just one "continuous" PR from a stats point of view?).

Thoughts?

**Comment by spickermann** [comment]
I wonder if a first step could be to show Dependabot's commits on the contributor's page in the project's insights?

**Comment by greysteil** [comment]
Hey @Kaplas85, no near term update, but since Dependabot is now part of GitHub responsibility for this has shifted teams. At the org/enterprise-level, we're looking at building more metrics into the security tab on GitHub (affectionally known as "security overview") as well as the "dependencies" tab under the org-level "insights" tab. At the repo level I don't think there are any near-term plans, but I'll point the team at this feedback.
