### ISSUE TITLE
Support multi-module Maven projects

### ISSUE THREAD

**Issue by evenh** [dependabot/dependabot-core#222]
In a lot of (open source and enterprise) projects it is very common to create [Maven multi-module](https://maven.apache.org/guides/mini/guide-multiple-modules.html) projects. One can for example have a module for only domain classes, utils or interfaces meant for public consumption.

Dependencies (code dependencies, plugins etc) can be attached to any module, optionally overriding dependencies higher up in the hierarchy (often referred to as the _build reactor_ in Maven terminology).

In order for dependabot to be useful to a lot of Java shops, this functionality must be implemented.

See [this project](https://github.com/evenh/maven-multimodule-sample) for a sample.

**Comment by evenh** [comment]
I've updated this issue with a better description :-)

**Comment by greysteil** [comment]
Thanks for creating this @evenh. Here's my plan for implementing - am I missing anything?

**File fetching**
- Dependabot fetches the root `pom.xml` (i.e., the one that is in the directory specified by the user, which by default is the root directory of the git repo)
- Dependabot reads the `<modules>` from that `pom.xml` and looks in each of those directories for a `pom.xml`
  - If any directory specified as a module doesn't have a `pom.xml` Dependabot errors
- Dependabot reads each of the module `pm.xml` files looking for more modules, and recursively downloads them, too.

**File parsing**
- Dependabot parses each of the downloaded files as it normally would
  - **Question**: Will Dependabot ever encounter the same dependency being required twice, with incompatible versions? Is that allowed? As I understand it only a single version of a dependency is used by Maven.

**Update checking / file updating**
- Happen as usual

**Comment by evenh** [comment]
Your proposal looks sane to me. Regarding your question, yes - that's a possibility (unfortunately)

**Comment by greysteil** [comment]
Cool. FYI, the PR tracking this is https://github.com/dependabot/dependabot-core/pull/354. Should have it done tomorrow. 🎉

**Comment by greysteil** [comment]
https://github.com/greysteil/maven-multimodule-sample/pulls

🔥 🔥 🔥 

I'll blog about this and release it on Monday. @evenh - if you have any repos you'd like to try it on before then I'd be much obliged. There are bound to be a few bugs hiding in there.

Thanks so much for your advice and encouragement on this one!

**Comment by evenh** [comment]
That's just awesome @greysteil - good (and quick) work 😀 I've just updated https://github.com/evenh/maven-multimodule-sample/commit/4035b8862f1911b982be583242ce6ca89e4257b3 and was expecting two pull requests with 1 file each or one pull request with 2 files after pushing that last commit.

**Comment by greysteil** [comment]
Ah, Dependabot won't create that because it remembers that it's previously created a PR to `24.1-jre`. I can make it "forget" it from console though - one moment...

**Comment by greysteil** [comment]
And in other news, I've just added support for custom repositories 🎉
