### ISSUE TITLE
Opt-out PR closing

### ISSUE THREAD

**Issue by bustikiller** [dependabot/dependabot-core#2221]
I would like to prevent Dependabot from closing PRs when a newer version of the dependency exists. This PR has sometimes gone through QA processes, and is merged to several branches, so just closing the PR for the old dependency leaves the rest of the branches in an inconsistent status, usually with merge conflicts against the new version of the dependency.

I don't know what would be the ideal flow, but I would prefer to finally merge the PR that has been tested, and then start the flow with the new version.

Another option would be adding a label to the PR to indicate that some work has already been done on that dependency, and thus it should not be closed.

**Comment by infin8x** [comment]
This would be resolved by #2264
