### ISSUE TITLE
Feature: Create issues when a new non-lockfile only update is available

### ISSUE THREAD

**Issue by nesl247** [dependabot/dependabot-core#2226]
When a non-lockfile only update is available, it would be great to create an issue for this. This way we can investigate if we want to upgrade. Lockfile only updates are generally done as we don't want to have to deal with breaking changes. However, it would still be good to be notified about these.

I would do it as an issue instead of a PR as it's more of an issue. In a lot of cases, it may not be upgraded, and we don't like open PRs that won't be merged. I would think a command that we can use to tell dependabot to create a PR for the issue would be beneficial as well. This PR would bypass the lockfil-only setting.

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.

Also a duplicate of #2242
