### ISSUE TITLE
Add UI for adding many nested projects for a single repo

### ISSUE THREAD

**Issue by bsideup** [dependabot/dependabot-core#2228]
Hi!

We have a few modules per repo, and our Dockerfile is usually located in `/app/Dockerfile`, but Dependabot does not detect it automatically :(

Is it possible to make it scan the repo for the Dockerfiles? At least on 1st level :)
Or, alternatively, maybe we can hint the Dependabot (with some `.dependabot.yml` file in the repo) where to look for it (the reason why we prefer a file because we can easily copy the file from one project into another and when we create new repos we will have it under the standard set of files)

**Comment by infin8x** [comment]
Closing this as Dependabot is now configured via a configuration file, rather than the UI: https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates
