### ISSUE TITLE
Ip-addresses used to access nuget

### ISSUE THREAD

**Issue by Leh2** [dependabot/dependabot-core#2230]
Can we get the ip-addresses that are used to access custom nuget feeds?

**Comment by infin8x** [comment]
Please see this page for details on GitHub's IP address: https://docs.github.com/en/github/authenticating-to-github/about-githubs-ip-addresses

**Comment by sorenhansendk** [comment]
Hi @infin8x! I have tried to configure our NuGet feed to allow traffic from all CIDRs mentioned in the meta endpoint (https://api.github.com/meta) but it still not working. The IP addresses dependabot uses right now is `3.94.32.93` and that is not in any ranges from the meta endpoint.

**Comment by jurre** [comment]
Are you perhaps using dependabot-preview?

**Comment by sorenhansendk** [comment]
@jurre Hi. We configure it via app.dependabot.com - is that the preview?

**Comment by jurre** [comment]
> @jurre Hi. We configure it via https://app.dependabot.com - is that the preview?

Yes, dependabot.com is the [pre-acquisition](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) product, and we're working on phasing it out and moving all functionality [natively into github](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates)

If possible, I'd look into migrating to the github native version, but there are still some features (mainly private package registry support) that are not available yet.

The dependabot-preview IPs are: `18.213.123.130`, `3.217.79.163` and `3.217.93.44`

**Comment by sorenhansendk** [comment]
@jurre Oh, cool! I didn't know that. We will open for that IPs. Thank you! 🎉

**Comment by sorenhansendk** [comment]
@jurre Do you have more IP addresses in the pool? Right now we get hitted by `3.94.32.93`

**Comment by thepwagner** [comment]
The latest IPs for Dependabot Preview, https://app.dependabot.com/, are:
```
3.209.160.83
3.93.159.41
3.94.32.93
```

The latest IPs for GitHub's Security Updates / Version Updates (i.e. Dependabot built into GitHub.com) are:
```
18.213.123.130
3.217.79.163
3.217.93.44
```

**Comment by sorenhansendk** [comment]
@thepwagner Ok, thank you 👍 Will these IP addresses we changed or be available in a API?

**Comment by jurre** [comment]
Hey @sorenhansendk I've added the IPs for the GitHub native version to the [meta](https://docs.github.com/en/free-pro-team@latest/rest/reference/meta) endpoint. The dependabot-preview IPs are not expected to change before the service will be shut down (there will be a full migration etc available before that happens), so those IPs will not be available in an API.

**Comment by sorenhansendk** [comment]
@jurre Thank you! That is pretty cool. Will these IPs also be exposed though the GitHub Terraform provider? 

https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/ip_ranges

**Comment by jurre** [comment]
> @jurre Thank you! That is pretty cool. Will these IPs also be exposed though the GitHub Terraform provider?
> 
> https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/ip_ranges

I would think so, yes, since that seems to use the API underneath: https://github.com/integrations/terraform-provider-github/blob/405dc41822596572a752f704dd62b6fb49508948/github/data_source_github_ip_ranges.go#L39
