### ISSUE TITLE
Question: Is it possible to give read only access to organisation or repository settings?

### ISSUE THREAD

**Issue by davidgoate** [dependabot/dependabot-core#2232]
Is it possible to grant read only access to other users?

# Context 
* We have many repositories which are managed and some settings (such as the automatic merging of PR's security vs patch vs minor vs all etc) and JavaScript `package.json` options are defined per repository and not globally.
* Also when new repos are created these settings need to be applied manually individually, which can be easy to forget.
* When working in a team, for only one person to have this access makes them a bottleneck for everyone else when they have questions about the settings as they can't simply look themselves.

**Comment by infin8x** [comment]
Dependabot is now configured largely via the config file: https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates.
