### ISSUE TITLE
Support batching of Pull Requests

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/dependabot-core#2233]
Similar to dependabot/feedback#5, but far more automated and far less intelligent.

I had to remove lock files from all of my projects because doing a live bump for every lockfile update lead my Circle CI usage to go from 4 hours a month to 60. I'd like to propose the following algorithm for batching PRs when anything other than live bumping is chosen:

1. On whatever schedule the user chooses, do the following:
  1.  open a PR with all updates. 
  2. if 1.1 fails, close the PR and open two PRs, one with half of the updates.
  3. if 1.1 passes, stop

Merge or wait for user input as appropriate. 

In general, this should reduce the number of runs for a given set of changes and, more importantly, when a PR gets merged, fewer CI runs should be triggered when ever dependency gets rebased independently.

**Comment by infin8x** [comment]
Duplicate of https://github.com/dependabot/dependabot-core/issues/1190
