### ISSUE TITLE
[feature request] Tabular view

### ISSUE THREAD

**Issue by cabello** [dependabot/dependabot-core#2234]
Hi 👋 

We have 21 repos added to Dependabot and I feel they would be better presented in table form.

Things I would like to do: 
- sort by language
- sort by last checked
- sort by weekly, daily
- turn on/off extra columns like the ones that are hidden behind "Edit button", for example "Only security patches"
- maybe filter/search some of the entries

Thanks for considering it.

**Comment by infin8x** [comment]
Closing this as the Dependabot.com dashboard will be sunset in favor of experiences built into GitHub.
