### ISSUE TITLE
Better detection of whether a Go repo is an application or a library

### ISSUE THREAD

**Issue by bartoszmajsak** [dependabot/dependabot-core#2235]
It seems that subsequent bumps of the dependencies in golang projects (using dep) result in updating `Gopkg.lock` [[1]](https://github.com/arquillian/ike-prow-plugins/pull/229) instead of `Gopkg.toml` [[2]](https://github.com/arquillian/ike-prow-plugins/pull/227) as it was initially. Is that intended?

**Comment by infin8x** [comment]
Closing this as `dep` has been replaced by `go mod`
