### ISSUE TITLE
Pull license data?

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#2236]
There's a good chance that this doesn't make sense as a Dependabot feature, but here goes! 😃 

I noticed that Snyk (which works slightly differently but I consider it in the same space as Dependabot) [scans for dependency licenses](https://snyk.io/features/enterprise#licenses) to help ensure an organization uses licenses they know they comply with.

I can't really figure out a good way for Dependabot to add that sort of behavior, and it might be best if we just put something like [Pivotal's LicenseFinder](https://github.com/pivotal-legacy/LicenseFinder) in our CI build and called it a day, but I just wanted to flag that some feature along these lines might make sense for Dependabot.

**Comment by infin8x** [comment]
Closing this as GitHub's Dependency Graph and Dependency Insights features are responsible for providing this data.
