### ISSUE TITLE
Notify user when an `npm` package dep is deprecated

### ISSUE THREAD

**Issue by mattwelke** [dependabot/dependabot-core#2239]
DefinitelyTyped deprecates @types packages when their respective package maintainers begin to ship type definition files with the packages. This can be because they took on the responsibility of writing separate type definition files themselves or because they migrated completely over to TypeScript, and so they're taking advantage of the fact that the TypeScript compiler will generate type definition files for their code automatically during the compile step.

When this happens, DefinitelyTyped adds a deprecation warning to the "@types" package and replaces the type definition files in the package with stubs, that way they won't conflict with the more authoritative bundled type definition files.

I think that Dependabot should be configured to look for these deprecations and send in pull requests to remove them from the package.json file. I'm not familiar with Dependabot's internals, but I can think of a few things to look for:

* The `npmjs.com` web page for the package will display a structured deprecation message containing the name of the package. For example, for `moment`, we have the message:

```
This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
```

Additionally, the NPM package's dependencies at this point will be only the library itself (`moment`, in this example).

**Comment by infin8x** [comment]
The Dependabot team don't expect to get to this, but are open to contributions - please get in touch if you'd like to implement this in `dependabot-core`.

**Comment by jeffwidman** [comment]
I don't think we'd ever implement the one-off functionality of removing the `@types` dependencies, but at a more general level we would like to eventually support notifying users when their dependency packages are deprecated. So I retitled the issue. 

How we do that is TBD... how the deprecated dep will get handled typically requires a developer to make some decisions that can't be outsourced to a bot.
