### ISSUE TITLE
Feature Request: Assign a random reviewer from a given list of users or a team

### ISSUE THREAD

**Issue by drewpterry** [dependabot/dependabot-core#2241]
Currently you can use `@dependabot use these reviewers` to add reviewers automatically for a Dependabot PR.

I'm working on a larger team and don't want to tag a whole bunch of people and have them be bombarded with Dependabot review requests. It would be really great to have a command that would allow me to automatically assign one reviewer from a group automatically forever.

So for example say I have github users `@user1, @user2, @user3, @user4` that are on the same team called `@team1`.

Having a command like `@dependabot assign reviewer from @team1` that would randomly assign one of the four members from that team to the PR would be useful.

**Comment by infin8x** [comment]
Closing this as we don't expect to implement it in Dependabot directly. There are various GitHub Actions and integrations that can assign PRs in a random fashion.
