### ISSUE TITLE
Project specific configuration for "Automatic PR rebases"

### ISSUE THREAD

**Issue by codebycliff** [dependabot/dependabot-core#2244]
I would like to turn on "Automatic PR rebases" for specific projects, not at the global level. Automatic rebasing fits some of our project workflows, but not all. Because of that, we have it disable across the board. I would really like to be able to enable this at the project level.

**Comment by infin8x** [comment]
Closing this as the `rebase-strategy` is available in GitHub-native Dependabot: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#rebase-strategy
