### ISSUE TITLE
Don't allow manual additions/changes to use unqualified releases

### ISSUE THREAD

**Issue by nesl247** [dependabot/dependabot-core#2248]
I'm not sure if this is something Dependabot would ever want to do, but the name itself doesn't imply it couldn't be done.

What I am thinking is to have Dependabot check all PRs for changes to a package manager's config file, like `composer.json`, and stop a PR from being merged if it uses unqualified releases like `dev-master`.

It's highly unrecommended to use versions like that, and unless it's a specific dependency, like security update checkers, it should be avoided.

**Comment by infin8x** [comment]
Closing this due to age and low demand. Folks on the GitHub dependency graph team are thinking about scenarios like these though.
