### ISSUE TITLE
Auto-merge updates based on compatibility score

### ISSUE THREAD

**Issue by connorshea** [dependabot/dependabot-core#2252]
This might be too complicated to be worth implementing, but I was thinking about how to handle dependency updates for something like [ouija-bot](https://github.com/connorshea/ouija-bot). The problem is that there's not really a good way to write tests for Discord bots because no one has made a proper scaffold for the whole of Discord's API and something like VCR to replay API requests would probably be overkill for a relatively small project.

So, the project doesn't really have any CI to speak of other than Rubocop, which hardly counts. Because of this, I'm left with three options for dependency updates:

- Disable dependabot (bad)
- Merge every dependency update manually (this is okay, but not ideal)
- Merge every dependency update whenever CI passes (this is risky because it could break the bot without me knowing, since CI passing doesn't really mean much)

So I want to suggest a fourth option:

- Merge dependency updates if the compatibility score for a given update of a dependency is >95% (or >90%, or whatever you want. It may also be useful to be able to require that there are e.g. >100 projects that have had this specific dependency updated).

This way I can rely on other codebases that actually have a proper test suite to verify that the new release of a gem doesn't have significant problems or breaking changes.

Just a thought :)

**Comment by infin8x** [comment]
Closing this due to age, low demand, and the lack of auto-merge support in GitHub-native Dependabot. If this scenario is critical to your workflow please feel free to comment.

**Comment by alwell-kevin** [comment]
Automerge is [now available in Beta](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request) on GitHub.com.
