### ISSUE TITLE
Opt-out of compatibility scores

### ISSUE THREAD

**Issue by connorshea** [dependabot/dependabot-core#2253]
I actually don't want this for privacy reasons, but because one of my projects, [ouija-bot](https://github.com/connorshea/ouija-bot), doesn't really have any test suite to speak of due to Discord bots not really being very easy to test. If it passes the CI, that just means rubocop is still passing. I don't want to add useless data to the compatibility score, so I'd like to be able to opt-out.

I don't know how many projects would opt-out for other reasons, or if this would make the dataset less useful overall, but I figured I'd request the feature :)

Thanks for dependabot!

**Comment by jeffwidman** [comment]
We had some internal discussion on this, and we are not going to do this in the foreseeable future... it's a bit of a niche feature request and given the amount of work it would take, the value just isn't there. Our time is better spent on other improvements for users.
