### ISSUE TITLE
Composer's require-dev dependencies do not need "permit version" updates

### ISSUE THREAD

**Issue by nesl247** [dependabot/dependabot-core#2256]
Updates that say "Updates the requirements on phpunit/phpunit to permit the latest version." with a title for something like "Update phpunit/phpunit requirement to ^6.4|^7.0" are not needed, at least in any case I can think of.

Dev dependencies should be the same for all users of the app, so that the same version of phpunit for example is used to run the tests.

Are there other scenarios that I am not thinking of that this makes sense?

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
