### ISSUE TITLE
Feature: Be able to subscribe to notices about new features

### ISSUE THREAD

**Issue by rdunlop** [dependabot/dependabot-core#2257]
Yesterday I read through the dependabot blog again (I try to do this every month...), and I noticed that there's a new feature which allows limiting the number of dependabot PRs to 10.

I decided that I didn't want this feature, so I went and disabled it. This morning I woke up to about a 
hundred dependabot PRs. (I'm happy about this). Until now, I didn't know that my projects were getting out of date.

Feature request: Have a way to subscribe (via email) to notices about new features/behavior. Essentially, I think that we need a way to subscribe to your blog...so that it's a push mechanism, not a pull mechanism.

**Comment by infin8x** [comment]
You can do this via the GitHub Changelog! https://github.blog/changelog/
