### ISSUE TITLE
Feature: show change in npm install size

### ISSUE THREAD

**Issue by styfle** [dependabot/dependabot-core#2258]
I really like dependabot, and I use it regularly with [Package Phobia](https://github.com/styfle/packagephobia/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed).

I think it would be cool to use data from Package Phobia when submitting the PR to update an npm dependency.

Maybe something like, "an increase of x MB" or "a decrease of x kB".

## Mockup

![mockup](https://user-images.githubusercontent.com/229881/41439085-6b5a1a06-6ff7-11e8-8928-c6a937fb3442.png)

## Package Phobia web app

https://packagephobia.com/result?p=prettier@1.13.0

## Package Phobia API

https://packagephobia.com/v2/api.json?p=prettier@1.13.0

**Comment by infin8x** [comment]
Closing this as it's unlikely we'd take this directly in Dependabot. We'll pass the idea on to the GitHub dependency graph team, as it's a more suitable addition there.
