### ISSUE TITLE
Feature suggestion for Java source files

### ISSUE THREAD

**Issue by davidgoate** [dependabot/dependabot-core#2260]
We have uses cases where we reference docker image tags inside java source files. the main usecase for this is in integration tests as we use docker junit and a file might look like:

```java
public class WireMockDockerRule extends DockerRule {

    private static final String DOCKER_IMAGE = "rodolpheche/wiremock:2.16.0-alpine";

    public WireMockDockerRule(final PortBinding binding) {
        super(ImmutableDockerConfig.builder()
                .image(DOCKER_IMAGE)
...
                .build());
    }

    private static Map<String, List<PortBinding>> getPortBindings(final PortBinding binding) {
...
    }

}
```

I'd be great if `.java` files could be scanned - I understand that it could be tricky to look for docker image tags inside strings of source files and perhaps costly.

What if there were either a source retention annotation or even just a comment in a specific format that dependabot could regex search for.

e.g.

```java
public class WireMockDockerRule extends DockerRule {

    @DependabotManaged(type="docker")
    private static final String DOCKER_IMAGE = "rodolpheche/wiremock:2.16.0-alpine";

...

}
```

or

```java
public class WireMockDockerRule extends DockerRule {

    //dependabot: docker
    private static final String DOCKER_IMAGE = "rodolpheche/wiremock:2.16.0-alpine";

...

}
```

which would help dependabot scan the `.java` files in the repo and then bump these strings as it would for a `FROM` line in a `Dockerfile`

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
