### ISSUE TITLE
Show details from timed-out update runs

### ISSUE THREAD

**Issue by swegner** [dependabot/dependabot-core#2261]
I just tried integrating dependabot on a personal repo ([swegner/beam](https://github.com/swegner/beam)) using Gradle. I see that dependabot "bumped" an hour ago, but I don't see any output. No pull requests are open, and I can't tell whether I have it properly configured.

It'd be nice if dependabot gave some output about what happened in its last run. On a successful run, this could include:

1. The head commit used.
1. What build system was used and what build files it found for that build system
1. The dependencies detected and their current version
1. A status for each dependency: whether it is known up-to-date / stale, or unknown.
1. Action that was take for stale dependencies.

**Comment by erdnaxeli** [comment]
What is the timeout time?

**Comment by duhseekoh** [comment]
I'm seeing failures at the 30 minute mark. Our yarn.lock file, which is big, but not out of the ordinary can't be processed by dependabot for within that timeframe for some reason. In the dependabot logs, only a handful of out the many dependencies get checked. We've been missing a lot of updates because of that. :(

**Comment by erdnaxeli** [comment]
> I'm seeing failures at the 30 minute mark. Our yarn.lock file, which is big, but not out of the ordinary can't be processed by dependabot for within that timeframe for some reason. In the dependabot logs, only a handful of out the many dependencies get checked. We've been missing a lot of updates because of that. :(

I have the same kind of problem with a Pipenv file. It tooks some time when running manually but no more than 5 minutes, I don't understand.

**Comment by jeffwidman** [comment]
The code around timeouts has changed a _lot_ since this issue was filed/updated. In fact, it's on a completely new infrastructure backend. So I'm going to close this, but if you are still seeing problems, please file an issue and we can look at what is happening in that specific case.
