### ISSUE TITLE
Per repo daily bump scan time setting rather than global

### ISSUE THREAD

**Issue by davidgoate** [dependabot/dependabot-core#2263]
If the org has a large number of repos and all the bumps happen at the same time (e.g. 05:00 UTC) then the CI such as jenkins gets immediately hit with a large number of PR's which causes the executors to get very busy. Would be good to stagger them, perhaps per repo or some delay between opening PR's.

**Comment by infin8x** [comment]
This is supported by GitHub-native Dependabot: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleinterval. See this blog post for how to migrate from Dependabot.com: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
