### ISSUE TITLE
Dependabot stalled on automated package update

### ISSUE THREAD

**Issue by GeorgeWL** [dependabot/dependabot-core#2269]
**Package manage/ecosystem**

JavaScript
**Manifest contents prior to update**

**Updated dependency**

Express-jwt 5.3.3 to Express-jwt 6.0.0
![Screenshot_20200630-175842](https://user-images.githubusercontent.com/5931248/86154815-7fafb280-bafb-11ea-84bf-d171747a1a1f.jpg)

**What you expected to see, versus what you actually saw**

**Images of the diff or a link to the PR, issue or logs**

**Comment by feelepxyz** [comment]
@GeorgeWL we're rolling out some improvements around this soon. There are cases where the security updates setting doesn't always install the app which causes the update to hang forever. You can attempt to fix it by turning `Dependabot security updates` on and off in your repo settings under `Security & analysis` 🙂

**Comment by GeorgeWL** [comment]
Tried that and my first guess, seems to not have worked.

I'll just update it manually and I think it will probably be fine next time

**Comment by lseppala** [comment]
We've made a lot of improvements to Dependabot since this issue was reported, and hopefully this hasn't happened again. I'm going to go ahead and close this issue, but please feel free to reopen and tag me if you continue to experience this problem 🙂
