### ISSUE TITLE
Ignoring a specific subfolder

### ISSUE THREAD

**Issue by yen0x** [dependabot/dependabot-core#2276]
Hi, we were wondering if it is possible to exclude a subfolder. For instance, we have an application with a `/scripts` subfolder that we wouldn't want dependabot to parse, but we still want the rest of `/` to be checked. We've only found out the possibility of ignoring specific dependencies with the `ignored_updates` tag so far which is not adapted to our usecase.

**Comment by feelepxyz** [comment]
@yen0x 👋 do you have manifest files in `/` that are referencing files in `/scripts` that shouldn't be checked? 
Dependabot only scans dependencies in the directory you ask it to check and any other files that are referenced from there, which will be needed to make the package manager resolve all dependencies.

**Comment by yen0x** [comment]
No we're not referencing `/scripts` in our root folder so from what you say, the case I mentioned should not be happening. Thank you for these details.

**Comment by dhowe** [comment]
Have the same problem -- is there a solution for this? I want to specifically ignore a directory that is continually sending me dependabot messages/PRs

**Comment by drdavella** [comment]
I have the same problem. I am currently required to use this tool by my management but will look for alternatives if this kind of basic functionality isn't provided.

**Comment by ingogriebsch** [comment]
We also have the same problem and would really appreciate a solution! :)

**Comment by alexweininger** [comment]
Having the same issue. Why was this closed?

**Comment by dhowe** [comment]
Same problem here -- please re-open

**Comment by chenrui333** [comment]
I just opened [a new one](https://github.com/dependabot/dependabot-core/issues/4364) for my case, feel free to re-post there
