### ISSUE TITLE
Dependabot creates orphaned PRs

### ISSUE THREAD

**Issue by SerCeMan** [dependabot/dependabot-core#2282]
**Package manage/ecosystem**
java, maven

**Manifest contents prior to update**
a pom file

**Updated dependency**
multiple

**What you expected to see, versus what you actually saw**
Periodically, dependabot creates PRs without any labels. For these PRs, dependabot doesn't react to comments, e.g. `@dependabot recreate` commands are ignored. Additionally, it seems like creating these PRs exceed the 10 PR limit. 
<img width="579" alt="Screen Shot 2020-07-06 at 12 15 29 pm" src="https://user-images.githubusercontent.com/1780970/86549246-69ce4180-bf82-11ea-98b7-913ffb33550f.png">

In the screenshot above, the "tagged" PR worked as expected, and dependabot was able to react to commands, etc. However, for the rest that were created (more than 20) - dependabot wasn't able to react. 

The repository is private, however, I'm happy to provide any additional information. 
 

**Images of the diff or a link to the PR, issue or logs**

**Comment by jurre** [comment]
Hi @SerCeMan I think we have an idea what happened here, we're looking into a fix. Will keep you up to date when we know more.

**Comment by jeffwidman** [comment]
@SerCeMan sorry that we never circled back here. 

Given that this was nearly 2 years ago, I suspect that the underlying issue was resolved, so I'm closing this.

If you still see this happening, please comment and I'll happily re-open, as this is _not_ expected behavior.
