### ISSUE TITLE
Unsupported package_manager npm_and_yarn

### ISSUE THREAD

**Issue by androdel** [dependabot/dependabot-core#2285]
When running my Ruby script, I get the following error:

```
/usr/local/lib/ruby/gems/2.6.0/gems/dependabot-core-0.94.13/lib/dependabot/file_fetchers.rb:11:in 'for_package_manager': Unsupported package_manager npm_and_yarn (RuntimeError)
```

When I try any other package manager, I get the same error.

```
require "dependabot/file_fetchers"
require "dependabot/source"

package_manager = "npm_and_yarn"

...

fetcher = Dependabot::FileFetchers.for_package_manager(package_manager).new(
  source: source,
  credentials: credentials,
)
```

Am I missing something?

**Comment by jurre** [comment]
You'll need to require the files from NPM:

```ruby
require "dependabot/npm_and_yarn"
```

Optionally you might need to add them to the load path before that by doing `$LOAD_PATH << "./npm_and_yarn/lib"`

**Comment by androdel** [comment]
Thx @jurre, but now I get the following error:
```/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:155:in 'require': cannot load such file -- dependabot/npm_and_yarn (LoadError)```

Did your $LOAD_PATH suggestion as well, but same result.

PS: I'm a Ruby noob btw 😛

**Comment by feelepxyz** [comment]
@androdel how are you running this? Are you running inside the core repo? You might be better off looking at dependabot-script where you only need to require `dependabot/omnibus` if you've installed it using bundler.

For example: https://github.com/dependabot/dependabot-script/blob/main/generic-update-script.rb (the readme has some pointers to get setup)

**Comment by androdel** [comment]
I installed it as a gem.

**Comment by androdel** [comment]
I'm up and running now. Thx @feelepxyz and @jurre for the help!
