### ISSUE TITLE
Error when clicking on Select Repos to add

### ISSUE THREAD

**Issue by jaganaath** [dependabot/dependabot-core#2289]
When clicking on 'Select Repos to add' button to allow scans on private repository, I get a page with below message:
GET https://api.dependabot.com/repos
Report an issue

However, I can see the Dependabot IPs are added in the security tab.

**Comment by lseppala** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

**Comment by jurre** [comment]
Given that this issue if for a feature that is (at least for now) not supported in the GitHub-native version of Dependabot and Dependabot Preview has been shut down, I'm going to close this issue. If we decide to bring this feature back in the future, we'll make sure to keep this in mind.
