### ISSUE TITLE
What release is Github running

### ISSUE THREAD

**Issue by a1flecke** [dependabot/dependabot-core#2292]
Hello,

I am trying to determine if my fix in #1924 was incomplete as I am still seeing some PRs being declared as non-SemVer when they are SemVer (different minor values) because they are build identifiers.

What dependabot-core release is Github currently running?

Thanks,

Aaron

**Comment by av-pinzur** [comment]
I also need this feature. Can you tell me where it’s at? Thanks!

**Comment by ylemkimon** [comment]
According to the log:
> updater | time="2020-07-26T18:19:26Z" level=info msg="starting job..." job_id=39488562 updater_version=**0.118.7**-6283553d1b6a61236381cf24f3eabb3a37a9d6e4

**Comment by a1flecke** [comment]
@ylemkimon Thanks!
