### ISSUE TITLE
[Private Registries] Unable to fetch repo metadata from private registry

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#2293]
Recently, I encountered an issue where dependabot-core was unable to fetch repo metadata i.e releases text, changelog, commits, etc. from private registry in `metadata_finder` class for `npm_and_yarn`. Upon further investigation, I found out that while fetching the metadata it uses `Bearer` authorization to authenticate whereas I was using a `Basic` base64 encoded auth token. 

Is there a reason behind only using Bearer authorization in the above scenario whereas in other scenarios (i.e `getting latest version` of package from registry), it decides the authorization based on the token like here : https://github.com/dependabot/dependabot-core/blob/9f7b26453519e1b2a2db21d19078d4a65755bf6d/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L73

**Comment by asciimike** [comment]
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta, which may help fetch info from private registries. Closing this as it should provide the ability to grab that info if you provide auth info, but if it doesn't work, feel free to re-open.
