### ISSUE TITLE
Please add a license to dependabot/gomodules-extracted

### ISSUE THREAD

**Issue by andrewedstrom** [dependabot/dependabot-core#2300]
https://github.com/dependabot/gomodules-extracted/issues/4

The repo https://github.com/dependabot/gomodules-extracted currently redistributes golang source code without retaining the original copyright notice, in violation of the [golang license.](https://github.com/golang/go/blob/master/LICENSE)

Please add the original copyright notice into that repo. Thanks!

**Comment by hmarr** [comment]
Fixed - thanks for pointing this out!
