### ISSUE TITLE
Allow bumping GH actions to rolling releases

### ISSUE THREAD

**Issue by evgeni** [dependabot/dependabot-core#2304]
Currently dependabot will bump GitHub actions to whatever the latest `vX.Y.Z` tag is. However, actions also usually have a `vX` tag that points to the latest X.Y.Z (and gets updated). I'd like to be able to select the bumping behavior and prefer `vX` tags.

Example PR that was opened with full version and then manually changed to `v2`: https://github.com/theforeman/releasetool/pull/19

**Comment by evgeni** [comment]
cc @ekohl

**Comment by nickmccurdy** [comment]
I've noticed this is also an issue when the same major version tag has an update (for example v2 to v2.0.1)
