### ISSUE TITLE
Check for updates fails on a Maven project (404 returned on a GET artifact URL)

### ISSUE THREAD

**Issue by rknj** [dependabot/dependabot-core#2305]
**Package manage/ecosystem**
Maven
**Manifest contents prior to update**
It's a private repository but what I can tell is that in the POM, I've a parent artifact defined (and it's the one that cannot be retrieved) and repositories where to find all our artifacts (public and private ones). Then I have subprojects with their own POM (but the check did not go that far).
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
I've set up a basic dependabot configuration:
```
version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```
and when I check for updates I get the following:
```
Dependabot can't evaluate your Java dependency files.
As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.
The error Dependabot encountered was:

Property not found: dependency.plugin.version

```
**Images of the diff or a link to the PR, issue or logs**
In the update logs, besides other actions that returned 200, I have:
```
  proxy | 2020/07/03 10:05:39 GET https://devtools.jahia.com:443/nexus/content/groups/public/org/jahia/jahia-parent/8.0.1.0-SNAPSHOT/jahia-parent-8.0.1.0-SNAPSHOT.pom
  proxy | 2020/07/03 10:05:39 404 https://devtools.jahia.com:443/nexus/content/groups/public/org/jahia/jahia-parent/8.0.1.0-SNAPSHOT/jahia-parent-8.0.1.0-SNAPSHOT.pom
```
https://devtools.jahia.com/nexus/content/groups/public/org/jahia/jahia-parent/8.0.1.0-SNAPSHOT/ is accessible but indeed there is no artifacts with SNAPSHOT in the name in it, only artifacts with time identifiers.
Is it a bug or am I missing something in the configuration ?
Because I do not see the link between dependency.plugin.version and the 404 in the log.

**Comment by rknj** [comment]
Anybody to help me with this ?

**Comment by jakecoffman** [comment]
Sorry for the delay! I think this PR should have fixed the issue: https://github.com/dependabot/dependabot-core/pull/5924

Dependabot didn't know how to look up snapshot URLs, but now it does.

**Comment by deivid-rodriguez** [comment]
Nice!

@rknj I know this issue is old and you may no longer be interested, but if you are still having issues here feel free to reopen this ticket!
