### ISSUE TITLE
github.com/kataras/iris dependency breaks dependabot

### ISSUE THREAD

**Issue by Al2Klimov** [dependabot/dependabot-core#2308]
**Package manage/ecosystem**
Go
**Manifest contents prior to update**
https://github.com/masif-upgrader/agent/blob/7e12b0528be1231c9718fb22da8a4840868f2c36/go.mod
**Updated dependency**
https://github.com/masif-upgrader/agent/issues/7
**What you expected to see, versus what you actually saw**
Nothing at all (as everything is up to date), versus the issue above.
**Images of the diff or a link to the PR, issue or logs**
See above.

**Comment by Al2Klimov** [comment]
CC @kataras

**Comment by kataras** [comment]
I am going to push a PR to masif-upgrader repository.

**Comment by lseppala** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Has this issue happened for you again in the same way?

**Comment by jeffwidman** [comment]
Closing, as no response received from the OP.
