### ISSUE TITLE
NuGet package updates should not include or consider build metadata

### ISSUE THREAD

**Issue by clairernovotny** [dependabot/dependabot-core#2310]
Dependabot is including SemVer build metadata in its updates for NuGet packages, but in NuGet, the + and anything afterwards (the build metadata) is not considered part of the version. Packages with different build metadata are considered identical, and the build metadata is never inserted into the project files.

**Package manage/ecosystem**
NuGet

**Manifest contents prior to update**
5.7.0-rtm.6686

**Updated dependency**
5.7.0-rtm.6708+b271881af1add5b777c665e044c4b90d10601ae2

**What you expected to see, versus what you actually saw**
5.7.0-rtm.6708

The comparison must exclude the + and everything after. NuGet does not consider build metadata as part of the package version for any purpose.

**Images of the diff or a link to the PR, issue or logs**

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/1069

**Comment by jakecoffman** [comment]
Build info is now being removed from version identifiers. Thanks for reporting this and for your patience!
