### ISSUE TITLE
Support private npm packages in Github-native Dependabot

### ISSUE THREAD

**Issue by markcellus** [dependabot/dependabot-core#2311]
When converting our project from dependabot preview to Github-native Dependabot, we get this message:

> Your account is using config variables to access private registries. GitHub-native Dependabot will support private registries before Dependabot Preview is shut down. For now, we recommend leaving Dependabot Preview active.

Sounds like the plan is to eventually support private registries in Github-native Dependabot, but I'm just filing this issue to keep track of this feature since its the only thing preventing my team from using it.

Can you all update this ticket when the feature is implemented? Thanks!

**Comment by asciimike** [comment]
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta, so this should be supported!

**Comment by markcellus** [comment]
Thanks @asciimike but it doesn't seem to work with registry URLs that require paths, like artifactory. I opened https://github.com/dependabot/dependabot-core/issues/3281. We would need this fixed before we can start using it.
