### ISSUE TITLE
[java, maven] Dependabot used wrong third party repository instead official (maven-compiler-plugin)

### ISSUE THREAD

**Issue by JayDi85** [dependabot/dependabot-core#2313]
Problem PR:
* https://github.com/magefree/mage/pull/6794

Problem dependency:
* `maven-compiler-plugin`

Use case:
* Maven's plugin: `maven-compiler-plugin`
* Project's version: 3.5.1
* [Latest official](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin) version: 3.8.1 (May, 2019)
* [Latest unofficial](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin?repo=jboss-ea) jboss's version: 3.8.1-jboss-1 (Oct, 2019 -- even more it's early access version, jbossEA).
* Problem: dependabot used unofficial source with 0 usages instead same version from official source with 19 usages.

**Comment by jeffwidman** [comment]
@blue2cat debugged this and noticed that the `jboss` repository is explicitly specified:
https://github.com/magefree/mage/blob/69c28ab8c860317432d06022d1981b62a06961c4/pom.xml#L69-L86

So Dependabot will intentionally prefer that as the source of packages before checking elsewhere. So this is working as expected.
