### ISSUE TITLE
Can dependabot update yarn resolutions?

### ISSUE THREAD

**Issue by GiriB** [dependabot/dependabot-core#2318]
Can dependabot update yarn resolution field in package.json? I see in our PRs it updates the lockfile but the not resolutions field.

**Comment by tuukka** [comment]
I would like to know this as well.

**Comment by ofhouse** [comment]
For everyone who's wondering: Dependabot **cannot** increase the version in the `resolutions` field.
However it respects the value in the `resolutions` field when it bumps a dependency.

**Comment by lseppala** [comment]
Based on this test, resolutions in a `package.json` file _should_ be updated, at least for the simple case of a non-nested, exact version resolution. 

https://github.com/dependabot/dependabot-core/blob/e899d765037ee6620f6327c8b17516e551896355/npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb#L3157-L3181

Could you share a bit more about the examples where dependencies are not updated in the resolution field?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.

**Comment by Dreamsorcerer** [comment]
> Based on this test, resolutions in a `package.json` file _should_ be updated, at least for the simple case of a non-nested, exact version resolution.

This doesn't seem to work. This a grouped update which is supposed to update everything in resolutions:
https://github.com/aio-libs/aiohttp-admin/pull/863/files

The group is defined as:
https://github.com/aio-libs/aiohttp-admin/blob/baba5a7adf79fdb8957231cd84dd53331b1f5845/.github/dependabot.yml#L12-L17

Nothing in resolutions has been touched...
