### ISSUE TITLE
Gradle dependencies in pluginManagement plugins section not updated

### ISSUE THREAD

**Issue by mattlong-finocomp** [dependabot/dependabot-core#2319]
**Package manage/ecosystem**
java gradle

**What you expected to see, versus what you actually saw**
In my settings.gradle i have a block similar to the following:
```
pluginManagement {
    plugins {
        id 'com.gradle.build-scan' version "3.0"
        id 'com.jfrog.artifactory' version "4.10.0"
    }
}
```

Which allows me to use consistent plugin versions in a multi-project build without having to respecify the plugin version in every subproject when i apply the plugins. See https://docs.gradle.org/5.6/release-notes.html#central-management-of-plugin-versions-with-settings-script
Dependabot doesn't seem to detect these as updateable dependencies.

I'm not sure if this is because the dependencies are in settings.gradle or in the pluginManagement block or a combination of the two.

According to the original announcement of Gradle support, dependabot supports parsing settings.gradle https://dependabot.com/blog/gradle-support/

**Comment by eirnym** [comment]
As far as I know, it's possible to list all your plugins in your `rootProject` build gradle file without applying them. At least I do this way. 
Later Gradle rejects all plugin mentions with a version inside sub-projects.

Could you try this workaround? (I don't know how it actually is a replacement

**Comment by mattlong-finocomp** [comment]
My employer has migrated away from dependabot so I'm not able to check the workaround sorry.
