### ISSUE TITLE
Ruby version was bumped 2.6.6

### ISSUE THREAD

**Issue by sizuhiko** [dependabot/dependabot-core#2321]
**Package manage/ecosystem**

docker image `dependabot/dependabot-core:0.118.7`

**What you expected to see, versus what you actually saw**

I use [dependabot-script](https://github.com/dependabot/dependabot-script) on latest docker image of dependabot-core.
From tag [0.118.7](https://hub.docker.com/layers/dependabot/dependabot-core/0.118.7/images/sha256-fed4b5eed8e6ba179b1d0797cbd0ff2579ba1e6b711383a4829e217b1225aefe?context=explore), happen error followings:
```
Your Ruby version is 2.6.6, but your Gemfile specified 2.6.5
```

Of course, this may be the `dependabot-script` issue, as [dependabot-script requires 2.6.5](https://github.com/dependabot/dependabot-script/blob/main/.ruby-version).

But, dependabot-core expect Ruby version is 2.6.5 on the [Dockerfile](https://github.com/dependabot/dependabot-core/blob/main/Dockerfile#L54).

What exactly is Ruby's version for the dependabot-core?

**Comment by jmaicher** [comment]
Same issue. I guess ruby has been bumped to 2.6.6 in the brightbox ubuntu repository and the 0.118.7 image was build afterwards. I suggest to bump ruby to 2.6.6 in dependabot-script. Should I create a MR?

**Comment by feelepxyz** [comment]
> Same issue. I guess ruby has been bumped to 2.6.6 in the brightbox ubuntu repository and the 0.118.7 image was build afterwards. I suggest to bump ruby to 2.6.6 in dependabot-script. Should I create a PR?

That would be much appreciated!

**Comment by sizuhiko** [comment]
I found  a PR. Thanks everyone.
https://github.com/dependabot/dependabot-script/pull/454

**Comment by JorgenPhi** [comment]
This was resolved for me by pulling and merging in the latest commit: https://github.com/dependabot/dependabot-script/commit/b6a95dbae679a0301059a19be21f6a6dc5104597

**Comment by sizuhiko** [comment]
Works fine ! Thanks.
