### ISSUE TITLE
[Nuget]: package bump leads to broken build because the build pipeline won't see the package yet

### ISSUE THREAD

**Issue by marcwittke** [dependabot/dependabot-core#2330]
### Package manage/ecosystem
Nuget

### The problem
It is not really a bug, but a problem in synchronization of tasks: Quite frequently I see package bumps resulting in a new branch and a respective PR. So far, so good. Our CI pipeline gets triggered and builds the PR but fails like that:

```
##[error]path/to.the.project.csproj(0,0): Error NU1103: Unable to find a stable package Microsoft.Extensions.Primitives with version (>= 3.1.6)
 - Found 49 version(s) in nuget.org [ Nearest version: 5.0.0-preview.1.20120.4 ]
```

It seems that dependabot "saw" a new package, that was not replicated yet to all downstream nuget servers, at least not to the one my CI agent is routed to. I understand that's not dependabot's fault, but what would be the correct countermeasure to avoid false negatives in my CI pipeline (that is really PITA when it comes to fixing it manually...)

**Comment by jeffwidman** [comment]
A few options:
1. You could change the frequency of Dependabot runs to be less frequent, thus reducing the chance of collisions.
2. You could vote for https://github.com/dependabot/dependabot-core/issues/3651 such that Dependabot delays creating the PR til the day after the package is updated.
3. You could wire up your CI system to do a delayed retry after a certain amount of time... or even if the delay is typically just a few minutes you could have your CI first do a sleep for 10 mins before kicking off.

Closing as fundamentally this is a CI delay / retry issue and not much we can do here.
