### ISSUE TITLE
Remove "feedback" repo from pinned repositories

### ISSUE THREAD

**Issue by HonkingGoose** [dependabot/dependabot-core#2340]
**Current behavior:**

There is currently a archived repository (_feedback_) pinned to the Dependabot profile main page at https://github.com/dependabot

**Expected behavior:**
Only the _dependabot_core_ repo is pinned.

**Steps to reproduce:**

1. Go to the Dependabot profile page at https://github.com/dependabot
2. Check the section "Pinned repositories"
3. _feedback_ repository is pinned.

**Proposed fix:** 
Remove (unpin) the_feedback_ repo from the list of pinned repositories for the Dependabot account.

**Comment by feelepxyz** [comment]
Thanks for reporting @HonkingGoose 👍  done

**Comment by HonkingGoose** [comment]
Wow that's quick! Thank you for fixing it. :smile:
