### ISSUE TITLE
*.csproj files not updating

### ISSUE THREAD

**Issue by VPKSoft** [dependabot/dependabot-core#2365]
**Package manager/ecosystem**
NuGet

**Manifest contents prior to update**
Only the *packages.config* file was updated in a multi-project visual studio solution but not the actual project files.

**Updated dependency**
Any.

**What you expected to see, versus what you actually saw**
The **.csproj* file *Reference* tag(s) should also be updated with the *packages.config* file(s).

**Images of the diff or a link to the PR, issue or logs**
Only the package.config files were updated. The **.csproj* files were left untouched.
After a update via Visual Studio for the project, the **.csproj* file is also changed:
![image](https://user-images.githubusercontent.com/40712699/88431559-49680900-ce03-11ea-8fcf-cfd671bfd2e9.png)
Dependabot changes only the *package.config* files and leaves the project files as they were:
![image](https://user-images.githubusercontent.com/40712699/88431949-fb073a00-ce03-11ea-8495-9791eb18d98a.png)

CI runs fails, but as the garbage keeps collecting on my on computer the solution compiles fine as the previous packages do exist, See the [PR](https://github.com/VPKSoft/Langlib/pull/86/files). Might be that I have something configured wrong? This is a old .NET solution, not NET Core targetting .NET Framework 4.6.2:
![image](https://user-images.githubusercontent.com/40712699/88432377-c47def00-ce04-11ea-8e92-c320f0819ab9.png)

**Comment by ahwm** [comment]
#1422 has some discussion in this area.
