### ISSUE TITLE
Dependabot-generated changelog is not readable without line breaks

### ISSUE THREAD

**Issue by AlekSi** [dependabot/dependabot-core#2367]
**Package manager/ecosystem**

Go modules.

**Updated dependency**

https://github.com/golangci/golangci-lint/releases/tag/v1.29.0

**What you expected to see, versus what you actually saw**

Dependabot-generated changelog for golangci-lint is not readable without line breaks.

![image](https://user-images.githubusercontent.com/11512/88475676-d2ce2700-cf3a-11ea-83c3-ec593df46b66.png)

**Comment by SVilgelm** [comment]
looks like all projects, what uses the `goreleaser` tool, have same issue

**Comment by lseppala** [comment]
Confirmed that this is still an issue:
 
![image](https://user-images.githubusercontent.com/5587177/144941332-fc26b519-4654-4664-a309-fbab0a3d88b0.png)

**Comment by jeffwidman** [comment]
Actually, poked around and found https://github.com/dependabot/dependabot-core/issues/2367 which shows that the changelog is already correctly displayed, so this was fixed at some point in the past. My guess is we now handle bullet points correctly.
