### ISSUE TITLE
The email address of commit author is a GitHub-provided noreply email address

### ISSUE THREAD

**Issue by ylemkimon** [dependabot/dependabot-core#2369]
> Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

The email address of Dependabot commit author is [a GitHub-provided `noreply` email address](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address), which makes hard to distinguish and is different from:

> Signed-off-by: dependabot[bot] \<support@github.com\>

Is this intended?

**Comment by jurre** [comment]
> Is this intended?

Yes, bots on GitHub always use the anonymized email address for commits.
