### ISSUE TITLE
[Feature request] Automatically upgrade dependencies, not only version number

### ISSUE THREAD

**Issue by Kristinita** [dependabot/dependabot-core#237]
### 1. Request

It would be nice, if would be possible upgrade dependencies, not only version numbers in requirements file.

For example, it would be nice add an option, that bot will run command after each version changing in requirements file.

### 2. Steps to reproduce

I develop plugins for Sublime Text, written on Python. By technical reasons I need add dependencies to my repository.

In my [**repository for testing**](https://github.com/Kristinita/SashaAnotherPyup) I add outdated version of [**PyPI gsearch**](https://pypi.python.org/pypi/gsearch) module to `requirements.txt` file. I use command:

    pip install -r requirements.txt -t . --upgrade

### 3. Justification

Automatically dependencies upgrading may save developers time.

I test Dependabot on my test repository. Dependabot only [**change dependency version**](https://github.com/Kristinita/SashaAnotherPyup/pull/2) in `requirements.txt` file, but not upgrade my gsearch dependency, that I include to my repository.

I need upgrade my dependency manually; after merging I need run command again:

    pip install -r requirements.txt -t . --upgrade

It would be nice, if Dependabot will run this command automatically after each version change in `requirements.txt` file.

Thanks.

**Comment by greysteil** [comment]
Thanks for the feedback @Kristinita. Would you mind moving this over to https://github.com/dependabot/feedback and making the title "Support vendoring for Python"?

It's a totally legit request, but might be tricky for us given the way we currently do Python updates.
