### ISSUE TITLE
Support Python 3.7.8

### ISSUE THREAD

**Issue by alexpdp7** [dependabot/dependabot-core#2371]
From:

https://github.com/alexpdp7/caw/issues/17

> Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000055efb628ede8 @requirements=[[">=", #<Dependabot::Python::Version 3.6>], ["<", #<Dependabot::Python::Version 3.8>]]>], [#<Dependabot::Python::Requirement:0x000055efb628d7e0 @requirements=[["=", #<Dependabot::Python::Version 3.7.8>]]>]]'.
> 
> Currently, the following Python versions are supported in Dependabot: 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.7, 3.7.6, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, 2.7.18, 2.7.17, 2.7.16, 2.7.15, 2.7.14, 2.7.13.

3.7.8 was released recently.

**Comment by feelepxyz** [comment]
Thanks for reporting, will deploy this tomorrow 👍

**Comment by alexpdp7** [comment]
Hi,

This was reverted:

https://github.com/dependabot/dependabot-core/commit/1bd840b76905bf48d72a3f652415c05baf8845c1

and

https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/python_versions.rb

doesn't include 3.7.8 any more.

Cheers,

Álex

**Comment by alexpdp7** [comment]
Hmmm, opening a new ticket
