### ISSUE TITLE
Cancel CI if PR is being rebased

### ISSUE THREAD

**Issue by ylemkimon** [dependabot/dependabot-core#2388]
Most CIs have an API to cancel the build. It'd be nice for Dependabot to have an option to cancel CI run/builds if PR is being rebased.

https://developer.github.com/v3/actions/workflow-runs/#cancel-a-workflow-run
https://circleci.com/docs/api/#cancel-a-build
https://developer.travis-ci.com/resource/build#cancel

**Comment by mwaddell** [comment]
For github, you can accomplish this using [concurrency groups](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

**Comment by ylemkimon** [comment]
I don't remember why I opened this issue, so closing.
