### ISSUE TITLE
Question: How are deployments of Dependabot triggered?

### ISSUE THREAD

**Issue by localheinz** [dependabot/dependabot-core#2404]
Out of curiosity, are deployments triggered 

- on merge to `main` 
- on push of a tag
- manually

?

Wondering because I have not seen #2360 in the wild yet!

🤓

**Comment by jurre** [comment]
We have to trigger these deploys manually, but I will try to do that today 👍

**Comment by localheinz** [comment]
@jurre 

Thank you for clarifying!

🤓
