### ISSUE TITLE
Q: How to raise issues once an error is occurred during dependencies update ?

### ISSUE THREAD

**Issue by omartrigui** [dependabot/dependabot-core#2424]
**Question**

Is there a way to make Dependabot raise issues once an error is occurred during dependencies update ? 
PS: I am using `dependabot-omnibus` gem

**More context:**
- Sample issue raised by dependabot https://github.com/pypa/warehouse/issues/5244
- Failure reasons: Connectivity issue with artifacts server, incorrect credentials, updater version mismatch etc ...

**Comment by feelepxyz** [comment]
@omartrigui we haven't built this into core (we're also deprecating using issue from the github-native version) so you'll have to write your own logic to rescue these errors and create issues using the GH API.

**Comment by omartrigui** [comment]
@feelepxyz thanks !
