### ISSUE TITLE
yarn.lock as generated by Dependabot is not optimal

### ISSUE THREAD

**Issue by StephanBijzitter** [dependabot/dependabot-core#243]
<img width="1297" alt="screen shot 2018-01-22 at 13 01 06" src="https://user-images.githubusercontent.com/1649903/35219845-762ec59c-ff74-11e7-87ed-e1447211d381.png">
This is part of a pull request created by Dependabot, and while this installs perfectly fine, I would expect `doctrine@^2.0.0, doctrine@^2.0.2:` to change into `doctrine@^2.0.0, doctrine@^2.1.0:`, so that only 2.1.0 is installed, instead of the current 2.0.2 and 2.1.0

doctrine is a dependency of eslint, that updated from 4.15.0 to 4.16.0

**Comment by greysteil** [comment]
Thanks for the feedback @StephanBijzitter.

I'm not sure there's an easy way to fix this on Dependabot's side - we lean heavily on Yarn's internals for lockfile generation, and if Yarn doesn't behave perfectly (as it hasn't above) then there's not a lot we can do.

There's an issue open over at the [yarn repo](https://github.com/yarnpkg/yarn/issues/3778), but it hasn't has as much love as I'd like. There's also [`yarn-tools`](https://bitbucket.org/atlassian/yarn-tools) that attempts to fix this, but I'm not 100% sure I trust it...

**Comment by StephanBijzitter** [comment]
Alright, that issue indeed seems to be exactly what I saw in one of our(/dependabot's) PRs. Hopefully they'll be able to resolve it soon. As for this issue, I'll leave it to you to close it if wanted, I've got my answer :-)

**Comment by greysteil** [comment]
👍 . I'm going to close but add a personal TODO to look into creating a `yarn-tools`-like PR into Yarn. The core team there are brilliant, but they've got a lot on their plate!

**Comment by scinos** [comment]
@greysteil happy to help with that PR

**Comment by greysteil** [comment]
FYI, this made it into Dependabot a few weeks ago - we now de-dup the `yarn.lock` for the dependency we're updating, based on some custom logic (inspired by `yarn-tools`). 🎉
