### ISSUE TITLE
No working way to only get security updates like the GitHub Pages bump

### ISSUE THREAD

**Issue by Blaisorblade** [dependabot/dependabot-core#2437]
**Package manager/ecosystem**: ruby:bundler
**Images of the diff or a link to the PR, issue or logs**: https://github.com/Blaisorblade/dot-iris/pull/315
**Updated dependency**: kramdown 1.17.0 -> 2.3.0, github-pages 206 -> 207.
**What you expected to see, versus what you actually saw**

I expect an option that allows such security updates and necessary dependency bumps, but not unneeded bumps like the one that caused #2436. Instead, when I enabled the "Only security updates" filter, I got an advisory about kramdown without a PR, because this PR had to upgrade github-pages, which doesn't count as a security update.

To fix that, I enabled instead as filter "Only top-level dependencies (and security patches for subdependencies)", which also tried to update tz-info (https://github.com/Blaisorblade/dot-iris/pull/314).

**Comment by jeffwidman** [comment]
We've pushed a lot of bugfixes since you filed this issue... is it still a valid / reproducible issue?

**Comment by Blaisorblade** [comment]
I’m trying the new setting, will file a new issue if there are problems.
