### ISSUE TITLE
Improve overall display of PRs

### ISSUE THREAD

**Issue by Andre601** [dependabot/dependabot-core#2443]
[Javalin]: https://github.com/tipsy/javalin
[JDA]: https://github.com/DV8FromTheWorld/JDA
[action]: https://github.com/peaceiris/actions-label-commenter
[Lombock]: https://github.com/rzwitserloot/lombok

## The issues
There are several issues with the look and feel of Dependabot's PRs which I want to list here in order of importance for me.

### 1) Inconsistent Commit, Releases and Changelog info
Dependabot's way of retrieving a dependency's update notes is... weird to put it simply.
It seems to be almost random on how the bot gets the update notes of a dependency if it even gets those, to begin with.

I'll list some dependencies I use to showcase how Dependabot does (not) show their respective changelogs, update releases, etc.:

- [Javalin]:
  - [ ] Lists release notes
  - [ ] Lists Changelog
  - [x] Lists commits since last update
- [JDA]:
  - [ ] Lists release notes
  - [ ] Lists Changelog
  - [ ] Lists commits since last update
- [peaceiris/actions-label-commenter][action]:
  - [x] Lists release notes
  - [x] Lists Changelog
  - [x] Lists commits since last update
- [Lombock]:
  - [ ] Lists release notes
  - [x] Lists Changelog
  - [x] Lists commits since last update

Something I also noticed is, that some dependencies aren't linked to their GitHub repository despite having one.
A prime example of this would be JDA, which does have an open-source repo, that is also linked in their release repository (bintray), yet unlike the other examples does it not have a valid link to the repository in the PR.

## 2) Inconsistend/Pointless Compatibility badge
The bot always has a compatibility badge to show how compatible the update is compared to previous ones (Will break things).

For 99% of my dependencies however is the button useless as it always shows "unknown".
This is weird, considering some of my dependencies having some CI systems to test things such as PRs and/or use CI servers for sharing test builds and such.

This is yet another case of Dependabot being really inconsistent about how it retrieves those infos.
While the docs do state that it generates the number based on passed and failed CI test runs does it give 0 information where it checks for those, similar to there being no info about how Dependabot gets the release info.

## Solutions
While I'm not sure how difficult improving or fixing those issues are, would I like to suggest possible solutions/ideas to consider.

### Improve retrieval of release info
From what I found so far can I safely assume that a majority of these issues happens because the dependency in question doesn't use a mainstream repository to share their releases.
In my case and with Java could this be the case as the releases that have *some* info are either hosted on MavenCentral or directly on GitHub (GitHub Actions). Meanwhile other dependencies such as JDA use other repos like bintray (they close soon.) or have their own setups using their own CI service or similar.

Dependabot should adabt its way of finding release information, similar to how it checks for different updates: By going through the different repository URLs, check for if there is something and then rertrieve the info.

A large majority of dependencies I use and know often have the option to link their source repository in the repo-site they use to share updates with and often use that option, so Dependabot could try getting those infos and take the release notes and/or changelog through that. I hope you get what I mean.

### Remove the compatibility score icon
This badge is completely redundant. If an update would be breaking, then Dependabot could also just append a note like
```markdown
**This update has a compatibility score of <number> and could therefore be a breaking change!**
```

The button as of now barely serves any real benefit and is for a large majority of dependency broken.
Even dependencies that previously had a visible compatibility score now show unknown as if they aren't the same anymore.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply and thanks for the feedback.

I definitely agree there's room for improvement here. However, with the wall of text in a single issue, it's difficult to keep it actionable.

For package metadata fetching problems, can you file bugs as you see them? Each one may have different root causes, so it's easier to track them separately then together. Many times, the packages themselves don't populate their metadata fields on their registries in the standard format, so sometimes having those packages fill out those fields will magically fix it. Sometimes it's on our end parsing those fields... it just depends.

For compatibility score upgrades, we've shipped several improvements the past few months on calculating the score, so it should be grey far less often.

I'm going to close, as this ticket is now three years old, so its not really worth investigating whether the metadata issues for the packages you listed are fixed... but if you do see them crop up again, please file issues. 

Thanks!
