### ISSUE TITLE
Can you add to the documentation how Dependabot decides on the superseded security-updates (PRs)? 

### ISSUE THREAD

**Issue by mahmoud-alfadel** [dependabot/dependabot-core#2449]
A vast number of the closed security-PRs are due to that Dependabot closes the original security-PR and creates a new one with a newer version of the affected dependencies. However, given that Dependabot sends a pull request to update the affected dependency manifest with the **closest non-vulnerable version** [1], why would it send a newer pull request to update the dependency? 

@greysteil  Could you please clarify this point here [1]:
[1] https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by mahmoud-alfadel** [comment]
@greysteil :-))

**Comment by greysteil** [comment]
I can't comment on the GitHub native version of Dependabot as I didn't write it - @infin8x or @feelepxyz may be able to provide more details. The strategy I'd expect us to be aiming for with security updates is only to supersede them if a newer version fixes additional security vulnerabilities.

**Comment by feelepxyz** [comment]
> A vast number of the closed security-PRs are due to that Dependabot closes the original security-PR and creates a new one with a newer version of the affected dependencies. However, given that Dependabot sends a pull request to update the affected dependency manifest with the **closest non-vulnerable version** [1], why would it send a newer pull request to update the dependency?

Yeah Dependabot should be targeting the lowest non-vulnerable version and only update it if there's a new vulnerability for a later version. Do you have any example public repos where you've spotted this? Can take a look and see if there's anything funky going with this logic.

**Comment by mahmoud-alfadel** [comment]
> > A vast number of the closed security-PRs are due to that Dependabot closes the original security-PR and creates a new one with a newer version of the affected dependencies. However, given that Dependabot sends a pull request to update the affected dependency manifest with the **closest non-vulnerable version** [1], why would it send a newer pull request to update the dependency?
> 
> @mahmoud-alfadel Dependabot should be targeting the lowest non-vulnerable version and only update it if there's a new vulnerability for a later version. Do you have any example public repos where you've spotted this? Can take a look and see if there's anything funky going with this logic.

Thanks, @feelepxyz, for the information. Here is an example of such a case in a public repo:
https://github.com/deadlybyte/react-speedy-reader/pull/146

**Comment by jeffwidman** [comment]
I looked through the chain of PR's that cascade from https://github.com/deadlybyte/react-speedy-reader/pull/146 and in all cases that I saw the next PR that superceded the previous PR had an additional vulnerability that it was fixing. So it's still going to the "lowest version that resolves all known vulnerabilities".
