### ISSUE TITLE
Support Gradle Projects

### ISSUE THREAD

**Issue by MiniDigger** [dependabot/dependabot-core#245]
things to consider here:
* map style notation: compile group: 'com.google.code.guice', name: 'guice', version: '1.0'
* short notation: compile 'commons-lang:commons-lang:2.6'
* different quotation marks (both " and ' are allowed)
* multi module projects

**Comment by greysteil** [comment]
Totally 👍  on adding this. I'm going to be off the grid for the next two weeks, but please don't take that as a lack of enthusiasm!

**Comment by SevastyanDark** [comment]
@greysteil Any news?

**Comment by greysteil** [comment]
Not yet, sorry! I'm going to be pushing on Rust and adding private repo support to Maven today, but will have a look at this immediately after. Would love to support Gradle projects, and will start a template PR in the next couple of days.

**Comment by SevastyanDark** [comment]
Thanks, i'm waiting!

**Comment by greysteil** [comment]
@MiniDigger, OK, I'm going to get started on this this week. Any pointers on docs / a (simple) example repo that I can use as a fixture?

**Comment by MiniDigger** [comment]
I guess you could use this project, it has a bunch of dependencies 
 https://github.com/VoxelGamesLib/dependencies/blob/master/build.gradle
Not sure what docs could help you, this one gives a good overview 
https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html

Gradle is a bit more flexible than maven, so there are countless ways to declare dependencies. For the start I would think supporting the map style (<configuration> group: 'com.google.code.guice', name: 'guice', version: '1.0') and the short (<configuration> 'commons-lang:commons-lang:2.6') notation with both single and double quotation marks in a dependencies block would be enough. Supporting multiple modules should be easy, all that's nessasary is scanning the repo for more build.gradle files (they can be anywhere, but I guess 2 level deep should be enough for most setups)

**Comment by MiniDigger** [comment]
Here is another good example as this highlights that a dependencies block doesn't need to be in the root of the file but can be nested in a buildscript or subprojects or a project('a') block.

https://github.com/MiniDigger/CryptoClicker/blob/master/build.gradle

**Comment by maracuja-juice** [comment]
An example for a gradle file used in an Android project: https://github.com/Samourai-Wallet/samourai-wallet-android/blob/develop/app/build.gradle

**Comment by DanielMartinus** [comment]
As mentioned earlier by @MiniDigger there are many ways to declare your dependencies in a gradle file. If only a file scan is done on a project it would be nice to take **ExtraPropertiesExtensions** into account. These are mainly used to manage dependency versions across different modules.

It would for example look like:

Some other gradle file, f.e.: `dependencies.gradle`
```groovy
ext {
    myLibraryVersion = '1.0.0'
}
```

Module 1 `build.gradle`
```groovy
    implementation "com.example.dependency:$myLibraryVersion"
```

Module 2 `build.gradle`
```groovy
    implementation "com.example.dependency:$myLibraryVersion"
```

Another thing to be aware of is that from Gradle version 3 `compile` is changed to `implementation` and `api` and a bunch of other configurations were added. But I can imagine this will be ignored when checking the dependency versions.

**Comment by MiniDigger** [comment]
I have no idea how the parsing works in the Backend, but looking at all the edge cases, maybe it's easier to just clone the repo and run gradle together with a special task to check dependencies? 
This plugin creates a json file with all versions of all dependencies and checks if there are newer versions available https://github.com/ben-manes/gradle-versions-plugin
Just something to consider, as this would automatically support all possible ways to define dependencies as it hooks in Gradles API.

**Comment by greysteil** [comment]
👍 - I've started the work over at https://github.com/dependabot/dependabot-core/pull/464.

**Comment by greysteil** [comment]
Initial PRs: https://github.com/greysteil/dependencies/pulls.

Still a long way to go on this, but it kinda works already!

**Comment by greysteil** [comment]
Hey team, I've just released this! If you do a hard refresh on your Dependabot dashboards you should be able to add Gradle projects (by selecting `Java - Gradle` as the language).

A few known deficiencies:
1. It can't handle Kotlin files yet
2. It can't do multi-module support yet. It will only operate on the `build.gradle` file in the repo you specify
3. It can't handle custom repositories yet (it will look for everything in the central repository
4. It doesn't do any resolution, just tries to update you to the latest (non-prerelease) version

As a result of the above I've put an `alpha` badge on current support. I'm planning to handle 2. and 3. in the next few days, and then take it from there, but the more projects you try it on the quicker I'll be able to iron out the bugs.

**Comment by eriwen** [comment]
💯 🌈 🌟

**Comment by SevastyanDark** [comment]
@greysteil You can temponarly scan repo for `*.gradle` files and index them.

**Comment by mueller-ma** [comment]
@greysteil Looks good so far, but I have some suggestions/bugs:

1. Can you have a look at https://github.com/openhab/openhab-android/pull/886 ?
When I try the update locally I get the following error:
````
Could not find com.google.firebase:firebase-core:15.0.1.
Searched in the following locations:
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://jcenter.bintray.com/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://jcenter.bintray.com/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://jcenter.bintray.com/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://jcenter.bintray.com/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://repo.maven.apache.org/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://repo.maven.apache.org/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://jitpack.io/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://jitpack.io/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
    https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.pom
    https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/15.0.1/firebase-core-15.0.1.jar
Required by:
    project :mobile

````

Google is deprecating its GCM in favor of FCM (Firebase cloud messaging). The PR is about updating the Google Maps package, but it seems to be related to this deprecation.


2. When using https://github.com/signalapp/gradle-witness for verification of dependencies, @dependabot-bot should update the corresponding hash sum. However gradle-witness doesn't support `implementation` for now.

3. The android support library packages should be updated in one PR, not split in multiple PRs.
````groovy
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.android.support:support-v4:27.1.1"
    implementation "com.android.support:recyclerview-v7:27.1.1"
    implementation "com.android.support:design:27.1.1"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
````

4. Here is an example by Google how to use variables to have the same version of libs in the whole project.
https://github.com/googlecodelabs/android-testing/blob/master/build.gradle#L21
https://github.com/googlecodelabs/android-testing/blob/master/app/build.gradle#L54
Android projects always have these two files and they can have more, if they contain more modules.

**Comment by greysteil** [comment]
Thanks for the feedback @mueller-ma! Gradle support is super alpha at the moment, but I should have some time over the next couple of weeks to start improving it. I'll definitely be referring to the above when I do!

**Comment by mueller-ma** [comment]
@greysteil Can you have a look at https://github.com/openhab/openhab-android/pull/958?
The build fails, because the bumped dependency cannot be found on a remote server:
````
A problem occurred configuring project ':mobile'.
> Could not resolve all artifacts for configuration ':mobile:classpath'.
   > Could not find com.google.gms:google-services:4.0.2.
     Searched in the following locations:
         https://maven.fabric.io/public/com/google/gms/google-services/4.0.2/google-services-4.0.2.pom
         https://maven.fabric.io/public/com/google/gms/google-services/4.0.2/google-services-4.0.2.jar
         https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.pom
         https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.jar
     Required by:
         project :mobile
````

How does @dependabot-bot know that there is a new version?

**Comment by audkar** [comment]
> It can't handle custom repositories yet (it will look for everything in the central repository 
If this is still true, then this is reason why it fails :)

google services artifact is in custom repository `http://maven.google.com`

**Comment by mueller-ma** [comment]
@audkar Thanks for the tip, but it didn't help:
````
A problem occurred configuring project ':mobile'.
> Could not resolve all artifacts for configuration ':mobile:classpath'.
   > Could not find com.google.gms:google-services:4.0.2.
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.pom
         https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.jar
         https://maven.fabric.io/public/com/google/gms/google-services/4.0.2/google-services-4.0.2.pom
         https://maven.fabric.io/public/com/google/gms/google-services/4.0.2/google-services-4.0.2.jar
         https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.pom
         https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.0.2/google-services-4.0.2.jar
     Required by:
         project :mobile
````

**Comment by greysteil** [comment]
Let me take a look into this one - I'll get back to you.

**Comment by mueller-ma** [comment]
@greysteil When bumping an annotation processor two lines need to be changed: https://github.com/openhab/openhab-android/pull/964/files#diff-267b4136e002edb2e31e096623801166L129 and the line below.

**Comment by mueller-ma** [comment]
@greysteil @dependabot-bot must not treat checksums inside the block `dependencyVerification {}` as version numbers and must not bump them.  `dependencyVerification {}` is created by https://github.com/signalapp/gradle-witness.
https://github.com/openhab/openhab-android/pull/1003

**Comment by mueller-ma** [comment]
Thanks. Any update on [this](https://github.com/dependabot/dependabot-core/issues/245#issuecomment-407114657)?

**Comment by greysteil** [comment]
Gotta confess I accidentally let that one drop. I'm doing a push on Gradle today and tomorrow, though, and will try to get that fixed, too.

**Comment by greysteil** [comment]
@mueller-ma - OK, the SHA issue is fixed in [this commit](https://github.com/dependabot/dependabot-core/commit/7819b483fbe3e2742c8403d603f2a7d24c346e2d) and the version issue is fixed [here](https://github.com/dependabot/dependabot-core/commit/195f26e520b26083ab3ecd464b5cb9059171d945). Thanks for pointing both out!

Deploying now - I'll re-run Dependabot on your repos once done and it should close any invalid PRs.

**Comment by matfax** [comment]
Is anyone working on Kotlin DSL yet?

**Comment by leogiertz** [comment]
@greysteil Are you planning on supporting dependency locking?

https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by greysteil** [comment]
Yep! Really keen to, but it's going to be quite a big project for us and I don't know exactly when. It's on my list for before we can take Gradle out of beta, though.

**Comment by Anoukh** [comment]
Hi, does the latest version support https://github.com/dependabot/dependabot-core/issues/245#issuecomment-385613964 ?

**Comment by greysteil** [comment]
Yes - should do. I'm going to close this issue now and we can deal with individual Gradle requests separately. 🎉
