### ISSUE TITLE
Dependabot suggests wrong versions of kotlinx.coroutines in Gradle project

### ISSUE THREAD

**Issue by vbuberen** [dependabot/dependabot-core#2460]
**Package manager/ecosystem**
Java Gradle

**Manifest contents prior to update**
https://github.com/ChuckerTeam/chucker/blob/develop/build.gradle

**Updated dependency**
Suggested update:
from `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.8`
to `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt`

**What you expected to see, versus what you actually saw**
I expect to see Dependabot suggesting regular stable Coroutines versions as they appear in [the official repo](https://github.com/Kotlin/kotlinx.coroutines#gradle):
`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9'`, because this is what is expected to be used in Android projects normally.

Instead I see some strange dependencies ending with `-native-mt`. 

Some time ago I had the same issue, where Dependabot suggested version ending with `-mpp-native-dev-11`. 

Probably, Dependabot looks at some wrong place to pick versions.

**Images of the diff or a link to the PR, issue or logs**

Old issue from some time ago with previous Coroutines update:
<img width="285" alt="Screenshot 2020-08-19 at 16 44 08" src="https://user-images.githubusercontent.com/13467769/90642565-3a764a00-e23b-11ea-9c7d-04017b77fd16.png">
Corresponding PR:
https://github.com/ChuckerTeam/chucker/pull/379

Fresh issue:
<img width="285" alt="Screenshot 2020-08-19 at 16 43 57" src="https://user-images.githubusercontent.com/13467769/90642640-524dce00-e23b-11ea-8860-dba60ecd9f0a.png">
Corresponding PR:
https://github.com/ChuckerTeam/chucker/pull/426

After some time after opening previous commit Dependabot decided to open another PR with the same version update suggestion:
https://github.com/ChuckerTeam/chucker/pull/429

**Comment by reconman** [comment]
Same issue in https://github.com/MathewSachin/Fate-Grand-Automata/pull/575

**Comment by ashughes** [comment]
FYI, there's a discussion about this in #2547 as well.

**Comment by jeffwidman** [comment]
I _think_ this was fixed by https://github.com/dependabot/dependabot-core/pull/4077, but I'm not 100% sure (it's late and I've been going through a lot of old issues this evening so I'm afraid my brain is a little fuzzy).

I'm going to close, but if for some reason I'm wrong, please comment and I'll re-open.
