### ISSUE TITLE
Azure DevOps: target multiple package manifests within a single repo

### ISSUE THREAD

**Issue by smholvoet** [dependabot/dependabot-core#2463]
I've been able to incorporate dependabot in my Azure DevOps org by making use of the Docker image and the dependabot script. I'm using the code below in a build pipeline which results in dependabot working its magic. 

```
docker run -v "$(pwd):/home/dependabot/dependabot-script" \
               -w /home/dependabot/dependabot-script \
               -e AZURE_ACCESS_TOKEN='<PAT>' \
               -e PACKAGE_MANAGER='nuget' \
               -e PROJECT_PATH='<org>/<project>/_git/<repo>' \
               -e DIRECTORY_PATH='<folder>' \
               dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb
```

This works great 👍  and I'm completely sold on this tool, but I'm wondering how I would be able to target multiple folders (meaning multiple package manifests). My repo for example has 10 different folders (projects), each containing a `packages.config` file.

I'm well aware of the way the "regular" dependabot works in GitHub for example, using the [config file](https://dependabot.com/docs/config-file/#available-configuration-options) where you can specify as many projects and languages as you like, as well as other various options. 

How would I tackle this issue, making use of the dependabot script? Looking at other issues, it seems like there is no support for `config.yml` files. Is there an alternative way to achieve this without running the same script multiple times, manually specifying a different `DIRECTORY_PATH` for each folder (project) within my repo?

**Comment by jurre** [comment]
> Is there an alternative way to achieve this without running the same script multiple times, manually specifying a different DIRECTORY_PATH for each folder (project) within my repo?

No, it's essentially what we do for the hosted version of Dependabot as well, we run it multiple times for each config. I don't think there's another way
