### ISSUE TITLE
Q: Dependabot does not respect semver version ranges specified in package-lock.json

### ISSUE THREAD

**Issue by omartrigui** [dependabot/dependabot-core#2467]
**Package manager/ecosystem**
npm_and_yarn

**Manifest contents prior to update**

package.json
```json
{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular": "1.5.7"
  }
}
```
package-lock.json
```json
{
  "name": "semver",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "angular": {
      "version": "1.5.7",
      "resolved": "https://registry.npmjs.org/angular/-/angular-1.5.7.tgz",
      "integrity": "sha1-Ts79DHE0tydXujtBu6Oh5NXv9aw="
    }
  }
}
```
**Updated dependency**

angular

**What you expected to see, versus what you actually saw**
I expect the version to be the same, but "1.8.0" was suggested.

**Images of the diff or a link to the PR, issue or logs**
![Screenshot from 2020-08-20 18-29-35](https://user-images.githubusercontent.com/7053612/90799185-2736ad80-e313-11ea-9a6f-8daf1d3eaa02.png)

**Comment by jurre** [comment]
You can configure dependabot to only update the lockfile, and never package.json by using the `versioning-strategy: lockfile-only` strategy as described here: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy and configure angular to only update patch versions in your package.json like `"~1.5"`.

**Comment by omartrigui** [comment]
@jurre Thanks for your reply. Would you please confirm that `versioning strategy` feature does not exist in `dependabot-omnibus` ? I did a search in this repo, but I didn't found anything relevant.

**Comment by omartrigui** [comment]
Thanks !

**Comment by ferdicus** [comment]
sorry late to the party, maybe someone can help me out to fully understand this: 

When I have this in my `package.json`
```
"prop-types": "^15.7.2",
"react": "16.13.1",
```

I'd expect:
A) dependabot to open a pull request for all minor/patch versions of `prop-types` < 16
B) dependabot to not touch `react` dependency

Unfortunately dependabot does update the manifest file for `react` :(

When I enable `lockfile-only`, will it also update the manifest file, when updating `prop-types` to say `15.9.1`? 
Will it even attempt to do this?

Thanks in advance

**Comment by alitainfotech** [comment]
@ferdicus I'm facing the same issue. Did changing to `lockfile-only` worked for you?
