### ISSUE TITLE
Allow to reduce the number of open PRs by tracking the library's maturity

### ISSUE THREAD

**Issue by gastaldi** [dependabot/dependabot-core#2468]
It would be great to have some sort of tracker to check when a new version "matures" depending on the library's past release frequency instead of opening a PR right away. This should drastically reduce the number of open PRs.

It's a nice feature already available in https://depfu.com/

**Comment by J-Vin** [comment]
What would help this? I bet we have plenty of resources already available,
waiting for a simple auth to access. I sure have found a ton I am working
on today. An "enabled" key not enabled yet.

**Comment by gastaldi** [comment]
@J-Vin the main use-case is to ensure that a library is only updated to a X version if no X+1 versions is released in a certain period.

**Comment by J-Vin** [comment]
Lol, I meant do you have any idea what would help these maturity steps show
in analytics? I wondered if it were something we could simply change a
setting or add a key value.

**Comment by gastaldi** [comment]
@HonkingGoose yes, you're right. I think this issue can be closed as a duplicate of #2151
