### ISSUE TITLE
Update GitHub Actions to latest release commit hash

### ISSUE THREAD

**Issue by rosslh** [dependabot/dependabot-core#2470]
I am using Dependabot to update my GitHub Actions which is a very useful feature! There is one issue though: I want to specify the action version using commit hashes - not tag names. This is because tags can be deleted and republished with malicious code, whereas a commit at a specific hash is immutable. [More detail on this issue here](https://julienrenaux.fr/2019/12/20/github-actions-security-risk/).

Right now when updating my actions, Dependabot replaces the commit hash with the latest tag name (e.g. `actions/example@6c2f566` becomes `actions/example@v1.0.0`). It would be great if it could find the commit hash of the latest release and use that instead.

**Comment by reitermarkus** [comment]
Might be as easy as changing

https://github.com/dependabot/dependabot-core/blob/main/github_actions/lib/dependabot/github_actions/update_checker.rb#L73

to return the `:commit_sha`, i.e. never “downgrading” a hash to a less secure tag.

Reading the code, I actually think these are swapped currently: Tag will be updated to a hash and hash will be updated to a tag.

**Comment by jauderho** [comment]
FWIW, this still seems to be a problem. 

For example, see this pull request generated by dependabot: https://github.com/jauderho/psfiles/pull/1

It's trying update a hash to a version tag.
