### ISSUE TITLE
 5000+ github fetch requests in 15 minutes

### ISSUE THREAD

**Issue by eramax** [dependabot/dependabot-core#2471]
Package manager: python

I found an issue that dependabot tried thousand times to fetch " azure-sdk-for-python " package until the github limit has exceeded. 
I don't know exactly what has been happened but It took almost 15 minutes to exceed all 5000 github request and return.

you can check this logs.
![ksnip_20200821-162515](https://user-images.githubusercontent.com/542413/90902002-16963e00-e3cc-11ea-8d9c-5f7515407d6b.png)

**Comment by jurre** [comment]
Could you share a bit more about how you have set up dependabot to open pull requests etc? Are you using `dependabot-script` as a baseline?

**Comment by jeffwidman** [comment]
Should this be closed as stale since OP seems to have disappeared?
