### ISSUE TITLE
Feat: configure option for bundling some packages in one PR

### ISSUE THREAD

**Issue by timomayer** [dependabot/dependabot-core#2486]
It often happens that a bigger framework has multiple packages (react, storybook, ...) if you use a lot of them and they all get updated with a new release, dependabot opens PRs for every single module.

I would like to see a feature to make it configurable to combine updates for specific packages always into one single PR opened by dependabot.

**Comment by jurre** [comment]
Hi @timomayer, this looks like a duplicate of https://github.com/dependabot/dependabot-core/issues/1190. It's definitely on our radar, but our current setup makes it hard, so it might be a while before this lands.
