### ISSUE TITLE
How Dependabot handle peer dependencies?

### ISSUE THREAD

**Issue by mahmoud-alfadel** [dependabot/dependabot-core#2491]
Hi @feelepxyz, @greysteil 

I have seen several cases where Dependabot closes a PR due to a reason like this "Looks like XYZ is no longer updatable, so this is no longer needed," as seen in this latest PR [here](https://github.com/ErvinKhamoydo/petrichNewJS/pull/7).

After some search, I found that this could be due to a peer dependency that blocks updating another dependency. But then why should Dependabot open this PR in the first place? And how does it handle peer dependencies if it is the case?

I would appreciate your clarification on this.

**Comment by jeffwidman** [comment]
👋 We've shipped a lot of improvements to peer dependency support over the last year: https://github.com/dependabot/dependabot-core/pulls?q=is%3Apr+is%3Aclosed+peer+dependency

So closing as the behavior you saw two years ago is likely completely different now.
