### ISSUE TITLE
dependabot fails fast on 1st invalid entry in gitsubmodule

### ISSUE THREAD

**Issue by gberche-orange** [dependabot/dependabot-core#2497]
As a dependabot user
* In order to get dependency updates despites partially invalid gitsubmodule config in a git repo
* I need dependabot to ignore invalid submodules instead of failing early.

**Package manager/ecosystem**
gitsubmodule

**What you expected to see, versus what you actually saw**

Given a .gitmodules file with an entry containing a non existent path such as [orange-cloudfoundry/paas-templates](https://github.com/orange-cloudfoundry/paas-templates/blob/94ddfde8fb029adcc41131e318c4aac1170cc3f3/.gitmodules#L13-L15
)

```
[submodule "master-depls/bosh-expe/template/bosh-deployment"]
	path = master-depls/bosh-expe/template/bosh-deployment
	url = https://github.com/cloudfoundry/bosh-deployment
```

When dependabot fails to fetch the faulty submodule and halts as the following logs show

```
[...]
  proxy | 2020/09/02 08:06:07 [014] 404 https://api.github.com:443/repos/orange-cloudfoundry/paas-templates/contents/master-depls/bosh-expe/template/bosh-deployment?ref=e5eRedactedHash
updater | ERROR <job_49822948> Error during file fetching; aborting
updater | INFO <job_49822948> Finished job processing
```

**Comment by jurre** [comment]
Hi @gberche-orange, I'm not sure I understand, but why would you not remove the invalid submodule instead?

**Comment by gberche-orange** [comment]
@jurre the invalid submodule would eventually be fixed, but in the meantime the other submodule still need to get updates from dependabot.

In the example repo, there are 17 submodules contributed by different teams. The failure of a single one prevent all others from getting updates from dependabot.

As a comparison, github UI still properly displays other valid submodules in that repo, and does not fail fast on the 1st invalid repo.

**Comment by jurre** [comment]
Gotcha, I'm not sure why we bail out early and if it's easy to still try and process the other submodules, but will try to find time to look into it 👍

**Comment by asgoel** [comment]
@jurre did you ever have a chance to look into this? I am seeing a similar issue where we have a submodule that we do not want to track updates for, but dependabot errors out if the `pyproject.toml` file in that submodule is invalid for whatever reason.
