### ISSUE TITLE
Security fixes ignore dependabot.yml

### ISSUE THREAD

**Issue by ChildishGiant** [dependabot/dependabot-core#2501]
**Package manager/ecosystem**
npm

I have my dependabot.yml setup to push to a dev branch but security fixes still push to master

**Comment by simlu** [comment]
This... what a pain in the butt... I rather disable security fixes than dealing with the merge conflicts

**Comment by jeffwidman** [comment]
Duplicate of https://github.com/dependabot/dependabot-core/issues/2767
