### ISSUE TITLE
cargo: updater misses a valid update (update_not_possible)

### ISSUE THREAD

**Issue by lucab** [dependabot/dependabot-core#2512]
**Package manager/ecosystem**

cargo

**Manifest contents prior to update**

https://github.com/coreos/zincati/blob/67f9f2cd0a376b4dc2406100083f3270634aef8c/Cargo.toml

**Updated dependency**

`prometheus`, expected update from `0.9.0` to `0.10.0`.
 
**What you expected to see, versus what you actually saw**

Dependabot is skipping this update, with the following messages logged:
```
  proxy | time="2020-09-08T05:14:56Z" level=info msg="proxy starting" commit=6c7a5acb2b2982f6bbe35988d635b24d7afa72ee
updater | time="2020-09-08T05:15:01Z" level=info msg="guest starting" commit=3f2146432118fdd1c0106af94aa1ee3180c134d7
updater | time="2020-09-08T05:15:01Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=54064398 updater_timeout=45m0s updater_version=0.119.2-44f545d18b91fba30ffc1bf83f991775bf34ab91
...
updater | INFO <job_54064398> Checking if prometheus 0.9.0 needs updating
updater | INFO <job_54064398> Latest version is 0.10.0
updater | INFO <job_54064398> Requirements to unlock update_not_possible
updater | INFO <job_54064398> Requirements update strategy bump_versions
updater | INFO <job_54064398> No update possible for prometheus 0.9.0

```

This is somehow new/recent, as previous updates to the same dependency were fine, e.g. https://github.com/coreos/zincati/pull/289.

**Comment by andrewbanchich** [comment]
I've been getting this as well. Dependabot worked for me for a couple PRs, then I updated `dependabot.yml` to include every workspace in my repo and it hasn't made a PR since. Not sure if that is related.

**Comment by lucab** [comment]
@andrewbanchich FYI I have a wild guess that `^` versions may play a role in this, see https://github.com/dependabot/dependabot-core/issues/2532#issuecomment-706071885.

**Comment by lucab** [comment]
I can confirm that carets were the root cause of my troubles. I'm closing this, keeping #2532 open as a duplicate.

**Comment by maxcountryman** [comment]
I'm seeing this message when using the Unix epoch as a version for a private Ruby gem. Oddly, it looks like Dependabot worked exactly one time and since then has not caught newer versions of the gem.
