### ISSUE TITLE
Dependabot closed the PR with "these dependencies are no longer a dependency" but it still is a dependency

### ISSUE THREAD

**Issue by reedr3** [dependabot/dependabot-core#2522]
Dependabot opened a PR for a dependency bump of springBootVersion. (https://github.com/cloudfoundry/uaa/pull/1376)
In this PR it bumped springBootVersion from 2.3.0.RELEASE to 2.3.3.RELEASE.

We then commented @dependabot rebase.
Dependabot then closed the PR with the comment "Looks like these dependencies are no longer a dependency, so this is no longer needed."

The bump from 2.3.0 to 2.3.3 was not merged into develop and so was lost.

This seems like @dependabot rebase is not working as expected in this case. We would have expected it to leave the PR open since the bump from 2.3.0 to 2.3.3 was still needed.

Our dependencies.gradle file has the following:

```
versions.springBootVersion = "2.3.0.RELEASE"
libraries.springBootBom = "org.springframework.boot:spring-boot-dependencies:${versions.springBootVersion}"
libraries.springBootGradlePlugin = "org.springframework.boot:spring-boot-gradle-plugin:${versions.springBootVersion}"
```

In our build.gradle we pull in dependencies via `apply(from: "dependencies.gradle")`

**Comment by deivid-rodriguez** [comment]
@jeffwidman I think we actually have a repro of this in our own repo: https://github.com/dependabot/dependabot-core/pull/5879.

**Comment by jeffwidman** [comment]
Oh interesting. I'd assumed the problem was a regression in our version parsing logic for Gradle that stopped picking up the new version, but #5879 is a npm/yarn issue, which points toward more of a generic service-level issue...

**Comment by Zwyx** [comment]
Hi @jeffwidman , this bug still happens: https://github.com/Zwyx/library-of-babel/pull/11

The alerts are still presents https://github.com/Zwyx/library-of-babel/security/dependabot but Dependabot doesn't want to recreate the PR.
