### ISSUE TITLE
Add command to update edited PR

### ISSUE THREAD

**Issue by jotoeri** [dependabot/dependabot-core#2524]
On a open dependabot-PR i got the information about a newer dependency version:
"_A newer version of electron exists, but since this PR has been edited by someone other than Dependabot I haven't updated it._"

Still, i would like to directly use the next dependency-version (a patch), but don't want to loose, what i committed already to fix previous breaking changes.
A dependabot command like `@dependabot update` would be a cool thing to manually trigger the update. IMO it would suffice if dependabot pushed a fixup, which i would then squash & merge later...

**Comment by mwaddell** [comment]
You can close the PR you edited (but not delete the branch) and dependabot will then create a new one for you - then you can manually merge the changes (or cherry-pick them) into the new branch

**Comment by jeffwidman** [comment]
Yeah, there's not a lot we can safely do in an automated fashion here... and the request to add a commend to re-edit stuff starts to move us toward re-implementing basic `git` functionality which is a rabbit hole we don't want to go down any further than we already are. The best solution is what @mwaddell proposed ☝️ .
