### ISSUE TITLE
Make new update PRs bundled together in a single PR.

### ISSUE THREAD

**Issue by claeusdev** [dependabot/dependabot-core#2526]
I would like to be able to bundle all the latest updates/PRs into one single PR. So currently, I have to review and merge a single PR from dependabot and then I would have to go ahead and update all other PRs either from dependabot or from our own codebase with the master branch, so say we have about 12 new updates to gems we use in our project, we have to do this individually for all. 

It would be rad to have this feature. If there's nobody to work on now, with some guidance i would be able to work on this.

**Comment by jurre** [comment]
Hi @claeusdev, we're already tracking this here: https://github.com/dependabot/dependabot-core/issues/1190

I appreciate your offer to work on this, but supporting the feature would require significant changes in the backend services that we use to run Dependabot at GitHub, and we would need to scope out how to integrate such a feature. Unfortunately our team currently doesn't have the bandwidth to work on this.

I'm going to close this out as a duplicate, and we will update #1190 when we know more.
