### ISSUE TITLE
Support/workaround for private php/composer dependencies

### ISSUE THREAD

**Issue by pkruithof** [dependabot/dependabot-core#2545]
I know there are a [couple of issues](https://github.com/dependabot/dependabot-core/issues?q=is%3Aissue+is%3Aopen+private) related to this, but all of them specify different package managers. Apologies if this is not the correct way to report issues.

Since migrating to the native Dependabot integration, it basically stopped working for us because we have private repositories that we include in our composer dependencies. What I would like to know:

* can you give us any indication when this will be supported?
* is there some way we can exclude this dependency so Dependabot can work for our other dependencies in the meantime?

**Comment by jurre** [comment]
> Since migrating to the native Dependabot integration, it basically stopped working for us because we have private repositories that we include in our composer dependencies. What I would like to know:

We don't yet support private registries in the GH native version of Dependabot, if you need this for now we recommend that you stick to Dependabot Preview.

> can you give us any indication when this will be supported?

We're starting work on this soon, but I can't give an exact date. It's a high priority for our team though

> is there some way we can exclude this dependency so Dependabot can work for our other dependencies in the meantime?

Unfortunately that's not possible, we need to be able to pull in all the dependencies in order to perform an update.

**Comment by pkruithof** [comment]
Thanks for the update. Do you mind if we keep this issue open to track the progress and avoid similar questions?

**Comment by pkruithof** [comment]
It seems like this is working now. Are you aware of any updates regarding this @jurre?

**Comment by rdohms** [comment]
@jurre any more news or an estimated timeline on auth against a private registry? (or a better issue to track?)

**Comment by jurre** [comment]
> @jurre any more news or an estimated timeline on auth against a private registry? (or a better issue to track?)

This is probably the best issue to track: https://github.com/github/roadmap/issues/67

If you're interested in testing it out before it's released once we're ready, please reach out to jurre <at> github <dot> com and I'll connect you to the right people

**Comment by asciimike** [comment]
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta, so you all are good to go (and special thanks to @rdohms for providing some pre-release feedback!)
