### ISSUE TITLE
Dependabot can't find `pip-compile` executable when updating packages

### ISSUE THREAD

**Issue by craigds** [dependabot/dependabot-core#2548]
**Package manager/ecosystem**
python:pip-compile

**Manifest contents prior to update**

https://github.com/koordinates/sno/blob/master/requirements/requirements.in

**Updated dependency**
any

**What you expected to see, versus what you actually saw**

Packages get updated normally in both the requirements.in and requirements.txt files

**Images of the diff or a link to the PR, issue or logs**

[[full log]](https://app.dependabot.com/accounts/koordinates/update-logs/48497045)

This issue happens with every package that dependabot tries to update:

```
updater | I, [2020-09-23T19:40:04.025727 #73]  INFO -- sentry: ** [Raven] Sending event 0d21575912e946e7b393f99d7150b0d8 to Sentry

  proxy | 2020/09/23 19:40:04 [046] POST https://sentry.io:443/api/1425239/store/

  proxy | 2020/09/23 19:40:04 [046] 200 https://sentry.io:443/api/1425239/store/

updater | ERROR <job_48497045> Error processing psycopg2 (Dependabot::SharedHelpers::HelperSubprocessFailed)

updater | ERROR <job_48497045> pyenv: pip-compile: command not found

updater | <job_48497045> 

updater | <job_48497045> The `pip-compile' command exists in these Python versions:

updater | <job_48497045>   2.7.18

updater | <job_48497045>   3.8.5

updater | <job_48497045> 

updater | <job_48497045> Note: See 'pyenv help global' for tips on allowing both

updater | <job_48497045>       python2 and python3 to be found.
```

Note: our other projects in our org (all closed source, unlike this one) are using the same devPI index URL and seem to be updating fine.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by jeffwidman** [comment]
Closing due to lack of response.
