### ISSUE TITLE
A declarative way of monitoring new versions

### ISSUE THREAD

**Issue by didier-durand** [dependabot/dependabot-core#2553]
Hi there,

I am a - very - happy user of dependabot on Java projects with Maven: it saves me hours!

I also have some other repos where shell scripts is the dominant language : I use curl to download some products on the fly as suggested by their developers.  The URLs include version number. I would like to get notified by dependabot if a newer version gets available (usually via a git tag) on the source repo.

Is that already possible or planned?

Thanks!

Didier

**Comment by thepwagner** [comment]
👋 this seems related to https://github.com/dependabot/dependabot-core/issues/2483 , but that's specific to urls in `Dockerfile`.

The same kind of hacks are possible as there, e.g. try to manage the version in a supported ecosystem if possible.

**Comment by didier-durand** [comment]
Thanks! Will explore this path.
