### ISSUE TITLE
Connection error to  "https://pypi.python.org/simple/" since around a few days

### ISSUE THREAD

**Issue by righettod** [dependabot/dependabot-core#2562]
Hello,

Since a few days, dependabot cannot correctly check the dependencies of my Python projects and raise this error:

![image](https://user-images.githubusercontent.com/1573775/94346905-1a9f2680-0030-11eb-84cd-85ce27ce6992.png)

* [Case 1](https://github.com/righettod/robots-disallowed-dict-builder/issues/12)
* [Case 2](https://github.com/righettod/tls-cert-discovery/issues/51)
* [Case 3](https://github.com/righettod/website-passive-reconnaissance/issues/18)

It is normal? It is related to **pypi.python.org** repository?

Perhaps is related to my projects but nothing has changed since the beginning of occurence of the issue.

Thank you very much in advance for your feedback 😃

**Comment by feelepxyz** [comment]
@righettod yeah this was an issue with pypi which has now been resolved: https://github.com/dependabot/dependabot-core/issues/2550#issuecomment-698921000

**Comment by righettod** [comment]
Ok, thank you very much for the clarification 👍
