### ISSUE TITLE
shared_helpers.rb:16:in `<module:SharedHelpers>': uninitialized constant Dependabot::VERSION (NameError)

### ISSUE THREAD

**Issue by crtdaniele** [dependabot/dependabot-core#2566]
Hi,
we have an issue with the new release (probably).
When I try to run Dependabot core on Azure pipeline, I see this error:

shared_helpers.rb:16:in `<module:SharedHelpers>': uninitialized constant Dependabot::VERSION (NameError)

Could you help me?

Thanks,
Daniele

**Comment by jurre** [comment]
Hi, that issue was introduced in the last release, you can `require "dependabot/version" in the file that's giving you this error to fix it and I'm also in the process of releasing a new version that fixes this, should take about an hour to test and roll everything out.

**Comment by crtdaniele** [comment]
Thanks! 
Work for me.

Now, I have another issue:

danielecarta => example-project => example-project => Checking for Azure Pipeline configuration file...
danielecarta => example-project => example-project => Azure Pipeline configuration file does not exist, raising bug if required...

In the project, I have the folder .dependabot with the config.yml file.
But now doesn't work correctly.

Thanks,
Daniele

**Comment by jurre** [comment]
Do you have the stacktrace?

I'm a little confused, the `dependabot/config.yml` file is used when using dependabot.com, but when you run dependabot-core as a standalone script on Azure pipelines the config file is not used.

**Comment by crtdaniele** [comment]
Mmmh I think you are wrong.
The config.yml is for non dependabot.com use.

https://dependabot.com/docs/config-file/
"These docs are for "Dependabot Preview", the legacy non-native version of Dependabot."
