### ISSUE TITLE
Update Peer dependencies

### ISSUE THREAD

**Issue by godban** [dependabot/dependabot-core#257]
Hey guys,
we are using dependabot for some time, thx for nice service. But we are missing one feature. Dependabot doesn't updates peer dependencies and we need to do it manually each time.

<img width="400" src="https://user-images.githubusercontent.com/2461970/36086802-a65409ac-0fce-11e8-9e31-3329b5ac5f6e.png"/>

Does it make sense to add support of it?

Thx

**Comment by greysteil** [comment]
It definitely does! I'm on holiday for the next week, so can't dig into this, but I'll try to get to it when I'm back. Totally agree Dependabot should handle peer dependencies, though :-)

**Comment by greysteil** [comment]
Would you mind porting this issue over to https://github.com/dependabot/feedback so it doesn't get lost?

**Comment by godban** [comment]
@greysteil sure

**Comment by greysteil** [comment]
❤️
