### ISSUE TITLE
Dependabot core on private registry on Azure

### ISSUE THREAD

**Issue by crtdaniele** [dependabot/dependabot-core#2573]
I tried to configure Dependabot for private npm registry.
In my file run.rb I insert this config:

credentials = [
  {
    "type" => "npm_registry",
    "token" => "",
    "registry" => "", (the path of registry without https://
  },
  {
    "type" => "git_source",
    "host" => "dev.azure.com",
    "username" => "x-access-token",
    "password" => ""
  }
]

In the pipeline on Azure: Failed processing: The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): path_of_registry

I use this repo on Azure: https://github.com/chris5287/dependabot-for-azuredevops

**Comment by jurre** [comment]
Hi @crtdaniele, I have no idea how the dependabot-for-azuredevops script/project works, you may have better luck opening an issue on [their repository](https://github.com/chris5287/dependabot-for-azuredevops), it doesn't seem like an issue with dependabot-core specifically.
