### ISSUE TITLE
Dependabot seemingly not working for repos

### ISSUE THREAD

**Issue by marktucks** [dependabot/dependabot-core#2574]
We have Dependabot enabled for all repos but we haven't had a pull request since 18th June, and that's only on one repo.

The repo that did have the PR, recently had a security advisory for Elliptic, which npm audit picked up in our build for some recent changes, but nothing from Dependabot. The Elliptic advisory was published 29th July.

**Package manager/ecosystem**
javascript
**Manifest contents prior to update**
package.json
**What you expected to see, versus what you actually saw**
I expected Dependabot to create a PR for Elliptic around the time the security advisory was published.

When does Dependabot check dependencies? Is it an ongoing thing, or only when something changes in the repo? Would existing PRs prevent Dependabot from creating PRs? as we have a couple of outstanding PRs for that repo. How do we know it's running for other repos?

**Comment by feelepxyz** [comment]
@marktucks have you configured version updates with a config file or using security updates only? If it's security updates you check the Security tab on the repo > dependabot alerts > click into an alert and see if dependabot has attempted to create an update. You can enable automated security updates from the repo settings page > security & analysis.

Security updates should be created in response to alerts but there's a open PR limit of 10 and 5 if you're using version updates with a config file.

If you've configured dependabot using the config file, check the status of it under the Insights tab > Dependency Graph > Dependabot. We had a bug previously which meant some repos lost track of the config file, in this case just pushing a new commit to the config file should fix this issue.

Let me know if this answers your question.
