### ISSUE TITLE
How to verify what command composer uses?

### ISSUE THREAD

**Issue by kevinquillen** [dependabot/dependabot-core#2588]
I am trying to set up a project with dependabot to give it a test run on a project.

The docs say that the way to update Drupal 9 is by running:

`composer update drupal/core-recommended --with-dependencies`

Is there a way to ensure that happens using dependabot and composer? I see others are using it for Drupal, so I am curious if it works. Is there a way to order which dependencies are updated?

**Comment by convenient** [comment]
Based on my investigation in https://github.com/dependabot/dependabot-core/issues/4416 it seems like it does update with dependencies

**Comment by lseppala** [comment]
Thanks for cross-linking your investigation, @convenient.

Yes, it seems to be the case that it is updated with dependencies. Looking at the Composer updater code

https://github.com/dependabot/dependabot-core/blob/5456c0dd3e3c6e2a2dac87d9ebce156e8230fab6/composer/helpers/v2/src/Updater.php#L78-L87

and the documentation for [setUpdateAllowTransitiveDependencies](https://api.drupal.org/api/drupal/vendor%21composer%21composer%21src%21Composer%21Installer.php/function/Installer%3A%3AsetUpdateAllowTransitiveDependencies/9.2.x), this updates the transitive dependencies when one dependency is updated.

I hope this answered your question! I am going to mark this as resolved, but you are welcome to reopen if there is misunderstanding.
