### ISSUE TITLE
.Net  - Updating Packages.props fails

### ISSUE THREAD

**Issue by TrymBeast** [dependabot/dependabot-core#2592]
**Package manager/ecosystem**
nuget

**Manifest contents prior to update**
* Packages.props content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Update="Microsoft.Web.Infrastructure" Version="1.0.0" />
    <PackageReference Update="Microsoft.AspNet.WebPages" Version="3.2.7" />
    <PackageReference Update="Microsoft.AspNet.Mvc" Version="5.2.7" />
    <PackageReference Update="Microsoft.AspNet.Web.Optimization" Version="1.1.3" />
    <PackageReference Update="Microsoft.AspNet.Razor" Version="3.2.7" />
    <PackageReference Update="Microsoft.AspNet.WebPages" Version="3.2.7" />
    <PackageReference Update="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Update="WebGrease" Version="1.6.0" />
    <PackageReference Update="Antlr" Version="3.5.0.2" />
    <PackageReference Update="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="2.0.1" />
  </ItemGroup>
</Project>
```
**What you expected to see, versus what you actually saw**
I was expecting to see some PRs to update Newtonsoft.Json and Microsoft.CodeDom.Providers.DotNetCompilerPlatform but it just gives an error, it seems to detect the file but this happens:

> proxy | 2020/10/02 07:17:40 [008] 200 https://api.github.com:443/repos/TrymBeast/CentralPackageVersion/contents/Packages.props?ref=f2c6ded46782df1c3e63e717b563c79688f4afdf
> updater | ERROR <job_64487579> Error during file fetching; aborting

**Comment by jeffwidman** [comment]
Thanks for reporting, and sorry it took us so long to get to this.

This is two years old, and our infra has changed a _lot_ since then, plus our logs for this are long-gone.

So I'm going to close, but if you're still seeing this issue leave a comment and I'll happily re-open.
