### ISSUE TITLE
go modules in subgroups cannot be resolved

### ISSUE THREAD

**Issue by hensur** [dependabot/dependabot-core#2618]
I recently deployed https://gitlab.com/dependabot-gitlab/dependabot on a private gitlab instance. I added a `.netrc` to the dependabot container which allow dependabot to fetch private repositories.

However, I noticed, that repositories inside gitlab subgroups could not be resolved.
The dependency `https://gitlab.example.com/test/subtest/dependency.git` causes this error:
```
remote: The project you were looking for could not be found.
    fatal: repository 'https://gitlab.example.com/test/subtest.git/' not found
```

I know that the `dependabot-gitlab` project might behave differently, but I was able to reproduce the issue with the helpers in `/go_modules/helpers` as well:
```
echo '{"function": "getUpdatedVersion","args": {"dependency": {"name": "gitlab.example.com/test/subtest/dependency", "version":"v0.1.5", "indirect": false}}}' | go_modules/helpers/helpers
```
This command returns the same error as described above.

The issue seems to be an outdated version of the golang internal module code which gets imported from https://github.com/dependabot/gomodules-extracted .

I re-extracted the code and was able to successfully fetch the latest version for the given package. The updated `gomodules-extracted` package requires some changes to the helpers in this repo as well, as some function signatures have changed.

I will create PRs with my changes and reference them here.
gomodules-extracted PR: https://github.com/dependabot/gomodules-extracted/pull/6
dependabot-core PR (depends on gomodules PR): https://github.com/dependabot/dependabot-core/pull/2619

**Package manager/ecosystem**
go mod

**Manifest contents prior to update**
private gitlab instance

**Updated dependency**
private gitlab instance

**What you expected to see, versus what you actually saw**
no errors while checking private go modules

**Images of the diff or a link to the PR, issue or logs**

**Comment by jeffwidman** [comment]
Can this be closed now that the two PR's necessary to fix this have been merged?

**Comment by hensur** [comment]
Yes, this can be closed!
