### ISSUE TITLE
Add dependabot badge

### ISSUE THREAD

**Issue by JamieMagee** [dependabot/dependabot-core#262]
Other services use a badge to show that the service is enabled for a certain GitHub repository. It might be a good way to increase awareness of dependabot by adding badges, showing that dependabot is enabled for a repo.

It could just be something as simple as a static badge like

[![Dependabot badge](https://img.shields.io/badge/Dependabot-enabled-blue.svg)](https://dependabot.com/)

When first enabling dependabot on a repo, the first PR could add the badge to the README.

**Comment by greysteil** [comment]
Super up for this. There's an issue tracking it over at https://github.com/dependabot/feedback/issues/49 and I've been slow to implement it, but I'll try to get it done in the next couple of weeks. Higher priority now that Gemnasium are shutting down.

Closing in favour of https://github.com/dependabot/feedback/issues/49, but thanks for the feedback / support!

**Comment by skeggse** [comment]
Hm I think that issue isn't quite linked correctly :grin:

**Comment by greysteil** [comment]
Oops! That should have been https://github.com/dependabot/feedback/issues/6!

**Comment by jtmoon79** [comment]
Relates to https://github.com/dependabot/dependabot-core/issues/1912
