### ISSUE TITLE
Add dependabot action to remove dependency

### ISSUE THREAD

**Issue by ColtonIdle** [dependabot/dependabot-core#2623]
Currently dependabot tells me that a dep is out of date and it sometimes reminds me "oh yeah! That my dependency isn't actually needed anymore!

It would be cool to say `@dependabot remove dep` and it'll just remove it in the same PR or create a new PR.

**Comment by jeffwidman** [comment]
I do see how this would be convenient if you were an expert in Dependabot commands, but most of our users aren't... many have no idea there's a `dependabot rebase` and `dependabot recreate`. Most just want their PR opened for new versions and move on with life. So I'm afraid I just don't see us spending the time to wire this up anytime in the forseeable future vs spending the time to support more ecosystems, fix bugs etc, so I'm actually going to close this for now, sorry. 

Long term, ideally the native package management tool would realize something is unused and auto-remove it (`go` does this for example).
