### ISSUE TITLE
Bugsnag package release notes match incorrect ecosystem in a python project

### ISSUE THREAD

**Issue by surkova** [dependabot/dependabot-core#2629]
**Package manager/ecosystem**
pip, python 3.8, flask app
**Manifest contents prior to update**
...

**Updated dependency**
bugsnag
**What you expected to see, versus what you actually saw**
Release notes included match `bugsnag-androind` project, while the package is being updated for a python app.
**Images of the diff or a link to the PR, issue or logs**

![Screen Shot 2020-10-13 at 09 38 23](https://user-images.githubusercontent.com/842976/95830374-da31ef00-0d37-11eb-9040-87d9d266ab22.png)

**Comment by kattrali** [comment]
Aha! I can fix that, thanks for letting me know.

**Comment by surkova** [comment]
@kattrali should I close this issue?
