### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by kritzikratzi** [dependabot/dependabot-core#2634]
please let your bot live somewhere else. make a fork and do your things there, or whatever, i don't care. but please don't bother me with automated checks of outdated repos. 

i see the good intention, but this is truly annoying for me.

**Comment by jurre** [comment]
You can disable Dependabot for [a single repo](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates#managing-github-dependabot-security-updates-for-your-repositories) or [all repo's in your account](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/managing-security-and-analysis-settings-for-your-user-account. Hope that helps.

**Comment by arhadthedev** [comment]
@jurre, probably, kritzikratzi means that by default the bot creates a daily bunch of pull requests clogging inbox notifications of everybody subscribed. With a big list of dependencies, it turns into a daily mini-catastrophe.

Maybe we need to replace individual per-bump pull requests into individual per-bump commits grouped into a unified summary pull request once per day/monts/whatever `interval` is set.

**Comment by jurre** [comment]
Thanks @arhadthedev, we're definitely aware of the noise Dependabot can create and have plans to tackle that in the future, but currently our team doesn't have the capacity to dedicate focus to this.

Grouped updates is definitely on our radar, there are a few issues tracking this already 👍
