### ISSUE TITLE
Update poetry to the latest version (1.1.3)

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#2650]
Currently I see that `dependabot` uses `poetry@1.1.2` (or previous versions)
But, it produces errors that were fixed in `1.1.3`: https://github.com/wemake-services/wemake-python-styleguide/pull/1672/checks?check_run_id=1262837348

Let's bump the `poetry` version! 🙂

**Comment by jurre** [comment]
Will try to merge https://github.com/dependabot/dependabot-core/issues/2650 today and roll out a new version next week, that should resolve those 🤞

**Comment by ulgens** [comment]
@jurre #2650 is this issue, i think you mean #2641 . Also, 1.1.4 is the latest version now, i'm not sure why it's not replaced by a newer PR yet. In any case, any news there? :slightly_smiling_face:

**Comment by sobolevn** [comment]
And https://github.com/dependabot/dependabot-core/pull/2676

**Comment by ulgens** [comment]
This can be closed now.

**Comment by sobolevn** [comment]
Thanks everyone!
