### ISSUE TITLE
inconsistent PR messages

### ISSUE THREAD

**Issue by ahmadnassri** [dependabot/dependabot-core#2659]
PR message is seemingly never consistent, in the past two weeks, I've surfaced the following scenarios:

- some PRs missing `from x.x.x` despite others including it

![image](https://user-images.githubusercontent.com/183195/96481346-67c68080-1209-11eb-84f7-4233d76553ad.png)
_(you can see this one here: https://github.com/mdn/yari/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed)_

- inconsistent use of "chore" and "build" within the same org:

Repo A:
![image](https://user-images.githubusercontent.com/183195/96480831-c0e1e480-1208-11eb-994b-5a2fb4cfbc27.png)

Repo B:
![image](https://user-images.githubusercontent.com/183195/96480851-c8a18900-1208-11eb-8409-6ea6692009ed.png)

both repos use the same commit message formats in other commits, and same `dependabot.yml` config

**Package manager/ecosystem**
N/A

**Manifest contents prior to update**
N/A

**Updated dependency**
N/A (everything)

**What you expected to see, versus what you actually saw**

- consistent commit message format and PR messages, use "build" for conventional commits.
- include "from" version numbers in all PRs.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.
