### ISSUE TITLE
Dependeabot warns of issues with package-lock.json file, which is no longer in the project

### ISSUE THREAD

**Issue by hisaac** [dependabot/dependabot-core#2665]
**Package manager/ecosystem**

`ruby:bundler`

**Updated dependency**

Dependaot is asking me to upgrade `object-path` to version 0.11.5 or later

**What you expected to see, versus what you actually saw**

**Summary:** After converting a project from nodejs to Ruby, I've been getting frequent requests from dependabot to update my node dependencies, which no longer exist in the project.

My project used to be a node-based project that used a `package-lock.json` to manage dependencies. Since then, I've converted the project to a Ruby-based project that uses Bundler and a `Gemfile` to manage dependencies.

Just today, Dependabot requested I update the `object-path` nodejs dependency, and points toward a `package-lock.json` file in my repo which no longer exists (this is the link it tries to open: https://github.com/hisaac/hisaac.net/blob/master/package-lock.json).

It seems that Dependabot has a cache of my repo that needs to be cleared. Is this an issue I can fix myself somehow?

**Images of the diff or a link to the PR, issue or logs**

![Screen Shot 2020-10-20 at 8 12 55 AM](https://user-images.githubusercontent.com/923876/96590802-13281180-12ac-11eb-9ba8-0ed0d7299a3f.png)

**Comment by infin8x** [comment]
Sorry about that! We're tracking a bug internally to fix the root cause of this issue, but in the meantime I've manually refreshed your dependency graph, which should stop the ghost alerts.

**Comment by hisaac** [comment]
Thank you @infin8x!
