### ISSUE TITLE
Support composer version 2

### ISSUE THREAD

**Issue by lstrojny** [dependabot/dependabot-core#2668]
Composer version 2 ~is currently in [RC2](https://getcomposer.org/changelog/2.0.0-RC2) and [is expected to land soon](https://twitter.com/seldaek/status/1316469160294191111)~ [has landed](https://blog.packagist.com/composer-2-0-is-now-available/) 

From trying to get dependabot-core going with composer 2.0.0-RC2, these three issues came up:

 * `setAllowListTransitiveDependencies()` is now `setUpdateAllowTransitiveDependencies(\Composer\DependencyResolver\Request::UPDATE_LISTED_WITH_TRANSITIVE_DEPS)`. This is used in `Dependabot\Composer\Updater` and `Dependabot\Composer\UpdateChecker`
 * `Composer\Installer\InstallationManager` requires constructor arguments now. `Dependabot\Composer\DependabotInstallationManager` extends that is used in `Dependabot\Composer\UpdateChecker`

So getting dependabot compatible should be quite doable

To my mind the question is: how to decide whether or not to use version 2? What would be possible is to let packages opt-in by requiring `composer-plugin-api` version 2 and only treat those as "should be updated with composer 2 for now".

**Comment by WyriHaximus** [comment]
It landed two days ago. And v1 was marked EOL with security fixes only at the same time: https://blog.packagist.com/composer-2-0-is-now-available/

> To my mind the question is: how to decide whether or not to use version 2? What would be possible is to let packages opt-in by requiring `composer-plugin-api` version 2 and only treat those as "should be updated with composer 2 for now".

IMHO go v2 from here on out, it is a lot faster, less resource intensive, and the only supported version. Another, and maybe even more important, the reason is that v2 is fully backwards compatible with v1. So upgrading to v2 wouldn't be a problem and have only gains.

**Comment by rdohms** [comment]
> IMHO go v2 from here on out, it is a lot faster, less resource intensive, and the only supported version. Another, and maybe even more important, the reason is that v2 is fully backwards compatible with v1. So upgrading to v2 wouldn't be a problem and have only gains.

Is this true though? If Dependabot runs v2 and a project runs v1 locally, they will get PRs for new versions of packages that depend on composer, like plugins. Those will break in CI, right?

**Comment by WyriHaximus** [comment]
> > IMHO go v2 from here on out, it is a lot faster, less resource intensive, and the only supported version. Another, and maybe even more important, the reason is that v2 is fully backwards compatible with v1. So upgrading to v2 wouldn't be a problem and have only gains.
> 
> Is this true though? If Dependabot runs v2 and a project runs v1 locally, they will get PRs for new versions of packages that depend on composer, like plugins. Those will break in CI, right?

That's the only major edge case, and there are two ways to deal with that:
A) Everyone to composer v2
B) Dependabot makes the version configurable in your dependabot config `- package-ecosystem: "composer"` vs `- package-ecosystem: "composer2"`

**Comment by jurre** [comment]
Thanks @WyriHaximus that's fantastic to hear, especially excited about the performance improvements, we've sometimes struggled to complete composer updates in time.

Will discuss with the team when we can prioritize this. Tbh I'm not sure if it's feasible for us to support two versions of composer, so we might have to wait until there's critical mass in terms of community support.

Given the blog post that you linked to, I don't see a reason for anyone not to upgrade though? So we could expect it to be the default fairly quickly?

**Comment by rdohms** [comment]
@jurre there is a bit of a chicken/egg problem with `wait until there's critical mass in terms of community support`. The entire PHP ecosystem is ready for this, pretty much all plugin and such things are ready for v2. But most of the people using dependabot are hanging back a bit since you only support v2.

The main issue here would be: any project that uses a composer plugin would get conflicting results. So for most of the people if you upgrade to 2 now it will not matter, but if you stay on v1 you would be slowing down the adoption of people who don't want to upgrade before you get to v2.

It's a lot better to nudge people to upgrade as opposed to holding them back. So If I may have a vote here: move to v2 now and help drive adoption.

**Comment by jurre** [comment]
Yeah @rdohms I generally agree with that sentiment 👍

**Comment by WyriHaximus** [comment]
So cutting to the solution, the change would update this line: https://github.com/dependabot/dependabot-core/blob/2503c8582222288cc0c44e83510aa267fa571334/Dockerfile#L103 to get it running with v2 (keeping https://twitter.com/naderman/status/1320708145988161536 in mind), and the things @lstrojny mentioned in the OP.

@jurre there is more on the horizon in terms of improvements but that probably land in 2.1 and look very promising: https://github.com/composer/composer/pull/9261

**Comment by WyriHaximus** [comment]
php-cs-fixer is blocking the upgrade:
![Screenshot from 2020-10-26 17-15-35](https://user-images.githubusercontent.com/147145/97198231-e2197680-17ae-11eb-8539-639fc547428e.png)

**Comment by WyriHaximus** [comment]
Opened a draft PR implementing this at #2682

**Comment by WyriHaximus** [comment]
> Opened a draft PR implementing this at #2682

Did not expect the 60 failing tests :joy:

**Comment by b1rdex** [comment]
There is an easy way to detect whether the project is moved to v2 or not: just check `plugin-api-version` field in `composer.lock`.
Would be nice to support both versions to not break anything.

**Comment by WyriHaximus** [comment]
@b1rdex Looking at the amount of work that needs to be done to move to v2, it's not worth also maintaining v1 support, which is also end of life as of the v2 release.

**Comment by staabm** [comment]
> To my mind the question is: how to decide whether or not to use version 2? What would be possible is to let packages opt-in by requiring `composer-plugin-api` version 2 and only treat those as "should be updated with composer 2 for now".

per https://github.com/composer/composer/issues/9501 it should be `composer-runtime-api` not `composer-plugin-api`:

> You should rather require composer-runtime-api: ^2 IMO if you require v2 runtime features, but technically it's going to be the same end result.

**Comment by boboldehampsink** [comment]
Currently, my manually upgraded projects to composer 2 are reverted every dependabot bump. So can't upgrade to v2 without dropping dependabot.

**Comment by WyriHaximus** [comment]
Also the thing I've noticed, and expected for that matter: It won't update packages requiring plugins requiring v2

**Comment by jurre** [comment]
After considering how Dependabot security updates work, where we send PRs to any repository with a security vulnerability, we feel that the burden to merge such a PR would become too high if it _also_ upgrades your lockfile at the same time.

As such, we feel that we should support both version for some time, more details on a deprecation process for v1 are coming.

I'm going to spike out what it would look like for us to support both versions this week, my current assumption is that we'll be able to detect the lockfile version at runtime and use the right composer version based on that.

Once we've found an approach to that problem that we're happy with, we can start working on upgrading all our tests to use the new lock file format, and start rolling this change out.

**Comment by boboldehampsink** [comment]
You might find inspiration at https://github.com/heroku/heroku-buildpack-php/pull/447, where this was also the case and has been fixed nicely (the way you already mentioned)

**Comment by WyriHaximus** [comment]
Whohoooooooooooo :tada: !!!

@jurre @feelepxyz So I assume the v2 supporting code will kick in within an hour or so?

**Comment by staabm** [comment]
@WyriHaximus see https://github.com/dependabot/dependabot-core/pull/2866

**Comment by jurre** [comment]
> Whohoooooooooooo :tada: !!!
> 
> 
> 
> @jurre @feelepxyz So I assume the v2 supporting code will kick in within an hour or so?

Yeah we're rolling it out right now, could be slightly longer than an hour but probably not. I'll ping here when it's live

**Comment by jurre** [comment]
Composer 2 support should be live now, I would love to hear if anyone runs into weird issues.

The way this is supposed to work is that we pick composer v1 if we notice a `plugin-api-version` of 1, and otherwise we use v2.

**Comment by WyriHaximus** [comment]
@jurre Already started kicking one package. Updates are streaming in, will do a composer v2 packages very soon

**Comment by WyriHaximus** [comment]
@jurre Ok first PR opened on a repository that purely targets composer v2: https://github.com/WyriHaximus/php-broadcast/pull/38 If there is anything funny happening I'll let ya'll know. Well done!

**Comment by carusogabriel** [comment]
Hey @feelepxyz @jurre Does this apply to `dependabot-preview` as well? We'd love to start using Composer V2 here at @usabilla, but we have some Private packages (https://github.com/dependabot/dependabot-core/issues/3092).

**Comment by feelepxyz** [comment]
@carusogabriel yep sure does 👍  we're also working on adding private registry support in the github native version but you can keep using preview until that's out.
