### ISSUE TITLE
Dependabot vendors go modules into a nested directory

### ISSUE THREAD

**Issue by Kemosabert** [dependabot/dependabot-core#2687]
**Package manager/ecosystem**
gomod
**What you expected to see, versus what you actually saw**
We have a monorepo and enabled dependabot for a service in the monorepo by adding a `dependabot.yml` file at the root of the repo in the `.github` folder. Since the `go.mod` file of the service for which we want to have automatic bumps is in the `catalog` folder, we added the `directory: "/catalog"` property to the config file. We vendor our dependencies in this application.

When dependabot created a PR for the bump of a dependency, it automatically vendored it, which  is great, but it did so in the `/catalog/catalog/vendor` folder and not in `/catalog/vendor` folder like it should be. It seems like it's nesting the vendored dependencies wrongly somehow.

**Images of the diff or a link to the PR, issue or logs**
<img width="1874" alt="Screenshot 2020-10-27 at 17 31 14" src="https://user-images.githubusercontent.com/21224391/97332043-4ead7780-187a-11eb-9d36-2016b6ea3e59.png">

**Comment by jurre** [comment]
Thanks for reporting this @Kemosabert, that definitely seems like a bug on our end, I'll look into it!

**Comment by Kemosabert** [comment]
Thanks for checking this @jurre, let me know if you need more information or context about this.
