### ISSUE TITLE
Missing native helpers in dependabot-bundler gem

### ISSUE THREAD

**Issue by manuelvanrijn** [dependabot/dependabot-core#2688]
**Package manager/ecosystem**
ruby:bundler

I noticed that dependabot-bundler only contains the lib folder, but https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/native_helpers.rb#L14 requires the `run.rb` file from the helpers folder. 

For me this resulted in a weird exception `Dependabot::DependencyFileNotEvaluatable: Error evaluating your dependency files`. Digging a little bit deeper I found that this is triggerd due to the error: `gems/dependabot-bundler-0.124.3/lib/dependabot/bundler/../../../helpers/run.rb (LoadError)`

The problem doesn't seem to occur in the CI because it uses the docker image, which contains all the folders and files.

I think the fix would be to include the helper folder within the gemspec, but before I dive into this I wanted to check if I'm not missing anything :)

**Comment by jurre** [comment]
I'm not sure if it makes sense to include those helpers in the gemspec, as we don't (and can't) do the same with other native helpers like [these](https://github.com/dependabot/dependabot-core/tree/main/go_modules/helpers).

How are you currently running Dependabot? If you're not using the docker image, you'll need to make sure that the native helpers for each ecosystem are available and setting the `DEPENDABOT_NATIVE_HELPERS_PATH` accordingly.

**Comment by manuelvanrijn** [comment]
Thanks @jurre 

This explains why the helpers aren't present within the gemspec. I'll figure out a way to specify the env variable :) thanks
