### ISSUE TITLE
Dependabot rebase slow on monorepo / yarn workspaces

### ISSUE THREAD

**Issue by Hazmi35** [dependabot/dependabot-core#2734]
**Package manager/ecosystem**
NPM / Yarn

**What you expected to see, versus what you actually saw**
I used yarn workspaces for my next personal website, and every day there's a chance that 3-6 dependencies have an update. 
I usually use `@dependabot squash and merge` to merge dependabot pull request, and everything works fine on the first PR I merged, and then it triggers dependabot to rebase on some PRs even if they **don't need to** sometimes, then instead of waiting I used the same command again, it should be merged after the rebase done and when the CI passed.
But the problem is sometimes when dependabot finished the rebase, the *"Dependabot is rebasing this PR"* message is still there, even if the rebase is done, I tried using `@dependabot rebase` but it says the PR is up-to-date but it does not merge automatically, even if CI has passed long ago, some PR can take up to 4 hours or less, this only happens on my repositories that use yarn workspaces, I also tried to type `@dependabot squash and merge` again, but it still stuck there for 1-4 hours, and sometimes the rebase is also takes a while, like 20-30 minutes.

**Images of the diff or a link to the PR, issue, or logs**
https://github.com/Hazmi35/website/pull/171 and some others pull request too

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?
