### ISSUE TITLE
Local dependencies ignored when using Pipfiles

### ISSUE THREAD

**Issue by greenape** [dependabot/dependabot-core#2735]
**Package manager/ecosystem**
Python:pipenv

**What you expected to see, versus what you actually saw**

Expect local path dependencies remain in the lock file, but they are removed.

**Images of the diff or a link to the PR, issue or logs**
https://github.com/Flowminder/FlowKit/pull/3242

**Comment by mattjw** [comment]
I hit this issue recently. Is there any work ongoing to tackle this? It'd be great to get a fix 🙏. Our workaround right now for the problematic project is to continue using Dependabot for the dependency notifications, but apply the update locally with a manual PR.

**Comment by deivid-rodriguez** [comment]
This was fixed by #8301!
