### ISSUE TITLE
Ability to automatically merge minor, deps-dev, and approved updates

### ISSUE THREAD

**Issue by alexandrz** [dependabot/dependabot-core#2743]
It would be helpful if it was possible to configure dependabot to automatically merge minor, deps-dev, or approved updates after PR passes all checks.

**Comment by jurre** [comment]
We've got a few discussions around automerge going already, I'm going to close this out as a duplicate. Please refer to https://github.com/dependabot/dependabot-core/issues/2268 and https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279
