### ISSUE TITLE
Propagate mixfile errors to the user better.

### ISSUE THREAD

**Issue by baseballlover723** [dependabot/dependabot-core#2757]
Currently if there is an error that causes dependabot to be unable to run the mixfile (such as using a file) while trying to update a dependency, then dependabot will swallow the error, making it very difficult to debug why the error is happening. I encountered this when I hadn't yet sanitized all of the supporting files (#2748), and it silently failed while trying to update the lockfiles. This particular error is fixed, but this could happen in the future with perhaps a more complex mixfile setup, or if future updates are not applied to all the places they need to.

The core cause for me was that the error was being swallowed [here](https://github.com/dependabot/dependabot-core/blob/main/hex/lib/dependabot/hex/update_checker/version_resolver.rb#L93-L97) and then nil being passed all the way back up and is eventually treated as not being upgradeable instead of being an error that the mixfile couldn't be executed. On top of that, the "error" return by the mix helpers, was just the empty string, so theres something not being handled correctly for propagating errors that occur in the hex helpers.

This probably requires a revamping of how errors are handled in the helpers in general, so I'll leave it to you all to decide if this is worth fixing or not.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by baseballlover723** [comment]
Hi, I don't work with Elixir anymore, so I'm not sure if its still an issue. I would presume so, if there haven't been major modifications to the hex part since I made this issue. Since the crux of it was that it would swallow the error message, and give back a generic one.
