### ISSUE TITLE
[Maven] Changes to version of parent in the root pom.xml are not reflected in child modules 

### ISSUE THREAD

**Issue by JarvisCraft** [dependabot/dependabot-core#2762]
**Package manager/ecosystem**
Maven

**Manifest contents prior to update**
`pom.xml` and `${submodule}/pom.xml` where `${submodule}` is the name of submodule directory referenced in `pom.xml`'s `<project><module>` section
**Updated dependency**
*any*

**What you expected to see, versus what you actually saw**
- **Expected**: Whenever the version of a parent of the root Maven module (`<project><parent><version>` in `pom.xml`) the corresponding version in the child module (`<project><parent><version>` in `${submodule}/pom.xml`) should also get changed to this value.
- **Actual**: Only parent's version gets updated while submodule's one doesn't

**Images of the diff or a link to the PR, issue or logs**

<details>
<summary>`pom.xml` (changed by Dependabot)</summary>

![image](https://user-images.githubusercontent.com/7693005/99154549-c9232780-26c1-11eb-8252-e1629f731663.png)
</details>

<details>
<summary>`pom.xml` (diff)</summary>

```diff
diff --git a/pom.xml b/pom.xml
index 4e672be..f3e385e 100644
--- a/pom.xml
+++ b/pom.xml
@@ -5,7 +5,7 @@
     <parent>
         <artifactId>custom-stuff</artifactId>
         <groupId>ru.divinecraft</groupId>
-        <version>1.0.2-beta.1</version>
+        <version>1.0.2</version>
     </parent>
     <artifactId>custom-stuff-paper</artifactId>
     <packaging>pom</packaging>
```
![image](https://user-images.githubusercontent.com/7693005/99154470-15ba3300-26c1-11eb-964f-dec721799612.png)
</details>

<details>
<summary>`custom-stuff-paper-lib/pom.xml` (unchanged by Dependabot)</summary>

![image](https://user-images.githubusercontent.com/7693005/99154497-400bf080-26c1-11eb-92c2-1b6f361f9ffc.png)
</details>

<details>
<summary>`custom-stuff-paper-plugin/pom.xml` (unchanged by Dependabot)</summary>

![image](https://user-images.githubusercontent.com/7693005/99154520-7a758d80-26c1-11eb-976a-4bc188e54499.png)
</details>

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

We've shipped a number of fixups to Maven parsing lately, even a couple in the last week.

Additionally, our underlying Maven parsing is all regex/ruby, and we want to long term move to using Maven itself as that's much less brittle. So while we're happy to fix bugs that are currently affecting folks, we're not adding new features and for bugs that aren't currently affecting folks we'd rather invest that energy into figuring out how to switch to Maven long term.

I'm going to close, as I assume this either isn't reproducible or isn't currently affecting you. But if I'm wrong please comment and we can re-open.
