### ISSUE TITLE
XStream bugfix version incorrect

### ISSUE THREAD

**Issue by kappmeier** [dependabot/dependabot-core#2774]
**Package manager/ecosystem**
maven/Java
**Manifest contents prior to update**
https://github.com/zetool/graph/blob/ae9838450e9debe3cc028a8e9bd260fe3a644424/pom.xml

**Updated dependency**
XStream, bugfix release for https://github.com/advisories/GHSA-mw36-7c6c-q4q2

Affected versions are up to and including: `1.4.13` and `1.4.13-java7`.

Fix versions: `1.4.14` and `1.4.14-jdk7`.

**What you expected to see, versus what you actually saw**

Expected to see: PR named `Bump xstream from 1.4.13 to 1.4.14`
What I saw: PR `Bump xstream from 1.4.13 to 1.4.13-java7`

**Images of the diff or a link to the PR, issue or logs**
The actual pull request: https://github.com/zetool/graph/pull/10

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by jeffwidman** [comment]
Closing due to lack of response.
