### ISSUE TITLE
Dependabot encountered an unknown error.

### ISSUE THREAD

**Issue by lucemia** [dependabot/dependabot-core#2792]
**Package manager/ecosystem**

python

**Manifest contents prior to update**

a requirements file contains numpy

**Updated dependency**

**What you expected to see, versus what you actually saw**

The Dependabot didn't work in my private repo recently. It continuously reports `Dependabot encountered an unknown error.`
The log shows an error related to numpy installation. 

> updater | <job_70741028> pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/.pyenv/versions/3.9.0/bin/python3.9 /usr/local/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9g2gbo23/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://gliacloud:cookiebank@pypi-dot-living-bio.appspot.com/pypi --extra-index-url https://gliacloud:cookiebank@pypi-dot-living-bio.appspot.com/pypi -- 'cython >= 0.29' 'numpy==1.14.5; python_version<'"'"'3.7'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"'' setuptools setuptools_scm wheel Check the logs for full command output.

- It looks like the error is related to install numpy in python3.9. Since python3.9 is new. https://pythonspeed.com/articles/switch-python-3.9/. Is there a way to tell dependabot use older python version?
- Tools like pip-tools can check dependencies without actually install these packages. Why Dependabot choose to install these dependencies while check update?

**Images of the diff or a link to the PR, issue or logs**

**Comment by Czaki** [comment]
I meet the same error. In my project, I use packages that do not support Python 3.9 yet. 

I found #1455 which suggests using the `.python-version` file But this file is already used by pyenv.

@feelepxyz I still cannot find the documentation which you mentioned in this Issue. 

It is possible to use a different name for this file, allow to define it in the `.github` folder, allow to define it in yaml file, or downgrade the default python version?

**Comment by feelepxyz** [comment]
Pretty sure this is caused by numpy not being having any wheels published for the given python version. Dependabot runs `pip-compile` and installs the dependency to make sure the version is resolvable.

@jurre might this be fixed by https://github.com/dependabot/dependabot-core/pull/2815 ?

@Czaki just to clarify, do you not use pyenv so don't want to use `.python-version`?

dependabot-core has some logic to guess your python version here: https://github.com/dependabot/dependabot-core/blob/00f0e52b630af6d55318951e8cb21a9a32eabbb7/python%2Flib%2Fdependabot%2Fpython%2Ffile_parser%2Fpython_requirement_parser.rb#L22-L26

**Comment by Czaki** [comment]
> @Czaki just to clarify, do you not use pyenv so don't want to use `.python-version`?

I use pyenv and I have separated environments for each project which has semantic means which will be not correctly parsed by dependable. Also sometimes there are different names of environments on different computers. So in all of my projects, I exclude .pyenv file in .gitignore to not create chaos.

**Comment by jurre** [comment]
> Pretty sure this is caused by numpy not being having any wheels published for the given python version. Dependabot runs `pip-compile` and installs the dependency to make sure the version is resolvable.
> 
> @jurre might this be fixed by #2815 ?

Yes, I think it would

**Comment by lucemia** [comment]
The issue is fixed
