### ISSUE TITLE
How to access Dependabot after hosting Dependabot locally using Docker concept

### ISSUE THREAD

**Issue by c86amik** [dependabot/dependabot-core#2810]
Hi Team,

I have successfully run the Dependabot Docker image (dependabot-core-development) by running the Dockerfile.development in Oracle Linux Machine. But after the image ran successfully, I am not able to access Dependabot.
My requirement is I want to access it and then I want to add my organization's GitHub repository with it.

Please help me with this.

**Comment by feelepxyz** [comment]
> I am not able to access Dependabot

@c86amik not sure I follow, if you self host you'll need to run everything yourself and there's no way to self-host a runner for Dependabot like you can do with github actions.

You can set up dependabot using the config file if you want to use the hosted version: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

**Comment by yeikel** [comment]
@feelepxyz Do you have any plans to add support to authenticate as a bot? 

At the moment, the tokens it generates are attached to a username so when we see the pull requests

It would be nice to deploy our own bots and authenticate using their credentials
