### ISSUE TITLE
Don't connect to central maven when repositories are configured in pom.xml

### ISSUE THREAD

**Issue by ilam-natarajan** [dependabot/dependabot-core#2834]
**Package manager/ecosystem**
maven
**Manifest contents prior to update**
any pom.xml with internal repositories
**Updated dependency**
any
**What you expected to see, versus what you actually saw**

In enterprise environment, the connection to central maven could be blocked. In this case, 
i) either don't connect to central maven at all
ii) or if the connection to central maven is not successful, don't raise exception, just move on to other repositories

currently i see below exception

```
/vendor/ruby/2.6.0/gems/excon-0.76.0/lib/excon/socket.rb:285:in `select_with_timeout': connect_write timeout reached (Excon::Error::Timeout)
	
```

please correct me if i'm wrong

**Comment by ilam-natarajan** [comment]
I have found a workaround to avoid this problem. And after looking into the dependabot code, I think this behaviour is by design and will never be modified. so closing this.

**Comment by patrickdronk** [comment]
@ilam-natarajan Could you share your workaround?
