### ISSUE TITLE
Secure updates for GitHub Actions (and more)

### ISSUE THREAD

**Issue by TriplEight** [dependabot/dependabot-core#2835]
We've decided to follow the GitHub's example and best practice: updating the Actions we're using in a less blind but still somehow automated manner. That's for security purposes.

- Instead of ~Semver or even exact versions, pin the action to the [commit SHA of the suitable release](https://github.com/github/docs/blob/main/.github/workflows/triage-issue-comments.yml#L37).
- [whitelist](https://github.com/github/docs/blob/main/.github/allowed-actions.js) these commits
- subscribe to the certain repos, gather their updates or changelogs via rssbot, make the weighted decision about each update, here something like changelog summary would be a great help, cc https://github.com/dependabot/dependabot-core/issues/2635

Can Dependabot currently help with something from this list?

**Comment by willnorris** [comment]
We similarly use commit SHA for actions in google/go-github, and dependabot now seems to support that (using SHAs in updates): https://github.com/google/go-github/pull/2049

One additional think we do, however, is to leave a comment for what release that SHA corresponds to (similar to what github/docs is doing [in their allowlist](https://github.com/github/docs/blob/main/.github/allowed-actions.js)).  It would be really nice if dependabot supported that and would bump the version in the comment.  For now, we're just doing it manually in the PR (like in the example above)

**Comment by timmeinerzhagen** [comment]
Would love to see sha comment adjustments in Dependabot natively. 

For the meantime I wrote an action [timmeinerzhagen/dependabot-sha-comment-action](https://github.com/timmeinerzhagen/dependabot-sha-comment-action) that does the trick for me

**Comment by npalm** [comment]
An alternative to this limitation of dependabot could be https://github.com/sethvargo/ratchet

**Comment by npalm** [comment]
Any updates on plans or roadmap of dependabot to support updating based on SHA instead of semver?

**Comment by TriplEight** [comment]
@npalm 

> Any updates on plans or roadmap of dependabot to support updating based on SHA instead of semver?

[Evidently](https://github.com/google/go-github/pull/2331/files), it does, but as @willnorris mentioned, for the readability a human should update [comment](https://github.com/google/go-github/pull/2331/commits) with an actual version.

**Comment by willnorris** [comment]
Oh, that would be fantastic if that's the case!  Do you have an example?

**Comment by kuhnroyal** [comment]
Only in internal repositories.
<img width="771" alt="Bildschirmfoto 2022-11-09 um 17 04 06" src="https://user-images.githubusercontent.com/1260818/200880129-db8085b5-cc22-48a5-b91c-b55c48bfa6a0.png">

**Comment by deivid-rodriguez** [comment]
Yes, this was [recently contributed](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/) by the community! 🎉

Closing this since it's now fixed!
