### ISSUE TITLE
Open PR for specific release type (patch|minor|major)

### ISSUE THREAD

**Issue by mittalyashu** [dependabot/dependabot-core#2845]
Dependabot opens a new PR for any package when there is a bump in version number regardless its a patch, minor or major release.

It will be helpful to limit the number of PRs, by specifying the release type. Using `schedule.interval` or `open-pull-requests-limit` doesn't give that much control over the type of PR dependabot creates.

This idea might no against security patch fix, maybe by-default it can ignores the configuration in case for security PR.

**Comment by mairaw** [comment]
I'd love to see this implemented.

**Comment by feelepxyz** [comment]
Closing as a duplicate of #2219
