### ISSUE TITLE
[Security Update] Dependabot filters vulnerable versions incorrectly

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#2846]
**Issue**
While filtering the vulnerable versions for a given security advisory, dependabot checks whether any of the vulnerable version criteria is met and if yes it declares the version as `vulnerable` (Code reference: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb#L134). 

Taking an example for security vulnerability data for `dot-prop` dependency on github (link:https://github.com/advisories/GHSA-ff7x-qrg7-qggm)
 
The following 2 are the security advisories created from the github security advisory data -

1. Vulnerable version range : >=5.0.0 and <5.1.1 , patched version: 5.1.1
2. Vulnerable version range: <4.2.1 . patched version: 4.2.1

So if `dot-prop` is a `subdependency` at version `4.2.0` with semver constraints as `^4.2.0`, ideally the least secure version should be `4.2.1`(given the above data), but following dependabot-core's logic since 4.2.1 does meet the vulnerable version criterion individually for the first security advisory(Code reference:https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/security_advisory.rb#L32), it declares the version 4.2.1 as vulnerable and removes it from the set of secure versions and returns the least security fix version as `5.1.1`. 

@jurre Is this the expected behaviour?

**Comment by jurre** [comment]
Do you happen to have an example repo that I could run this against?

**Comment by milind009** [comment]
I have created this sample repo: https://github.com/milind009/DependabotTestRepo. I have added dot-prop as a subdependency have a vulnerable version

**Comment by milind009** [comment]
I have created this sample repo: https://github.com/milind009/DependabotTestRepo and added the above dependency as a subdependency with the same vulnerable version

**Comment by milind009** [comment]
I also wanted to add that currently the way we pass the vulnerable versions while creating the security advisory object is like
suppose the vulnerability information is '>= 5.0.0 , < 5.1.1'(as obtained from github security advisory datasource), we split the string at the ','(comma character) and pass the array as vulnerable versions array to the security advisory object. 
So the vulnerable versions array for security advisory object would look like: ['>= 5.0.0' , '< 5.1.1']. I think this could be the issue on our side. I was looking at the dependabot-core code and saw that while creating the requirements for the security advisory data it expects the vulnerable version range to be joined by an '&'(like '>=5.0.0 & <5.1.1') character to treat the constraints together and not separately. I'm still trying to validate this but this seems like the issue that is causing the unexpected behaviour

**Comment by GiriB** [comment]
@jurre FYI. As Milind described above this could be an error on how we pass the vulnerable range to dependabot-core. Apologies if you already spent some time on this. Let us get back to you once we validate. Feel free to close this issue if the right way to pass ranges is like `'>=5.0.0 & <5.1.1'` and not ['>= 5.0.0' , '< 5.1.1']

**Comment by milind009** [comment]
We can close this. I was able to verify using the `&` and it worked as expected. Once again, Apologies if you had to spend time on this
