### ISSUE TITLE
Slashes in branch names break container build

### ISSUE THREAD

**Issue by Morriz** [dependabot/dependabot-core#2850]
**What you expected to see, versus what you actually saw**

Our pipeline to not break upon dependabot PR.

Since probably more than half of the dev world is building image(s) by now in their pipelines, I would expect dependabot to NOT create branch names that don't translate to image tags. How unvisionary is that?

Seeing this involves probably just replacing slashes with either underscore(s) or dash(es) I am hoping this will be a quick and easy fix here. Offering the configuration to replace these slashes (with underscore as default, as it makes most sense IMO) would be nice.

**Comment by feelepxyz** [comment]
@Morriz you can configure the branch name separator using the config file: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#pull-request-branch-nameseparator

Sorry for the slow response!

**Comment by Morriz** [comment]
Well, I instructed the team already to only create meaningful branch names adhering to [a-z]+[a-z-]+ now, since we still would have to come up with identical rewrite logic for retagging. Plus we don't want long living branch names anyway ;)
