### ISSUE TITLE
Can I host dependabot in my workplace to update dependencies?

### ISSUE THREAD

**Issue by ilam-natarajan** [dependabot/dependabot-core#2862]
In [Readme](https://github.com/dependabot/dependabot-core#license) , I see

```
If you would like to use Dependabot Core in a non-commercial capacity, such as to host a bot at your workplace, then we give you full permission to do so. In fact, we'd love you to and will help and support you however we can.
```

but in [License](https://github.com/dependabot/dependabot-core/blob/main/LICENSE) , I see

```
You must limit use of this software in any manner primarily
   intended for or directed toward commercial advantage or
   private monetary compensation to a trial period of 32
   consecutive calendar days. This limit does not apply to use in
   developing feedback, modifications, or extensions that you
   contribute back to those giving this license.
```

So I am puzzled if hosting the bot in workplace is allowed or not.  Or is it just me misinterpreting the license
Can you please clarify.

**Comment by jurre** [comment]
Yes, that's fine. You can't offer it as a service to third parties, but running internally is 👍

**Comment by ilam-natarajan** [comment]
@jurre Thanks a lot for the clarification.

**Comment by jeffwidman** [comment]
See also https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100
