### ISSUE TITLE
Missing keyword using_bundler_2

### ISSUE THREAD

**Issue by zhaomengru2015** [dependabot/dependabot-core#2879]
When I  used `dependabot/dependabot-core` v0.126.1 to update ruby dependencies, I got `missing keyword: using_bundler_2` error. But it works well in v0.125.6.

**Comment by jurre** [comment]
Could you give us a bit more context on how you're using dependabot-core, where you're seeing this error and what you've already tried to fix it so far?

**Comment by zhaomengru2015** [comment]
we are using dependabot in Github Enterprise, since it didn't support Github Enterprise yet, we've implemented our own dependabot to update dependencies. It used the dependabot-core as the base image. recently we've upgraded the dependabot-core from 0.125.6 to 0.126.1 and all ruby dependencies were failed to update. So we temporarily downgraded our dependabot-core to 0.125.6 and the problem fixed

**Comment by zhaomengru2015** [comment]
could it be caused by we were using bundler v1?

**Comment by jurre** [comment]
No, bundler v1 should work fine. I would really need to see your code and a stacktrace of the error etc to be able to help here.

**Comment by feelepxyz** [comment]
Are you running it inside the core docker container? This needs to be updated aswell.

**Comment by feelepxyz** [comment]
Closing as stale
