### ISSUE TITLE
Use "Update Branch" instead of force pushing a rebase

### ISSUE THREAD

**Issue by isouza-daitan** [dependabot/dependabot-core#2882]
When dependabot detects that the base branch of a PR has changed, it does a rebase and force pushes the changes to the PR. This causes any PR reviews to be dismissed and developers need to re-approve it. It is not a big burden for a single PR but gets significantly worse when you have 3 or more PRs open and each merge requires re-approval.

I know the automatic rebase can be disabled but would it be possible to do a clean merge from the base branch, similar to what the "Update Branch" button does? 

![Screenshot from 2020-12-17 13-28-53](https://user-images.githubusercontent.com/9718970/102515734-ddfe2c80-406c-11eb-9e79-44aaa60f3413.png)

The "Update Branch" feature does not dismiss reviews and would not require the re-approval of PRs.

**Comment by jurre** [comment]
It's not really possible with how Dependabot works currently, what we call a "rebase", is actually just running the update again against the target branch. We don't preserve the commit history between runs. If we were to do what the "Update branch" button attempts to do, we'd have to actually figure out how to cleanly merge changes, and especially in the case of lockfiles, the chances of running into conflicts are very large.
