### ISSUE TITLE
fetching repos returns 500

### ISSUE THREAD

**Issue by kramuenke** [dependabot/dependabot-core#2884]
Hi dependabot team,

When using the dependabot UI, the XHRs fetching the repos for an account are failing with a 500

<img width="1557" alt="Screen Shot 2020-12-18 at 10 02 33 am" src="https://user-images.githubusercontent.com/469886/102554494-14918100-4119-11eb-82b7-1bc2a5d3afed.png">

**Comment by jurre** [comment]
Hi, could you maybe share the account name or ID this is happening for? If you'd prefer not to share this publicly feel free to open a support ticket with GitHub support.

**Comment by kramuenke** [comment]
Thanks jurre,

i'll raise a support ticket

**Comment by jurre** [comment]
Thanks @kramuenke, I'm going to close out this issue in that case and we'll follow up via support 👍
