### ISSUE TITLE
Dependabot-bundler does not include helpers with the packaged gem

### ISSUE THREAD

**Issue by rasthana** [dependabot/dependabot-core#2885]
**Package manager/ecosystem**
bundler

**What you expected to see, versus what you actually saw**
`dependabot-bundler` fails to parse the gemfile from [here](https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/file_parser.rb#L111). It appears that [NativeHelpers](https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/file_parser.rb#L111) was added on https://github.com/dependabot/dependabot-core/commit/c4fed9553d86f013c5ec7408a547e8f4c85cb7f4 however the `.gemspec` was not updated to include the supported files in the packaged gem.

<img width="964" alt="Screen Shot 2020-12-17 at 5 06 53 PM" src="https://user-images.githubusercontent.com/1459185/102554400-62ab7380-408a-11eb-9ced-ab39bd86574b.png">

**Comment by jurre** [comment]
Thanks for reporting this @rasthana, I wonder if this is actually also an issue for other ecosystems that rely on native helpers (npm_and_yarn, python, go modules). We'll look into it, but not sure if I can make it happen before the holidays.

The easiest way to resolve this for now would be to use the dependabot docker container, it installs any dependencies needed, but it's quite a heavy-weight solution.

**Comment by rasthana** [comment]
@jurre Thanks for the feedback. I noticed that `npm_and_yarn` packaging was working as intended, i'm assuming due to: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/dependabot-npm_and_yarn.gemspec#L35-L38

**Comment by jurre** [comment]
Ah yes! I think we can basically do the same thing for bundles, will try to get that out today or tomorrow
