### ISSUE TITLE
Update used pipenv version

### ISSUE THREAD

**Issue by and-semakin** [dependabot/dependabot-core#2888]
At the moment, `dependabot` uses really old `pipenv==2018.11.26`. After this release, `pipenv` has changed the format of `Pipfile.lock` a little bit (they added some new fields). I use more recent versions of `pipenv`, and my lock-file is already converted to the new format. When `dependabot` tries to update dependencies with its old `pipenv`, it removes all the new fields (converts lock-file back to the old format), which is really annoying. It causes large useless diffs in PRs from `dependabot`.

`dependabot` tries to update parts of itself, but it definitely needs some human help in this task. Let's track the efforts of upgrading `pipenv` in this issue.

**Comment by and-semakin** [comment]
All the PRs where `dependabot` unsuccessfully tried to update `pipenv`:
* `2020.5.28` https://github.com/dependabot/dependabot-core/pull/1885
* `2020.6.2` https://github.com/dependabot/dependabot-core/pull/1893
* `2020.8.13` https://github.com/dependabot/dependabot-core/pull/2451
* `2020.11.4` https://github.com/dependabot/dependabot-core/pull/2723
* `2020.11.15` https://github.com/dependabot/dependabot-core/pull/2764

**Comment by and-semakin** [comment]
Looks like folks are working hard here: https://github.com/dependabot/dependabot-core/pull/3817

**Comment by jurre** [comment]
Yep, this should be out later today

**Comment by jurre** [comment]
Should be available now
