### ISSUE TITLE
Add top-level `additional-labels` array

### ISSUE THREAD

**Issue by dfreilich** [dependabot/dependabot-core#2902]
### Description
I've had a number of times where I am happy with the default labels dependabot sets, but I would like to add one in addition. For instance, we label our PRs `type/chore` to take advantage of some built in release notes formatting. Currently, the way I can get dependabot to add them in addition to the current labels (to help with differentiation and searching) is by setting:
```
    labels:
      - "dependencies"
      - <dependancy type>
      - "type/chore"
```

### Solution
A top-level key `additional-labels` would be helpful, enabling me to just write:
```
version: 2
...
additional-labels:
 - "type/chore"
 ```

**Comment by asciimike** [comment]
Since we just released it and I'm shamelessly pushing for it, would https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs#labelling provide the functionality you're looking for? It should add labels to all Dependabot PRs, or any subset you want based on the type, etc.

**Comment by jeffwidman** [comment]
Closing due to lack of user response. ☝️ should address what you need.
