### ISSUE TITLE
Dependabot is not fetching the latest version of a dependency from repo.maven.apache.org

### ISSUE THREAD

**Issue by odin-delrio** [dependabot/dependabot-core#2926]
**Package manager/ecosystem**
`java:gradle`

**Manifest contents prior to update**
`build.gradle.kts`

**Updated dependency**
`org.springframework.cloud:spring-cloud-dependencies `

**What you expected to see, versus what you actually saw**
When checking in  [repo.maven.apache.org](https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml), dependabot should determine that the latest version is `2020.0.0`, released on `2020-12-22`, 7 days ago as the time of writing this (2020-12-29).

**Images of the diff or a link to the PR, issue or logs**
Dependabot logs state that the latest version is still `Hoxton.SR9`, when according to https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml it's not true (that maven link is exactly the one dependabot says it is using, see logs below):

![image](https://user-images.githubusercontent.com/9112748/103279347-dc6a2800-49cd-11eb-9d1e-6e3ffe6198f5.png)

Dependabot logs from today (2020-12-29):
```
updater | INFO <job_79275963> Checking if org.springframework.cloud:spring-cloud-dependencies Hoxton.SR9 needs updating
  proxy | 2020/12/29 07:06:04 [038] GET https://repo.maven.apache.org:443/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml
  proxy | 2020/12/29 07:06:04 [038] 200 https://repo.maven.apache.org:443/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml
updater | INFO <job_79275963> Latest version is Hoxton.SR9
updater | INFO <job_79275963> No update needed for org.springframework.cloud:spring-cloud-dependencies Hoxton.SR9
```

Note, if needed, I can tell you in which repository I'm experiencing this, but it's a private one.

**Comment by odin-delrio** [comment]
Update: I updated manually the library to the `2020.0.0`, immediately after merge I pressed the "check for updates" button and got this:

``` 
updater | INFO <job_79456388> Checking if org.springframework.cloud:spring-cloud-dependencies 2020.0.0 needs updating
  proxy | 2020/12/30 23:32:18 [032] GET https://repo.maven.apache.org:443/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml
  proxy | 2020/12/30 23:32:18 [032] 200 https://repo.maven.apache.org:443/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml
updater | INFO <job_79456388> Latest version is 2020.0.0
updater | INFO <job_79456388> No update needed for org.springframework.cloud:spring-cloud-dependencies 2020.0.0
```

My feeling is that at least my builds were hitting some kind of cache.

**Comment by jeffwidman** [comment]
Closing as this unfortunately is old enough that we don't have all the necessary logs to figure out exactly what happened. My guess is the job queue got stuck somehow for a bit. Anyway, if you see it happen again, please file an issue and we'll try to get to it quicker to understand what specifically is breaking.
