### ISSUE TITLE
Pull-request header is outdated when dependency has been upgraded in the mean time

### ISSUE THREAD

**Issue by davidkarlsen** [dependabot/dependabot-core#2930]
**Package manager/ecosystem**
golang modules

See example in - the header is misleading since the module has been upgraded to 0.20 in the mean time, so the PR is really about 0.20.0 -> 0.20.1, not 0.18.8

https://github.com/evryfs/github-actions-runner-operator/pull/132

**Comment by jeffwidman** [comment]
Thanks for reporting. Unfortunately, this ticket is really old, and the relevant job logs etc aren't around anymore for us to debug what happened in this specific case. If you see it happen again, please file another issue and we'll try to jump on it faster to debug what specifically happened.
