### ISSUE TITLE
Do not consider trailing space for length for commit message prefix

### ISSUE THREAD

**Issue by MasterOdin** [dependabot/dependabot-core#2934]
For a repo I work in, we use the development prefix `[DevDependency]` which is exactly 15 characters long. To get the semi-colon to not appear after the prefix, I added a space to it, but that then causes dependabot to throw a configuration warning about `[DevDependency] ` on being too long (16 characters). Given this line:

https://github.com/dependabot/dependabot-core/blob/c39763e26335075c44b72ebd58db6cb12f384fdc/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L79

where if the prefix ends with a space, the prefixer than omits the space it was going to use, I would ask that the last character, if it is a trailing space, be omitted from the character count limit, especially given the bonus of that space disabling the semi-colon.

**Comment by navneet0693** [comment]
@MasterOdin I am running into something similar, would it possible for pointing me where exactly is this "15 characters" max length is decided or declared? Is it possible to configure it?

**Comment by jeffwidman** [comment]
The commit message prefix length was increased from 15 characters to 50 characters in November of 2022.

That should give you enough space to have trailing space. 😁
