### ISSUE TITLE
Dependabot cannot update node-notifier to a non-vulnerable version 

### ISSUE THREAD

**Issue by AlCalzone** [dependabot/dependabot-core#2935]
**Package manager/ecosystem** javascript/yarn

**Manifest contents prior to update** https://github.com/zwave-js/node-zwave-js/blob/31f21271c69a5db89b171494d8a06c8afba2d9a1/yarn.lock#L1385
```
  optionalDependencies:
    node-notifier "^8.0.0"
```

**Updated dependency**  
Dependabot cannot update for some reason

**What you expected to see, versus what you actually saw**
No update, although 8.0.1 is available in the registry and would satisfy the current caret version range `^8.0.0`.

**Images of the diff or a link to the PR, issue or logs**
https://github.com/zwave-js/node-zwave-js/security/dependabot/yarn.lock/node-notifier/open/update-logs/69532680
```
updater | INFO <job_80240711> Starting job processing
updater | INFO <job_80240711> Starting update job for zwave-js/node-zwave-js
updater | INFO <job_80240711> Checking if node-notifier 8.0.0 needs updating
  proxy | 2021/01/02 10:32:15 [054] GET https://registry.npmjs.org:443/node-notifier
  proxy | 2021/01/02 10:32:15 [054] 200 https://registry.npmjs.org:443/node-notifier
  proxy | 2021/01/02 10:32:15 [056] GET https://registry.npmjs.org:443/node-notifier/9.0.0
  proxy | 2021/01/02 10:32:15 [056] 200 https://registry.npmjs.org:443/node-notifier/9.0.0
updater | INFO <job_80240711> Latest version is 9.0.0
updater | INFO <job_80240711> Requirements to unlock update_not_possible
updater | INFO <job_80240711> Requirements update strategy widen_ranges
  proxy | 2021/01/02 10:32:21 [058] GET https://registry.npmjs.org:443/node-notifier/8.0.1
  proxy | 2021/01/02 10:32:21 [058] 200 https://registry.npmjs.org:443/node-notifier/8.0.1
updater | INFO <job_80240711> The latest possible version of node-notifier that can be installed is 8.0.0
updater | INFO <job_80240711> The earliest fixed version is 8.0.1.
updater | INFO <job_80240711> Finished job processing
```
![grafik](https://user-images.githubusercontent.com/17641229/103455624-f027ce00-4cee-11eb-954a-c6e1abd21fb5.png)

**Comment by Standard8** [comment]
I'm having this issue as well:

```
updater | INFO <job_193310464> Checking if path-parse 1.0.6 needs updating
  proxy | 2021/09/01 21:50:22 [016] GET https://registry.npmjs.org:443/path-parse
  proxy | 2021/09/01 21:50:23 [016] 200 https://registry.npmjs.org:443/path-parse
  proxy | 2021/09/01 21:50:23 [018] GET https://registry.npmjs.org:443/path-parse/1.0.7
updater | INFO <job_193310464> Latest version is 1.0.7
  proxy | 2021/09/01 21:50:23 [018] 200 https://registry.npmjs.org:443/path-parse/1.0.7
updater | INFO <job_193310464> Requirements to unlock update_not_possible
updater | INFO <job_193310464> Requirements update strategy bump_versions
updater | INFO <job_193310464> The latest possible version of path-parse that can be installed is 1.0.6
updater | INFO <job_193310464> The earliest fixed version is 1.0.7.
```

In `package-lock.json`:

```
    "resolve": {
      "version": "1.20.0",
      "resolved": "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz",
      "integrity": "sha512-wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==",
      "dev": true,
      "requires": {
        "is-core-module": "^2.2.0",
        "path-parse": "^1.0.6"
      }
    },
```

There's no reason that shouldn't be able to be updated. This has happened for several modules in the same repository, and "Create Dependabot security update" doesn't seem to do anything.

**Comment by jeffwidman** [comment]
👋 Are you still seeing this?

We shipped a lot of improvements this past year to fix many of the various root causes hiding behind the `update_not_possible` error for the `npm` ecosystem.

**Comment by jeffwidman** [comment]
Closing due to lack of user response.

Also, you can see in the logs that Dependabot realized there was a newer version available, but then wasn't able to update to it so threw the `update_not_possible` error. Most likely there was another constraint in your dep graph that prevented the bump... but as I mentioned ☝️ we were able to fix a number of those for the `npm` ecosystem with some work over the past year.
