### ISSUE TITLE
high severity PRs did not tag `security`  tag

### ISSUE THREAD

**Issue by chenrui333** [dependabot/dependabot-core#2944]
For example like this one, `https://github.com/mav1283/javascript30-day-four/pull/7` 

![image](https://user-images.githubusercontent.com/1580956/103604268-8cfc8e00-4ede-11eb-82db-90476921b103.png)
![image](https://user-images.githubusercontent.com/1580956/103604333-bf0df000-4ede-11eb-9aa7-e57b51cf5711.png)

**Comment by feelepxyz** [comment]
@chenrui333 this is by design, the github-native version doesn't add a `security` tag to the pull request and instead shows a link to the security alert from the pull request header to repo/security admins.

**Comment by chenrui333** [comment]
I see, thanks for clarifying it.
