### ISSUE TITLE
JSON Output

### ISSUE THREAD

**Issue by yasin-amadmia-mck** [dependabot/dependabot-core#2947]
Hi,
I was wondering if it would be useful to have `dependabot-core` simply output (in JSON or other format) the outcome of the scans rather than raising a PR ?

This could be more useful for CI related workflows whereby one may simply want to log the findings and not necessarily raise any PR.

**Comment by jurre** [comment]
I think you should be able to do this with https://github.com/dependabot/dependabot-script, and getting rid of the ` Dependabot::PullRequestCreator` and serializing the `updater.updated_dependency_files` into JSON. The dry-run script included in core should also point you somewhat in this direction, in that case we print the results to stdout in plain text, but it should be possible to build a JSON that way as well.

**Comment by jeffwidman** [comment]
You could also accomplish this by hacking on [the Dependabot CLI](https://github.com/dependabot/cli/#dependabot-update) a little... it emits YAML, but wouldn't be hard to make it emit JSON instead.
