### ISSUE TITLE
Custom artifactory for Github Native Dependabot

### ISSUE THREAD

**Issue by skjindal93** [dependabot/dependabot-core#2948]
I am trying to setup dependabot in one of my private repository via Github native method. There are some public dependencies in my private repository which are not hosted at Maven Central, but has a separate custom path.

How do I specify a custom artifactory path in my `.github/dependabot.yml` so that it's is able to fetch the artifactories from the custom artifactory path as well?

I wasn't able to find a way to do that in the Github native dependabot docs.

**Comment by jurre** [comment]
This is not yet supported in the GitHub native version, but it's coming soon. Until then, I'd recommend you use https://dependabot.com

**Comment by TwoAbove** [comment]
Hey @jurre 
Sorry for opening an old issue, but are there any timelines on implementing this? I couldn't find anything on this
