### ISSUE TITLE
"Illformed requirement" error when using `Gem::Requirement` for `spec.required_ruby_version`

### ISSUE THREAD

**Issue by ybiquitous** [dependabot/dependabot-core#2963]
**Package manager/ecosystem**
ruby:bundler

**Manifest contents prior to update**
`*.gemspec` file

**Updated dependency**
All Ruby gems in my project

**What you expected to see, versus what you actually saw**
I have a `*.gemspec` file including the following `spec.required_ruby_version`:

```ruby
spec.required_ruby_version = Gem::Requirement.new(">= 2.7.2", "< 3.0.0")
```

https://github.com/sider/runners/blob/495a312a369dd34bf227211fa40b60e559753ac4/runners.gemspec#L15

This is a valid specifier, but Dependabot does not seem to parse it. 😢 

For example, the latest version of Bundler generates a `*.gemspec` file including `Gem::Requirement`:

```console
$ bundle -v
Bundler version 2.2.4

$ bundle gem foo
...
Gem 'foo' was successfully created. For more information on making a RubyGem visit https://bundler.io/guides/creating_gem.html

$ grep required_ruby_version foo/foo.gemspec
  spec.required_ruby_version = Gem::Requirement.new(">= 2.3.0")
```

**Images of the diff or a link to the PR, issue or logs**
The following is a part of the log in <https://github.com/sider/runners/network/updates/80287287>:

```
updater | ERROR <job_80287287> Illformed requirement [#<Gem::Requirement:0x0000556ac7d92ab0 @requirements=[[">=", #<Gem::Version "2.7.2">], ["<", #<Gem::Version "3.0.0">]]>]
updater | ERROR <job_80287287> /usr/lib/ruby/2.6.0/rubygems/requirement.rb:105:in `parse'
updater | ERROR <job_80287287> /usr/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `block in initialize'
updater | ERROR <job_80287287> /usr/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `map!'
updater | ERROR <job_80287287> /usr/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `initialize'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:52:in `new'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:52:in `ruby_version'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:34:in `rewrite'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker/file_preparer.rb:254:in `block in lock_ruby_version'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker/file_preparer.rb:252:in `each'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker/file_preparer.rb:252:in `lock_ruby_version'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker/file_preparer.rb:170:in `gemfile_content_for_update_check'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker/file_preparer.rb:61:in `prepared_dependency_files'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker.rb:402:in `prepared_dependency_files'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker.rb:377:in `latest_version_finder'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker.rb:197:in `latest_version_details'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.5/lib/dependabot/bundler/update_checker.rb:21:in `latest_version'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:446:in `log_checking_for_update'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:177:in `check_and_create_pull_request'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:68:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `block in run'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `each'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `run'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_80287287> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_80287287> bin/update_files.rb:21:in `<main>'
```

https://github.com/dependabot/dependabot-core/blob/f6809298e1a0d15f52bd5aff0f6d0be77113b8d0/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb#L52

**Comment by ybiquitous** [comment]
I think using `Gem::Requirement.create` instead of `Gem::Requirement.new` should fix this problem as follows.

The `Gem::Requirement.create` factory method can receive not only `String` but also a `Gem::Requirement` instance.
See also <https://ruby-doc.org/stdlib-2.6.6/libdoc/rubygems/rdoc/Gem/Requirement.html#method-c-create>.

```diff
diff --git a/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb b/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
index 90666c13b..c18767034 100644
--- a/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
+++ b/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
@@ -49,7 +49,7 @@ module Dependabot
         end
 
         def ruby_version
-          requirement = Gem::Requirement.new(ruby_requirement)
+          requirement = Gem::Requirement.create(ruby_requirement)
 
           ruby_version =
             RUBY_VERSIONS.
```

**Comment by ybiquitous** [comment]
Perhaps, the following may be a workaround:

```diff
-spec.required_ruby_version = Gem::Requirement.new(">= 2.7.2", "< 3.0.0")
+spec.required_ruby_version = [">= 2.7.2", "< 3.0.0"]
```

**Comment by feelepxyz** [comment]
> ```diff
> ```diff
> +spec.required_ruby_version = [">= 2.7.2", "< 3.0.0"]
> ```
> 
> 
>       
> ```

@ybiquitous nice one, I think that's the recommend syntax. I haven't seen any examples where the `required_ruby_version` is already initialized as a Gem::Requirement, can you point me to some examples/docs for this? 

We'll still need to upgrade bundler in dependabot-core to support your project. We're planning to do this in the next month or so.

**Comment by ybiquitous** [comment]
@feelepxyz Thanks for the feedback! 😄 

Surely, I cannot find the use of `Gem::Requirement` on the gemspec document:
<https://guides.rubygems.org/specification-reference/#required_ruby_version=>

But the [`bundle gem`](https://bundler.io/v2.2/man/bundle-gem.1.html) command creates a gemspec file template including `Gem::Requirement`. See below:

```console
$ bundle -v
Bundler version 2.2.5

$ bundle gem foo
Creating gem 'foo'...
(...omitted...)
Gem 'foo' was successfully created. For more information on making a RubyGem visit https://bundler.io/guides/creating_gem.html

$ grep -C3 required_ruby_version foo/foo.gemspec
  spec.description   = "TODO: Write a longer description or delete this line."
  spec.homepage      = "TODO: Put your gem's website or public repo URL here."
  spec.license       = "MIT"
  spec.required_ruby_version = Gem::Requirement.new(">= 2.4.0")

  spec.metadata["allowed_push_host"] = "TODO: Set to 'http://mygemserver.com'"

```

See also the Bundler source code:
<https://github.com/rubygems/rubygems/blob/9b50ef6d1a9fedb44b4a0124dc0b4ab64dd980f4/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L17>

---

> We'll still need to upgrade bundler in dependabot-core to support your project. We're planning to do this in the next month or so.

I’m looking forward to the new release supporting Bundler 2, thank you. 😊

**Comment by ybiquitous** [comment]
Hi there,

[Bundler 2.2.18](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.18) now does not output `Gem::Requirement` (rubygems/rubygems#4598)! 🎉 
So, I do not think that we have to address this issue.

Please close this issue if no objections.

**Comment by martijnversluis** [comment]
> Hi there,
> 
> [Bundler 2.2.18](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.18) now does not output `Gem::Requirement` ([rubygems/rubygems#4598](https://github.com/rubygems/rubygems/pull/4598))! 🎉

Thanks for the notice, nice that they solved this!

> So, I do not think that we have to address this issue.
> 
> Please close this issue if no objections.

Hmm I'm not sure, there are quite a number of gems now "in the wild" that still have this version requirement.

Honestly, if the rubygems.org consciously outputs the version as `">= 2.4, < 4"` instead of `[">= 2.4", "< 4"]` then `Gem::Requirement` should support parsing that format.

Besides that, I'm also interested how the SaaS version of Dependabot solves this?

**Comment by feelepxyz** [comment]
> > [Bundler 2.2.18](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.18) now does not output `Gem::Requirement` ([rubygems/rubygems#4598](https://github.com/rubygems/rubygems/pull/4598))! 🎉

Nice! I've also put together a fix for this for existing projects https://github.com/dependabot/dependabot-core/pull/3809

**Comment by ybiquitous** [comment]
@feelepxyz Thank you for fixing it! ❤️
