### ISSUE TITLE
Support for new requirements.txt output from pip-compile

### ISSUE THREAD

**Issue by cancan101** [dependabot/dependabot-core#2976]
As of pip-tools vs 5.5.0, the format of the requirements.txt file generated by pip-compile has changed slightly in that each comment is on its own line. See for example: https://github.com/jazzband/pip-tools/pull/1297#issuecomment-756459866.

This means that when dependabot runs, it generates a huge diff to the requirements.txt file if the checked in file was generated from a newer version of pip-compile.

**Comment by jurre** [comment]
I think https://github.com/dependabot/dependabot-core/pull/2943 should fix this @cancan101

**Comment by jerr0328** [comment]
Now the PR is #2985
