### ISSUE TITLE
Logs output

### ISSUE THREAD

**Issue by y0y0z** [dependabot/dependabot-core#2983]
I love dependency bot, I use it on github and I am extending the my use on it.
Although I follow the official documentation, I couldn't find how can I find the execution log of the dependency bot...

1. Is there a log for the dependency bot when running on github?
2. If there is a log, how can I access it?

**Comment by jurre** [comment]
Thanks for the kind words @y0y0z. If you click on the `Last checked .. ago` link that you see when following [this](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#checking-the-status-of-version-updates) doc, you should be able to see the logs 👍

**Comment by y0y0z** [comment]
@jurre: thank you, much appreciated.
