### ISSUE TITLE
Dependabot didn't detected new buster image with dateversionstring

### ISSUE THREAD

**Issue by sidey79** [dependabot/dependabot-core#2994]
**Package manager/ecosystem** 

docker

**Manifest contents prior to update**

```
ARG BASE_IMAGE="debian"
ARG BASE_IMAGE_TAG="buster-20201209-slim"
FROM --platform=$TARGETPLATFORM ${BASE_IMAGE}:${BASE_IMAGE_TAG}
```

**Updated dependency**

There is a newer version with the tag buster-20210111-slim at docker hub available https://hub.docker.com/_/debian)

from: buster-20201209-slim
to: buster-20210111-slim

I expected that dependabot detects that there is a newer version available

**Comment by divolgin** [comment]
Related to this is #2692.  And we have a similar issue with MinIO tags that also use dates like `RELEASE.2021-04-22T15-44-28Z`.
