### ISSUE TITLE
Wrong type when using the Conventional Commits and GitHub Actions

### ISSUE THREAD

**Issue by felipecrs** [dependabot/dependabot-core#2996]
Dependabot is able to auto-detect the convention for the commit message, such as the Conventional Commits. It properly sends a PR with the commit message like `build(deps): bump...`  for npm packages. However, when using it to upgrade the GitHub Actions dependencies, it also uses the same pattern.

It was supposed to use the `ci` type rather than `build`. This is important because someone configured automatic releases in their repos based on the commit messages, such as `build(deps)`, which indeed upgrades a production dependency.

**Comment by wyardley** [comment]
`build(deps)` should not be triggering, I think?

I've typically seen `fix(deps)` for triggering changes (i.e., to production dependencies), and `chore(deps)` or `build(deps)` for, e.g., dev Dependencies.

**Comment by felipecrs** [comment]
If you are talking about semantic-release: it's configurable.

https://github.com/vscode-shellcheck/vscode-shellcheck/blob/master/release.config.js#L15-L19

**Comment by jojomatik** [comment]
Hi there, I also use dependabot, conventional commits and semantic release.

I use `build(deps):` for updates in production dependencies, this leads to a new minor release in my configuration.

I use `build(deps-dev):` for non production (i.e. development dependencies) such as build tools and linters. These do not trigger a new release.

I've recently enabled dependabot for github actions in some of my repositories. For my configuration I'd need dependabot to decide whether the action is used inside `.github/workflows` or inside a file mentioned in a composite action (like for example [`action.yml`](https://github.com/jojomatik/sync-branch/blob/beta/action.yml) in [jojomatik/sync-branch](https://github.com/jojomatik/sync-branch/)). 

If dependabot only updates workflow files I'd like it to create a `build(deps-dev):` commit (or possibly `ci(deps):` or similar, I think that would be fine to me as well). 

If it actually updates an action file in a composite action I'd need it to create a `build(deps):` commit.

> Currently dependabot is not smart enough to detect different prefixes for different types of updates, but you can configure it to use a fixed prefix for actions, see [our docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message)

@jurre: I don't think splitting between workflows in `.github/workflows` and action files and defining seperate types is not possible right now, is it? I'd like to see both behaviours within one repository (see [jojomatik/sync-branch](https://github.com/jojomatik/sync-branch/)).

Would you accept a PR that tries to automatically differentiate these two cases? Not sure yet how much work that would be and if I have enough time to do so but I might give it a try :)

**Comment by jojomatik** [comment]
> Currently dependabot is not smart enough to detect different prefixes for different types of updates, but you can configure it to use a fixed prefix for actions, see [our docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message)

Another question that I can't really find an answer to in the docs: What exactly does the prefix, does it define the commit type of the conventional commit message? The type and scope? Or does it just switch back to "default" commit messages and prefix that?

**Comment by deivid-rodriguez** [comment]
So, if I understand correctly, there's two separate feature requests here:

* Improve commit message auto-detection to prioritize PRs from the same ecosystem.
* Provide a development vs production distinction for the Github Actions ecosystem.

Both of them seem reasonable to me.

**Comment by jojomatik** [comment]
> So, if I understand correctly, there's two separate feature requests here:
> 
> * Improve commit message auto-detection to prioritize PRs from the same ecosystem.
> * Provide a development vs production distinction for the Github Actions ecosystem.
> 
> Both of them seem reasonable to me.

Thanks for summarsing @deivid-rodriguez!

The second bullet point is exactly what I want 👍 

Are you talking about detecting whether previous commits used `build(deps-dev)` or `ci(deps)`/ `ci(deps-dev)` in the first bullet point? Would that already fulfill your feature request @felipecrs?

**Comment by deivid-rodriguez** [comment]
No problem!

For the second point, actually I'm not really sure it actually works, but my idea is that, since Dependabot style auto-detection first looks on commit messages by Dependabot itself, and looks from newest to oldest, I imagine you should also be able to edit the scope in last Dependabot commit message if you want to change the style going forward. But of course in this case, we don't want to change it for _every_ Dependabot commit, so we'd need some extra feature either in the configuration or in the auto-detection.

**Comment by jojomatik** [comment]
Yeah the first one is definitely more complex.

Should I create a new issue for the second one? Any clue how we'd be able to get the file path in the `production_check` method?

**Comment by deivid-rodriguez** [comment]
Actually I'm not sure which one is more complex 😅. Currently production checks only consider dependency groups, not the file where the dependency is specified, so it requires some extra work to support that.

I think it's worth opening a new ticket for this. This does not only apply to Github Actions. For example, in Ruby libraries, in vision production dependencies are the ones defined in a `.gemspec` file as runtime dependencies, while development dependencies are anything else. So that criteria would also depend on the file where dependencies are defined.

**Comment by jojomatik** [comment]
> I think it's worth opening a new ticket for this. This does not only apply to Github Actions. For example, in Ruby libraries, in vision production dependencies are the ones defined in a `.gemspec` file as runtime dependencies, while development dependencies are anything else. So that criteria would also depend on the file where dependencies are defined.

Created #6057, feedback appreciated.
