### ISSUE TITLE
The docker `update_checker` method; `version_of_latest_tag` can be very slow

### ISSUE THREAD

**Issue by JohannesEH** [dependabot/dependabot-core#2997]
The 'version_of_latest_tag' method in the docker 'update_checker' implementation is really slow when it doesn't match the 'latest' tag digest in the first few tags.

Currently the implementation downloads a list of tags and tries to match the 'latest' tag's digest to another tag's digest by fetching digests one-by-one for all tags in the docker repo (note it short-circuits if a match if found early). The problem is that a single loop of the fetching a digest can take about a second, because it has to fetch an auth token first. Now couple this with a repo containing hundreds of tags, none of which is maching the digest of 'latest' (like dependabot-core), and you have a process taking tens of minutes.

I'm not sure how to deal with this problem though. I've looked at the Docker API, and searched online, to see if I could find a good solution to get a list of tags for a specific digest from a docker repo, but I found nothing.

So at the very least I wanted to raise a flag, of a potential performance bottleneck in the current implementation. Maybe you guys have some ideas on how to make this fster. I mean, maybe its possible to parallelize fetching the digests or something.

Let me know what you think.

**Code ref:** https://github.com/dependabot/dependabot-core/blob/6d2bc8ce93c9efd64f7f1d6359e109ab8703b099/docker/lib/dependabot/docker/update_checker.rb#L158-L171

**Comment by JohannesEH** [comment]
One of the reasons it is so slow is because the docker client is doing this:

1. Do a unauthenticated head request for the manifest which fails with a 401 response
2. From the 401 response get the authentication method and do a token get request
3. Do the same head request as in step one with the bearer token from step 2.

These steps sometimes take up to 750ms to complete, sometimes less. So in the end you are waiting between 100ms - 1500ms just for the two first steps. These steps could be cut from the equation, if the docker regsitry client was a little bit smarter about reusing the bearer token while it is valid. Basically reducing the amount of requests by 2/3. But of course that is work to be done in the 'docker_registry2' project.

**Comment by hfhbd** [comment]
I think I hit the same bug. I run dependabot locally based on https://github.com/dependabot/dependabot-script. It works fine with gradle, bundler and npm, but checking a docker file, dependabot takes 20 minutes. Checking other dependency managers (gradle, bundler) takes on a few seconds, often 10-20. The cpu is idle, but it does a lot of small but slow network request. 
I often get these slow behavior when checking a docker file using dependabot itself.
