### ISSUE TITLE
Continous alerts for non-existing yarn.lock file

### ISSUE THREAD

**Issue by ViggoV** [dependabot/dependabot-core#3008]
My issue is the same as [https://github.com/dependabot/feedback/issues/901](https://github.com/dependabot/feedback/issues/901)

I keep getting alerts for a lockfile that doesn't exist in the given project, specifically `yarn.lock`

**Package manager/ecosystem**
Javascript, NPM, **not** Yarn
**Updated dependency**
Various dependecies, some which also appear in `package-lock.json` and some which don't
**What you expected to see, versus what you actually saw**
I expect not to receive alerts for a non-existing lockfile. I do

**Comment by feelepxyz** [comment]
@ViggoV there's probably an issue with dependency graph caching some old manifest, could you message github support specifying which repo it is? They'll be able to re-set the cache.

https://support.github.com/contact
