### ISSUE TITLE
Composer PR is downgrading plugin-api-version

### ISSUE THREAD

**Issue by freddyheppell** [dependabot/dependabot-core#3023]
**Package manager/ecosystem**
PHP Composer

**Manifest contents prior to update**
https://github.com/projectcitybuild/web/blob/7aa3db697ec89e90c4e77bef53b9e984a0758e66/composer.lock
https://github.com/projectcitybuild/web/blob/7aa3db697ec89e90c4e77bef53b9e984a0758e66/composer.json

**Updated dependency**
laravel/laravel

**What you expected to see, versus what you actually saw**
In the upgraded `composer.lock` file, the `plugin-api-version` was changed from `2.0.0` to `1.1.0`, which I believe means it ran with composer v1 rather than v2. I'd expect this version to remain unchanged. This caused a variety of other changes in the lock file too.

**Images of the diff or a link to the PR, issue or logs**
PR was: projectcitybuild/web#345

Direct link to diff line:
https://github.com/projectcitybuild/web/pull/345/files#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5R10227

**Comment by kasn** [comment]
you require `ext-json` in you [composer.json](https://github.com/projectcitybuild/web/blob/master/composer.json#L12) which currentliy will force dependabot to use composer v1. 

this is supposed to be fixed soon with https://github.com/dependabot/dependabot-core/pull/3004

**Comment by freddyheppell** [comment]
Alright thanks, I'll close this issue then
