### ISSUE TITLE
API Rate Limit exceeded

### ISSUE THREAD

**Issue by c86amik** [dependabot/dependabot-core#3024]
Hi Team,
I am able to successfully host Dependabot in my enterprise using Jenkins pipeline. And it is successfully scanning all the projects that I want to pass and raise PRs if Dependabot found any outdated dependencies.
But the problem that I am facing in some cases, it is throwing an error as "API RATE LIMIT EXCEEDED". So I started debugging the dependabot-core code installed locally.
I am using **gem "dependabot-omnibus", "~> 0.118.8"** as defined in the Gemfile.
I have used the concept of Docker to host and run Dependabot in my enterprise environment using Jenkins pipeline.

Please if anyone can help to solve this issue of API RATE LIMIT thing, then it will be really helpful for me.

Thanks,
Amik

**Comment by busches** [comment]
Are you passing in a GitHub auth token? Unauthenticated requests are limited to 60 requests per hour; authenticated is 5000 per hour. https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by c86amik** [comment]
Yes I have created an Enterprise Access Token and passed that same token in dependabot to run the projects of my enterprise. But some how that token was not getting attached in some case and throws this API Rate limit exceeded error.
What I investigate is that, when it is creating the PR, then in that case in the mutable args property the token was not attached in the header segment. That may be the reason for which I am getting this error.
But how to resolve this?

**Comment by busches** [comment]
Are you 100% that it's enterprise and not GitHub.com throwing the error? You haven't included the script you're using, but the sample they offer requires both.

**Comment by c86amik** [comment]
Hi the error is throwing from this repo "https://api.github.com/repos/junit-team/junit4/contents/" which is github.com. And I only provide the Service Access Token for the Enterprise not for github.com.
So, will I need to provide the Personal Access Token for github.com also to the generic-update-script.rb file of dependabot-script project

**Comment by c86amik** [comment]
So that means I need to set this property **ENV["GITHUB_ACCESS_TOKEN"]** also with my Personal Access Token that I will create from my github.com account.
I will do the necessary changes. And then I will run Dependabot again for my Enterprise projects. And I will let you know in both the cases, whether it is successful or failed.

**Comment by c86amik** [comment]
Thanks. It worked. At last I am successful while running Dependabot for the projects of my enterprise. Thanks for your support.
