### ISSUE TITLE
Respect yarnrc registry config.

### ISSUE THREAD

**Issue by wxsms** [dependabot/dependabot-core#3026]
**Package manager/ecosystem**

javascript

**Manifest contents prior to update**

https://github.com/wxsms/vuepress-theme-mini/blob/master/package.json

**Updated dependency**

ini

**What you expected to see, versus what you actually saw**

The upgrade shoud respect registry settings inside `.yarnrc`:

https://github.com/wxsms/vuepress-theme-mini/blob/master/.yarnrc

```
registry "https://registry.npm.taobao.org"
```

But what I got:

https://github.com/wxsms/vuepress-theme-mini/pull/15/files

**Images of the diff or a link to the PR, issue or logs**

![image](https://user-images.githubusercontent.com/5960988/105293431-122cb600-5bf4-11eb-83f8-49e7feb346dc.png)

**Comment by wxsms** [comment]
Hello? can anyone help with this one? It makes dependabot not usable and annoying in my case.

**Comment by RongxinZhang** [comment]
Getting similar issues.

**Comment by jeffwidman** [comment]
We put a bunch of work into fixing this last quarter.

Docs here: 
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#npm-registry
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-dependabot-to-only-access-private-registries
