### ISSUE TITLE
Golang: Dependabot doesn't run go fmt

### ISSUE THREAD

**Issue by simongottschlag** [dependabot/dependabot-core#3036]
**Package manager/ecosystem**
Golang

**Updated dependency**
https://github.com/XenitAB/azad-kube-proxy/pull/37/commits/89d9d5bc8138e56d558ab26dff2afb160954dafd

**What you expected to see, versus what you actually saw**
https://github.com/XenitAB/azad-kube-proxy/pull/37/commits/3430eb44cf06f24e7a7644a529a80da9591588b3

**Info**
When dependabot does a PR, it doesn't run go fmt and it causes checks for fmt to fail.

**Comment by jurre** [comment]
Are you using Dependabot Preview or the GH Native version? And could you share the repo you're running this against? If you're unable to share that publicly feel free to open an issue via [GH support](https://support.github.com/contact) and we can debug privately

**Comment by simongottschlag** [comment]
Hi @jurre !

I think I'm using the GH Native version, but not 100% sure (it says dependabot-preview as user when doing the PRs). You can find the repo here: https://github.com/XenitAB/azad-kube-proxy

You can see a commit here that isn't working: https://github.com/XenitAB/azad-kube-proxy/commit/89d9d5bc8138e56d558ab26dff2afb160954dafd
Here is a commit when I run `go fmt`: https://github.com/XenitAB/azad-kube-proxy/commit/3430eb44cf06f24e7a7644a529a80da9591588b3

**Comment by jurre** [comment]
Thanks @simongottschlag, it looks like you're using dependabot-preview, if you sign in to https://dependabot.com there should be a button that will let you convert the project to the GH native version, where this should work out of the box.

**Comment by simongottschlag** [comment]
@jurre thank you so much!
