### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lstrojny** [dependabot/dependabot-core#3039]
Can we get a new release so that the fix from https://github.com/dependabot/dependabot-core/pull/3004 is available in production?

**Comment by lstrojny** [comment]
Here we go: https://github.com/dependabot/dependabot-core/pull/3042

**Comment by jurre** [comment]
> Here we go: #3042

Yep just releasing + rolling this out now, apologies for the delay

**Comment by lstrojny** [comment]
No worries
