### ISSUE TITLE
Dependabot making Incompatible Dependency upgrades

### ISSUE THREAD

**Issue by amogkam** [dependabot/dependabot-core#3041]
We've recently added Dependabot to our repository (https://github.com/ray-project/ray) and it works great for the most part. We are using pip-tools/pip-compile and have both our manifest and lock file checked in. 

However, a problem we've been seeing is that Dependabot is making PRs for upgrades that are incompatible with other dependencies. 

For example https://github.com/ray-project/ray/pull/13645, which leads to this error in our CI
```
ERROR: Cannot install boto3==1.16.59 and botocore==1.19.58 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

I would expect Dependabot to automatically resolve these and upgrade other dependencies all in the same PR to maintain compatibility. Calling pip-compile should automatically do this I believe- does Dependabot call this internally?

I'd like to avoid having to manually fix these dependency conflict issues. Thanks!

**Package manager/ecosystem**

**Manifest contents prior to update**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Images of the diff or a link to the PR, issue or logs**

**Comment by titouanc** [comment]
Hello,

I encountered a similar issue in a private repository. I observed that this problem happens when the requirements are specified in a package's setup.cfg and then compiled into requirements.txt.

I have been able to isolate the issue in this repository: https://github.com/titouanc/demo-incompatible-dependabot-upgrades

**Comment by jurre** [comment]
> Hello,
> 
> I encountered a similar issue in a private repository. I observed that this problem happens when the requirements are specified in a package's setup.cfg and then compiled into requirements.txt.
> 
> I have been able to isolate the issue in this repository: https://github.com/titouanc/demo-incompatible-dependabot-upgrades

Thanks for putting that together! I'll put this on our backlog to investigate, but that should help a tonne 🙇

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

> I would expect Dependabot to automatically resolve these and upgrade other dependencies all in the same PR to maintain compatibility. Calling pip-compile should automatically do this I believe- does Dependabot call this internally?

For top-level dependencies, Dependabot currently only bumps one dependency at a time in most cases. I say most because there's a handful of exceptions in the `npm` world. But for python it'll only bump one.

However, it should _not_ be opening a PR to bump a dependency that results in a conflict... Internally Dependabot is calling the native python package manager, in your case `pip-compile`, so that should throw an error, which eventually bubbles up as an `update_not_possible` error in the Dependabot logs. Long term, we'd like to eventually add support for grouped updates (#1190 ) but no ETA for that right now.

@titouanc thanks for the fantastic repro example--I broke it out as a new issue in #6593 so that we don't lose track of it, as I'm not convinced it's related to the first report in this issue.

@alancleary I'd recommend you also file a new bug, as tagging onto this as a catch-all when it's really a fairly specific bug report doesn't really make it possible to triage/deal with.

**Comment by jeffwidman** [comment]
@amogkam it's been two years since your original bug report, and we've shipped a bunch of updates internally, as well as newer versions of `pip-compile` which include their upstream bug fixes.

Is this still reproducible or should this issue be closed?

**Comment by jeffwidman** [comment]
I'm going to close as it's too easy for us to lose track of old stale issues otherwise. But if you're still able to reproduce this, please comment and we can re-open.

**Comment by jprestel-rue** [comment]
This is currently happening in my `pip-compile` project.

Here's the dependabot config
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      prod-dependencies:
        applies-to: version-updates
        dependency-type: production
```

and here's the relevant bits of our `pyproject.toml`

```python
dependencies = [
    "aws-cdk-lib>=2.153.0,<3.0.0",
    "constructs>=10.3.0,<11.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.2,<9.0.0",
    "ruff>=0.6.1,<1.0.0",
    "mypy>=1.11.1,<2.0.0",
    "pre-commit>=3.6.0,<4.0.0",
]

[build-system]
requires = ["hatchling>=1.25.0,<2.0.0"]
build-backend = "hatchling.build"
```

Dependabot's PR fails our checks with this error:
```
pip-sync -q requirements.txt requirements-dev.txt
ERROR: Cannot install -r /tmp/tmp1ow_2qjp (line 2), -r /tmp/tmp1ow_2qjp (line 3) and typeguard==4.3.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.6/x64/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/click/core.py", line [14](https://github.com/RueLaLa/xxxxxxxxxxxx/actions/runs/xxxxxxxx/job/xxxxxxxx?pr=xxx#step:4:15)34, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/piptools/scripts/sync.py", line 145, in cli
    sync.sync(
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/piptools/sync.py", line 263, in sync
    run(  # nosec
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.12.6/x64/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmp1ow_2qjp', '-q']' returned non-zero exit status 1.
```
