### ISSUE TITLE
A way to not to create PR but merge the dependency changes directly

### ISSUE THREAD

**Issue by gaurav517** [dependabot/dependabot-core#3056]
Is there a way to not to create PR but merge the dependency changes directly?

In my use-case, 
- I have a repo: 'my-repo' with a submodule linked to master branch of 'my-submodule-repo'.
- Whenever there is an update in master branch of 'my-submodule-repo', I would like 'my-repo' to update its submodules (automatically, without PR).

Would that be possible currently?

**Comment by jurre** [comment]
That's currently not possible. There's some discussion around automatically merging PRs [here](https://github.com/dependabot/dependabot-core/issues/1823) and some options are discussed in that thread. I'm going to close this out for now.
