### ISSUE TITLE
[ruby:bundler] Failing to create PRs with JSON::GeneratorError

### ISSUE THREAD

**Issue by filipkis** [dependabot/dependabot-core#3074]
For about 3 weeks now we're not getting any new dependancy updates for our **ruby:bundler** ecosystem. This correlates to the moment we turned the `vendor: true` option, but I didn't yet confirm causation (i.e. if reverting that change would fix it, but we would really like to have vendoring on).

Here is the relevant part of the log for one dependency. All that need to be updated fail at same place with the same error.

```
updater | INFO <job_86767312> Checking if newrelic_rpm 6.14.0 needs updating
  proxy | 2021/02/03 16:58:57 [148] GET https://rubygems.org:443/api/v1/versions/newrelic_rpm.json
  proxy | 2021/02/03 16:58:57 [148] 200 https://rubygems.org:443/api/v1/versions/newrelic_rpm.json
updater | INFO <job_86767312> Latest version is 6.15.0
  proxy | 2021/02/03 16:58:58 [150] GET https://index.rubygems.org:443/versions
  proxy | 2021/02/03 16:58:58 [150] 206 https://index.rubygems.org:443/versions
updater | INFO <job_86767312> Requirements to unlock own
updater | INFO <job_86767312> Requirements update strategy bump_versions
updater | INFO <job_86767312> Updating newrelic_rpm from 6.14.0 to 6.15.0
  proxy | 2021/02/03 16:59:13 [152] GET https://index.rubygems.org:443/versions
  proxy | 2021/02/03 16:59:13 [152] 206 https://index.rubygems.org:443/versions
  proxy | 2021/02/03 16:59:24 [154] GET https://rubygems.org:443/gems/newrelic_rpm-6.15.0.gem
  proxy | 2021/02/03 16:59:24 [154] 200 https://rubygems.org:443/gems/newrelic_rpm-6.15.0.gem
updater | INFO <job_86767312> Submitting newrelic_rpm pull request for creation
updater | I, [2021-02-03T16:59:31.805722 #72]  INFO -- sentry: ** [Raven] Sending event e3c9ae4f7724410f8c9a2afe16318955 to Sentry
  proxy | 2021/02/03 16:59:31 [156] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/02/03 16:59:31 [156] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_86767312> Error processing newrelic_rpm (JSON::GeneratorError)
updater | ERROR <job_86767312> source sequence is illegal/malformed utf-8
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/mime_type/json.rb:12:in `to_json'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/mime_type/json.rb:12:in `encode'
updater | ERROR <job_86767312> /usr/lib/ruby/2.6.0/forwardable.rb:230:in `encode'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/client.rb:176:in `make_request_body'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/client.rb:44:in `build_request'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/client.rb:30:in `request'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/http-4.4.1/lib/http/chainable.rb:27:in `post'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/api_client.rb:59:in `create_pull_request'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:632:in `create_pull_request'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:271:in `check_and_create_pull_request'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:66:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_86767312> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:27:in `run'
updater | ERROR <job_86767312> bin/update_files.rb:21:in `<main>'
```

**Package manager/ecosystem**
ruby:bundler

**What you expected to see, versus what you actually saw**
I expect ruby:bundler PRs to be created, but they are not. Neither is `@dependabot rebase` or `@dependabot recreate` working on any PRs that were opened before.

**Comment by jurre** [comment]
Thanks for opening this issue @filipkis, it's very likely that this is indeed related to vendoring, especially the `source sequence is illegal/malformed utf-8` bit makes me think that, we need to upload binary files as `base64`, and maybe we're failing to do that in this case.

Does this happen for all the dependencies in your repo?

Could you share which repo this is happening on so I can dig a little deeper? Feel free to go through [support](https://support.github.com/contact) if it's a private repo that you don't want to share publicly. I'll try to set up a dummy project with `gem "newrelic_rpm", "~> 6.14.0"` to try and replicate this, but if this is happening for all gems, I'm not sure if I'll be able to replicate this.

I'm not sure if I'll be able to dive into it this week, but any info you have that you think would help us debug this would be greatly appreciated

**Comment by filipkis** [comment]
Hi @jurre and thanks for a very prompt response. I've went ahead and created a [dummy project repo](https://github.com/filipkis/test-dependabot-bundler) that has same `Gemfile`, Gemfile.lock` and dependabot settings. And indeed same errors appear. 

Hope this helps.

**Comment by jurre** [comment]
> Hi @jurre and thanks for a very prompt response. I've went ahead and created a [dummy project repo](https://github.com/filipkis/test-dependabot-bundler) that has same `Gemfile`, Gemfile.lock` and dependabot settings. And indeed same errors appear.
> 
> Hope this helps.

That's amazing, thanks so much ✨

**Comment by mctofu** [comment]
From sprint planning: Let's investigate what's going wrong in this case.
