### ISSUE TITLE
Send Dependabot emails to Microsoft Teams channel

### ISSUE THREAD

**Issue by Alexander-Betz** [dependabot/dependabot-core#3091]
I hope it's okay that I ask this here.

Is it possible to send Dependabot emails (like for newly created pull requests) to a specified email address? I would like to send the emails to a Microsoft Teams channel. Is that possible somehow?

I couldn't find an option for that in Github for Dependabot or in the dependabot.yml file.

**Comment by jurre** [comment]
It's not possible directly from Dependabot, but I think it should be possible with the Github/Teams integration: https://github.blog/2020-09-10-announcing-the-github-integration-with-microsoft-teams/

This is not something that we're likely going to add to Dependabot natively though, so I'm going to close out this issue for now. Feel free to follow up with questions, and I'll try to help. I'm not super experienced with Teams, but I should be able to reach out to folks that are.

**Comment by Lahiru-ResLife** [comment]
Hi @Alexander-Betz and @jurre,
I'd like to continue this conversation as I don't think there is a solution to direct Dependabot alerts to Ms Teams.

The following link only creates notifications for issues, pulls, commits, comments, releases, deployments - not security alerts.
https://github.blog/2020-09-10-announcing-the-github-integration-with-microsoft-teams/ 

Is there any way this is possible?

**Comment by jeffwidman** [comment]
@Lahiru-ResLife Afraid this isn't really something we can help with, since it's mostly a question of teams integration, and not alert generation. Can you [file a support ticket here](https://support.github.com/request?tags=teams-integration-support) requesting that they add notifications of alerts to the teams integration?
