### ISSUE TITLE
Add authentication support for Composer (private librairies)

### ISSUE THREAD

**Issue by benoitchantre** [dependabot/dependabot-core#3092]
At the moment, Dependabot fails to create pull requests when some dependencies come from a composer library requiring an authentication.

Could you add a way to set the required configuration for Composer that would work with the _Secrets_?

**Comment by rdohms** [comment]
Duplicate of #2545
Relates to ##2778

In case anyone is looking for more updated information.

**Comment by thepwagner** [comment]
Closing as duplicate of https://github.com/dependabot/dependabot-core/issues/2545

The best issue to follow is https://github.com/github/roadmap/issues/67
