### ISSUE TITLE
Perform custom action after updating dependencies

### ISSUE THREAD

**Issue by ghost** [dependabot/dependabot-core#3100]
For rescript/javascript projects, when dependabot updates the dependencies, I would like it to run a custom command (rescript compile) to update the generated JS files and commit those as part of the PR. A similar issue might exist for typescript. Thanks for considering

**Comment by busches** [comment]
Can this be accomplished with an npm postinstall hook?  https://docs.npmjs.com/cli/v6/using-npm/scripts

**Comment by kanishka-work** [comment]
sounds promising, it even mentions coffeescript. I'll give it a try and reopen if I hit a major obstacle.

**Comment by kanishka-work** [comment]
I added a postinstall script with yarn. It works locally, but I am guessing dependabot doesn't commit the changed files based on a recent PR that I expected to cause some other files to be committed

**Comment by mwaddell** [comment]
Can you create a custom workflow that runs on PRs (like https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#common-dependabot-automations) that executes this code and pushes the results to that branch?

**Comment by jeffwidman** [comment]
Yep, your best bet here is what @mwaddell helpfully suggested (thanks BTW!)

If you configure a custom action to add commits to the PR, then you may also want to prepend those commit messages with `[dependabot skip]` to Dependabot that it is safe to perform its normal rebase operations even though non-Dependabot commits are present on the Dependabot Pull Request.

GitHub actions provides tremendous flexibility for additional customization on PR's / commits so this isn't something we're likely to build into Dependabot.
