### ISSUE TITLE
Rebase PR for azure based repos

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#3102]
We have been running a dependabot like service for azure based repos and create dependency update PRs for repos at regular cadence.
 We have been getting feature requests by our customers to add support for `automatic resolution of merge conflicts` in PR but currently dependabot-core does not support that for azure based repos. 
We are actually planning to implement this in our forked dependabot-core repository and contribute back whatever we can to dependabot-core. 
I wanted to know if there are any plans to add this support in dependabot-core in the near future so that we can avoid any redundant effort else we are planning to add this feature in the next couple of weeks.

@jurre Can you help us with this?

**Comment by jurre** [comment]
What would such a feature look like? What we do for GitHub, is to re-run the job against the latest head ref. This is not part of dependabot-core, but rather of the services we use to run it. Could you do something similar for Azure? Actual resolution of conflicts seems really hard, but I'm curious to hear your thoughts.

**Comment by milind009** [comment]
We are planning to do something similar for azure. We would be re running the update with the latest head ref and then force push the changes onto the source branch

**Comment by jurre** [comment]
Cool, that makes sense 👍 we're not planning to add anything specific to that functionality to core, but I'm curious to hear which bits you think would make sense here. 

I'm happy to chat through some of this on zoom/teams if that would be helpful as well, feel free to reach out at jurre <at> github <dot> com.

**Comment by milind009** [comment]
We are planning to add the pull request updater implementation for azure client on similar lines as done for github and gitlab currently. I'll open PRs for the code changes that i have made for clarity

**Comment by milind009** [comment]
Created this PR:https://github.com/dependabot/dependabot-core/pull/3153

**Comment by jeffwidman** [comment]
Fixed in https://github.com/dependabot/dependabot-core/pull/3153
