### ISSUE TITLE
The name of PR is too short if use 'kotlin()'

### ISSUE THREAD

**Issue by anatawa12** [dependabot/dependabot-core#3144]
Searched with: jvm, kotlin

**Package manager/ecosystem** gradle gradle.kts

**Manifest contents prior to update** build.gradle.kts

**Updated dependency** "org.jetbrains.kotlin.jvm" (in PR, "jvm")

**What you expected to see, versus what you actually saw**
expected "Bump org.jetbrains.kotlin.jvm from 1.4.21 to 1.4.30", but was "Bump jvm from 1.4.21 to 1.4.30"

**Images of the diff or a link to the PR, issue or logs**

PR: https://github.com/anatawa12/bintray2central/pull/1

You may think it's expected behavior, but I think full name is better.

**Comment by busches** [comment]
I see it both ways, as it's a kotlin plugin, the name is just `jvm`, but the message is not clear it's a kotlin plugin, and as you said, it is updating `org.jetbrains.kotlin.jvm` behind the scenes. 🤷 
Can always do it the long way and swap it to `id('org.jetbrains.koltin.jvm')` and it'll be the long name. :D

**Comment by huehnerlady** [comment]
well it should support it in my opinion.

Maybe doesn't have to be the WHOLE plugin id, but at least something like `kotlin-jvm` would be helpful.

**Comment by jeffwidman** [comment]
This is a tricky one, as @busches notes there's tradeoffs here.

I don't think it's something we're going to invest time into changing, but if you feel strongly enough to open a PR happy to review/have a broader discussion about it...
