### ISSUE TITLE
Dependabot is unable to create a security update when using Yarn Workspaces in a monorepo

### ISSUE THREAD

**Issue by cobrabr** [dependabot/dependabot-core#3151]
**Package manager/ecosystem**
NPM / Yarn  

**Manifest contents prior to update**
N/A  

**Updated dependency**
`axios`, from 0.19.2 to 0.21.1  

**What you expected to see, versus what you actually saw**
Dependabot should have created a PR to address the vulnerability. Instead, the Alerts page shows the following error message:
![image](https://user-images.githubusercontent.com/724969/108118443-5d5bac80-706c-11eb-81a3-012341af59aa.png)

Looking the logs (by following the "View logs" link in that error message), I found the following (seemingly) relevant piece of information:

```
updater | INFO <job_89216057> Checking if axios  needs updating
  proxy | 2021/02/16 20:10:48 [028] GET https://registry.npmjs.org:443/axios
  proxy | 2021/02/16 20:10:48 [028] 200 https://registry.npmjs.org:443/axios
  proxy | 2021/02/16 20:10:48 [030] GET https://registry.npmjs.org:443/axios/0.21.1
  proxy | 2021/02/16 20:10:48 [030] 200 https://registry.npmjs.org:443/axios/0.21.1
updater | INFO <job_89216057> Latest version is 0.21.1
updater | INFO <job_89216057> Dependabot can't update vulnerable dependencies for projects without a lockfile or pinned version requirement as as the currently installed version of axios isn't known.
updater | INFO <job_89216057> Finished job processing
```

I can provide the full log if necessary.

The repo in question is a monorepo, and the sub-repo in which the vulnerability is present uses Yarn Workspaces, because it has packages of its own. So the `yarn.lock` file is in the base sub-repo directory, while the `package.json` file that containts the `axios` dependency is in the package's directory. 

In other words, the file structure looks something like this:

```
subrepo/package.json						# this file has the Yarn Workspaces configuration 
subrepo/yarn.lock							# this lockfile is used by *all* packages within this root directory
subrepo/packages/subpackage1/package.json	# this file has the axios dependency
```

**Images of the diff or a link to the PR, issue or logs**
N/A

**Comment by feelepxyz** [comment]
@cobrabr thanks fro reporting this. This is a known issue and we don't have a fix planned for this yet but have raised it with the team.

The current workaround is to ignore alerts for the nested packages and use the alert/update raised for the root lockfile. This should in theory work as dependabot supports workspaces if the update is triggered for directory where the `package.json` with the `workspaces` config exists.

**Comment by cobrabr** [comment]
So, in other words, move the dependency from the internal `package.json` to the root one? Or did I misunderstand?

**Comment by feelepxyz** [comment]
@cobrabr if everything is working as it should, you should be getting two dependabot alerts for `axios` one for `subrepo/yarn.lock` and one for `subrepo/packages/subpackage1/package.json`, the nested `subpackage1` update will fail with the above error your reported as it's trying to run the update in `subrepo/packages/subpackage1` and doesn't know about the parent lockfile and workspace config. The alert for `subrepo/yarn.lock` should however succeed and update `axios` in both the lockfile and the nested `package.json` file.

Dependabot currently supports updating workspace projects but only when triggered in the right directory, the update is triggered upstream based on what's in the Dependency Graph and here we currently don't know about the workspace layout so we create two security alerts, one for each individual file that includes the vulnerable dependency.

We'll need to make the Dependency graph aware of workspace layouts so we don't trigger updates in the nested folder.

**Comment by cobrabr** [comment]
We're only getting one alert (the one for `subrepo/packages/subpackage1/package.json`), and Dependabot says it can't create a PR for that one because it can't find a lockfile, as the image in my original post shows.

All PRs that Dependabot does create only ever update `yarn.lock` files, never `package.json` ones. Is there something I need to configure to allow it to do that (keeping in mind that we don't necessarily want Dependabot to manage package versions, only security alerts and updates)?

**Comment by feelepxyz** [comment]
@cobrabr oh something else might be wrong in that case. Could you set up a public test repo with the same workspace setup you use and axios installed in a sub-package with a vulnerable version? (e.g. `0.18.0`) Would massively help debugging this 🙇

**Comment by cobrabr** [comment]
Will do. I'll post a link here when I'm done.

**Comment by cobrabr** [comment]
https://github.com/IntelexTechnologies/dependabot-test

This test repo has both alerts, though...

**Comment by cobrabr** [comment]
We can close this one for now. We had to upgrade `axios` manually because of another requirement, so we can't reproduce it anymore. I'll open a new issue here if required.

**Comment by stackptr** [comment]
@feelepxyz I am receiving the same message about a missing lockfile in a repo using yarn workspaces. I am working on reproducing the issue in a test repo, because in the private repo experiencing this there is no duplicate alert that applies to the root lockfile. Each alert references a sub-package's `package.json` within the workspace, with nothing referencing the lockfile.

**Comment by strass** [comment]
I'm also having issues here. Does anyone have a solution?

**Comment by teriu** [comment]
Same issue here

**Comment by marklai1998** [comment]
@cobrabr can you reopen it? It is still an issue

**Comment by cobrabr** [comment]
I don't work at the place where this problem was happening anymore, nor am I using Dependabot right now, so I can't test if it's still happening. 

Feel free to keep this issue open for tracking/fixing, but I can't help with more information anymore, unfortunately.

**Comment by abdulapopoola** [comment]
Closing out as stale
