### ISSUE TITLE
Unable to sign up, presented with error page.

### ISSUE THREAD

**Issue by mwcw** [dependabot/dependabot-core#3152]
Hi,

I clicked "Sign Up" and got:

POST https://api.dependabot.com/access_tokens
Report issue

![image](https://user-images.githubusercontent.com/30947532/108158929-15a35680-713a-11eb-9e64-63921490aa38.png)

MW

**Comment by nitaigao** [comment]
Me too, also can't log in

**Comment by stavrogin** [comment]
Exactly same issue

**Comment by jurre** [comment]
I'm investigating what's going on.

For most new installations if at all possible I would recommend using the [github native version](https://docs.github.com/en/github/administering-a-repository/about-dependabot-version-updates) of Dependabot.

**Comment by jurre** [comment]
It should be resolved now, thanks for reporting this!

**Comment by stavrogin** [comment]
Thanks @jurre , I confirm that it is working
