### ISSUE TITLE
Dependabot doesn't properly handle python versions with epoch

### ISSUE THREAD

**Issue by daviddavis** [dependabot/dependabot-core#3165]
In python, if you have a version requirement such as `pulp-smash>=1!0.12.0`, dependabot will throw this error: 

```
Illformed requirement [">=1!0.12.0"]
```

This is a perfectly valid version though according to [PEP440](https://www.python.org/dev/peps/pep-0440/). The `1!` being the epoch segment.

**Comment by kohder** [comment]
We're running into this too because we use Astronomer's Airflow packages. Example for the GitHub provider package: https://pip.astronomer.io/simple/apache-airflow-providers-github/
