### ISSUE TITLE
Cannot setup custom maven repository

### ISSUE THREAD

**Issue by stavrogin** [dependabot/dependabot-core#3167]
Hi,
I would like to setup a custom maven repository in addition to maven central, but I don't want to edit the project's pom.xml file 
as explained [here](https://dependabot.com/blog/custom-maven-repositories/)
I guess that it should be possible by editing the dependabot config file but [here ](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem)I cannot find any details
Could you please explain how to do it?
Thanks

**Comment by jurre** [comment]
This is currently not possible for the GitHub native version of Dependabot, but it's coming soon. If you need it right now you can set up an account on dependabot.com and use the preview version of Dependabot.

**Comment by stavrogin** [comment]
Hi @jurre ,
thank you for your reply. 
I have a couple of more questions:
1) Is Dependabot native also for GitHub Enterprise? I tried to put dependabot.yaml in .github folder but nothing was triggered (in my personal GitHub, not enterprise, it works fine)
2) So is there a way, in  preview version of Dependabot, to configure an external Nexus without moving the configuration into pom.xml ?
Thanks you

**Comment by asciimike** [comment]
Will be fixed by https://github.com/github/roadmap/issues/67, closing.
