### ISSUE TITLE
Could'nt find any version for "package" that matches "version-range" error in yarn workspaces

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#3186]
I observed this failure while working on a `yarn` based repo using `workspaces`. For a dependency (say X), in one of the workspace `package.json`, X was declared in `"dependencies"` with absolute version say Y. Now Y is an invalid version. The `"resolutions"` field in the root package.json contains X being resolved to valid version Z and the lockfile too contains an entry as 
`"X@Y":
version "Z"`
Now when i try to update any dependency in this repo, it gives the same error. Deep diving into this, i saw this failure occurs in the `'resolve'` step of install wherein it checks if the version (for e.g Y) exists in the `registry response` for the dependency. 
@jurre @feelepxyz  Is this failure expected or am i missing something? Could you also deep dive more into the possible reason for this and if it can be avoided?

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

Yarn workspaces support landed in:
* https://github.com/dependabot/dependabot-core/pull/5685

I think this should resolve what you're describing, but I haven't tested it myself and not super famiilar with the `yarn` ecosystem. 

I'm going to close, but if for some reason this doesn't resolve your issue please comment and we can reopen.
