### ISSUE TITLE
PyPi package deprecations

### ISSUE THREAD

**Issue by Avamander** [dependabot/dependabot-core#3221]
It would be nice if there was a way to mark a Pip package as deprecated, or simply warn about dependencies not updated for a long time.

For example [Flask-BabelEx](https://github.com/mrjoes/flask-babelex) is deprecated and should be replaced with [Flask-Babel](https://github.com/python-babel/flask-babel).

**Comment by jeffwidman** [comment]
Dupe of https://github.com/dependabot/dependabot-core/issues/3242, and unfortunately probably not something we can do for reasons outlined in https://github.com/dependabot/dependabot-core/issues/3242#issuecomment-1211592452.
