### ISSUE TITLE
HCL parse error

### ISSUE THREAD

**Issue by mjulianotq** [dependabot/dependabot-core#3225]
**Package manager/ecosystem**
Terraform 0.14.6
**What you expected to see, versus what you actually saw**
I expected dependabot to parse and analyze my HCL which is working fine with Terraform, but it apparently cannot parse the dialect I'm using.
**Images of the diff or a link to the PR, issue or logs**
It complained about `string` in the below saying `unable to parse HCL: At 2:12: Unknown token: 2:12 IDENT string`:
```hcl
variable "customer_name" {
    type = string
    description = "Required. This name will be applied to all resources in this module for easy identification."
}
```

**Comment by asciimike** [comment]
Howdy @mjulianotq, thanks for the report. We don't currently support Terraform 0.14, though it's something we'll be working on soon. Please follow https://github.com/dependabot/dependabot-core/issues/1176 for the latest updates.

**Comment by mjulianotq** [comment]
@asciimike I searched for HCL 2 before I opened this, but that didn't come up. Sorry for generating admin overhead for you.

**Comment by asciimike** [comment]
It's all good, TBH the issues aren't super searchable, so I don't blame you. I'm going to spend some time every day cleaning them up, and hopefully get everything back in a more reasonable state :)
