### ISSUE TITLE
Escape links in release notes

### ISSUE THREAD

**Issue by asciimike** [dependabot/dependabot-core#3276]
Currently we escape @ mentions of users in Dependabot PRs by adding a ZWJ between the @ and the username, so that users don't constantly get notified of everything Dependabot is doing.

We should likely do something similar with links in release notes, since GitHub linkifies the release note links and shows them in the maintainer's repos.

Without this, maintainers are crushed under thousands of useless back-references from Dependabot.

Examples:
 - https://twitter.com/MrJamesHenry/status/1371492139180392459 (and https://github.com/eslint/eslint/pull/14178)
 - https://github.com/laravel/framework/pull/36480

**Comment by brrygrdn** [comment]
We have identified this as a regression in the Dependabot service itself, and a fix will go out shortly to prevent this behaviour in future, with a few follow-ups to avoid this kind of problem in future.

Apologies for the noise! 🙉

**Comment by brrygrdn** [comment]
Closing this out as the core PR is just a follow up.

**Comment by bradzacher** [comment]
Just flagging that there are fresh reports of this regressing again

https://twitter.com/NicoloRibaudo/status/1567065351522848768

**Comment by nicolo-ribaudo** [comment]
Thank you @bradzacher!

This is the spammed PR: https://github.com/tc39/ecma262/pull/2819

**Comment by jeffwidman** [comment]
☝️  was tracked in https://github.com/dependabot/dependabot-core/issues/5639
