### ISSUE TITLE
Private NPM registry url with path support

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [dependabot/dependabot-core#3292]
**Package manager/ecosystem**
javascript

**Manifest contents prior to update**
N/A

**Updated dependency**
N/A

**What you expected to see, versus what you actually saw**
I'm getting error below, but my private registry url is from ProGet and it's like `https://registry.example.com/npm/npm` and path is required.

Dependabot should allow for registry urls with path.

**Images of the diff or a link to the PR, issue or logs**
```
JavaScript registries must specify a url in a format like `https://registry.npmjs.org` or `https://npm.pkg.github.com`. Please don't include a path.
```

![image](https://user-images.githubusercontent.com/75308464/111476216-48048d00-86c1-11eb-96da-0fab438c5ac8.png)

**Comment by jurre** [comment]
Hi @pstepniewskiconfigit, I think this should be answered here already: https://github.com/dependabot/dependabot-core/issues/3292, the gist is: This config is only used to map the secrets to this registry, for actual resolution we look at your npmrc/lockfile, the same way npm/yarn do this. Removing the path as the error suggests should fix the issue for you. We'll look into clarifying this further on our end.
