### ISSUE TITLE
Bundler updates are reintroducing the Ruby platform to `Gemfile.lock`

### ISSUE THREAD

**Issue by agrobbin** [dependabot/dependabot-core#3299]
**Package manager/ecosystem**
ruby:bundler

**Manifest contents prior to update**

Our `Gemfile.lock` defines 2 platforms:

```
PLATFORMS
  x86_64-darwin
  x86_64-linux
```

All of a sudden Dependabot has started trying to add a new platform, and the gem dependencies that go along with it (in our case, the non-platform-specific `nokogiri`) when updating *any* Ruby gem. For example, in a recent Dependabot PR to update `rspec-rails`, this is the diff:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 6105d2271..2ea10642a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -369,6 +369,7 @@ GEM
     mimemagic (0.3.5)
     mini_magick (4.11.0)
     mini_mime (1.0.2)
+    mini_portile2 (2.5.0)
     minitest (5.14.4)
     monetize (1.9.4)
       money (~> 6.12)
@@ -390,6 +391,9 @@ GEM
     mustache (1.1.1)
     nenv (0.3.0)
     nio4r (2.5.7)
+    nokogiri (1.11.2)
+      mini_portile2 (~> 2.5.0)
+      racc (~> 1.4)
     nokogiri (1.11.2-x86_64-darwin)
       racc (~> 1.4)
     nokogiri (1.11.2-x86_64-linux)
@@ -533,10 +537,10 @@ GEM
     rspec-mocks (3.10.2)
       diff-lcs (>= 1.2.0, < 2.0)
       rspec-support (~> 3.10.0)
-    rspec-rails (4.1.0)
-      actionpack (>= 4.2)
-      activesupport (>= 4.2)
-      railties (>= 4.2)
+    rspec-rails (5.0.0)
+      actionpack (>= 5.2)
+      activesupport (>= 5.2)
+      railties (>= 5.2)
       rspec-core (~> 3.10)
       rspec-expectations (~> 3.10)
       rspec-mocks (~> 3.10)
@@ -719,6 +723,7 @@ GEM
     zeitwerk (2.4.2)
 
 PLATFORMS
+  ruby
   x86_64-darwin
   x86_64-linux
 ```

**What you expected to see, versus what you actually saw**

Expected: Dependabot does not attempt to add a new platform to `Gemfile.lock`.

What actually happened: Dependabot added `ruby` as a new platform

**Comment by jurre** [comment]
Thanks @agrobbin, do you know when this started happening? Which version of bundler are you using? (the version _should_ not matter, but it might be related to the bug in this case)

**Comment by agrobbin** [comment]
I don't know exactly when this started, or if it's actually been an issue since we upgraded to Bundler 2.2.3+, but here's our current version info:

```
RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.2.13
```

**Comment by agrobbin** [comment]
Looking closer at our Git history, it looks like this has been an issue since we moved to Bundler 2.2.3+, when multi-platform support was added to Bundler. I don't see any Dependabot PRs since we did that (~10 days ago) that haven't tried to also add the `ruby` platform back to our list of platforms.

**Comment by jurre** [comment]
Aye yes, I've seen this before, I think it's related to https://github.com/dependabot/dependabot-core/issues/2927. We are still on bundler 1.17 internally currently, but are working to upgrade this at the moment. I think we'll need to complete that upgrade in order to fix this.

I'm afraid the only real option I can offer right now is to downgrade bundler :( 

We hope to land the upgrade in the next few weeks, but I can't commit to a timeline yet

**Comment by agrobbin** [comment]
Ahhh that makes sense then! I will make sure I follow that issue, and in the meantime, I will add back in `ruby` as a platform. That won't be perfect, as Bundler 1.x likely won't be able to successfully upgrade multi-platform packages, but it should be good enough until Bundler 2.2+ is supported in Dependabot-land.

**Comment by feelepxyz** [comment]
@agrobbin 👋  we've just launched support for bundler v2 in Dependabot Version and Security Updates. This should just work if your lockfile has been `BUNDLED WITH 2.x`. Let us know if this is working for you.

Dependabot Preview support is coming next week.

**Comment by agrobbin** [comment]
Thanks @feelepxyz! We will give it a shot.

**Comment by feelepxyz** [comment]
This should be fixed, let us know if not!

**Comment by agrobbin** [comment]
@feelepxyz perfect timing since there was a Nokogiri update yesterday. As expected, everything worked flawlessly, thanks again!
