### ISSUE TITLE
Dependabot creates misleading links to PR's due to embedded changelog

### ISSUE THREAD

**Issue by iliapolo** [dependabot/dependabot-core#3309]
**Package manager/ecosystem**

ALL

**Manifest contents prior to update**

Not Applicable

**Updated dependency**

Any

**What you expected to see, versus what you actually saw**

Dependabot PR's embed the changelog of the updated dependency in its PR body. 

![Screen Shot 2021-03-21 at 12 34 37 PM](https://user-images.githubusercontent.com/1428812/111901593-d5d5d480-8a41-11eb-9ab7-b09a9db65974.png)

These changelogs often include text in the form of:

```text
go: duplicate conversion functions when parent structs have the same base name (#2697) (52bd510), closes https://github.com/aws/jsii/issues/2632
```

This creates a *closing* relationship between the dependabot PR and the issue mentioned in the changelog.
This creates clutter and confusion, as the dependabot PR most certainly does not resolve the issue it mentions. 

In addition, if the PR is approved/merged by a user that has permissions to both repositories, merging the dependabot PR will **actually close** the mentioned issue, which is not intended.    

**Images of the diff or a link to the PR, issue or logs**

For example, the following dependabot [PR](https://github.com/awslabs/aws-delivlib-sample/pull/83) in the [`aws-delivlib-sample`](https://github.com/awslabs/aws-delivlib-sample) repository, closed an [issue](https://github.com/aws/jsii/issues/2048) in the [`jsii`](https://github.com/aws/jsii) repository. 

![Screen Shot 2021-03-21 at 12 32 18 PM](https://user-images.githubusercontent.com/1428812/111901536-7f689600-8a41-11eb-9f34-42b4101f0202.png)

You can also see the amount of links created to this issue due to dependabot PR's in unrelated repositories. 

I would expect dependabot PR's to not create any implicit links to other issues, and this indeed doesn't seem intentional, but rather a consequence of GitHub functionality.

**Comment by feelepxyz** [comment]
👋 @iliapolo this looks like a regression, we try to not backlink github links in dependabot PRs. Will take a look.

**Comment by feelepxyz** [comment]
@iliapolo we already fixed this [here](https://github.com/dependabot/dependabot-core/pull/3301), just confirmed new PRs to update `jsii-pacmak` don't create backlinks anymore: https://github.com/awslabs/cdk-watchful/pull/399
