### ISSUE TITLE
Dependabot flags vulnerability in requirements.txt files in old releases

### ISSUE THREAD

**Issue by nishakm** [dependabot/dependabot-core#3316]
**Package manager/ecosystem**
Python3 with pip-tools

**What you expected to see, versus what you actually saw**
Dependabot recently flagged a vulnerable version of urllib3 against https://github.com/tern-tools/tern. However, it detected the vulnerable package in one of our [frozen manifests]( https://github.com/tern-tools/tern/blob/main/docs/releases/v2_3_0-requirements.txt) which we keep for every release as a build reproducibility best practice. 

We've since [bumped up the version on urllib3](https://github.com/tern-tools/tern/blob/main/docs/releases/v2_5_0-requirements.txt#L155) but Dependabot still alerts us because it's looking at a frozen manifest.

We would expect Dependabot look at the top level [requirements.txt](https://github.com/tern-tools/tern/blob/main/requirements.txt) for this project.

This might be something Dependabot will not be able to solve, in which case, we would like an "other" reason for dismissing the alert (I had to choose "already working on a fix" which isn't the case here).

Thanks!

**Comment by feelepxyz** [comment]
@nishakm yeah I think falls outside of what we can fix for now. Dependabot alerts is powered by the dependency graph which finds supported manifests in your entire repo and there's no way to ignore certain files yet but will pass along this feedback.

An "other" reason seems reasonable too.

**Comment by jeffwidman** [comment]
Closing, as explained above there's nothing we can do. 

You can now add a custom reason for dismissal: https://docs.github.com/en/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#dismissing-dependabot-alerts
