### ISSUE TITLE
Stop submitting new PRs when open-pull-request-limit is reached

### ISSUE THREAD

**Issue by jwhui** [dependabot/dependabot-core#3341]
I am trying to use the `open-pull-request-limit` feature. The [documentation](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#open-pull-requests-limit) states:

> By default, Dependabot opens a maximum of five pull requests for version updates. Once there are five open pull requests, new requests are blocked until you merge or close some of the open requests, after which new pull requests can be opened on subsequent updates. Use open-pull-requests-limit to change this limit.

However, I noted that the existing PR(s) are closed and superseded by a new PR automatically (see https://github.com/openthread/ot-cc2538/pull/6).

Any guidance on how to achieve the documented behavior?

Configuration: [dependabot.yml](https://github.com/openthread/ot-cc2538/blob/main/.github/dependabot.yml)

**Comment by jurre** [comment]
Hi @jwhui, I think this is working as intended, but maybe the documentation is not fully complete. the PR with the old version is closed and a new one, with the new version is opened leaving the same number of open pull requests. Is this not what is happening?

There is currently no way to configure Dependabot to _not_ replace outdated updates with a new version, if that's what you're looking to achieve. We should maybe clarify this in the docs

**Comment by jwhui** [comment]
@jurre , thanks for the response. The specific part of the documentation that confuses me is:

> new requests are blocked until you merge or close some of the open requests, after which new pull requests can be opened on subsequent updates

- What does "new requests are blocked" mean?
- In "until you merge", who is "you"?

I interpreted that as dependabot **not** automatically closing PRs to make room for new ones.

**Comment by jurre** [comment]
> What does "new requests are blocked" mean?

I think a better way to work this might be: `Pull requests for other dependencies are blocked, if a new version of this dependency is released Dependabot will close the PR to the old version and open one for the new one, keeping the number of pull requests at the limit`

> In "until you merge", who is "you"?

It's really anyone, and closing a PR also applies.

The number determines the maximum number of open pull requests Dependabot will allow at any time, but there is no logic around specific actors or anything like that.

I get your confusion and will look into getting the docs changed, appreciate the feedback.

**Comment by jeffwidman** [comment]
It's the total number of dependabot pull requests. So in your example you can open as many as you want, but Dependabot will only open 5 PR's at a time.

**Comment by jeffwidman** [comment]
My docs PR clarifying the wording https://github.com/github/docs/pull/20095 has been merged, so closing this.

**Comment by jwhui** [comment]
I'm not sure https://github.com/github/docs/pull/20095 clarifies the issue I raised. In particular, from https://github.com/dependabot/dependabot-core/issues/3341#issuecomment-806000092, when the limit is reached, a new PR will be opened, but the old one will closed at the same time, keeping the number of open PRs at the limit. I don't think the "will not open any new requests" wording is consistent. Thoughts?
