### ISSUE TITLE
Dependabot updates multiple not connected dependencies in one PR

### ISSUE THREAD

**Issue by vbuberen** [dependabot/dependabot-core#3347]
**Package manager/ecosystem**
Gradle

**Updated dependency**
Kotlin

**What you expected to see, versus what you actually saw**
According to PR name and based on how Dependabot works I expect to have only on dependency per PR updated.
However, in this particular PR I see the 3 dependencies were updated with one commit and 2 other were not even mentioned in the PR description.

**Images of the diff or a link to the PR, issue or logs**
Here is the PR Dependabot created: https://github.com/ChuckerTeam/chucker/pull/586/files

**Comment by jurre** [comment]
@vbuberen those dependencies are connected by the `kotlinVersion` variable, right? The behavior seems to make sense to me, would you expect Dependabot to remove the variable reference and hard-code the version? That seems undesirable to me.

They are all mentioned in the PR description from what I can see?

> Bumps kotlinVersion from 1.4.31 to 1.4.32.
> Updates kotlin-gradle-plugin from 1.4.31 to 1.4.32 
> Updates kotlin-stdlib from 1.4.31 to 1.4.32

**Comment by vbuberen** [comment]
Now PR looks right. It looks like the PR changed after I reported the issue. Don't know how is that possible.
When I was reporting it the PR looked like in this commit (note activity and fragment versions change): https://github.com/ChuckerTeam/chucker/commit/9d8b5b2cdd25e0e0a60575d14aaf4de2997d3e54

**Comment by jurre** [comment]
Ah, thanks. That _is_ weird, I think that this was fixed after a previous PR was merged and this was rebased (well, it re-runs the update for the given dependency again under the hood). But definitely seems like a bug on our end that we'll need to look into.

Thanks for reporting 👍

**Comment by vbuberen** [comment]
Ok, so it happened again in another PR.
Attaching a commit link this time: https://github.com/ChuckerTeam/chucker/pull/589/commits/fe5b4ab37d050b4c7205d6cd5641324ee5a1ad51
