### ISSUE TITLE
Intermittently getting `dependency_file_not_resolvable` error

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3357]
We run `dependabot` on GitHub.com (not self-hosted) on a number of go-based repos. So dependabot is processing `go.mod`/`go.sum`. These repos are all using either go version 1.15 or 1.16.

We are intermittently getting the following error:

```
dependency_file_not_resolvable {:message=>""}
```

What's weird is the error seems to be intermittent and will work fine, but then fail against random repos. And because the message is empty, we have no idea what the root of the problem is.

Here's an example of a specific error:

```
updater | INFO <job_102322932> Handled error whilst updating github.com/confluentinc/confluent-kafka-go: dependency_file_not_resolvable {:message=>""}
```

This is so weird because that's a completely public repo... and this dependency is specified in other repos which all worked fine. If I re-run the job on this failing repo, it will fails with the same error message, but the repository reported as failing seems to be random.

Any idea what's going on?

**Comment by jeffwidman** [comment]
Actually, I just noticed that these repos have two direct deps that conflict... ie:
* direct dep A makes a breaking API change that doesn't affect this repo
* direct dep B relies on A, and _is affected by the breaking change, but hasn't yet updated to it_. 

So when I run `go get -u -t ./...` locally, it fails with something like...
```
dep B undefined call to direct dep A.broken API
```

I'm going to try fixing those and I suspect it will start working again.

**Comment by jeffwidman** [comment]
This is resolved now. Something was fixed in dependabot and now it properly reports the error (which was a broken / unreachable hash/package version in the dep tree).

**Comment by jurre** [comment]
Happy to hear it @jeffwidman, @xlgmokha improved error reporting for golang a bit in the past few weeks so that's probably why it's reported now 🎉
