### ISSUE TITLE
How dependabot works?

### ISSUE THREAD

**Issue by Rbsn-joses** [dependabot/dependabot-core#3358]
I have a curiosity, how does dependabot know which is the most recent version in gradle in a private repository?

**Comment by jurre** [comment]
The magic sauce is here: https://github.com/dependabot/dependabot-core/blob/c36e14b63ea1f1c0aa893f64d15d1af9c5c8c90d/gradle/lib/dependabot/gradle/update_checker/version_finder.rb

We grab the dependency metadata from the repository, using the credentials that were configured to authenticate
