### ISSUE TITLE
Remove `@` from PR description intro

### ISSUE THREAD

**Issue by shu-mutou** [dependabot/dependabot-core#3378]
Not to send lots of mentions, our community does not allow using `@` in commit message. But some packages has `@` in its name, so commit message in PR from dependabot includes `@` like following.

```
Bump @angular/platform-browser from 11.2.6 to 11.2.7

Bumps [@angular/platform-browser](https://github.com/angular/angular/tree/HEAD/packages/platform-browser) from 11.2.6 to 11.2.7.
- [Release notes](https://github.com/angular/angular/releases)
- [Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md)
- [Commits](https://github.com/angular/angular/commits/11.2.7/packages/platform-browser)

Signed-off-by: dependabot[bot] <support@github.com>
```

Can we remove `@` from commit message?

**Comment by markcellus** [comment]
We have something similar. What setup are you using to prevent merging PRs with `@` in commit messages? A required Github status check?

**Comment by I-Cat** [comment]
I can confirm this is an issue look at my code as i tested on my own repo

**Comment by shu-mutou** [comment]
Our community checks `@` in commit message by own script via GitHub status check. They worry about lots of mentions not only `@user` but also `@org/team` due to commits that include `@`.

**Comment by jurre** [comment]
We escape `@user` mentions pretty aggressively, you check out the code [here](https://github.com/dependabot/dependabot-core/blob/e7c1929d7f850f8516311cc41753958cb6b980d2/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb)

Did you see an instance where this caused a user to be mentioned? If so we'd love to know so we can fix it ASAP, it is incredibly annoying to be bombarded by dependabot mentions. As far as I can tell `@angular/platform-browser` should not lead to a mention, but you're saying sometimes there is a team in the org with the same name and then it does cause mentions?

FWIW what we do instead of remove the `@`, is insert a zero-width space, and wrap the mention in a code block, maybe we need to include teams in the regex that does this escaping

**Comment by shu-mutou** [comment]
@jurre, thank you for showing the check inside dependabot!

And our community is checking mention by [this regex](https://github.com/kubernetes/test-infra/blob/55dab213bff9ed663013072c14f17c19dc9c625f/prow/plugins/invalidcommitmsg/invalidcommitmsg.go#L66), and this check prevents merging PR.

[dependabot](https://github.com/dependabot/dependabot-core/blob/e7c1929d7f850f8516311cc41753958cb6b980d2/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb#L140) seems to create commit messages that never have words to send mention, right?

If so, `\u200B` might be dropped somewhere.... We need to find the place where it was dropped.

`test-infra` team in our community just worry about lots of mention sent to other orgs, teams or users. Basically, our team doesn't get mentioned from PRs. I'm not sure in community wide.

**Comment by markcellus** [comment]
We do the same @shu-mutou. Until dependabot team supports this, I updated our script to detect whether the user is dependabot. If it is, then we don't error the github status check.

**Comment by jurre** [comment]
> dependabot seems to create commit messages that never have words to send mention, right?

It should, but I _think_ that this may assume only _users_ are mentioned, and doesn't take into account teams.

We'll need to change [this](https://github.com/dependabot/dependabot-core/blob/e7c1929d7f850f8516311cc41753958cb6b980d2/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb#L11) regex to `/[a-z0-9\/]+(-[a-z0-9]+)*/` I think (and probably change the name).

It should we a relatively straight-forward fix, I'll try to find some time for it today. Just want to add some test coverage, and do some research around valid team names to make sure we handle all of them.

**Comment by shu-mutou** [comment]
@jurre In v0.140.0, I found that link text in `Release notes` and `Commits` in PR description are sanitized, but not commit messages.
Is this expected behavior?

We can see which mentions are sanitized in `<meta name="description" content="[here]">` with Chrome.

![image](https://user-images.githubusercontent.com/12838129/113961304-cab3de80-9860-11eb-9c7e-5be0859df266.png)

**Comment by shu-mutou** [comment]
@jurre Could you reopen this issue?

**Comment by jurre** [comment]
I'm looking into a more generic solution to this on the GitHub side of things, we're playing a game of wack-a-mole on the Dependabot side, it would be a lot easier if we could mark a PR to not create any mentions when opening it, either via a setting in the API or as a special case for Dependabot

**Comment by shu-mutou** [comment]
Thank you for your deep consideration. I hope it will be implemented with a better design. 🙏 🙏 🙏

**Comment by abdulapopoola** [comment]
Closing out as stale
