### ISSUE TITLE
Create single PR for common dependant package

### ISSUE THREAD

**Issue by soumyamahunt** [dependabot/dependabot-core#3399]
In version 1, if a version update is available for package used across multiple projects inside a repo only one PR is created. But in version 2, for each project a separate PR is created. Please bring back the older behavior or give us a way to choose which behavior we want.

**Comment by feelepxyz** [comment]
@soumyamahunt how does your v2 config file look? This should still be possible and if you're using npm/yarn workspaces you'll only want to add the directory with the root lockfile and not add each sub-project to the config file.

**Comment by soumyamahunt** [comment]
> @soumyamahunt how does your v2 config file look? This should still be possible and if you're using npm/yarn workspaces you'll only want to add the directory with the root lockfile and not add each sub-project to the config file.

Although I am using nuget, but you are right. Dependabot updates manifests for projects referenced inside the main project. I was explicitly defining manifest location for other sub-projects which caused duplicate PRs. Sorry for wasting your time.

**Comment by feelepxyz** [comment]
@soumyamahunt nice one 🙌 no problem!
