### ISSUE TITLE
Azure/Gitlab/Bitbucket clients do not handle file deletion + file create is missing

### ISSUE THREAD

**Issue by jerbob92** [dependabot/dependabot-core#3409]
**Package manager/ecosystem**
go_modules
**Manifest contents prior to update**
github.com/buger/jsonparser v1.0.0
**Updated dependency**
github.com/buger/jsonparser v1.1.1
**What you expected to see, versus what you actually saw**
The vendoring pulls in the dependencies, it is possible that vendoring either creates new files, or deletes files, besides updating them, which works for most implementations. I think the following things are missing:

- The Azure, Gitlab and Bitbucker client implementations miss the `file.deleted` check to see if a file has been deleted to send a delete action in the pull request
- When new files are created, the creation of the pull request for Gitlab fails, since everything is [added as update](https://github.com/dependabot/dependabot-core/blob/488259938c04c846b9943d501d5107243665b6ab/common/lib/dependabot/pull_request_creator/gitlab.rb#L97), and Gitlab recognizes that the file doesn't exist so there is nothing to update
- `DependencyFile` should probably get a `created` property for new files so clients that see create/update as a different action are also supported

**Images of the diff or a link to the PR, issue or logs**
The following error is raised when new files are created by vendoring:
```
WARN: Gitlab::Error::BadRequest: Server responded with code 400, message: A file with this name doesn't exist
```

**Comment by jurre** [comment]
Thanks @jerbob92, we'd appreciate any help fixing this in the GitLab/Azure PR creation code as all GitLab code in Dependabot are community contributions and we currently only maintain and support the GitHub integration.

**Comment by jurre** [comment]
> > Thanks @jerbob92, we'd appreciate any help fixing this in the GitLab/Azure PR creation code as all GitLab code in Dependabot are community contributions and we currently only maintain and support the GitHub integration.
> 
> I can take care of the GitLab implementation, I don't have access to Azure though, would you accept a PR that only fixes GitLab?

Absolutely

**Comment by jerbob92** [comment]
@jurre created the PR, let me know if you want tests, I'm not a Ruby developer so might take me some time to figure tests out.
