### ISSUE TITLE
@dependabot rebase not happening automatically 

### ISSUE THREAD

**Issue by mikemhenry** [dependabot/dependabot-core#3421]
**Package ecosystem**
pip

**Language version**
python
**Manifest location and content prior to update**

**dependabot.yml content**
https://github.com/glotzerlab/signac/blob/master/.github/dependabot.yml

**What you expected to see, versus what you actually saw**
In this PR (and others)
https://github.com/glotzerlab/signac/pull/535'
 dependabot isn't  resolving conflicts automatically. 
I thought that if I merged (squashed) in one dependabot PR, the other PRs would "rebase" automatically. 

Currently I have to merge in the PR, then run `@dependabot rebase` on the next one.  This should just work, right?
>Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself.

**Comment by mikemhenry** [comment]
It looks like someone merged that one in :facepalm: Try taking a look at this one:
https://github.com/glotzerlab/signac/pull/539

**Comment by jurre** [comment]
Thanks @mikemhenry, I can't really make out what's the conflict in that PR? It seems like it should be a clean merge?

**Comment by jurre** [comment]
I don't think it needs to rebase the PR, as there are no conflicts? Dependabot will only rebase if it notices changes that conflict with the PR

**Comment by csadorf** [comment]
> It looks like someone merged that one in 🤦

Sorry, but I was not the one to enable auto-merge...

**Comment by bdice** [comment]
I think what we’re wanting is for Dependabot to automatically rebase if its branch is not up to date with the target branch (master/main). Currently we have no conflicts but the automerge is held up because the PR needs the target branch merged into it (or a rebase to be triggered).

**Comment by jurre** [comment]
Ah I see. No there's currently not a way to do that, the way these "rebases" are implemented is by re-running the update on top of the latest sha on the main branch, so these are quite expensive.

I get why that'd be useful though, and I wonder if there's a way we could implement this without having to re-run the entire update which seems wasteful in these scenario's

**Comment by markcellus** [comment]
Hmm this is news to me. I thought dependabot auto rebased PRs even if there isn't a conflict. At least I thought this is how it worked when we were on dependabot-preview. Some repos have the `Require branches to be up to date before merging` set in their [branch protection rules](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-status-checks-before-merging). This means that each PR needs to be up to date with master before it can be merged.

**Comment by jurre** [comment]
> Hmm this is news to me. I thought dependabot auto rebased PRs even if there isn't a conflict. At least I thought this is how it worked when we were on dependabot-preview. 

We've always only rebased when there's a reason to do so, but the logic is a little fuzzy tbh. None of that behavior has changed between preview and the GitHub native version. 

You can still force the PR to be recreated against the latest head sha by running the aforementioned `@dependabot recreate`, but that's a manual trigger.

**Comment by mikemhenry** [comment]
> Sorry, but I was not the one to enable auto-merge...

Sorry I should have been more clear -- also don't hit update branch!

Thanks for the clarification @jurre ! I thought that if there were conflicts with the main branch (because another dependabot PR was merged in) that the bot would automatically "rebase" the PR.

**Comment by jurre** [comment]
> I thought that if there were conflicts with the main branch (because another dependabot PR was merged in) that the bot would automatically "rebase" the PR.

Yes, that's indeed how it works. But there do need to be actual _conflicts_, not just newer commits in the default branch

**Comment by mikemhenry** [comment]
Got it! I was confused by the GitHub message "This branch is out-of-date with the base branch" and thought that was a condition that should trigger a rebase. Any plan to make that so something the bot can handle?

**Comment by jurre** [comment]
> Any plan to make that so something the bot can handle?

There's nothing currently in the pipeline, but I understand the problem now and agree this would be useful. It would just be good if there was a way to do it without having to re-run the entire update, as that is quite slow. I don't have a good answer right now, we'll need to think about it for a bit.
