### ISSUE TITLE
Duplicated PR created for a dependency present in just one of several packages in a monorepo

### ISSUE THREAD

**Issue by gnarea** [dependabot/dependabot-core#3443]
**Package ecosystem**

npm

**Manifest location and content prior to update**

- [`/package.json`](https://github.com/relaycorp/awala-gateway-desktop/blob/master/package.json)
- [`/packages/daemon/package.json`](https://github.com/relaycorp/awala-gateway-desktop/blob/master/packages/daemon/package.json)

**dependabot.yml content**

https://github.com/relaycorp/awala-gateway-desktop/blob/master/.dependabot/config.yml

**Updated dependency**

`@relaycorp/relaynet-testing` from 1.1.4 to 1.1.5

**What you expected to see, versus what you actually saw**

`@relaycorp/relaynet-testing` is only used in `/packages/daemon/package.json`, not in `/package.json`, so I expected to see just one PR for this dependency. Instead, I got 2 PRs, and the one for the root `package.json` doesn't actually change `/package.json`, but `/packages/daemon/package.json` -- so the two PRs are identical except for the PR titles.

**Images of the diff or a link to the PR, issue or logs**

The PR I'd expect: https://github.com/relaycorp/awala-gateway-desktop/pull/64

The additional PR I wouldn't expect: https://github.com/relaycorp/awala-gateway-desktop/pull/63

**Comment by Jericho** [comment]
This sounds very similar to #1408 which means that this problem is not limited to npm packages.

**Comment by gnarea** [comment]
I don't see this issue in any of the 40+ repos we have, except for the one repo where we use a monorepo. And roughly 50% of our repos use NPM and around 40% Gradle.

**Comment by jeffwidman** [comment]
Given the path to the dependabot config file mentioned in the original post, that was for Dependabot preview, before the service was rewritten native to GitHub.

I see on the repo (thankfully it's public) that you're still using Dependabot... Are you still seeing this?

**Comment by gnarea** [comment]
Thanks for looking into this @jeffwidman. I haven't seen this issue in ages so I'll go ahead and close this.

**Comment by jeffwidman** [comment]
That's great news! Thanks for letting us know.
