### ISSUE TITLE
pymysql[rsa] is not being bumped to latest (possibly due to the extra module?)

### ISSUE THREAD

**Issue by kevinlul** [dependabot/dependabot-core#3447]
**Package ecosystem**
pip
**Package manager version**
pip-compile
**Language version**
Python 2.7
**Manifest location and content prior to update**
https://github.com/ccmbioinfo/stager/blob/master/flask/requirements.in
https://github.com/ccmbioinfo/stager/blob/master/flask/requirements.txt
**dependabot.yml content**
https://github.com/ccmbioinfo/stager/blob/master/.github/dependabot.yml
**Updated dependency**
pymysql[rsa] 0.10.1 not updated
**What you expected to see, versus what you actually saw**
I expected pymysql to be bumped to the latest available version on PyPI (1.0.2) https://pypi.org/project/PyMySQL/#history but this has not occurred.
**Native package manager behavior**
```console
$ pip install pymysql[rsa]
Collecting pymysql[rsa]
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 645 kB/s 
Collecting cryptography
  Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 1.6 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.5-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
     |████████████████████████████████| 402 kB 5.2 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 6.0 MB/s 
Installing collected packages: pycparser, cffi, pymysql, cryptography
Successfully installed cffi-1.14.5 cryptography-3.4.7 pycparser-2.20 pymysql-1.0.2
```
**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment]
My understanding is that typically you don't pin the extra, you only pin the normal module and than that will inherit the version from its parent.

See https://github.com/dependabot/dependabot-core/issues/4720#issuecomment-1418723907 for details.

If for some reason I'm wrong, please comment and we can reopen.

**Comment by kevinlul** [comment]
Bruh, it's been two years
