### ISSUE TITLE
GET `https://api.dependabot.com/repos` failed

### ISSUE THREAD

**Issue by jasonycw** [dependabot/dependabot-core#3450]
Fail to get the repository on https://app.dependabot.com/accounts/{github_account}/

**Package ecosystem** nuget

**Package manager version** n/a

**Language version** .NET Core 3.1

**Manifest location and content prior to update** n/a

**dependabot.yml content** n/a

**Updated dependency** n/a

**What you expected to see, versus what you actually saw** The page should show all the added repo, but it failed

**Native package manager behavior** n/a

**Images of the diff or a link to the PR, issue or logs** 
![image](https://user-images.githubusercontent.com/4518597/113808170-0767d300-9798-11eb-8300-b805882426af.png)
![image](https://user-images.githubusercontent.com/4518597/113808404-83621b00-9798-11eb-83f5-be2edba2bf62.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue** n/a

**Comment by jurre** [comment]
Hi, could you share which account this happened for? That'll make it easier to figure out what happened. If you're uncomfortable sharing this publicly, feel free to reach out to support and they will route it to us.

**Comment by GeertvanHorrik** [comment]
Having the same issue. Account: WildGums (and all our other accounts, which I will keep private).

I have been clicking around, it looks that as soon as an account has private repos, it fails.

**Comment by jurre** [comment]
> Having the same issue. Account: WildGums (and all our other accounts, which I will keep private).
> 
> I have been clicking around, it looks that as soon as an account has private repos, it fails.

Thanks! It appears that account has a config variable set up for the public NuGet package index (https://api.nuget.org/v3/index.json) and this is causing an error on our side (we expect these to be private registries, and a Token to be present).

I'm working on a fix , but it should also be safe to remove that public URL from the config as Dependabot will always be able to pull from the public registry and no config for that is needed.

**Comment by GeertvanHorrik** [comment]
Thanks for the pointer, this is great, we have this for all our private registry restores. We have been having this for a while, so I can wait for a fix :)

**Comment by jurre** [comment]
This should work again. I would suggest considering migrating to the GitHub native version of Dependabot, it's a lot more robust in general and we have much better monitoring etc so when these sort of things happen they tend to be fixed quicker 🤞

**Comment by GeertvanHorrik** [comment]
Thanks, much appreciated.

Migration is on our todo list (but low prio because things are working as they are). We have a lot of repositories and we can easily sync the config files where I believe the new github native version requires clicking around (I could be wrong here). We also have very specific needs which packages to auto merge, etc.

**Comment by jurre** [comment]
> Migration is on our todo list (but low prio because things are working as they are). We have a lot of repositories and we can easily sync the config files where I believe the new github native version requires clicking around (I could be wrong here).

That makes sense 👍 we plan to make it much easier to mass-migrate soon. There should be no clicking around in the native version, but please do reach out with specific pain points that we can address either here or via username <at> thiswebsite dot com.

> Update: I can confirm it's working again for us!

Fantastic 🎉
