### ISSUE TITLE
Transitive public dependency of private gem not resolved

### ISSUE THREAD

**Issue by amake** [dependabot/dependabot-core#3461]
**Package ecosystem**

Bundler

**Package manager version**

2.2.9

**Language version**

Ruby 2.7.2

**Manifest location and content prior to update**

`/project-name/Gemfile`

**dependabot.yml content**

```yaml
version: 2
registries:
  rubygems-server-our-private-server:
    type: rubygems-server
    url: https://our-private-server.example.com
    username: "${{secrets.RUBYGEMS_SERVER_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_PASSWORD}}"
updates:
- package-ecosystem: bundler
  directory: "/project-name"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  registries:
  - rubygems-server-our-private-server
```

We are using GitHub-native Dependabot now, but our project is private so I can't link you to the actual `dependabot.yml`.

**Updated dependency**

We have a private gem hosted in the repository `rubygems-server-our-private-server`; let's call it `private-gem`.

`private-gem` has a dependency on [`locale`](https://rubygems.org/gems/locale) `~> 2.1`, which is publicly hosted on https://rubygems.org.

Our application's `Gemfile` has (relevant items only):

```rb
source 'https://our-private-server.example.com' do
  gem 'private-gem', '~> 0.1'
end
```

Our application's `Gemfile.lock` has (relevant items only):

```
GEM
  remote: https://rubygems.org/
  remote: https://our-private-server.example.com/
  specs:
    locale (2.1.3)
    private-gem (0.1.0)
      locale (~> 2.1)

DEPENDENCIES
  private-gem (~> 0.1)!
```

Neither of these gems have been updated, but they appear to be the trigger of the error described below.

**Images of the diff or a link to the PR, issue or logs**

The Insights > Dependency graph > Dependabot page is showing the following error:

```
Bundler::GemNotFound with message: Your bundle is locked to locale (2.1.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of locale (2.1.3) has removed it. You'll need to update your bundle to a version other than locale (2.1.3) that hasn't been removed in order to install.
```

Further, the Dependabot log shows:

```
  proxy | 2021/04/08 02:31:51 [066] GET https://our-private-server.example.com:443/quick/Marshal.4.8/private-gem-0.1.0.gemspec.rz
  proxy | 2021/04/08 02:31:51 [066] * authenticating rubygems server request (host: our-private-server.example.com)
⋮
  proxy | 2021/04/08 02:33:33 [180] GET https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.0.gemspec.rz
  proxy | 2021/04/08 02:33:33 [180] 200 https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.0.gemspec.rz
  proxy | 2021/04/08 02:33:33 [182] GET https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.1.gemspec.rz
  proxy | 2021/04/08 02:33:33 [182] 200 https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.1.gemspec.rz
  proxy | 2021/04/08 02:33:33 [184] GET https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.2.gemspec.rz
  proxy | 2021/04/08 02:33:33 [184] 200 https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.2.gemspec.rz
  proxy | 2021/04/08 02:33:33 [186] GET https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.3.gemspec.rz
  proxy | 2021/04/08 02:33:33 [186] 200 https://rubygems.org:443/quick/Marshal.4.8/locale-2.1.3.gemspec.rz
updater | INFO <job_108675550> Handled error whilst updating bundler: dependency_file_not_resolvable {:message=>"Bundler::GemNotFound with message: Your bundle is locked to locale (2.1.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of locale (2.1.3) has removed it. You'll need to update your bundle to a version other than locale (2.1.3) that hasn't been removed in order to install."}
```

Observations:
- Dependabot is correctly resolving `private-gem` on `our-private-server.example.com`.
- Dependabot *is* finding `locale` on rubygems.org (the `GET`s legitimately return 200 OK)
- Despite this, it seems as though Dependabot is expecting to find `locale` on `our-private-server.example.com`? We definitely do not re-host public dependencies there.

Other thoughts
- I don't understand the current support level for Bundler v2 in Dependabot given #1699. We have been using Dependabot Preview for many months with Bundler v2 without issue, but apparently it wasn't supported? Now we have moved to GitHub-native Dependabot and I *think* it worked for a bit but then started failing soon after.
- In Bunder 2.2.10+ they have split the `GEM` sections by remote for security reasons; we have *not* yet updated to that format. How will that affect things? Is this issue happening *because* we haven't updated yet?

**What you expected to see, versus what you actually saw**

Before we moved to GitHub-native Dependabot, we had been running in this configuration for months with no issues.

I expect that Dependabot would be able to check our dependencies as we are hosting them without error.
**Native package manager behavior**

Running `bundle` locally succeeds as expected.

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Unfortunately I can't easily provide a minimal repro because this involves private registries.

**Comment by jurre** [comment]
Thanks for reporting this @amake, that definitely seems weird

> I don't understand the current support level for Bundler v2 in Dependabot given #1699. We have been using Dependabot Preview for many months with Bundler v2 without issue, but apparently it wasn't supported? Now we have moved to GitHub-native Dependabot and I think it worked for a bit but then started failing soon after.

Yeah good question, what we do for bundler is basically strip out the `BUNDLED WITH` line from the lockfile, run the update with the latest bundler version we have installed (now 2.1.15, but used to be 1.7.3 before v2 support), and put back the `BUNDLED WITH` line. That actually mostly worked fine, but it broke down if you depended on bundler in the Gemfile, and we were missing some fixes that bundler had introduced.

> In Bunder 2.2.10+ they have split the GEM sections by remote for security reasons; we have not yet updated to that format. How will that affect things? Is this issue happening because we haven't updated yet?

Tbh I'm not entirely sure, we've not seen this before, but it does sound like it might! Are you able to give this a go? I believe `bundle update --bundler` will update the format.

If that doesn't work or isn't feasible I'll need to set up a repro, lmk. 🤞

**Comment by amake** [comment]
We updated to Bundler 2.2.15 with the new `Gemfile.lock` format and now Dependabot is working again!

**Comment by juanibiapina** [comment]
>  what we do for bundler is basically strip out the BUNDLED WITH line from the lockfile, run the update with the latest bundler version we have installed (now 2.1.15, but used to be 1.7.3 before v2 support), and put back the BUNDLED WITH line

:scream:

**Comment by jurre** [comment]
> That is really really scary. 😱

What do you find scary about it?

**Comment by juanibiapina** [comment]
It opens the possibility for all sorts of unpredictable problems, like this one for instance.

**Comment by jurre** [comment]
> It opens the possibility for all sorts of unpredictable problems, like this one for instance.

It has its tradeoffs for sure, but it saves a bunch of complexity as well. This scenario would have happened either way I think.

**Comment by gencer** [comment]
@jurre I have very same issue here. I have a private gem which depends on some other "public" gems and Dependabot Native seems to find it on GitHub Packages rather than Rubygems.org... Therefore, I do not get any PRs from Dependabot native.

```
PLATFORMS
  ruby

RUBY VERSION
   ruby 3.0.1p64

BUNDLED WITH
   2.2.17
```

However, I am able to install all gems locally (`bundle install`) and in CI/CD side.

Dependabot shows this error for every gem it checks:

```
updater | INFO <job_135224420> Handled error whilst updating puma: dependency_file_not_resolvable {:message=>"Bundler::GemNotFound with message: Your bundle is locked to dkim (1.0.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of dkim (1.0.1) has removed it. You'll need to update your bundle to a version other than dkim (1.0.1) that hasn't been removed in order to install."}
```

Yes, `dkim` is a public gem and my private gem depends on it. And, These are the logs where dependabot checks `dkim`:

```
proxy | 2021/05/18 18:39:21 [206] 200 https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=celluloid-gems%2Cchilkat%2Cfugit%2Crack%2Crest-client%2Csequel-bulk-audit%2Csequel-redis-cache
  proxy | 2021/05/18 18:39:21 [208] GET https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=dkim%2Cmail%2Cpg%2Csequel
  proxy | 2021/05/18 18:39:21 [208] * authenticating rubygems server request (host: rubygems.pkg.github.com)
  proxy | 2021/05/18 18:39:21 [208] 200 https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=dkim%2Cmail%2Cpg%2Csequel%2Cwork_queue
  proxy | 2021/05/18 18:39:21 [210] GET https://index.rubygems.org:443/versions
  proxy | 2021/05/18 18:39:21 [210] 304 https://index.rubygems.org:443/versions
  proxy | 2021/05/18 18:39:22 [214] GET https://index.rubygems.org:443/info/work_queue
  proxy | 2021/05/18 18:39:22 [214] 200 https://index.rubygems.org:443/info/work_queue
  proxy | 2021/05/18 18:39:22 [216] GET https://index.rubygems.org:443/info/dkim
  proxy | 2021/05/18 18:39:22 [216] 200 https://index.rubygems.org:443/info/dkim
  proxy | 2021/05/18 18:39:23 [218] GET 
```
