### ISSUE TITLE
Unclear how to apply pull-request-branch-name.separator changes to existing PRs

### ISSUE THREAD

**Issue by lattwood** [dependabot/dependabot-core#3467]
**Package ecosystem**
I believe it's any but we're experiencing it with npm/yarn.

When you change the `pull-request-branch-name.separator`, there isn't a straight forward way to recreate the security fix branches that may have already been opened.

**Comment by jurre** [comment]
The setting only applies to new PRs created, there's currently no way to retroactively do this.

**Comment by lattwood** [comment]
This results in the creation of PRs that will never successfully build, and no way to make successfully build through actions on dependabot. Hence filing a bug.

I tried disabling dependabot, deleting prs & branches, then re-enabling with no luck.

**Comment by jurre** [comment]
> This results in the creation of PRs that will never successfully build, and no way to make successfully build through actions on dependabot. Hence filing a bug.

Why is that exactly? It's just the branch name that changes with this setting, how does that cause the build to fail?

**Comment by lattwood** [comment]
For the same reason the configuration options was added originally: https://github.com/dependabot/dependabot-core/issues/396#issue-318461739

**Comment by jurre** [comment]
Ah, I see, you have a build process set up that requires a certain format of the branch name to build docker images.

There is some manual work I can do to wipe out the old PR in the database, if you contact support with the repositories and pull-requests (I'm assuming they're private and you would rather not share publicly) in question I'll figure out a safe way to do it, but it might take a few days before I get to it. If you reference this issue, it'll get routed back to me.

**Comment by lattwood** [comment]
Ooof. We turned it on for ~11 repos with a bunch of open security dependabot PR yesterday :\

**Comment by jurre** [comment]
> Ooof. We turned it on for ~11 repos with a bunch of open security dependabot PR yesterday :\

If it's all the Dependabot PR's on those repo's, I can maybe make that work as well.

I guess there's no way to gsub the `/` for a `-` in the build process?

**Comment by jeffwidman** [comment]
Closing, as I don't see us taking the time to make this feature apply retroactively to previously opened PR's. For repos where this is a blocker and need a one-time migration, the workaround of filing a support request and having us do a manual wipe of the outstanding PR's is sufficient for now.
