### ISSUE TITLE
yarn major/minor/patch upgrade flags

### ISSUE THREAD

**Issue by Incognito** [dependabot/dependabot-core#347]
Could be interesting to add support for this yarn feature:
https://github.com/yarnpkg/yarn/commit/1522cdeee64f7eebfc4a0e4c3596158654f21692

I think some of the teams here might use it.

**Comment by greysteil** [comment]
Interesting - thanks for the heads up. I'll have a think about how we could incorporate it.

**Comment by greysteil** [comment]
I'm going to close this for now and come back to it if/when Dependabot ever decides to expand it's tool suite for library authors. Thanks for the heads up on it, though!
