### ISSUE TITLE
Support centralized versions TOML added in gradle 7.0

### ISSUE THREAD

**Issue by yogurtearl** [dependabot/dependabot-core#3471]
as a stop gap until https://github.com/dependabot/dependabot-core/issues/1164 is done, it would be great to support the new `gradle/libs.version.toml` file supported in Gradle 7.0

See
https://docs.gradle.org/nightly/userguide/platforms.html#sub:conventional-dependencies-toml

[Full support thru Gradle Tooling API is the full solution](https://github.com/dependabot/dependabot-core/issues/1164) and this would just be a bandaid until that is supported

**Comment by huehnerlady** [comment]
is that maybe a duplicate of https://github.com/dependabot/dependabot-core/issues/3121? 🤔

**Comment by zbynek** [comment]
@asciimike could this be closed as duplicate?

**Comment by asciimike** [comment]
Closing as a dupe of #3121, per above
