### ISSUE TITLE
.yarnrc registry regex incorrect

### ISSUE THREAD

**Issue by joshuagiggxon** [dependabot/dependabot-core#3474]
https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L15

Regex for .yarnrc registry is:

```
/^(?:--)?registry\s+['"](?<registry>.*)['"]/
```

But it's common to wrap registry in quotes, which then fails to match.

e.g. (copied from a Google Search)

```
registry "https://nexus.dev/repository/npm-proxy/"
"@mycompany:registry" "https://myserver.dev/repository/npm-releases/"
```

**Comment by jakecoffman** [comment]
This was fixed by https://github.com/dependabot/dependabot-core/pull/5840
