### ISSUE TITLE
Allow disabling for npm dev dependencies

### ISSUE THREAD

**Issue by siddharthvp** [dependabot/dependabot-core#3475]
Many JS/TS packages use a large number of build tools which are updated often – creating a lot of dependabot PRs. It would be helpful if it is possible to disable dependabot PRs for npm dev dependencies but keep them enabled for the regular npm dependencies.

**Comment by asciimike** [comment]
Specifically you're looking for `allow`'s `dependency-type: development` applied to `ignore`? In general, I think we've got work to do on making `allow` and `ignore` symmetrical, and I've captured that here: https://github.com/dependabot/dependabot-core/issues/3479.

Please feel free to comment on that issue, as it will resolve this category of issue; if that's not the case, feel free to reopen this!
