### ISSUE TITLE
Upgrading Dependencies in Lockstep or: How I Learned to Stop Worrying and Love the Build Failures

### ISSUE THREAD

**Issue by lattwood** [dependabot/dependabot-core#3476]
Because of how awscli, boto3, and botocore are versioned, it would be awesome to have dependabot open **one PR** instead of the three it currently opens. This is because of the version constraints in the respective modules.

I see two potential solutions. One is allowing folks to specify groups of dependencies that should be upgraded in lockstep. The other is having dependabot figure out which dependencies **have** to be upgraded in lockstep. Not sure which one is the bigger lift.

#### awscli upgrade PR failure message
```
The conflict is caused by:
    The user requested botocore==1.20.48
    awscli 1.19.49 depends on botocore==1.20.49
```

#### botocore upgrade PR failure message
```
The conflict is caused by:
    The user requested botocore==1.20.49
    awscli 1.19.48 depends on botocore==1.20.48
```

#### boto3 upgrade PR failure message
```
The conflict is caused by:
    The user requested botocore==1.20.48
    awscli 1.19.48 depends on botocore==1.20.48
    boto3 1.17.49 depends on botocore<1.21.0 and >=1.20.49
```

My workaround is creating a new branch with the three branches octopus merged and opening a PR for that. Unfortunately the GitHub UI doesn't support doing that from a browser. :(

If I was willing to let builds on `main`/`master` fail briefly, I could merge the PRs in rapid succession.

**Comment by asciimike** [comment]
I believe the feature you're looking for is https://github.com/github/roadmap-internal/issues/299 (which is also discussed here: https://github.com/dependabot/dependabot-core/issues/1190), as that should create one PR for you to merge. I'll close this since I believe it's already captured there, but let me know if that's not the case.

**Comment by lattwood** [comment]
![image](https://user-images.githubusercontent.com/6198952/114425756-c3a60c80-9b8f-11eb-92b2-7916016bfe96.png)
c'mon dude, don't be linking to stuff us plebeians can't see.

**Comment by asciimike** [comment]
Ugh, apologies, linked to the public roadmap issue!

**Comment by asciimike** [comment]
As a side note, I would expect that this feature would be configurable for version updates as well as security updates.

**Comment by dreid** [comment]
@asciimike 

> I believe the feature you're looking for is [github/roadmap#148](https://github.com/github/roadmap/issues/148) (which is also discussed here: #1190), as that should create one PR for you to merge. I'll close this since I believe it's already captured there, but let me know if that's not the case.

The linked roadmap issue only specifically mentions doing a single PR if you have multiple projects in a single repo that have the same dependency.

This issue appears to be about multiple related dependencies that need to be updated in lockstep.

**Comment by asciimike** [comment]
@dreid I consider both to be in scope for when we eventually build grouped update functionality. Next time I can update the public roadmap issue, I'll try to make it more generic, and as we get closer to implementation, it'll get tightened back down.

I think grouped updates can mean a few things:
 - group all the updates for an ecosystem in a single manifest into N commits in a single PR (likely the more common version update scenario)
 - group all the updates for a specific dependency across all manifests into N commits in a single PR (likely the more common security update scenario)
