### ISSUE TITLE
'Signed-off-by' value doesn't match commit author data

### ISSUE THREAD

**Issue by christophebedard** [dependabot/dependabot-core#3480]
Note that I have searched existing issues and have not found anything that matches my issue.

**Package ecosystem**

npm (unrelated)

**Package manager version**

N/A

**Language version**

N/A

**Manifest location and content prior to update**

N/A

**dependabot.yml content**

https://github.com/christophebedard/tag-version-commit/blob/d19e9cce9cd0e6ccaa4b6fa73ed533c6692588fe/.github/dependabot.yml

**Updated dependency**

N/A

**What you expected to see, versus what you actually saw**

Some projects use the "developer certificate of origin" (DCO) kind of standard: https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

This is most often done by asking users to sign off commits with the `-s` flag for `git commit`, which adds a line to the commit message, e.g. `Signed-off-by: Author Name <email@domain.com>`.

Most "DCO checking" implementations require that the commit author data matches the `Signed-off-by:` info.

dependabot had been complying up until a couple weeks ago; it might have coincided with my switch to GitHub/native dependabot.

Now dependabot signs off with:

> Signed-off-by: dependabot[bot] <support@github.com>

but the commit author data is:

> dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

so the DCO check fails.

**Proposed fix**

Assuming you want to keep having that support email in the commit sign off, a simple fix would be to add another `Signed-off-by:` line with author/email info that matches the commit author data. The DCO checking tool I use (https://github.com/christophebedard/dco-check), and probably others, I assume, would see that as being valid. They wouldn't mind the extra sign off data that doesn't match the commit author data.

**Native package manager behavior**

N/A

**Images of the diff or a link to the PR, issue or logs**

https://github.com/christophebedard/tag-version-commit/pull/260, see: https://github.com/christophebedard/tag-version-commit/pull/260/checks?check_run_id=2320958149#step:4:23:

> Checking commits: d19e9cce9cd0e6ccaa4b6fa73ed533c6692588fe..3a1b540a36758a4bf18ac652b93fb35d5d1f010c
> 
> 	3a1b540a36758a4bf18ac652b93fb35d5d1f010c
> 	dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> 	Bump eslint-plugin-jest from 24.3.1 to 24.3.5
> 	Bumps [eslint-plugin-jest](jest-community/eslint-plugin-jest) from 24.3.1 to 24.3.5.
> 	- [Release notes](jest-community/eslint-plugin-jest/releases)
> 	- [Changelog](jest-community/eslint-plugin-jest@main/CHANGELOG.md)
> 	- [Commits](jest-community/eslint-plugin-jest@v24.3.1...v24.3.5 (compare))
> 	Signed-off-by: dependabot[bot] <support@github.com>
> 		found sign-off: dependabot[bot] <support@github.com>
> 
> Missing sign-off(s):
> 
> 	3a1b540a36758a4bf18ac652b93fb35d5d1f010c
> 		sign-off not found for commit author: dependabot[bot] 49699333+dependabot[bot]@users.noreply.github.com; found: ['dependabot[bot] <support@github.com>']

https://github.com/christophebedard/tag-version-commit/pull/261

**🕹 Bonus points: Smallest manifest that reproduces the issue**

N/A

**Comment by AraHaan** [comment]
I would be for replacing what signoff it does provide with the one from the commit author it set.

Cant they fix it by doing what ``git commit --signoff`` would do when they made the commit like how you would expect?

**Comment by christophebedard** [comment]
> Cant they fix it by doing what `git commit --signoff` would do when they made the commit like how you would expect?

yeah, it should be an easy fix!

**Comment by jeffwidman** [comment]
Tangetially related:
* https://github.com/dependabot/dependabot-core/issues/3849
* https://github.com/dependabot/dependabot-core/issues/2454

**Comment by nigelmegitt** [comment]
I just hit this issue too: the [DCO-2 app](https://github.com/apps/dco-2) does not consider Dependabot commits to be appropriately signed off, and it's correct.

Signed-off by line:

```
Signed-off-by: dependabot[bot] <support@github.com>
```

Commit verified as coming from:

```
dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
```

So the email addresses do not match up, and they should.
