### ISSUE TITLE
Support private git repos in the pip ecosystem

### ISSUE THREAD

**Issue by Gidgidonihah** [dependabot/dependabot-core#3494]
According [to the documentation](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#package-ecosystem), at this time the pip ecosystem (pip, piping, pip-compile and poetry) do not support private git repositories.

Recently [support was added](https://github.blog/2021-03-15-dependabot-private-dependencies/) for several non-pip ecosystems.

Details were given about my attempts to use private repos within the pip ecosystem on a ticket (https://github.com/dependabot/dependabot-core/issues/2488#issuecomment-819782685) about private registries, rather than private repositories.

**Comment by asciimike** [comment]
Thanks for submitting this! As @jurre mentioned, we've got an internal issue tracking this, and hopefully we can add it soon (via the same mechanism that private registries use).

**Comment by mctofu** [comment]
As a workaround you can use private registry support to access a private git repo via an access token.

Use the `git` registry type: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#git

For pip you'll also need to allow the `insecure-external-code-execution` option: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#registries

**Comment by vbuaraujo** [comment]
Why is `insecure-external-code-execution` required for private pip repos but not for public pip packages? And why dependabot-preview did not require a configuration like this? Just trying to understand what is going on and what are the risks involved.

**Comment by asciimike** [comment]
> Why is insecure-external-code-execution required for private pip repos but not for public pip packages?

See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#insecure-external-code-execution, TL;DR: it's because on private registries, you've got secrets that the update process could leak, while on public registries you don't have these credentials.

> And why dependabot-preview did not require a configuration like this?

It probably should have, and now we've fixed the glitch ;)

**Comment by mblakesley** [comment]
@asciimike can you say a little bit more about this? Why is this unique to `pip`? We have another project using `npm` with the same private repo and it doesn't need the option `insecure-external-code-execution`. Also, how insecure is this option?

**Comment by jeffwidman** [comment]
Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/6147. I realize that one is much newer, but it also has a lot more debugging information about the various package managers current behavior.

**Comment by shelper** [comment]
maybe this one is related? https://github.blog/2021-03-15-dependabot-private-dependencies/#updates-from-private-github-repositories
