### ISSUE TITLE
Rebase-strategy not limited to conflicts

### ISSUE THREAD

**Issue by electrofelix** [dependabot/dependabot-core#3502]
**Package ecosystem**
likely all, but seen with docker and gomod
**dependabot.yml content**
```
version: 2
registries:
  my-registry:
    type: docker-registry
    url: <private-registry>
    username: <secret>
    password: <secret>
updates:
  - package-ecosystem: "docker"
    directory: "/"
    registries:
    - my-registry
    schedule:
      interval: "daily"
```
**What you expected to see, versus what you actually saw**
Expect that after approval of a multiple dependabot PRs, coupled with a custom workflow to automatically merge the target branch into the each PR targetting the same branch on each update to the target branch, that the dependabot PRs will be automatically updated and provided it passes CI will be merged. This should trigger a merge into any remaining dependabot PRs targeting the same branch, until such time that all approved dependabot PRs merge without requiring further intervention unless there is a conflict created.

What we see is dependabot always rebases all proposed PRs when anything is merged thus removing approvals due to the force push. Potentially this may be caused by enabling requiring branches be up to date with the target branch will also trigger this behaviour. As we have enabled the setting as described by https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule 
![image](https://user-images.githubusercontent.com/912324/114894595-af1f7980-9e06-11eb-8de4-5b5c4edc8ac7.png)

According to https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#rebase-strategy, the rebase should only occur if there was a conflict.
![image](https://user-images.githubusercontent.com/912324/114896700-74b6dc00-9e08-11eb-9576-3b68e480a24e.png)

This may well just a documentation bug rather than behaviour bug. For teams that set require branch to be up to date with target before merging, the current behaviour may well be ideal where the have an action that automatically merges dependabot PRs. However it is surprising for this to occur when the documentation says it should only happen if there was a conflict.

If it was possible for this to only occur when there is an actual conflict it would be ideal, because we'd be happy enough to have to re-approve anything that conflicted and had to be recreated from scratch. Happy to add a separate enhancement request around having additional strategies to allow teams to customize the outcome here depending on their needs, just want to get confirmation on whether the observed behaviour is the expected behaviour and the documentation needs a slight adjustment to make it clearer, or if expected behaviour was the intention and thus this is a functional bug.

After the force pushes it appears some information disappears so I can look to capture screenshots of the review approving the PR before it is dismissed by the force push. As these are for private repos I can't just link to the affected PRs.

**Comment by jurre** [comment]
> What we see is dependabot always rebases all proposed PRs when anything is merged 

Yeah that's right, when you merge a PR the manifest files change and this triggers a rebase. We don't check for actual conflicts, we just detect if the files in question have been changed.

> This may well just a documentation bug rather than behaviour bug. 

Agreed, I think we can definitely improve the docs around this 👍 

> If it was possible for this to only occur when there is an actual conflict it would be ideal

Yeah, I get the use-case 👍 I'm not sure if we can easily determine actual conflicts, but it's definitely something we can investigate

**Comment by brrygrdn** [comment]
👋🏻  @electrofelix - we've clarified our documentation to reflect that we will rebase PRs on _changes_ rather than conflicts as it more correctly reflects the current functionality.

I've marked this issue as a `feature request` rather than a bug as it is something we should investigate improving on as @jurre said.

**Comment by electrofelix** [comment]
Thanks, it makes total sense that is the way it works, because most will benefit from that.

**Comment by electrofelix** [comment]
Would https://docs.github.com/en/graphql/reference/objects#pullrequest the mergeable which is an enum that can indicate if it is mergable, conflicting, or still being calculated be sufficient to determine this https://docs.github.com/en/graphql/reference/enums#mergeablestate?

Unclear for the REST API if https://docs.github.com/en/rest/reference/pulls#get-a-pull-request whether the `mergeable` field is the same as the example has it returning a boolean.

Thought there is always `mergeable_state` that suggests it could provide a bit more info.

**Comment by gustavovnicius** [comment]
A comment on the documentation:

Isn't a pull request supposed to be rebased when it detects changes to the `target-branch`?

![Screenshot 2021-05-06 at 11 42 02](https://user-images.githubusercontent.com/2379486/117277380-207ba680-ae60-11eb-98b1-8902b2dbf499.png)

**Comment by electrofelix** [comment]
@gustavovnicius the documentation was updated to change from saying on conflict to on any change to clarify the behaviour. I think this is being kept open because it would be useful if you could limit it to rebase on conflicts only in situations where you want a different workflow that still involves manual approval and ensuring the status checks pass against what will be the result of merging the PR.

**Comment by gustavovnicius** [comment]
I understand that @electrofelix , my question is:

Let's say we have the branches `main` and `dependabot-maven-main-<dependency>`. And I have linear protection enabled on `main`, which is also my `target-branch`.

When I push something new to `main` isn't the expected behavior that the dependabot branch gets rebased from the latest `main`?

**Comment by electrofelix** [comment]
@gustavovnicius I missed what you meant. That would make more sense to me too, I guess the documentation update might need another small update :wink:

**Comment by jeffwidman** [comment]
👋 sorry for the slow followup here.

> What we see is dependabot always rebases all proposed PRs when anything is merged thus removing approvals due to the force push. 

I should also point out that part of the difficulty here is that you've set your repo settings such that new commits dismiss old approvals. If you relax that, you can keep the workflow mentioned in the first post.

Re: the docs improvements... these docs are open source, please feel free to open a PR if you think a small (or large!) tweak could improve them.

I'm going to close as I don't think for the forseeable future Dependabot will be able to realize whether or not there's a conflict on the changed files... there's too many variables across all the different ecosystems we support, so regenerating the manifest files whenever they change avoids a massive case of edge-case headache. And the docs, while they could be slightly improved as mentioned ☝️ , are still reasonably clear for the general intent.
