### ISSUE TITLE
[go] Drop support for `dep`, as everyone is now moving to `go mod`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3529]
I noticed several references in the source to `dep` which was a package manager that was a precursor to `go mod`. 

Now that `go mod` is finalized and built into the standard lib, the ecosystem is migrating to that, so it's probably worth dropping support for `dep` completely. 

That would simplify the code for both maintainers and drive-by readers (such as myself) since I could safely assume that the code works according to expected `go mod` paradigm, rather than being afraid there are edge cases I don't realize that may be causing subtle bugs when `dep` behavior is accidentally mis-applied to `go mod`... 

Examples of `dep` references:
* https://github.com/dependabot/dependabot-core/blob/760b69a68962c4692d5d7dd8fef8fa36e6f2d9f8/go_modules/lib/dependabot/go_modules/requirement.rb#L135
* https://github.com/dependabot/dependabot-core/blob/760b69a68962c4692d5d7dd8fef8fa36e6f2d9f8/go_modules/lib/dependabot/go_modules/update_checker.rb#L113

**Comment by jurre** [comment]
`dep` is already deprecated in dependabot already, it's not supported in the GH native version of Dependabot, and it's marked as deprecated in dependabot-preview. We're planning to remove the codepath entirely, I think the references in the `go_modules` implementation are leftovers from when in was ported from the `dep` code, there are two top level folders: `go_modules` and `dep` which each house the implementation for that package manager.

Those references should probably be cleaned up though, thanks for pointing them out.

**Comment by jeffwidman** [comment]
I put up https://github.com/dependabot/dependabot-core/pull/3537 to remove the outdated references. 

I hadn't even seen the separate `dep` folder... yeah, makes sense to just clear that out completely.

**Comment by jeffwidman** [comment]
I also put up https://github.com/dependabot/dependabot-core/pull/3538 to remove the `dep` folder... no need to keep maintaining it IMO. Anyone still stuck with `go dep` is likely also going to be stuck with an older version of dependabot so they are unlikely to be impacted...

**Comment by AraHaan** [comment]
Unless they use the github native dependabot.

**Comment by jeffwidman** [comment]
>> Anyone still stuck with go dep is likely also going to be stuck with an older version of dependabot so they are unlikely to be impacted...
> Unless they use the github native dependabot.

Except that [github-native dependabot doesn't support `dep`](https://github.com/dependabot/dependabot-core/issues/3529#issuecomment-823837664).

**Comment by jeffwidman** [comment]
Closed by #3538
