### ISSUE TITLE
[question] ignore package names or wildcards

### ISSUE THREAD

**Issue by christopherthielen** [dependabot/dependabot-core#353]
Some packages I want to keep at a specific version.  I'd rather not receive PRs for these packages.  Is it currently possible?

**Comment by greysteil** [comment]
Absolutely - if you comment `@dependabot ignore this dependency` then Dependabot will close the PR and not bother you about that dependency again (unless you update it yourself). Will that work for you?

**Comment by christopherthielen** [comment]
Moved to https://github.com/dependabot/feedback/issues/133

**Comment by christopherthielen** [comment]
oh wow, you're fast @greysteil 
:)

**Comment by greysteil** [comment]
Haha, just slightly too slow, though! 😉
