### ISSUE TITLE
Issue with "key not found: :security_updates_only" on a python repo

### ISSUE THREAD

**Issue by alk-jozog** [dependabot/dependabot-core#3535]
Hello,
we have an issue on a python repository in which we host our Ansible codebase. Ansible and its dependencies are managed with Pipenv. It used to work fine but we have noticed that we don't receive PR from Dependabot anymore for a few weeks.

[Here is our Pipfile, stored at /Pipfile](https://github.com/dependabot/dependabot-core/files/6351598/Pipfile.txt)

Our settings (just using default values):
![dependabot-settings](https://user-images.githubusercontent.com/50452850/115570745-aa533d80-a2be-11eb-9e18-464d0975b6eb.png)

In dependabot UI there is no error but when checking the update logs, we see Status: timed_out with the following logs:
[dependabot.log](https://github.com/dependabot/dependabot-core/files/6351592/dependabot.log)

Is there something wrong with our setup as this is not a "true" python project ?

Thanks for your help.

**Comment by asciimike** [comment]
@alk-jozog looks like you're using Dependabot Preview. Would you mind updating to GitHub native Dependabot (you can migrate directly on https://app.dependabot.com!) and trying again?

**Comment by jurre** [comment]
This was a regression in preview that has since been fixed, but yeah I'd also second Mike's recommendation to update to native, which is more robust and where this didn't happen 👍
