### ISSUE TITLE
Race condition in Dependabot PR creation

### ISSUE THREAD

**Issue by WyriHaximus** [dependabot/dependabot-core#3544]
When adding Dependabot native to https://github.com/WyriHaximus/php-phpstan-rules-wrapper I came across some unexpected behaviour. It's configured with one open PR limit. And every time when a PR is merged it runs Dependabot again, which is really cool because that's a feature that's rather handy, but I never got around requesting. Anyway, when that happens it will fail to open new PR's because of the open PR limit. However, there are no more PR's open at the time the error is occurring. It looks like this at that moment in time:

![image](https://user-images.githubusercontent.com/147145/115765766-71db5e80-a3a7-11eb-87f6-2d43a24f2860.png)

The only thing I can think off is that during the merge of a PR Dependabot Native kicks off and checks the number of PR's it has open at that moment, which it thinks is one. And as a result the check for possible PR's fails. One that repository the behaviour is 100% reproducible. And judging by the logs it has 3 more PR's lined up.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

This issue is over a year old, and we've pushed a lot of improvements/bugfixes to our internal infrastructure since then... is this still a valid / reproducible issue?

If it is still 100% reproducible on that repo let me know.

**Comment by WyriHaximus** [comment]
@jeffwidman Not 100% if this is still the case. But will do some tests and let you know.

**Comment by WyriHaximus** [comment]
Think it just happened here https://github.com/WyriHaximus/php-test-utilities/pull/670  was opened with outdated information after https://github.com/WyriHaximus/php-test-utilities/pull/669 was merged.

**Comment by WyriHaximus** [comment]
Will set up an example repo later tonight

**Comment by WyriHaximus** [comment]
Set up https://github.com/WyriHaximus/dependabot-probable-sniffle this morning, will try to get it in the race condition again

**Comment by jeffwidman** [comment]
Were you able to get this into the race condition again?

**Comment by WyriHaximus** [comment]
Only seen it once or twice, but none of them were reproducible. So closing this issue :+1:

**Comment by jeffwidman** [comment]
Sounds good. And if you do see it, please let us know, we might be able to track it down.

**Comment by WyriHaximus** [comment]
Will do :+1:
