### ISSUE TITLE
Command to switch target-branch of a specific Pull request

### ISSUE THREAD

**Issue by Andre601** [dependabot/dependabot-core#3546]
## Idea
A command like `@dependabot switch <branch>` should exist that, when used, would change the PRs target branch to the one provided.
If the branch doesn't exist would Dependabot create it and then switch the branch of the PR to it. Perhaps to prevent conflicts or accidental branch creation due to typos should this action perhaps require an additional argument or a sort of `--flag` thing to make it create a branch when not existing.

## Why?
Repositories may have a setup that is hooked directly into a System like a CI/CD-Server that takes whatever push was made towards a branch to do what it was set to do.
The issue here is, that with a breaking change from a PR, this merge could trigger a failing run because the code itself also would need an update to mirror the breaking changes.

Having this option would essentially allow maintainers to have a separate branch, where they also can alter their code to then make a single merge (Or maybe multiple if you merge the Dependency update separately) into the main branches, which then would result in functional CI/CD-Runs.

I myself encountered this issue, where The setup-java action had a breaking change. I didn't notice it in the changelog and had to fix it in multiple separate commits because the runs were constantly failing due to the breaking change.
While I now look closer at changelogs do I still have to take the intentional risk of a CI-run failing due to the dependency having breaking changes that require me to manually update them.

**Comment by mwaddell** [comment]
Related to #2721

I recommend using a custom github action (like https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#common-dependabot-automations) which runs when your PR is created and it creates your new PR on a different branch, does a rebase against that and then closes dependabot's one.

I'm not sure how dependabot would apply changes calculated against one branch against another one without knowing for certain that they share a common history - this would be something you would enforce in your own action.

**Comment by jeffwidman** [comment]
👋 Sorry for the radio silence here.

It's an interesting idea, but I'm closing as I just don't see us doing this in the forseeable future due to a combination of lack of user need + complexity to implement. If you really want it you can script it using GitHub Actions to run the `dependabot-core` lib yourself using something like https://github.com/dependabot/dependabot-script.
