### ISSUE TITLE
Dependabot seems to ignore FROM mcr.microsoft.com/dotnet/sdk:5.0.101 AS build-env line

### ISSUE THREAD

**Issue by leotsarev** [dependabot/dependabot-core#3567]
**Package ecosystem**
docker
**Language version**
.NET 5
**Manifest location and content prior to update**
https://github.com/joinrpg/joinrpg-net/blob/aaf24110fb4ad21619af721fb508ec8319409d60/src/JoinRpg.Portal/Dockerfile
**dependabot.yml content**
https://github.com/joinrpg/joinrpg-net/blob/aaf24110fb4ad21619af721fb508ec8319409d60/.github/dependabot.yml
**What you expected to see, versus what you actually saw**
See `FROM mcr.microsoft.com/dotnet/sdk:5.0.101 AS build-env`
I expect this upgraded to:
`FROM mcr.microsoft.com/dotnet/sdk:5.0.202 AS build-env`

**Comment by leotsarev** [comment]
Hey, what can I do to help with this bug moving forward?

**Comment by leotsarev** [comment]
Polite ping

**Comment by leotsarev** [comment]
@jurre sorry for pinging, but I don't know who to connect to get this bug moving.

**Comment by deivid-rodriguez** [comment]
Hei @leotsarev! So sorry for taking so long to get back.

This is a bug where the presence of a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of a manifest confuses Dependabot.

Fix is coming at #6714!
