### ISSUE TITLE
Delete outdated fork of vcs

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3579]
It looks like https://github.com/dependabot/vcs is a leftover remnant that is no longer needed as of https://github.com/dependabot/dependabot-core/commit/ab8b04caab507f139c38f6e3571a740eb5bfecf2#diff-fbfe30a54b3219fea06853067f5338d0afa3dd33d683edf7129aa25304c840d1 which landed two years ago.

Should that fork be deleted (or at least archived for now) to reduce confusion for outsiders trying to come up to speed on how this all fits together?

**Comment by jeffwidman** [comment]
nudge @jurre @mctofu

**Comment by jurre** [comment]
I've archived it, I don't think it's been used for a very long time
