### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by Strikerrr** [dependabot/dependabot-core#358]
Tried to sign in with github and it said it fails

**Comment by greysteil** [comment]
It would also be great to get full details of the flow you went though - if you can replicate and provide screenshots that would be fantastic.

**Comment by Strikerrr** [comment]
Of course, it's no problem. I'll do it and write down each step

**Comment by Strikerrr** [comment]
Okay so, I went to the dependabot.com website and clicked sign up then it redirected to the sign in with github page. I clicked the button, then it opened up Fasthub's in-built chrome and then it tells me authentication error.

**Comment by Strikerrr** [comment]
[](https://i.imgur.com/p8svSIH.jpg)

**Comment by Strikerrr** [comment]
Did the image appear?

**Comment by Strikerrr** [comment]
![Image](https://i.imgur.com/JoFjILM.jpg)

**Comment by greysteil** [comment]
Afraid not

**Comment by Strikerrr** [comment]
There, should be there now

**Comment by Strikerrr** [comment]
Thanks, I found this project and was quite interested because I make some node modules and I'd like to have this to keep our deps up to date.

**Comment by greysteil** [comment]
Well hopefully we can help you with that! I've never seen this error before, and we've got a few thousand people using Dependabot. Is there a chance that it's an issue that's specific to FastHub? Would you mind checking the flow in another browser?

**Comment by greysteil** [comment]
Looking through the frontend code we're using session storage to handle the OAuth redirect flow - this error is coming from that, and never touching the backend. Hence my suspicion it's FastHub.

**Comment by Strikerrr** [comment]
Indeed it was fasthub. Would you suggest I open an issue to their repo as this can be an issue for a lot more oauth apps?

**Comment by greysteil** [comment]
Yes - I don't think this one has anything to do with Dependabot. We've got the following in our frontend codebase, which looks entirely reasonable to me, if you want to include it in the issue:

```
const queryParams = queryString.parse(window.location.search);
const storedState = window.sessionStorage.getItem("dependabot.oauthState");
if (storedState !== queryParams.state) {
  this.setState({ stateError: true });
}
```

Thanks for your help debugging this one, and let me know how you get on with Dependabot!

**Comment by Strikerrr** [comment]
Alright, I'll get on to Fasthub now and report this. Cheers for the fast response, and I got it working in the end and it's already doing its job ;)
