### ISSUE TITLE
Whitelist certain GitHub Action yml files to be versioned by dependabot?

### ISSUE THREAD

**Issue by tobiasehlert** [dependabot/dependabot-core#3582]
I am wondering if it's possible to activate dependabot updating of version for a list of yml files?
Maybe some whitelisting possibility that I can't find in the documentation?

In a private repo I am in, there are around 25 yml files and we only want dependabot to act one 3 of those.. :)

Regards,
Tobias

**Comment by asciimike** [comment]
I believe you should be able to use [`allow`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#allow) or [`ignore`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore) with the name of the actions to handle this.
