### ISSUE TITLE
Migration notes are confusing

### ISSUE THREAD

**Issue by eps1lon** [dependabot/dependabot-core#3591]
We just received the PR that updates the dependabot config to v2 (https://github.com/mui-org/material-ui/pull/26024).

This PR mentions
> please merge this PR and migrate to GitHub-native Dependabot before then.

If I need to "migrate to GitHub-native Dependabot before then" why not mention this first?

```diff
-please merge this PR and migrate to GitHub-native Dependabot before then
+please migrate to GitHub-native Dependabot and then merge this PR
```

I then visited [Learn more about migrating to GitHub-native Dependabot](https://docs.github.com/en/code-security/supply-chain-security/upgrading-from-dependabotcom-to-github-native-dependabot) to find out how to "migrate to GitHub-native Dependabot".
Though this page says I only have to merge the PR:
> Upgrading from Dependabot Preview to GitHub-native Dependabot requires only one step: merge the Upgrade to GitHub-native Dependabot pull request in your repository.

-- https://docs.github.com/en/code-security/supply-chain-security/upgrading-from-dependabotcom-to-github-native-dependabot#upgrading-to-github-native-dependabot

I interpret this as  
```diff
-In order to keep getting Dependabot updates, please merge this PR and migrate to GitHub-native Dependabot before then.
+In order to keep getting Dependabot updates, please merge this PR.
```

being sufficient. Is that interpretation accurate?

**Comment by jurre** [comment]
Thanks @eps1lon, yep the only thing you have to do is merge the PR, and then you will be migrated to GitHub-native.

cc @asciimike can we clarify that a bit further?

**Comment by asciimike** [comment]
The majority of folks only need to merge the PR, then they're migrated. Folks who are using private repos/registries need to do a bit more work (grant Dependabot access to the repos/migrate their secrets), then they're migrated. I've clarified the docs (should be published shortly) and I'll work on clarifying the PR.

Thanks for the feedback!
