### ISSUE TITLE
Why are you replacing a good feature with a bad feature that does less?

### ISSUE THREAD

**Issue by ucirello** [dependabot/dependabot-core#3596]
![image](https://user-images.githubusercontent.com/138827/116575688-bb560d00-a8c3-11eb-8a15-16c2d44a0dab.png)

One of the nicest features of this change was the auto-merge. So I am being asked to replace one service that always worked fine for another service that a) adds a file that I don't want to see in my repository and b) that does less (auto-merge doesn't work)

Why am I supposed to be doing work for Microsoft? Could you please _not_ do this or do it in a way that I am not confronted with bad product decisions?

Please and thank you.

**Comment by jurre** [comment]
There's a lot of context about this [here](https://github.com/dependabot/dependabot-core/issues/2268) and [here](https://github.com/dependabot/dependabot-core/issues/1973) and [here](https://docs.github.com/en/code-security/supply-chain-security/upgrading-from-dependabotcom-to-github-native-dependabot#differences-between-dependabot-preview-and-github-native-dependabot). I'm going to close this out as a duplicate.
