### ISSUE TITLE
Add an issue category that isn't bug/feature request

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3611]
I've been filing a number of tickets that aren't bugs--the code works find today--but also aren't feature requests. They're more like tech debt/code improvements. I never know which category to use. So maybe add another category like "tech debt"? With the idea that it _improves_ dependabot w/o actually adding any new features?

Examples of these types of tickets:
* https://github.com/dependabot/dependabot-core/issues/4448
* https://github.com/dependabot/dependabot-core/issues/4154
* https://github.com/dependabot/dependabot-core/issues/3612

**Comment by jeffwidman** [comment]
cc @brrygrdn for visibility since I see you do a lot of labeling these days 😀

**Comment by jurre** [comment]
That makes sense, I've added a `T: tech-debt` label 👍

**Comment by jeffwidman** [comment]
Added a issue template here: https://github.com/dependabot/dependabot-core/pull/4470
