### ISSUE TITLE
Why the need for `.freeze` in ruby files that have `# frozen_string_literal: true` at the top?

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3613]
Given this line at the top of the file:
https://github.com/dependabot/dependabot-core/blob/1cd441517a8c71b324242c9d1becf594c49cb3ff/go_modules/lib/dependabot/go_modules/version.rb#L1

Why have `.freeze` here? https://github.com/dependabot/dependabot-core/blob/1cd441517a8c71b324242c9d1becf594c49cb3ff/go_modules/lib/dependabot/go_modules/version.rb#L16 

I see this pattern all over the `go_modules` code, and it's confusing which is the preferred way to handle freezing strings... ie, should I be freezing all strings that I don't want mutated? Or can I ignore that and simply rely on the file annotation at the top?

**Comment by feelepxyz** [comment]
@jeffwidman ah yeah, `frozen_string_literal` only applies to quoted strings, for other things like regex's (go example) and arrays we still need to `.freeze` to make it immutable.

**Comment by jeffwidman** [comment]
Ah, that makes sense, thank you!
