### ISSUE TITLE
Is there a way I can stop dependabot from spamming my repository?

### ISSUE THREAD

**Issue by limonte** [dependabot/dependabot-core#3618]
Every released PR in [sweetalert2](https://github.com/sweetalert2/sweetalert2) repository looks like this:

![image](https://user-images.githubusercontent.com/6059356/116777223-17f92980-aa76-11eb-86fe-c46bbd10a217.png)

Example: https://github.com/sweetalert2/sweetalert2/pull/2169

It's annoying and counterproductive. and I'd like to stop it. Is there a way I can prevent relating PRs in my repository from closed dependabot PRs?

**Comment by feelepxyz** [comment]
@limonte sorry about this! This issue has been fixed but quite a few PRs came through before it landed.

**Comment by limonte** [comment]
> @limonte sorry about this! This issue has been fixed but quite a few PRs came through before it landed.

Thank you @feelepxyz!
