### ISSUE TITLE
Run additional maven phase after the bump

### ISSUE THREAD

**Issue by slinkydeveloper** [dependabot/dependabot-core#3622]
We use dependabot in a repo where we generate a file called `THIRD-PARTY.txt` for license compliance. This file needs to be updated every time a dependency is bumped, but dependabot is not able to do that, hence causing several conflicts in our git flow.

It would be nice if we could just run, after the bump, the maven phase that generates this file (https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/data-plane/pom.xml#L418), without building the project. Is there anyway to do that? Or some approach that mixes dependabot and GH actions?

**Comment by jurre** [comment]
> Or some approach that mixes dependabot and GH actions?

Yep, the recommended workflow for that scenario is to run a GH action (or any CI job for that matter) after Dependabot, and push the results back to the Dependabot branch. In order to allow dependabot to force-push rebases over that new commit on the branch you can pre/post-fix it with `[dependabot skip]`.

I'm going to close out the issue, but feel free to follow up with questions 👍

**Comment by slinkydeveloper** [comment]
> In order to allow dependabot to force-push rebases over that new commit on the branch you can pre/post-fix it with [dependabot skip].

Any fancy doc/blog post that explains how to do that? :smile: I guess that's a requirement for many, so some "official"-ish doc might be useful

**Comment by jurre** [comment]
This is the safest way to implement it: https://github.com/dependabot/dependabot-actions-workflow. By splitting the workflow into two separate steps we avoid direct read-write/secrets access. Alternatively this can be simplified into a single workflow by using `pull-request-target` but it comes with some security implications that may or may not be acceptable for your scenario, but in general it is not encouraged.

**Comment by slinkydeveloper** [comment]
Gotcha, we're trying that solution, Thank you so much for that example repo!

It would be nice if that repo can be somehow translated into a ready to use action (or 2 steps action, to split in two different workflows).
