### ISSUE TITLE
Nuget pre-release packages with SemVer 2.0 are ignored

### ISSUE THREAD

**Issue by mynkow** [dependabot/dependabot-core#3643]
I have spent 2 days already trying to figure out why pre-release packages are being ignored.

First, the packages are versioned with SemVer 2.0 and [here](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning) it is explained how it works.

I have noticed that dependabot is doing the following query to the nuget query engine for the package [Cronus.DomainModeling](https://www.nuget.org/packages/Cronus.DomainModeling/)

`https://api-v2v3search-0.nuget.org/query?q=Cronus.DomainModeling&prerelease=true`

![image](https://user-images.githubusercontent.com/183151/117132473-8eb26180-adab-11eb-8585-4c212c6a2a3f.png)

As you could see from the results, SemVer 1.0 results are being returned but not SemVer 2.0.

After several hours of test/fail I have found the following [documentation ](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#request-parameters)for the query API. Here it is documented that you could provide a parameter to include SemVer 2.0 packages:

> The semVerLevel query parameter is used to opt-in to SemVer 2.0.0 packages. If this query parameter is excluded, only packages with SemVer 1.0.0 compatible versions will be returned (with the standard NuGet versioning caveats, such as version strings with 4 integer pieces). If semVerLevel=2.0.0 is provided, both SemVer 1.0.0 and SemVer 2.0.0 compatible packages will be returned. See the SemVer 2.0.0 support for nuget.org for more information.

After adding the parameter the missing packages are now displayeed:

`https://api-v2v3search-0.nuget.org/query?q=Cronus.DomainModeling&prerelease=true&semVerLevel=2.0.0`

![image](https://user-images.githubusercontent.com/183151/117132896-244df100-adac-11eb-82d3-253f1b4de16a.png)

Note: I guess this issue is related: #1972

Could you please consider fixing this issue?

**Comment by jasonrudolph** [comment]
👋 @mynkow: Thanks for reaching out!

We require [the template](https://raw.githubusercontent.com/dependabot/dependabot-core/main/.github/ISSUE_TEMPLATE/bug-report.md) to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half-way. 😀

**Comment by leksyCode** [comment]
Really, closed for that reason?
