### ISSUE TITLE
Use an OSI approved license

### ISSUE THREAD

**Issue by sathieu** [dependabot/dependabot-core#3645]
`dependabot` is currently under *Prosperity Public License* which is not approved by OSI and is not free software.

Please move to an approved license. Most commonly used are (from no to more copyleft):

- MIT
- Apache
- LGPL
- GPL
- AGPL

AGPL can fit if you want other companies to contribute back.

**Comment by asciimike** [comment]
@sathieu re-licensing Dependabot Core is a long standing internal issue (we know the current license is a bit wonky and has caused some companies to balk at it).

I wouldn't expect any movement on this in the short term, but it's definitely something we need to consider going forward.

**Comment by sathieu** [comment]
Thanks @asciimike for you response.

Are any current and future contributors signing a CLA or something which will ease the migration?

Is the target license already chosen? Is there any roadmap on this topic?

**Comment by asciimike** [comment]
Generally speaking, GitHub doesn't require CLAs on our public repos, so I doubt we'd add one here. We haven't chosen what license we'd use, but we'll definitely let folks here know with ample time before it changes.

**Comment by weitzjdevk** [comment]
>  (we know the current license is a bit wonky and has caused some companies to balk at it).

So is there a way to use dependabot as a company in a private Gitlab installation? The website says it is free, but the License says otherwise.
Or does the license mean I am not allowed to create any software, which integrates dependabot-core as a library, where I were to resell my software as a "dependabot-core-2.0" thing?

**Comment by asciimike** [comment]
> So is there a way to use dependabot as a company in a private Gitlab installation? The website says it is free, but the License says otherwise.

Yes. https://github.com/dependabot/dependabot-core/#license explicitly says that you're able to do this. Just don't sell anything with dependabot-core in it. (Obviously, I'm not a lawyer, consult your lawyers as necessary).

This confusion is the primary driver of why we'd want to migrate.

**Comment by wwahammy** [comment]
Is there any sort of an update on this? I appreciate that you're running this primarily on a proprietary service but I don't like promoting these vaguely FOSS-looking licenses.

**Comment by andrcuns** [comment]
Would anyone be able to advise? If I'm using `dependabot-core` in my app that has no commercial purpose, is it ok for me to use one of the OSI approved licenses and reference all the non commercial restrictions in it or do I have to use the same Prosperity Public License license?

**Comment by wwahammy** [comment]
> Would anyone be able to advise? If I'm using `dependabot-core` in my app that has no commercial purpose, is it ok for me to use one of the OSI approved licenses and reference all the non commercial restrictions in it or do I have to use the same Prosperity Public License license?

Unfortunately, no one can actually advise you here; that's a legal question.

As someone who is not a lawyer but reads a lot of open source and open source adjacent licenses... I don't know. It's not clear.

**Comment by wwahammy** [comment]
The solution to address this confusion would be for GH to relicense under FOSS license that folks actually have some experience working with and is clearer.

**Comment by andrcuns** [comment]
That's what I figured, thanks anyway.

**Comment by jonjanego** [comment]
Hello everyone!  Thanks for the feedback. We are happy to announce that dependabot-core is [now using the MIT license](https://github.com/dependabot/dependabot-core/blob/main/LICENSE) :)

As such - I'm going to close this issue as completed!
