### ISSUE TITLE
add support for D projects that use dub

### ISSUE THREAD

**Issue by SingingBush** [dependabot/dependabot-core#3668]
Almost all D developers use a tool called dub. The project would have either a `dub.json` or `dub.sdl` file in it's root directory. The central repository for dependencies being https://code.dlang.org

It would be great if dependabot could add dub support so that the D community can make use of it.

For documentation on dub please see: https://dub.pm/commandline

**Comment by asciimike** [comment]
Currently we're paused on ecosystem improvements, but as suggested in https://github.com/dependabot/dependabot-core/issues/2166#issuecomment-778594878, we're happy to help get a PR with support running in an Action so folks can benefit from it.
