### ISSUE TITLE
Support for dependencies on CI/CD

### ISSUE THREAD

**Issue by laurentsimon** [dependabot/dependabot-core#3675]
It' be awesome to support CI/CD systems such as, for example, [github actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) and [Google's cloud build]( https://github.com/google/clusterfuzz/blob/master/cloudbuild.yaml#L16).

Both of these make intensive use of repos that developers also want to be able to update.

OpenSSF's [scorecard](https://github.com/ossf/scorecard/issues/412) is working on supporting this too.

**Comment by jeffwidman** [comment]
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2140 which already tracks Google Cloud Build.
