### ISSUE TITLE
git checkout fails due to some really long filenames on Windows

### ISSUE THREAD

**Issue by SingingBush** [dependabot/dependabot-core#3676]
I decided to take a look at making changes to support D this morning but couldn't even work on the repo on Windows due to insanely long spec filenames in common:

```
Cloning into 'dependabot-core'...
remote: Enumerating objects: 108774, done.
remote: Counting objects: 100% (1807/1807), done.
remote: Compressing objects: 100% (896/896), done.
remote: Total 108774 (delta 959), reused 1579 (delta 773), pack-reused 106967
Receiving objects: 100% (108774/108774), 80.01 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (73984/73984), done.
error: unable to create file common/spec/fixtures/vcr_cassettes/Dependabot_MetadataFinders_Base_ChangelogFinder/_changelog_text/with_a_github_repo/with_a_changelog/for_a_git_dependency_with_multiple_sources/when_the_ref_has_changed/1_2_1_1_6_1_1.yml: Filename too long
warning: unable to access 'common/spec/fixtures/vcr_cassettes/Dependabot_MetadataFinders_Base_ReleaseFinder/_releases_text/with_a_github_repo/with_releases/when_the_release_is_present/updating_from_no_previous_release_to_new_release/.gitattributes': Filename too long
error: unable to create file common/spec/fixtures/vcr_cassettes/Dependabot_MetadataFinders_Base_ReleaseFinder/_releases_text/with_a_github_repo/with_releases/when_the_release_is_present/updating_from_no_previous_release_to_new_release/1_2_1_1_1_4_1.yml: Filename too long
fatal: cannot create directory at 'common/spec/fixtures/vcr_cassettes/Dependabot_MetadataFinders_Base_ReleaseFinder/_releases_text/with_a_github_repo/with_releases/when_the_release_is_present/updating_from_uknown_previous_release_to_new_release': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Windows can be set to allow long paths by setting *LongPathsEnabled* in the registry but I'd still go with perhaps shortening those paths a bit.

edit:
Interestingly I went to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` to set *LongPathsEnabled* but it's already set. It turns out Git for Windows cannot go beyond the old 260 char limit by default, see [Stackoverflow](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows). So I ended up working around it by doing `git config --system core.longpaths true` as Administrator.

**Comment by feelepxyz** [comment]
@SingingBush that's a bummer, those file paths a generated so won't be easy for us to change unfortunately 😞 

We're also not accepting support for new ecosystems to dependabot-core at the moment as we're focusing on improving and supporting the ones we have already and want to do a bunch of re-architecting to make it easier to support community contributions to new ecosystems. Our current recommendation is to build the new ecosystem as a separate gem that depends on `dependabot-common`.

We've got some more notes on this in our contributions guidelines: https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#why-have-we-paused-accepting-new-ecosystems

**Comment by jeffwidman** [comment]
Changing the file paths is not something we're planning on doing for the reasons mentioned ☝️. And @Marcono1234 very nicely documented the git settings required to workaround this on Windows in #4198. Closing, as there's nothing more to do here.
