### ISSUE TITLE
Support for ACR (private azure docker registry)?

### ISSUE THREAD

**Issue by konstantinblaesi** [dependabot/dependabot-core#3689]
I am using the dependabot-scripts repository and modified the generic-update-script.rb like this

```
puts "Adding ACR credentials"
credentials << {
    "type" => "docker_registry",
    "registry" => "myregistry.azurecr.io",
    "username" => "registry-user",
    "password" => "registry-pass"
}
```

The Dockerfile I want to update starts like this
```
FROM myregistry.azurecr.io/foo/nginx:1.18.0
```

```
docker run --env-file .env --rm -it dependabot-script
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Adding ACR credentials
Fetching docker dependency files for github-user-foo/dependabot-mvn-demo
Parsing dependencies information
Traceback (most recent call last):
        19: from ./generic-update-script.rb:159:in `<main>'
        18: from ./generic-update-script.rb:159:in `each'
        17: from ./generic-update-script.rb:169:in `block in <main>'
        16: from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
        15: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:100:in `version_up_to_date?'
        14: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:113:in `version_tag_up_to_date?'
        13: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
        12: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
        11: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:232:in `tags_from_registry'
        10: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:65:in `tags'
         9: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:26:in `doget'
         8: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:251:in `doreq'
         7: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
         6: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
         5: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
         4: from /usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
         2: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
         1: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 401 Unauthorized (RestClient::Unauthorized)
        21: from ./generic-update-script.rb:159:in `<main>'
        20: from ./generic-update-script.rb:159:in `each'
        19: from ./generic-update-script.rb:169:in `block in <main>'
        18: from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
        17: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:100:in `version_up_to_date?'
        16: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:113:in `version_tag_up_to_date?'
        15: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
        14: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
        13: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:232:in `tags_from_registry'
        12: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:65:in `tags'
        11: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:26:in `doget'
        10: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:245:in `doreq'
         9: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:269:in `rescue in doreq'
         8: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:313:in `do_bearer_req'
         7: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
         6: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
         5: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
         4: from /usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
         2: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
         1: from /home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/dependabot/.bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 401 Unauthorized (RestClient::Unauthorized)
        14: from ./generic-update-script.rb:159:in `<main>'
        13: from ./generic-update-script.rb:159:in `each'
        12: from ./generic-update-script.rb:169:in `block in <main>'
        11: from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
        10: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:100:in `version_up_to_date?'
         9: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:113:in `version_tag_up_to_date?'
         8: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
         7: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
         6: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:232:in `tags_from_registry'
         5: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:65:in `tags'
         4: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:26:in `doget'
         3: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:245:in `doreq'
         2: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:269:in `rescue in doreq'
         1: from /home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:307:in `do_bearer_req'
/home/dependabot/.bundle/gems/docker_registry2-1.10.0/lib/registry/registry.rb:323:in `rescue in do_bearer_req': DockerRegistry2::RegistryAuthenticationException (DockerRegistry2::RegistryAuthenticationException)
        9: from ./generic-update-script.rb:159:in `<main>'
        8: from ./generic-update-script.rb:159:in `each'
        7: from ./generic-update-script.rb:169:in `block in <main>'
        6: from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
        5: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:100:in `version_up_to_date?'
        4: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:113:in `version_tag_up_to_date?'
        3: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
        2: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
        1: from /home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:227:in `tags_from_registry'
/home/dependabot/.bundle/gems/dependabot-docker-0.142.0/lib/dependabot/docker/update_checker.rb:242:in `rescue in tags_from_registry': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): myregistry.azurecr.io (Dependabot::PrivateSourceAuthenticationFailure)
```

Am I doing something wrong or is the ACR simply not supported?

**Comment by feelepxyz** [comment]
@konstantinblaesi yeah I don't think we support it but have never tried it myself. Dependabot supports AWS ECR, is the auth setup similar to that?

This is how we handle AWS ECR creds atm: https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/docker/lib/dependabot/docker/utils/credentials_finder.rb#L33-L66

**Comment by pinkfloydx33** [comment]
I am in the same boat. Any update on whether this is or will be supported?

**Comment by emibcn** [comment]
@feelepxyz The `.npmrc` we use to connect to our private ACR can be generated with something like:
```shell
NPM_URL="ourorganization.pkgs.visualstudio.com/Project1/_packaging/Project1"
NPM_DEFAULT_USERNAME="someuser"
NPM_DEFAULT_PASSWORD="SECRET_PAT"
NPM_DEFAULT_EMAIL="whatever"

cat <<EOF
always-auth=true

registry=https://${NPM_URL}/npm/registry/
; begin auth token 
//${NPM_URL}/npm/registry/:username=${NPM_DEFAULT_USERNAME}
//${NPM_URL}/npm/registry/:_password=${NPM_DEFAULT_PASSWORD}
//${NPM_URL}/npm/registry/:email=${NPM_DEFAULT_EMAIL}
//${NPM_URL}/npm/:username=${NPM_DEFAULT_USERNAME} 
//${NPM_URL}/npm/:_password=${NPM_DEFAULT_PASSWORD} 
//${NPM_URL}/npm/:email=${NPM_DEFAULT_EMAIL}
; end auth token
EOF
```

**Comment by emibcn** [comment]
Ok, I made it work. The registry URL must contain the final `/`, something like:

https://ourorganization.pkgs.visualstudio.com/Project1/_packaging/Project1/npm/registry/

**Comment by emibcn** [comment]
I faced a second problem while trying to update the package. I needed to change the source code at `/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb`, function `build_npmrc_content_from_lockfile`:
```ruby
        def build_npmrc_content_from_lockfile
          return unless yarn_lock || package_lock
          return unless global_registry

          # Don't add https://
          "registry = #{global_registry['registry']}\n"\
          "#{global_registry_auth_line}"\
          "always-auth = true"
        end
```

**Comment by emibcn** [comment]
Hmmm, I also had to create a `/home/dependabot/.npmrc` (like in https://github.com/dependabot/dependabot-core/issues/3689#issuecomment-979771706 ) because we use our registry also as a proxy to the official NPM registry.

**Comment by pinkfloydx33** [comment]
@emibcn, The original post in this issue is regarding Azure Container Registry (docker), not Azure Artifacts (Azure Devops package feeds) FYI.

To use Azure Artifacts with dependabot you need to pass creds in the form:

```ruby
{
   'type' => 'npm_registry', 
   'registry' => 'https://pkgs.dev.azure.com/ORGNAME/_packaging/FEEDNAME/npm/registry/',
   'token' => "FEEDNAME:#{aztoken}" 
} 
```
Where `aztoken` is the `System.AccessToken`

**Comment by emibcn** [comment]
@pinkfloydx33 Ups! Sorry for the confusion and thank you for the explanation. Is it in some documentation?

**Comment by floriankoch** [comment]
Hi, any News here? Is there an ETA for ACR support?

**Comment by esc-gesch** [comment]
Just to bump this, is there an ETA for the support of ACR? Or maybe any workaround we can use this this is fixed?

**Comment by pavera** [comment]
I spent a little time starting to research this, and it seems beyond the authentication issue there may be issues similar to #4212. Specifically according to https://docs.microsoft.com/en-us/rest/api/containerregistry/ the API does not seem to follow the expected URL layout.  Would be happy to learn I'm wrong about this if anyone knows of different documentation?

**Comment by jeffwidman** [comment]
@lachie83, someone internal at GitHub pointed me your way... Know anyone at Microsoft connected to the Azure Container Registry team who might know more re: ☝️ ?

Hopefully they already support the proper OCI APIs and we're just misunderstanding the docs...

**Comment by lachie83** [comment]
Hi @jeffwidman - thanks for the ping. Let me look into this and get back to you.

**Comment by sajayantony** [comment]
I was able to test this with ACR and if there is an updated tag then dependabot-core is able to access the registry/list tags and also show the patch - 

```
[dependabot-core-dev] ~/dependabot-core $ ./bin/dry-run.rb docker sajayantony/dependabot-test
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/sajayantony/dependabot-test/
=> parsing dependency files
=> updating 1 dependencies: library/alpine

=== library/alpine (3.16.1)
 => checking for updates 1/1
 => latest available version is 3.16.2
 => latest allowed version is 3.16.2
 => requirements to unlock: own
 => requirements update strategy:
 => updating library/alpine from 3.16.1 to 3.16.2

    ± Dockerfile
    ~~~
    1c1
    < FROM dependabottest.azurecr.io/library/alpine:3.16.1
    ---
    > FROM dependabottest.azurecr.io/library/alpine:3.16.2
    ~~~
🌍 Total requests made: '0'
```
Modified this just quickly validate it this - (not sure if there is a better way)
https://github.com/dependabot/dependabot-core/blob/8ab4d78efe7cf9a75bef76dd883d7ee3fffffb40/bin/dry-run.rb#L108-L109
```ruby
  credentials: [
    {
      "type" => "docker_registry",
      "registry" => "dependabottest.azurecr.io",
      "username" => "dependabottest",
      "password" => "...."
    }
  ],
```

ACR should not need any special configuration besides the being able to discover the docker_registry credentials.

**Comment by pavera** [comment]
@sajayantony thanks for looking into this!  We've had various user reports of failures using various credentials such as:

- Service Principal (App Id) with secret
- ACR Token (Preview Feature) with username and password
- User 00000000-0000-0000-0000-000000000000 with access token generated by az acr login -n <registry name> -t

It seems from the documentation that we should be recommending Service Principals to our users, but we've had multiple reports of that authentication method failing and have been able to recreate that failure internally as well.

What type of credentials did you use in your testing?  Again, thanks for looking at this :)

**Comment by jeffwidman** [comment]
Whenever this gets resolved, we need to also remove the note from our docs about ACR not being supported: https://github.com/github/docs/pull/19397

**Comment by sajayantony** [comment]
@pavera 

I tested with admin creds first and then moved onto AAD - 
1.  SPN (AppId and password) 
```
az ad sp create-for-rbac -n "sajaya-dependabot-testuser" --role "Contributor" \
    --scope $(az acr show -n myregistry--query 'id' -o tsv)
```
AppID and Password were taken and I modified the creds as shown above. 

2.  Token generated (ensure you have tag list permissions) 

```
az acr token create -r dependabotest -n testdependabotuser --repository library/alpine content/read metadata/read 
```

3 -With token generated  from my identity 

```
az acr login -n dependabottest  --expose-token -o json 
```

For e.g. validate you can list tags with that username and password 

```
➜ oras repository show-tags dependabottest.azurecr.io/library/alpine -u 00000000-0000-0000-0000-000000000000 -p $ACR_ACCESS_TOKEN
3.16.1
3.16.2
```

If there are authentication issue please open an issue on the Azure portal for ACR and we can continue investigation.

**Comment by jeffwidman** [comment]
Thanks @sajayantony for looking into this.

I did some poking around internally, and I think we found the source of the confusion:
1. When running `dependabot-core` as a standalone script, private docker registry credential auth flows are supported either through the OCI-compliant route leveraging the `WWW-Authenticate header`, or via Basic auth. This is what happens via the `dry-run` script.
2. Internally at GitHub for security reasons we never give Dependabot access to registry credentials, those are instead injected via a sidecar proxy. So essentially we're always running `dependabot-core` with a custom URL but no creds.
3. That proxy supported _only_ the OCI-compliant path for authentication until last week, when @pavera added support for Basic Auth.
4. From looking at the HTTP header replies from ACR, they don't return a OCI-compliant `WWW-Authenticate header` pointing to a token server. 
5. However, the ACR credential paths _do_ work via the basic auth flow. This is why `dry-run` has always seemed to work, yet we've gotten customer reports of not working for the Dependabot service at GitHub. [^1]

However, now that the proxy has support for basic auth, it looks like ACR is now supported not only in `dry-run` but also via the Dependabot service we run at GitHub. As best we can tell, this means we now support all three authentication methods mentioned in https://github.com/dependabot/dependabot-core/issues/3689#issuecomment-1263664425.

Many thanks to @sajayantony and @pavera for figuring this out.

[^1]: We realize it's confusing to have a `dry-run` that doesn't actually match what's run in prod at GitHub... That's why we recently built https://github.com/dependabot/cli, see also https://github.com/dependabot/dependabot-core/pull/5806

**Comment by sajayantony** [comment]
@jeffwidman - Could you clarify this ? 

> From looking at the HTTP header replies from ACR, they don't return a OCI-compliant WWW-Authenticate header pointing to a token server.

What header are you missing here - Shown below is the auth header from ACR. 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1821104/194918454-d9031035-62d1-4365-95ef-173099f27018.png">

**Comment by pavera** [comment]
If basic auth is set on a request then the response has the following:
```
curl -v https://PAT:bananas@dependabottest.azurecr.io/v2/base/grafana/tags/list 2>&1 | grep -i www
< Access-Control-Expose-Headers: WWW-Authenticate
< Www-Authenticate: Basic realm="Azure Container Registry"
```
With basic auth set Dockerhub still replies with:
```
curl -v https://PAT:bananas@registry.hub.docker.com/v2/library/golang/tags/list 2>&1 | grep -i www
< www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/golang:pull"
```
I'm less confident that this is fixed. We probably need to set up an azure account so we can test e2e.

**Comment by jeffwidman** [comment]
Ah, yeah, that's a potential problem.

Basically our flow is that we first attempt basic auth, then if that fails, we use the `Www-Authenticate` header to locate the token server to retrieve the proper auth token... then we use that newly generated token in basic auth against the original URL.

So in this case, yeah, it'd probably break...

**Comment by jeffwidman** [comment]
Just got off the phone with @sajayantony and here's some more details:
1. ACR supports _both_ basic auth and bearer auth. So if a tool supports basic auth, it's fine that ACR doesn't reply with the bearer token server since the initial auth will work via basic auth.
2. That said, since some tooling other than Dependabot doesn't support basic auth but only bearer auth, he is going to take an action item to make it so that if a tool improperly sends basic auth creds, ACR still responds with the bearer auth info in the `401` response.

Practically speaking, Dependabot will already work with ACR today because although bearer auth is more idiomatic in the container registry ecosystem, for implementation simplicity we first try basic auth and then fallback bearer auth. Since ACR supports basic auth, that _should_ work fine for us. And even if it doesn't, once they implement the bearer auth response to bad basic auth creds, then that fallback should work fine as well.
