### ISSUE TITLE
Dependabot stopped making PRs

### ISSUE THREAD

**Issue by ccleve** [dependabot/dependabot-core#3691]
I have activated Dependabot for three projects. They each use Javascript and have dependencies in NPM.

For two of the projects, one public and one private, I'm getting pull requests regularly. It's working great.

For one private project, I haven't gotten a Dependabot pull request since January, despite the fact that it has the same dependencies as the other projects. I do get security warnings for the project. I can't find any configuration options for Dependabot that would account for the difference: so far as I can tell, Dependabot is either on or off.

Why would Dependabot stop creating PRs?

The public project is dieselpoint/groundlist.site. (Github people: if you have access to my private projects, the project not getting the PRs is dieselpoint/groundlist).

**Comment by jasonrudolph** [comment]
> For two of the projects, one public and one private, I'm getting pull requests regularly. It's working great.
>
> ...
> 
> The public project is dieselpoint/groundlist.site. (Github people: if you have access to my private projects, the project not getting the PRs is dieselpoint/groundlist).

👋 @ccleve: The public project has a [`.github/depenabot.yml` file](https://github.com/dieselpoint/groundlist.site/blob/5ed87ea9a5bb7c83ffe084027b3abd119e3d8d3b/.github/dependabot.yml). That file is necessary for enabling Dependabot. For the private project you mentioned (dieselpoint/groundlist), it appears that Dependabot is not enabled for the repository. Can you ensure that you have a valid `.github/depenabot.yml` file present in the repository?

If you already have a `.github/dependabot.yml` file present in the dieselpoint/groundlist repo, please let us know, and we'll re-open this issue.
