### ISSUE TITLE
Upgrade to intemediary version

### ISSUE THREAD

**Issue by icecream17** [dependabot/dependabot-core#3701]
atom has tons of dependency updates, and instead of updating by several versions, I would like to tell dependabot to upgrade to an intermediate version instead.

For example the upgrade here: https://github.com/icecream17/atom/pull/8 (now lost - I deleted and reforked) has _504_ commits. I don't feel like debugging huge upgrades. So I want to upgrade to maybe 2.0.0 instead, then go step by step to 2.2.8. Is there a way to do this?

**Comment by asciimike** [comment]
Can you use `ignore` conditions and the forthcoming #2219 to do something like this (e.g. ignore major/minor and only merge in patch until you want minor, then major)?

**Comment by icecream17** [comment]
The version after 1.0.11 is 2.0.0, a major bump
But upgrading to 2.2.8 is also a major bump

So no, disabling things won't help

**Comment by jeffwidman** [comment]
This hasn't been a common feature request, it seems most folks can use `ignore` with major/minor to get a close enough approximation of what they want. So closing for now.
