### ISSUE TITLE
Dependabot claims to be not configured while dependabot.yml is present and it was working before

### ISSUE THREAD

**Issue by pellared** [dependabot/dependabot-core#3709]
## Description

Take notice: https://github.com/goyek/goyek/blob/main/.github/dependabot.yml - it has not been changed since  Oct 25, 2020

After that dependabot was working without any issues. Example: https://github.com/goyek/goyek/pull/38

Some time ago I noticed that dependabot started to claim that it is not configured and I do not get any PRs from it:

![image](https://user-images.githubusercontent.com/5067549/117993803-56c59400-b340-11eb-89d6-9982b9ec509a.png)

## What may have caused it

The repository was originally here: https://github.com/pellared/taskflow
Then it was moved to: https://github.com/goyek
Afterwards it was renamed to `goyek`

**Comment by asciimike** [comment]
Would you mind touching the file and re-committing it? I have a feeling that if you moved it around, we might not have picked up the move, thus we're still updating (or rather, attempting to update) the old repo.

**Comment by pellared** [comment]
@asciimike Fixed. Thanks
