### ISSUE TITLE
Update to older version

### ISSUE THREAD

**Issue by josesimoes** [dependabot/dependabot-core#3720]
**Package ecosystem**
NuGet
**Package manager version**
NuGet
**Language version**
.NET C#
**Manifest location and content prior to update**

https://github.com/nanoframework/nanoFramework.TestFramework/blob/develop/.github/dependabot.yml

**Updated dependency**

Package is: nanoFramework.Tools.Debugger.Net
Current version was "2.0.0-preview.15" and dependabot updated it to "2.0.0-preview.8".

**Native package manager behavior**

See here: https://github.com/nanoframework/nanoFramework.TestFramework/pull/48

**Comment by asciimike** [comment]
Weird... I wonder if we're doing a string compare as opposed to a number compare here... 😅

**Comment by mynkow** [comment]
Yes, dependabot is doing SemVer1.0 comparison. This issue has been already identified in the following (and probably there are many more) tickets:

#1972
#3643

**Comment by asciimike** [comment]
Closing in favor of #1972, I'll see if someone can poke at this.
