### ISSUE TITLE
Unable to disable dependabot in mirror (where there is a dependabot.yaml file)

### ISSUE THREAD

**Issue by phlax** [dependabot/dependabot-core#3727]
This seems to be related to #2804 altho in this case the secondary repo is not a fork exactly - its more like a secondary mirror which is manually kept up-to-date with the main repo

The main repo has and needs a dependabot config file - it would be possible i guess - but definitely sub-optimal to remove the dependabot file in the secondary repo

I had thought it would be possible to disable dependabot on the secondary by going to "> Settings > Security & analysis" - but that shows a button to "enable dependabot" even though dependabot is already creating frequent prs

**Comment by asciimike** [comment]
The "security & analysis" settings are for Dependabot Security Updates, while the `dependabot.yml` controls Dependabot Version Updates. You'll need to either remove the file and not re-sync it when you do your manual syncs, or set the `open-pull-requests-limit: 0` to turn off PR creation in the mirror.

**Comment by phlax** [comment]
cc @htuch @antoniovicente

thanks @asciimike i guess we will have to live with an updated/removed config
