### ISSUE TITLE
CI test failure with gradle/npm on a completely unrelated PR

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3735]
https://github.com/dependabot/dependabot-core/pull/3733/checks?check_run_id=2607539269

This PR modifies the `go_modules` section of the code, and is completely unrelated to `gradle`/`npm`, yet that's what failed.

So filing a separate ticket to track/address it.

**Comment by feelepxyz** [comment]
@jeffwidman thanks for reporting, will take a look.

**Comment by jeffwidman** [comment]
@feelepxyz was this resolved?

**Comment by jurre** [comment]
I think those particular failures have been addressed, but we still have a bunch of other flaky tests in our test-suite. I think we can close this out and we can track the state of the test-suite separately (probably internally at first).
