### ISSUE TITLE
PR not created for migrating from Dependabot Preview to 

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dependabot/dependabot-core#3757]
Hi there,

One of our repos seems to have upset Dependabot and it's not creating the migration PR, even when triggering it from `app.dependabot.com`.

The repo in question:
![image](https://user-images.githubusercontent.com/2286713/118894234-c1a43b80-b8fb-11eb-97b8-d8a8c69d4f36.png)

Then to trigger the PR:
![image](https://user-images.githubusercontent.com/2286713/118894245-c79a1c80-b8fb-11eb-8eb5-9fcb5ff07d92.png)

And then it just goes back to this and a PR is never created:
![image](https://user-images.githubusercontent.com/2286713/118894282-d41e7500-b8fb-11eb-8db7-fc8e69a0b38e.png)

What's weird is that the repo is having Dependabot Native and Preview open PRs there, even though we don't have a native config file yet...

All our other repos have been migrated and got PRs fine.

Any help would be great thanks!

**Comment by jurre** [comment]
That's odd! Could you share the full repo URL? @brrygrdn any idea why that could happen?

> What's weird is that the repo is having Dependabot Native and Preview open PRs there, even though we don't have a native config file yet...

This is probably because [Security Updates](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates) is enabled on the repo?

**Comment by ElvenSpellmaker** [comment]
@jurre Sure! https://github.com/amido/stacks-webapp-template

**Comment by ElvenSpellmaker** [comment]
> This is probably because Security Updates is enabled on the repo?
Ahh yes!

**Comment by brrygrdn** [comment]
As @jurre says, it's working as intended that you can get Security Update PRs from native, but the presence of Security Update PRs shouldn't block your migration PR having been created 🤔 

I'll have a look into what went wrong

**Comment by aheritier** [comment]
I tried today to migrate several private repositories and nothing happens like for @ElvenSpellmaker 


<img width="501" alt="Screenshot 2021-05-27 at 20 27 12" src="https://user-images.githubusercontent.com/174600/119877970-ef0b6d80-bf29-11eb-91da-a93318e721d5.png">
<img width="442" alt="Screenshot 2021-05-27 at 20 27 50" src="https://user-images.githubusercontent.com/174600/119878072-05b1c480-bf2a-11eb-995f-4ef16b591882.png">

No log, just the popup saying that it will be created but nothing done after several hours.

Sometimes I see also the message

> Something went wrong when creating your Pull Request. Try again or contact support.

<img width="502" alt="Screenshot 2021-05-27 at 20 24 09" src="https://user-images.githubusercontent.com/174600/119877579-82906e80-bf29-11eb-9325-58ecff1dc08d.png">

The list of repositories I tried to convert:

* https://github.com/cloudbees/sfdc-client
* https://github.com/cloudbees/support-advisor-server
* https://github.com/cloudbees/support-analytics
* https://github.com/cloudbees/support-bundle-reader
* https://github.com/cloudbees/support-uploadsite
* https://github.com/cloudbees/zendesk-bot
* https://github.com/cloudbees/zendesk-cli

It worked few weeks ago for a repo : https://github.com/cloudbees/elroy-libs (I don't think we triggered it but not sure)

I am not admin of our org, maybe something is wrong at the org level ?

**Comment by aheritier** [comment]
My projects are very similar and are using such configuration

```
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/src/main/docker"
    update_schedule: "daily"
```

**Comment by ElvenSpellmaker** [comment]
> As @jurre says, it's working as intended that you can get Security Update PRs from native, but the presence of Security Update PRs shouldn't block your migration PR having been created 🤔
> 
> I'll have a look into what went wrong

Hey any news about this? We'd like to have our upgrade PR please?!

**Comment by brrygrdn** [comment]
👋🏻  @ElvenSpellmaker Sorry for the delay, I've had a look into this. It seems that Dependabot Preview created a migration PR almost a year ago: https://github.com/amido/stacks-webapp-template/pull/376

The migration PRs use the same rules as a normal Dependabot PR, so when a PR is closed out it behaves like an 'ignore this change' message. This wasn't very obvious or transparent on our side so I'll have a look at improving that.

**Comment by ElvenSpellmaker** [comment]
> 👋🏻 @ElvenSpellmaker Sorry for the delay, I've had a look into this. It seems that Dependabot Preview created a migration PR almost a year ago: [amido/stacks-webapp-template#376](https://github.com/amido/stacks-webapp-template/pull/376)
> 
> The migration PRs use the same rules as a normal Dependabot PR, so when a PR is closed out it behaves like an 'ignore this change' message. This wasn't very obvious or transparent on our side so I'll have a look at improving that.

Oh thanks, I did wonder if it was a PR that had been closed at some point but I couldn't find one when I searched on github! Thanks for confirming.

If I re-open the PR will it update to settings currently there in Dependabot Preview's site?

**Comment by ElvenSpellmaker** [comment]
I'm the one who closed it too haha! 😅

I suppose it's because ideally Dependabot Preview seems a better solution than the current Dependabot, but hey ho.

**Comment by brrygrdn** [comment]
@ElvenSpellmaker I'm just having a look at that, I don't believe it will update the PR commit. I'll see what I can do to bump it forward.

**Comment by ElvenSpellmaker** [comment]
> @ElvenSpellmaker I'm just having a look at that, I don't believe it will update the PR commit. I'll see what I can do to bump it forward.

Thanks!

**Comment by brrygrdn** [comment]
@aheritier I've had a look at the repositories you mentioned. It seems like the following failed due to there being no active configs:

- cloudbees/support-advisor-server
- cloudbees/support-analytics
- cloudbees/support-bundle-reader

This would normally indicate that the repositories were no longer accessible by Dependabot, however the remaining repos you mentioned do appear to have encountered errors attempting to create the migration PR so it may be something else.

**Comment by ElvenSpellmaker** [comment]
> 
> 
> @ElvenSpellmaker I'm just having a look at that, I don't believe it will update the PR commit. I'll see what I can do to bump it forward.

Hey @brrygrdn, I've re-opened the PR, is there any way to update it from what's in app.dependabot.com please?

**Comment by brrygrdn** [comment]
@ElvenSpellmaker 👋🏻  Unfortunately the migration PRs don't have the same lifecycle behaviour as a normal PR. I'm having a look into how best to mange refreshing the diff in cases like this. Aiming to get back on this tomorrow.

**Comment by ElvenSpellmaker** [comment]
> @ElvenSpellmaker 👋🏻 Unfortunately the migration PRs don't have the same lifecycle behaviour as a normal PR. I'm having a look into how best to mange refreshing the diff in cases like this. Aiming to get back on this tomorrow.

Excellent thank you!

**Comment by brrygrdn** [comment]
@ElvenSpellmaker I'm currently testing a fix that will allow me to regenerate your config into a _new_ pull request. Will confirm shortly.

**Comment by ElvenSpellmaker** [comment]
Excellent, thanks @brrygrdn!

**Comment by brrygrdn** [comment]
@ElvenSpellmaker You should now have a PR with the up to date config 👍🏻

**Comment by ElvenSpellmaker** [comment]
Perfect, thank you! =)

**Comment by brrygrdn** [comment]
:wave: @aheritier I just wanted to check if you were still having issues with the migration of some CloudBees repos?

I've done a quick check and most of the repos we attempted to migrate had no active configs at time of the migration but I can see a few that are blocked on generating a valid v2 configuration file. Since these repositories are private, the best approach would be to contact us [via support](https://support.github.com/contact) so we can discuss further.

**Comment by aheritier** [comment]
thanks @brrygrdn I'll do it if needed. We migrated a large part of them. Few of them manually, it's not something very difficult to do.
