### ISSUE TITLE
Dependabot errors on gradle dependency with prefix version range

### ISSUE THREAD

**Issue by J3173** [dependabot/dependabot-core#3759]
**Package ecosystem**
gradle

**Package manager version**
gradle 6.5.1

**Language version**
Java 11

**Manifest location and content prior to update**
https://github.com/openEHR/archie/blob/51a8c40f6741a4ca33befae80489537054a24ae5/build.gradle#L75

**dependabot.yml content**
https://github.com/openEHR/archie/blob/51a8c40f6741a4ca33befae80489537054a24ae5/.github/dependabot.yml

**Updated dependency**
junit:junit:4.+

**What you expected to see, versus what you actually saw**
Dependabot status shows "Dependabot encountered an unknown error" when you have a gradle dependency with a [prefix version range](https://docs.gradle.org/current/userguide/single_versions.html), i.e. a version string ending in a `+` sign, e.g.: `testCompile 'junit:junit:4.+'`. Changing the dependency to `testCompile 'junit:junit:4.13.2'` makes the Dependabot run complete normally.

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**
Log snippet from Insights > Dependency graph > Dependabot:
```
updater | I, [2021-05-20T11:12:06.586733 #7]  INFO -- sentry: ** [Raven] Sending event 3470f01421054b2c925703a1ed699d1a to Sentry
updater | ERROR <job_136399394> Error processing junit:junit (RuntimeError)
updater | ERROR <job_136399394> No files changed!
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-gradle-0.148.3/lib/dependabot/gradle/file_updater.rb:35:in `updated_dependency_files'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:691:in `generate_dependency_files_for'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:281:in `check_and_create_pull_request'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:89:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_136399394> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_136399394> bin/update_files.rb:21:in `<main>'
```

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by kirill-artamonov-form3** [comment]
For one of the company's GitHub actions, 2 tags for different semantic versions were created on the same commit.
Dependabot then fails to updated GitHub actions due to:
> updater | 2023/05/03 12:52:13 ERROR <job_656601151> Error processing <...> (RuntimeError)
> updater | 2023/05/03 12:52:13 ERROR <job_656601151> No files changed!

Shouldn't Dependabot ignore versions without actual changes rather then failing?
If so - should I create a separate issue for that? Or is it covered by this one?
Also, would such error block updates of other GitHub actions?
Thanks in advance! 🙏

**Comment by jakecoffman** [comment]
I just deployed a fix for this, let me know if you're still seeing issues with it.
