### ISSUE TITLE
Increase max file size for package-lock.json manifest

### ISSUE THREAD

**Issue by driesvints** [dependabot/dependabot-core#3771]
Hi there,

I've recently found out that Dependabot limits for manifest file sizes are limited to 0.5 MB per file. If it's over that then Dependabot won't scan and alert the repo for security vulnerabilities. I felt that this was a little low and did a poll on Twitter to see what the average file size of package-lock.json in apps would be. Even though it didn't get super many votes, it showed that on average there's more than 57% of apps that have a file size greater than 0.5 MB. This means that more than 50% of apps aren't being checked for security vulnerabilities.

The related article on file size limits: https://docs.github.com/en/code-security/supply-chain-security/troubleshooting-the-detection-of-vulnerable-dependencies#are-there-li[…]cy-graph-data

The poll on Twitter: https://twitter.com/driesvints/status/1392838538601766918

I believe a limit of 1.5 MB would make more sense here. That would cover (according to the poll) about 85% of apps which seems a lot more safer, no? Could this be up for consideration?

In any case, thanks for the great work you do at Dependabot 🙂

**Comment by asciimike** [comment]
Thanks for the data! I'll chat with the dependency graph team and see what we can do about why the limit is what it is and where it should go!

**Comment by asciimike** [comment]
I pulled some data internally, and across all `package-lock.json` files currently in GitHub, here are some size stats:
 - average: 475kB
 - median: 369kB
 - 90th: 1.23MB
 - 95th: 1.55MB
 - 99th: 1.84MB
 - 99.9th: 2.97MB

The data you have was actually pretty darn close to what I'm seeing: we currently cover ~50% of folks with the ~0.5MB limit and 1.5MB would be about 95% of people.

**Comment by driesvints** [comment]
Thanks @asciimike for checking in on that. Hopefully GitHub is willing to increase the file size limit to 1.5 MB. It would mean a whole lot more apps are going to be covered 🙂

**Comment by alexreid** [comment]
All our package-lock.json files are over this limit, so it'd be great to see this raised. It's not clear to me if running Dependabot using package.json alone will catch security vulnerabilities given that package.json dependencies are often specified as version ranges.

**Comment by asciimike** [comment]
> It's not clear to me if running Dependabot using package.json alone will catch security vulnerabilities given that package.json dependencies are often specified as version ranges.

The version ranges aren't the issue, we'll happily check that your `package.json` is affected; the problem is more often that transitive dependencies are captured in the `package-lock.json` and not in `package.json`, so we'd miss those :(

**Comment by asciimike** [comment]
Hello dependafriends,

We've deployed a change to raise the limit to 1.5MB, which should cover the majority of folks (well, 95% of you ;).

In order to see larger manifests, you'll need to change the manifest in some way (even a `touch` and a `git commit` should do the trick) as we only detect manifests on `push` (or just wait for the next Dependabot update!).

**Comment by driesvints** [comment]
Thanks @asciimike1

**Comment by alexreid** [comment]
I've noticed that NPM 7 uses a new version of the lock file (`"lockfileVersion": 2`), which seems to be between 2 and 3 times bigger, in our experience. This means some of our projects (those using Angular in particular) are now getting quite close to the new limit. Do you have any stats on lock file sizes by lockfile version, and would there be any hope of getting this limit raised to accommodate the increase in file size in the future?

**Comment by asciimike** [comment]
I hadn't done this analysis, but I've kicked off a job and will report when it completes (I think it'll be a bit...).

FWIW, re-running the query on data that's more current produces pretty similar stats (avg of 0.5MB, P95 of 1.55MB), while I know that npm7 adoption has increased reasonably over the last few months. Maybe angular project usage hasn't changed too much so it's not really influencing the aggregate stats?

**Comment by alexreid** [comment]
@asciimike Thanks for the numbers, it's good to see that it's not just me! My understanding is that lockfile v2 contains a complete copy of the the older format, so that v2 lockfiles can be used by both NPM 6 and 7, which may well explain the fact that it's roughly doubling the size. It seems that [v3 lockfiles](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion) will exist at some point in the future, and will drop NPM 6 compatibility, so it may be that this isn't a problem in the long term, depending on how long that process takes!

**Comment by asciimike** [comment]
Hah, yeah I looked for v3 as well, but got very little signal (I think literally one file). I'm re-running on a broader time period/swath of repos, but agreed that we might be in a bit of a weird space before the transition is completed.
