### ISSUE TITLE
invalid request to private npm repository

### ISSUE THREAD

**Issue by wengjq** [dependabot/dependabot-core#3776]
Related issues [#943](https://github.com/dependabot/dependabot-core/issues/943)

The author gived the method 

> credentials << {
  "type" => "npm_registry",
  "registry" => ENV["DEPENDENCY_REGISTRY"],
  "token" => ENV["DEPENDENCY_TOKEN"]
}

I have a question about how to deal with the registry protocol is http? Are there relevant parameters to pass？

**Comment by jeffwidman** [comment]
In https://github.com/dependabot/dependabot-core/pull/5928, the protocol passed in is now honored, so you should now be able to pass in `http`.

I'm going to close as resolved, but please try it and if for some reason it's not working comment and we can re-open.
