### ISSUE TITLE
Provide possibility to get rid of dependabot-preview manually

### ISSUE THREAD

**Issue by mhatvan** [dependabot/dependabot-core#3818]
## Basic info:

**Package ecosystem**
npm
**Language version**
Node 14

## Current behavior in GitHub-native Dependabot:

The automatic `Upgrade to GitHub-native Dependabot` PR didn't have the ideal configuration, so I created a separate PR that got rid of the old `dependabot-preview` configuration and created the new `dependabot.yml`. I assumed that the config change alone should be enough to do the migration. Unfortunately not, now we are in a weird state of having both `dependabot-preview` and `dependabot` creating upgrade PRs.

I reopened the `Upgrade to GitHub-native Dependabot` closed PR and merged it in hopes of fixing this mess, but it didn't do anything.

`app.dependabot.com` still has the `Upgrade to GitHub-native Dependabot` for that repo, so kind of stuck in a deadlock situation.

How can we get rid of the old `dependabot-preview` now?

**Comment by jurre** [comment]
Hi @mhatvan, you should be able to click on the little gear icon for that repo in app.dependabot.com and click "Delete language" to get rid of the old config, and that should remove the installation for preview.

I think the migration step bailed out once it noticed the repo already existed in dependabot-native, apologies about that. Lmk if manually removing the repo works for you.

**Comment by mhatvan** [comment]
Clicking the cog leads to a new page with the "Applied config from `.github/dependabot.yml`", no "delete language" anywhere to be found.

It also tells me "the repo is using a config file so can no longer be managed from the dashboard".

Any other solution?

**Comment by jurre** [comment]
Easiest thing is probably to contact support and mention this issue and the repo it's happening on: https://support.github.com/contact

We can verify ownership of the repo and I can manually fix this up for you that way

**Comment by jurre** [comment]
I believe this is resolved now, please lmk (here or via support) if there's anything else we can do.

**Comment by mhatvan** [comment]
Yeah, it is resolved, thanks a lot!
