### ISSUE TITLE
Redundancy in commit sign off and co-author

### ISSUE THREAD

**Issue by ImRodry** [dependabot/dependabot-core#3820]
**Package ecosystem** npm

**Package manager version** 6.14.13

**Language version** Node 14.17.0

**Manifest location and content prior to update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw** Only a "Signed-off-by" line in the commit, without a "Co-authored-by" line. Instead, both were provided in the suggested commit description.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

This issue happens with any dependency update. Dependabot will sign-off and co-author the commit, making it so that it shows up twice in the commit authors. Removing the co-author line fixes this issue.
Description and authors of the automatic squash and merge commit:
![image](https://user-images.githubusercontent.com/38259440/120226350-ecb55600-c23e-11eb-9243-f971523ad25c.png)
Edited squash and merge commit description with the removed "Co-authored-by" line:
![image](https://user-images.githubusercontent.com/38259440/120226409-0e164200-c23f-11eb-99df-cb3191fcb115.png)
I find this to be a bit redundant so it should be removed, if possible.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

So the symptom here of duplicate authors was probably more of a UI display bug in GitHub. The sign off trailer is actually not deterministically a commit co-author, in some projects both the author and the committer have to include a sign-off trailer message.

This has since been fixed, and even though the sign off and co-author trailers are still present, GitHub UI only displays a single author, for example see how https://github.com/dependabot/dependabot-core/commit/a2ae2480cbb584aaca104c945c2bfdc05894f82a displays.

**Comment by ImRodry** [comment]
It seems to have been fixed indeed. May I ask why these lines are included? Removing them now produces the same exact behavior so I still find them rather useless?

**Comment by jeffwidman** [comment]
Signoff trailer is required in some open source projects for CI checks. Technically those checks aren't really applicable for a bot as the commiter signoff matters more in that case. But it's easier for convenience for those projects to retain it.

And co-author line is useful for when commits get amended to attribute the commit to both the author amending the commit and also Dependabot.

So I realize for your use case they're extraneous but for other projects they're useful.

**Comment by ImRodry** [comment]
> And co-author line is useful for when commits get amended to attribute the commit to both the author amending the commit and also Dependabot.

That is in fact not needed. If you amend a tweet that is not yours, the new tweet will be authored by you and the previous author, even if you don't have the co-author line. Could this be removed please? I always remove it when merging dependabot PRs on my repos and it's really annoying
