### ISSUE TITLE
Use `squash` as shortcut for `squash and merge`

### ISSUE THREAD

**Issue by spenserblack** [dependabot/dependabot-core#3823]
I usually prefer to squash the PR instead of creating a merge commit, since the changes that dependabot makes are usually pretty simple.
However, typing out `@dependabot squash and merge` can get a bit tedious. Would it be possible for `@dependabot squash` to also be a command with the same result as `@dependabot squash and merge`? I think that squashing *and* merging is more common on GitHub than squashing *without* merging, so I think the user's intent could be properly conveyed with just `squash`.

**Comment by jeffwidman** [comment]
👋 sorry for the slow reply.

Is there a reason you use the comment ops rather than directly clicking the `Squash` button in the GitHub UI? Is this from old dependabot-preview or do you need the comment ops for an actions workflow?

**Comment by spenserblack** [comment]
> Is there a reason you use the comment ops rather than directly clicking the `Squash` button in the GitHub UI?

I use the comment ops when the dependency update looks good *to me,* but I'd like to let the actions finish their checks, and/or dependabot is currently rebasing. Basically, once I've reviewed and I want to merge *if the checks have passed,* it's a bit convenient to use comment op than to come back to the PR later.

**Comment by jeffwidman** [comment]
Oh interesting. Is there a reason you don't use branch protections to enforce the CI checks completing and the branch to be up to date before merging? Because then you could enable automerge and effectively get the same thing w/o needing the comment op...

**Comment by spenserblack** [comment]
Interesting! I definitely need to use the branch protection and auto-merge features. To be honest I've used the comment ops out of familiarity. But branch protection isn't available to private repositories on free accounts, right?

Just curious, is there a chance that comment ops are getting deprecated in favor of other GitHub features?

**Comment by spenserblack** [comment]
I've moved on to using auto-merge. I think the GitHub UI fully covers the use cases that previously were covered by comment ops, so I'm closing this.
