### ISSUE TITLE
pip package not resolved to anything in dependency graph

### ISSUE THREAD

**Issue by ntravis** [dependabot/dependabot-core#3829]
**Package ecosystem**
pip
**Package manager version**
n/a
**Language version**
Python, version n/a
**Manifest location and content prior to update**
/requirements/default.txt
**dependabot.yml content**

**Updated dependency**
django-health-check, version doesn't matter
**What you expected to see, versus what you actually saw**
I expect to see a link to the canonical release of django-health-check, i.e. this repo https://github.com/KristianOellegaard/django-health-check similar to other open source packages,

**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
non-public repo, but there is an image of the dependency graph:
![image](https://user-images.githubusercontent.com/8976020/120388315-f3a09f00-c2f8-11eb-9f78-7c1852f90f0f.png)

The "not linked" text is where I would expect to see the normal link as indicated above.

**Comment by jurre** [comment]
Our team does not maintain the dependency graph, currently Dependabot and the dep graph are entirely separate services and teams. If you open an issue with [support](https://support.github.com/contact) they should be able to route it to the right team.
