### ISSUE TITLE
Question: nuget ecosystem scanned files

### ISSUE THREAD

**Issue by aleks-ivanov** [dependabot/dependabot-core#3833]
I apologize for posting this here, but there is no Discussions section and I didn't know where to post the question.

I went through the nuget ecosystem codebase to find which files does Dependabot look for and this is the list I got from what I understood:

'*.sln', '*.csproj', '*.vbproj', '*.fsproj', 'Packages.props', 'global.json', 'nuget.config'

Did I miss anything ?

Also is there a list of files for each ecosystem that Dependabot looks for, so I don't have to go through each ecosystems' codebase ?

**Comment by asciimike** [comment]
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems has the most up to date list for Dependabot Security Updates.

We don't seem to have a similar detailed list for version updates, we just have the full list of supported ecosystems/versions: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem. It's definitely something we should add in the future.
