### ISSUE TITLE
Question: How to scan only root folder ?

### ISSUE THREAD

**Issue by aleks-ivanov** [dependabot/dependabot-core#3834]
Once again, I apologize for posting this here, but there is no Discussions section and I didn't know where to post the question.

Is there any way to instruct Dependabot to scan only the root folder without recursing into inner folders ?

For example, there are a nuget.config and a global.json in the root folder (whilst there are other scannable files in the inner folders) and would like to instruct Dependabot to scan only them two.

**Comment by asciimike** [comment]
If you're using [Dependabot version updates](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates), you would only add a single manifest with the [directory](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory) set as `/`.

If you're using [Dependabot security updates](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates), there currently isn't a way to only enable it on individual manifests--it's all or nothing.
