### ISSUE TITLE
[ Bug ] `directory: '/'` isn't working for the following projects

### ISSUE THREAD

**Issue by aleks-ivanov** [dependabot/dependabot-core#3841]
Created `dependabot.yml` for of these projects:
- https://github.com/microsoft/RockPaperScissorsLizardSpock (composer, docker, maven, nuget, pip)
- https://github.com/dotnet/spark (maven, nuget)

In both instances and all listed ecosystems, the `directoory: '/'` returned 0 dependency sources:

![2q323f](https://user-images.githubusercontent.com/74899441/120614766-3d57c980-c460-11eb-8a84-0677ced7d309.png)

However, when I used a terminal to search for the suggested files individually and extracted a path to their parent folder e.g. `directory: 'src/csharp/Extensions/Microsoft.Spark.Extensions.Delta'`, Dependabot worked as intended:

![43h54564j](https://user-images.githubusercontent.com/74899441/120615046-8871dc80-c460-11eb-803b-07459c065f5d.png)

**Comment by feelepxyz** [comment]
@aleks-ivanov this is a known limitation with dependabot. The `directory` option currently does not accept wildcards and does not scan in sub-directories for manifests unless there's a manifest that references other manifests by path. You'll need to create one config entry for each directory where the dependency manifest exists like you did with your fork.

**Comment by asciimike** [comment]
Closing this as WAI, though I will mention that I have spent a little bit of time thinking about glob syntax in `directory` and I think it's a reasonable feature request.
