### ISSUE TITLE
Consider using groupId and artifactId to avoid confusions

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#3845]
When two packages have the same name, such as these : 

```
     <dependency>
          <groupId>net.sf.ingenias</groupId>
          <artifactId>codegen</artifactId>
          <version>1.2</version>
      </dependency>

      <dependency>
          <groupId>org.eclipse.emf</groupId>
          <artifactId>codegen</artifactId>
          <version>2.1.0</version>
      </dependency>
```

 Dependabot creates  PRs that appear to be identical (besides the different versions, they have the same PR title and commit messages) : 

https://github.com/yeikel/dependabot-playground/pull/4
https://github.com/yeikel/dependabot-playground/pull/5

Both upgrades are "Bumping codegen"  (PR title and commits) 

If I merge these two, it will be hard to differentiate between them and I think that it will be confusing to look at the history.

I believe that it would be better if it was "Bumping groupId:artifactId" to avoid any kind of confusion and be explicit about it

**Comment by jeffwidman** [comment]
This was implemented for Gradle here:
* https://github.com/dependabot/dependabot-core/pull/6526

Shouldn't be hard to do something similar for Maven if anyone wants to take a stab at it.

**Comment by yeikel** [comment]
> This was implemented for Gradle here:
> * https://github.com/dependabot/dependabot-core/pull/6526
> 
> Shouldn't be hard to do something similar for Maven if anyone wants to take a stab at it.

@jeffwidman Can you assign it to me? I'll give it a try

**Comment by jeffwidman** [comment]
Go for it!

@deivid-rodriguez very nicely just revamped [the contributing docs](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md), I suggest reading through them and let us know if anything is confusing or not working as expected.

**Comment by jeffwidman** [comment]
@yeikel is this still of interest?

**Comment by yeikel** [comment]
> @yeikel is this still of interest?

Yes. I am hoping to get to it soon
