### ISSUE TITLE
apply .editorconfig for pull request

### ISSUE THREAD

**Issue by tbugfinder** [dependabot/dependabot-core#3851]
Hi,
it would be helpful if dependabot could apply `.editorconfig` settings properly while creating a PR on a GitHub repo. In my case the `.editorconfig` file is within a subdirectory next to the file being updated.
Not sure if it would use root `.editorconfig` settings, though.

Thanks.

**Comment by jeffwidman** [comment]
Can you expand on this a little more?

Which particular ecosystem and which `.editorconfig` settings would you like applied on the PR?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.
