### ISSUE TITLE
Can't list my repos

### ISSUE THREAD

**Issue by fabioSalimbeni** [dependabot/dependabot-core#3857]
**Package ecosystem**
npm

**What you expected to see, versus what you actually saw**
When I go to https://app.dependabot.com I can see the list of my repos. 

I can see a CORS error thrown in the console.

Access to fetch at 'https://api.dependabot.com/repos?account-id=<my_account_id>&account-type=org&page=1&installation-state=active' from origin 'https://app.dependabot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by asciimike** [comment]
I have seen occasional intermittent issues, but nobody on our team is able to reproduce this one. Does it happen on all browsers? Have you disabled any adblockers, etc. (on the off chance one of them might interfere)?

If you can, we [recommend migrating off Dependabot Preview (dependabot.com)](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot) ASAP, as we won't be fixing issues related to Preview that aren't actively causing issues with migration.
