### ISSUE TITLE
Error listing repositories

### ISSUE THREAD

**Issue by bobvanderlinden** [dependabot/dependabot-core#3859]
We have quite a few repositories that use Dependabot and the listing of repos always took some time. Now however it shows an error after a while:

![image](https://user-images.githubusercontent.com/6375609/121023548-a95d6900-c7a3-11eb-92dc-1f54e92b6751.png)

There is no additional information, so I'm clueless whether this is a duplicate of https://github.com/dependabot/dependabot-core/issues/3857.

The error shows up on the organisation page of dependabot: https://app.dependabot.com/accounts/nedap

**Comment by asciimike** [comment]
I have seen occasional intermittent issues, but nobody on our team is able to reproduce this one. Does it happen on all browsers? Have you disabled any adblockers, etc. (on the off chance one of them might interfere)? Can you open the console and see if there are any errors?

If you can, we [recommend migrating off Dependabot Preview (dependabot.com)](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot) ASAP, as we won't be fixing issues related to Preview that aren't actively causing issues with migration.

**Comment by bobvanderlinden** [comment]
Just did another go, it now works again :+1: Still takes a long time to load.

> If you can, we recommend migrating off Dependabot Preview (dependabot.com) ASAP, as we won't be fixing issues related to Preview that aren't actively causing issues with migration.

Indeed :smile: I just wanted to see which repositories were still on Dependabot Preview so I can notify the right teams. I'll close this issue as I now know which ones need to migrate and do not need the interface anymore :+1:
