### ISSUE TITLE
Dependabot alerts does not support Poetry

### ISSUE THREAD

**Issue by yawhide** [dependabot/dependabot-core#3861]
**Package ecosystem**

Poetry https://github.com/python-poetry/poetry

**Package manager version**

Poetry v1.1.6

**Language version**

Python 3.6.8 (but I assume any python version would not work)

**Manifest location and content prior to update**
`/pyproject.toml`
`/poetry.lock`
**dependabot.yml content**

I only enabled the three buttons found in https://github.com/*/*/settings/security_analysis
**Updated dependency**

n/a
**What you expected to see, versus what you actually saw**

After switching from using a requirements.txt to a pyproject.toml (aka from pip to poetry), I noticed all my security alerts went away even though I did not update my dependencies. I exported a requiremens.txt from my pyproject.toml file and uploaded it to a new repo and all the security alerts appeared.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by asciimike** [comment]
Looks like we don't currently support either of those manifest types at present ([docs of supported ones](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems)), though I'll forward that request on to the team.

**Comment by yawhide** [comment]
Appreciate it!

**Comment by denizgenc** [comment]
So if I understand correctly, Dependabot can automatically update a repository that uses Poetry (see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates), but it can't alert on it?

**Comment by yawhide** [comment]
> So if I understand correctly, Dependabot can automatically update a repository that uses Poetry (see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates), but it can't alert on it?

it can make PRs but you dont get dependenbot security alerts

**Comment by jurre** [comment]
> So if I understand correctly, Dependabot can automatically update a repository that uses Poetry (see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates), but it can't alert on it?

Yep, that's right. These are currently mostly separate services and alerts are not powered by dependabot-core. Eventually we would love support for all ecosystems to be equal across the tools, but we're not there yet.

I'm going to close out this issue as there's not much our team can currently do, but it's being tracked by the right team internally.

**Comment by rsprudencio** [comment]
I'm also interested in this feature, which team/repo maintains dependabot alerts?

**Comment by jurre** [comment]
> I'm also interested in this feature, which team/repo maintains dependabot alerts?

They do not have any public repo's/issue trackers, going through support is the best way to contact them.
