### ISSUE TITLE
Run Dependabot YML Linter on PR too

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#3878]
Dependabot uses a yaml file for its settings. The linter for the yaml only runs on the `main` branch after a change, but not as a check during a PR request.
Please also run the linter in the PR request, to prevent merging invalide yaml configuration in the `main` branch. 

Sample: https://github.com/hfhbd/routing-compose/pull/9, no check and `main ci` with failing check https://github.com/hfhbd/routing-compose/runs/2791232493

**Comment by jurre** [comment]
Thanks for reporting this, it should definitely run on PRs as long as the config file is changed. I'm digging in trying to figure out why this isn't working.

**Comment by jeffwidman** [comment]
This is a dupe of #4605. Although this one is older, that one has more discussion, so closing this one.
