### ISSUE TITLE
Terraform Unknown Error when searching for updates

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dependabot/dependabot-core#3881]
**Package ecosystem**
Terraform

**Manifest location and content prior to update**

https://github.com/amido/stacks-infrastructure-aks/blob/master/.github/dependabot.yml

Pointing to this folder: https://github.com/amido/stacks-infrastructure-aks/tree/master/deploy/azure/infra/stacks-aks

We have a constraints file specifying the versions of things we need: https://github.com/amido/stacks-infrastructure-aks/blob/master/deploy/azure/infra/stacks-aks/constraints.tf

Error Output from the logs:
```
...
updater | INFO <job_156766197> Starting update job for amido/stacks-infrastructure-aks
updater | ERROR <job_156766197> undefined method `fetch' for "~> 2.5":String
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:90:in `build_provider_dependency'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:41:in `block (4 levels) in parse'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:40:in `each'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:40:in `block (3 levels) in parse'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:39:in `each'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:39:in `block (2 levels) in parse'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:37:in `each'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:37:in `block in parse'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:31:in `each'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.152.0/lib/dependabot/terraform/file_parser.rb:31:in `parse'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:546:in `dependencies'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_156766197> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_156766197> bin/update_files.rb:21:in `<main>'
...
```

**Comment by Nishnha** [comment]
We no longer support the [shortname](https://github.com/amido/stacks-infrastructure-aks/blob/master/deploy/azure/infra/stacks-aks/constraints.tf#L4) required-providers syntax since adding support for Terraform 0.13+.
The old syntax is deprecated in favor of the new [source address syntax](https://www.terraform.io/docs/language/providers/requirements.html#source-addresses) for providers.

Try modifying the required-providers block in `constraints.tf` to use source addresses instead.

**Comment by jurre** [comment]
> Hi @Nishnha, thanks for the reply, is there any chance we could have a nicer error message than a Ruby crash please?

Yes, agreed! `@Nishnha` is working on it here: https://github.com/dependabot/dependabot-core/pull/3883

**Comment by ElvenSpellmaker** [comment]
> 
> 
> > Hi @Nishnha, thanks for the reply, is there any chance we could have a nicer error message than a Ruby crash please?
> 
> Yes, agreed! `@Nishnha` is working on it here: #3883

Thanks! =)

**Comment by ElvenSpellmaker** [comment]
Hey @Nishnha and @jurre, your documentation page says you support all Terraform versions less than 1.0:
![image](https://user-images.githubusercontent.com/2286713/121675490-6228ee00-caab-11eb-9ab3-5dab2f7e7206.png)

If you no longer support short names you only support >= 0.12.26 <= 1.0, the docs might need updating. 🙂

**Comment by Nishnha** [comment]
@ElvenSpellmaker the changes to the docs should be merged in tomorrow. Thank you for your vigilance! :)

**Comment by ElvenSpellmaker** [comment]
> @ElvenSpellmaker the changes to the docs should be merged in tomorrow. Thank you for your vigilance! :)

No worries, thanks! 😁
