### ISSUE TITLE
Add Microsoft Library Manager (libman) support

### ISSUE THREAD

**Issue by bdovaz** [dependabot/dependabot-core#3892]
I am configuring dependabot for an ASP .NET Core project and I see that I can configure nuget but not libman.

From what I have seen it is not available whitin the package ecosystems:

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

Would it be possible to implement it? Thank you.

https://github.com/aspnet/LibraryManager

**Comment by jurre** [comment]
We're currently [not adding/accepting new ecosystems into dependabot-core](https://github.com/dependabot/dependabot-core/blob/c25a331685a703c5db72346fa55b9745d6408c46/CONTRIBUTING.md#contributing-new-ecosystems), so this is not something we can currently commit to.

If you would like to build on top of Dependabot, there are some suggestions in the docs I linked to that describe how to do this, and I'd be happy to answer questions.
