### ISSUE TITLE
Docker image can't be built

### ISSUE THREAD

**Issue by PeterDaveHello** [dependabot/dependabot-core#3898]
**Docker version**

<details>

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

According to [Running with Docker](https://github.com/dependabot/dependabot-core#running-with-docker) section in README.md, there is no need to provide any additional build arguments to build the Docker image, however I can reproduce the build failure on different machines:

```
 ---> Running in 7645acdb0293
Removing intermediate container 7645acdb0293
 ---> 5e6d3a0443f7
Step 52/67 : USER dependabot
 ---> Running in 36d75e79772f
Removing intermediate container 36d75e79772f
 ---> eb2c678d2165
Step 53/67 : RUN mkdir -p /opt/bundler/v1   && mkdir -p /opt/bundler/v2
 ---> Running in e8200de2084e
mkdir: cannot create directory ‘/opt/bundler/v1’: Permission denied
The command '/bin/sh -c mkdir -p /opt/bundler/v1   && mkdir -p /opt/bundler/v2' returned a non-zero code: 1
```

After insert one additional Dockerfile instruction: `RUN ls -al /opt/` to debug the issue, I found that the permission seem to be interesting:

```
Step 53/68 : RUN ls -al /opt/
 ---> Running in 869a74d784a9
total 48
drwxr-xr-x  13 dependabot dependabot 4096 Jun 14 13:44 .
drwxr-xr-x 100 root       root       4096 Jun 14 13:56 ..
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 bundler
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 composer
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 dep
drwxr-xr-x  11 root       root       4096 Jun 14 13:42 go
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 go_modules
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 hex
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 npm_and_yarn
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 python
drwxr-xr-x   7 dependabot dependabot 4096 Jun 14 13:43 rust
drwxr-xr-x   3 root       root       4096 Jun 14 13:44 terraform
```

So looks like the user `dependabot` is the owner of `/opt/` but not the content under `/opt/`, even though there is `--chown=dependabot:dependabot` with the upper `COPY` instruction, it seems to apple only on the deeper destination, not every level of the path.

The quick fix is to add an additional Dockerfile instructions: `RUN chown -R dependabot:dependabot /opt/`, and then the image could be built with success on my side, not sure if this is also a problem for the others, or it's just me.

Would like to send a pull request to it if it's confirmed an issue, thanks.

**Comment by PeterDaveHello** [comment]
I can see some updates here: https://hub.docker.com/r/dependabot/dependabot-core/tags

So I assume it's not an everywhere problem ...

Took a look at these two:

- https://github.com/dependabot/dependabot-core/blob/main/.github/workflows/ci.yml
- https://github.com/dependabot/dependabot-core/blob/main/.github/workflows/docker.yml

The difference might be the BUILDKIT.

**Comment by PeterDaveHello** [comment]
After setting `DOCKER_BUILDKIT=1`, I can directly build the image with success, even more, the Docker image size is different:

```
REPOSITORY                    TAG                 IMAGE ID       CREATED             SIZE
with-build-kit                latest              4b6ba3b9e9ff   11 minutes ago      4.19GB
without-build-kit             latest              268b0e15fb5c   50 minutes ago      6.44GB
```

Still think may need to modify the Dockerfile, as buildkit seems to be more like an enhancement, not a requirement 🤔

**Comment by feelepxyz** [comment]
@PeterDaveHello oh interesting! Yeah not sure what happens if you build without buildkit as the cached version of core is built using it so might get weird results because of the mismatch 🤔

We'd like to avoid doing a recursive `chown` as this increase the docker image a lot as all files get added to a new layer.

**Comment by PeterDaveHello** [comment]
@feelepxyz maybe just create the directories earlier with the correct permission? Maybe still need to figure out why the buildkit can avoid the permission issue, and before that, make buildkit a requirement to build the image, maybe have the permission fix in the meanwhile? I can send a pull request to revise the doc.

**Comment by jeffwidman** [comment]
I'm going to close this as Buildkit is very much the "new default" of Docker... so for most folks it should work fine w/o needing to explicitly enable it as long as they're using a relatively modern version of docker.
