### ISSUE TITLE
Unique statistic repo is not correct

### ISSUE THREAD

**Issue by sagittaracc** [dependabot/dependabot-core#3919]
it seems to me that my unique statistic repo doesn't work right.
Every time i push into my repo and then go to Insight > Traffic, i see unique clones number which are pretty much the same as a number of the push i've made. Which makes me think it is dependabot's clones.
I think dependabot's clones shouldn't be considered as the real repo clone cuz it makes the statistic not authentic.

**Comment by asciimike** [comment]
I'll try to find some time to dive into where this metric comes from; I agree that # clones should probably reflect human users instead of bot users (or at least separate that out).

**Comment by jurre** [comment]
@sagittaracc could you share a repo where you're observing this? I'm asking because for most ecosystems Dependabot does not perform git clones, but instead use the API to fetch data.

**Comment by sagittaracc** [comment]
@jurre yes sure. This repo: https://github.com/sagittaracc/suql

**Comment by sagittaracc** [comment]
@jurre this repo has no watchers. Also i dont have any followers. So i dont see any other reasons behind the misterious # clones.

**Comment by jurre** [comment]
Thanks @sagittaracc, for composer Dependabot definitely should not clone the repository.

I'm also not seeing any Dependabot PRs on that repo, so even if dependabot _did_ clone for composer (which it doesn't), it doesn't look like it's ever ran.

Could this be a CI job, or some other automated process that pulls it in? The repo is public, so anyone should be able to clone it.

**Comment by sagittaracc** [comment]
i am not sure what a CI job is, but it is possible that some real people clone the repo for example when i push my repo is the first on the list by hash tags orm as last updated. I would be cool to see some advanced statistic like who exaclty has cloned the repo or something like this.

**Comment by jurre** [comment]
I agree it'd be cool! But this repo is really only for Dependabot specific things, a better place to discuss something like that would be here: https://github.com/github/feedback/discussions

I'm going to close this out since there's not much we can do on the Dependabot side.
