### ISSUE TITLE
[Questions] it is able use it for local project?

### ISSUE THREAD

**Issue by JiangWeixian** [dependabot/dependabot-core#3942]
dear dependabot team

I have project never push it to github/gitlab, may i use this repo locally by `bin/dry-run.rb npm_and_yarn path/repo`

**Comment by jurre** [comment]
Yep, you can, as per the README:

> If you want to host your own automated dependency update bot then this repo should give you the tools you need. A reference implementation is available [here](https://github.com/dependabot/dependabot-script).
