### ISSUE TITLE
Status of accepting new ecosystems

### ISSUE THREAD

**Issue by seahindeniz** [dependabot/dependabot-core#3943]
There is a decision for not accepting new ecosystems until June 2021 that is stated in the `CONTRIBUTING.md` file, and I want to ask what are the current decision for supporting new ecosystems?
Are there any news from the `dependabot` team since we are in/passing June 2021?

> We are not currently accepting new ecosystems into dependabot-core, starting in December 2020 until at least June 2021.

https://github.com/dependabot/dependabot-core/blob/1b17a40a0f0c51ecc40560aa888d06a7e554353b/CONTRIBUTING.md#L14

I'm personally waiting for #1736 to be resolved

**Comment by asciimike** [comment]
Much of what is said in that document is still true: we're investing heavily in the product, but don't have the expertise to properly maintain every ecosystem being asked for. Right now, the only way we're able to properly support new ecosystems is if the ecosystem maintainers are willing to help support it (so if you know the `pnpm` maintainers, please have them chime in on that issue).

I'll update `CONTRIBUTING.md` to remove the date and clarify that.

Long term, we're looking into what it would take to break up dependabot-core and allow folks to write their own Dependabot updaters and run them on our infrastructure, allowing folks to add arbitrary languages without the need for us to merge them into core.

**Comment by seahindeniz** [comment]
The long-term decision sounds fantastic!

cc @zkochan

**Comment by jeffwidman** [comment]
I'm going to close as the info ☝️ answered the original question.

As far as an update, unfortunately it's  still the current answer. We are hoping to be in a position soon to start to discuss support for new ecosystems, as we've shipped a _lot_ of internal infra over the past few quarters to build out a solid platform, but don't have anything more specific we can share just yet.
