### ISSUE TITLE
Positional Dependency does not update with Gradle KTS

### ISSUE THREAD

**Issue by NyCodeGHG** [dependabot/dependabot-core#3956]
**Package ecosystem**

Gradle
**Manifest location and content prior to update**
https://github.com/NyCodeGHG/dependabot-test/blob/5f9f088aef544e347aabf946d02195c6e0cb79b5/build.gradle.kts
**dependabot.yml content**

https://github.com/NyCodeGHG/dependabot-test/blob/5f9f088aef544e347aabf946d02195c6e0cb79b5/.github/dependabot.yml
**Updated dependency**

```kotlin
implementation("org.slf4j", "slf4j-api", "1.7.30")
// Should update to
implementation("org.slf4j", "slf4j-api", "1.7.31")
```
**What you expected to see, versus what you actually saw**
I expected the dependency to get updated.
Dependabot didn't recognized the dependency and it wasn't present in the logs.

**Images of the diff or a link to the PR, issue or logs**
https://hastebin.com/dasofisise.yaml
**🕹 Bonus points: Smallest manifest that reproduces the issue**

build.gradle.kts:
```kotlin
plugins {
    kotlin("jvm") version "1.5.10" // or java plugin
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.slf4j", "slf4j-api", "1.7.30")
}
```

**Comment by DRSchlaubi** [comment]
Related to #1164 as tooling api would cover this

**Comment by thepwagner** [comment]
I agree with _DRSchlaubi, the tooling API is the way to actually fix this.
For detecting the dependency at least... I'm less sure that the tooling API will making updating `"1.7.30"` easier, but I'd love to learn if it is.

For now, is expressing dependencies in the format Dependabot can parse an acceptable workaround?

**Comment by NyCodeGHG** [comment]
if it is not possible to change that, that would be ok, but I find the syntax that I use now much more readable
