### ISSUE TITLE
Unrelated packages being updated due to yarn dedupe

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#3964]
**Package ecosystem**
yarn

**Package manager version**

npm@7.7,4

node 14.16.1

**What you expected to see, versus what you actually saw**
We have a service built on top of dependabot-core which runs for azure based repos. Recently, in a PR created by our service for lerna managed yarn monorepo, there were some updates to some unrelated packages which were not a part of the dependency tree for the package being updated in the PR. For e.g `adal-node` was the dependency for which the PR was created. However, the PR also contained changes for `@jest/reporters` which was not a subdependency for the `adal-node`. 
The change in @jest/reporters was basically updating it to a new version which was satisfied by the given semver constraints. Experimenting with the code in `helpers/yarn/updater.js`, i found that this might be related to the `deduplication` done by dependabot-core in case of yarn because after commenting out the de-duplication logic, i was able to create PR with the expected changes.
Is this the expected behaviour with deduplication? Should'nt it dedupe only the subdependencies for the concerned dependency update? 

Let me know if i'm missing something here
@jurre @feelepxyz

**Comment by feelepxyz** [comment]
@milind009 yarn dedupe currently dedupes the whole lockfile so might remove unrelated packages: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/helpers/lib/yarn/fix-duplicates.js

**Comment by milind009** [comment]
> @milind009 yarn dedupe currently dedupes the whole lockfile so might remove unrelated packages: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/helpers/lib/yarn/fix-duplicates.js

I see here we pass a `updatedDependencyName` and only dedupe the subdependencies only for that dependency and update them to the maximum possible version. However in my case, i was seeing some unrelated dependency being updated to max version possible according to the semver constraints. Let me know if i'm missing something in code for dedupe

**Comment by milind009** [comment]
I think i got it how dependabot dedupes the entire lockfile. Here: https://github.com/dependabot/dependabot-core/blob/07243bf2365993508e08aee1d7f055336168395e/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb#L66, it calls `run_yarn_updater` for all the top level dependencies hence deduping the entire lockfile. 
Additionally i tried running yarn install (dedupe included) locally and i observed that it only reduces duplicate version for dependencies whereas in dependabot we also try to update it to the latest possible version according to the semver constraint while deduping. Was this an additional functionality added to dependabot or is it already present in yarn and can be enabled through some command option?

**Comment by milind009** [comment]
Duplicate of #4063
