### ISSUE TITLE
Dependabot not following pagination on Quay.io

### ISSUE THREAD

**Issue by day1118** [dependabot/dependabot-core#3989]
**Package ecosystem**
Docker
**Package manager version**
NA
**Language version**
NA
**Manifest location and content prior to update**
**/Dockerfile**
```docker
FROM quay.io/invisionag/yet-another-cloudwatch-exporter:v0.24.0-alpha
USER exporter
```
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
```
**Updated dependency**
From: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.24.0-alpha`
To: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.27.0-alpha`
**What you expected to see, versus what you actually saw**
Dependabot reported that there are no updates on the docker image. Looking closer, the logs reported that the latest tag is `0.12.0-alpha`. Following the `GET https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list` operation shows that this is correct, but the response includes pagination (limit 50) which is likely not being followed.
**Native package manager behavior**
NA
**Images of the diff or a link to the PR, issue or logs**
NA
**🕹 Bonus points: Smallest manifest that reproduces the issue**
See above
**Additional info**
The `yet-another-cloudwatch-exporter` registry did move to using a `v` prefix in the image tag starting at  `v0.13.1-alpha`, however, there is a `0.13.0-alpha` tag, which should have been detected if the prefix was the case (I believe there is support for that prefix anyway based on https://github.com/dependabot/dependabot-core/pull/1195)
**Dependabot logs**
```
  proxy | time="2021-06-25T09:37:42Z" level=info msg="proxy starting" commit=97f78db7d4c42ec4f30c03ac9a981efd790f852d
  proxy | 2021/06/25 09:37:42 Listening (:1080)
updater | 2021-06-25T09:37:42.442133533 [165790641:main:WARN:src/devices/src/legacy/serial.rs:434] Detached the serial input due to peer close/error.
updater | time="2021-06-25T09:37:44Z" level=info msg="guest starting" commit=524810a0a39a9005af53185e9bb7817463751bc4
updater | time="2021-06-25T09:37:44Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=165790641 updater_timeout=45m0s updater_version=0.156.1-3e98b4e9cb1701f0fe394cdcf227935fa77fd407
updater | I, [2021-06-25T09:37:45.449859 #9]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_165790641> Starting job processing
  proxy | 2021/06/25 09:37:47 [002] GET https://api.github.com:443/repos/cyralinc/cyral-yace
  proxy | 2021/06/25 09:37:47 [002] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [002] 200 https://api.github.com:443/repos/cyralinc/cyral-yace
  proxy | 2021/06/25 09:37:47 [004] GET https://api.github.com:443/repos/cyralinc/cyral-yace/git/refs/heads/main
  proxy | 2021/06/25 09:37:47 [004] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [004] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/git/refs/heads/main
  proxy | 2021/06/25 09:37:47 [006] GET https://api.github.com:443/repos/cyralinc/cyral-yace/contents/?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [006] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [006] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/contents/?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [008] GET https://api.github.com:443/repos/cyralinc/cyral-yace/contents/Dockerfile?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [008] * authenticating github api request
  proxy | 2021/06/25 09:37:48 [008] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/contents/Dockerfile?ref=226e1445eb24abf365b113cc280832358ce56550
updater | INFO <job_165790641> Finished job processing
updater | time="2021-06-25T09:37:48Z" level=info msg="task complete" container_id=job-165790641-file-fetcher exit_code=0 job_id=165790641 step=fetcher
updater | I, [2021-06-25T09:37:49.058595 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_165790641> Starting job processing
updater | INFO <job_165790641> Starting update job for cyralinc/cyral-yace
updater | INFO <job_165790641> Checking if invisionag/yet-another-cloudwatch-exporter v0.24.0-alpha needs updating
  proxy | 2021/06/25 09:37:51 [012] GET https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
  proxy | 2021/06/25 09:37:51 [012] 200 https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
updater | INFO <job_165790641> Latest version is 0.12.0-alpha
updater | INFO <job_165790641> No update needed for invisionag/yet-another-cloudwatch-exporter v0.24.0-alpha
updater | INFO <job_165790641> Finished job processing
updater | time="2021-06-25T09:37:51Z" level=info msg="task complete" container_id=job-165790641-updater exit_code=0 job_id=165790641 step=updater
```

**Comment by thepwagner** [comment]
Dependabot uses https://github.com/deitch/docker_registry2 to interact with Docker registries.

The relevant code is around https://github.com/dependabot/dependabot-core/blob/279956f9f28dd1dce087a2163615a8d6c99c827b/docker/lib/dependabot/docker/update_checker.rb#L231 ; we pass `auto_paginate: true`.

The library's code stands up to a readthrough to me:
https://github.com/deitch/docker_registry2/blob/220c03d5d2ad0268ca97ecabb16cc8ec58943dbd/lib/registry/registry.rb#L65 seems to follow the `link` header to the next page, as https://docs.docker.com/registry/spec/api/#listing-image-tags says it should.

**Comment by thepwagner** [comment]
Quay seems to be doing an unexpected form of pagination:

```
$ curl -I https://quay.io/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
HTTP/2 200
server: nginx/1.12.1
date: Fri, 25 Jun 2021 19:12:07 GMT
content-type: application/json
content-length: 730
link: </v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1iqHhz0fi3SSJWjvf1I2bf9lBdyjrGS6OFvm09Hooy3yjhLJRcD2UzjUjIDgYdDSCshWY5U8cEl83toaY-jTTtXRmTTZxeTSEeRIJHalvO_0aRA%3D&n=50>; rel="next"
x-frame-options: DENY
strict-transport-security: max-age=63072000; preload
```

The library dependabot uses expects [`last=`](https://github.com/deitch/docker_registry2/blob/220c03d5d2ad0268ca97ecabb16cc8ec58943dbd/lib/registry/registry.rb#L226) to be used for pagination in the `link` header, not `next_page`.

I think it may have followed the example from the spec too closely, if we assume [docker's implementation](https://github.com/distribution/distribution/blob/a1e30cca34d3ef49514fb22244a1ad375828a24d/registry/client/repository.go#L244-L254) of this logic is authoritative - that's not how pagination should work.

**Comment by day1118** [comment]
Thanks for the investigation and update @thepwagner 
Is there anything that can be done in the meantime? Or Dependabot cannot be relied upon for the Quay.io registry with more than 50 images?

**Comment by xlgmokha** [comment]
> Is there anything that can be done in the meantime?

I don't know of a temporary solution at the moment. We could try to apply a monkey patch specifically for quay.io but it's not clear to me if that will pass review. I think a patch upstream would be helpful. https://github.com/deitch/docker_registry2/issues/56#issuecomment-869496320

>  Or Dependabot cannot be relied upon for the Quay.io registry with more than 50 images?

I'm not up to date on the spec but I think we'll need to update the quay.io registry to align with the other docker registries or potentially patch upstream as I mentioned above. I'm open to suggestions.

**Comment by Nishnha** [comment]
The problem is investigated in an [upstream dependency](https://github.com/deitch/docker_registry2/issues/56#issuecomment-869496320).
Closing this issue as stale.

**Comment by day1118** [comment]
> The problem is investigated in an [upstream dependency](https://github.com/deitch/docker_registry2/issues/56#issuecomment-869496320).
> Closing this issue as stale.

While the source of the problem is an upstream repo, the bug still manifests and dependant does not work as expected (or provide any warning). I think the issue should remain open until the upstream is resolved.

**Comment by aitoracedo** [comment]
This is still an issue in our team. Is there any new update on this topic?
