### ISSUE TITLE
Update dependency subtrees

### ISSUE THREAD

**Issue by kanishka-work** [dependabot/dependabot-core#3992]
Create PRs to update trees of dependencies.

For example, if my project depends on A which depends on B which depends on C, if B and A have new versions, then create a PR using the new versions of A and B together.

**Comment by jurre** [comment]
Grouped updates is definitely something that's on our radar. I think most of this is tracked [here](https://github.com/dependabot/dependabot-core/issues/1296) and [here](https://github.com/dependabot/dependabot-core/issues/1190). They don't explicitly mention subtrees but it seems similar enough to not track separately.
