### ISSUE TITLE
Support vendoring for Python

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#400]
_From @Kristinita on January 21, 2018 4:6_

### 1. Request

It would be nice, if would be possible upgrade dependencies, not only version numbers in requirements file.

For example, it would be nice add an option, that bot will run command after each version changing in requirements file.

### 2. Steps to reproduce

I develop plugins for Sublime Text, written on Python. By technical reasons I need add dependencies to my repository.

In my [**repository for testing**](https://github.com/Kristinita/SashaAnotherPyup) I add outdated version of [**PyPI gsearch**](https://pypi.python.org/pypi/gsearch) module to `requirements.txt` file. I use command:

    pip install -r requirements.txt -t . --upgrade

### 3. Justification

Automatically dependencies upgrading may save developers time.

I test Dependabot on my test repository. Dependabot only [**change dependency version**](https://github.com/Kristinita/SashaAnotherPyup/pull/2) in `requirements.txt` file, but not upgrade my gsearch dependency, that I include to my repository.

I need upgrade my dependency manually; after merging I need run command again:

    pip install -r requirements.txt -t . --upgrade

It would be nice, if Dependabot will run this command automatically after each version change in `requirements.txt` file.

Thanks.

_Copied from original issue: dependabot/feedback#76_

**Comment by greysteil** [comment]
Thanks for the feedback @Kristinita. This one will require quite a bit of work on our side, given the way we currently update Python files (it's using regexes, not shelling out to Python). I'd like to do it in future, though, so will keep it here as a reminder.

**Comment by electrofelix** [comment]
@greysteil is the generic problem here that there is a need for user specified post-run commands? Though I'm guessing there are some security issues with something like that

**Comment by greysteil** [comment]
Not exactly - Dependabot doesn't clone your repo (for security reasons), so it *can't* currently run user specified post-run commands. They're probably more suited to a CI environment.

**Comment by Kristinita** [comment]
Not solved.

Thanks.
