### ISSUE TITLE
Is dependabot-core used by GitHub native Dependabot?

### ISSUE THREAD

**Issue by moltenice** [dependabot/dependabot-core#4006]
Does [GitHub Native Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) use `dependabot-core`'s logic?

I am interested in finding out if this repo, `dependabot-core`, will be maintained longer term for handling dependencies in GitHub's repositories now that dependabot.com is soon to retire.

**Comment by jurre** [comment]
Yep, it is powering the native version and it's not going anywhere!

**Comment by moltenice** [comment]
Brilliant thanks for clarifying!
