### ISSUE TITLE
Dependabot created PR updating stable release to pre-release

### ISSUE THREAD

**Issue by hemberger** [dependabot/dependabot-core#4020]
**Package ecosystem**
docker

**Package manager version**
N/A

**Language version**
N/A

**Manifest location and content prior to update**
/Dockerfile
https://github.com/smrealms/smr/blob/f19a32648091a76e5a691473cc17c4c70276e17e/Dockerfile

**dependabot.yml content**
https://github.com/smrealms/smr/blob/f19a32648091a76e5a691473cc17c4c70276e17e/.github/dependabot.yml

**Updated dependency**
From: php:8.0.7-apache
To: php:8.1.0alpha2-apache

**What you expected to see, versus what you actually saw**
Since `php:8.0.7-apache` is a stable release and `php:8.1.0alpha2-apache` is a pre-release, I expected Dependabot to not open a PR.

If this is the intended behavior (I could not find documentation stating definitively one way or the other), then it would be really helpful to have an option to disable PRs for pre-releases.

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**
https://github.com/smrealms/smr/pull/1095

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```Dockerfile
FROM php:8.0.7-apache
```

Thank you!

**Comment by ruudk** [comment]
Similar issue here:
```
Bump php from 8.0.5-fpm to 8.1.0alpha2-fpm
```

**Comment by atc0005** [comment]
I encountered this on multiple projects this AM:

```diff
diff --git a/dependabot/docker/go/Dockerfile b/dependabot/docker/go/Dockerfile
index 07353ab..f05540d 100644
--- a/dependabot/docker/go/Dockerfile
+++ b/dependabot/docker/go/Dockerfile
@@ -15,4 +15,4 @@
 # binaries) to reflect that version of Go.
 
 # https://hub.docker.com/_/golang
-FROM golang:1.16.5
+FROM golang:1.17beta1
```

**Comment by deivid-rodriguez** [comment]
Pretty sure this issue has been fixed in recent times since I did some manual testing and worked fine and we also have specific tests for this situation.

So let me close this but feel free to reopen if I'm mistaken and this is still happening.

Thanks!
