### ISSUE TITLE
Private repository name gets overwritten in poetry.lock update (even when the update is for a PyPI package)

### ISSUE THREAD

**Issue by isobelhooper** [dependabot/dependabot-core#4026]
**Package ecosystem**: Python / poetry
**Package manager version**: Poetry 1.1.7
**Language version**: Python 3.8
**Manifest location and content prior to update**:

_Shortened and redacted pypoetry.toml_:

```
[tool.poetry.dependencies]
python = "^3.8"
environ-config = "^20.1.0"
private-package = { version = "=0.17.0", source = "private-repository" }

[[tool.poetry.source]]
name = "pypi-default"
url = "https://pypi.org/simple/"

[[tool.poetry.source]]
name = "private-repository"
url = "https://redacted-pypi.example.com/simple/"
secondary = true

...
```

_Shortened and redacted poetry.lock_:

```
[[package]]
name = "environ-config"
version = "20.1.0"
description = "Boilerplate-free configuration with env variables."
category = "main"
optional = false
python-versions = "*"

[package.source]
type = "legacy"
url = "https://pypi.org/simple"
reference = "pypi-default"

[[package]]
name = "private-package"
version = "0.17.0"
description = "A package on our private PyPI-alike server."
category = "main"
optional = false
python-versions = ">=3.7,<4.0"

[package.source]
type = "legacy"
url = "https://redacted-pypi.example.com/simple/"
reference = "private-repository"

...
```

**Updated dependency**: environ-config, from 20.1.0 to 21.2.0

**What you expected to see, versus what you actually saw**:
_Expected_
* environ-config and its dependencies have their version numbers updated in their `[[package]]` sections and in `[metadata.files]` in poetry.lock, and also in `[tool.poetry.dependencies]` in pyproject.toml.
* The content-hash in the `[metadata]` section is updated.
* Possibly Poetry finds some other file changes, but nothing else outside `[metadata.files]` or the appropriate `[[package]]` sections are changed.
 
_Observed_
* environ-config and its dependencies have version numbers updated as expected.
* content-hash is updated as expected.
* However, the name of the private repository in poetry.lock is also changed to a 4-digit hex string in the `[package.source]` section for `private-package`:

```
[package.source]
type = "legacy"
url = "https://redacted-pypi.example.com/simple/"
reference = "1bd7"
```

but is not changed in pyproject.toml, resulting in an error in our tests of `Repository "1bd7" does not exist.`.

**Native package manager behavior**

When run on the pyproject.toml file that Dependabot produces, `poetry lock --no-update` does not change the reference name to a hex string.

----

The hex string looks like it comes from [config_variable_sources in PyprojectPreparer](https://github.com/dependabot/dependabot-core/blob/5ed3f7fcb086b1c71fa3b846bebdaa76b0add879/python/lib/dependabot/python/file_updater/pyproject_preparer.rb#L109), but I'm afraid I don't know Ruby well enough to have searched any further.

Apologies for the heavily redacted manifests - I hope these are useful enough on their own, but can try to produce actual poetry.lock and pyproject.toml files that are small but still reproduce this behaviour if the excerpts above are not enough.

**Comment by estiller** [comment]
This issue might be related to https://github.com/dependabot/dependabot-core/issues/2487.
It prevents using Dependabot on repositories with Poetry that use private Python registries.

**Comment by mishok13** [comment]
As far as I can tell this is still an issue for dependabot running on GitHub. I'm not sure when GitHub picks up dependabot-core releases, but in all recent (i.e. less than 3 days old) dependabot PRs the references in `poetry.lock` to our private PyPI mirror have been updated with 4 character long string:
<img width="168" alt="Screenshot 2022-01-27 at 10 44 55" src="https://user-images.githubusercontent.com/548482/151333664-6592facd-7b6e-4d82-b680-ab94ff5d6c22.png">.

Can you provide some insight here @jurre ?

**Comment by itsdani** [comment]
I can confirm this is still an issue, references still get overwritten in the poetry lock file on GitHub.
@jurre Is it possible this is not yet used by GitHub, or should we open a new Issue for this?

**Comment by estiller** [comment]
@itsdani @jurre We are using the private repo a secondary source, and we are still seeing this issue on GitHub. I thought that GitHub didn't pick up this version yet, but if it did, then it still doesn't work.

**Comment by nicolewhite-p44** [comment]
having the same problem...is anyone working on a fix? the "reference" in my poetry.lock gets replaced with a random value

**Comment by itsdani** [comment]
Since this issue is closed with a merged solution, I think we should move over to the new one #4797
