### ISSUE TITLE
Ignoring all sem versions in the ignore field does not update vulnerable packages. 

### ISSUE THREAD

**Issue by MassivDash** [dependabot/dependabot-core#4027]
According to this link https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore. 

> update-types—use to ignore types of updates, such as semver major, minor, or patch updates on version updates (for example: version-update:semver-patch will ignore patch updates). You can combine this with dependency-name: "*" to ignore particular update-types for all dependencies. Currently, version-update:semver-major, version-update:semver-minor, and version-update:semver-patch are the only supported options. **Security updates are unaffected by this setting**.

If I read this correctly, setting up ignore array with ```dependency-name: "*", update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"] ``` should result in security PR's and bumps to vulnerable packages, however Dependobot ignores all updates.
  
I am using latest dependobot docker image 0.156.4 and scanning a node.js project (npm_and_yarn) with confirmed vulnerable package (axios 0.19.2, https://snyk.io/vuln/SNYK-JS-AXIOS-1038255) 

I would expect this package to get bumped according to the documentation. What is the correct way to set up only sec updates with  dependobot docker image ?

**Comment by asciimike** [comment]
I don't believe that the Dependabot docker image handles security updates, as those are handled on GitHub's infrastructure and not in `dependabot-core`.

If you're doing things locally, I'd run `npm audit fix` in this case.

**Comment by MassivDash** [comment]
Thank you for your comment, so you saying that depondobot-core is unable to produce sec updates only ?This is GitHub specific feature ? I am well aware of the npm audit cmd line, but I am looking for a bit more than a simple script that runs audit npm for me. I would like to to run the dependobot in a self hosted environment, an a cron schedule, in many different strategies (sec only) ?

**Comment by asciimike** [comment]
> so you saying that depondobot-core is unable to produce sec updates only

Correct. Here's the general flow:
 - A vulnerability is added to GitHub's Advisory Database, either by us curating the National Vulnerability Database, or by a maintainer letting us know of a vulnerability
 - We trigger Dependabot Alerts if you have a vulnerable dependency in your repo
 - We perform Dependabot Security Updates to update that dependency to the minimum fixed version

I believe that dependabot-core has the logic to perform security updates, it just isn't easily able to be plumbed into the flow of "we'll send you an alert to trigger that update". I don't think that there's an easy way for us to re-jigger core to be more aware of vulnerable packages in your manifest, so unfortunately I don't think what you're asking is going to be easily done. 

I will say that version updates are a superset of security updates, in that if you're always on the latest version of a dependency, you'd only get security updates for the latest update, which you'd be getting anyways. If your cron is running daily, it's basically going to be the same, though obviously with a bit more overhead to keep packages updated (though, you're using Dependabot, so obviously you care about doing that anyways!).
