### ISSUE TITLE
[Question] Ignore non-production ready versions

### ISSUE THREAD

**Issue by sehenst** [dependabot/dependabot-core#4028]
Is it possible to ignore non-production ready versions such as `-preview` versions?

Example: 
```
Bump mssql-jdbc from <older version> to 9.3.1.jre11-preview
```

**Comment by hemberger** [comment]
Also related: https://github.com/dependabot/dependabot-core/issues/4020

**Comment by sehenst** [comment]
According to https://semver.org/#spec-item-9

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

So I guess that `dependabot` should ignore these type of versions **AND** other projects must use these naming conventions in order for everything to work, right?

**Comment by hemberger** [comment]
Yeah, it might be out of dependabot's hands if the project isn't using semver. Perhaps there could be an option to ignore non-semver releases?

**Comment by arnested** [comment]
Being able to [`ignore`](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore) versions using regular expressions could also be a solution (although each repo would have to configure a suiting ignore themselves).

**Comment by hemberger** [comment]
I'm seeing this issue again for the PHP 8.2 release candidates, e.g. https://github.com/smrealms/smr/pull/1440.

> Bumps php from 8.1.7-apache to 8.2.0RC2-apache.

**Comment by jeffwidman** [comment]
We've shipped a number of improvements to the docker version parsing thanks to @deivid-rodriguez 's hard work.

So I'm going to close as I suspect most of the examples in this issue have been fixed, plus this issue is becoming a catch-all rather than specific bugs... so not very actionable.

If you _do_ happen to notice it happening again, please open a new issue with the specific example that you're seeing.
