### ISSUE TITLE
terraform: add h1 hashes for multiple os_arch in terraform.lock.hcl file

### ISSUE THREAD

**Issue by mwieczorek** [dependabot/dependabot-core#4042]
## Problem

Dependabot updates terraform.lock.hcl file with h1 hash for new provider version, but only for default platform it runs on. Example PR: https://github.com/mwieczorek/dependabot-test/pull/1

In above example I run locally command

```
terraform providers lock \                      
  -platform=linux_arm64 \
  -platform=linux_amd64 \
  -platform=darwin_amd64 \
  -platform=windows_amd64
```

which produced 4 h1 hashes in file. When depedabot run, it added only one h1 hash (linux_amd64). 

If I merge that PR and then clone the repository locally I may run into one of the issues:

1. ([cached providers](https://www.terraform.io/docs/cli/config/config-file.html#plugin_cache_dir): plugin_cache_dir set in .terraformrc file) - during local `terraform init` I'll get an error like `Error while importing hashicorp/vault v2.21.0 from the shared cache directory: the provider cache at .terraform/providers has a copy of registry.terraform.io/hashicorp/vault 2.21.0 that doesn't match`
2. (no cached providers) -  local`terraform init` will update terraform.lock.hcl file with new h1

## Proposed solution

Add most common os_arch 'platforms' to ['terraform providers lock' command](https://github.com/dependabot/dependabot-core/blob/5042e9c39132b07d6253cfa531ef4f1514d35e9e/terraform/lib/dependabot/terraform/file_updater.rb#L110). F.e. linux_amd64, darwin_amd64, windows_amd64

I understand some providers may not have all of those os_arch combinations, so dependabot should gracefully ignore if one of them is not available.

**Comment by billinghamj** [comment]
I wonder if this could be worked around temporarily with a Github Action workflow which adds to the dependabot PR 🤔

**Comment by moritzheiber** [comment]
Right now, all of dependabot's PRs for Terraform are useless to us because they only include the hashes for `linux_amd64`, and not any of the other architectures. I'd love to see this either turned into an option (e.g. `architectures = [linux_amd64, darwin_amd64]`) or default to "all platforms" by default.

**Comment by sebbrandt87** [comment]
It would be valuable to have to option to extend the platform providers locking.

https://github.com/dependabot/dependabot-core/blob/f6acb90326f54ad7b19d6045ad9d8f9960248855/terraform/lib/dependabot/terraform/file_updater.rb#L115

Or we simply add all needed platforms in the hcl.lock through the flags `-platform=linux_amd64 -platform=linux_arm64 -platform=darwin_amd64 -platform=windows_amd64`.

Parsing the `hcl.lock` and deciding which to take might be to much.

**Comment by jeffwidman** [comment]
Wasn't this effectively fixed by?
* #4905
