### ISSUE TITLE
Dependabot fails when `setuptools` is listed in `pyproject.toml`

### ISSUE THREAD

**Issue by matteosantama** [dependabot/dependabot-core#4058]
It is a known issue that `poetry` does not treat `setuptools` as a regular dependency (https://github.com/python-poetry/poetry/issues/1584). Specifically, `setuptools` does not get an entry in `poetry.lock`. 

This causes `dependabot` to fail for projects that list `setuptools` as an explicit dependency (say, in their `pyproject.toml`). 

```ruby
def fetch_version_from_parsed_lockfile(updated_lockfile)
    version =
        updated_lockfile.fetch("package", []).
        find { |d| d["name"] && normalise(d["name"]) == dependency.name }&.
        fetch("version")
    
    return version unless version.nil? && dependency.top_level?
    
    raise "No version in lockfile!"
end
```
Link: https://github.com/dependabot/dependabot-core/blob/81336a26dbf70a117463b2936307e5ad0d0d02f0/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb#L103

It looks like this will be resolved on the `poetry` side with the release of `poetry==1.2.0`, but there has been no indication when that will actually be released. In the meantime, I propose special-casing `setuptools` (along with `pip`, `wheels`, and `distribute`) ~in the `fetch_version_from_parsed_lockfile` function~ at some point in the `poetry` processing pipeline.

**Comment by jurre** [comment]
@matteosantama thanks! Special casing for now sounds good to me, from briefly glancing at the code you linked to it seems like we may be able to do something like:

```ruby
module Dependabot
  module Python
    class UpdateChecker
      # This class does version resolution for pyproject.toml files.
      class PoetryVersionResolver
        # These dependencies are treated differently by poetry, and don't get an entry in the lockfile.
        # This causes resolution to fail, until this is resolved in poetry we ignore them. This is expected to land in poetry 1.2.0
        IGNORED_DEPENDENCY_NAMES = %w(pip wheels distribute)

        # .... 

        def fetch_version_from_parsed_lockfile(updated_lockfile)
          return if IGNORED_DEPENDENCY_NAMES.include?(dependency.name)
```

Would you be up for contributing such a patch? We'll want some tests to verify this behavior, and I'm not entirely sure the suggested implementation I wrote down will actually work.

Lmk, we can put it on our backlog if you don't have the spare cycles to look into it 🙇

**Comment by jeffwidman** [comment]
We're now using `poetry` > `1.2.0`, so this should just work with no need to special case!
