### ISSUE TITLE
Please allow us to modify the commit message format

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#406]
_From @StephanBijzitter on February 1, 2018 9:58_

After this pull request: https://github.com/dependabot/dependabot-core/pull/244

Our commitlint started to fail, since we do have it set up to expect `chore(dependencies): `. It's nice that you cater to the Angular project, but this is a breaking change for us. Now we can modify the commit message when squash merging, but that still leaves every pull request with a red cross.

To take a piece of code from the pull request, we would expect the message to be: `"chore(dependencies): bump business from 1.4.0 to 1.5.0"` (notice the `b` in `bump`, not `B`)

So, please allow us to configure this message to our liking. I'd open up a pull request myself, but I have no experience with Ruby. If you agree this is a wanted feature, but you don't have time for it, I'd love to give it a shot though!

```
input: build: Bump commander from 2.12.2 to 2.13.0
   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
   found 1 problems, 0 warnings
```

_Copied from original issue: dependabot/feedback#82_

**Comment by gabemeola** [comment]
> _From @deivid-rodriguez on February 4, 2018 16:13_
> 
> I know this would be definitely more work but projects use lots of different commit message conventions, it'd be nice if dependabot played nice with everyone via configuration.
> 
> Ideally I'd like to be able to tell dependabot specifically the template for the commit message I want, like:
> 
> ```
> Bump %{library} from %{original_version} to %{final_version}.
> ```



> _From @deivid-rodriguez on February 4, 2018 16:13_
> 
> I know this would be definitely more work but projects use lots of different commit message conventions, it'd be nice if dependabot played nice with everyone via configuration.
> 
> Ideally I'd like to be able to tell dependabot specifically the template for the commit message I want, like:
> 
> ```
> Bump %{library} from %{original_version} to %{final_version}.
> ```

@greysteil Are there any plans to support custom commit messages in the future?

My specific use case is including `[ci skip]` in the commit message.
https://gitlab.com/help/ci/yaml/README#skipping-jobs

**Comment by greysteil** [comment]
It's come up quite a few times, so we almost certainly will in future. It's not imminent, though - won't be before the end of the month.

**Comment by greysteil** [comment]
With dependabot-script you might be able to hack it and overwrite the branch namer...

**Comment by gabemeola** [comment]
@greysteil Thanks for the quick response!

Pardon my ruby inexperience, should I be able to pass `pr_message_footer` to `pull_request_creator` class. https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator.rb#L36

As far as Gitlab is concern this string can be included anywhere in the commit message

**Comment by greysteil** [comment]
Great to hear! Yep, we use that footer when passing through all the Dependabot-specific PR text from main Dependabot (commands, compatibility scores, etc.). It's perfect for your use case here 🙂
