### ISSUE TITLE
dependency name change

### ISSUE THREAD

**Issue by kanishka-work** [dependabot/dependabot-core#4073]
One of my js dependencies changed names on npm. Is there a way to add an annotation in dependabot config to specify this until I upgrade to the new package name? Also, is there some way to put the name change information in npm and have dependabot reference that information when deciding which dependencies to upgrade?

**Comment by jurre** [comment]
You'll have to change the dependency name in your package.json manually I think.

> Is there a way to add an annotation in dependabot config to specify this until I upgrade to the new package name?

What would you expect Dependabot to do with such a config?

> Also, is there some way to put the name change information in npm and have dependabot reference that information when deciding which dependencies to upgrade?

There's currently nothing like that that I'm aware of, no.

**Comment by kanishka-work** [comment]
> What would you expect Dependabot to do with such a config?

As you would expect, I would want dependabot to remove the old name, add the new package name, following the allowed version range in the old name, since the version numbers continue between the two names of the project.

**Comment by jurre** [comment]
If you already need to change the config file to be aware of this, wouldn't it be just as easy to just rename the dependency? You'll probably need to change a bunch of other things, like import statements etc when this happens anyway, so I don't think there's much value in teaching Dependabot to do this.
