### ISSUE TITLE
New dependabot command "remove"

### ISSUE THREAD

**Issue by Nokel81** [dependabot/dependabot-core#4076]
I would like a new dependabot command called "remove". This would tell dependabot to change a bump PR into a removal PR.

Sometimes I have noticed that uses of a dependency are removed but the removal of the dependency itself is sometimes forgotten about. My standard practice is to do a quick check (manually) if a dependency is being used before approving a bump PR. It would be very useful if I could do `@dependabot remove` if I notice that the repo no longer uses a specific dependency.

**Comment by mwaddell** [comment]
Duplicate of #2623

**Comment by Nokel81** [comment]
Ah thanks, closing this then.
