### ISSUE TITLE
Python 3.7.11 is not supported

### ISSUE THREAD

**Issue by yawhide** [dependabot/dependabot-core#4079]
Python 3.7.11 has been released for about a month now and it looks like dependabot doesnt support it yet.

**Package ecosystem**

poetry

**Package manager version**

1.1.6

**Language version**

python 3.7.11

**Manifest location and content prior to update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**

I expect python 3.7.11 to be supported but it is not

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**
```
Dependabot encountered the following error:

Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000055e3c80e4ff0 @requirements=[["=", #<Dependabot::Python::Version 3.7.11>]]>]]'.

Currently, the following Python versions are supported in Dependabot: 3.9.5, 3.9.4, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.10, 3.8.9, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.10, 3.7.9, 3.7.8, 3.7.7, 3.7.6, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.13, 3.6.12, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.10, 3.5.8, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3.
Learn more

```
Link to python https://www.python.org/downloads/release/python-3711/

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by yawhide** [comment]
thank you!

**Comment by yawhide** [comment]
@jurre how long will it take for dependabot to update so that I can get new depedabot alerts?

It looks like I am still getting the same error.

**Comment by michakinchen1988** [comment]
H have to down drade 16 bit then u update to 32 then download the 64 but kill your macefee

**Comment by jurre** [comment]
Releasing a new version now, expect to have it rolled out later today

**Comment by yawhide** [comment]
working! thanks again
