### ISSUE TITLE
JS: Peer dependencies

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#410]
_From @godban on February 12, 2018 8:8_

Hey guys,
we are using dependabot for some time, thx for nice service. But we are missing one feature. Dependabot doesn't updates peer dependencies and we need to do it manually each time.

<img width="400" src="https://user-images.githubusercontent.com/2461970/36086802-a65409ac-0fce-11e8-9e31-3329b5ac5f6e.png"/>

Original issue https://github.com/dependabot/dependabot-core/issues/257#issuecomment-364847296

_Copied from original issue: dependabot/feedback#86_

**Comment by kelly-tock** [comment]
was this closed because it was fixed?

**Comment by greysteil** [comment]
This was a long time ago! Dependabot won't create PRs to update peer dependency declarations at the moment because they need to be treated differently to other dependency requirements (you often want to keep them as low as possible, rather than raising them).

**Comment by AdamVig** [comment]
@greysteil I use Dependabot on two internal libraries (an ESLint configuration and a CommitLint configuration) and I want it to keep the peer dependencies (Husky, ESLint, CommitLint, etc.) up to the latest versions. Can you reopen this issue or is there a different issue I should watch?

**Comment by greysteil** [comment]
This issue is a bit of a mess, so I'd recommend opening a separate one.

As context, I believe the thinking behind closing this was that generally you don't want to bump peer dependencies in the same way as you bump other dependencies. The goal is normally to keep them as loose as possible (so that your users know that as many versions of the peer dependency are supported as possible). That makes adding support for them in Dependabot non-trivial, but it's not impossible.
