### ISSUE TITLE
Dependabot run on new PRs only for new library changes

### ISSUE THREAD

**Issue by thotakartheek004** [dependabot/dependabot-core#4102]
Hi all,

Use Case : I would like to identify insecure libraries/packages for newly introduced ones before merging to master. This would avoid time to fix and also avoids insecure libraries. 
Want to use this action on every PR approval

Not sure if its available, if yes, please share sample yaml

**Comment by jurre** [comment]
I think [dependency review](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review) should help here!

**Comment by asciimike** [comment]
Closing this as _jurre is correct: Dependency Review is the product you're looking for! Feel free to reopen if that doesn't work for you.
