### ISSUE TITLE
Open one PR for all dependencies in a repository

### ISSUE THREAD

**Issue by BillWagner** [dependabot/dependabot-core#4119]
In our samples repositories, [`dotnet/docs`](https://github.com/dotnet/docs) and [`dotnet/samples`](https://github.com/dotnet/samples), we will regularly see tens of PRs across all samples to update a single dependency. When one of our libraries changes, we have one PR per project, which is a lot of very similar and small PRs to merge.

We'd like to see one PR for each dependency across all projects in the repo. For example, when the test NuGet package updates, we'd see one PR that updates that package in all the projects where it's in use.

**Comment by jurre** [comment]
This is already tracked in #1190, so I'm going to close this issue out
