### ISSUE TITLE
Support for variables in `plugins` block

### ISSUE THREAD

**Issue by EdwarDDay** [dependabot/dependabot-core#4127]
I have thw following use case for the `gradle` ecosystem:
I tried to use a variable for the version in the `plugins` block of my `build.gradle.kts` file. Something like:
```kotlin
plugins {
    val kotlinVersion = "1.5.20"
    kotlin("android") version kotlinVersion
    kotlin("plugin.serialization") version kotlinVersion
}
```

But I didn't get any update to kotlin `1.5.21`, so it looks like dependabot only supports:
```kotlin
plugins {
    kotlin("android") version "1.5.20"
    kotlin("plugin.serialization") version "1.5.20"
}
```

It would be nice to update these plugins consistently with one PR.

**Comment by AleksanderBrzozowski** [comment]
When you use this:
```
plugins {
    kotlin("android") version "1.5.20"
    kotlin("plugin.serialization") version "1.5.20"
}
```
Would you get two separate PRs when there is new update to `1.5.21`?

**Comment by EdwarDDay** [comment]
Yes. That's what I want to prevent.

**Comment by AleksanderBrzozowski** [comment]
@EdwarDDay 
The funny thing is that it works but you need to surround kotlinVersion with double quotes `"` 😄 

Try this ;)
```kotlin
plugins {
    val kotlinVersion = "1.5.20"
    kotlin("android") version "$kotlinVersion"
    kotlin("plugin.serialization") version "$kotlinVersion"
}
```

**Comment by Flexicon** [comment]
Any updates on this one? It would be great if there was some way to support raw variables in plugin declarations without the need to interpolate them needlessly. 🙏 

---

**Does not work:**

```kotlin
plugins {
    val kotlinVersion = "1.7.0"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
}
```

**Works:**

```kotlin
plugins {
    val kotlinVersion = "1.7.0"
    kotlin("jvm") version "$kotlinVersion"
    kotlin("plugin.spring") version "$kotlinVersion"
}
```
