### ISSUE TITLE
Requirements.txt file is not identified in root path, only if it is inside a folder

### ISSUE THREAD

**Issue by brunojosafa** [dependabot/dependabot-core#4144]
I am using dependabot with Azure DevOps for a python project with using variables below:

      DIRECTORY_PATH: /
      PACKAGE_MANAGER: pip

The requirements.txt file is located in / root path but when executing the scan the following message is shown:
```
`/home/dependabot/.bundle/gems/dependabot-python-0.142.0/lib/dependabot/python/file_fetcher.rb:84:in `check_required_files_present': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/.bundle/gems/dependabot-python-0.142.0/lib/dependabot/python/file_fetcher.rb:53:in `fetch_files'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./generic-update-script.rb:154:in `<main>'`
```
It only works when I put the requirements.txt file inside a folder.

**Comment by saleh1shalabi** [comment]
Any new updates on this issue?

**Comment by deivid-rodriguez** [comment]
This seems specific to Azure DevOps? Maybe report it to https://github.com/tinglesoftware/dependabot-azure-devops, and if it turns out to be an issue here, we reopen this?

I think this simple case should work outside of Azure DevOps.

**Comment by saleh1shalabi** [comment]
@deivid-rodriguez I did now post a new issue there. hopefully this can be adressed soon. 
Thanks a lot!

**Comment by deivid-rodriguez** [comment]
Cool, let me close this issue then. If it turns out to be a problem on our side, please reopen this!

**Comment by deivid-rodriguez** [comment]
Just saw that you did not post this issue originally. Feel free to post a new issue then if it turns out to be something on our side 👍
