### ISSUE TITLE
Need to bump to a version of https://github.com/dependabot/gomodules-extracted/ that uses go 1.17 code

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4153]
It's awesome that `go` `1.17` landed in https://github.com/dependabot/dependabot-core/pull/4149/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R170-R171.

However, the underlying `gomodules-extracted` code also changed significantly during the upstream `1.17` release. 
So need to bump that to keep things in-sync... otherwise we may inadvertently get `1.16` behavior while thinking we are getting `1.17` behavior.

I opened a PR https://github.com/dependabot/gomodules-extracted/pull/12 to update that repo. Once that's merged and a new release cut, will need to update here.

This code only uses two functions from `gomodules-extracted`:
* `github.com/dependabot/gomodules-extracted/cmd/go/_internal_/modfetch.Lookup` ➡️  signature and behavior unchanged.
* `github.com/dependabot/gomodules-extracted/cmd/go/_internal_/modload.LoadModFile(context.Background())` ➡️  signature and behavior _did_ change, so will need some tweaking here as part of pulling it in. Also, should check [if `LoadModGraph` is a better fit](https://github.com/dependabot/gomodules-extracted/pull/12#discussion_r691813491).

**Comment by mctofu** [comment]
Thanks for the analysis! A PR to update `gomodules-extracted` and adapt to the changes is here: https://github.com/dependabot/dependabot-core/pull/4157.

**Comment by jeffwidman** [comment]
Closed by https://github.com/dependabot/dependabot-core/pull/4157 

See also https://github.com/dependabot/dependabot-core/pull/4434
