### ISSUE TITLE
Add a new test case for a `go.mod` generated using `go` `1.17`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4154]
The `go.mod` file format in `go` `1.17` has some significant differences from previous `go` versions.

See #4148 for details.

While the bug was fixed in #4149, I do wonder if there should be a new test case added?

Because now need to test the new `go 1.17` file syntax/behavior of `go.mod` file in addition to the backwards compatibility with the `go` `1.16` behavior.. 

A quick look at the fixtures in https://github.com/dependabot/dependabot-core/tree/main/go_modules/spec/fixtures/projects shows that many of them specify older `go` versions and so even when run using `go` `1.17`, it will run in compatibility mode and won't actually exercise the newer `1.17` behavior.

I don't think it's worth the time to duplicate all the fixtures as both 1.16 and 1.17, but having at least one or two 1.17 `go.mod` files for sanity might be a wise move.

**Comment by jeffwidman** [comment]
Actually, if I recall correctly, the new `1.17` behavior _only_ kicks in if the `go.mod` file explicitly specifies `go 1.17`... otherwise it runs in `1.16` (aka backwards-compatibility) mode.

So effectively there is currently no test coverage at all for 1.17 behavior.

**Comment by mctofu** [comment]
> So effectively there is currently no test coverage at all for 1.17 behavior.

Yup, that's true. I've added a simple test in https://github.com/dependabot/dependabot-core/pull/4159.

Are there any other go 1.17 cases that would be worth testing? I think it would make sense to start updating tests that still reference unsupported versions of go to a later one.

**Comment by jeffwidman** [comment]
> I think it would make sense to start updating tests that still reference unsupported versions of go to a later one.

What is your stated guarantee for support for older versions of `go`? If you don't have one, you'll probably want to add one now to start the clock ticking on dropping support for older use cases.

In general the `go` community does a good job of keeping up with latest versions, so supporting the last 3 versions probably makes sense.
