### ISSUE TITLE
Unknown error in maven dependencies scan

### ISSUE THREAD

**Issue by aleks-ivanov** [dependabot/dependabot-core#4168]
The error is `Property not found: slf4j.version`.

This is [the file](https://github.com/aleks-ivanov/pentaho-kettle/blob/master/pom.xml) that Dependabot is scanning.

This is [the log](https://github.com/dependabot/dependabot-core/files/7045652/dep-log.txt) of the scan.

Does anyone know what this error means, why it occurs and how to go about fixing it ?

**Comment by lseppala** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

**Comment by aleks-ivanov** [comment]
> It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

I will check🙂

**Comment by aleks-ivanov** [comment]
> It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

Yes, it still appears and in several dependency sources.

If you fork the repo as is now from my profile, you would be able to see the errors in the logs. (default branch has been switched to feature/test-dependabot)

**Comment by jakecoffman** [comment]
Sorry for no response for almost a year. I think #5924 and #5931 should have fixed this.

Your report was useful in recreating the issue, so thanks for filing this and linking to the code!

Feel free to reopen if you're still seeing the same problem.
