### ISSUE TITLE
cannot resolve npm dependency from custom dependency if the name contains 'github'

### ISSUE THREAD

**Issue by rethab** [dependabot/dependabot-core#4177]
In my package.json, I have a dependency on a package named "github-helper". I fetch this package from a custom registry. While Dependabot is able to update other dependencies from my custom registry, it fails for this one.

**Problem Analysis**
Consider the function `source_for` from https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb#L239:
```ruby
      def source_for(name, requirement, manifest_name)
        return git_source_for(requirement) if git_url?(requirement)

        resolved_url = lockfile_parser.lockfile_details(
          dependency_name: name,
          requirement: requirement,
          manifest_name: manifest_name
        )&.fetch("resolved", nil)

        return unless resolved_url
        return unless resolved_url.start_with?("http")
        return if resolved_url.match?(/(?<!pkg\.)github/)

        registry_source_for(resolved_url, name)
      end
```

This function is used to determine the source for dependencies. While it correctly resolves the URL for my package, the package name matches the regex on the fourth last line.

The effect of this is that this package doesn't have the source field set. 
Later on in the process, Dependabot just takes registry.npmjs.org as registry if there's no source.

In the end, I see this error under `Insights -> Dependency Graph -> Dependabot`:
> The following private package registry was used and caused the update to fail: registry.npmjs.org.

I guess this function was not really written for packages that contain the name github 😄 

----

**Package ecosystem**
npm

**Package manager version**
irrelevant

**Language version**
irrelevant

**Manifest location and content prior to update**
irrelevant

**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```
**Updated dependency**
irrelevant

**What you expected to see, versus what you actually saw**
Expected: Dependabot is able to update the dependency
Actual: Dependabot says it cannot fetch the dependency from registry.npmjs.org

**Native package manager behavior**
irrelevant

**Comment by jurre** [comment]
Thanks for the clear bug report, looks like an oversight on our end that we should be able to fix! Could you share a (minimal) manifest and lockfile that reproduce the error? It'll help a lot with debugging / fixing.

**Comment by rethab** [comment]
Hi @jurre this is an internal dependency fetched from a custom/internal registry. So I don't think I can give you an easy reproducer.

What is the manifest? package-lock.json or package.json? That'd be the same issue unfortunately..

However as I have dependabot running locally I can certainly help with testing any patches.

Or let me know if there's anything else I could do that would be helpful for you :)

**Comment by jurre** [comment]
>  this is an internal dependency fetched from a custom/internal registry. So I don't think I can give you an easy reproducer.

It sounds like any package in a non-default registry that contains `github` will trigger the error, so you should be able to strip out everything else to reproduce this. We can also try to set up something ourselves.

> What is the manifest? package-lock.json or package.json?

The manifest file refers to package.json and the lockfile to package-lock.json. The reason I was asking for a setup that reproduces the error is that it'll make it a lot quicker for us to debug and fix this, and we'll make sure to actually fix the error you're seeing, but we can try to reproduce the error ourselves using the info you provided and let you know when we've released a patch.

**Comment by rethab** [comment]
I have created a small package that reproduces the error. Please see the log from dependabot here: https://github.com/rethab/dependabot-reproducer/network/updates/190603225

**Comment by jurre** [comment]
Hey, it's been a while but I _think_ that I may have fixed this some time ago, is it still happening?

**Comment by rethab** [comment]
Hi @jurre thanks for getting back on this. This particular issue seems resolved, but unfortunately there are too many other issues so we can't use dependabot 😢
