### ISSUE TITLE
Azure Devops URLs with spaces in the project name do not work

### ISSUE THREAD

**Issue by biltongza** [dependabot/dependabot-core#4182]
My organization's Azure Devops project name has spaces in it. I am using the generic-update-script from https://github.com/dependabot/dependabot-script and specifying my PROJECT_PATH in the correct format of `organisation/project/_git/repo`. If I specify the project with spaces, I get the following exception:

```
usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://dev.azure.com/Organisation/Project With Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev"
	from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.85.0/lib/excon.rb:121:in `new'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.85.0/lib/excon.rb:250:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:220:in `block in get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:279:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:219:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:50:in `fetch_commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:73:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:65:in `files'

```

(Note that I can copy that URL to my browser and access it just fine)

If I encode the spaces as `%20` (for example `PROJECT_PATH=Organisation/Project%20With%20Spaces/_git/RepoName`, I just get a generic not found:

```
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:237:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:93:in `fetch_repo_contents_treeroot'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/clients/azure.rb:69:in `fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:309:in `_azure_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:208:in `_fetch_repo_contents_fully_specified'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:179:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.160.1/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.160.1/lib/dependabot/file_fetchers/base.rb:65:in `files'

```

Changing our project name is not feasible.

I understand the URL parser complaining about the URL not being valid with spaces, but I do expect escaping the spaces to work. I'm not able to see exactly what URL it is using to figure out why it is saying not found either.

**Comment by asciimike** [comment]
Taking a look quickly, I don't expect that the `name with spaces` would work in non-browser context (as the browser should escape it), but I am very surprised that we aren't encoding for you, and that an encoded version doesn't work on ADO (potentially it's getting double encoded?).

Looks like [the ADO docs don't prohibit spaces either](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops), so something we should support. I see a few mentions of `source.organization` (e.g. https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#L51) that can probably be escaped, and it's worth a shot on our end. I'll see about getting it prioritized in the near term.

**Comment by asciimike** [comment]
cc @chris5287 in case they have any thoughts on this (looks like they contributed the ADO pieces)

**Comment by biltongza** [comment]
Any updates on this?

**Comment by asciimike** [comment]
Unfortunately not, as we've been slammed with some other work. I think it's theoretically an easy fix, but looking at the way the azure client was implemented, it's a bit tedious. Looks like renovate did this: https://github.com/renovatebot/renovate/issues/3581 so I assume it will work.

**Comment by asciimike** [comment]
Hrm, it actually might be easy to sanitize the URLs https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#L221 and https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#L247. My weak brain can't understand how https://github.com/excon/excon/blob/5f384be869097fb5195ac086e8abb714e247b570/lib/excon/utils.rb#L103-L108 handles escaping, but it seems like it might not do spaces properly?

**Comment by xlgmokha** [comment]
Without source diving too deep, I think we want the equivalent of:

```irb
irb(main):001:0> require 'uri'
=> false
irb(main):002:0> x = "https://dev.azure.com/Organisation/Project With Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev"
irb(main):003:0> URI.encode(x)
(irb):3: warning: URI.escape is obsolete
=> "https://dev.azure.com/Organisation/Project%20With%20Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev"
```

To be handled either by the underlying http client (excon) or by dependabot before attempting to `URI.parse(url)` which doesn't gracefully handle spaces.

```irb
irb(main):004:0> URI.parse("https://dev.azure.com/Organisation/Project With Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev")
Traceback (most recent call last):
        7: from /home/mokha/.asdf/installs/ruby/2.7.1/bin/irb:23:in `<main>'
        6: from /home/mokha/.asdf/installs/ruby/2.7.1/bin/irb:23:in `load'
        5: from /home/mokha/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from /home/mokha/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
        2: from /home/mokha/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
        1: from /home/mokha/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
URI::InvalidURIError (bad URI(is not URI?): "https://dev.azure.com/Organisation/Project With Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev")
irb(main):005:0> URI.parse(URI.escape("https://dev.azure.com/Organisation/Project With Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev"))
(irb):5: warning: URI.escape is obsolete
=> #<URI::HTTPS https://dev.azure.com/Organisation/Project%20With%20Spaces/_apis/git/repositories/RepoName/stats/branches?name=dev>
```

However, `URI.escape` appears to have been replaced by [URI#escape](https://ruby-doc.org/stdlib-3.0.2/libdoc/uri/rdoc/URI/RFC2396_Parser.html#method-i-escape) or [URI#extract](https://ruby-doc.org/stdlib-3.0.2/libdoc/uri/rdoc/URI/RFC2396_Parser.html#method-i-extract) in Ruby 3.

**Comment by biltongza** [comment]
Sorry to nag, just wanted to follow up on this :)

**Comment by jeffwidman** [comment]
@AlekhyaYalla is this different than what you fixed in https://github.com/dependabot/dependabot-core/pull/5656?

I _think_ this refers to repo/project name, vs your PR fixed spaces in registry name, but since I don't use Azure DO I'm not confident that I've got the terminology correct...

**Comment by AlekhyaYalla** [comment]
yes, this is the same issue #5656. Is it still throwing the error?

**Comment by jeffwidman** [comment]
Thanks @AlekhyaYalla that's great news because it means it's fixed. 🎉 

This issue is from 2021, so before your fix shipped... I don't think it's still happening, we simply didn't realize it was sitting in our backlog til now.
