### ISSUE TITLE
Dependabot does not propose to upgrade dependency if the package of the dependency has changed

### ISSUE THREAD

**Issue by bmarty** [dependabot/dependabot-core#4195]
Sorry if it has been reported before.

I don't know if it is possible for dependabot to detect a change in the dependency location, but it should be nice if it was the case.

My dependency was:

` androidTestImplementation('com.schibsted.spain:barista:3.9.0')`

and dependabot did not create a pr on my project https://github.com/vector-im/element-android to upgrade to

`androidTestImplementation('com.adevinta.android:barista:4.0.0')`

(note the change in the version number, but also on the package name)

The compilation would be broken for sure, but at least the maintainer of the project would be aware of the upgrade.

It appears that the repository https://github.com/SchibstedSpain/Barista has been renamed to https://github.com/AdevintaSpain/Barista

**Comment by asciimike** [comment]
> I do know if it is possible for dependabot to detect a change in the dependency location, but it should be nice if it was the case.

Unfortunately I don't think we've got an easy way to support this (especially sketchy in cases where ownership has changed, which from our perspective we can't tell the difference between someone renaming their org and a different org forking a package), but I agree it would be nice if there were a way for package managers to suggest new packages that we could then know to consume (e.g. a deprecation notice with a forward).

**Comment by jeffwidman** [comment]
Yeah, the best we could probably do here is if the ecosystem supported the concept of a `deprecated` tag or similar marker. More and more ecosystems are starting to support this.

The maintainer could put up a final version with a deprecated marker and a pointer to the new version... and in Dependabot we could somehow notify you about the deprecated package... but that's about as far as we'd want to go, deprecations / moves happen for _all_ kinds of reasons so typically require a developer's judgement on how to handle.

So I'm going to close as we've got various tickets tracking deprecation--it's not something we handle today at all for any ecosystem.
