### ISSUE TITLE
Remote Container is not working

### ISSUE THREAD

**Issue by Marcono1234** [dependabot/dependabot-core#4200]
I am currently trying to use the Remote Containers setup for this repository (as [described in the README](https://github.com/dependabot/dependabot-core#debugging-with-visual-studio-code-and-docker)) for dd1fba76003434639209627676febc595787ba7c. However, I cannot get it to work:

- Running `bundle install` in the `omnibus` directory from the console of the remote container fails with:
    ```
    [!] There was an error while loading `dependabot-bundler.gemspec`: No such file or directory - helpers. Bundler cannot continue.
    ```
- Running the launch target "Debug dry run" does nothing after I select a repository to scan. The "Debug Output" tab of VS Code shows:
    ```
    bundler: command not found: rdebug-ide
    Install missing gem executables with `bundle install`
    ```
- Opening any Ruby file, waiting for the extensions to be activated (see progress indicator in bottom bar of VS Code) causes a bunch of warnings and errors:
    ![Warnings and errors](https://user-images.githubusercontent.com/11685886/132063381-ec590f11-c5a6-4088-9071-37acf6de72ad.png)

It appears this might be related to the way the Remote Container is created. Due to its usage of `Dockerfile.development` it seems to contain the files of this project twice:
- `${HOME}/dependabot-core`: Created and set up by the Dockerfile. Only contains a subset of all project files, manually mapped using Docker bind mounts [here](https://github.com/dependabot/dependabot-core/blob/dd1fba76003434639209627676febc595787ba7c/.devcontainer/devcontainer.json#L12-L84).
- `/workspaces/dependabot-core`: Contains the complete project. This directory seems to be created by the Remote Containers extension and is a copy of the project files from the host OS.

Note that I just wanted to try out something with Dependabot, and most likely won't be using the Remote Container again, so this is not blocking me.
However, I thought this GitHub issue might be useful in case others are experiencing this issue as well.
Feel free to close it.

## VS Code
```
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

Remote - Containers version v0.194.0

**Comment by jeffwidman** [comment]
I'm fairly sure this was resolved in https://github.com/dependabot/dependabot-core/pull/5086.

Note that the underlying gems used for debugging will change when the upgrade to Ruby 3.1 lands, see the commit message in this PR about removing `debase`: https://github.com/dependabot/dependabot-core/pull/5447.
