### ISSUE TITLE
Create a single PR for namespaced packages

### ISSUE THREAD

**Issue by Tallyb** [dependabot/dependabot-core#4203]
Create a single PR for all npm packages that are updated and belong to the same namespace. e.g. @angular, @storybook. 
It is common for namespace to be version aligned, so it can have ~10 packages updated (to the same version)at the same time. 
Why this is preferred? 
1. Reduce the number of PRs need to be merged
2. Less conflicts
3. Single packages update might fail the PR, while the whole namespace update can succeed

**Comment by jurre** [comment]
I think most of this is tracked in https://github.com/dependabot/dependabot-core/issues/1190 and https://github.com/dependabot/dependabot-core/issues/1296. I don't think we need to track this separately, it would likely be a config option for one of those feature requests, but I think it makes sense in that context 👍
