### ISSUE TITLE
dependabot shows wrong changelog for @js-joda/timezone package

### ISSUE THREAD

**Issue by chenrui333** [dependabot/dependabot-core#4208]
**Package ecosystem**
npm
**Package manager version**
yarn 1.22.x
**Language version**
node 14
**What you expected to see, versus what you actually saw**
link to the right changelog
**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

![image](https://user-images.githubusercontent.com/1580956/132387882-9a83e928-890b-46c2-ab61-f169b74e9d6e.png)

This should be the right changelog for the package:
https://github.com/js-joda/js-joda/blob/master/packages/timezone/CHANGELOG.md

![image](https://user-images.githubusercontent.com/1580956/132387930-bec3e74e-a55d-42d6-a23d-49b4ea988f30.png)

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

Looking at this, I'm not seeing the issue? Your screenshot only shows the commit diff, not image of a wrong changelog. So it's impossible to know what is wrong here.

I'm going to close as impossible to repro, but if you're still seeing this issue and able to provide more info please do so and we can reopen.
