### ISSUE TITLE
Support using pip-compile generated file header to choose Python version

### ISSUE THREAD

**Issue by honnix** [dependabot/dependabot-core#4216]
Since https://github.com/jazzband/pip-tools/releases/tag/6.2.0 pip-compile logs Python version (up to minor version) in the generated file, for example `This file is autogenerated by pip-compile with python 3.6`.

This information could be used to deduce which Python version to use when executing pip-compile before falling back to the default one. I think it has higher accuracy than trying to read `python_version` marker from generated file because using `python_version` marker in `*.in` file does not necessarily mean it gets compiled under a Python version that satisfies the marker.

**Comment by jeffwidman** [comment]
👋 Interesting idea. 

What do you think about moving more toward extracting the `python` version from `pyproject.toml`?

That seems to be the way a lot of tooling in the python ecosystem is moving, so would let us provide a solution that's more generic than just `pip-compile`...

**Comment by honnix** [comment]
> 👋 Interesting idea.
> 
> What do you think about moving more toward extracting the `python` version from `pyproject.toml`?
> 
> That seems to be the way a lot of tooling in the python ecosystem is moving, so is a solution that's more generic than `pip-compile`... and I _think_ we already do that today.

Yeah I think that makes sense. I'm not sure there is a standard way to define python version in pyproject.toml though. It might be OK to take the lower bound of `python_requires`.

**Comment by bmerry** [comment]
> What do you think about moving more toward extracting the python version from pyproject.toml?

That wouldn't solve the use case where there are multiple lockfiles each targeting a different Python version (see #4607).

**Comment by webknjaz** [comment]
The Python version is just one small part of the problem. How about the platform/arch factors? https://github.com/dependabot/dependabot-core/issues/4607

**Comment by bmerry** [comment]
@deivid-rodriguez thanks for implementing this. Do you know how to tell whether it's deployed to Github yet? I just tried it on a Github project, and it doesn't seem to have worked. It opened https://github.com/ska-sa/spead2/pull/291, where the top of the file indicates Python 3.12, but it's pulled in packages that the requirements.in indicates are only for use with <3.12.

**Comment by deivid-rodriguez** [comment]
It's deployed already. Can you open a separate issue? Handling markers may require extra tricks, not sure.
