### ISSUE TITLE
Path dependencies with .tar extension failed to parse

### ISSUE THREAD

**Issue by AlekhyaYalla** [dependabot/dependabot-core#4218]
The issue we are facing is while fetching path dependency file content [(here).](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb#:~:text=fetched_files%20%2B%3D-,path_dependencies,-(fetched_files)) While dependabot trying to fetch the path dependencies from package.json, it's failing to parse the  ([code here](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#:~:text=JSON.-,parse,-(tree_response.body).fetch)) while reading the contents of that file in the path. Please find the package.json's sample with path dependency below. 
`"aria-web-telemetry": {
      "version": "file:TestFolder/aria-web-telemetry.tar",`

I observed it's due to the tar extension of the file the parsing has been failed, and it is expected. dependabot is able to handle the .tgz extension successfully. ([here](https://github.com/dependabot/dependabot-core/blob/9311442dcb970af796cd9767580533c030d2b014/npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb#L126)). By handling, I mean, tgz files are fetching from the host and returned in dependency files(Although, that particular dependncy is getting ignored while parsing). Only for .tar files, it's failing to parse throwing the parse error.  

I wanted to understand, 
- is there any specific reason for not handling .tar files?  
- Can we handle the .tar files, in the same way, .tgz files are handled? 
- Is there any way to skip the .tar extension files or skip that path dependency and continue to the next dependency to avoid parsing errors?  
Please share your views, if I have to skip the .tar extension files until some workaround has been given for handling the tar files
@feelepxyz @jurre @greysteil

**Comment by greysteil** [comment]
> I wanted to understand, is there any specific reason for not handling .tar files?

I doubt it - looks like @feelepxyz made the original change, and was likely led by the npm docs, which mention `.tgz. but not `.tar`. If npm can handle `.tar` then I expect we should just add handling for it here.

(I'll leave anything more on this to @jurre, as I don't work on Dependabot anymore and he's likely to have a much more informed opinion!)

**Comment by lseppala** [comment]
I believe this has been fixed in your PR #4246. Thank you very much for your contribution!

Please feel free to re-open if I'm misunderstanding.
