### ISSUE TITLE
Dependabot cannot access git submodule from private repository

### ISSUE THREAD

**Issue by njgrisafi** [dependabot/dependabot-core#4230]
**Package ecosystem**
gitsubmodule

We have a git submodule that dependabot seems it's unable to access. The submodule is a private repository within our org.

Our dependabot runs are failing due with a 404 to `api.github.com`: 
```
  proxy | 2021/09/15 20:01:50 [050] * authenticating github api request
  proxy | 2021/09/15 20:01:50 [050] 404 https://api.github.com:443/repos/Org/private-repo/contents/setup.py?ref=3328d2434b4b98850096729ee44da909c727578b
```

Is there any way we can configure dependabot to skip this submodule? Or is there a way we can give dependabot access to this repository so it can continue?

**Comment by ewjoachim** [comment]
I believe the same thing happens when a project has a setup.cfg but not setup.py (see https://github.com/procrastinate-org/procrastinate ) 

Should I open a different issue or is it the same ?

**Comment by asciimike** [comment]
Can you grant Dependabot access to that repo via: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies?

**Comment by njgrisafi** [comment]
> Can you grant Dependabot access to that repo via: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies?

We followed the docs to grant dependabot access to the repo but still see this issue.

**Comment by asciimike** [comment]
@njgrisafi can you file a support request via github.com/support and provide info about the org and repo name so we can take a look? Feel free to reference this issue.

**Comment by ewjoachim** [comment]
I got my first Dependabot PR after I added an empty `setup.py` file to the project.

**Comment by jeffwidman** [comment]
I can see in the support ticket that @njgrisafi 's issue was a token authentication issue that's since been resolved and looks like @ewjoachim also has his problem solved, so I'm going to close this.

BTW, I have a hunch the empty `setup.py` is no longer necessary now that we support `pyproject.toml`...
