### ISSUE TITLE
Auto update node version on .nvmrc

### ISSUE THREAD

**Issue by neviaumi** [dependabot/dependabot-core#4234]
it possible to support .nvm like [renovatebot](https://docs.renovatebot.com/modules/manager/nvm/) do ? 

so that it can keep node LTS version as updated as possible by auto PR.

**Comment by brrygrdn** [comment]
Marking this as 'new-ecosystem' as managing the language version is kind of a cross-cutting concern that doesn't fit our current package-manager based updaters.

**Comment by neviaumi** [comment]
I think this already resolved. As you can use node-version file in Github action now.
