### ISSUE TITLE
clone submodules for go_modules file fetcher

### ISSUE THREAD

**Issue by aminjam** [dependabot/dependabot-core#4249]
We have a go_modules project that utilizes submodules and we use replace directives from the main modules to access other modules. When we run dependabot we see errors that couldn't read `go.mod` from the submodule.

```
updater | ERROR <job_206648398> go: code.cloudfoundry.org/garden@v0.0.0-20210608104724-fa3a10d59c82 (replaced by ../garden): reading ../garden/go.mod: open /home/dependabot/dependabot-updater/repo/src/garden/go.mod: no such file or directory
```

I was able to fix this issue locally and successfully run `./bin/dry-run.rb` after [changing this line](https://github.com/dependabot/dependabot-core/blob/cf1962332b5be22ad608874bb396029b7ac4ce01/common/lib/dependabot/file_fetchers/base.rb#L509) to be the following:

```
git clone --no-tags --recursive #{br_opt} #{source.url} #{path}
```

Is it possible to solve this issue in a different way? If not, would it be possible to add a new config so that repositories can clone submodules for go_modules projects?

**Comment by jakecoffman** [comment]
Submodule cloning was added in https://github.com/dependabot/dependabot-core/pull/5982 so this should be working now!

Let us know if you're seeing any issues with it.
