### ISSUE TITLE
Custom label

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#425]
_From @geonu on March 13, 2018 2:31_

We want adding our custom label by rule. like [this](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

_Copied from original issue: dependabot/feedback#102_

**Comment by bhathiya** [comment]
@greysteil A related question. Is it possible to replace a label? For example, if I want to replace `security` label with the `critical` label, is that possible?
