### ISSUE TITLE
[Feature Suggestion] Add command for changing default branch for watching issues

### ISSUE THREAD

**Issue by hron84** [dependabot/dependabot-core#4259]
It would be nice if dependabot could support repositories which has production code on (main/master) branch that is practically untouchable and also has a development branch which is periodically merged to default one. 

For this support, we need a command to tell Dependabot which branch should be used for monitoring/PR-ing.

**Comment by jurre** [comment]
I think you're looking for the [target branch](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#target-branch) configuration option

**Comment by hron84** [comment]
@jurre wow, i didn't know Dependabot now has a config file. I will take a look into it. However, I see package-ecosystem is needed to be defined. Dependabot currently detects my projects correctly and I would not touch this behavior, I'd only change the target branch, is it possible somehow?

**Comment by jurre** [comment]
> @jurre wow, i didn't know Dependabot now has a config file. I will take a look into it. However, I see package-ecosystem is needed to be defined. Dependabot currently detects my projects correctly and I would not touch this behavior, I'd only change the target branch, is it possible somehow?

Ah, I'm guessing you're only using security updates (for security vulnerabilities only) and not version updates (periodic updates for any version updates)? There's a little workaround for telling dependabot to not open version updates but still have some of the config apply to security updates, which is setting the [open-pull-request-limit](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit) to 0. I hope that helps

**Comment by hron84** [comment]
@jurre exactly, I use Dependabot only for security updates. He's doing an awesome job on tracking them. At this weekend I plan to look into the config and setup the config based on your guide.
