### ISSUE TITLE
Adding error message for azure client errors

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#4263]
Currently, in the `azure` client class, dependabot raises an appropriate error depending on the error response code. For e.g [here](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#L230), it raises `InternalServerError` when `response code == 500`
The problem, here, is just raising appropriate error isn't entirely helpful to detect the exact root cause of the failure. If we can also add the error message from the response to the raised error, then it would help analyse the exact issue of the failure. For example, `AzureDevops(ADO)` allows repos to specify policies like allowing commit only for identities having emails or having emails ending with a particular suffix like `@xyz.com,etc`. If now an identity having email other than what is allowed by such policies tries to create a source branch, it returns a 500 response code i.e `InternalServerError`. Without the error message, it would be difficult to know that the failure was caused due to this policy. Similarly, while PR creation in `azure` client, it passes `labels` ([code](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb#L181)) in the request body. If the label already does not exist, then it tries to create a new one and if the requesting identity does not have the permission to create a new label in ADO, then it returns a `403` response code. In this case too, it would be difficult to know that the error was caused due to missing label creation permissions from only the response code

@jurre @feelepxyz I wanted to understand if you guys have come across such issues reported by other ADO customers or for any other clients supported in dependabot and if you have plans on making these errors more descriptive with the response error message

**Comment by jeffwidman** [comment]
Azure Devops support is very much community supported. I'm sure all the point you raise could be improved. You've done a great job with PR's in the past, and we'd happily review/merge any new ones you open.

I'm going to close as this issue is honestly a bit spaghetti with intertwined issues, comments, and questions so isn't super actionable. But feel free to break them out as distinct issues that are more easily tracked / fixed by separate PR's.
