### ISSUE TITLE
Checking If Upgrade Was Successful 

### ISSUE THREAD

**Issue by rossgeesman** [dependabot/dependabot-core#4267]
My organization just completed the upgrade to the Github native Dependabot. For us, this involved migrating our secrets over for access to our internal registries. On one of our repos, the migration seems to have worked because we can see the new dependabot opening new PRs but on the other repos, there hasn't been any action so far. Is there another way to verify if the upgrade has worked?

**Comment by brrygrdn** [comment]
Hi @rossgeesman, sorry for the delay in replying.

The easiest way to verify if the upgrade has worked is to visit Insights > Dependency Graph page and then click on the Dependabot tab, the url is: `https://github.com/$ORG/$REPO/network/updates`

There you should see a list of the configured update configurations along with logs and errors from any recent runs.

If you have any further problems, please contact [GitHub Support](https://support.github.com/contact) and we can have a further look into this for you.
