### ISSUE TITLE
Support for non-standard Dockerfile names

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#428]
_From @bsedat on March 15, 2018 18:33_

We build a few flavors of a docker image from a single repository using multiple Dockerfiles, so it would be nice to be able to customize the name of the Dockerfile that should be updated.

_Copied from original issue: dependabot/feedback#105_

**Comment by nesl247** [comment]
@greysteil I believe you just implemented this right?

**Comment by greysteil** [comment]
I did indeed!
