### ISSUE TITLE
Bump library versions specified in `annotationProcessorPaths`

### ISSUE THREAD

**Issue by alexpdp7** [dependabot/dependabot-core#4282]
My Java Maven project uses Error Prone as described in:

https://errorprone.info/docs/installation

, but annotationProcessorPaths do not seem to receive updates.

**Comment by brrygrdn** [comment]
Hi @alexpdp7 would it be possible for you to give us some more information on the problem?

If you can refer to [our bug report template](https://github.com/dependabot/dependabot-core/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) it has some questions about the issue that might help us diagnose it.

If your project is private or you don't feel comfortable posting details on a public issue, please file an issue via [GitHub Support](https://support.github.com/contact) so we can discuss it.

**Comment by alexpdp7** [comment]
Sure, sorry- the thing that I'd like dependabot to target is:

https://github.com/alexpdp7/zqxjkcrud/blob/master/pom.xml#L114

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<build>
		<plugins>
			<plugin>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>com.google.errorprone</groupId>
							<artifactId>error_prone_core</artifactId>
							<version>2.9.0</version> <!------- this --!>
```

**Package ecosystem**
Java/Maven
**Package manager version**
all?
**Language version**
Java 11
**Manifest location and content prior to update**
/pom.xml https://github.com/alexpdp7/zqxjkcrud/blob/master/pom.xml
**dependabot.yml content**
https://github.com/alexpdp7/zqxjkcrud/blob/master/.github/dependabot.yml
**Updated dependency**
2.9.0 to 2.1.10
**What you expected to see, versus what you actually saw**
I wanted to get an update of the `annotationProcessorPaths` `version` element
**Native package manager behavior**
The package manager does not do automatic updates
**Images of the diff or a link to the PR, issue or logs**
N/A
**🕹 Bonus points: Smallest manifest that reproduces the issue**
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.pdp7</groupId>
	<artifactId>zqxjkcrud</artifactId>
	<version>master</version>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>11</source>
					<target>11</target>
					<fork>true</fork>
					<compilerArgs>
						<arg>-XDcompilePolicy=simple</arg>
						<arg>-Xplugin:ErrorProne</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
						<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
						<arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
						<arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
					</compilerArgs>
					<annotationProcessorPaths>
						<path>
							<groupId>com.google.errorprone</groupId>
							<artifactId>error_prone_core</artifactId>
							<version>2.9.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

, I guess.

**Comment by jeffwidman** [comment]
To clarify:
Are `annotationProcessorPaths` a feature native to Maven or are they a custom extension of some sort?

**Comment by alexpdp7** [comment]
Maven's, I believe: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths
