### ISSUE TITLE
Dependabot takes hours for a common dependency upgrade in a mono repo.

### ISSUE THREAD

**Issue by AlekhyaYalla** [dependabot/dependabot-core#4288]
**Issue:**
One of the issues we observed in dependency updates, is Dependabot taking a very huge amount of time in a mono repo for updating a dependency which is populated in more no of packages. In our case, we have a mono repo with yarn as a package manager and ~600 packages in it. _React_ is one of the commonly added dependency in ~350 packages in this repo (both dependency & devDependency). While we try to update _react_ using dependabot in this repo, it is taking nearly ~4hrs to finish the update task. The usual time by dependabot for doing an update of an irregular dependency in this repo is ~15-20min. The below are the observations from the investigation we did for common dependency.

**Observations:**
-	While generating the updated lock file content in this [method](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb#:~:text=def-,updated_yarn_lock,-(yarn_lock)), it is passing the dependencies to-be-updated along with the requirements (These are the package.jsons that has the dependency in it, either devDependency or dependency).
-	This [method ](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb)calls the respective package manager function (in our case, it is yarn) to update the dependencies. This [method ](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/helpers/lib/yarn/updater.js#:~:text=async%20function-,updateDependencyFiles,-(directory%2C%20dependencies)%20%7B)runs a loop to run the commands add & install in each and every package.json to autogenerate the lock file content. 
-	With our investigations, it is evident, that the time taken to update a dependency in the mono repo is directly proportional to the number of package.jsons that dependency presents in.

**Wanted to know:**
-	In the case of mono repo, all these packages.jsons would be updating to the same version and having a common lock file in the repo level, is it okay to run a single command in lock file level/repo level and autogenerate the content of it?
-	Are there anything else contributing to the longer runs in this area (apart from investigations)?
-	If this is a known issue, are there any plans/planned to accommodate this?
-	Is it possible to optimize these commands in Dependabot-core using  “yarn workspace” or any mono repo tool, that would help in running these commands efficiently at the repo level, instead of running them in each and every package level?

@jurre @hmarr @feelepxyz Please share your thoughts on this

**Comment by deivid-rodriguez** [comment]
I did not read this in detail, but since the linked PR was closed I guess this was fixed? Please reopen if not!
