### ISSUE TITLE
Enable open-pull-requests-limit to apply only for dependabot PR

### ISSUE THREAD

**Issue by alk-sramond** [dependabot/dependabot-core#4292]
Hi dependabot team !

As described by the title we would like to have a feature which enable us to apply the limit only to dependabot user PR.
On some repositories with lot of traffic it's not un-common to have a lot of PR open.

A flag would look like open-pull-requests-limit-apply-to-dependabot-only: true / false.

If we set the limit too low dependabot will never open a PR. Also it's not always simple to fix a limit some repositories have temporary increase in PR and some month with no traffic. 

Hope there was not already a similar suggestion ! Have a nice day !

**Comment by jurre** [comment]
That's how it works already! 😄  Have you ran into issues with it?
