### ISSUE TITLE
Dependabot keeps repeatedly notifying of exact same dependency update

### ISSUE THREAD

**Issue by lukehutch** [dependabot/dependabot-core#4298]
**Package ecosystem**
Maven
**Package manager version**
Unknown (latest version installed with GitHub Actions)
**Language version**
Java 7
**Manifest location and content prior to update**
N/A
**dependabot.yml content**
https://github.com/toolfactory/jvm-driver/blob/main/.github/dependabot.yml
**Updated dependency**
Multiple dependencies, including maven-javadoc-plugin 3.2.0 -> 3.3.1 (see screenshot below)
https://github.com/toolfactory/jvm-driver/pull/5
**What you expected to see, versus what you actually saw**
I expect Dependabot to only try to update a dependency once. But I get notifications repeatedly (41 times in the last 8 days, sometimes multiple times per hour). I don't know if this is a problem with Dependabot itself, or just the GitHub integration with it. Please advise.
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
See screenshot below
**🕹 Bonus points: Smallest manifest that reproduces the issue**
N/A

![image](https://user-images.githubusercontent.com/811305/136592953-347aabcb-68fb-47d6-b8bc-739527ed26f8.png)

**Comment by jurre** [comment]
It looks like you're getting emails from dependabot pushing a rebase commit, you can disable automatic rebasing as [documented here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#rebase-strategy). 

By default, Dependabot will try to keep the PR up to date, so if it detects a possible conflict, it will re-apply the update and (force) push that to the existing branch. 

Hope that helps

**Comment by lukehutch** [comment]
Thanks for the tip, that was probably the issue.
