### ISSUE TITLE
PRs and issues are getting polluted with long list of references.

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#431]
_From @IvanGoncharov on March 21, 2018 15:36_

--------------------
Every PR or issue which was mentioned under `Commits` or `Release notes` is getting polluted with a long list of references. For example here is my PR to `graphql-js`:
https://github.com/graphql/graphql-js/pull/1267
![image](https://user-images.githubusercontent.com/8336157/37719460-b96c7c14-2d2d-11e8-86c4-7127c8c7e90b.png)

-------------------------
**And this list will become longer with every new repository that starts to use your tool**.
No other dependency bots are causing such issues, e.g. greenkeeper.

_Copied from original issue: dependabot/feedback#108_

**Comment by bkeepers** [comment]
> Cc @bkeepers - I don't suppose this will affect anything you're doing with Probot Brandon? If so, and you've got any sway over that feature request tracker, it would be really nice to be able to tell GitHub not to create cross-references for some links.

Thanks for the feedback. We're currently advocating for giving apps more control over timeline events. I'll make sure your use case is documented. 

cc @wilhelmklopp @jmilas
