### ISSUE TITLE
dependabot input a rubocop alert

### ISSUE THREAD

**Issue by charoleizer** [dependabot/dependabot-core#4313]
When starts a new rails app, dependabot recommends me to put `gem "nokogiri", ">= 1.12.5"` on gemfile.

![image](https://user-images.githubusercontent.com/5617249/137166323-63afe9d5-564f-44e3-8c40-dee7984ee350.png)

When I did it, the rubocop find an offense, because of the double quotes `"`

```
Offenses:

Gemfile:38:5: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
gem "nokogiri", ">= 1.12.5"
    ^^^^^^^^^^
Gemfile:38:17: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
gem "nokogiri", ">= 1.12.5"
                ^^^^^^^^^^^

33 files inspected, 2 offenses detected, 2 offenses corrected
```

Idk if this issue is a bug, but for me in this case, it'll be good if dependabot recommends with simple quote like this: `gem 'nokogiri', '>= 1.12.5'`

**Comment by jurre** [comment]
The text shown there is just a suggestion on which version to update to, it does not take into account any style guide or rubocop config.

If you let dependabot open up a [security update](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates) it should respect the style already used in the repo.
