### ISSUE TITLE
Issue with gomod dependencies in gitlab subgroups

### ISSUE THREAD

**Issue by doriandekoning** [dependabot/dependabot-core#4315]
**Package ecosystem**
Gomod
**Package manager version**
Go 1.16
**Language version**
go 1.16
**Manifest location and content prior to update**
`/go.mod`
**dependabot.yml content**
```
version:  2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    auto-merge: false
```

**Updated dependency**
An internal dependency `[our.domain.name]/[group2]/[subgroup]/[something]`

**What you expected to see, versus what you actually saw**
I expect no errors, but all version checks of private gitlab modules in subgroups result in errors like this one:
```
[2021-10-08 11:25:05 +0000 tid=1b1d class=DependencyUpdateJob] ERROR: [group1]/[project]=>gomod] module [our.domain.name]/[group2]/[subgroup]/[package]/v2: git ls-remote -q origin in /home/dependabot/go/pkg/mod/cache/vcs/e24177e82ae344e15ee18cd6ef4e576cffa1fadbcee399cfefb2746ae0eecb0c: exit status 128:
	remote: The project you were looking for could not be found or you don't have permission to view it.
	fatal: repository 'https://[our.domain.name]/[group2]/[subgroup].git/' not found
```

It does resolve all packages that are not in a gitlab subgroup.

**Native package manager behavior**
It retrieves the package successfully. 
**Images of the diff or a link to the PR, issue or logs**

Seems to be related to this issue but this seems to have closed a year ago. https://github.com/dependabot/dependabot-core/issues/2618

I'm using dependebot for gitlab and I raised this issue there, it was pointed out that the issue probably lies somewhere in dependabot-core.

**🕹 Bonus points: Smallest manifest that reproduces the issue**

If someone can point me in the right direction that would be great, that way I could make an PR with a fix myself :)

**Comment by doriandekoning** [comment]
Thanks for your quick reply!

I understand that the resources are limited, if you can point me in the right direction I could ofcourse do some research myself! The concept of subgroups is fairly simple: instead of having `gitlab.com/group/project.git` (similar to github)  you can have `gitalb.com/group/subgroup/project.git` or even multiple levels. In essence its just a slightly different url. It works for ~8 projects which are not in subgroups and does not work for all ~10 dependencies which are in subgroups. Also when using the token provided to gitlab from the cli I can clone the project correctly. 

 
<details>
  <summary>By the way, I have this stacktrace: </summary>

```
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:249:in `handle_subprocess_error'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:178:in `run_go_get'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:97:in `block in update_files'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:194:in `block (2 levels) in in_repo_path'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/shared_helpers.rb:160:in `with_git_configured'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:193:in `block in in_repo_path'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/shared_helpers.rb:35:in `block in in_a_temporary_repo_directory'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/shared_helpers.rb:35:in `chdir'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/shared_helpers.rb:35:in `in_a_temporary_repo_directory'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:192:in `in_repo_path'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:84:in `update_files'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:80:in `updated_files'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater/go_mod_updater.rb:67:in `updated_go_mod_content'
  /home/dependabot/app/vendor/bundle/ruby/2.7.0/gems/dependabot-go_modules-0.162.1/lib/dependabot/go_modules/file_updater.rb:34:in `updated_dependency_files'
  /home/dependabot/app/app/services/dependabot/file_updater.rb:24:in `call'
  /home/dependabot/app/app/services/application_service.rb:7:in `call'
  /home/dependabot/app/app/services/dependabot/update_checker.rb:152:in `updated_files'
  /home/dependabot/app/app/services/dependabot/update_checker.rb:109:in `updated_dependency'
  /home/dependabot/app/app/services/dependabot/update_checker.rb:31:in `call'
  /home/dependabot/app/app/services/application_service.rb:7:in `call'
  /home/dependabot/app/app/services/dependabot/dependency_updater.rb:70:in `updated_dependencies'
  /home/dependabot/app/app/services/dependabot/dependency_updater.rb:37:in `block in dependency_list'
  /home/dependabot/app/app/services/dependabot/dependency_updater.rb:37:in `map'
  /home/dependabot/app/app/services/dependabot/dependency_updater.rb:37:in `dependency_list'
  /home/dependabot/app/app/services/dependabot/dependency_updater.rb:17:in `call'
  /home/dependabot/app/app/services/application_service.rb:7:in `call'
  /home/dependabot/app/app/services/dependabot/update_service.rb:100:in `all_updated_dependencies'
  /home/dependabot/app/app/services/dependabot/update_service.rb:93:in `all_vulnerable_dependencies'
  /home/dependabot/app/app/services/dependabot/update_service.rb:112:in `update_security_vulnerabilities'
  /home/dependabot/app/app/services/dependabot/update_service.rb:18:in `block in call'
  /home/dependabot/app/app/services/semaphore.rb:5:in `synchronize'
  /home/dependabot/app/app/services/semaphore.rb:5:in `synchronize'
  /home/dependabot/app/app/services/dependabot/update_service.rb:17:in `call'
  /home/dependabot/app/app/services/application_service.rb:7:in `call'
  /home/dependabot/app/app/jobs/dependency_update_job.rb:19:in `perform'
```

</details>


This stacktrace points me to this file: `https://github.com/dependabot/dependabot-core/blob/main/go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb` but unfortunately I don't have a lot of experience with ruby. I think some kind of path of which a git git repository should be cloned (or which should be `go get`-ed is determined wrong. Somewhere the last `/something` is cut off (or only the `host/something/something` is used). Do you have any clues where this might happen?

**Comment by jurre** [comment]
Looking at the stacktrace, the error is bubbled up from running `go get`. Could you share what your `go.mod` file looks like? We perform a `go get -d` with the `dependency_name@version`, maybe the `name` is off in the case of a subgroup?

**Comment by jerbob92** [comment]
@doriandekoning did you end up making that merge request/issue? I don't see it.

**Comment by doriandekoning** [comment]
@jerbob92  I did :) https://github.com/andrcuns/charts/pull/100 and https://github.com/andrcuns/charts/issues/99 
I think after this the repository got moved to gitlab so that's where it might have gotten lost https://gitlab.com/dependabot-gitlab/chart

**Comment by jerbob92** [comment]
@doriandekoning Thanks! Thought it was an issue in dependabot-gitlab itself, not the chart. This issue appeared to be something else for us :)

**Comment by ReyOrtiz** [comment]
Hello, was this issue solved? I'm facing the same problem:

`the project you were looking for could not be found or you don't have permission to view it. fatal: repository`

I've set GOPROXY,  and even GONOSUMDB and still doesn't work. I tried with GOPRIVATE=* too
