### ISSUE TITLE
GitLab NPM fails with private group packages

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#4318]
Hey,
thanks for this great product.

I want to use it on a private GitLab instance with the build in npm registry from GitLab.
So I forked the `dependabot/dependabot-script` repo and added the `npm` credentials.

Unfortunately, dependabot fails with a `PrivateSourceAuthenticationFailure`, but it is able to login. I dont know, why it fails, so I debugged it, with `EXCON_DEBUG=true`:

1. Dependabot is able to read the lockfile and its dependencies.
1. It fetches the first `dependency_url`, and requests all versions of this dependency. 
2. The request contains the correct `authentication` header and the login was successful.
2. The responding array contains all versions. 
2. Dependabot is able to `check_npm_response` and to parse the body.
3. It founds the latest version in the body, here `0.0.46`.
2. Dependabot tries to get the information about the latest version by requesting `/0.0.46`.
3. It fails, because the GitLab `npm` registry does not provide a `/version` endpoint, and forwards the request to `registry.npmjs.org`. This fails too with `404`, because this dependency is scoped and not available on central registry.
4. `@version_endpoint_working` is false. This should not be a problem, there is a check and a `RSpec` test to test it.
5. Dependabot fails although, but I dont know why: The login was successful, it founds the correct version. Only the `/version` is not working, but Dependabot supports this.

Do you have any idea, why Dependabot is not able to update the package?

The network debug log is attached.

**Package ecosystem**

npm
**Package manager version**

npm 6
**Language version**

node 14
**Dependabot credentials**
```
[ {
  "type" => "git_source", 
   "host"=>"github.com", 
   "username"=>"x-access-token", "password"=>"[MASKED]"
   }, {
     "type"=>"maven_repository", 
     "url"=>"https://gitlab.u.de/api/v4/groups/3091/-/packages/maven", 
     "password"=>"[MASKED]"
   }, { 
   "type"=>"npm_registry", 
   "registry"=>"gitlab.u.de/api/v4/packages/npm/", 
   "token"=>"[MASKED]"
   }, {
   "type"=>"git_source", 
   "host"=>"gitlab.u.de", 
   "username"=>"x-access-token", "password"=>"[MASKED]"
   }]
```
[dependabot_gitlabNPM.txt](https://github.com/dependabot/dependabot-core/files/7349682/dependabot_gitlabNPM.txt.txt)

**Comment by hfhbd** [comment]
After a long analysis: The lock file contains the package dependency url: `https://gitlab.u.de/api/v4/projects/6453/packages/npm/@GROUP/PROJECT/-/@GROUP/PROJECT-0.0.44.tgz`.
This [line](https://github.com/hfhbd/dependabot-core/blob/35032ea1459b48e93dea8c9d6b0c3f7417dce014/npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb#L294) removes the package id, so you need to provide 2 credentials:

```
[ {
  "type" => "git_source", 
   "host"=>"github.com", 
   "username"=>"x-access-token", "password"=>"[MASKED]"
   }, {
     "type"=>"maven_repository", 
     "url"=>"https://gitlab.u.de/api/v4/groups/3091/-/packages/maven", 
     "password"=>"[MASKED]"
   }, { 
   "type"=>"npm_registry", 
   "registry"=>"gitlab.u.de/api/v4/packages/npm/", 
   "token"=>"[MASKED]"
   }, {
   "type"=>"npm_registry", 
   "registry"=>"gitlab.u.de/api/v4/projects/6453/packages/npm/", 
   "token"=>"[MASKED]"
   }, {
   "type"=>"git_source", 
   "host"=>"gitlab.u.de", 
   "username"=>"x-access-token", "password"=>"[MASKED]"
   }]
```

**Comment by jeffwidman** [comment]
Is this still an issue?

GitLab support is basically community-driven, so we won't be able to track it down further unless you can isolate that it's a general `dependabot-core` issue and not something specific to GitLab.

**Comment by hfhbd** [comment]
I looked again and it should be updated: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/73639 I have to test it

**Comment by jeffwidman** [comment]
First, I misread this originally... I thought it was about opening MR's, didn't realize it was about supporting GitLab registries. I updated my comment ☝️ .

Thanks for tracking down the issue links. It looks like they now send abbreviated responses, which should include the versions... so fetching should work fine now. 

The remaining open issue https://gitlab.com/gitlab-org/gitlab/-/issues/344107 to send the full response I think just means we won't be able to fetch the package metadata when building the PR description. But once they do, Dependabot should just work™ . 

Given that there's nothing more that be done on the Dependabot side, I'm going to close. If you still see problems, then comment and we can re-open.
