### ISSUE TITLE
[Go] Dependabot removes dependencies that are being used

### ISSUE THREAD

**Issue by mx-psi** [dependabot/dependabot-core#4322]
**Package ecosystem** Go
**Package manager version** Go 1.16
**Language version** Go 1.16
**Manifest location and content prior to update** https://github.com/DataDog/datadog-agent/blob/add545d/go.mod
**dependabot.yml content** https://github.com/DataDog/datadog-agent/blob/add545d/.github/dependabot.yaml
**Updated dependency** github.com/open-policy-agent/opa from 0.31.0 to 0.33.1
**What you expected to see, versus what you actually saw**
Dependabot created DataDog/datadog-agent#9531 in which it removed a bunch of dependencies that are used by the Go module. I would expect to bump the open-policy-agent dependency and possibly others, but never remove used dependencies.
**Native package manager behavior**

<details>

<summary>
Diff when running 'go get github.com/open-policy-agent/opa@v0.33.1' and 'go mod tidy'
</summary>

```diff
diff --git a/go.mod b/go.mod
index d76642cf4..1c13d9ecc 100644
--- a/go.mod
+++ b/go.mod
@@ -94,7 +94,7 @@ require (
 	github.com/coreos/go-semver v0.3.0
 	github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a
 	github.com/davecgh/go-spew v1.1.1
-	github.com/dgraph-io/ristretto v0.0.3
+	github.com/dgraph-io/ristretto v0.1.0
 	github.com/docker/docker v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible
 	github.com/docker/go-connections v0.4.0
 	github.com/dustin/go-humanize v1.0.0
@@ -114,7 +114,6 @@ require (
 	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
 	github.com/golang/mock v1.6.0
 	github.com/golang/protobuf v1.5.2
-	github.com/golang/snappy v0.0.3 // indirect
 	github.com/google/go-cmp v0.5.6
 	github.com/google/gofuzz v1.2.0
 	github.com/google/gopacket v1.1.19
@@ -152,7 +151,7 @@ require (
 	github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d // indirect
 	github.com/olekukonko/tablewriter v0.0.5
 	github.com/oliveagle/jsonpath v0.0.0-20180606110733-2e52cf6e6852 // indirect
-	github.com/open-policy-agent/opa v0.31.0
+	github.com/open-policy-agent/opa v0.33.1
 	github.com/opencontainers/runtime-spec v1.0.3-0.20210326190908-1c3f411f0417
 	github.com/openshift/api v0.0.0-20190924102528-32369d4db2ad
 	github.com/patrickmn/go-cache v2.1.0+incompatible
@@ -190,7 +189,7 @@ require (
 	go.uber.org/zap v1.19.1
 	go4.org/intern v0.0.0-20210108033219-3eb7198706b2
 	golang.org/x/mobile v0.0.0-20201217150744-e6ae53a27f4f
-	golang.org/x/net v0.0.0-20210614182718-04defd469f4e
+	golang.org/x/net v0.0.0-20210825183410-e898025ed96a
 	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
 	golang.org/x/sys v0.0.0-20210923061019-b8560ed6a9b7
 	golang.org/x/text v0.3.7
diff --git a/go.sum b/go.sum
index 656d287f1..8a706a6f9 100644
Binary files a/go.sum and b/go.sum differ
```

</details>

**Images of the diff or a link to the PR, issue or logs**

PR linked above, specific commit is https://github.com/DataDog/datadog-agent/commit/ad68f769ecd080399a110b049a55a225f541fcb1

**Comment by mx-psi** [comment]
Not sure if related but this was generated during a run where Dependabot had the `Dependabot ran out of disk space during its update` error

**Comment by xlgmokha** [comment]
> Not sure if related but this was generated during a run where Dependabot had the `Dependabot ran out of disk space during its update` error

We've made some recent changes to improve this: https://github.com/dependabot/dependabot-core/pull/4356

**Comment by jurre** [comment]
@mx-psi I'm not sure I understand, it seems like the diff Dependabot generated is the same as for running `go get github.com/open-policy-agent/opa@v0.33.1` and `go mod tidy` manually? This is essentially exactly what Dependabot does, and the behavior seems consistent with the package manager? Even without running `go mod tidy`, go removes that `snappy` dependency when I run this update manually.

```
datadog-agent HEAD % g st
HEAD detached at 8088e0e37 # The ref dependabot ran against
nothing to commit, working tree clean
datadog-agent HEAD % go get github.com/open-policy-agent/opa@v0.33.1
go: downloading github.com/open-policy-agent/opa v0.33.1
go: downloading github.com/fsnotify/fsnotify v1.5.1
go: downloading github.com/peterh/liner v0.0.0-20170211195444-bf27d3ba8e1d
go: downloading github.com/bytecodealliance/wasmtime-go v0.30.0
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go get: upgraded github.com/dgraph-io/ristretto v0.0.3 => v0.1.0
go get: upgraded github.com/golang/snappy v0.0.3 => v0.0.4 # seems like this was upgraded, but is not in the `go.mod` file
go get: upgraded github.com/open-policy-agent/opa v0.31.0 => v0.33.1
datadog-agent HEAD % git diff
diff --git a/go.mod b/go.mod
index 5230bf499..e611aa928 100644
--- a/go.mod
+++ b/go.mod
@@ -94,7 +94,7 @@ require (
        github.com/coreos/go-semver v0.3.0
        github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a
        github.com/davecgh/go-spew v1.1.1
-       github.com/dgraph-io/ristretto v0.0.3
+       github.com/dgraph-io/ristretto v0.1.0
        github.com/docker/docker v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible
        github.com/docker/go-connections v0.4.0
        github.com/dustin/go-humanize v1.0.0
@@ -114,7 +114,6 @@ require (
        github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
        github.com/golang/mock v1.6.0
        github.com/golang/protobuf v1.5.2
-       github.com/golang/snappy v0.0.3 // indirect
        github.com/google/go-cmp v0.5.6
        github.com/google/gofuzz v1.2.0
        github.com/google/gopacket v1.1.19
@@ -152,7 +151,7 @@ require (
        github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d // indirect
        github.com/olekukonko/tablewriter v0.0.5
        github.com/oliveagle/jsonpath v0.0.0-20180606110733-2e52cf6e6852 // indirect
-       github.com/open-policy-agent/opa v0.31.0
+       github.com/open-policy-agent/opa v0.33.1
        github.com/opencontainers/runtime-spec v1.0.3-0.20210326190908-1c3f411f0417
        github.com/openshift/api v0.0.0-20190924102528-32369d4db2ad
        github.com/patrickmn/go-cache v2.1.0+incompatible
diff --git a/go.sum b/go.sum
index 92d317ed2..1f2c5c6ea 100644
Binary files a/go.sum and b/go.sum differ
```

We can see that the upgraded version of snappy is in the `go.sum` in both the diff Dependabot generates and when performed manually:

```diff
github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db/go.mod h1:/XxbfmMg8lxefKM7IXC3fBNl/7bRcc72aCRzEWrmP2Q=
github.com/golang/snappy v0.0.1/go.mod h1:/XxbfmMg8lxefKM7IXC3fBNl/7bRcc72aCRzEWrmP2Q=
github.com/golang/snappy v0.0.3 h1:fHPg5GQYlCeLIPB9BZqMVR5nR9A+IM5zcgeTdjMYmLA=
github.com/golang/snappy v0.0.3/go.mod h1:/XxbfmMg8lxefKM7IXC3fBNl/7bRcc72aCRzEWrmP2Q=
github.com/golang/snappy v0.0.4 h1:yAGX7huGHXlcLOEtBnF4w7FQwA26wojNCwOYAEhLjQM=
github.com/golang/snappy v0.0.4/go.mod h1:/XxbfmMg8lxefKM7IXC3fBNl/7bRcc72aCRzEWrmP2Q=
```

I believe this is [expected behavior:](https://golang.org/ref/mod#go-mod-file-go)

> The go.mod file includes an explicit require directive for each module that provides any package transitively imported by a package or test in the main module. (At go 1.16 and lower, an indirect dependency is included only if minimal version selection would otherwise select a different version.)

The packages that are imported by `datadog-agent` from the `open-policy-agent/opa` module are:

- github.com/open-policy-agent/opa/ast
- github.com/open-policy-agent/opa/rego
- github.com/open-policy-agent/opa/types

I _think_ that none of these (transitively) rely on snappy in that new version of the `opa` dependency, and that's why it gets pruned out. If that seems like a bug to you, we should raise it with the go mod maintainers I think, since Dependabot is just executing the package manager in this case.

**Comment by mx-psi** [comment]
@jurre since Dependabot does force pushes, looking at the latest diff will not show you the incorrect commit. 

The incorrect commit Dependabot made is  https://github.com/DataDog/datadog-agent/commit/ad68f769ecd080399a110b049a55a225f541fcb1 as you can see that commit removes `github.com/cilium/ebpf`, `github.com/docker/docker`, `github.com/h2non/filetype`, `github.com/opencontainers/runtime-spec`, `go.etcd.io/etcd/client/v2`, `k8s.io/kube-state-metrics/v2` and `k8s.io/klog`. These don't get removed when you do `go mod tidy`.

**Comment by jurre** [comment]
Ah, thanks I had missed the commit specific link! 

I am not able to reproduce it by running dependabot against that commits parent ref, and it looks like the rebases Dependabot performed also resolved the issue, so I'm tempted to assume it did have something to do with the disk space error.

I apologize for not being able to give a more conclusive answer.

If you do run into it again please let us know!

**Comment by mx-psi** [comment]
Alright, thanks for having a look, fingers crossed then! I will reopen the issue if something similar happens again
