### ISSUE TITLE
android-maps-utils opened by dependabot never complete CI

### ISSUE THREAD

**Issue by ColtonIdle** [dependabot/dependabot-core#4343]
Dependabot works great. It opens up a PR. Some basic CI runs for our team. Life is good.

Somehow... someway... every time the following dependency updates

https://github.com/googlemaps/android-maps-utils/

github/dependabot just break CI (i.e. it starts but never finishes)

I haven't dug into this issue at all yet, but wanted to see if anyone was experiencing the same thing.

**Comment by jeffwidman** [comment]
This sounds like a problem with your CI system and not `dependabot-core`.
