### ISSUE TITLE
upgrade NodeJS to new LTS.

### ISSUE THREAD

**Issue by salzig** [dependabot/dependabot-core#4359]
I would like to see usage of NodeJS LTS (v16) in the docker image, currently v14 (previous active LTS, now maintanance LTS) gets installed. 

Overview of releases and LTS state: https://nodejs.org/en/about/releases/

Is this something i should open a pull request for?

**Comment by shu-mutou** [comment]
We also need support for nodejs v16. Our dependency check is stopped now. :cry: 
Thanks in advance!

**Comment by shu-mutou** [comment]
Ref. #4531

**Comment by jeffwidman** [comment]
This was resolved in https://github.com/dependabot/dependabot-core/pull/4733
