### ISSUE TITLE
package-lock files with version 3 are not handled correctly by Dependabot

### ISSUE THREAD

**Issue by ferferga** [dependabot/dependabot-core#4361]
We recently upgraded to Node 16 and the lockfile version 3 of package-lock.json (the version without backwards-compatible features of the lockfile, see docs [here](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion), as we want to enforce always the most current features with the latest LTSs).

Lockfiles proposed by dependabot have massive changes, even when recreated or rebased

**Package ecosystem**
**npm**
**Package manager version**
**npm 8.1.0**
**Language version**
- Node 16

**Relevant PRs**

- https://github.com/jellyfin/jellyfin-vue/pull/1585
- https://github.com/jellyfin/jellyfin-vue/pull/1584
- https://github.com/jellyfin/jellyfin-vue/pull/1583
- https://github.com/jellyfin/jellyfin-vue/pull/1582
- https://github.com/jellyfin/jellyfin-vue/pull/1581
- https://github.com/jellyfin/jellyfin-vue/pull/1580
- https://github.com/jellyfin/jellyfin-vue/pull/1579
- https://github.com/jellyfin/jellyfin-vue/pull/1578
- https://github.com/jellyfin/jellyfin-vue/pull/1577

**Comment by cedric-anne** [comment]
I confirm the issue. Same problem on this PR: https://github.com/glpi-project/glpi/pull/10035 .

**Comment by jeffwidman** [comment]
Closing, as I think this was fixed by the bump to NPM 8:
* https://github.com/dependabot/dependabot-core/pull/4763

Please comment if I'm misreading/misunderstanding something, and we can re-open.

**Comment by cedric-anne** [comment]
Indeed, it seems to be OK now.
