### ISSUE TITLE
Make dependabot to a verified action

### ISSUE THREAD

**Issue by bowenjia** [dependabot/dependabot-core#4376]
Given some companies only allow to run verified actions in the business. Would you consider to make Dependabot as a Github verified action?

Thank you

**Comment by brrygrdn** [comment]
Hi @bowenjia, we currently do not support running Dependabot updates themselves via Actions on http://github.com, they use their own dedicated service which is a feature that your Organisation or Repository administrators can enable. 

See [GitHub Docs: Enabling and disabling Dependabot version updates](https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates) for more information.

We may support Dependabot via Actions in future and I've flagged internally that Dependabot is not currently a verified Actions creator.
