### ISSUE TITLE
Dependabot scores for private registries

### ISSUE THREAD

**Issue by leog** [dependabot/dependabot-core#4378]
First of all, thank you very much for your work. Dependabot is a very useful tool and I’m trying to configure it for an organization using private registry.

I was wondering if Dependabot scores apply for private registries, and if so, what is the process it follows to determine the score. I couldn’t really find specifics around the CI run and what it expects where to summarize results and get a score, and as I was thinking about using that with a private registry, I will need details to help the process.

**Comment by brrygrdn** [comment]
Hi @leog, thanks for using Dependabot!

We have a high-level explainer of Compatibility scores [here](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates#about-compatibility-scores)

The gist is that we use CI outcomes across _public_ repositories to calculate this value in the service. If I understand your issue correctly, you'd like to have a compatibility score for your internal libraries that would use the CI outcomes on your private repos, which our current implementation doesn't support unfortunately.
