### ISSUE TITLE
Adding a reviewer to a GitLab merge request is not working

### ISSUE THREAD

**Issue by ctosin** [dependabot/dependabot-core#4385]
The functionality below, which adds reviewers to a GitLab merge request, does not seem to be working properly.

https://github.com/dependabot/dependabot-core/blob/def2fca85bfe7c25d40569bb43b1d694fde4c89c/common/lib/dependabot/pull_request_creator/gitlab.rb#L156

It is trying to call a URL that does not exist, therefore a 404 is being returned.

Actually the problem seems to be in the GitLab dependency that Dependabot is using. This is the invalid URL: `/projects/#{url_encode project}/merge_requests/#{merge_request}/approvers`.

**Comment by jurre** [comment]
We rely on community contributions for GitLab support currently, I'd be happy to accept a PR that fixes this, but am wondering if this could be some sort of breaking change in the gitlab url format?

**Comment by andrcuns** [comment]
This is a know issue, the endpoint was removed starting from gitlab version 14.

Unfortunately https://github.com/narkoz/gitlab is taking extremely long to release a new version where the endpoint is updated in master.

Once it is released, I would prepare a PR that fixes it, I don't think dependabot-core project would be ok to build the gitlab gem from the master branch.

**Comment by floh96** [comment]
@andrcuns there was a new release of the gitlab gem. Is it now possible to fix this issue? thanks

**Comment by andrcuns** [comment]
I believe it is, yes. I might take a look when I have some free time.
