### ISSUE TITLE
Update Versions within Terragrunt Generate Configuration

### ISSUE THREAD

**Issue by Phylu** [dependabot/dependabot-core#4398]
This feature is part of the `terraform` ecosystem.

In my terraform repository, I have different folders for different terraform projects. The provider versions are generated by a terragrunt configuration for all these projects in order to have the same version for all of them.

The configuration is stored in the `terragrunt.hcl` file which should be picked up by dependabot. Here is an example configuration:

```
terraform_version_constraint  = ">= 1.0.10"
terragrunt_version_constraint = ">= 0.35.8"

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = "eu-central-1"
}
EOF
}

generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  required_version = ">= 1.0.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 3.64.2"
    }
  }
}
EOF
}
```

I would love Dependabot to update the following versions automatically:
* Terraform Version as defined by: `terraform_version_constraint`
* Terraform Version as defined by: `required_version` inside the generate `terraform` block
* Terragrunt Version as defined by: `terragrunt_version_constraint`
* Terraform Provider Version as defined by: `version` inside the generate `terraform > required_providers` block

**Comment by lorengordon** [comment]
@Phylu I use terragrunt also... How about writing the file yourself somewhere in the project and reading it with `file()`?

versions.tf:
```
terraform {
  required_version = ">= 1.0.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 3.64.2"
    }
  }
}
```

terragrunt.hcl:
```
terraform_version_constraint  = ">= 1.0.10"
terragrunt_version_constraint = ">= 0.35.8"

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = "eu-central-1"
}
EOF
}

generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = file("versions.tf")
}
```

**Comment by Phylu** [comment]
@lorengordon Great idea. I will try this for sure.

**Comment by Phylu** [comment]
I can confirm, that this works. The only problem is that `terraform validate` will complain if there are multiple version statements in the same directory, but I can work around this. Thanks a lot! :)

**Comment by niksauer** [comment]
@Phylu How did you work around it?

**Comment by Phylu** [comment]
The file structure looks as follows:

project_folder
– terragrunt.hcl
– versions.template.tf
– project_1
–– terragrunt.hcl
– project_2
–– terragrunt.hcl

In the parent terragrunt.hcl I have:
```
generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = file("versions.template.tf")
}
```

In the children terragrunt.hcl I have:
```
include {
  path = find_in_parent_folders()
}
```

Dependabot is configured to upgrade the versions on the `project_folder` level. When an update is done there, the terragrunt init will propagate it to all the children folders.

The main drawback is, that you can't have a provider in a child project that is not used in the others as they all inherit it from the same config.
