### ISSUE TITLE
Add support for sqlproj dependency files

### ISSUE THREAD

**Issue by roancath** [dependabot/dependabot-core#4424]
It would be nice to add support for sqlproj dependency files for dacpac (SQL server database) projects that are based on .NET. These projects also have package references similar to csproj files so I think it would make sense to include sqlproj files for nuget. Currently, it seems the nuget package type only support .(cs|vb|fs)proj files or a packages.config.

**Comment by pinkfloydx33** [comment]
There's a cross platform .NET (core) SDK for building sql projects/dacpacs. They use csproj files and can make use of dacpacs published to nuget feeds (as well as generating such packages). Dependabot works with these since they are just nuget packages and the normal package reference format.

https://github.com/rr-wfm/MSBuild.Sdk.SqlProj

**Comment by jhutchings1** [comment]
@jjcaine Can you have a look at this request? If the schema is the same internally, this seems like a small change to detect the other files. What do you think? 

https://github.com/dependabot/dependabot-core/blob/main/nuget/lib/dependabot/nuget/file_fetcher.rb#L17

**Comment by liesen** [comment]
Would it be possible to resurrect this idea?

I've done some experiments with the project discovery code: https://github.com/dependabot/dependabot-core/compare/main...liesen:dependabot-core:sqlproj. It appears that if MSBuild is able to resolve the Microsoft.Build.Sql SDK either using the NuGet-based resolver or using the .NET SDK resolver, then we can treat the project as any other .NET SDK project.

The SDK-style SQL projects are essentially a .csproj file but with a .sqlproj extension. In fact, it's possible to rename a .sqlproj file to .csproj and Dependabot will pick up the dependencies. I'd prefer to keep the .sqlproj extension.

**Comment by liesen** [comment]
https://github.com/liesen/dependabot-sqlproj/actions/runs/17649156718 is an example of a workflow that shows that renaming .sqlproj to .csproj make Dependabot pick up dependencies from the project.
