### ISSUE TITLE
Support reading advisories from private repository

### ISSUE THREAD

**Issue by cw-acroteau** [dependabot/dependabot-core#4437]
It would be nice if Dependabot could support reading advisories from a repository, located at https://github.com/{USERNAME_OR_ORGANIZATION}/{REPOSITORY}/security/advisories.

The goal of this feature would be to enable bigger organization to be able to publish advisories for their own private packages (which can/should not appear in the public DB), or for them to be able to publish advisories that are not already in the public Github Advisories DB (for example, advisories present in NVD but not at github.com/advisories).

Also, I tried finding where in the source code the advisories are fetched from Github Advisories, but I couldn't find it. How are the advisories fetched?

**Comment by brrygrdn** [comment]
>Also, I tried finding where in the source code the advisories are fetched from Github Advisories, but I couldn't find it. How are the advisories fetched?

Currently security advisories are injected into the [UpdaterCheckers](https://github.com/dependabot/dependabot-core/blob/b1f81765c32de788182ae204c802c3c83e081efd/common/lib/dependabot/update_checkers/base.rb#L15) classes as a data structure.

This is generally performed by the service or script running core, for example in our `dry-run` script [here](https://github.com/dependabot/dependabot-core/blob/906887b3b24bc2e86a29b8652123dc51317ff6a2/bin/dry-run.rb#L147)

This is an interesting feature request, we have lightly discussed moving Advisory fetching into core, although it isn't a pre-requisite of doing this.

**Comment by cw-acroteau** [comment]
> This is an interesting feature request, we have lightly discussed moving Advisory fetching into core, although it isn't a pre-requisite of doing this.

So I assume that for GitHub-native Dependabot this happens in their infrastructure (cosed-source)?

Of course, having an extensible way to fetch advisories would be great, as it could allow writing connectors for external sources, similar to how Dependency Track does it with Sonatype's OSSIndex, NVD and GitHub Advisories.

However, I think that allowing to read from repository-specific advisories in GitHub could be a good start, as I assume it would probably take less efforts than what is involved to move the Advisory fetching into the core, even ignoring the fact that this code might be closed source currently.

**Comment by jeffwidman** [comment]
> So I assume that for GitHub-native Dependabot this happens in their infrastructure (cosed-source)?

Yes, the advisory fetching pipeline is unfortunately closed source.

**Comment by jeffwidman** [comment]
👋 starting to triage our backlog and saw this.

This issue isn't actually related to `dependabot-core`--which is about creating PR's from alerts (and version updates), not generating the alerts themselves.

I realize the goal here is probably to ultimately create a security update PR from these private advisories, but there's several steps from "create innersource advisory" to "figure out if a repo's dep graph is vulnerable" to "trigger security PR to be created".

So the best place to start this discussion is over at: https://github.com/community/community/discussions/categories/code-security

Feel free to drop a breadcrumb link in this issue to that discussion.

**Comment by jeffwidman** [comment]
I should also add that if you have the vulnerability database, and you're willing to run `dependabot-core` yourself, then what's missing is massaging the advisory data into the format that `dependabot-core` expects for the vulnerable versions.

Here's an example command using the `dry-run.rb` script:
```
# fake a security advisory in a direct dep of a pub-based repo
SECURITY_ADVISORIES='[{"dependency-name":"buffer","patched-versions":[],"unaffected-versions":[],"affected-versions":["<= 2.0.0"]}]' bin/dry-run.rb pub dart-lang/pub-dev --dir "/app" --cache=files --dep="buffer"
```
