### ISSUE TITLE
Dependabot can't resolve your Terraform dependency files

### ISSUE THREAD

**Issue by HorizonNet** [dependabot/dependabot-core#4438]
We're using Dependabot for updating our Terraform providers automatically. To prevent version issues we're pinning the Terraform version to a specific version via `required_version`. Since last week Dependabot is not able to run `terraform init` since the Terraform version in the underlying runner seems to be pinned to a different version. Currently Dependabot fails with the following error

<img width="908" alt="Screen Shot 2021-11-22 at 11 35 45 AM" src="https://user-images.githubusercontent.com/1908271/142939295-0514e01d-3cfb-4c21-85dc-a51468dc5b2e.png">

I'm not a 100% sure, but it could be related to the recent changes introduced by #4405.

Before, Dependabot was able to update providers without a problem to the most recent version.

**Comment by jeffwidman** [comment]
I'm pretty sure this was resolved by this PR:
* https://github.com/dependabot/dependabot-core/pull/4464

**Comment by HorizonNet** [comment]
@jeffwidman Unfortunately not. The screenshot below is from today.

![Screen Shot 2022-08-26 at 9 52 24 AM](https://user-images.githubusercontent.com/1908271/186851833-48011462-2343-43f8-b1e5-960df6b7aec2.png)

**Comment by gtirloni** [comment]
This might help https://github.com/dependabot/dependabot-core/pull/5591

**Comment by jeffwidman** [comment]
I think this is fixed by https://github.com/dependabot/dependabot-core/pull/5591
