### ISSUE TITLE
Non-standard Dockerfile name

### ISSUE THREAD

**Issue by Agares** [dependabot/dependabot-core#4449]
In my repository, I have some Dockerfiles that are not called `Dockerfile`, but for example `migrations.Dockerfile`. I'm looking for a way to include those in dependabot, but it appears like only the directory in which the Dockerfiles reside can be specified (https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory), but dependabot will look only at `Dockerfile`, not other files.

**Comment by jurre** [comment]
Looking at [the code](https://github.com/dependabot/dependabot-core/blob/906887b3b24bc2e86a29b8652123dc51317ff6a2/docker/lib/dependabot/docker/file_fetcher.rb#L10), we should handle any file that includes `dockerfile`. [Here](https://github.com/dependabot/dependabot-core/blob/906887b3b24bc2e86a29b8652123dc51317ff6a2/docker/spec/dependabot/docker/file_fetcher_spec.rb#L116-L140) is a test with an example of a non-standard name that is handled as expected.


Have you tried this and are you getting any errors? If so, would you mind sharing those?

**Comment by Agares** [comment]
Ohh, this indeed seems to work! Thank you, I misunderstood that line previously and though it means it will look for files that contain `Dockerfile` in any sub-directory, it works fine with full directory paths. 
Would be cool to be able to specify wildcard paths, but that's I guess a different issue :)

**Comment by jurre** [comment]
Yeah I think that's tracked [here](https://github.com/dependabot/dependabot-core/issues/2178). Going to close this out for now 👍
