### ISSUE TITLE
Pull in changelogs for updated sub-dependencies

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#446]
Probably hidden away in a `details` tab.

**Comment by ralexander-phi** [comment]
I think this could be valuable. I know a few places that require engineers to review all changes to all dependencies (for security/quality reasons). Including links for transitive dependencies could help them avoid manually tracking the changes down.

How do folks like the look and feel of a comment layout like [this](https://github.com/ralexander-phi/mockup-transitive-dependencies-info/pull/2)? This PR shows a single direct dependency updated, but transitive dependencies updated, added, or deleted. (the links and text are copy/pasted, so consider it a mockup only).

This design hides all transitive dependencies updated inside a new `details` element, and further hides changelogs and other info behind further nested `details` elements. This keeps things quite compact until expanded.

For updated transitive dependencies, I think it makes sense to include the release notes, changelog, and commits as done for direct dependencies.

For newly added transitive dependencies I'm not sure about the best info to include. We could put the full commit history for the dependency, but that seems excessive. Instead I'm thinking we can link to changelog, releases page, and commit history and let the reviewer figure out what info they need to look at.

For deleted dependencies, I think listing them directly is sufficient.

I'm open to feedback and ideas.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
