### ISSUE TITLE
devcontainer used by VSCode based on devcontainer.json  docker image missing bundler/helpers directory

### ISSUE THREAD

**Issue by dwc0011** [dependabot/dependabot-core#4465]
The devcontainer used by VSCode based on devcontainer.json does not include helpers directory required by the dependabot-bundler.gemspec, due to the bundlers/helpers directory missing from .devcontainer/devcontainer.json

See error below:
```
[!] There was an error while loading `dependabot-bundler.gemspec`: No such file or directory - helpers. Bundler cannot continue.

 #  from /home/dependabot/dependabot-core/bundler/dependabot-bundler.gemspec:38
 #  -------------------------------------------
 #    prefix = "/" + File.basename(File.expand_path(__dir__)) + "/"
 >    Find.find("lib", "helpers") do |path|
 #      if ignores.any? { |i| File.fnmatch(i, prefix + path, File::FNM_DOTMATCH) }
 #  -------------------------------------------
```

**Comment by jurre** [comment]
Are you using the `bin/docker-dev-shell` script to start up the container?

I guess more generally, what steps are you taking to get to this error? I'd recommend going through the `docker-dev-shell` script if you're not already doing so, as it sets up a bunch of things that'll allow you to edit files on your host machine.

**Comment by dwc0011** [comment]
I was using it within Visual Studio Code and needed to rebuild the container at some point and that uses devcontainer.json  which does not have the bundler/helpers directory included.  I did use the docker-dev-shell script to run some tests but I needed to debug via VSCode.  I guess my question would be, should there be a difference in the the devcontainer.json and what's in the docker-dev-shell, I wouldn't think so, maybe the maintenance path diverged and devcontainer.json was missed along the way?

**Comment by dwc0011** [comment]
I have updated my title and comment to be more representative of the problem.

**Comment by jurre** [comment]
To be honest I don't use the `devcontainer.json` (or VSCode) and I don't know much about it, I will try to find someone on the team that does

**Comment by dwc0011** [comment]
I do have a fix, its a simple one and will put in a PR later today or tomorrow.  But it would be good for someone with experience to review. 

I definitely feel that working and debugging VSCode is a work in progress as things stand, I was able to get everything to work through trial and error, but it wasn't as simple as the README made it out to be and this was the first fix required to get the rest of it working.
