### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#449]
_From @jbreitbart on April 8, 2018 12:14_

Do you have any plans to support golang with dependabot? I know it is probably not the ideal time with dep / vgo thing going around, but maybe once this is sorted out?

_Copied from original issue: dependabot/feedback#125_

**Comment by will-swu** [comment]
waiting for go before we adopt this service.

**Comment by greysteil** [comment]
@will-swu - using Dep or something else?

**Comment by will-swu** [comment]
Yep, we use Dep.

**Comment by key** [comment]
We use Dep too. Waiting for golang support :)

**Comment by fubarhouse** [comment]
I use dep & vgo, and I'd be interested in seeing support here.

**Comment by hairyhenderson** [comment]
Using `dep` over here too, would love to see support!

**Comment by greysteil** [comment]
PR to add Go support (just a placeholder) is [here](https://github.com/dependabot/dependabot-core/pull/592). Any comments / advice appreciated.

**Comment by greysteil** [comment]
Dependabot now supports `dep`! 🎉 

https://dependabot.com/blog/go-support

Would love your feedback. (And I appreciate updating to `dep` v0.5.0 on the day it comes out, and before it's on homebrew, is a pain - sorry!)

I'm going to close this because I'm feeling triumphant, but that doesn't mean I've forgotten about vgo.

**Comment by fubarhouse** [comment]
@greysteil,

I've noticed my first PR only changes my lock file - the toml file remains out of sync. This is not what I would expect - I don't know if this is by design, but I feel I should let you know.

See https://github.com/fubarhouse/drubuild/pull/45 for the full details.

**Comment by greysteil** [comment]
Thanks Karl - that's helpful feedback.

At the moment Dependabot is treating all Go code as if it was a library, so doesn't want to change the `Gopkg.toml` unless it has to (and if it does, does so by widening the range). I *think* that's the right behaviour for libraries (let me know if I'm wrong), but it's definitely not the right behaviour for apps.

My plan is to make the above configurable, because I don't *think* there's any way that Dependabot can tell whether it's working on an application or a library (again, correct me if I'm wrong).

**Comment by fubarhouse** [comment]
Well, by finding package `main`, you can identify an application from a library.

I think that's okay - but if it was configurable that would definitely fit the bill for ever scenario - especially when vgo/module support eventually comes alone. 👍 

Good work!

**Comment by greysteil** [comment]
Ah, good point - I can tell if it's a library just by checking for the presence of a `main.go`! I'll get that changed now. 🎉

**Comment by fubarhouse** [comment]
You may also come across outliers where `package main` is contained in other files, such as `app.go`.

This however is considerably unlikely.

**Comment by greysteil** [comment]
Good to know. [This change](https://github.com/dependabot/dependabot-core/commit/beb14f33a84cbf6677ef33e42d4123a79cb8f025) is deploying now and will give more intuitive behaviour. 🎉
