### ISSUE TITLE
Use "fix" instead of "chore" when upgrading production dependencies

### ISSUE THREAD

**Issue by gnarea** [dependabot/dependabot-core#4497]
If you're using Conventional Commits/Semantic Releases, you'd want Dependabot PRs for your production dependencies to use the type `fix` so that a new release can be triggered. `chore` won't trigger a new release, so it's only suitable for development dependencies.

**Comment by jurre** [comment]
By default dependabot will look at the commit history and figure out what prefix folks use, but you can tell it which one to use using the config file as well: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message

Lmk if that doesn't resolve your issue, but I think it should so I'll close this out 😄

**Comment by gnarea** [comment]
Thanks @jurre! Unfortunately, that's not working for me.

Here's an example where I set `commit-message` in the Dependabot config: https://github.com/relaycorp/awala-gateway-desktop/commit/bd5746bc4fad26d1f02a0334cd1cbe120cd375cc

And here's a PR Dependabot created afterwards: https://github.com/relaycorp/awala-gateway-desktop/pull/961

You'll notice that the new PR is still using `chore`.

The weird thing is that Dependabot is certainly detecting prod vs dev dependencies, because it's marking the scope as either `deps` or `deps-dev`.

**Comment by jurre** [comment]
Looks like the new config had not been picked up by Dependabot, most likely due to yesterdays AWS outage :( I have resynchronized them and I can see they're now set correctly. Lmk if it works on new commits!

**Comment by gnarea** [comment]
Thanks @jurre! Everything works now as expected 🚀
