### ISSUE TITLE
Add support to update .nvmrc

### ISSUE THREAD

**Issue by anatoli-klamer** [dependabot/dependabot-core#4507]
To use dependabot to update Dockerfile like:
```
FROM node:16.13.1
```
we also need to be able to update .[nvmrc](https://github.com/nvm-sh/nvm) automatically (and preferably in the same MR) 
So developers can locally use the same node version as we use in production

**Comment by jurre** [comment]
Yeah updating language versions outside of a Dockerfile is not something we have a good story for right now, it would be cool to support but we don't have any immediate plans for it.

**Comment by anatoli-klamer** [comment]
Maybe I can help... any thoughts how can it be done? Some custom rules, plugins?

**Comment by jurre** [comment]
We're not really in a position to accept such contributions right now, more context [here](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems)

**Comment by jeffwidman** [comment]
I'm going to close this as partially a dupe of https://github.com/dependabot/dependabot-core/issues/4234 and partially "wontfix".

Managing `.nvmrc` versions might be doable, see #4234 for that. But managing it in conjunction with another ecosystem update such as a dockerfile update just isn't something that I see being very feasible without a _ton_ of broken edge cases... to the point that I'd question if we're adding value or just confusion.
