### ISSUE TITLE
Python: Use pip-compile to determine latest resolvable version (unless using Pipfile)

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#451]
_From @dschep on April 11, 2018 17:26_

I have `flake8` and `pycodestyle` in my `requirements.txt` (generated from a `requirements.in` containing `flake8` but not `pycodestyle` using `pip-compile`)

Dependabot creates a PR (dschep/dependabot-test#1) for `pycodestyle==2.4.0` but flake8 depends on `pycodestyle >= 2.3.0, < 2.4.0`, so flake8 doesn't work after installing the new requirements.

Is there anyway for dependabot to guarantee the consistency of packages that depend on each other? And what is the recommended work around for this?

_Copied from original issue: dependabot/feedback#127_

**Comment by dschep** [comment]
Awesome. Thank you!
