### ISSUE TITLE
Terraform PRs titles no longer container resource name

### ISSUE THREAD

**Issue by larryclaman** [dependabot/dependabot-core#4519]
I am observing this on GitHub, but I think the bug is coming from dependabot core.  It may be related to #4440 as this issue just started in the last week, and that's right around when this patch to terraform functionality was applied.

**Package ecosystem**
Terraform

**What you expected to see, versus what you actually saw**
Up until a week ago, the PRs created by dependabot for my terraform manifests had fully descriptive names, eg `Bump hashicorp/kubernetes from 2.3.2 to 2.7.0`

In the last week, the name of the resource provider appears to have been dropped from the PR name, and my PRs are now titled like `Bump from 2.68.0 to 2.88.1`, which is clearly not very useful when trying to review the PR list.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jurre** [comment]
Thanks for reporting this @larryclaman, we're tracking it internally as well. It _might_ have snuck in with https://github.com/dependabot/dependabot-core/pull/4440 or one of the terraform updates but needs further investigation.

**Comment by dwc0011** [comment]
> I am observing this on GitHub, but I think the bug is coming from dependabot core. It may be related to #4440 as this issue just started in the last week, and that's right around when this patch to terraform functionality was applied.


I will test this again, this should not of been affected and was working in my tests cases prior to merging.  Do you have a sample snippet so I can test this exact case.

Thanks

**Comment by dwc0011** [comment]
> Thanks for reporting this @larryclaman, we're tracking it internally as well. It _might_ have snuck in with #4440 or one of the terraform updates but needs further investigation.

Found the issue, small change and submitted a PR with just this fix.

**Comment by larryclaman** [comment]
@dwc0011 @jurre Thanks for fixing this so fast! Do you have a sense of how quickly this will make it to github.com?  Reason I ask is, as of this morning, Dependabot on GitHub is still truncating this information.

**Comment by dwc0011** [comment]
> @dwc0011 @jurre Thanks for fixing this so fast! Do you have a sense of how quickly this will make it to github.com? Reason I ask is, as of this morning, Dependabot on GitHub is still truncating this information.

The code is merged into master but there has not been a tag made yet.  I am not sure when that will happen and will defer to @jurre for that.

**Comment by jurre** [comment]
Should be in the next release (https://github.com/dependabot/dependabot-core/pull/4546), I'll roll it out tomorrow, thanks again for the fix @dwc0011
