### ISSUE TITLE
Finding wrong changelog for crate in subdirectory

### ISSUE THREAD

**Issue by nipunn1313** [dependabot/dependabot-core#4544]
**Package ecosystem**
cargo
**Package manager version**
N/A
**Language version**
N/A
**Manifest location and content prior to update**
N/A
**dependabot.yml content**
N/A
**Updated dependency**
An example is `deadpool-postgres`
Which has its changelog in https://github.com/bikeshedder/deadpool/blob/master/postgres/CHANGELOG.md
A dependabot pull finds this changelog instead https://github.com/bikeshedder/deadpool/blob/master/CHANGELOG.md

**Comment by cklim4405** [comment]
> **Package ecosystem**
> cargo
> **Package manager version**
> N/A
> **Language version**
> N/A
> **Manifest location and content prior to update**
> N/A
> **dependabot.yml content**
> N/A
> **Updated dependency**
> An example is `deadpool-postgres`
> Which has its changelog in https://github.com/bikeshedder/deadpool/blob/master/postgres/CHANGELOG.md
> A dependabot pull finds this changelog instead https://github.com/bikeshedder/deadpool/blob/master/CHANGELOG.md

**Comment by abdulapopoola** [comment]
Closing as stale
