### ISSUE TITLE
APIs for dependabot config

### ISSUE THREAD

**Issue by laurentsimon** [dependabot/dependabot-core#4555]
Hi

I doubt this is the right place to ask but I could not find a better place.
There seems to be a dependabot service on GitHub with several options available.

Are there GitHub APIs to retrieve the configuration settings, such as whether alerts and security updates are turned on - https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies and https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates

In addition, are you going to merge all these settings into the dependabot.yml config file? It's confusing to have dependabot scattered in different places (a config file and in GitHub settings). I understand they may be different services in the backend, but the marketing around all these being "dependabot" makes it really confusing.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

I empathize with the confusion here.

AFAIK, we don't currently have API's to retrieve the configuration settings. 

The UI generally controls settings for the security alerts and the `dependabot.yml` config file controls settings for version updates. We realize it's confusing, and there are efforts to improve that.
