### ISSUE TITLE
[question] ignore package names or wildcards

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#457]
_From @christopherthielen on April 19, 2018 16:42_

Some packages I want to keep at a specific version. I'd rather not receive PRs for these packages. Is it currently possible?

_Copied from original issue: dependabot/feedback#133_

**Comment by lorengordon** [comment]
@greysteil 	got a follow up to this one... we have a few projects where we still support Python 2.6, but many packages have deprecated support. We'll often have two lines in a requirements file for this, one that pins the 2.6 version and one that pins the latest version for everything else. For example:

```
distro==1.0.4;python_version<="2.6"  # pyup: ==1.0.4
distro==1.3.0;python_version>="2.7"
```

We've been using pyup, which handles exceptions using comments in the file, as you can see. When telling dependabot to ignore the dependency when a PR is opened on the first line, dependabot comments that `distro` will be ignored. Does that mean even the second line will never be updated also?

**Comment by greysteil** [comment]
Unfortunately yes - that's the case.

I don't think I have a good answer for this one with Dependabot either - I took a look at a repo with the above setup last week whilst debugging an error and realised the above was going to cause issues. Basically, Dependabot can't handle the idea that you depend on more than one version of a given package at once, which is what the above looks like to it.

I think one option here might be for Dependabot to ignore dependencies with a `python_version<=` marker - I can't imagine it should ever be updating those. Can you think of any case where that wouldn't work?

**Comment by lorengordon** [comment]
> I think one option here might be for Dependabot to ignore dependencies with a python_version<= marker - I can't imagine it should ever be updating those. Can you think of any case where that wouldn't work?

Yes, in our case in the example above we would *want* Dependabot to update the second listed `distro` dep.

I can think of a couple approaches...

1. Do something similar to pyup (and pylint, shellcheck, flake8, etc) and parse a comment-spec to determine whether to ignore a line.
2. Include the pin when a user comments to ignore a dependency. E.g. `distro==1.0.4` in this case...

**Comment by greysteil** [comment]
Sorry, I don't think I was clear - I meant ignore **only in the case where the marker uses `<` or `<=`**. Would that work?

**Comment by lorengordon** [comment]
Ohohohoh! My reading comprehension is low! Sorry! Need to pay better attn to the details.

So yes, that would work in this case also. =D

**Comment by greysteil** [comment]
Awesome - implemented in https://github.com/dependabot/dependabot-core/commit/f75085e508dc96d6657bdbec5c2e6d87b3907a7d, which is deploying now.

**Comment by lorengordon** [comment]
Very nice! Thanks!
