### ISSUE TITLE
Status check to prevent merging during rebases

### ISSUE THREAD

**Issue by xt0rted** [dependabot/dependabot-core#4570]
When using an [auto-merge workflow](https://github.com/xt0rted/markdownlint-problem-matcher/blob/7f637e254b41501e05512641ae636b8ad757da2d/.github/workflows/dependabot-auto-merge.yml) there's plenty of times where a PR starts to rebase but since there's no code conflicts auto-merge or even manual merge is still possible. Having a dependabot status check that could change and block the merge would be very helpful.

Here's multiple examples of what I'm seeing:

- https://github.com/xt0rted/markdownlint-problem-matcher/pull/350
- https://github.com/xt0rted/markdownlint-problem-matcher/pull/354
- https://github.com/xt0rted/markdownlint-problem-matcher/pull/355

**Comment by markcellus** [comment]
There's a setting in branch protection rules that let you "Require branches to be up to date before merging". Does that work for you? That should prevent the PRs from being merged until they're rebased.

**Comment by xt0rted** [comment]
That would apply to every PR then, which makes it harder to work on everything else.

**Comment by markcellus** [comment]
You can enable branch protections to just dependabot PRs.

**Comment by xt0rted** [comment]
How do you enable that? I've only been able to turn them on for all PRs.

**Comment by markcellus** [comment]
Dependabot opens PRs on branches that begin with `dependabot/npm_and_yarn` so you'll have to add a new branch protection rule that targets those branches.

1. Go to Settings page on repo
2. Click "Branches" on left sidebar
3. Under "Branch Protection Rules", click "Add Rule"
4. Under "Branch Name pattern" type in `dependabot/npm_and_yarn/*`
5. Check "Require status checks to pass before merging "
5. Check "Require branches to be up to date before merging"

Hope this helps!

**Comment by xt0rted** [comment]
Thanks for the info. I tested something similar and both setups prevented dependabot from being able to rebase.

The first setup I tried was similar to what you describe and I got a comment on the issue from dependabot saying it couldn't rebase (I don't recall the exact settings).

>Dependabot attempted to update this pull request, but because the branch `dependabot/github_actions/softprops/action-gh-release-1` is protected it was unable to do so.

With the setup you described dependabot doesn't rebase at all and when I manually trigger it with `@dependabot rebase` the issue is updated saying it's being rebased but it never happens. When I remove the branch protection rule it starts to rebase again.

**Comment by markcellus** [comment]
Sounds like something may be wrong with your setup. You might want to open an issue describing your situation leading to your error. I've been using the same setup on my repos for quite some time now and haven't had that issue.

**Comment by mwaddell** [comment]
This issue could also be solved by having dependabot create PRs in "Draft" and that rebasing/recreating a PR sets it back to "Draft" (e.g. task #1963 and #2379)

**Comment by xt0rted** [comment]
@mwaddell I like that idea but it won't work in all scenarios. Draft PRs are locked behind paid teams and enterprise plans if the repo is private (which a lot of mine are). I've complained to support about this ever since they removed them from pro accounts but there's no plan to let all paying users use them sadly.

**Comment by mwaddell** [comment]
@xt0rted I think there may be something wrong with your branch protection setup then.  We use the following setup and it prevents auto-merge once a rebase is started because it requires a review and dismisses the review when a rebase happens:

![image](https://user-images.githubusercontent.com/750244/151708096-3e2368eb-315e-4efa-a716-bd96a5394f07.png)

I've never had a problem with rebase happening when using branch protection since branch protection only impacts whether or not something can be merged.

**Comment by jeffwidman** [comment]
Closing because this should work fine using the branch protection rules as described ☝️. If for some reason it's not, please include some screenshots of your settings and we can re-open.

@mwaddell @markcellus thank you for chiming in to explain/document it.
