### ISSUE TITLE
configuration option for submodules to edit existing PRs rather than making new ones

### ISSUE THREAD

**Issue by JasonGross** [dependabot/dependabot-core#4674]
dependabot is very noisy when we're slow to merge PRs.  Please make it possible to tell dependabot to edit existing PRs for a given submodules, updating them to the latest commit, rather than closing the existing PR and making a new one.  This would probably require changing the dependabot branch naming scheme to only include the submodule name and not the commit hash.

**Comment by mwaddell** [comment]
Duplicate of #2882

**Comment by mwaddell** [comment]
Related to #3993

**Comment by JasonGross** [comment]
Duplicate of #3993
