### ISSUE TITLE
[JS] No change to package.json

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/dependabot-core#468]
In RohanNagar/thunder-client-js#9 dependabot is trying to bump a dependency but is only making changes to `package-lock.json`. However, I don't have the "Only lockfile updates" option selected for this repo, so it should modify `package.json` too, correct?

**Comment by greysteil** [comment]
In this case it looks Dependabot is trying to make a distinction between libraries and applications, and has identified that `thunder-client-js` is a library. As a result, it thinks that it's best for it to keep the versions ranges as wide as possible, so it doesn't update the package.json.

Wrong thing to do?

**Comment by RohanNagar** [comment]
Ah I see, I didn't realize there was different logic for libraries and applications. `thunder-client-js` is a library, so that makes sense. Thanks!
