### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by davfsa** [dependabot/dependabot-core#4683]
This request is to add `pyproject.toml` support without the use of poetry or any external packages (just `pip`). 

This was partially implemented back in  back in 2018 with https://github.com/dependabot/dependabot-core/pull/635, which included support for poetry. But `pyproject.toml` was initially proposed in [PEP 518](https://www.python.org/dev/peps/pep-0518/) and later expanded in [PEP 517](https://www.python.org/dev/peps/pep-0517/), [PEP 621](https://www.python.org/dev/peps/pep-0621/) and [PEP 660](https://www.python.org/dev/peps/pep-0660/), which made it is possible to make a package without the use of any setup script or external packages.

Would be really nice to have dependabot detect those dependencies and open pull requests to keep them up to date :)

References:
- Documentation for `pip` on `pyproject.toml`: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
- Example of `pyproject.toml` only package: https://github.com/FasterSpeeding/Tanjun/blob/master/pyproject.toml

**Comment by choldgraf** [comment]
Just a note that this would be useful for us as well. I am seeing more and more Python projects migrating from the `setuptools` workflow to one that uses `pyproject.toml`, especially now that projects like `flit` support editable installs (with `pip install -e`). It feels like `pyproject.toml` is the future standard for Python library dependency configuration, and I'd really appreciate supporting this feature in dependabot.

**Comment by rouge8** [comment]
I think this is a duplicate of https://github.com/dependabot/dependabot-core/issues/3290

**Comment by davfsa** [comment]
Seems to be so, will close then :)
