### ISSUE TITLE
For actions that are pinned-by-hash, bump the human readable version number in the code comment

### ISSUE THREAD

**Issue by ChrisCarini** [dependabot/dependabot-core#4691]
Hello!

As good security practice and guided by the code scanning alert for 'Pinned-Dependencies' from the [ossf/scorecard](https://github.com/ossf/scorecard) project, users are encouraged to pin GitHub workflow actions by hash. The [example provided by the scorecard repo](https://github.com/ossf/scorecard/blob/f55b86d6627cc3717e3a0395e03305e81b9a09be/.github/workflows/main.yml#L27)includes a comment following the action+pinned-hash, example below:
```yaml
     - name: Clone the code
       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
```

Subsequent updates by dependabot do not bump the version in the comment, leading to confusion and incorrect information. An example of this can be found here: ChrisCarini/environment-variable-settings-summary-intellij-plugin#36

Below is a before & after example of the above linked PR

### Before

<img width="762" alt="Screen Shot 2022-01-31 at 22 53 54" src="https://user-images.githubusercontent.com/6374067/151924917-dab1e220-a96f-4792-b719-6c2ade75c9d6.png">

### After

<img width="756" alt="Screen Shot 2022-01-31 at 22 52 13" src="https://user-images.githubusercontent.com/6374067/151924762-fbd11f2b-1455-478d-b2bc-a3276492f6f6.png">

### Summary

Dependabot updated `ossf/scorecard-action` from version `v1.0.1` to `v1.0.2`.

In the "Before", the hash was updated correctly, however the trailing comment with the tag version, was not.

| Hash                                     | Tag Version |
|------------------------------------------|-------------|
| e3e75cf2ffbf9364bbff86cdbdf52b23176fe492 | v1.0.1      |
| c8416b0b2bf627c349ca92fc8e3de51a64b005cf | v1.0.2      |

I believe this change would help GitHub workflow owners to have a better security posture w.r.t. using hash-pinned GitHugb action dependencies, while also having improved ergonomics to be able to quickly verify they are on the correct version.

This idea shares similar sentiment of dependabot/dependabot-core#3699

_(I would consider trying to make a code change for this, however I lack expertise in Ruby and have thus far struggled to get the project opened for development.)_

**Comment by jeffwidman** [comment]
Another comment format we should support (from https://github.com/dependabot/dependabot-core/issues/5314):
> `# pin @v2.4.0`

**Comment by jeffwidman** [comment]
I think this is a great idea and we'd happily merge a PR if anyone wants to take a crack at it. Looking at the relevant code, I don't think it'd be that hard to implement.

A few design notes:
1. Another comment format we should support (from https://github.com/dependabot/dependabot-core/issues/5314) is `# pin @v2.4.0`.
2. Probably we should only bump this pin if it's present... although a part of me wonders if always appending it to SHAs might be both more useful and easier to implement/maintain??
3. It should only be modified if the _actual_ version is a SHA... that avoids accidentally bumping random other comments if the actual version is already human readable.

**Comment by lucacome** [comment]
I want to pin the dependencies in our repos, but I'm kinda waiting for this feature to be implemented. It will make it much easier to maintain.

I was looking into StepSecurity to do the first pass in all the workflows and found https://github.com/step-security/secure-workflows/issues/1087. They removed the tag comment because dependabot doesn't support updating it.

I also wanted to point out that the OpenSSF action uses yet another format for the comment when you create their workflow
```
  - name: "Checkout code"
    uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
```
not sure how popular this is...I think ` # v3.0.0` is more than enough and I'd be okay with dependabot overwriting the comment when updating the dependency.

**Comment by jeffwidman** [comment]
I just deployed this feature, many thanks to @jproberts for contributing the PR.

Many variations of version tags are supported, for examples see the unit tests:
https://github.com/dependabot/dependabot-core/blob/b4112ce4639d7eed1e3b2e0792eb7533f7cb125f/github_actions/spec/fixtures/workflow_files/pinned_sources_version_comments.yml#L7-L30

If you hit bugs please let us know.

**Comment by tobiasKaminsky** [comment]
It seems not to work when updating minor:
https://github.com/nextcloud/android-common/pull/41/files

**Comment by jeffwidman** [comment]
@tobiasKaminsky I think the issue is the code comment format expects the full version... see the test cases above... ie you'd want something like `v3.1.0`... if that doesn't solve it, or if you want `v3` to work, then please create a new issue

**Comment by ReimarBauer** [comment]
Hi everyone,

I discovered this issue while looking for a way to automatically enter the hashes.

I also receive the version comment with Dependabot. How or through what method do you obtain the hash?"

**Comment by panchoh** [comment]
> How or through what method do you obtain the hash?

It's the git hash that identifies the commit, so you can just visit the repo web page on GitHub, and peruse the Releases/Tags section. For each release/tag there you'll see a commit hash (some clicking may be necessary, though). Also, make sure to keep clicking until you get the full hash, not just the abbreviated version that the WebUI shows.

Hope that it helps.

**Comment by gegoune** [comment]
Or use something like https://github.com/suzuki-shunsuke/pinact.
