### ISSUE TITLE
Is it possible to trigger dependabot scan on developer pull requests

### ISSUE THREAD

**Issue by RJColeman** [dependabot/dependabot-core#4728]
(also posted in SO: https://stackoverflow.com/questions/71068152/how-to-trigger-dependabot-scan-on-developer-pull-requests)

I'm not sure if my use case is one dependabot is suited for, so hoping someone can tell me if it is or is not, and if it is, point me to some documentation on how to do what I'm describing:

I want to create workflow that:

1. runs dependabot scan on each developer pull request
2. dependabot only reports on newly introduced or updated dependencies in scanned pull request
3. pull request is blocked by any new dependencies with vulnerabilities of medium or higher
4. dependabot does not create PR as a result of a PR scan

Is this possible or outside the scope of what dependabot's use cases?

**Comment by jurre** [comment]
Hey, it looks like your feature request is about dependabot _alerts_ and the dependency-graph which aren't powered by dependabot-core (I realize this is not necessarily clear), but I think some of what you're is already available with [dependency review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-dependency-changes-in-a-pull-request), and the rest is [planned](https://github.com/github/roadmap/issues/149)

**Comment by RJColeman** [comment]
@jurre Ah thank you so much. I found the info in dependency review shortly after asking this question. And great to see the planned info as well.
