### ISSUE TITLE
Group the same deps into one PR

### ISSUE THREAD

**Issue by hantsy** [dependabot/dependabot-core#4742]
Renovate create a single PR for all deps in a multi projects repo, like this,https://github.com/hantsy/spring-r2dbc-sample/pull/42/files

But dependabot created one PR for each small projects, eg the Quarkus 2.7.1.Final upgrade, see: https://github.com/hantsy/quarkus-sandbox/pulls, if possible to merge all these PR into one PR like renovate.

**Comment by brrygrdn** [comment]
Thanks for your feedback @hantsy, we are tracking this under https://github.com/dependabot/dependabot-core/issues/1190

This is something we do want to deliver for Dependabot.
