### ISSUE TITLE
Dependabot breaks Yarn Zero Install / yarn.lock

### ISSUE THREAD

**Issue by pegak** [dependabot/dependabot-core#4751]
**Package ecosystem**
yarn

**Package manager version**
yarn 3.1, pnp, zero install

**Language version**
Node 16

**Manifest location and content prior to update**
https://github.com/pegak/nauc-me-it/pull/5

**dependabot.yml content**

**Updated dependency**
Next.js from 12.0.10 to 12.1.0

**What you expected to see, versus what you actually saw**
I expect to have correct `yarn.lock`, not one that breaks the app. 

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**
https://github.com/pegak/nauc-me-it/pull/5

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment]
I'm not super familiar with the yarn ecosystem, but ☝️ says this is a duplicate of #1297, which tracks adding Yarn V2 support... that shipped last quarter. So I'm closing as a combo of duplicate + resolved. If for some reason I misunderstood, please comment and we can re-open.
