### ISSUE TITLE
Avoid making duplicate PRs

### ISSUE THREAD

**Issue by Kixunil** [dependabot/dependabot-core#4757]
Dependabot opens a new PR even when there's already a PR to update a dependency (and use its newly added feature) already open. It'd be nice if it could scan the existing PRs and avoid making another one if one of them is updating the dependency already. I guess this could be configurable in case people want an alternative "only update the dependency" PR.

**Comment by jurre** [comment]
Does the old PR get closed but you simply wish Dependabot wouldn't open a new one, or did you get two open PRs for the same dependency?

I ask because the second scenario shouldn't happen, and it would be a bug, but if it's the first scenario then I understand the feature request.

**Comment by Kixunil** [comment]
One PR was from manually created by myself immediately after I published the dependency with a new feature (I maintain the dependency) and later dependabot opened another one. The reason I made the manual PR was to also make use of the newly released feature.

**Comment by brrygrdn** [comment]
👋🏻 @Kixunil Thanks for your feedback, we are looking at ways we can make PRs more aware of any Dependency changes they include other than directly analysing the diff, but right now this isn't something feasible for us.

We are looking more generally at how we can reduce redundant work and noise from Dependabot as part of #1190

**Comment by Kixunil** [comment]
Shouldn't it be relatively easy to just pull information from the relevant file (r.g. Cargo.toml for Rust) in the branch PR is made from? Anyway, thanks for considering!
