### ISSUE TITLE
Specifying runtime.txt causes Dependabot to miss Python dependency files

### ISSUE THREAD

**Issue by choldgraf** [dependabot/dependabot-core#4758]
**Package ecosystem**
`pip`, with `pyproject.toml`

**Manifest location and content prior to update**

https://github.com/executablebooks/sphinx-book-theme/blob/master/pyproject.toml

**dependabot.yml content**

https://github.com/executablebooks/sphinx-book-theme/blob/master/.github/dependabot.yml

**What you expected to see, versus what you actually saw**

I was trying to set up `dependabot` with my repository here: https://github.com/executablebooks/sphinx-book-theme. I'm using `pyproject.toml` to define the dependencies for this package. Also relevant is that I have a folder called `docs/` (for my Sphinx documentation), and this folder had a file in it called `runtime.txt` (which was a configuration file for [mybinder.org](https://mybinder.org).

I looked at the logs for Dependabot's `pip` ecosystem detector, and it was erroring, saying that it was looking for `docs/setup.py` (and apparently missing the `pyproject.toml` file in the project root.

I suspected that the `runtime.txt` file might have something to do with it (because I never configured dependabot to look inside of `docs/`). I deleted that file in this PR: https://github.com/executablebooks/sphinx-book-theme/pull/505

And afterward, Dependabot was correctly able to detect my project's dependencies in `pyproject.toml`

**Things that confused me**

So this problem is resolved for me, but I'm opening this issue in case this is exposing a bug inside of Dependabot. There are two things that seem strange to me about this:

1. That the presence of a file inside of `docs` (in this case, `docs/runtime.txt`) would cause Dependabot to miss another configuration file in the project root (I'd assume the project root should take some kind of precedence)
2. That a file like `runtime.txt` would impact the `pip` ecosystem dependency searcher at all (since I believe `runtime.txt` has no privileged role in the Python community.

I hope that this context is helpful!

**Comment by choldgraf** [comment]
Note that I think I'm going to run into this bug in another repository here:

https://github.com/executablebooks/jupyter-book/tree/master/docs

Where it will be more difficult to delete the configuration files inside of `docs/`. So it would be great to have guidance about how I can get `dependabot` to choose `pyproject.toml` in the root, rather than focus on `docs/requirements.txt` or `docs/runtime.txt`

**Comment by jeffwidman** [comment]
👋 Is this still happening? 

We shipped some changes to improve our `pyproject.toml` support last summer/fall, and perhaps one of those changed the preference order of file selection... So just curious if you're still hitting this?

**Comment by choldgraf** [comment]
I don't _think_ this is an issue any more, but I'm not 100% sure. If you know about this issue and think it's resolved, I think we can just close this, and I'll re-open if I hit the problem again.

**Comment by jeffwidman** [comment]
Sound reasonable, let's do it. I'm not sure you'll be able to re-open since not a maintainer, but you can alwyas just comment on this and one of us will reopen.
