### ISSUE TITLE
Configure PR message (problem with commit message skip ci)

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [dependabot/dependabot-core#4764]
I would like to remove the commits from the PR description. Our team have pipelines that run on PR, and this takes into account the PR description to whether or not skip the CI.

![image](https://user-images.githubusercontent.com/84582602/155614737-7e98a50b-4309-4792-be8f-49b190de1f0c.png)

All these messages of version changes with [skip ci] message are really getting in the way of our pipelines.
I know this might be a problem with the module, but would be helpful if somehow dependabot could work around those messages.

**Comment by jurre** [comment]
Not sure that we should be changing the descriptions, what would you expect dependabot to do in this case? Would it be an option for your CI system to scan the commit messages instead of the PR description? This is the convention I've typically seen for this sort of thing.

**Comment by brunomiranda-hotmart** [comment]
We use drone as our CI tool.

Drone scans commit messages when you make a pipeline for push, when you make pipeline for PRs, it scans the PR message.

> Not sure that we should be changing the descriptions, what would you expect dependabot to do in this case?
I would like to be able to configure what is going to be output on dependabot's PR message. By default this should not be used, but if I would like so, I could be able to.
