### ISSUE TITLE
Do I need a license to use dependabot-core in Azure Devops to monitor repos used for production deployments?

### ISSUE THREAD

**Issue by jcr010910** [dependabot/dependabot-core#4776]
As mentioned in the title, I was under impression that I can use dependabot-core to monitor my repo but the license [here ](https://github.com/dependabot/dependabot-core/blob/main/LICENSE) stated that: "This license lets you use and share this software for free, with a trial-length time limit on commercial use". so looking for a confirmation or pointing to whom shall I contact?

**Comment by yeikel** [comment]
From what I understand, you can use it as long as you do not sell any product with this (example : if you try to build your own clone of dependabot) 

Relevant : https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100

**Comment by jeffwidman** [comment]
As @yeikel helpfully pointed out, https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100 addresses this.
