### ISSUE TITLE
Make dependabot respect granularity of previous semversioning

### ISSUE THREAD

**Issue by DanielNoord** [dependabot/dependabot-core#4779]
For context this PR: https://github.com/DanielNoord/pydocstringformatter/pull/63.

Dependabot updates the version to `3` while the previous version was specified to a `patch` number (`2.3.2`). The associated release does have a patch number (`3.0.0`), see: https://github.com/actions/setup-python.
It would be good if dependabot respects previous "granularity" in semversions and adds a similar level of specificity when upgrading a dependency.

**Comment by xt0rted** [comment]
Sounds like the same issue as #4768

**Comment by hemberger** [comment]
I've been having this issue off and on for a couple years (see, e.g., https://github.com/dependabot/dependabot-core/issues/3704).

Here's another example I just encountered, bumping `codecov/codecov-action` from `v1` to `v2.1.0`:
https://github.com/MechanicalSoup/MechanicalSoup/pull/387

**Comment by bewuethr** [comment]
@hemberger That seems related, but going in the other direction, right? From less specific to more specific.

**Comment by bewuethr** [comment]
Added to a discussion at https://github.com/github/feedback/discussions/12303

**Comment by exvuma** [comment]
This should be fixed in https://github.com/dependabot/dependabot-core/pull/4953 so closing out 😄
