### ISSUE TITLE
[Feature request] Make dependabot github-actions update version in comment

### ISSUE THREAD

**Issue by jauderho** [dependabot/dependabot-core#4787]
I recently switched over to using commit hashes for Github Actions and Dependabot has been doing a great job of keeping things up to date. 

However, I noticed that it has not been keeping the commented version up to date so it would be nice to have that. For example, https://github.com/jauderho/sandbox/pull/171/files where `docker/login-action` is updated from 1.4.0 to 1.4.1

The comment still shows as v1.12.0

**Comment by jeffwidman** [comment]
Agreed, closing as a dupe of https://github.com/dependabot/dependabot-core/issues/4691
