### ISSUE TITLE
RFE: Offer setting to limit Dependabot PRs to only stable Docker container images

### ISSUE THREAD

**Issue by atc0005** [dependabot/dependabot-core#4800]
Unless explicitly specified, I'd like to limit Dependabot Pull Requests for Dockerfiles to stable container updates.

For example, if I have Dependabot monitor this minimal Dockerfile:

```docker
FROM golang:1.17.7
```

I'd like to only ever consider 1.17.8, 1.18.0, 1.18.1, and so on (all stable versions) as valid updates. I'd like to exclude versions such as 1.18beta1, 1.18beta2, 1.18rc1.

If however I have Dependabot explicitly monitor a Dockerfile like this one:

```docker
FROM golang:1.18beta2
```

then I'd like to see Dependabot offer an update to `1.18rc1` when it becomes available.

For the most part this is the behavior I see when using this configuration:

https://github.com/atc0005/go-ci/blob/c9265b73b574006d53cfdedbc7d9e8f933ca5ff8/.github/dependabot.yml

but occasionally I see behavior such as what I've noted on #4798. It would be useful to explicitly define the expected behavior.

Or, as an alternative to explicitly _allowing_ stable updates only, perhaps a setting to explicitly _ignore_ any non-stable updates for a monitored Dockerfile.

**Comment by atc0005** [comment]
Another example:

- https://github.com/atc0005/check-vmware/pull/630
- https://github.com/atc0005/check-vmware/blob/88217754203f84d35da805724555ffa681f93fae/.github/dependabot.yml#L61-L85

Here I'm attempting to limit update PRs to just the 1.17.x series, but instead 1.18rc1 is offered.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply

As noted in https://github.com/dependabot/dependabot-core/issues/4798, we fixed this particular scenario... I assume you didn't encounter this during the recent `go` `1.20` release cycle.

In general, if you're already on a pre-release, then Dependabot _should_ bump you to the next pre-release. 

If you're on a stable version, then it should bump you to the next stable, skipping pre-releases. There's a feature request to allow configuring to always bump to pre-release here:
* https://github.com/dependabot/dependabot-core/issues/2250
