### ISSUE TITLE
Doesn't rebase automatically on merge conflicts anymore

### ISSUE THREAD

**Issue by Maxim-Mazurok** [dependabot/dependabot-core#4804]
**Package ecosystem**
npm
**Package manager version**
8.1.0
**Language version**
Node 17.0.1
**Manifest location and content prior to update**
https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/package.json
**dependabot.yml content**
https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/dependabot.yml
**Updated dependency**
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/617
**What you expected to see, versus what you actually saw**
Since "This branch has conflicts that must be resolved" I expect dependabot to do auto-rebase. Same goes for https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/593
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/617
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/593
<img width="975" alt="image" src="https://user-images.githubusercontent.com/7756211/156914179-ea55dada-4e10-4d85-83fe-352e48f0206e.png">

**🕹 Bonus points: Smallest manifest that reproduces the issue**
N/A

Note, that I'll be running `@dependabot rebase` manually in order to merge PR ASAP. May be related: https://github.com/dependabot/dependabot-core/issues/3132

**Comment by Maxim-Mazurok** [comment]
As a workaround, I'll be using this action: bbeesley/gha-auto-dependabot-rebase

https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/619

**Comment by deivid-rodriguez** [comment]
Thanks for reporting, unfortunately nobody had time yet to look into this.

This was already reported at https://github.com/dependabot/dependabot-core/issues/5317, let's unify discussion there.

**Comment by Maxim-Mazurok** [comment]
Sure, I never got this dependabot feature to work, and the workaround I've mentioned above has been working flawlessly.
