### ISSUE TITLE
Reduce hardcoding of `amd64` to make the dev experience more pleasant on M1 Macs

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4810]
Running `bin/dev-docker-shell` on my M1 Mac throws this warning:

```
/C/d/dependabot-core ❯❯❯ bin/docker-dev-shell
 > image dependabot/dependabot-core-development already exists

=> running docker development shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[dependabot-core-dev] ~/dependabot-core $
```

Grep'ing the repo I see a bunch of `amd64` hardcoding: https://github.com/dependabot/dependabot-core/search?q=amd64

Ideally the architecture would depend on the host platform... that's likely not feasible everywhere, but perhaps some of these could be switched to dynamically picking the architecture. That way if someone is debugging a single ecosystem, possibly it could run natively on arm / apple silicon.

That'd result in a more pleasant dev experience, especially as more and more devs switch to the M1 / M2 apple laptops.

**Comment by deivid-rodriguez** [comment]
mmm just a warning? I couldn't get it to build at all on my machine, any hints?

**Comment by thepwagner** [comment]
Related https://github.com/dependabot/dependabot-core/issues/4697

**Comment by jeffwidman** [comment]
@deivid-rodriguez I can't get the `Dockerfile` to build following [these instructions](https://github.com/dependabot/dependabot-core#building-the-development-image-from-source) due to a problem with `terraform` package. 

But I could pull the latest pre-built docker image following these instructions:
https://github.com/dependabot/dependabot-core#running-with-docker

And then it seems to run fine, other than the warning mentioned in my first post.

So as long as you're not needing to modify the source Dockerfile, you should be okay for now.

**Comment by jeffwidman** [comment]
Closing as this was partially addressed by https://github.com/dependabot/dependabot-core/pull/4858 and this ticket is so broad that it's not super actionable... with the popularity of the M1 laptops, I'm sure we'll soon flush out any additional bugs and tackle them one-by-one.
