### ISSUE TITLE
Add support for private s3 maven repositories

### ISSUE THREAD

**Issue by iathmika** [dependabot/dependabot-core#4813]
I have a use case where I need that dependabot should find out outdated dependencies in the project by fetching latest versions of internal libraries from private s3 repositories too.

We use a modified version of dependabot-core in a jenkins pipeline job which fetches repositories from Gerrit and finds external outdated dependencies for it.  However, there should an option to configure it through AWS s3 credentials for the private registry too having URL of the format `s3://maven.company-name.com/releases`.

**Comment by jeffwidman** [comment]
To clarify:
Is this essentially a Maven-compatible private registry, or just raw disk access from S3?

I'm also confused by the URI protocol... Why `s3://`? Wouldn't you typically want a `https` or `ssh` url to access a given S3 bucket? Or is there some protocol / tool that I'm unfamiliar with?

If you're running Maven natively, what URL would you give it to access these packages?

**Comment by jeffwidman** [comment]
Closing due to lack of user response. Happy to re-open if you provide more info.

**Comment by louis-jaris** [comment]
My company is also interested in this feature ✌️

**Comment by ghaiszaher** [comment]
Hello @jeffwidman, do you think this feature will be considered soon or is it not on your radar? It's getting increasingly important for us to get dependency updates for our private packages on S3 and we might need to explore other options if this is not planned.

**Comment by TriNextMattis** [comment]
Hello @jeffwidman, I wanted to check in on this issue as it is quite important for us. It has been some time since the last update. Are there any plans to implement this any time soon?
