### ISSUE TITLE
Version properties defined in maven profiles are not updated

### ISSUE THREAD

**Issue by whiskeysierra** [dependabot/dependabot-core#482]
See https://github.com/zalando/logbook/blob/master/pom.xml#L567

```xml
    <profiles>
        <profile>
            <id>spring-boot-2.0</id>
            <properties>
                <spring.version>5.0.5.RELEASE</spring.version>
                <spring-boot.version>2.0.1.RELEASE</spring-boot.version>
            </properties>
        </profile>
```

**Comment by greysteil** [comment]
Thanks for the bug report.

Can you be a bit more specific here? It looks like Dependabot created [this PR](https://github.com/zalando/logbook/pull/241) to try to update `spring-boot` - what could it have done better?

**Comment by whiskeysierra** [comment]
Nevermind. The problem is that I only want the version in the profile to be updated. But that's nothing the bot should be doing.
