### ISSUE TITLE
Front-end does not communicate perfectly with the API

### ISSUE THREAD

**Issue by LizelleJ** [dependabot/dependabot-core#4825]
**What you expected to see, versus what you actually saw**
The API from GraphQL reports numerous vulnerabilities for a dependency in yarn.lock, but the front-end (security/dependabot/) shows that the vulnerability has been "fixed". Now, the dependency was updated in 1 place in this file, not each and every place. The API is reporting it as a vulnerability as it was found on another line, but the front-end is not showing the vulnerability at all and it seems like it is picking up the fixed version only and thus not showing the vulnerability still exists on the front-end. This is thus inaccurate and we would not be able to dismiss the vulnerability using the front-end or create a PR for the update.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

Two thoughts:
1. A number of fixes have shipped over the past 6 months that fixed several bugs for scenarios around this. So you might try again and see if it's fixed now?
2. This issue tracker is for `dependabot-core`, the library for creating PR's triggered by cron or security alerts... but it's not for creating alerts themselves. So I'm going to close. If you're still hitting this bug, I suggest starting a discussion at https://github.com/community/community/discussions/categories/code-security, as that's the best way to reach that team.
