### ISSUE TITLE
Nuget Unnecessarily updates SemVer2 build component

### ISSUE THREAD

**Issue by pinkfloydx33** [dependabot/dependabot-core#4845]
Dependabot is unnecessarily creating updates/PRs for Nuget where the before and after refer to the **exact same underlying package version**, but with added SemVer2 data. 

**Package ecosystem**
Nuget
**Package manager version**
6.1.0
**Language version**
C#10/.NET6.0 

**Manifest location and content prior to update**
`csproj` file with the following dependencies (see below for minimal example) 

- Dependency: Serilog.Exceptions
  - Initial Version: `8.1.0`
  - Updated to: `8.1.0+build.52`
- Dependency: Serilog.Enrichers.Span
  - Initial Version: `2.2.0`
  - Updated to: `2.2.0+build.276`

**What you expected to see, versus what you actually saw**
Dependabot is updating package versions that are already technically correct, but substituting in the full SemVer2 version. This creates an unnecessary pull request and is not in line with the instructions on nuget.org or Package Manager behavior. 

For example, the current version of [Serilog.Exceptions](https://www.nuget.org/packages/Serilog.Exceptions/) on nuget.org is listed as `8.1.0` but with a SemVer2 version of  `8.1.0+build.52`. Similarly, [Serilog.Enrichers.Span](https://www.nuget.org/packages/Serilog.Enrichers.Span/) is listed officially as `2.2.0` but with a SemVer2 of `2.2.0+build.276`. 

 My project file was already referencing `8.1.0` and `2.2.0` respectively but dependabot created an update for each with the following diffs:

```diff
-        <PackageReference Include="Serilog.Exceptions" Version="8.1.0" />
+        <PackageReference Include="Serilog.Exceptions" Version="8.1.0+build.526" />
```
and
```diff
-        <PackageReference Include="Serilog.Enrichers.Span" Version="2.2.0" />
+        <PackageReference Include="Serilog.Enrichers.Span" Version="2.2.0+build.276" />
```

IMO this is incorrect for three reasons. First, they technically are the **same version**. Second, per nuget.org, the *official*/listed versions do not include the build component. Finally, the instructions for installing he packages also do not include the extra data.

For example, the instructions for Serilog.Exceptions show  the project file:
```xml
<PackageReference Include="Serilog.Exceptions" Version="8.1.0" />
```
And the CLI:
```bash
dotnet add package Serilog.Exceptions --version 8.1.0
```
Note that the extra SemVer2 build information is absent in both cases. If you add the package via Nuget Package Manager it will not have the added build info either. 

**Native package manager behavior**
Updating with the native package manager does not add the extra SemVer2 build data. 

Note however that this is **not** an error case. The version *is* respected (or ignored?) during restore without generating an error. 

**Images of the diff or a link to the PR, issue or logs**
See above

**🕹 Bonus points: Smallest manifest that reproduces the issue**

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup> 
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup> 
    <ItemGroup>
        <PackageReference Include="Serilog.Exceptions" Version="8.1.0" />
        <PackageReference Include="Serilog.Enrichers.Span" Version="2.2.0" />
    </ItemGroup>
</Project>
```
**Notes**
I am running a customized version of the dependabot script on my Azure DevOps repo. I run inside of a container built from the `Dockerfile` at the root of this repository (so I can customize the UID and GID).

My current version of `dependabot-omnibus` is `0.178.0` though this exhibits in `0.177.0` as well. Likely related to #4255

**Comment by Danielku15** [comment]
Just had a quick look as I lately contributed some changes on NuGet for dependabot and stumbled over this issue.  

I think the error might reside in https://github.com/dependabot/dependabot-core/blob/add0e471c1920e2a726273aee7f84a37429b31c6/nuget/lib/dependabot/nuget/version.rb#L105-L121

The build info is properly parsed already, but it is wrongly considered on the comparisons. I think this whole comparison might simply be dropped as it should be ignored on version compares. This should then make dependabot think that it's the same version and do nothing. 

> Build metadata MUST be ignored when determining version precedence. (https://semver.org/#spec-item-10)
