### ISSUE TITLE
Have clearly stated minimum supported versions

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4856]
Supporting old versions is nice, but adds an engineering cost... especially for drive-by committers like myself.

It'd be helpful to have clearly state minimum supported versions, such as "We default to supporting the last N versions of go, currently that means we support back to go x.xx"

I suspect you'll need to run this by the product team, but it's probably a good idea to start this discussion sooner rather than later so that those deprecation messages can get posted publicly with plenty of warning for folks.

To be clear, this problem extends to all ecosystems, not just go...

**Comment by jurre** [comment]
We have https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem which we could add some more detail to?

**Comment by jonjanego** [comment]
https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories
