### ISSUE TITLE
Bundler CI failure on completely unrelated PR

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4859]
This `bundler` test failure: https://github.com/dependabot/dependabot-core/runs/5559702507?check_suite_focus=true

happened on a PR that only affects `go`, so it must be present on `main` as well, so opening this to track it.

**Comment by deivid-rodriguez** [comment]
I thought #4846 had fixed it but it seems that now the same spec fails at a different place :(

**Comment by deivid-rodriguez** [comment]
This was fixed by #4869!
