### ISSUE TITLE
Dependabot should not add build info to the manifest with NuGet

### ISSUE THREAD

**Issue by jakecoffman** [dependabot/dependabot-core#4873]
This is a follow-on to #4845.

It is an ecosystem best practice to drop the build identifier from the version when adding dependencies to a .NET project. 

[Here's an example from nuget.org](https://www.nuget.org/packages/Serilog.Exceptions/)
<img width="657" alt="Screen Shot 2022-03-17 at 11 54 19 AM" src="https://user-images.githubusercontent.com/886768/158852991-95e7ede6-86de-4a67-9d09-a033abf7985a.png">

Although there is a build identifier, the site tells users to drop it when installing. 

Also doing some searches on github.com, the only time I've seen version numbers in a `.csproj` is when Dependabot bumped the dependency.

Thanks for reporting this @pinkfloydx33!

**Comment by martincostello** [comment]
A recent example of this I encountered from a dependabot update, if it's useful: https://github.com/martincostello/costellobot/pull/51

Adding the build number also seems to break the ability for dependabot to include the release notes in the Pull Request description.

**Comment by Turnerj** [comment]
Agreed - not a fan of the build information being added via Dependabot and manually do the package update to avoid that being added to the git history. My recent example: https://github.com/TurnerSoftware/InfinityCrawler/pull/145

**Comment by jeffwidman** [comment]
Unfortunately we're unlikely to get to this anytime soon, but happy to review a PR if anyone wants to take a crack at this.

**Comment by jakecoffman** [comment]
duplicate of #2310
