### ISSUE TITLE
Use same user

### ISSUE THREAD

**Issue by Incognito** [dependabot/dependabot-core#489]
Low priority but it looks like there's a different user for the committer and author of a commit when dependabot runs:

<img width="276" alt="screen shot 2018-05-22 at 13 13 29" src="https://user-images.githubusercontent.com/379322/40359173-0cb4c358-5dc2-11e8-94c8-2bc2eb5bb75a.png">

This also has caused some of my repos to have the bot listed twice as a contributor. Not really a big issue, but it can mess up automatic statistics tracking and things like that.

**Comment by greysteil** [comment]
Thanks for the heads up. We use that second user for commit signing, because it's not (currently) possible for apps to sign commits themselves (they're not treated as first class users). As soon as that restriction gets lifted I'll switch to using a single user.
