### ISSUE TITLE
Search *.yml on directory different then `/` for github-actions

### ISSUE THREAD

**Issue by flpStrri** [dependabot/dependabot-core#4899]
When using the `directory` attribute for a `github-actions` dependabot seems to be looking inside `/directory_path/action.yml` or `/.github/workflows/<anything>.yml`.

For my template repositories would be nice that it looks inside `/directory_path/.github/workflows/<anything>.yml` so this dependencies are also updated.

**Comment by jurijzahn8019** [comment]
This has already worked, but since some days does not anymore :cry:

**Comment by GustavoKatel** [comment]
it stopped working for me too :( I'm also using dependabot to update templates in a different directory

**Comment by amimart** [comment]
Same issue on this actions collection: https://github.com/okp4/actions

The ability to benefit from dependency updates on a collection of reusable workflows was pretty useful.

**Comment by jeffwidman** [comment]
This was fixed by https://github.com/dependabot/dependabot-core/pull/6189.

However, note [the slight behavior change](https://github.com/dependabot/dependabot-core/pull/6189#issuecomment-1323968366):
> Previously users could indicate directory: `/foo/bar` and get workflow files looked for at `/foo/bar/.github/workflows`. Now they'll need to indicate directory: `/foo/bar/.github/workflows`.

Related:
* https://github.com/dependabot/dependabot-core/issues/5970
