### ISSUE TITLE
Dependabot for NPM creates lockfile with wrong registry

### ISSUE THREAD

**Issue by rethab** [dependabot/dependabot-core#4922]
_please note that replaced out actual internal registry with registry.mycorp.com_

**Package ecosystem**

- npm

**Package manager version**

- npm v8 (lockfile version 2)

**Language version**

- not applicable

**Manifest location and content prior to update**

**dependabot.yml content**

```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
```

**Updated dependency**

- not applicable

**What you expected to see, versus what you actually saw**

Dependabot updated package-lock from

```json
    "node_modules/@octokit/webhooks-types": {
      "version": "5.4.0",
      "resolved": "https://registry.mycorp.com/@octokit/webhooks-types/-/webhooks-types-5.4.0.tgz",
      "integrity": "sha512-wqe8PCvR1R8AEaw1GaT8Q71FnJndGXWg7p9xz+ezrrQ0mm510xZ4J6cywOPemNFFzfGzhAvCh2PqZUevuVqxqQ==",
      "dev": true
    },
```

to:

```json
    "node_modules/@octokit/webhooks-types": {
      "version": "5.5.1",
      "resolved": "https://registry.npmjs.org/@octokit/webhooks-types/-/webhooks-types-5.5.1.tgz",
      "integrity": "sha512-FaBbqZS2e4fCdQvUqeBKpJJOVsRxGcrf0NA91WBXz9GP5/4xgQgdjpbzAcDOSfESBYDYD78HeI5VeihfCW28Ew==",
      "dev": true
    },
```

this means dependabot changed the registry from our internal to the public registry.npmjs.org.

**Native package manager behavior**

- not applicable

**Images of the diff or a link to the PR, issue or logs**

```text
updater | INFO <job_329354585> Checking if @octokit/webhooks-types 5.4.0 needs updating
  proxy | 2022/03/28 10:00:01 [022] GET https://registry.mycorp.com/@octokit%2Fwebhooks-types
  proxy | 2022/03/28 10:00:02 [022] 200 https://registry.mycorp.com/@octokit%2Fwebhooks-types
  proxy | 2022/03/28 10:00:02 [024] GET https://registry.mycorp.com/@octokit%2Fwebhooks-types/5.5.1
  proxy | 2022/03/28 10:00:02 [024] 400 https://registry.mycorp.com/@octokit%2Fwebhooks-types/5.5.1
updater | INFO <job_329354585> Latest version is 5.5.1
updater | INFO <job_329354585> Pull request already exists for @octokit/webhooks-types with latest version 5.5.1
```

Note that these logs are from a second run after the bad PR has already been created.
That is why the last line says "already exists".
However also note that it **is** checking the internal registry.
For other dependencies, I have also seen that dependabot checks both the internal registry and npmjs.

However, since all our dependencies are sourced from an internal registry, dependabot must **never** check the public one. This is a security feature: even if the public registry had a new version, we wouldn't be interested in that. Therefore, I think dependabot should not default to the public registry when an internal one is used.

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by rethab** [comment]
https://github.blog/changelog/2022-12-13-dependabot-hardens-support-for-private-registries/

Does "hardening" mean you fixed this bug ? :) @jeffwidman

**Comment by jeffwidman** [comment]
I didn't personally work on this, but I checked with a colleague who did and he said:
> The focus was more on making attempts to access public registries/sources of metadata optional by “hardening” the calls. IE handling errors so the update can proceed even if these public sources are blocked or down.
> If dependabot (and the npm tooling that we leverage) somehow decides the “private” package is sourced from a public registry, I think we would still go along with it, and if the public registry is not blocked by a firewall, would succeed in the attempt and produce an invalid update.

So the behavior described in this ticket probably still exists... and I agree, if the lockfile already specifies a private registry, we probably shouldn't override with a newer update from a public registry.

**Comment by jeffwidman** [comment]
Another colleague mentioned:
> we expect the private registry to be configured in the project `.npmrc` but if for some reason you didn't want to do that there's a new option to add `replaces-base: true` in your dependabot private registry config to indicate the public registry shouldn't be used

And someone else mentioned:
> In general, I prefer suggesting adding the `.npmrc` to the repo first rather than rely on our ability to generate the correct one as often it’s the case a repo has accidentally messed up their package-lock without realizing it. Happened often when I was doing Node work at my last job.

So while I haven't personally played with either of these, it does seem like there's two possible ways you could use to force not calling out to the public registry... can you try it and let us know if one provides what you need?

Related:
* https://github.com/dependabot/dependabot-core/pull/6138
