### ISSUE TITLE
problems with sub-packages defined in the package > full repository needed

### ISSUE THREAD

**Issue by dennisvandehoef** [dependabot/dependabot-core#4925]
**Package ecosystem**
`go_modules`
**Package manager version**
`0.181.2`
**Language version**
`1.18`
**Manifest location and content prior to update**
Note, I stripped them, as I can't share the real code. Though the stripped version should still explain the issue. foobar.com is the domain of our private hosted GitLab.

go.mod
```
module foobar.com/dir_name/project_name

go 1.18

require (
	github.com/aws/aws-sdk-go v1.10.23
	github.com/certifi/gocertifi v0.0.0-20170727155124-3fd9e1adb12b // indirect
         ....
)
```

main.go
```
package main

import (
        ...
	"foobar.com/dir_name/project_name/config"
)
....
```
**What you expected to see, versus what you actually saw**
I expected updates to run, though this did not work as expected and I git this error: 
```
foobar.com/dir_name/project_name imports
	foobar.com/dir_name/project_name/config: cannot find module providing package foobar.com/dir_name/project_name/config
```

### Code that causes the issue
[Here](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_updater.rb#L69) we only write the files that we collected from the fully checked out git repository in the [FileFetcher](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_fetcher.rb#L19) This includes [the first file that is part of the main package](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_fetcher.rb#L64).

Though the problem is that the subdirectory, with the internal package are not captured, and are not written out. Therefore, the [full go get run](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb#L99) will fail on this. But if you would run `go get -d` (the executed command) inside the repository cloned b the file fetcher, it works without an error.
 
### Solution

I created an ugly monkey patched version of the [Dependabot::GoModules::FileUpdater#use_repo_contents_stub](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_updater.rb#L65) method, that does the trick and fixes it. But can't be back ported here in its current state.

```ruby
require 'dependabot/file_updaters/base'

module Dependabot
  module GoModules
    class FileUpdater < Dependabot::FileUpdaters::Base
      private

      def use_repo_contents_stub
        @repo_contents_stub = true

        file_fetcher = Dependabot::FileFetchers.for_package_manager('go_modules').new(
          # The initializer does not accept the source parameter
          # and we try to change as few as possible in this monkey-patched version
          source: @options[:source],
          credentials: credentials
        )

        SharedHelpers.in_a_temporary_repo_directory(
          file_fetcher.directory,
          file_fetcher.clone_repo_contents
        ) do |path|
          @repo_contents_path = path

          dependency_files.each do |file|
            next if file.name == 'main.go'

            path = File.join(@repo_contents_path, directory, file.name)
            path = Pathname.new(path).expand_path
            FileUtils.mkdir_p(path.dirname) unless Dir.exist?(path.dirname)
            File.write(path, file.content)
          end

          # Only used to create a backup git config that's reset
          SharedHelpers.with_git_configured(credentials: []) do
            `git config --global user.email "no-reply@github.com"`
            `git config --global user.name "Dependabot"`
            `git add .`
            `git commit -m'fake repo_contents_path'`
          end
        end
      end
    end
  end
end
```

**Comment by dennisvandehoef** [comment]
By the way, I exclude main.go as it was not changed by dependabot, and could contain wrong content as simply[ the first file part of the package main](https://github.com/dependabot/dependabot-core/blob/v0.180.2/go_modules/lib/dependabot/go_modules/file_fetcher.rb#L64) is saved here.

**Comment by jeffwidman** [comment]
Thanks for the detailed debugging.

We haven't touched the `go_modules` updating code much for a while, so I assume this is still happening on your repo?

**Comment by deivid-rodriguez** [comment]
Closing since there was no feedback. Feel free to reopen if still running into this!
