### ISSUE TITLE
Support Kotlin Script dependencies

### ISSUE THREAD

**Issue by krzema12** [dependabot/dependabot-core#4947]
With Kotlin's compiler, it's possible to have stand-alone scripts that can fetch Maven dependencies. As an example, see [this script](https://github.com/krzema12/kotlin-python/blob/python-backend/.github/workflows/build_and_test.main.kts):

```kotlin
#!/usr/bin/env kotlin

@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.10.0")
```
The string inside `DependsOn` is package's coordinate using roughly the same format as used by Gradle.

I thought it would be cool for Dependabot to bump versions of these as well. Please let me know if you'd be fine with accepting a contribution of adding a new `package-ecosystem` that would handle it. Technically the package ecosystem is the same as Maven or Gradle, but I suppose it's also about the logic for analyzing the use site of the dependency.

**Comment by krzema12** [comment]
FYI, it's an incoming feature in Renovate Bot: https://github.com/renovatebot/renovate/issues/16662

**Comment by jurre** [comment]
Thanks for the update @krzema12, apologies for not responding to this from our end. I agree it would be cool for Dependabot to be able to do this, but not sure about the timeline in which we'll be able to do it.
