### ISSUE TITLE
Dependency graph not locating manifest files after changing directory

### ISSUE THREAD

**Issue by pauloromeira** [dependabot/dependabot-core#4967]
**Package ecosystem**
- pip

**Package manager version**
- pip-compile 6.6.0

**Language version**
- Python 3.10.3

**Manifest location and content prior to update**
- Old location (working fine): `/requirements`
- New location (bug): `/dependencies/pip/requirements`

**dependabot.yml content**
Before:
```yml
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements" # Location of package manifests
    schedule:
      interval: "weekly"
```
After:
```yml
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/dependencies/pip/requirements" # Location of package manifests
    schedule:
      interval: "weekly"
```

**What you expected to see, versus what you actually saw**

_Expected  to see_: Depency graph being able to find dependencies in the new location
_What I actually saw_: Dependency graph says it couldn't find dependency manifests (shown below)

1. I've figure the issue when a security alert was reported that was also saying it couldn't find `/requrements/Pipfile` manifest. By looking into the logs, apparently it tries to access the old location via but gets a 404, as shown in the logs below
2. After deactivating and re-activating `Settings / Code security and analysis / Dependency graph`, I got a message under `Insights / Dependency graph / Dependencies` saying it couldn't find the dependency manifest
3. All pip dependencies were removed from the listing in `Insights / Dependency graph / Dependencies`
4. I think this might also affect security alerts

**Images of the diff or a link to the PR, issue or logs**
- I could reproduce the issue in this repository: https://github.com/pauloromeira/dependabot-new-directory-bug
- Depency graph can't find manifest files in the new location: https://github.com/pauloromeira/dependabot-new-directory-bug/network/dependencies
- But dependabot can: https://github.com/pauloromeira/dependabot-new-directory-bug/pull/2

Dependabot alerts:
![Screenshot from 2022-04-07 03-12-38](https://user-images.githubusercontent.com/1191135/162133806-c71b45f1-8167-49db-917d-0ef835ab4ff5.png)

View logs:
```
  proxy | time="2022-04-07T06:11:23Z" level=info msg="proxy starting" commit=0cfe6fc8a85a641097e4d9faf5c8349b892b1e40
  proxy | 2022/04/07 06:11:23 Listening (:1080)
updater | 2022-04-07T06:11:23.804006532 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-04-07T06:11:23.837605484 [336144308:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-04-07T06:11:25Z" level=info msg="guest starting" commit=4fb4616711b59a04fd2667246d0074f3ff728601
updater | time="2022-04-07T06:11:25Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=336144308 updater_timeout=30m0s updater_version=0.180.3-4bb639f41f83963743d852df016da6da712ba0b5
updater | I, [2022-04-07T06:11:26.962596 #6]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_336144308> Starting job processing
  proxy | 2022/04/07 06:11:29 [002] GET https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug
  proxy | 2022/04/07 06:11:29 [002] * authenticating github api request
  proxy | 2022/04/07 06:11:29 [002] 200 https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug
  proxy | 2022/04/07 06:11:29 [004] GET https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug/git/refs/heads/master
  proxy | 2022/04/07 06:11:29 [004] * authenticating github api request
  proxy | 2022/04/07 06:11:29 [004] 200 https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug/git/refs/heads/master
  proxy | 2022/04/07 06:11:29 [006] GET https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug/contents/requirements?ref=8d0c49df61298ce37f50bd475639090d5e6a062d
  proxy | 2022/04/07 06:11:29 [006] * authenticating github api request
  proxy | 2022/04/07 06:11:29 [006] 404 https://api.github.com:443/repos/pauloromeira/dependabot-new-directory-bug/contents/requirements?ref=8d0c49df61298ce37f50bd475639090d5e6a062d
updater | ERROR <job_336144308> Error during file fetching; aborting
updater | INFO <job_336144308> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-04-07T06:11:30Z" level=info msg="task complete" container_id=job-336144308-file-fetcher exit_code=0 job_id=336144308 step=fetcher
updater | time="2022-04-07T06:11:30Z" level=warning msg="failed during fetch, skipping updater" job_id=336144308
```

At `Insights / Dependency graph / Dependencies`, after disabling and re-enabling dependency graph:
![Screenshot from 2022-04-07 03-32-12](https://user-images.githubusercontent.com/1191135/162135028-23317d0b-3c69-4600-aed4-8ee5fbe8921b.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**
- Create a repo with pip-compile manifests under `/requirements` and a `dependabot.yml` file with the directory pointing to `/requirements`
- Activate Dependency graph (`Settings / Code security and analysis / Dependency graph`)
- Move `/requirements` to `/dependencies/pip/requirements` and point `dependabot.yml`'s directory to the new location (`/dependencies/pip/requirements`)
- Disable and re-enable Dependency graph
- Go to `Insights / Dependency graph / Dependencies`

(I did those same steps [here](https://github.com/pauloromeira/dependabot-new-directory-bug))

**Comment by brrygrdn** [comment]
Hi @pauloromeira, thanks for the bug report!

I'll have to check in with my colleagues on the Dependency Graph side on that part of the issue. With regards to your original repo where you found Dependabot also didn't detect the manifest path, it's possible your config file could be invalid so it is failing over to the previous configuration.

If you aren't comfortable sharing the repository name and/or the contents of the `dependabot.yml` file in a public issue, please [contact support](https://support.github.com/contact) and link to this issue so we can discuss it further.

**Comment by brrygrdn** [comment]
In regards to the Dependency Graph detection, it disregards a list of common vendor directories so we don't detect and alert on your vendor's manifest files.

The list of defined vendor directories we ignore is [here](https://github.com/github/linguist/blob/32ec19c013a7f81ffaeead25e6e8f9668c7ed574/lib/linguist/vendor.yml#L16)

**Comment by pauloromeira** [comment]
Hi @brrygrdn, thank you for taking a look into this.

Unfortunately I cannot share the original repo, but I could reproduce this issue exactly here: https://github.com/pauloromeira/dependabot-new-directory-bug

As you can see, [Dependency Graph](https://github.com/pauloromeira/dependabot-new-directory-bug/network/dependencies) can't find manifest files, although Dependabot is able to [bump dependencies](https://github.com/pauloromeira/dependabot-new-directory-bug/pulls) just fine.

**Comment by jeffwidman** [comment]
As best I can tell reading this, the Dependency graph is expected since the path to the manifest file includes an ignored name from linguist.

The Dependabot failure wasn't expected, but looking at the trace and timing I suspect it's simply a job that was stuck in a queue somewhere, so by the time it got to Dependabot update job, the old manifest file was deleted and since it was a security update it simply took the security alert config and looked in that path... which is now gone.

I'm going to close as this is overall working as expected as best I can tell... but if for some reason I'm wrong please comment and we can reopen.
