### ISSUE TITLE
rest api for retrieving dependency alerts

### ISSUE THREAD

**Issue by jgangemi** [dependabot/dependabot-core#4974]
are there plans to introduce a rest api that will allow for querying about alerts in a repository and across an organization? i'd like to be able to create some automated tooling around generating reports.

**Comment by brrygrdn** [comment]
Hi @jgangemi - we don't currently have a REST implementation for Dependabot alerts, we do however provide access to this information via the [v4 GraphQL API](https://docs.github.com/en/graphql/reference/objects#repositoryvulnerabilityalert).

We've recently updated this [to make it easier to retrieve information about Dependabot PRs as well](https://github.blog/changelog/2022-04-06-dependabot-alert-api-adds-relevant-update-info-to-the-schema/).

Unfortunately, we don't have any plans to add a REST implementation at the moment.
