### ISSUE TITLE
Security updates: Allow/Ignore specific manifests

### ISSUE THREAD

**Issue by tsawada** [dependabot/dependabot-core#4997]
My repo has multiple manifest files (lock files), and a few of them are auto-generated from other list of dependencies that dependabot does not support directly.
I am happy that dependabot can scan for security alerts for those autogenerated files, but do not want dependabot to open PRs for them because we have to fix the source thus those PRs are not useful.

I found `open-pull-requests-limit` for version updates, but the documentation says it "has no impact on security updates".
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

It'd be great if I can turn off just PRs for security updates, but still keep the dependabot to alert on the manifests.

**Comment by brrygrdn** [comment]
Hi @tsawada! If you go into your repository Settings > Code security and analysis, you can disable "Dependabot security updates".

This will not affect alerts on the manifests, just stop PR creation. You can also remove any `.github/dependabot.yml` file if you don't want any PRs for Security or Version updates.

I hope this answers your question, feel free to re-open the issue if not.

**Comment by tsawada** [comment]
Thanks @brrygrdn, but that does not do what I want.
Let's say that my repository has `a/package.json` and `b/package.json`, and I want to stop PR creation just for `b/package.json` but still want PRs for `a/package.json`.
I think the setting you mentioned will stop PR creation for both `a/` and `b/` altogether.

**Comment by tsawada** [comment]
ping? @brrygrdn please reopen

**Comment by brrygrdn** [comment]
Ah, I understand the problem, that makes sense. We do intend to look at our configuration of Dependabot services in GitHub and I think this requirement makes good sense.

**Comment by jeffwidman** [comment]
Let's track this more broadly as allow/ignore specific manifests for any type of update, and then the schedule would handle applying the config to security updates vs version updates.

So closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2883
