### ISSUE TITLE
Support NuGet package version overrides

### ISSUE THREAD

**Issue by martincostello** [dependabot/dependabot-core#4999]
In a forthcoming version of the .NET SDK/Visual Studio/NuGet, support will be added for projects using NuGet [Central Package Management](https://devblogs.microsoft.com/nuget/introducing-central-package-management/) (i.e. with `Directory.Packages.props`) to override the version of a specific package reference using the new [`VersionOverride`](https://devblogs.microsoft.com/nuget/introducing-central-package-management/#overriding-package-versions) property.

As far as I can tell from looking at the code (I'm by no means a Ruby expert so I may have misinterpreted it), dependabot-core would not currently support offering updates for such declarations.

Dependabot already supports package updates for usage of `<PackageVersion>` elements in `Directory.Packages.props`, so I would have thought this should also be supported to complete the support of this feature when it becomes stable in Visual Studio 17.2/.NET SDK 6.0.300/NuGet 6.2.

**Comment by klemmchr** [comment]
Any updates on this? Central Package Management is already available publicly but dependabot is still incomptabile.

**Comment by jeffwidman** [comment]
PR's are always welcome. Happy to provide pointers if anyone is interested but not sure where to start.

**Comment by martincostello** [comment]
Did this get resolved by #8179?

**Comment by danmoseley** [comment]
FWIW dotnet/aspire has central package management and dependabot was updating it smoothly (until the recent deployment of #8179). It managed to follow the properties to where they were set as well.

So as far as I know this issue can be closed (?)

**Comment by abdulapopoola** [comment]
Closing this out as suggested by @danmoseley and liked by @martincostello
