### ISSUE TITLE
Dependabot alerts won't clear after update

### ISSUE THREAD

**Issue by jaydorsey** [dependabot/dependabot-core#5008]
**Package ecosystem**
bundler

**Package manager version**
bundler 2.3.11 (also tried with 2.3.6)

**Language version**
ruby 3.1.1, 3.1.2

**Manifest location and content prior to update**
`/Gemfile` in standard root location

Private repo, but here's the relevant snippet
```
    nokogiri (1.13.4)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.4-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.4-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.4-x86_64-linux)
      racc (~> 1.4)
```

**dependabot.yml content**
N/A. Never configured a `dependabot.yml` file

**Updated dependency**
`nokogiri`, from `1.13.3` to `1.13.4`

**What you expected to see, versus what you actually saw**

I expected the security banner to disappear once I merged the dependency update into my default branch

The security banner did not disappear once I merged the dependency update into my default branch. It's been almost 6 days and I've also tried:

- Rolling back to a vulnerable version & doing a new pull request/merge with the patch
- Upgrading bundler & ruby versions

I also observe the graphql API showing these vulnerabilities as existing, when they do not.

**Native package manager behavior**

When I run `bundle audit check --update` locally & as a CI step, no vulnerabilities are present.

**Images of the diff or a link to the PR, issue or logs**

Security banner:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/191564/163696994-98c1242b-6a34-427c-94e8-d30366acbba8.png">

Actual alert (and merged in PR)

<img width="964" alt="image" src="https://user-images.githubusercontent.com/191564/163697000-e6ecb183-3370-40c7-aa04-7169ea76483d.png">

Github action where we also run bundle audit:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/191564/163697045-0b39e29f-248d-4ecf-9b0a-64715fc9a67d.png">

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Unable to reproduce this on new/other repos, however:

This is happening on ~6 of our private repos that all have slightly different configs (one has sidekiq enterprise, for example. One has a private library referenced. Some are only public gems)

**Comment by deivid-rodriguez** [comment]
I run into the same thing with the latest nokogiri security update. I thought it was maybe related to a single gem update solving 2 different security vulnerabilities. Anyways, I cleared the alerts manually (reporting "Alert is inaccurate or incorrect") and moved on. But I will report back if it happens again.

**Comment by jaydorsey** [comment]
> Anyways, I cleared the alerts manually (reporting "Alert is inaccurate or incorrect") and moved on.

I did not know this was a feature, so thanks for pointing that out. Previously, we shied away from dismissing alerts because we noticed that when we had regressions (from a bad merge conflict, for example, where we patched it and then it was re-opened) the alert never got "re-triggered".

Being able to classify the alert dismissal is pretty useful though so I'll give te bhat a try again.

Will use that as a workaround for this instant issue but will leave this issue open (hopefully) because it sounds like it's not intended behavior.

**Comment by Radon8472** [comment]
I have a similar issue (I think it is related to this issue).

In my case the alerts where cleared, but Dependabot still shows a warning in "Dependency graph".

The info says patches versions `1.10.22, 2.0.13` and `1.10.23, 2.1.9`, and my depencies are now `"^1.10.23 || ^2.1.9"` so the issue should be fixed [see here](https://github.com/Radon8472/pwmoduleinstaller/blob/2241bd80e288474231f8016b05eae0036b346cf2/composer.json#L34)

**Comment by renatolond** [comment]
I have the same in one my repos which is public, here it is if it helps for debugging :)
https://github.com/renatolond/mastodon-twitter-poster

**Comment by jeffwidman** [comment]
I'm going to close this issue as the original issue has been worked around, and this is now becoming a catch-all issue. Unfortunately catch-call issues aren't really helpful because while the symptoms may be similar, the root cause may be entirely different.

My guess is that the majority of these issues are caching issues which have likely cleared by now, but if for some reason you're still seeing issues, please open a new issue and be sure to include a link to your repo. If it's a private repo, then open a support ticket.

**Comment by JarnoRFB** [comment]
I had a similar problem, that merged PRs were showing next to open dependabot alerts, which is confusing. However, when I looked at the details of the alerts I found that the alert was reopened after having been closed once, which explained why a merged PR can be shown next to an open alert.

![image](https://user-images.githubusercontent.com/8550270/187146660-faab0a3f-a29f-43e1-acf7-d6047a8cfc7d.png)

In the details one can also see which exact PR reintroduced the vulnerable dependency. 
Indicating this more clearly in the overview that the alert was reopened would make it less confusing though.

**Comment by jeffwidman** [comment]
@JarnoRFB per the comment right above yours:
> ...this is now becoming a catch-all issue. Unfortunately catch-call issues aren't really helpful because while the symptoms may be similar, the root cause may be entirely different... if for some reason you're still seeing issues, please open a new issue and be sure to include a link to your repo. If it's a private repo, then open a support ticket.

I'm going to lock this issue to prevent similar follow-on comments. Please file new issues instead.

**Comment by jeffwidman** [comment]
@JarnoRFB my apologies, I just re-read your comment, and I see you were helpfully trying to provide clarity here, you weren't actually raising a new issue. 

Sorry for my misreading of your helpful comment, and thank you for the helpful screenshot.

I'm going to unlock this, but again, anyone with an actual issue, please file a new issue instead of tagging onto this issue.
