### ISSUE TITLE
Dependabot ignores version constraint for i386 Docker image

### ISSUE THREAD

**Issue by atc0005** [dependabot/dependabot-core#5009]
**Package ecosystem**
- Docker

**Package manager version**

- N/A

**Language version**

- N/A

**Manifest location and content prior to update**

- https://github.com/atc0005/go-ci/blob/d1aeb7e2b0317eac35f3e8d15a7908f5ddf9e80a/stable/build/alpine-x86/Dockerfile

**dependabot.yml content**

- https://github.com/atc0005/go-ci/blob/d1aeb7e2b0317eac35f3e8d15a7908f5ddf9e80a/.github/dependabot.yml#L174-L200

**Updated dependency**

- Currently using `i386/golang:1.17.9-alpine3.14` (set manually), Dependabot offers `i386/golang:1.18.1-alpine3.14`

**What you expected to see, versus what you actually saw**

- expected no offer of Dockerfile update as 1.17.9 is the latest Go 1.17 image at this time (https://github.com/atc0005/go-ci/pull/608)
- expected an update from 1.17.8 to 1.17.9 instead of 1.17.8 to 1.18.1 as https://github.com/atc0005/go-ci/pull/601 applied (which I later manually reversed once I realized that I merged an invalid PR)

**Native package manager behavior**

- N/A

**Images of the diff or a link to the PR, issue or logs**

Current PR:

- https://github.com/atc0005/go-ci/pull/608

Previous PR:

- https://github.com/atc0005/go-ci/pull/601 

As noted earlier, the current PR is unexpected as the version constraint should be preventing 1.18 from being offered for all but the `unstable` Dockerfile (different directory path, different Dependabot config block). The prior PR was incorrect as the version constraint was expected to result in an offer of an update version update for the same series (1.17.x instead of 1.18.x).

**Comment by jakecoffman** [comment]
Try setting the dependency name to `i386/golang` in `dependabot.yml`:

```
    ignore:
      - dependency-name: "i386/golang"
```

**Comment by atc0005** [comment]
> @jakecoffman:  Try setting the dependency name to `i386/golang` in `dependabot.yml`:
> 
> ```
>     ignore:
>       - dependency-name: "i386/golang"
> ```

Thanks for the help! The suggested changes appear to work as intended.

- https://github.com/atc0005/go-ci/pull/610
- https://github.com/atc0005/go-ci/pull/611
  - https://github.com/atc0005/go-ci/pull/612
