### ISSUE TITLE
Support for private repositories in a VPN?

### ISSUE THREAD

**Issue by lukehsiao** [dependabot/dependabot-core#5011]
While dependabot added support for private repositories, it relies on these private repositories by accessible on the public internet (perhaps behind some authentication).

Another common setup is for the private repository to be totally isolated from the public internet, and only accessible to users on a company VPN (e.g., tailscale).

Is there any way we could support this?

One option: if dependabot was configurable to run as a github workflow, then users could leverage other actions (e.g., https://github.com/tailscale/github-action) to make sure their private repository was visible to dependabot.

**Comment by trazek** [comment]
Any word on this? Seems like having dependabot accessible to private repos is not even for my use case as well

**Comment by jeffwidman** [comment]
Today there's three ways to run the code here in `dependabot-core`:
1. Using the native service built into GitHub... this is what people normally think of for Dependabot, and what gets run when you add the `dependabot.yaml` file.
2. Standalone, using an entrypoint like https://github.com/dependabot/dependabot-script. This can absolutely be done within the context of a GitHub action to wire in something like Tailscale, or even run completely air-gapped if you wanted to download it and run it offline within your VPN/private network.
3. Using GitHub's standalone GitHub Enterprise Server (GHES) product. This basically runs a local copy of GitHub on an appliance, so you get convenience of 1️⃣ but the VPN/offline capability of 2️⃣ . Many large companies you've heard of do exactly this.

So yeah, this is all possible, and very flexible, you get to choose the tradeoffs of convenience vs customization.

**Comment by jfly** [comment]
> 2. Standalone, using an entrypoint like https://github.com/dependabot/dependabot-script

Note, as of 2024-05-30, this approach appears to have [been broken for over a year](https://github.com/dependabot/dependabot-script/commit/2cfe9b095ce8eeb65442ec9512b6bf4bb56067b5).
