### ISSUE TITLE
set Maven repository URL config variable per project instead of globally

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#503]
I work on Java open source projects, some of which build with Maven central and some requiring building against https://nexus.opendaylight.org. Ideally, I don't want to set nexus.opendaylight.org as the global Maven repository URL config variable - because that mirror is slow enough as it is... :smile: 

In an ideal world, I'd there like to be able to set Maven repository URL config variable per project instead of globally.

**Comment by greysteil** [comment]
Interesting. What's the reason you don't include `https://nexus.opendaylight.org` as a repository in the top-level POM for those repos? Does it have credentials in the URL?

If you add a Maven repository URL as a Dependabot config variable then Dependabot will look at that repo as well as at the Central Repository (the relevant code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/update_checkers/java/maven/version_finder.rb)) - hopefully it shouldn't slow down the mirror too much, since it never actually pulls down any files (it just inspects the POMs).

**Comment by vorburger** [comment]
> reason you don't include https://nexus.opendaylight.org as a repository 

opinions about how good an idea that really is vary widely... :smile_cat: 

It can be a PITA, for example, if you have corp internal maven repo mirrors of FLOSS code.

> in the top-level POM for those repos?

In this particular case, the "top-level" POM where this would have to do, even if we wanted to do it (which the community that this code is from, not personal project, most likely will not want to anyway), it would not actually help / work:

See e.g. https://github.com/opendaylight/infrautils/blob/master/common/parent/pom.xml which has 
a parent that is from https://github.com/opendaylight/odlparent - but those are different repos. So if you built the former, it would not find the POM(s) from the latter, which could define a parent, anyway. This is just 1 example of many such repos in that community - they don't even all have a single per-project parent, so No Go.

> then Dependabot will look at that repo as well as at the Central Repository

Oh? That's not how [a custom Maven settings.xml](https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml) would work... :-) It could in theory be a problem if one were crazy enough to put forks of artifacts with the same GAV on a "mirror" rep. But I'm getting pedantic here, sorry. :smiley: 

I've just tried what you suggested, but hit #505.

**Comment by greysteil** [comment]
👍, thanks for the explanation. I've just pushed a fix for #505 which *should* fix things for this case - please let me know if it doesn't!

**Comment by yeikel** [comment]
How do you set this globally?

**Comment by greysteil** [comment]
@yeikel this and the previous issue you commented on have been closed for several years - it's probably best to open a new issue asking for support.

I no longer work on Dependabot directly, but I _think_ the docs you want in this case are [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot).

**Comment by yeikel** [comment]
Thank you, @greysteil. I created a new issue as suggested
