### ISSUE TITLE
`updates[*].directory` configuration key no longer respected for GitHub Actions workflows

### ISSUE THREAD

**Issue by per1234** [dependabot/dependabot-core#5047]
The GitHub Actions file fetcher code was changed by https://github.com/dependabot/dependabot-core/pull/4815 to assume that the `updates[*].directory` configuration key points to the location of a [GitHub Actions action metadata file](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) if it has any value other than `/`:

https://github.com/dependabot/dependabot-core/blob/0e83753c9c89bcd96a61471478544f44e4183b88/github_actions/lib/dependabot/github_actions/file_fetcher.rb#L44-L48

This made it no longer possible to use Dependabot to maintain dependencies of GitHub Actions workflow which are located anywhere except the standard `.github/workflows`.

We were using that capability to maintain collections of reusable workflows [in a centralized repository](https://github.com/arduino/tooling-project-assets/tree/main/workflow-templates), from which they are propagated to specific project repositories. In this use case, the fact that the workflows are outside the `/.github/workflows` path used by GitHub Actions is irrelevant (in fact essential as we don't want them to run in the centralized "assets" repository).

I feel that this use of the `updates[*].directory` configuration key to differentiate between what are really two completely separate things (workflows vs action metadata files) is unintuitive and likely to cause other problems in the future as the two files evolve according to their distinct purposes. It would be best to instead differentiate them via separate `updates[*].package-ecosystem` key values.

### Package ecosystem

`github-actions`

#### Location

Any location following the format:

```text
<updates[*].directory>/.github/workflows
```

Example:

```text
/workflow-templates/dependabot/workflow-template-copies/.github/workflows
```

#### Content

Any workflow containing a reference to an outdated action.

Example:

```yaml
on:
  - push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
```

### dependabot.yml content

Any file with `updates[*].directory` key value other than `/` for the `github-actions` ecosystem.

Example:

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /workflow-templates/dependabot/workflow-template-copies/
```

### Updated dependency

Any GitHub Actions action with an available version newer than the one specified in the Workflow reference.

For example:

`actions/checkout@v2` -> `actions/checkout@v3`

#### Expected

Dependabot submits a PR to update the outdated action reference in the GitHub Actions workflow.

#### Actual

Dependabot no longer submits PRs to update the workflows under `<updates[*].directory>/.github/workflows`.

The updates check now fails with an error.

For example:

```text
Dependabot couldn't find a <anything>.yml
Dependabot couldn't find a .yml.

Dependabot requires a .yml to evaluate your Github_actions dependencies. It had expected to find one at the path: /workflow-templates/dependabot/workflow-template-copies/action.yml or /.github/workflows/<anything>.yml.
```

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply here.

Your use case makes sense to me. Would https://github.com/dependabot/dependabot-core/issues/5137 be another way to solve this more generically?

**Comment by per1234** [comment]
Thanks @jeffwidman.

I don't see anything in https://github.com/dependabot/dependabot-core/issues/5137 that would explicitly solve this issue.

As long as this logic remains, there is no fix:

https://github.com/dependabot/dependabot-core/blob/60539be83d982d73ec15262a5c6b75631ccf55bf/github_actions/lib/dependabot/github_actions/file_fetcher.rb#L48

If the implementation of https://github.com/dependabot/dependabot-core/issues/5137 somehow changes that logic, then the situation may be different. However, it seems that would an inadvertent side effect rather than an integral part of implementing the proposal from https://github.com/dependabot/dependabot-core/issues/5137, which is about using wildcards to discover the [`action.yml` metadata files for GitHub Actions actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) in the repository, and not about discovering the [GitHub Actions workflow files](https://docs.github.com/actions/using-workflows/about-workflows).

---

I would be absolutely fine with any change that makes it possible to use Dependabot to maintain GitHub Actions workflows outside `/.github/workflows/`. If that requires the modification of our existing `dependabot.yml` file, no problem. If that requires moving the "assets" workflows to some other path in the repository, no problem.
