### ISSUE TITLE
Maven repository config variables must specify a username and password

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#505]
https://nexus.opendaylight.org/content/repositories/public/ and http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ are examples of Nexus Maven repositories which host artifacts from a (large) particular open source community, but which does not require authentication.

Currently, setting the Maven repository URL config variable on https://app.dependabot.com/accounts/vorburger/repos (global only; see #503) refuses this with an error saying "Maven repository config variables must specify a username and password", thus apparently insisting that any other Maven repo than central must have both a URL and uid/pwd - which is not, neccessarily, the case.

**Comment by greysteil** [comment]
Sorry about that. I'll get this fixed tomorrow morning - it's a bank holiday here today. 🙂

**Comment by greysteil** [comment]
This should now be fixed. Can you let me know if you have any problems?

**Comment by vorburger** [comment]
I've just been able to set `https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/` as Maven repository URL config variable on https://app.dependabot.com/accounts/vorburger/repos without username and password, so it looks like this works.

**Comment by yeikel** [comment]
@vorburger or @greysteil  Can you explain how you set it? I am looking for the same
