### ISSUE TITLE
Use an http npm repo instead of https

### ISSUE THREAD

**Issue by balazs92117** [dependabot/dependabot-core#5060]
We use dependabot mostly for npm and yarn package updates. We have a private repo called repo2.private.company.com. And as the name suggests it is on a private network (10.0.x.y) and therefor it doesn't use https, only http.
The problem is, dependabot somehow forces https.
I tracked down the problem, and inside the temp folder, the .npmrc file gets generated with "@company:registry=http**s**://repo2.private.company.com/repository/npm-stuff/" content.
I checked the files, and I think this one generates the .npmrc: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
In that file, **https** is hard coded.

How can we use a "non-secure" private repo via **http** with dependabot?

**Comment by jeffwidman** [comment]
In https://github.com/dependabot/dependabot-core/pull/5928, the protocol passed in is now honored, so you should now be able to pass in `http`.

I'm going to close as resolved, but please try it and if for some reason it's not working comment and we can re-open.
