### ISSUE TITLE
Dependabot should not look into nuget disabledPackageSources

### ISSUE THREAD

**Issue by leoChronos** [dependabot/dependabot-core#5061]
I work on projects that use private nuget feeds only and we block public feeds using **disabledPackageSources**. Our expectation is that Dependabot would offer some way to ignore feeds or respect project configuration for **disabledPackageSources**.

**Comment by jakecoffman** [comment]
This should be working now with https://github.com/dependabot/dependabot-core/pull/5874. Let us know if you have any issues!
