### ISSUE TITLE
dependabot PR changes protocol from git+ssh to https

### ISSUE THREAD

**Issue by msf-figma** [dependabot/dependabot-core#5071]
The dependabot PR at https://github.com/figma/figma/pull/65091/ changed the protocol for an internal dependency (`github.com/figma/livegraph`) from `git+ssh` to `https`).

Before:
```
$ jq .dependencies.livegraph.from <package-lock.json
"livegraph@git+ssh://git@github.com/figma/livegraph.git#9e474edc3ef6a818d2fafdf40b57696840fc2028"
```

After:
```
$ jq .dependencies.livegraph.from <package-lock.json
"livegraph@https://github.com/figma/livegraph.git#9e474edc3ef6a818d2fafdf40b57696840fc2028"
```

**Package ecosystem**

npm

**Package manager version**

npm 8.5.3

**Language version**

node 16.13.1

**Manifest location and content before the Dependabot update**

livegraph/package-lock.json

**dependabot.yml content**

**Updated dependency**

`bump minimist from 1.2.5 to 1.2.6`

**What you expected to see, versus what you actually saw**

I expect the protocol to remain `git+ssh`, but it changed to `https`.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue, or logs**

https://github.com/figma/figma/pull/65091

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jp1987** [comment]
Any update/work around for this? Running into the same issue.
