### ISSUE TITLE
Support for batched PR

### ISSUE THREAD

**Issue by laurentsimon** [dependabot/dependabot-core#5089]
Dependabot creates a PR for each update. It's really really really hard in terms of usability when users follow best practices such as pinning dependencies by hash.

I would like to have batched PRs where the cadence can be configured. Users could select a weekly PR update, for example.

Note that certain users are trying to get around this by using custom actions/code to automatically merge these PRs, or automatically "review" them. This is pretty dangerous code: for example I don't think merely checking check the author of the PR works, because it can be spoofed.

IFAIK, renovatebot has support for this, so it would be great to have feature parity.

**Comment by jeffwidman** [comment]
This falls into the "grouped updates" bucket which has several different issues in the backlog depending on the variant of the request, but the one that most closely matches this variant is probably https://github.com/dependabot/dependabot-core/issues/1190.
