### ISSUE TITLE
Dependabot can't fetch changelog information when the source url is a organization private repository

### ISSUE THREAD

**Issue by oburgosm** [dependabot/dependabot-core#5101]
We have a Maven project in our organization hosted in Github Enterprise Cloud and many artifacts that inherit from this artifact. We want that dependabot manage the updates from the parent artifact in the others repositories. The PR is being created but the problem is that this PR doesn't contain releases/changelog information body that we think it should have. It seems that dependabot try to access to the source_url, but it can't fetch the information due to a 401 error:

```
proxy | 2022/05/05 10:30:50 [066] * de-auth'd request returned 401, replacing response
proxy | 2022/05/05 10:30:50 [069] GET https://github.com:443/<my-org>/<my-artifact>.git/info/refs?service=git-upload-pack
```

- Can be provided a configuration for setting token or credentials that allows dependabot to access the release/changelog content from the organization private repository?
- Any other alternative for getting this content retrieval working?

**Comment by jeffwidman** [comment]
Possibly related: https://github.com/dependabot/dependabot-core/issues/2291

**Comment by oburgosm** [comment]
It was in the same  GitHub Enterprise Cloud organization, but currently we don't have this problem

**Comment by jeffwidman** [comment]
Thanks for letting us know. It could also have been fixed by some of the changes mentioned in this comment:
* https://github.com/dependabot/dependabot-core/issues/2291#issuecomment-1284536002
