### ISSUE TITLE
Dependabot not ignoring dependency as requested

### ISSUE THREAD

**Issue by dwieeb** [dependabot/dependabot-core#511]
This started just a couple days ago. A while ago I asked dependabot to ignore a dependency: https://github.com/ionic-team/ionic-cli/pull/3145. Two days ago, it opened a PR for an older version: https://github.com/ionic-team/ionic-cli/pull/3247. I asked it to ignore it again. This morning it's still opening PRs: https://github.com/ionic-team/ionic-cli/pull/3273

**Comment by greysteil** [comment]
👍 - I'll take a look. We changed the logic for this recently (see [this blog post](https://dependabot.com/blog/updating-older-versions)).

**Comment by dwieeb** [comment]
Oh, awesome! That will be helpful when there are updates to 6.*

Is there an undo feature if I've completely ignored a dependency?

**Comment by greysteil** [comment]
Yep - reopen the PR that you ignored it in, or bump it yourself. I’m travelling right now but going to dig into the bug that caused those PRs tonight.

**Comment by greysteil** [comment]
This was absolutely a bug - sorry about that. We weren't handling ignore conditions correctly for repos that don't commit a lockfile where a dependency was fully ignored (as it this case). I've fixed that, and if you close ionic-team/ionic-cli#3273 with `@dependabot ignore this version` then Dependabot won't bother you about it again unless you upgrade. Sorry about that one!

**Comment by dwieeb** [comment]
@greysteil Thanks! No worries. 

And I gotta say how awesome Dependabot is. 💪 You're crushing it!
