### ISSUE TITLE
Dependencies not found in Docker when Dockerfile uses UTF-8 BOM encoding

### ISSUE THREAD

**Issue by jblazek** [dependabot/dependabot-core#5118]
**Package ecosystem**
docker

**Package manager version**
n/a

**Language version**
n/a

**Manifest location and content before the Dependabot update**
[Dockerfile1](https://github.com/jblazek/dependabot-test/blob/main/Dockerfile1)
[Dockerfile2](https://github.com/jblazek/dependabot-test/blob/main/Dockerfile2)

**dependabot.yml content**

https://github.com/jblazek/dependabot-test/blob/main/.github/dependabot.yaml

**Updated dependency**
not applicable, updates not recognized.

**What you expected to see, versus what you actually saw**

When using docker package manager, I noticed one repo Dockerfile was not updating while others were. I expect to see _Checking if dotnet/aspnet 5.0.7-alpine3.13 needs updating_, but did not and just saw _finished job processing_ 

Upon investigation, the file which was not being updated was using UTF-8 BOM encoding while others which were getting PR updates were just using UTF-8.

**Native package manager behavior**
n/a

**Images of the diff or a link to the PR, issue, or logs**

_Dockerfile1_

```text
updater | INFO <job_362848288> Starting job processing
updater | INFO <job_362848288> Starting update job for jblazek/dependabot-test
updater | INFO <job_362848288> Checking if dotnet/aspnet 5.0.7-alpine3.13 needs updating

...other log entries checking dependency version...

updater | INFO <job_362848288> Finished job processing
```

_Dockerfile2_

```text
updater | INFO <job_362848288> Starting job processing

...other log entries, no dependency is detected...

updater | INFO <job_362848288> Finished job processing
```

PR for file not using BOM encoding: https://github.com/jblazek/dependabot-test/pull/1

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Smallest manifest is [Dockerfile2](https://github.com/jblazek/dependabot-test/blob/main/Dockerfile2), only a FROM directive is needed and save the file with UTF-8 BOM encoding.

**Comment by mattt** [comment]
Thanks for reporting this, @jblazek. I have a potential fix with #5129.
