### ISSUE TITLE
Add prefix to security update dependabot prs

### ISSUE THREAD

**Issue by bruno-salapic** [dependabot/dependabot-core#5135]
Currently it seems the only way to change/alter the commit message is via a config file.
Which based on my reading only applies to version updates (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

Since for security updates it doesn't seem that it takes any config file, can we have a way to have the same feature to alter/modify the commit-msg based on our needs/requirements.

We require Jira ticket to be the prefix of tickets as I'm sure many companies do as well. this seems like a must-have.

If there already exists a way to alter security update commit-msgs and I just completed and missed it in the docs please redirect me.

**Comment by ml242** [comment]
Interested in this because my commitlint config is breaking as of a few days ago on dependabot pull requests.

**Comment by jeffwidman** [comment]
If we were to do anything, we'd probably expose this via labels:
* https://github.com/dependabot/dependabot-core/issues/4761

From there, you could use a GitHub action to take whatever follow-up action you wanted, such as modifying the commit and force-pushing it to the PR branch. 

I'm going to close as a duplicate of https://github.com/dependabot/dependabot-core/issues/4761.
