### ISSUE TITLE
Support for BitBucket ?

### ISSUE THREAD

**Issue by dependb** [dependabot/dependabot-core#5148]
Is there any support for BitBucket now ?
If yes, can I get links to the resources required to integrate dependabot in BitBucket.

**Comment by jeffwidman** [comment]
There's two types of BitBucket support:
1. Pulling dependency updates _from_ repos from bitbucket... this is already supported, it's just another git repository endpoint. We do have a little bit of special handling for the bitbucket client, but not a lot.
2. Running dependabot itself on BitBucket to update code _within_ a Bitbucket repo. For that you're looking for https://github.com/dependabot/dependabot-script

**Comment by mayphyuoo** [comment]
Hi, I know this is already closed, but it is saying scripts are broken in [dependabot-script](https://github.com/dependabot/dependabot-script)? will it still work?

**Comment by anyulled** [comment]
> Hi, I know this is already closed, but it is saying scripts are broken in [dependabot-script](https://github.com/dependabot/dependabot-script)? will it still work?

now you need to use https://github.com/dependabot/cli
