### ISSUE TITLE
Error while running the command : bin/dry-run.rb go_modules rsc/quote 

### ISSUE THREAD

**Issue by dependb** [dependabot/dependabot-core#5154]
```
cryo_ch33m@IE4LLT93J0YD3:~/dependabot-core$ bin/docker-dev-shell
 > image dependabot/dependabot-core-development already exists

=> running docker development shell
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules rsc/quote
bin/dry-run.rb is only supported in a development container.

Please use bin/docker-dev-shell first.
```

**Comment by jakecoffman** [comment]
The dry-run script [checks](https://github.com/dependabot/dependabot-core/blob/31fa5969183584dd62718eba21d6aec31694cb51/bin/dry-run.rb#L40) that the dependabot user is running the script. Did you make changes to the Dockerfiles?

**Comment by dependb** [comment]
No, I haven't made any changes to the Dockerfiles.

**Comment by jakecoffman** [comment]
https://github.com/dependabot/dependabot-core/issues/5153 seems to indicate this wasn't an issue at first?

Try modifying the script to output the value of `Etc.getpwuid(Process.uid).name`. If it's not `"dependabot"` then the script will not proceed.
