### ISSUE TITLE
dependabot stuck at 'Checking now' for hours 

### ISSUE THREAD

**Issue by yashash1511** [dependabot/dependabot-core#5160]
![image](https://user-images.githubusercontent.com/89068816/168982502-4d829487-6319-43e4-b52a-9af129b0c9ab.png)
https://github.com/blueedgetechno/win11React/network/updates

there has been problem with dependabot on this particular repo previously too #5112

the link to dependabot file https://github.com/blueedgetechno/win11React/blob/master/.github/dependabot.yml

happens with this particular repo only (even if i fork this repo and then enable dependabot on the fork it works there)

**Comment by yashash1511** [comment]
yes it is fine now thanks a lot

**Comment by yashash1511** [comment]
![image](https://user-images.githubusercontent.com/89068816/169513751-b91d29f0-2e0e-4c77-b8a7-606a018486ef.png)
https://github.com/blueedgetechno/win11React/blob/master/.github/dependabot.yml

we updated the dependabot.yml file 2days ago but it seems that dependabot is still using older config & trying to access that secret which is no longer required

**Comment by yashash1511** [comment]
sorry nvm

**Comment by yashash1511** [comment]
firstly i am sorry for closing & reopening multiple times

![image](https://user-images.githubusercontent.com/89068816/169515240-6d736d04-c9a0-4a06-a8c7-e16f3f3ceea7.png)
we no longer require secret we updated the dependabot config 2days ago but still it is using the older config and saying secret could not be read

**Comment by jakecoffman** [comment]
I ran another resync and it cleared out the deleted registry. We're looking into why this is happening, thanks for reporting it!

**Comment by yashash1511** [comment]
I manually ran 'Check for updates'
![image](https://user-images.githubusercontent.com/89068816/169552965-1b1ffbc2-d464-4c31-b203-e3cf62f96d31.png)

it worked this time thank you

**Comment by jakeleventhal** [comment]
I am experiencing this hanging forever
<img width="974" alt="Screenshot 2023-09-11 at 9 40 48 AM" src="https://github.com/dependabot/dependabot-core/assets/15133828/ce1a45d9-92d5-4294-8986-30cfb141029c">

**Comment by amitkachi** [comment]
> I am experiencing this hanging forever <img alt="Screenshot 2023-09-11 at 9 40 48 AM" width="974" src="https://private-user-images.githubusercontent.com/15133828/267038586-ce1a45d9-92d5-4294-8986-30cfb141029c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjE4MjEsIm5iZiI6MTcwOTU2MTUyMSwicGF0aCI6Ii8xNTEzMzgyOC8yNjcwMzg1ODYtY2UxYTQ1ZDktOTJkNS00Mjk0LTg5ODYtMzBjZmIxNDEwMjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0MTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYzQ4YTIyOTVkNTA0ZWMyYTk5ZTM2NWQyZDI4MzhjYzY4ZmU0NGJiNmVlY2ZjMTkzMDlmMWQ3MWEzNDI5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eIE9IZ53g_SApLyibvl2Pu8B-Vv9EvcUBvB7258_bKI">

I am facing the same issue! its stucked for a days in checking now state. any help here?

**Comment by mikicz** [comment]
![image](https://github.com/dependabot/dependabot-core/assets/5583319/46392602-ca8b-4a0c-9827-f047d399fad0)

Happening for me still

**Comment by hellofanny** [comment]
hello guys! 
I'm also facing the same issue! It's stuck on `checking now`. I tried to making a small change to the `dependabot.yml`, but still happening. 🙇‍♀️ Is there any workaround that I could try?

<img width="802" alt="image" src="https://github.com/user-attachments/assets/f0655cac-b9b1-4d89-95fe-687107a12ba7" />
