### ISSUE TITLE
Terraform: Two or more modules with same relative source in the same file results in multiple attempts to create the same PR

### ISSUE THREAD

**Issue by dwc0011** [dependabot/dependabot-core#5167]
Terraform referencing the same relative source more than once in the same file results in the following error when creating commit and PR in CodeCommit, it works with Github as that processes duplicate files in the commit differently, unable to test with Bitbucket and Azure

```
Updating iam_policy_document::github::plus3it/terraform-aws-tardigrade-iam-principals::11.0.1 from 11.0.1..to 12.0.0
--
986 | /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/aws-sdk-core-3.131.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': 
Cannot put the file at the specified path because there are one or more conflicting file change requests for that file. 
Either resolve the conflicts locally, or put the files you want to add in different paths, and then try again.. 
Path: /modules/iam_policy_document/main.tf (Aws::CodeCommit::Errors::SamePathRequestException)
```

**Package manager version**
Terraform

**Updated dependency**
:github::plus3it/terraform-aws-tardigrade-iam-principals::11.0.1 from 11.0.1..to 12.0.0
**What you expected to see, versus what you actually saw**
Expected: the child module iam_policy_document to be updated once since the module is a relative source, it should only need to be updated once
Actual: the updated_files list contains the file multiple times referenced for the same 

Proposed solution:  [terraform/file_updater.rb](https://github.com/dependabot/dependabot-core/blob/780bcdb0b6f81659a071c0220632a98265625bfc/terraform/lib/dependabot/terraform/file_updater.rb#L28) not add duplicate files if they exist already.

** Minimal Config to reproduce **
./main.tf:
```
module "child1" {
  source = "./child"
}

module "child2" {
  source = "./child"
}

```
./child/main.tf
```
module "dns" {
  source = "git::https://github.com/cloudposse/terraform-aws-route53-cluster-zone.git//some/dir?ref=tags/0.2.5"
}
```

I am working this PR already.

**Comment by jeffwidman** [comment]
> it works with Github as that processes duplicate files in the commit differently

Can you clarify the behavior you observe with GitHub? I'm curious if it's filtering it out or something else?

**Comment by dwc0011** [comment]
> > it works with Github as that processes duplicate files in the commit differently
> 
> Can you clarify the behavior you observe with GitHub? I'm curious if it's filtering it out or something else?

I updated the description to minimize the test case further and ran and debugged using the live-run.rb

I am not exactly sure how the github api deals with it, I do know that the code passes both file trees (derived from the child module being included twice and the trees are duplicates of each other) to the [github create_tree api](https://github.com/dependabot/dependabot-core/blob/50fd5475565065e8e6a1421460b78093e9cc53e8/common/lib/dependabot/pull_request_creator/github.rb#L202)  
and it resolves it and creates a single commit, branch, and PR.
