### ISSUE TITLE
How to use dependabot-core to raise PR for a bitbucket repository

### ISSUE THREAD

**Issue by dependb** [dependabot/dependabot-core#5171]
How to use dependabot-core to raise PR for a bitbucket repository

**Comment by jeffwidman** [comment]
There's two types of BitBucket support:
1. Pulling dependency updates _from_ repos from bitbucket... this is already supported, it's just another git repository endpoint. We do have a little bit of special handling for the bitbucket client, but not a lot.
2. Running dependabot itself on BitBucket to update code _within_ a Bitbucket repo. For that you're looking for https://github.com/dependabot/dependabot-script
