### ISSUE TITLE
Dependabot does not respect semver version ranges specified in package.json 

### ISSUE THREAD

**Issue by DerekLiang** [dependabot/dependabot-core#5176]
**Package ecosystem**

npm_and_yarn

**Manifest contents prior to update**

package.json
```json
{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ngx-lightbox": "~1.0.0"
  }
}
```
package-lock.json
```json
{
  "name": "sample",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "ngx-lightbox": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/ngx-lightbox/-/ngx-lightbox-1.0.0.tgz",
      "integrity": "sha512-+ZSun1hN87GpZxsMLg6fix1SmIjXREgV8qkg8EpT+NXWCvP+fT3n56ijRSmOXBubdLN1gOwLY+3QZtycCSvKyw=="
    }
  }
}
```
**Manifest contents after update**
```json
{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ngx-lightbox": "~2.6.1"
  }
}

```

```json
{
  "name": "sample",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "file-saver": {
      "version": "2.0.5",
      "resolved": "https://registry.npmjs.org/file-saver/-/file-saver-2.0.5.tgz",
      "integrity": "sha512-P9bmyZ3h/PRG+Nzga+rbdI4OEpNDzAVyy74uVO9ATgzLK6VtAsYybF/+TOCvrc0MO793d6+42lLyZTw7/ArVzA=="
    },
    "ngx-filesaver": {
      "version": "8.1.0",
      "resolved": "https://registry.npmjs.org/ngx-filesaver/-/ngx-filesaver-8.1.0.tgz",
      "integrity": "sha512-xAwThsB/ap9qs7BRgW+mJPWBK60uaqkfPnw3vzbykTdfIvGf62U/6osDCq4TCPl/POWLFui6b3Bu+gfDMqoZhw==",
      "requires": {
        "tslib": "^1.9.0"
      }
    },
    "ngx-lightbox": {
      "version": "2.6.1",
      "resolved": "https://registry.npmjs.org/ngx-lightbox/-/ngx-lightbox-2.6.1.tgz",
      "integrity": "sha512-4sMG6QvXEbuiXnnJxZpV+B49q5uplvOYh2YK0gC24dhEcdoOyevIQRjf8WYgiJ4pRtZZUG3D6JZ+dbSKOkbMIg==",
      "requires": {
        "file-saver": "^2.0.5",
        "ngx-filesaver": "8.1.0"
      }
    },
    "tslib": {
      "version": "1.14.1",
      "resolved": "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz",
      "integrity": "sha512-Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg=="
    }
  }
}

```

**update via dependabot-script**
``` bash
docker run  -v "$(pwd)/dependabot-script/:/home/dependabot/dependabot-script" \
                    -w '/home/dependabot/dependabot-script' \
                    -e AZURE_ACCESS_TOKEN=$AZURE_PAT \
                    -e GITHUB_ACCESS_TOKEN=$GITHUB_PAT \
                    -e PACKAGE_MANAGER=$PACKAGE_MANAGER \
                    -e PROJECT_PATH=$PROJECT_PATH \
                    -e DIRECTORY_PATH=$DIRECTORY_PATH \
                    -e BRANCH=$BRANCH \
                    dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb
```

**in npmjs.com**
```
[2.6.1](https://www.npmjs.com/package/ngx-lightbox/v/2.6.1) 5,755 15 days ago
...
[2.1.2](https://www.npmjs.com/package/ngx-lightbox/v/2.1.2) 909 2 years ago
[2.1.1](https://www.npmjs.com/package/ngx-lightbox/v/2.1.1) 407 3 years ago
[2.1.0](https://www.npmjs.com/package/ngx-lightbox/v/2.1.0) 93 3 years ago
[2.0.2](https://www.npmjs.com/package/ngx-lightbox/v/2.0.2) 16 3 years ago
[2.0.1](https://www.npmjs.com/package/ngx-lightbox/v/2.0.1) 99 3 years ago
[2.0.0](https://www.npmjs.com/package/ngx-lightbox/v/2.0.0) 329 3 years ago
[1.2.0](https://www.npmjs.com/package/ngx-lightbox/v/1.2.0) 584 3 years ago
[1.1.0](https://www.npmjs.com/package/ngx-lightbox/v/1.1.0) 27 4 years ago
[1.0.2](https://www.npmjs.com/package/ngx-lightbox/v/1.0.2) 11 4 years ago
[1.0.1](https://www.npmjs.com/package/ngx-lightbox/v/1.0.1) 4 4 years ago
[1.0.0](https://www.npmjs.com/package/ngx-lightbox/v/1.0.0) 2 4 years ago
```

**I'd expect:**
A) dependabot to open a pull request for all minor/patch versions of ngx-lightbox < 1.1
B) when  `~` is omitted, dependabot to not touch ngx-lightbox dependency.

The following screen shows an **incorrect** update. I am expecting it to be `1.0.2` instead of `2.6.1`.
![image](https://user-images.githubusercontent.com/13641/169624018-6bd511f0-8bc1-40f1-be1e-ac3334199283.png)

**Comment by jeffwidman** [comment]
@markus-k can you please open a separate issue for the python Pipfile problem? They may be related, but there's a lot of ecosystem specific code and just as likely they are separate issues.

**Comment by martijnhartlief** [comment]
The `<` symbol seems to be ignored as well.

<img width="1138" alt="Schermafbeelding 2022-06-24 om 13 00 55" src="https://user-images.githubusercontent.com/12697043/175521980-c0a20239-6137-46e1-8246-81c0b715003b.png">

**Comment by igordrnobrega** [comment]
Hey guys, are there any plans to check on this? Thanks.

**Comment by fregante** [comment]
Isn't this by design? Dependabot cannot work if it has to follow ranges:

- 5.0.0 = hardcoded, will never update
- ^5.0.0 = only 5.x can ever be updated, no major updates allowed
- ~5.0.0 = only 5.0.x can ever be updated, no minor updates allowed

The only allowed range would have to be `*`, but that has obvious consequences for users of your package.

In short, server ranges are not for dependabot, but for your users. If you want to enforce the same rules, then tell dependabot via `@dependabot ignore this major version` and such.

**Comment by martijnhartlief** [comment]
> If you want to enforce the same rules, then tell dependabot via `@dependabot ignore this major version` and such.

I'm not looking forward to tell dependabot for every repository and package combination what it shouldn't update after it tries to update it for the first time.

**Comment by jeffwidman** [comment]
@fregante thanks for your comment, it helped me understand what folks are actually asking for here.

You can configure Dependabot to [ignore version ranges of updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore).

I'm not as familiar with `dependabot-script`, but I suspect you can use the `OPTIONS` param to pass in the desired ignores via JSON. Docs are currently somewhat lacking there, but I hope to pay down some tech/docs debt on that repo over the next few months.

I'm going to close because as explained by @fregante this appears to be a misunderstanding of how Dependabot works with version ranges in your manifest files. If for some reason I'm misunderstanding, please leave a clarifying comment and we can re-open.
