### ISSUE TITLE
Pick one reviewer from group

### ISSUE THREAD

**Issue by rubencodes** [dependabot/dependabot-core#5185]
It would be really great if we could alternatively set dependabot to pick a random reviewer from the list of reviewers, rather than tagging everyone as is the default behavior. This would be similar to how [CODEOWNERS](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#routing-algorithms) picks from a group.

For context, our org has a team that focuses on keeping our infrastructure up to date, and we don't need everyone looped in on every minor package update—just some pseudo-random assignment. Thank you!

**Comment by mattt** [comment]
Thanks for sharing this idea with us, @rubencodes!

According to [the docs](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-team-notifications), you _might_ be able to achieve this by specifying a team as a value for the [`"reviewers"` key](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers). Do you have the "Only notify requested team members" and "Enable auto assignment" settings enabled for your team?

![review-assignment-notifications](https://user-images.githubusercontent.com/7659/170332451-a404385c-01e9-4ca5-b6fd-846500726d88.png)

![review-assignment-enable](https://user-images.githubusercontent.com/7659/170332356-58936d90-8f20-4997-bcde-9b4b6326e7c2.png)

**Comment by rubencodes** [comment]
Oh that might be what I was missing, thank you! I'll give that a try and report back!
