### ISSUE TITLE
Auto-rebase does not work

### ISSUE THREAD

**Issue by laurentsimon** [dependabot/dependabot-core#5215]
Hi,

I have dependabot enabled https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/dependabot.yml

I have not declared `rebase-strategy` (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy), yet none of the PRs are rebased automatically.

I don't understand why, but it's making the experience pretty terrible :/

Could you tell me what I'm missing?

Thank you!

**Comment by jakecoffman** [comment]
We pushed a fix for this yesterday and it looks like Dependabot force pushed to this PR: https://github.com/slsa-framework/slsa-github-generator/pull/173

So I'm going to call this fixed! 

Reopen if it misbehaves again. Thanks for the report!

**Comment by nikosmoum** [comment]
Can we please re-open this? 
It is not working for us (we're using gradle: https://github.com/candlepin/candlepin/blob/master/.github/dependabot.yml)
Here is the latest PR with a merge conflict for at least 20 minutes, and it hasn't been automatically rebased: https://github.com/candlepin/candlepin/pull/3421

**Comment by angelod1as** [comment]
@nikosmoum maybe you need to open a new issue?

**Comment by nikosmoum** [comment]
@angelod1as I have created https://github.com/dependabot/dependabot-core/issues/5317

**Comment by duaneking** [comment]
Reopen this, please.
