### ISSUE TITLE
Terraform updates sometimes fails to add lockfile hashes for included platforms

### ISSUE THREAD

**Issue by Flydiverny** [dependabot/dependabot-core#5225]
**Package ecosystem**
terraform

**Package manager version**
terraform 1.0.0 and terraform 1.2.2 (not entirely sure what dependabot runs)
`required_version = "1.0.0"` ([repro](https://github.com/Flydiverny/dependabot-tf-repro-1.0.0/pull/2/files))  and `required_version = ">=1.1.0, <2.0.0"` ([repro](https://github.com/Flydiverny/dependabot-tf-repro/pull/1)) both exhibit the same problem 

**Language version**
terraform 1.0.0 and terraform 1.2.2 (not entirely sure what dependabot runs)
`required_version = "1.0.0"` ([repro](https://github.com/Flydiverny/dependabot-tf-repro-1.0.0/pull/2/files))  and `required_version = ">=1.1.0, <2.0.0"` ([repro](https://github.com/Flydiverny/dependabot-tf-repro/pull/1)) both exhibit the same problem 

**Manifest location and content before the Dependabot update**
`.terraform.lock.hcl`

**dependabot.yml content**
https://github.com/Flydiverny/dependabot-tf-repro/blob/3b5e9aa2024a5a3d5cef34edea3a7b6d9fdab71e/.github/dependabot.yml#L1-L12

**Updated dependency**
`registry.terraform.io/hashicorp/aws` from 4.13.0 to 4.17.0

**What you expected to see, versus what you actually saw**
Expected
```terraform
provider "registry.terraform.io/hashicorp/aws" {
  version = "4.17.0"
  hashes = [
    "h1:0i4o/1AEBOIW/fr3C45vJlG350FfRzSldJcWfViOFLc=",
    "h1:5NfNH5iQ3VGpMwjlSOkQyBYh8mvKH3QMp0UHB71eTqc=",
    "h1:FtkENM8QDK6CLhBr4k97kx26G2CqHZk9q5sNhHcnYRc=",
    "zh:2cc932fb0af13850de3c60a5318b695c82973489c140ca4f13218f69136c36e5",
    "zh:4018884d66acfa8273f7100ef0334004ed8a3790ffc7621eaef65d1d9c3fab43",
    "zh:6a7769e5c81e543f5deaaa8596e45f92244a61f5026c8c66d5bf55f2a7fd4801",
    "zh:7956c1e17ec7647af3612cc98cbcd21d50b2d9f5e41c676b62ee214f5610c29f",
    "zh:833d9d608dbffda7da565004ef592a8a364e96b5c13cacf873f5d32714e197ff",
    "zh:9b12af85486a96aedd8d7984b0ff811a4b42e3d88dad1a3fb4c0b580d04fa425",
    "zh:a55b8b72e47999d9c7aecaa009797ed7eb3f669a719d3f6127ee5e0f1b91ecc2",
    "zh:a6f2377d71dfba9669f060e687498e589b490366026821bd83451ac9ef0cd9e8",
    "zh:b006aa281097b3db27a62ea3c8cfaf4c4d979d57f4a6c180bd2da3d0ab4bd61a",
    "zh:d6a6d29256fee6c3b35384719c84c19b13dcccc53bffce5f529023607d130d0b",
    "zh:edc155e147883872e1227aa6a4ef3205fa9de421475d96c20a34a5eaff3df01f",
    "zh:f25773dcc00dead0412e222cf3891ac6228dcb4d69da9bacfca305a0a2a1db56",
  ]
}
```

Result ([see dependabot PR here](https://github.com/Flydiverny/dependabot-tf-repro/pull/1))
```terraform
provider "registry.terraform.io/hashicorp/aws" {
  version = "4.17.0"
  hashes = [
    "h1:0i4o/1AEBOIW/fr3C45vJlG350FfRzSldJcWfViOFLc=",
    "zh:2cc932fb0af13850de3c60a5318b695c82973489c140ca4f13218f69136c36e5",
    "zh:4018884d66acfa8273f7100ef0334004ed8a3790ffc7621eaef65d1d9c3fab43",
    "zh:6a7769e5c81e543f5deaaa8596e45f92244a61f5026c8c66d5bf55f2a7fd4801",
    "zh:7956c1e17ec7647af3612cc98cbcd21d50b2d9f5e41c676b62ee214f5610c29f",
    "zh:833d9d608dbffda7da565004ef592a8a364e96b5c13cacf873f5d32714e197ff",
    "zh:9b12af85486a96aedd8d7984b0ff811a4b42e3d88dad1a3fb4c0b580d04fa425",
    "zh:a55b8b72e47999d9c7aecaa009797ed7eb3f669a719d3f6127ee5e0f1b91ecc2",
    "zh:a6f2377d71dfba9669f060e687498e589b490366026821bd83451ac9ef0cd9e8",
    "zh:b006aa281097b3db27a62ea3c8cfaf4c4d979d57f4a6c180bd2da3d0ab4bd61a",
    "zh:d6a6d29256fee6c3b35384719c84c19b13dcccc53bffce5f529023607d130d0b",
    "zh:edc155e147883872e1227aa6a4ef3205fa9de421475d96c20a34a5eaff3df01f",
    "zh:f25773dcc00dead0412e222cf3891ac6228dcb4d69da9bacfca305a0a2a1db56",
  ]
}
```

**Native package manager behavior**

Using `terraform init -upgrade` and `terraform providers lock -platform=darwin_amd64 -platform=darwin_arm64 -platform=linux_amd64` will give the expected output as pasted above.
**Images of the diff or a link to the PR, issue, or logs**
https://github.com/Flydiverny/dependabot-tf-repro/pull/1

**🕹 Bonus points: Smallest manifest that reproduces the issue**

The referenced repository has the smallest reproduction I was able to make.
Having just the `registry.terraform.io/hashicorp/aws` provider to upgrade the pull request from dependabot actually did include the platform hashes, and reading the log, see attached 
[dependabotlog.txt](https://github.com/dependabot/dependabot-core/files/8834074/dependabotlog.txt), it looks like it does download the platforms so I'm not sure why they are not in the PR in the end.

**Comment by Nishnha** [comment]
Thanks for reporting and reproducing this bug! I'll take a look.

Our [current Terraform version in Dependabot is 1.2.0](https://github.com/dependabot/dependabot-core/blob/main/Dockerfile#L225), but seeing how this issue persists across versions, I don't think it's related to that.

**Comment by Nishnha** [comment]
I found that the root cause of this bug is an overeager regular expression: https://github.com/dependabot/dependabot-core/blob/69c8c38a73c0ccbf1f3d022537aa3dd83d033024/terraform/lib/dependabot/terraform/file_updater.rb#L267-L269

Instead of removing the hashes array for each provider in the lockfile, this removes from the hash array of first provider to the end of the hash array of the last provider. This results in a lockfile that only contains the version information for the first provider:

```
provider "registry.terraform.io/datadog/datadog" {
  version = "x.y.z"
  hashes = [
    "h1: ...",
    "zh: ...",
  ]
}

provider "registry.terraform.io/hashicorp/archive" {
  version = "x.y.x"
  hashes = [
    "h1: ...",
    "zh: ...",
  ]
}

provider "registry.terraform.io/hashicorp/aws" {
  version = "x.y.z"
  hashes = [
    "h1: ...",
    "zh: ...",
  ]
}
```

becomes:

```
provider "registry.terraform.io/datadog/datadog" {
  version = "x.y.z"
}
```

instead of:

```
provider "registry.terraform.io/datadog/datadog" {
  version = "x.y.z"
}

provider "registry.terraform.io/hashicorp/archive" {
  version = "x.y.x"
}

provider "registry.terraform.io/hashicorp/aws" {
  version = "x.y.z"
}
```


With no version information in the lockfile for the other providers, Terraform fetches the hashes for the _latest_ version. Thus, the version of the downloaded hashes are different from the original. When these hashes are compared, the file updater finds that none match and defaults to using `linux_amd64`.

Fixing the overeager regex should resolve this.

**Comment by Flydiverny** [comment]
@Nishnha I put up this draft PR https://github.com/dependabot/dependabot-core/pull/5341 that from my local testing fixes things. I'm not really sure about how to add additional tests here, made some futile attempts locally but I haven't really done any ruby and just keep getting `Content didn't change!` for the new tests I tried to add😄
