### ISSUE TITLE
Feature: custom notes or comments that stay with dependency and appear on every PR

### ISSUE THREAD

**Issue by filipkis** [dependabot/dependabot-core#5248]
Sometimes there is some internal knowledge related to some dependancy. For instance, that it has to be updated together with another (e.g. backend and frontend version of same library), some hack or tricky situation that needs to be checked manually etc. 

Additionally, with bigger team it would be useful to just see what issues (aka comments or additional manual changes) were needed in previous PRs related to the same dependancy. Then somebody new dealing with dependancy would have easier time dealing with it.

Here are some suggestions, but obviously open to more discussion and ideas:

* new dependabot commands `@dependabot note [message]` which then records a note related to that dep which would get displayed somewhere on every future PR related to that dep (there could also be `@dependabot remove note [id]` for removing outdated notes - or simply just UI remove button
* displaying a list of all previous PRs and indicating how many non-dependabot comments and changes they have
* similar to previous point, but allowing you in the same list to expand and see the actual comments from previous PRs so you don't have to navigate elsewhere

**Comment by mattt** [comment]
Thanks for sharing your thoughts, @filipkis. I agree that updates requiring some additional context are problematic, because it adds friction to reviewing and acting on Dependabot PRs.

Is this a problem you could solve with CI checks? For example, if two versions of a dependency need to be coordinated across subprojects in a monorepo, you could add a check in an Actions workflow to make sure they agree with each other. This may be more or less possible, depending on your specific project structure or the kinds of checks you're doing, but the general idea is that any PR with a ✅ should be ready to merge.

**Comment by jeffwidman** [comment]
👋 Hey @filipkis dunno if you remember, but over a decade ago you unexpectedly hosted a visiting speaker for the local TEDx conference in Croatia after Eyjafjallajökull forced his flight to get canceled and he was too poor to afford a hotel. That was me. 😁 
I've still got fond memories of playing street basketball on the pavement behind your apartment, as well as running the Plitvice lakes circuit upon your recommendation, not to mention experimenting with shifting the stickshift w/o using the clutch on the drive to/from. 🙄 
Thanks again for your hospitality!

For this feature request, I also know exactly the problem you're facing, but I'd really prefer we keep Dependabot focused on PR updates and as stateless as possible. It's not that hard to use GitHub actions to setup a CI bot to auto-comment on any PR that touches a particular dependency.

I'll run this by some of the other engineers for a second opinion, but it'll likely be a wontfix.

**Comment by filipkis** [comment]
Hi @jeffwidman, 

Of course I remember. I was wondering every now and then what have you been up to. Seeing your message here put a smile on my face and I, once again, cannot believe how small our world is.

Anyhow, thanks for checking in on this. I totally understand desire to make PR updates stateless and if you chose to make this wontfix. Still wish it wasn't so, but I think you guys have bigger improvements to focus on.

Greetings from Sweden :)

**Comment by jeffwidman** [comment]
Sounds good. I'll close for now. And give me a holler if you ever make it across the pond towards Seattle/ Vancouver.
