### ISSUE TITLE
No consuming dependabot.yml file - undefined method "dep.package_manager" in update_config file

### ISSUE THREAD

**Issue by dependb** [dependabot/dependabot-core#5254]
```
Traceback (most recent call last):
        1: from /home/dependabot/dependabot-core/common/lib/dependabot/config/update_config.rb:25:in `ignored_versions_for'
/home/dependabot/dependabot-core/common/lib/dependabot/config/update_config.rb:60:in `name_normaliser_for': undefined method `package_manager' for #<Array:0x0000558a3e85ae80> (NoMethodError)
```

**Comment by Nagyonkrisztina** [comment]
> ```
> Traceback (most recent call last):
>         1: from /home/dependabot/dependabot-core/common/lib/dependabot/config/update_config.rb:25:in `ignored_versions_for'
> /home/dependabot/dependabot-core/common/lib/dependabot/config/update_config.rb:60:in `name_normaliser_for': undefined method `package_manager' for #<Array:0x0000558a3e85ae80> (NoMethodError)
> ```

**Comment by dependb** [comment]
Sure @mattt , Here is a detailed description of my action. 
I am running dependbot on a private repository inside BitBucket. 
When I don't have a depndabot.yml file in my repository, It was able to raise pull requests (was working fine).
But now, I have added a dependabot.yml file in my repository (essentially the config file (dependabot.yml) is not processing out and breaking the code). 
Below is the piece of code which manage the configuration file handling 
```
# fetching the config file
config = Dependabot::Config::FileFetcher.new(source: source, credentials: credentials)
# parsing the fetched file
cfile = Dependabot::Config::File.parse(config.config_file.content)
#  returns a config based object from parsed file adding ignore conditions if any mentioned in the config file 
config_objectified = cfile.update_config(package_manager)

iversions = config_objectified.ignored_versions_for(dependencies_objects_array)

```

the iversions object is later used to do the updates according to dependabot.yml file.

**When check the function .igonred_versions_for  I found lot of gliches ** 

```
def ignored_versions_for(dependency, security_updates_only: false)
        normalizer = name_normaliser_for(dependency)
        dep_name = normalizer.call(dependency.name)

        @ignore_conditions.
          select { |ic| self.class.wildcard_match?(normalizer.call(ic.dependency_name), dep_name) }.
          map { |ic| ic.ignored_versions(dependency, security_updates_only) }.
          flatten.
          compact.
          uniq
      end

```

If you see the second line of this function - dependency.name is passed as argument to normalizer. Here dependency is an array so "dependency.name" doesn't exist. 

I don't know how is it used ? And my code is breaking over that point.

**Comment by jeffwidman** [comment]
Based on your other questions you're trying to run Dependabot from within a BitBucket repository. Which is great--we're happy you're getting value from Dependabot! 🍰 

However, it's not something we can spend engineering resources supporting... you'll have to figure this out yourself. I suggest starting with https://github.com/dependabot/dependabot-script which wraps `dependabot-core`. If you do figure out a bug, we're happy to review/merge PR's, but can't answer configuration / setup questions.
