### ISSUE TITLE
dependabot-core licence

### ISSUE THREAD

**Issue by damiang78** [dependabot/dependabot-core#5268]
Hi,

Sorry if this is not the right place to ask, but I didn't know how else to get in contact.

We would like to host an instance of Dependabot with GitLab privately at our workplace for the use of updating our project dependencies as well as identifying security vulnerabilities. Could you please clarify if the The Prosperity Public License 2.0.0 allows us to do this freely?

Thanks
Damian

**Comment by shjohnson-pi** [comment]
@damiang78 I believe you are specifically allowed to do that, as long as it's for internal use.

> # License
> We use the License Zero Prosperity Public License, which essentially enshrines the following:
> 
> * **If you would like to use Dependabot Core in a non-commercial capacity, such as to host a bot at your workplace, then we give you full permission to do so.** In fact, we'd love you to and will help and support you however we can.
> * If you would like to add Dependabot's functionality to your for-profit company's offering then we DO NOT give you permission to use Dependabot Core to do so. Please contact us directly to discuss a partnership or licensing arrangement.

From main readme: https://github.com/dependabot/dependabot-core#license

**Comment by jeffwidman** [comment]
As @shjohnson-pi helpfully pointed out (thanks!), this should be fine. See also https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100.

Note that the open source component of Dependabot is the version updater (this repo's library), not the security vulnerability identifier... that code is internal to GitHub so requires being on the GitHub platform. So you're welcome to stand up Dependabot somewhere else, just be aware you won't get security vulnerability alerts.
