### ISSUE TITLE
Can dependabot suggest patches for direct dependency?

### ISSUE THREAD

**Issue by varunzxzx** [dependabot/dependabot-core#5271]
Currently, dependabot suggests only the vulnerable package patch version(fix) but If I need to upgrade only the direct dependency which consumes the fix. 

- Is that possible with dependabot?
- Is this feature part of the backlog?

If we have a dependency tree like this
`A -> B -> C -> D`
Package D is vulnerable. Dependabot only tries to update package D in the lock file instead of updating package A which consumes the patched package D.

Few Examples:
https://github.com/varunzxzx/varunzxzx.github.io/pull/29
https://github.com/varunzxzx/varunzxzx.github.io/pull/33

**Comment by deivid-rodriguez** [comment]
I think we did some work to fix this for `npm`, but not sure about `yarn`. Hopefully someone else in the team can confirm.

**Comment by jeffwidman** [comment]
It will try to update package `D`, and if that forces upgrade of a parent dep in the tree, it will also for some ecosystems try to unlock that and bump that as well. If not required, then it won't... For a security update we're trying to limit the scope of the bump to be the least disruptive necessary to address the vulnerability, so we will never default to upgrading the parent unless it has to.

That said, this isn't supported for all ecosystems, but we're getting better over time. PR's are always welcome!

I'm going to close as I think this answer the question, and there's no further action needed here.

**Comment by skeet70** [comment]
@jeffwidman is there any documentation about what ecosystems this is supported for, and what the recommended workaround is where it isn't? We're seeing spates of build failures across our repos of Dependabot try to upgrade D and stating "security_update_not_possible", when one is if the parent dependency is upgraded. This is on Rust projects.
