### ISSUE TITLE
Bump terraform core version to 1.2.3

### ISSUE THREAD

**Issue by joberget** [dependabot/dependabot-core#5273]
https://github.com/dependabot/dependabot-core/blob/e749054566b45b5e0cd6d757df9b6f7e60dcb748/Dockerfile#L225

Is it possible to increase dependabot-core tf version to 1.2.3? Fixes an important bug in 1.2.1 also. https://github.com/hashicorp/terraform/pull/31091

**Comment by jakecoffman** [comment]
This is done [v0.194.0](https://github.com/dependabot/dependabot-core/pull/5282)
