### ISSUE TITLE
Dependabot NOT creating pull requests for parent pom version.

### ISSUE THREAD

**Issue by sri-al-cc** [dependabot/dependabot-core#5276]
Dependabot is NOT creating pull requests for parent pom version.

We are using maven 3.X as package manager. Our project uses a parent pom  version as below
     <parent>
         <groupId></groupId>
         <artifactId>xxxxx-base-java-webapp</artifactId>
         <version>2022.1.0</version>
		 <type>pom</type>
    </parent>

We have an several next versions of parent poms in nexus repository, but dependabot thinks an update is not needed. However it does work and create Pull requests  for regular dependencies specified with
    <dependencies>
    </dependencies>

dependabot.yml

version: 2
updates:
- package-ecosystem: maven
  directory: "/xxxx"
  target-branch: "develop"
  open-pull-requests-limit: 10

Log file
2022-06-14T18:42:49.0954590Z Parsing dependencies information
2022-06-14T18:42:49.1031289Z Checking if xxxxx-base-java-webapp  needs updating
2022-06-14T18:42:49.1031933Z No update needed for xxxxx-base-java-webapp

**Comment by jeffwidman** [comment]
I'm not 100% positive, but I _think_ this is resolved by a combo of https://github.com/dependabot/dependabot-core/pull/6491 and https://github.com/dependabot/dependabot-core/pull/6248, so closing. If for some reason I'm misunderstanding, please comment and we can re-open.
