### ISSUE TITLE
requirements.txt in wrong directory being updated

### ISSUE THREAD

**Issue by adamjstewart** [dependabot/dependabot-core#5299]
We would like to be able to test the minimum dependency versions our project supports in addition to testing the latest versions. This requires keeping a `requirements.txt` that is not updated by dependabot. I've tried placing this file in several directories (`/.github/requirements-min.txt`, `/requirements/min/requirements.txt`), but dependabot still updates this file even though it's configured to only search in `/requirements`.

**Package ecosystem**: pip

**Package manager version**: pip 22.1.2

**Language version**: python 3.7–3.10

**Manifest location and content before the Dependabot update**: https://github.com/microsoft/torchgeo/blob/main/.github/requirements-min.txt

**dependabot.yml content**: https://github.com/microsoft/torchgeo/blob/main/.github/dependabot.yml

**Updated dependency**: numpy from 1.17.2 to 1.22.0

**What you expected to see, versus what you actually saw**: since my `dependabot.yml` is configured to only update files in `/requirements`, I would not expect a file in `/.github` to be updated.

**Native package manager behavior**: N/A

**Images of the diff or a link to the PR, issue, or logs**: https://github.com/microsoft/torchgeo/pull/623

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by adamjstewart** [comment]
What I would really love to see would be the ability to specify exactly which files I want to update and which I don't. That would allow me to keep a `/requirements/min.txt` file that doesn't get updated in the same directory as the other `/requirements/*.txt` files I do want to see updated. But let's fix this bug first.

**Comment by adamjstewart** [comment]
We're also seeing security alerts on this file even though it's not in the specified directory: https://github.com/microsoft/torchgeo/security/dependabot

Is there any way to tell dependabot to ignore a certain file? Do we have to change the file ending to something else to confuse it?

**Comment by adamjstewart** [comment]
Looks like changing or removing the file extension is the only way to avoid dependabot for a specific file: https://github.com/microsoft/torchgeo/pull/646

**Comment by deivid-rodriguez** [comment]
I actually checked this using [dependabot's CLI](https://github.com/dependabot/cli) against https://github.com/microsoft/torchgeo/tree/ee6132041b465f39d516c72e8ee0b1338a592459 and got the expected results (no updates proposed for dependencies at `[.github/requirements-min.txt](https://github.com/microsoft/torchgeo/blob/ee6132041b465f39d516c72e8ee0b1338a592459/.github/requirements-min.txt). Maybe some recent change has actually fixed this?

**Comment by adamjstewart** [comment]
Are you able to reproduce this with older versions of dependabot CLI? Just want to make sure your setup indeed reproduces the issue I was seeing for older dependabot before confirming that it's fixed in newer dependabot.

**Comment by deivid-rodriguez** [comment]
Trying this with every single Dependabot CLI version just to confirm that the bug actually existed at some point seemed a bit too much, so I went ahead, forked your repo, rewinded it back to the commit where you had a `.github/requirements-min.txt` file, and clicked on "Check for updates", and no PR was created and no `.github/requirements-min.txt` file appeared in the list of tracked files in the "Insights > Dependency Graph > Dependabot" page. So it seems that this is actually fixed! 🎉

I'm going to close this as fixed but of course if you run into this again feel free to reopen. I could be perfectly missing something. Thanks!

**Comment by deivid-rodriguez** [comment]
> Trying this with every single Dependabot CLI version just to confirm that the bug actually existed at some point seemed a bit too much

Just to clarify, because I don't think I worded the above appropriately. I think running a bisection on this would be interesting and doable. We would need to run the CLI as provided in the `script/dependabot` script in this repo, and jump back and forth using `git bisect` running an update against your repo on each step. But it's a bit of work that may not be worth the effort.
