### ISSUE TITLE
Rust: support workspace inheritance

### ISSUE THREAD

**Issue by Eugeny** [dependabot/dependabot-core#5315]
Cargo nightly now supports workspace-level dependencies.

See:

* https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance
* https://github.com/rust-lang/cargo/issues/8415
* https://rust-lang.github.io/rfcs/2906-cargo-workspace-deduplicate.html

**Comment by Muscraft** [comment]
workspace inheritance was [stabilized](https://github.com/rust-lang/cargo/pull/10859) and is set to be released in Rust `1.64` on [September 22, 2022](https://forge.rust-lang.org/#current-release-versions)
