### ISSUE TITLE
[Gradle] Auto-rebase when there is a merge conflict does not work

### ISSUE THREAD

**Issue by nikosmoum** [dependabot/dependabot-core#5317]
**Package ecosystem**
gradle
**Package manager version**
gradle 7.4.2
**Language version**
Java 11
**Manifest location and content before the Dependabot update**
https://github.com/candlepin/candlepin/blob/master/dependencies.gradle
**dependabot.yml content**
https://github.com/candlepin/candlepin/blob/master/.github/dependabot.yml
**Updated dependency**
Does not matter, it happens with all of them
**What you expected to see, versus what you actually saw**
With this PR as an example (https://github.com/candlepin/candlepin/pull/3421) I would have expected dependabot to automatically rebase it when the PR had merge conflict (the merge conflict was specifically on the dependencies.gradle file), but that did not happen even after waiting for ~1 day. I had to manually comment with 'dependabot rebase' before dependabot actually rebased the PR.
**Images of the diff or a link to the PR, issue, or logs**
https://github.com/candlepin/candlepin/pull/3421

**Comment by Zen8** [comment]
- [ ] lLo

**Comment by nikosmoum** [comment]
This hasn't resolved itself. It never worked in the first place, and still doesn't work, so it is definitely not related to an a temporary outage.

**Comment by jeffwidman** [comment]
Do you have a P

**Comment by jeffwidman** [comment]
Do you have a more recent example of a PR that encountered this? Our job logs disappear after two weeks so it's tough to debug older PR's.

**Comment by nikosmoum** [comment]
I don't have a recent example right now, but once it happens again I'll post here

**Comment by nikosmoum** [comment]
@jeffwidman Hi Jeff, here is a recent example of this issue:
https://github.com/candlepin/candlepin/pull/3702 and https://github.com/candlepin/candlepin/pull/3703 got opened at the same time. 3702 got merged first, causing a merge conflict in 3703, which is not rebased automatically even now, after 3 days.

**Comment by jeffwidman** [comment]
Sorry, just now catching up on notifications. I didn't troubleshoot it. Auto-rebase generally happens when the manifest file changes, but there may be a bug in there, not sure...
