### ISSUE TITLE
Customizable commit message format

### ISSUE THREAD

**Issue by kinggoesgaming** [dependabot/dependabot-core#533]
As per my [discussion on Twitter](https://twitter.com/kinggoesgaming/status/1006282375267880960), dependabot tries to automatically detect the format of the commit messages based on the commit history of the repository. 

However in my case, (uuid-rs/uuid), we are transitioning from a freestyle formatting to a [conventional commit format](https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md), and want to start with dependabot commit messages.

**Comment by greysteil** [comment]
Thanks for creating this @kinggoesgaming.

OK, so the current setup is that Dependabot will automatically detect that you're using angular-style commits as soon as 30% of your last 30 commits use it (excluding merge commits and Dependabot's own commits). Are you saying that it will cause a problem for Dependabot to be doing the wrong thing during the transition?

FYI, the code for this is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb#L532-L540).

I could make this configurable, but if it's only going to be a very temporary problem is there a need to?

**Comment by kinggoesgaming** [comment]
hmm wasnt aware of the 30% ratio.... I might enforce this on dependabot last then (ignoring dependabot PRs in the meanwhile)

However configurable commit messages might be usable for people anyways, so rest is your call

**Comment by greysteil** [comment]
👍 - in that case I'm going to close, as I've only ever hear people ask for "angular-style commit messages" or "not angular style commit messages".

If you're reading this and want something different, please do open a new issue for it and I'm very happy to discuss!
