### ISSUE TITLE
Feature request / question expath dependencies

### ISSUE THREAD

**Issue by duncdrum** [dependabot/dependabot-core#534]
Hello dependabot team, 

I would like to add [expath](http://expath.org) dependency checking to dependabot, with the immediate use case of leveraging it for [exist-db](https://github.com/eXist-db/exist) application packages. 
I have looked through your contribution guidelines, and examples, and am pretty much ready to start. Before I do so I'd just like to feel the waters about any reservations your team might have about adding this feature, or any other insights into what you'd like to see for this to be accepted. 

Greetings

**Comment by greysteil** [comment]
Totally up for adding support. I’m on my phone so can’t dig in too much, but take a look at the open PR with a .NET template for an idea of how adding a new language / package manager works. Might make sense for me to put together a template for you?

**Comment by duncdrum** [comment]
@greysteil thanks for the swift response. I think your documentation has enough to get me going (my ruby might be a bit rusty). I ll see how far I get, and come back here with more questions should I get stuck.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
