### ISSUE TITLE
Dockerfile updated to pre-release (alpha) base image

### ISSUE THREAD

**Issue by hemberger** [dependabot/dependabot-core#5353]
**Package ecosystem**
Docker

**Manifest location and content before the Dependabot update**
https://github.com/smrealms/smr/blob/2e72c95ce1ea41c1810c0f3d2d732b8b50dff59c/Dockerfile
Location: `/Dockerfile`
Content: `FROM php:8.1.7-apache`

**dependabot.yml content**
https://github.com/smrealms/smr/blob/5c514f4803f8b01cdfad27b35dd31187d82bfc16/.github/dependabot.yml
```yml
version: 2

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
```

**Updated dependency**
Dependency name: php
From version: php:8.1.7-apache
To version: 8.2.0alpha3-apache

**What you expected to see, versus what you actually saw**
I expected to not see a Dependabot PR for an alpha version.

**Images of the diff or a link to the PR, issue, or logs**
PR: https://github.com/smrealms/smr/pull/1387
Dependabot log: https://github.com/smrealms/smr/network/updates/415198896

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```Dockerfile
FROM php:8.1.7-apache
```

**Comment by deivid-rodriguez** [comment]
Just tried this and got the expected result:

```
=> parsing dependency files
=> updating 1 dependencies: php

=== php (8.1.7-apache)
 => checking for updates 1/1
 => latest available version is 8.1.12-apache
 => latest allowed version is 8.1.12-apache
 => requirements to unlock: own
 => requirements update strategy: 
 => updating php from 8.1.7-apache to 8.1.12-apache

    ± Dockerfile
    ~~~
    1c1
    < FROM php:8.1.7-apache
    ---
    > FROM php:8.1.12-apache
    ~~~
🌍 Total requests made: '0'
```

Som recent change must've fixed this 🎉.

Thanks for reporting and sorry for the late reply!
