### ISSUE TITLE
[pub] Log the Dart / Flutter SDK version selected when running dependabot

### ISSUE THREAD

**Issue by jonasfj** [dependabot/dependabot-core#5396]
Diving through logs I found it hard to debug what Dart/Flutter version dependabot had used.
It might be nice if we can write that to log, that would help people trying to find out why their dependabot setup is acting up.

This is easily  the case if you don't have sufficient SDK constraints, in which case dependabot will also pick latest stable SDK.

**Comment by jonasfj** [comment]
While doing this we could also log a few other useful stings.

And check if it's running the flutter install script too many times, at-least we should double check logs, the one I looked at seemed a bit weird.

cc @sigurdm,

**Comment by jeffwidman** [comment]
Care to submit a PR?

**Comment by jeffwidman** [comment]
Addressed by https://github.com/dependabot/dependabot-core/pull/5748

@sigurdm Thanks for jumping on this so fast!
