### ISSUE TITLE
bin/dry-run.rb: not found

### ISSUE THREAD

**Issue by Nubilly** [dependabot/dependabot-core#5398]
good day,  
I'm trying to follow the steps in the readme but I can't seem to run the dry-run script. I'm very new to docker. 

![image](https://user-images.githubusercontent.com/36627448/180014428-cbfa247d-cb71-41a5-b515-9b05e469b38e.png)

**Comment by jeffwidman** [comment]
👋 welcome to docker.

In this case, we've already got a script that will get docker going for you automagically. So replace the `docker exec` command with `bin/docker-dev-shell` from within the folder where you git cloned the repo... ie, you're executing https://github.com/dependabot/dependabot-core/blob/main/bin/docker-dev-shell and that will spin up what you need from docker.

Full instructions: https://github.com/dependabot/dependabot-core#running-with-docker

Closing as I think this will resolve it, but if you still need help please comment and happy to re-open.

**Comment by Nubilly** [comment]
ah ok, that makes sense. thank you.
