### ISSUE TITLE
Funding with OpenCollective

### ISSUE THREAD

**Issue by welkie** [dependabot/dependabot-core#540]
I saw an issue for GitLab support and noticed some messages indicating funding is low right now, preventing a lot of time being spent on this to add features.

I suggest having the project join [OpenCollective](https://opencollective.com/). It's gaining a lot of prominence in funding open source projects. It offers more transparency and is more community-oriented than Patreon.

EDIT:

Did some more lurking and discovered Dependabot is more like like a SaaS business with an open source core (I love that model, btw!). I'm assuming your goal is to fund it via revenue from the business? If this is the case, I still recommend you consider also funding via open source crowdfunding.

I'm not the type to purchase SaaS services. I'd rather grab the code and self host it. But I have no problem throwing a few dollars at the projects I benefit from even if I self host them. I'm guessing that by adding this funding stream, you'd tap many more users willing to monetarily support the project.

**Comment by greysteil** [comment]
Hey @welkie,

Thanks for getting in touch with this! I hadn't thought about putting Dependabot on OpenCollective before, and had just been focussing on SaaS revenue, but it's an interesting idea. I need to think about it a little more, and I'm hopefully that SaaS revenue will keep growing quickly and that asking for donations won't be necessary, but I'll keep this in mind 🙂
