### ISSUE TITLE
Scan for Maven skin updates in src/site/site.xml

### ISSUE THREAD

**Issue by michael-o** [dependabot/dependabot-core#5419]
Maven Site Plugin uses `site.xml` to generate a site. A site can be skinned by adding a skin artifact to the site.xml. Skin can get outdated and cause issues like [this](https://issues.apache.org/jira/browse/MSITE-907). Therefore, scan `src/site/site.xml`, extract the skin coordinates, check Maven Central for a new version and create a PR.

**Comment by yeikel** [comment]
Relevant for you https://github.com/dependabot/dependabot-core#contributing-to-dependabot
