### ISSUE TITLE
Broken link in repository description

### ISSUE THREAD

**Issue by jsoref** [dependabot/dependabot-core#5442]
**Package ecosystem**
_any_

**Package manager version**
_any_

**Language version**
N/A

**Manifest location and content before the Dependabot update**
N/A

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**
Links should go to things that exist

> About
> 🤖 The core logic behind Dependabot's update PR creation. For product feedback see: https://github.com/github/feedback/discussions/categories/dependabot-feedback

**Native package manager behavior**
Usually they link to things that exist?

**Images of the diff or a link to the PR, issue, or logs**

https://github.com/dependabot/dependabot-core

<img width="494" alt="image" src="https://user-images.githubusercontent.com/2119212/181644928-be7a710f-b427-46f2-9cf5-90ca2d95f27e.png">

https://github.com/community/community/discussions/categories/dependabot-feedback

<img width="1806" alt="image" src="https://user-images.githubusercontent.com/2119212/181645132-066bf796-3433-4f74-a4f4-6b377662c555.png">

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment]
Thanks @jsoref for reporting! However, I'm not sure this is a broken link... looks to me more like there's simply no existing discussions there on this category, but it's possible to create some.

That said, I'm not sure if that is still the best place to submit product feedback... @bradify is there a better place we should link to? Or is that discussion category still the best place for public product feedback?

**Comment by jsoref** [comment]
The category list is pictured. If the category still existed, it'd be in the picture. It's gone.

**Comment by jurre** [comment]
Should probably go to https://github.com/community/community/discussions/categories/code-security, we used to have one dedicated to Dependabot, but looks like it was expanded to include all code security. I've updated the link, thanks
