### ISSUE TITLE
Can dependabot alerts support gradle?

### ISSUE THREAD

**Issue by lianup** [dependabot/dependabot-core#5449]
Hi team,

Do you have any plans to make dependabot alerts support gradle?

Currently only maven is supported in the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#supported-ecosystems-and-manifests-for-dependency-scope).

**Comment by jhutchings1** [comment]
👋🏻  Hi @lianup if you configure an Actions workflow which uploads information about the Gradle dependencies in use (like [this one](https://github.com/mikepenz/gradle-dependency-submission)), then you can get Dependabot alerts for Gradle.
