### ISSUE TITLE
Dependabot::DependencyFileNotParseable for valid GitHub-actions

### ISSUE THREAD

**Issue by Nikikuzi** [dependabot/dependabot-core#5453]
github actions file contains env section like this

```
env:
  DISPLAY: :99
```

and this is valid format

but due to colon sign DependencyFileNotParseable error throwing. With commented ' DISPLAY: :99' line parser working properly

**Comment by jeffwidman** [comment]
Hmm... that value is a string, so what happens if you quote the value only?
```
env:
  DISPLAY: ":99"
```

**Comment by Nikikuzi** [comment]
@jeffwidman Thanks. Working fine as workaround

**Comment by jeffwidman** [comment]
Great.

I'm going to close this--arguably it is a parsing bug, but probably in the parsing library that we use and not our code. And the workaround of quoting the string is straightforward. If you do want to fix this, you're welcome to submit a PR, but it's not something the core team will have cycles to spend time on.
