### ISSUE TITLE
Check if possible to build/install Ruby w/o Rdoc support

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5475]
https://github.com/dependabot/dependabot-core/runs/7646741836?check_suite_focus=true#step:3:5062

```
#7 463.0 Generating RDoc documentation
#7 463.2 Parsing sources...
#7 463.2   0% [ 1/917]  /usr/local/src/ruby-3.1.2/doc/NEWS-1.8.7
```

Notice this is step 1 of 917... so there's 917 steps to build docs, which probably no one looks at, but we build on every CI run.

We should check to see if there's a flag we can pass to skip building Rdoc when we build Ruby...

**Comment by jeffwidman** [comment]
@deivid-rodriguez do you happen to know off the top of your head if this is possible? I'm happy to research, but thought I'd ask first...

**Comment by deivid-rodriguez** [comment]
Yes! I think `./bin/ruby-install --system ruby $RUBY_VERSION -- --disable-install-doc` should do the trick!
