### ISSUE TITLE
Dependabot description does not match update (actually updating something completely different)

### ISSUE THREAD

**Issue by lkiesow** [dependabot/dependabot-core#5488]
**Package ecosystem**

Maven

**Package manager version**

Maven 3.x

**Language version**

Java 11

**Manifest location and content before the Dependabot update**

https://github.com/opencast/opencast/blob/bf01db6914db909397a156782ce2d42ca5bc1077/modules/db/pom.xml

**dependabot.yml content**

https://github.com/opencast/opencast/blob/bf01db6914db909397a156782ce2d42ca5bc1077/.github/dependabot.yml#L55-L59

**Updated dependency**

- MariaDB Connector/J vs Webpack

**What you expected to see, versus what you actually saw**

Dependabot created a pull request updating MariaDB Connector/J (Java/Maven dependency). After a `@dependabot rebase`, the dependency being updated is still the MariaDB library, but Dependabot's description of the commit is about updating Webpack which is not even in the same packaging ecosystem.

You can temporarily find the relevant pull request here: https://github.com/opencast/opencast/pull/4059/files
It may get updated next week.
But here is a screenshot of what's going on:

![Screenshot from 2022-08-06 17-21-28](https://user-images.githubusercontent.com/1008395/183255691-a600ce5c-cf6f-471e-9efd-4481904dc03c.png)

And the list of coommits:

![Screenshot from 2022-08-08 11-03-34](https://user-images.githubusercontent.com/1008395/183381932-b7b34e6d-1881-49f8-949a-f1e6bd41d52d.png)

**Comment by skaille** [comment]
[![Auto label Pull Requests](https://github.com/github/docs/actions/workflows/auto-label-prs.yml/badge.svg)](https://github.com/github/docs/actions/workflows/auto-label-prs.yml)

**Comment by skaille** [comment]
[]()
