### ISSUE TITLE
Use another label for security updates

### ISSUE THREAD

**Issue by nesl247** [dependabot/dependabot-core#552]
It would be great to have another label for security updates. Maybe `critical-dependencies` or `security-dependencies` or just a `security` label, not sure.

The purpose is to be able to see all the PRs in the organization that have a specific label that need to be looked at immediately.

**Comment by greysteil** [comment]
👍 on this. I've done all of the prep work in https://github.com/dependabot/dependabot-core/commit/642c374303b9d2221f38f22a4416cdf05f0c5c18.

I'm leaning towards just a `security` label. Will be relatively straightforward to change later if there's a better option.

**Comment by nesl247** [comment]
Sounds good to me. Thanks for the fast work!

**Comment by greysteil** [comment]
Great - done in https://github.com/dependabot/dependabot-core/commit/dd460e15ea23d0120732a1aa1888bf973b65d911, which is deploying now. Thanks for the feedback, and great to have you using Dependabot again! 🎉
