### ISSUE TITLE
Inconsistent order of entries in the updated `poetry.lock`

### ISSUE THREAD

**Issue by sigprof** [dependabot/dependabot-core#5530]
**Package ecosystem**
pip

**Language version**
CPython 3.8

**Manifest location and content before the Dependabot update**
https://github.com/sigprof/nix-devenv-qmk/blob/853d411176cc073f4d3b4e3f1c590b5f99346fff/nix/pyproject.toml
https://github.com/sigprof/nix-devenv-qmk/blob/f89118e1f8d1c2aa827525f2e53cca3f4e4ef8d8/nix/poetry.lock

**dependabot.yml content**
https://github.com/sigprof/nix-devenv-qmk/blob/853d411176cc073f4d3b4e3f1c590b5f99346fff/.github/dependabot.yml

**Updated dependency**
Bump [hjson](https://github.com/hjson/hjson-py) from 3.0.2 to 3.1.0.

**What you expected to see, versus what you actually saw**
In addition to updating the `hjson` version in `poetry.lock`, Dependabot also shuffled around the order of `[package.extras]` entries in unrelated packages:
https://github.com/sigprof/nix-devenv-qmk/commit/c0cc28ab3a807d1cd40698dcd90593275264a1ae

**Images of the diff or a link to the PR, issue, or logs**
https://github.com/sigprof/nix-devenv-qmk/pull/87

Looks like the underlying issue here is https://github.com/python-poetry/poetry/issues/6153; I'm also reporting that here, because an actual fix for that in the 1.1 branch of `poetry` may not happen.

**Comment by deivid-rodriguez** [comment]
Yes, it seems like this is an upstream issue, https://github.com/python-poetry/poetry/issues/6153, already fixed. From quickly reading the issue and stuff linked from there, it's still unclear when the fix will be released, and whether it will be backported to poetry 1.1.

So I was what's left to be discussed here in order to close this issue is:

* Is it worth to cherry-pick the fix to dependabot-core?
* Is it easy?

**Comment by mkniewallner** [comment]
Hi, we ended up releasing [1.1.15](https://github.com/python-poetry/poetry/releases/tag/1.1.15) which includes a backport of the fix, so once Dependabot uses the new version, the issue should be fixed.

**Comment by deivid-rodriguez** [comment]
Awesome, thanks!

Dependabot should be creating a PR for us soon to upgrade the dependency. I'll make sure to close this ticket once we merge that PR.

**Comment by jeffwidman** [comment]
@deivid-rodriguez FYI we switched [the default check frequency to weekly](https://github.com/dependabot/dependabot-core/pull/5435) to reduce noise. So for something like this where you _know_ there's an update we want to pull in, it's best to manually trigger an update check at https://github.com/dependabot/dependabot-core/network/updates.

I went ahead and did that, which as expected resulted in https://github.com/dependabot/dependabot-core/pull/5578
