### ISSUE TITLE
Python package compatible version update when not necessary

### ISSUE THREAD

**Issue by netsandbox** [dependabot/dependabot-core#5537]
**Package ecosystem**
pip

**Manifest location and content before the Dependabot update**
https://github.com/netsandbox/gh_dependabot_python_compatible_version/blob/5ce94f9679ff84b6fa95e831445ee70327f345fe/requirements.txt

**dependabot.yml content**
https://github.com/netsandbox/gh_dependabot_python_compatible_version/blob/5ce94f9679ff84b6fa95e831445ee70327f345fe/.github/dependabot.yml

**Updated dependency**
Update example-pkg-cloos requirement from ~=2.0.0 to ~=2.0.2

**What you expected to see, versus what you actually saw**
No dependabot update because version `2.0.2` is covered by the [compatible release version specifier](https://peps.python.org/pep-0440/#compatible-release) `~=2.0.0`

**Images of the diff or a link to the PR, issue, or logs**
https://github.com/netsandbox/gh_dependabot_python_compatible_version/pull/1

**🕹 Bonus points: Smallest manifest that reproduces the issue**
https://github.com/netsandbox/gh_dependabot_python_compatible_version

**Comment by deivid-rodriguez** [comment]
Hi! Thanks for reporting this!

You're asking for the `increase-if-necessary` versioning strategy, which `pip` does not yet support. Have a look at the docs for how the different versioning strategies work: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy.

This shouldn't be too hard to support though.
