### ISSUE TITLE
[question] why does dependabot avoid updating `content-hash` in `poetry.lock`?

### ISSUE THREAD

**Issue by natestemen** [dependabot/dependabot-core#5554]
I've noticed the PRs that dependabot opens on one of my repos using poetry updates versions as expected ([example](https://github.com/natestemen/mitiq-2/pull/20)), but it doesn't seem to be updating the `content-hash` property in the `metadata` section of the file.

It seems to me the content-hash replacement is happening in [`replace_content_hash`](https://github.com/dependabot/dependabot-core/blob/bd0d43e90d23e5cf9d8ce6d9bfcd1430fcd70997/composer/lib/dependabot/composer/file_updater/lockfile_updater.rb#L380-L395), but unfortunately there is not much in the way of info about why this is happening in the git blame/history. My guess is that this is done to avoid unnecessary merge conflicts, but this may be way off and I'd like to understand better.

Are there any downsides to having the content-hash be out of sync with the actual content?

**Comment by jurre** [comment]
Hey, tbh it sounds like a bug!

I have a clarifying question though, the code you linked to is for composer (php), it looks like you're experiencing this with Poetry (python)? 

The code for poetry lives here: https://github.com/dependabot/dependabot-core/blob/d0e5145348eeb88cc82d74cab20e548da674682e/python/lib/dependabot/python/file_updater/poetry_file_updater.rb#L88-L99

**Comment by natestemen** [comment]
Ah good point, I was looking in the wrong place. Thanks for finding the correct code.

In this case it seems like it may be a bug! I did find a commit https://github.com/dependabot/dependabot-core/commit/6f3064a5a267235e87b8ca1c1fd7a83729c31ab1 which seems to be where this code was originally added. The PR https://github.com/dependabot/dependabot-core/pull/635 even has a comment about this very issue.

**Comment by jeffwidman** [comment]
@natestemen I haven't looked at the code in detail, but based on what you found ☝️, my guess is that it's a 1-5 line fix... want to submit a PR?

**Comment by natestemen** [comment]
Jeff, I see you've assigned this to yourself. Sorry I haven't had time to implement a fix. If you work something out, I'd love to take a look at the PR..

**Comment by jeffwidman** [comment]
Sorry, I assigned it to be sure I responded to it, but not to actually pickup the PR... However, what's on my plate has shifted a bit so I won't have time to dig into this at all for a while, so I've unassigned it from myself. 

You (or anyone else interested) are more than welcome to pick it up.

**Comment by deivid-rodriguez** [comment]
@natestemen Can you share a public repository where this can be reproduced? I think normally poetry updates this hash, as the commit you mentioned and some PRs I've seen show, so maybe this is some very specific case, so it'd be nice to look at some manifest files that have the issue.

**Comment by natestemen** [comment]
Hey @deivid-rodriguez, sorry for the slow response, and apologies for the broken link in my original comment. I tried recreating the issue and unfortunately cannot. I will reopen this if I come across it again.

**Comment by deivid-rodriguez** [comment]
Thanks for getting back to us and checking this again 💯
