### ISSUE TITLE
Ability to select the project folder

### ISSUE THREAD

**Issue by kefzce** [dependabot/dependabot-core#556]
I have a similar project structure

```bash
├── [4.0K]  application
│   ├── [4.0K]  bin
│   ├── [4.0K]  config
│   ├── [4.0K]  public
│   ├── [4.0K]  src
│   ├── [4.0K]  templates
│   ├── [4.0K]  tests
│   ├── [4.0K]  translations
│   ├── [4.0K]  var
│   └── [4.0K]  vendor
└── [4.0K]  docker
    ├── [4.0K]  database
    ├── [4.0K]  nginx
    └── [4.0K]  php-fpm
```

and my composer.json file under the application folder, so @dependabot-bot can't bump my dependencies, i don't really like move composer.json from application to /, so think 
possibility to choose project folder in  https://app.dependabot.com/accounts/username/repos will be great idea

**Comment by greysteil** [comment]
Thanks for getting in touch @kefzce. You can select the directory you want Dependabot to operate on when you add a project:

![image](https://user-images.githubusercontent.com/1144873/41972011-7348fc3c-79de-11e8-8542-11e863f33e11.png)

Hopefully that solves your problem?

**Comment by kefzce** [comment]
@greysteil  Many thanks, it's true, I somehow missed it, but I did not see the possibility in the already created project to choose a directory, so if i create project first, create project on app.dependabot.com and after this dockerize project, move all project files into application folder, i should delete project from site, and recreate it to 
specify new directory e.g application, instead of being able to choose folder like on creation stage.

**Comment by greysteil** [comment]
Yes, exactly - unfortunately you've got to delete it and then recreate it, rather than editing. (I'd like to add editing of directory at some point soon!)

Great that that gives you what you need, though! 🎉
