### ISSUE TITLE
`@dependabot merge` command is unreliable

### ISSUE THREAD

**Issue by jeppester** [dependabot/dependabot-core#5566]
We experience that every so often dependabot will acknowledge a `@dependabot merge`-comment with a thumbs-up emoji, but NOT merge the PR.

Examples:
- https://github.com/abtion/muffi/pull/1119
- https://github.com/abtion/muffibook/pull/238
- https://github.com/abtion/muffi/pull/1327
- https://github.com/abtion/muffi/pull/1359
- https://github.com/abtion/muffi/pull/1345
- https://github.com/abtion/muffibook/pull/340
- https://github.com/abtion/muffibook/pull/356
- https://github.com/abtion/rails-template/pull/1553
- https://github.com/abtion/rails-template/pull/1552
- https://github.com/abtion/rails-template/pull/1683
- https://github.com/abtion/design-system/pull/523

We are using a github action for posting the merge command, so it gets posted rather quickly after the PR is created.
My best guess is that there's some sort of race condition at play here.

Let me know if I need to post this issue elsewhere, I couldn't find a dedicated repository for the dependabot github comment interface.

**Comment by jeppester** [comment]
Here's another example:
https://github.com/abtion/muffibook/pull/238

**Comment by jeppester** [comment]
Happened again today with two PRs, but in a private project, so I can unfortunately not reference it.

**Comment by jeppester** [comment]
Happened again on a private project today

**Comment by jeppester** [comment]
Another occurrence:
https://github.com/abtion/muffi/pull/1327

**Comment by jeppester** [comment]
https://github.com/abtion/muffi/pull/1359#pullrequestreview-1233635335

**Comment by jeppester** [comment]
https://github.com/abtion/muffi/pull/1345

**Comment by deivid-rodriguez** [comment]
@jeppester Thanks for giving us some public examples of the problem, they will be useful once we get to this. However, can you edit your initial post instead and compile your list of examples there? That way we can use the helpful information they may provide us once we get to this, but we don't need to deal with all the notifications generated every time you post a new example.

**Comment by jeppester** [comment]
It's been nearly half a year without so much as a confirmation that I posted the issue in the correct repo.

I hope you can understand why I felt a like I had to come back and add more examples every now and then, to show that this issue was not just some one-off problem. It happening for months before I stopped seeing it like that myself and eventually decided to report it.

I don't want to be rude, so I'll stop bugging you with it. 

Given the lack of reports from other user, and the understandable lack of concern from you because of that, I must say I'm losing my hope that this will ever get addressed, there are probably more important problems to solve.

**Comment by deivid-rodriguez** [comment]
I'm so sorry we failed to give you a proper response here, and we really appreciate that you care to come over here, report an issue and provide us with examples. I _think_ there's some work going on regarding the `merge` command so there may be updates here in a bit, I'll keep you posted if/when I know more!

**Comment by bewuethr** [comment]
FWIW, this (confirmation with emoji, but then no merge) happens to us all the time. We use `squash and merge`, but the symptom is the same.

For a while, we thought a check that makes sure a to-do list in the PR description being triggered by the comment with the command somehow prevented the merge, but that wasn't it.

**Comment by deivid-rodriguez** [comment]
Is this still a problem? If there are any issues with merging, Dependabot should now be explaining them by posting a comment in the PR.

Although, any fixes/issues related to this won't lie in the dependabot-core repository. This repository is only responsible for the creation of the PRs themselves, but not with other functionality like `@dependabot` comments.

Because of this, in this particular case, it's better to open a [support request](https://support.github.com), so that this is properly triaged internally. So let me close this ticket based on that.

If this is still happening and you do create the support ticket, please do mention this issue and any example PRs that show the problem.

Thanks so much!

**Comment by jeppester** [comment]
@deivid-rodriguez Since when has dependabot explained failed merges?
Last time I had this problem was a couple of weeks ago.

While I'm happy to get some guidance on what to do next, it would have nice to have gotten this guidance more than a year ago when I first posted, and directly asked if I posted the right place.

**Comment by deivid-rodriguez** [comment]
@jeppester I think not long ago, but I'd say longer than two weeks ago, so there's something fishy going on here.

Regarding conflicting instructions, you are totally right, and I apologize for that. We have not had a consistent policy regarding what to do with issues that don't fall in dependabot-core, but are still real issues with Dependabot's service at GitHub.

I've been recently directing this kind of issue to Github's support recently, but I failed to notice that I had implicitly "accepted" this issue in dependabot-core before. Again, my apologies.
