### ISSUE TITLE
Make semantic-release commit messages compatible with @commitlint/config-conventional

### ISSUE THREAD

**Issue by squirly** [dependabot/dependabot-core#560]
One of the more popular commit linters for semantic-release, `@commitlint/config-conventional` following the [`Conventional Commits Guideline`](https://conventionalcommits.org/), enforces that scopes be lowercase.
https://github.com/marionebl/commitlint/blob/d636811b4537904231c483a05e91aaf96deb7f6e/%40commitlint/config-conventional/index.js#L6

### Error in My Project, [`@squirly/di`](https://github.com/squirly/di)
```
😞   Errors found with commit 6a91ae3
💬   build(devDeps): bump prettier from 1.13.5 to 1.13.7

Bumps [prettier](https://github.com/prettier/prettier) from 1.13.5 to 1.13.7.
- [Release notes](https://github.com/prettier/prettier/releases)
- [Changelog](https://github.com/prettier/prettier/blob/master/CHANGELOG.md)
- [Commits](https://github.com/prettier/prettier/compare/1.13.5...1.13.7)

Signed-off-by: dependabot[bot] <support@dependabot.com>
✖   scope must be lower-case [scope-case]
✖   found 1 problems, 0 warnings
```
Error from: https://circleci.com/gh/squirly/di/64#action-103

## Breaking Change In `dependabot-core`

Recently dependabot was updated to add scopes to semantic-release commits:
https://github.com/dependabot/dependabot-core/blob/ef1b3218c3a28c676a8131cb07cf1b8312a19a4c/lib/dependabot/pull_request_creator/message_builder.rb#L124-L125
Changed in: https://github.com/dependabot/dependabot-core/commit/ef1b3218c3a28c676a8131cb07cf1b8312a19a4c#diff-527fb27a2c1732e920d070c442a83a77R124

## Fix

Since it is in the in the interest of `dependabot-core` to reach broad interoporability, conforming to the most restrictive standards is necessary.

A simple fix, is to change the `"devDeps"` scope to `"deps-dev"`.

**Comment by greysteil** [comment]
Thanks for the fix!

**Comment by greysteil** [comment]
FYI, fix is deploying now. Thanks again for this, and sorry for the break.
