### ISSUE TITLE
Incompatible with github rebase feature.

### ISSUE THREAD

**Issue by MartinX3** [dependabot/dependabot-core#5626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

8.19.1

### Language version

18.8.0

### Manifest location and content before the Dependabot update

N/A

### dependabot.yml content

version: 2
updates:
    # Fetch and update latest `npm` packages
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
          time: '00:00'
      open-pull-requests-limit: 10
      reviewers:
          - martinx3
      assignees:
          - martinx3
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
    # Fetch and update latest `github-actions` pkgs
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: daily
          time: '00:00'
      open-pull-requests-limit: 10
      reviewers:
          - martinx3
      assignees:
          - martinx3
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope

### Updated dependency

N/A

### What you expected to see, versus what you actually saw

I just click the "rebase" button in the PR, because it has not merged changes.
By default it adds a merge commit with my username as author.
But also if I manually switch the action to ust rebase it replaces the commit author with my own github user.
The authored author is still dependabot.
This and also the issue, that dependabot can't rebase PR's or recreate them from scratch (even if I use the depdendabot commands) breaking the behaviour of dependabot.

I expect a rebase.

I get
```
Looks like this PR has been edited by someone other than Dependabot. That means Dependabot can't rebase it - sorry!

If you're happy for Dependabot to recreate it from scratch, overwriting any edits, you can request @dependabot recreate.
```

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

N/A

### Smallest manifest that reproduces the issue

N/A

**Comment by jeffwidman** [comment]
What happens if you do `@dependabot recreate` on that PR?

Is this happening on a public repo or a private one?

**Comment by MartinX3** [comment]
The bot gives it a thumbs up
But does nothing

The repo is public

**Comment by jeffwidman** [comment]
> The repo is public

Okay, what is the PR where this is happening? Please help us save time here by linking directly to the comment where you left the comment that the bot gave a 👍 but then did nothing...

**Comment by MartinX3** [comment]
Oh, yes of course

https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/272#issuecomment-1236962903
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/272#issuecomment-1236985710
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/272#issuecomment-1236992957
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/272#issuecomment-1236993387

I did need to force push it myself

Here is another one
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/270#issuecomment-1236962400
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/270#issuecomment-1236985907
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/270#issuecomment-1236992905
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/270#issuecomment-1236993448

And another one
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/269#issuecomment-1236941334
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/269#issuecomment-1236956971

**Comment by jurre** [comment]
That's just how the rebase functionality works, right? If you rebase a commit, you amend the diff in that commit, and GitHub will add you as an author to the commit because of that. Dependabot will then also not rebase those commits, because it sees that they have been manually amended, and it leaves a comment explaining this:

> Looks like this PR has been edited by someone other than Dependabot. That means Dependabot can't rebase it - sorry!

**Comment by MartinX3** [comment]
@jurre but I just use the github webui button called "rebase".
Should I next time just wait until dependabot rebased the PR somewhere in the future instead of using githubs own advertised feature?

**Comment by jeffwidman** [comment]
Yeah, this is a bit of a "gotcha", but unfortunately it's working as expected. 

The first issue here is that the GitHub rebase doesn't regenerate the lockfiles, it only does the git rebase... versus when Dependabot rebases things, it actually regenerates the lock files in case anything it's rebasing on top of impacted the lockfiles.

Secondly, Dependabot is aware and _could_ override the committer back to Dependabot as part of a force rebase... but we can't guarantee that's what the user wants... they may want to manually have changed things and not want Dependabot imposing it's own will. So Dependabot does the safe thing and leaves a warning comment and then leaves it up to the user what to do. In your case, a simple `@dependabot recreate` is all you need to do.

And yeah, when you do `@dependabot rebase` or recreate, you then have to wait for the background job to kick in and execute... it can take a few minutes to a few hours depending on how busy our job queues are.

**Comment by MartinX3** [comment]
@jeffwidman but would be `@dependabot rebase force` a nice feature?

**Comment by jeffwidman** [comment]
That's what `@dependabot recreate` does

**Comment by MartinX3** [comment]
Here I needed to repopen the PR, because dependebot froze.
https://github.com/Rad-Touristik-Club-Koln-e-V-1972/Rad-Touristik-Club-Koln-e-V-1972.github.io/pull/293

I did let dependabot rebase 7 PR's at the same time and somehow with the 7th it hang up.
