### ISSUE TITLE
github links in release notes cause timeline notification spam

### ISSUE THREAD

**Issue by ljharb** [dependabot/dependabot-core#5639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

expected no timeline notifications

saw thousands of notifications, and it seems to be infinitely increasing: https://twitter.com/bitandbang/status/1567066927893303296 → https://twitter.com/NicoloRibaudo/status/1567065351522848768 → https://github.com/tc39/ecma262/pull/2819

**Comment by deivid-rodriguez** [comment]
Thanks for letting us know about this @ljharb! We're aware how disrupting this kind of timeline references can be.

We have identified the issue as specific to releases including the `org/repo#pr` shortcut in their changelog or release notes, and we're already working on a fix.

I will post further updates once this is resolved!

**Comment by ljharb** [comment]
Thanks!

**Comment by deivid-rodriguez** [comment]
Just confirming that the fix was deployed! :)

**Comment by jnyrup** [comment]
Did this regress?

E.g. https://github.com/microsoft/vstest/pull/15720 now has +19000 items, which practically makes the timetable unusable.
