### ISSUE TITLE
Bump Python to `3.10.7`

### ISSUE THREAD

**Issue by Kurt-von-Laven** [dependabot/dependabot-core#5653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We receive [the following error message](https://github.com/ScribeMD/rootless-docker/network/updates/454220323) because our [`pyproject.toml`](https://github.com/ScribeMD/rootless-docker/blob/e80c4157bf2137d1080bc86b00550983f74bd2d1/pyproject.toml#L22) and [`poetry.lock`](https://github.com/ScribeMD/rootless-docker/blob/689bceea9c233dceda80f134e57ea24afafe772c/poetry.lock#L280) specify Python 3.10.6.

```
Dependabot failed to update your dependencies because there was an error resolving your Python dependency files.

Dependabot encountered the following error:

Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x00005633a6c97630 @requirements=[[">=", #<Dependabot::Python::Version 3.10.6>], ["<", #<Dependabot::Python::Version 4.0.0.a>]]>]]'.

Currently, the following Python versions are supported in Dependabot: 3.10.5, 3.10.4, 3.10.3, 3.10.2, 3.10.1, 3.10.0, 3.9.13, 3.9.12, 3.9.11, 3.9.10, 3.9.9, 3.9.8, 3.9.7, 3.9.6, 3.9.5, 3.9.4, 3.9.2, 3.9.1, 3.9.0, 3.8.13, 3.8.12, 3.8.11, 3.8.10, 3.8.9, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.13, 3.7.12, 3.7.11, 3.7.10, 3.7.9, 3.7.8, 3.7.7, 3.7.6, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.15, 3.6.14, 3.6.13, 3.6.12, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.10, 3.5.8, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3.
```

Python 3.10.7 has been released, and [the `ubuntu-22.04` GitHub-hosted runner comes with Python 3.10.6 pre-installed](https://github.com/actions/runner-images/blob/e295cb5837908738b0beabaa729425846fab9afc/images/linux/Ubuntu2204-Readme.md#python), so we are reluctant to downgrade to Python 3.10.5 at this point.

**Comment by jeffwidman** [comment]
Agreed, we should bump straight to `3.10.7`. Want to submit a PR?

**Comment by Kurt-von-Laven** [comment]
Sure thing; I opened the linked PR. Please let me know if you have any feedback. I aped #5333.
