### ISSUE TITLE
Wrong dependency graph

### ISSUE THREAD

**Issue by weddige** [dependabot/dependabot-core#5659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

/requirements.txt

### What you expected to see, versus what you actually saw

I have the dependency sslyze in the requirement.txt. In the dependency graph it is linked to https://github.com/secworks/sslyze, which is the wrong repository. The correct reposiroty would be https://github.com/nabla-c0d3/sslyze.

![image](https://user-images.githubusercontent.com/1119426/189143569-0b362f8e-b087-4e05-babf-80e9ecfa8421.png)

### Smallest manifest that reproduces the issue

```
sslyze
```

**Comment by weddige** [comment]
See also https://github.com/secworks/sslyze/network/dependents?dependent_type=REPOSITORY

**Comment by jeffwidman** [comment]
Thanks @weddige this appears to me to be a legit bug given that https://pypi.org/project/sslyze/ points directly to the https://github.com/nabla-c0d3/sslyze repo.

However, the code that generates the dependency graph output isn't actually in `dependabot-core` but actually in a separate service whose code isn't open source. It's also run by a different team, so I've inquired internally to figure out how they'd like to handle this bug report. Sorry, I'm sure this is confusing looking at it from an external perspective.

**Comment by weddige** [comment]
Thank you for the update and forwarding the information.

**Comment by abdulapopoola** [comment]
Closing as stale
