### ISSUE TITLE
Add option to not create PRs when a new repo is added

### ISSUE THREAD

**Issue by cbautista1002** [dependabot/dependabot-core#568]
My company just signed up for the unlimited plan. We'd like to add all of the repos at once but if we do then 5 PRs will be created for every single repo which will be overwhelming. Is there a way to select "All repositories" but not have PRs automatically created until someone explicitly bumps a repo?

We have dozens of repos and are slowly introducing Dependabot to the repos that makes sense. But at the same time we don't want to have to add a repo one at a time as people request. Adding a repo requires GitHub admin status which few people have. So ideally the GH admin would be able to add all repos without causing bumps. Then individual repo owners can bump when they're ready.

**Comment by greysteil** [comment]
Hi @cbautista1002,

Thanks for using Dependabot, and for getting in touch.

You can grant Dependabot access to all of your repos on GitHub without it kicking off bumping runs for them - you do that from the configure button [here](https://github.com/apps/dependabot). For Dependabot to actually start creating PRs against a repo that repo needs to be added manually in the Dependabot dashboard ([here](https://app.dependabot.com)), which any of your employees with write access to the repo will be able to do.

Hopefully that's what you need? It's a nice validation for me, too - I've been holding off on any kind of "auto-enrolling" functionality for exactly this reason!

**Comment by cbautista1002** [comment]
Thanks @greysteil! I see what you mean and I think I'm good to go! I need to work with one of my co-workers who has GH admin rights to be sure. With tomorrow's holiday it's going to take a couple of days, but I'll post here as soon as I have a more definitive answer. Thanks again.

**Comment by greysteil** [comment]
Great! Have a fantastic July 4th!
