### ISSUE TITLE
See if we can leverage `composer` `2.4`'s new `bump` feature

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5719]
Composer 2.4 added a new `bump` option: https://blog.packagist.com/composer-2-4/

We may be able to leverage this a bit more directly for bumping versions in `composer.json`. See the caveats about doing it for libraries on that blog post.

See also:
* https://github.com/dependabot/dependabot-core/issues/5721

**Comment by driskell** [comment]
Just to put here what was mentioned elsewhere. I think the bump just increases the json to the currently installed version so doesn’t update anything except the minimum requirement and only updates it what’s already installed

**Comment by jeffwidman** [comment]
Ah yeah, looks like you're right: https://php.watch/articles/composer-bump

They're adding [a `--dry-run` flag](https://github.com/composer/composer/pull/11047) too, but regardless doesn't really add any value for us.

**Comment by jeffwidman** [comment]
And thanks again @driskell really appreciate you swinging by to dispense some knowledge.
