### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#572]
Originally suggested in https://github.com/dependabot/feedback/issues/76.

**Comment by camdez** [comment]
What's the latest here? Just looking for someone to do the work, or is something in flight? Happy to help!

**Comment by devn** [comment]
Same, I'm new to dependabot, but I am happy to help in any way I can.

**Comment by alexisvincent** [comment]
What is the process to get support for Clojure?

**Comment by gphilipp** [comment]
https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems
<img width="910" alt="image" src="https://user-images.githubusercontent.com/56603/120471365-86464a00-c39c-11eb-8d19-5c6290bbcf51.png">

**Comment by steffan-westcott** [comment]
Congratulations to @0tza for getting [some funding from Clojurists Together](https://www.clojuriststogether.org/news/q3-2021-funding-announcement/) 😀 I hope the situation outlined in the post above improves and community contributions for Clojure support will be accepted in the near future.

**Comment by greysteil** [comment]
Cc @asciimike @hmarr ☝️

**Comment by asciimike** [comment]
Congrats on the funding, and thanks to the folks who picked Dependabot as an area of investment. We're glad to see the community invest in security!

As for the above, as stated, the main issue has been that we lack the domain expertise to support the full breadth of contributed ecosystems. We have been working with another popular ecosystem on a closer partnership experience where they can provide that level of support, and would consider a similar relationship with the Clojure community. At a minimum, we are asking for two folks who will commit to being active in this repo if/when Clojure questions come up (we will likely tag you); otherwise, we don't think we can provide an acceptable level of support for devs when they have questions.

**Comment by danielcompton** [comment]
Hi @asciimike! I’m a recent ex-Hubber, admin for the Clojure community Maven repo Clojars, and the secretary of Clojurists Together which funded @0tza for this work. I’m happy to help on providing a close relationship with GitHub here 😀

**Comment by asciimike** [comment]
@danielcompton @0tza I see that the project is listed as starting 1 Nov 2021; how firm is that date? We're starting to do quarterly planning and I want to get a rough idea of when we should start talking about this in more depth.

**Comment by tobias** [comment]
Hello @asciimike. I also am an admin for Clojars, the Clojure community Maven repository. I would be happy to provide a second set of eyes on any Clojure (& Clojure dependency ecosystem) questions.

**Comment by danielcompton** [comment]
> I see that the project is listed as starting 1 Nov 2021; how firm is that date? We're starting to do quarterly planning and I want to get a rough idea of when we should start talking about this in more depth.

What kind of timing works best for you? The paid work was planned to be started in November, but we can also do development/prep work/coordination/etc. before then?

**Comment by asciimike** [comment]
@danielcompton I think Nov 1 is actually pretty good as we should be wrapping up one of our larger currently-in-flight projects by then and can focus on new ecosystems. I'll set myself a reminder to ping this thread in mid-October to pick this up again.

**Comment by gphilipp** [comment]
Hi @0tza, sounds like you should have started the work by now 🤞. If there are conversations happening, where can we find them and contribute?

**Comment by 0tza** [comment]
I have started to move all the conversations to https://clojurians.slack.com/archives/C02PZRZPC4R
See you all there 👋🏽

**Comment by exvuma** [comment]
@0tza if we don't have access to that workspace how should we request access?

**Comment by 0tza** [comment]
> @0tza if we don't have access to that workspace how should we request access?

That's a public channel [on clojurians slack](https://clojurians.slack.com). it should be open to anyone.
