### ISSUE TITLE
Switch from deprecated `sentry-raven` to `sentry-ruby` in `updater`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5722]
The `updater` code currently uses `sentry-raven`: https://github.com/dependabot/dependabot-core/blob/9ee5b41845c5f404322cbd48a12370379ffded96/updater/Gemfile#L26

However, this lib has been deprecated by Sentry in favor of `sentry-ruby`. 

Migration guide here: https://docs.sentry.io/platforms/ruby/migration/

**Comment by abdulapopoola** [comment]
This is now done; thanks to @JamieMagee !
