### ISSUE TITLE
Question regarding GHE releases

### ISSUE THREAD

**Issue by stulle123** [dependabot/dependabot-core#5726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi there,

This is just a general question:

How long does it take approximately until a merged PR in this repo will make it into the GHE release?

Thanks,

stulle123

**Comment by stulle123** [comment]
@jeffwidman

**Comment by jeffwidman** [comment]
Thanks again for your work on https://github.com/dependabot/dependabot-core/pulls?q=is%3Apr+is%3Aclosed+author%3Astulle123, I have a hunch that this isn't actually a general question but more specifically you're wondering when those will land on a GHE instance near you? 😄 

I don't know, but @landongrindheim might be able to point you to the right docs for release cadence and know what release those PR's will likely land in...

**Comment by landongrindheim** [comment]
Changes here typically will not be pushed to GHES appliances without action being taken by the administrators of those appliances. That's typically done via upgrading GHES versions or by manually syncing GitHub Actions.

GHES releases are generally done quarterly, though there are intermittent patch releases. If this is functionality that your organization needs, I'd recommend reaching out to support and they can walk through syncing GitHub Actions 🙂
