### ISSUE TITLE
Emit a log message when applying ignored versions in the current job

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When the current job is affected by `ignored_versions`, let's emit a log:

* What ignored_versions are configured?
* How many candidate versions were there before/after applying ignored versions? (maybe??)

Alternative: only output if the candidate set is reduced to zero? (like `Dependabot::AllVersionsIgnored`)

Related:
https://github.com/dependabot/dependabot-core/pull/1849

**Comment by jeffwidman** [comment]
This is a great first issue if anyone is interested. There's an example of how to do this here:
* https://github.com/dependabot/dependabot-core/pull/6601

**Comment by abdulapopoola** [comment]
This is a duplicate of an internal issue that is being worked on.
