### ISSUE TITLE
Terraform modules in Azure Devops repos 404 due to incorrect fetch path

### ISSUE THREAD

**Issue by AurimasNav** [dependabot/dependabot-core#5756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

terraform

### What you expected to see, versus what you actually saw

I've expected to have PR for terraform module version update created, instead I get an error.
```json
  :host          => "dev.azure.com"
  :local_address => "172.17.0.2"
  :local_port    => 33882
  :path          => "/aurimasnavardauskas/terraform/_git/tf-modules.git/info/refs"
  :port          => 443
  :reason_phrase => "Not Found"
  :remote_ip     => "13.107.42.20"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
```
the correct path in azure devops repos should be `/aurimasnavardauskas/terraform/_git/tf-modules/info/refs` without the appended `.git` to the `tf-modules` repository name.

I am aware that this project is not responsible for azure devops dependabot task implementation, however I've already reported this issue there and after investigation it seems that the issue is in dependabot-core rather than the azure devops task implementation.
The related issue and investigation: https://github.com/tinglesoftware/dependabot-azure-devops/issues/347

### Images of the diff or a link to the PR, issue, or logs

build logs:
https://dev.azure.com/aurimasnavardauskas/dependabot/_build/results?buildId=6&view=logs&j=42a276bf-7749-5ba3-b33d-570bc5e297a3&t=07ac1df1-2752-5bc5-77e1-e8fdbfbf1b81

### Smallest manifest that reproduces the issue

1. `terraform` project contains:
    - Teraform "module" repository:  https://dev.azure.com/aurimasnavardauskas/terraform/_git/tf-modules
2.  `dependabot` project contains:
    - Repo scanned by dependabot, terraform "deployment" code which utilizes the module from repo mentioned above: https://dev.azure.com/aurimasnavardauskas/dependabot/_git/iac-tf
    - The repo where dependabot pipeline is defined:  https://dev.azure.com/aurimasnavardauskas/dependabot/_git/dependabot

**Comment by jeffwidman** [comment]
Thanks providing a reproducible example in a public repo in your report.

Looks like @mburumaxwell found [some useful debugging breadcrumbs](https://github.com/tinglesoftware/dependabot-azure-devops/issues/347#issuecomment-1251154358):
> At some point dependabot is adding a `.git` to the URL which Azure does not serve. In the [logs](https://dev.azure.com/aurimasnavardauskas/dependabot/_build/results?buildId=5&view=logs&j=42a276bf-7749-5ba3-b33d-570bc5e297a3&t=07ac1df1-2752-5bc5-77e1-e8fdbfbf1b81&l=1177) you will see the path `aurimasnavardauskas/terraform/_git/tf-modules.git/info/refs` which if you used on Postman/Insomnia would result in a `404` too. However, if you change the path to `aurimasnavardauskas/terraform/_git/tf-modules/info/refs` (remove the `.git`), it returns `200` which is what we expect.

I don't know how soon we can get to this, if you want to take a crack at it yourself it should be fairly straightforward to use [the `dry-run` script](https://github.com/dependabot/dependabot-core#dry-run-script). I _highly_ recommend running it within docker (see the section just above dry run). Then all you'd need to do is add a few `puts` statements to track down where in the Terraform-specific logic we're appending that code... 

In general we've found there's a 50/50 chance with private providers that they aren't following the Terraform API spec, see https://github.com/dependabot/dependabot-core/issues/5707 for example.
