### ISSUE TITLE
Dependabot no longer updating my repo

### ISSUE THREAD

**Issue by adamjstewart** [dependabot/dependabot-core#5798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip 22.2.2

### Language version

Python 3.7–3.10

### Manifest location and content before the Dependabot update

All `*.txt` files in https://github.com/microsoft/torchgeo/tree/main/requirements should be maintained by dependabot

### dependabot.yml content

https://github.com/microsoft/torchgeo/blob/main/.github/dependabot.yml

### Updated dependency

In the last 5 days, there have been many new releases of our dependencies, such as 4 new Sphinx releases.

### What you expected to see, versus what you actually saw

We have not seen any new PRs opened by dependabot in the last 5 days. I would expect new PRs for things like Sphinx and mypy and other packages that have had new releases.

**Comment by adamjstewart** [comment]
Looks like it's magically working again, false alarm

**Comment by jeffwidman** [comment]
Thanks for circling back. Not sure why it's failing... you can always check the logs here https://github.com/microsoft/torchgeo/network/updates and manually trigger a new job run if it looks like a transient network error etc

**Comment by adamjstewart** [comment]
Thanks for the debugging tip! I just noticed a couple new dependency releases, I'll check that out if it isn't triggered automatically.
