### ISSUE TITLE
dependabot stuck on `Checking now` for more than 12 hours

### ISSUE THREAD

**Issue by junwei-lii** [dependabot/dependabot-core#5810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

2.3.14

### Language version

Ruby 2.7.6

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

### What you expected to see, versus what you actually saw

Expected: pr created for outdated gems
Actual: dependabot stuck on `Checking now` for more than 12 hours

### Native package manager behavior

`bundle install` successfully

### Smallest manifest that reproduces the issue

private repo, can't share 🙏 

it just stuck there, and we don't have a way to collect other information

![image](https://user-images.githubusercontent.com/103160672/192921408-e72919bb-b3c5-4c47-b031-a9e1413a3199.png)

**Comment by jeffwidman** [comment]
Given the `!` sign, it's likely hitting some kind of error. 

Does it succeed if you run with the `dry-run` script? https://github.com/dependabot/dependabot-core#dry-run-script

Unfortunately, without more information, it's not really actionable for us here on `dependabot-core`... it's just as likely going to be a database flake (not something for this issue tracker) as a possible code bug (which belongs in this issue tracker). Feel free to file a support request, but I suggest first trying the dry run script and see if that surfaces any clues.

**Comment by junwei-lii** [comment]
sorry about the late response, it's still stuck on "checking now"

let me figure out what do you mean by "the dry-run script", will feedback later, thanks for your time 🙏 

btw, could you pls clarify how to "file a support request" ? I haven't done this before

**Comment by junwei-lii** [comment]
having fun debugging with `bin/dry-run.rb`  :D
thanks

**Comment by junwei-lii** [comment]
hi,  it took hours to finish checking 195 updates, and everything looks good

any suggestion on how to restart the dependabot checking job in `Dependency graph` ?
<img width="941" alt="image" src="https://user-images.githubusercontent.com/103160672/194023096-1be9f755-bf1c-4315-8f5b-6ac2e2675f84.png">

**Comment by junwei-lii** [comment]
One more thing to mention:  in our Gemfile, we lock the bundler version to 2.3.22, but it seems dependabot is using 2.3.14 , which causes the checking failed

I'm not sure whether this is an issue for `dependabot`, in my opinion bundler version shouldn't be a checking blocker

Any thoughts/comments on this ? 🙇 

![image](https://user-images.githubusercontent.com/103160672/194197414-66d4fd61-831b-47af-93c8-6ed338ccad92.png)

**Comment by jeffwidman** [comment]
@junwei-lii I'm confused... you mention previously that this is stuck on `Checking now` but then you now show an error... are these unrelated issues or did the `Checking now` go away and this error show up instead?

Regardless, ☝️  should probably be on a separate issue from the one stuck in `Checking now`... and this ticket resolved if `Checking now` is gone... 

Also, before you file a new ticket, can you please click the `Check for updates` button again? I literally _just_ deployed #5509 and #5513 and so that may fix what you're seeing here.

**Comment by junwei-lii** [comment]
> but then you now show an error
This is an error happened before(we made a workaround by lock bundler version to 2.3.14) , sorry about the misleading

**Comment by junwei-lii** [comment]
> Also, before you file a new ticket, can you please click the Check for updates button again? 

this is the issue, I don't have any button to click on

**Comment by junwei-lii** [comment]
> @junwei-lii I'm confused... you mention previously that this is stuck on `Checking now` but then you now show an error... are these unrelated issues or did the `Checking now` go away and this error show up instead?
> 
> Regardless, ☝️ should probably be on a separate issue from the one stuck in `Checking now`... and this ticket resolved if `Checking now` is gone...
> 
> Also, before you file a new ticket, can you please click the `Check for updates` button again? I literally _just_ deployed #5509 and #5513 and likely that affects what you're seeing here, although unclear if that resolved the error or is resulting in the error. But re-running to confirm before you file a new ticket will save us both time.

tested with pet project, bundler version restriction should be resolved now
pending issue is "how to reset the checking"

**Comment by jeffwidman** [comment]
@junwei-lii I suspect this is a case where the Bundler run takes a long time... you mentioned hours for example. However the job should have timed out, but clearly didn't, so we can try clearing it for you. You didn't post the repo link, and I suspect it's a private repo, so please file a support ticket about your account and include the actual repo URL. If it's a private repo, then don't file a community issue--those are public to the world. More info on filing tickets here: https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket

I'm going to close as there's nothing we can do here from the `dependabot-core` perspective, this is a one-off support issue.

**Comment by junwei-lii** [comment]
> so we can try clearing it for you

This is what I need 🙏 

> You didn't post the repo link, and I suspect it's a private repo

Yes, it's a private repo;

sorry about the bothering, I expect this issue should be handled by some kind of official organization, just didn't take time to figure out how to do it, because I find firing an issue is the most easy one to do

Thank you again for the bundler fix and the `bin/dry-run.rb` mode guide, they're pretty helpful 🙇 

And I'll read more carefully before firing an issue

**Comment by jeffwidman** [comment]
@junwei-lii BTW, thanks for being persistent on this. As someone may have commented on the internal ticket you filed, once you provided the proper info about which repo it was, we were able to identify a bug that was affecting thousands of  jobs from timing out properly... we got that fixed and a cleanup job is slowly clearing out the backlog... so your persistence and willingness to send the right info is making things better for a lot more repos than just yours. ❤️
