### ISSUE TITLE
Add option to scan effective pom when using Maven

### ISSUE THREAD

**Issue by gitaroktato** [dependabot/dependabot-core#5834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When we're running Dependabot on a Maven-based project it's not finding any security issues in the transitive dependencies. In theory, it could be achieved by first generating an effective pom that lists all the transitive dependencies and then scanning the result with Dependabot.  But I checked the documentation and haven't found an option to use an effective pom instead of the `pom.xml` file.

Usually, there are many vulnerable packages in the transitive dependencies that still got built into the result if teams produce a standalone JAR. These dependencies have to be excluded in the pom.xml or need version override.

An effective pom can be easily generated by executing the [`help:effective-pom`](https://maven.apache.org/plugins/maven-help-plugin/effective-pom-mojo.html) goal.

**Comment by jeffwidman** [comment]
👋 This repo is about issues with version updates, not the security/vulnerability alerts themselves.

They are separate services / teams / codebases. That team doesn't have a public issue tracker, but now that we have community discussions that is probably the best way to request this: https://github.com/orgs/community/discussions/categories/code-security

In the meantime, as a workaround, you can use the new [Dependency Submission API](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api) to submit the the JAR for alerts analysis on the _actual_ artifact that gets built.
