### ISSUE TITLE
[Gitlab] : Pull request messages are not formatted

### ISSUE THREAD

**Issue by codisart** [dependabot/dependabot-core#584]
Since dependabot use github flavored markdown, the messages are not correctly formatted when displayed on a gitlab Merge request.

**Comment by greysteil** [comment]
Is there an example PR you can link to? Would help with fixing!

**Comment by codisart** [comment]
Do you have a login on gitlab ?

**Comment by greysteil** [comment]
Yep - I'm @greysteil there, too.

**Comment by codisart** [comment]
I gave you access

**Comment by greysteil** [comment]
Ah, I see, looks like this is specific to the markdown in the `<details>` tags. Annoying that GitLab doesn't support that! Wouldn't be too hard to convert it all to html, though.

**Comment by connorshea** [comment]
It looks like this was fixed? e.g. https://gitlab.com/deivid-rodriguez/nipanipa/merge_requests/548

**Comment by greysteil** [comment]
Excellent news! 🎉

**Comment by connorshea** [comment]
I suspect this is because GitLab now uses common mark for its Markdown rendering, if anyone was wondering how it got fixed :)

**Comment by greysteil** [comment]
Yeah - I'm guessing so. I didn't do anything on it. Very pleased they're using the same standard as GitHub!
