### ISSUE TITLE
Support updating date of License

### ISSUE THREAD

**Issue by donBarbos** [dependabot/dependabot-core#5842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Every year the licenses of many projects become obsolete, and the authors are either not interested in updating or do not remember about it. If Dependabot users receive an offer to advertise, this could make licensing easier.

I know it's a bit off topic, but I think it's important. I apologize in advance for such a frivolous suggestion.

**Comment by jeffwidman** [comment]
What do you mean the licenses become obsolete? Do you mean the copyright notices that state the year?

If so, then that isn't necessarily a problem... I'm not a lawyer, and not speaking in an official capacity as a GitHub representative... but the research I've done for my own hobby projects indicated that the copyright year != this year... Start https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated for example... 

I'm going to close as I think this is what you're referring to, but if for some reason you're talking about something else, please comment and we can re-open.
