### ISSUE TITLE
Poetry multiple-constraint dependencies broken by unrelated dependency update

### ISSUE THREAD

**Issue by greschd** [dependabot/dependabot-core#5862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

Poetry (version 1.2.1)

### Language version

python = ">=3.7,<3.10"

### Manifest location and content before the Dependabot update

`pyproject.toml`: https://github.com/greschd/dependabot-poetry-multiple-constraints/blob/4c051f7216cbb70decb1b206fe8de7ff060c188a/pyproject.toml
`poetry.lock`: https://github.com/greschd/dependabot-poetry-multiple-constraints/blob/4c051f7216cbb70decb1b206fe8de7ff060c188a/poetry.lock

### dependabot.yml content

https://github.com/greschd/dependabot-poetry-multiple-constraints/blob/4c051f7216cbb70decb1b206fe8de7ff060c188a/.github/dependabot.yml

### Updated dependency

`wheel` updated from `0.37.0` to `0.37.1`

### What you expected to see, versus what you actually saw

Only the `wheel` related entries in `poetry.lock` should be updated. Instead, the multiple-constraint `numpy` dependency is partially removed.

It seems that dependabot doesn't understand the [multiple-constraint dependency](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) (different `numpy` version for different `python` versions)

```toml
numpy = [
    {version = ">=1.15,<1.22", python = ">=3.7,<3.8"},
    {version = ">=1.22", python = ">=3.8,<3.11"}
]
```

This is mentioned in https://github.com/dependabot/dependabot-core/issues/2715#issuecomment-777435053, but I couldn't find an issue specific to this incompatibility.

In the `poetry.lock`, the multiple-constraint dependency is added as multiple `numpy` entries (AFAICT, the last matching one is selected for a given Python version). Dependabot updates keep only the first entry, and discard the rest.

### Native package manager behavior

PR created manually, using `poetry lock`: https://github.com/greschd/dependabot-poetry-multiple-constraints/pull/2

### Images of the diff or a link to the PR, issue, or logs

https://github.com/greschd/dependabot-poetry-multiple-constraints/pull/1

### Smallest manifest that reproduces the issue

Almost minimal repository: https://github.com/greschd/dependabot-poetry-multiple-constraints

**Comment by jeffwidman** [comment]
Thanks for the detailed issue. We have a few python improvements that we're currently working on, although looking at them I don't think any will fix this particular issues. So it might be a bit til one of us can get to it, in the meantime if you have any interest in opening a PR I'm more than happy to guide you.

**Comment by deivid-rodriguez** [comment]
Hei @greschd!

We're adding PEP621 support soon indeed and I'm already subscribed to that ticket in the poetry roadmap, thanks!

Regarding your question, no, I don't think we support updating dependencies with environment markers in any Python format as of now, so I think for now fixing 1 is the easiest, just make sure they are properly ignored.
