### ISSUE TITLE
Dependabot PRs add setuptools as package dependency

### ISSUE THREAD

**Issue by l0b0** [dependabot/dependabot-core#5868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

Unknown (whatever Poetry version GitHub Dependabot is using)

### Language version

Python 3.9

### Manifest location and content before the Dependabot update

[Gist](https://gist.github.com/l0b0/a7e8b42d62ae2e5e819d45457a760689)

### dependabot.yml content

[Gist](https://gist.github.com/l0b0/f834a12e114b103c9ca64846fdbb7167)

### Updated dependency

[Gist](https://gist.github.com/l0b0/1cbb7b5f3b77574d6770cd1a58f0d70c)

### What you expected to see, versus what you actually saw

None of the package dependencies should include the setuptools package. This is a bug in older versions of Poetry, which cause issues when trying to install packages. In particular, the stricter [poetry2nix runs into an infinite loop](https://github.com/linz/geostore/actions/runs/3222471294/jobs/5271574498) ([upstream issue](https://github.com/nix-community/poetry2nix/issues/648)) when trying to deal with a lock file containing setuptools.

### Native package manager behavior

More recent versions of Poetry do not include setuptools when running `poetry lock`. For a few weeks or months now I've been working around this behaviour by manually removing any reference to setuptools from poetry.lock in Dependabot PRs.

### Images of the diff or a link to the PR, issue, or logs

[PR](https://github.com/linz/geostore/pull/2123/files)

**Comment by jeffwidman** [comment]
Hmm, we recently upgraded `poetry` so we're running latest release: https://github.com/dependabot/dependabot-core/pull/5746

What makes you think this is due to an older version of `poetry`?

Have you tried running the update locally using the `dry-run` script documented on the readme? Add a few `puts` statements and you can probably start to narrow down the source of the issue.

**Comment by l0b0** [comment]
> What makes you think this is due to an older version of `poetry`?

After a bit more investigation, it turns out I had this the wrong way around - the _newer_ versions of Poetry are the ones causing issues because setuptools is no longer excluded from the lock file. I get a workable lock file with current poetry2nix using Poetry 1.1.14. The [fix](https://github.com/nix-community/poetry2nix/pull/736) is actually arriving in poetry2nix, which is now able to deal with this change. Sorry for the noise.

**Comment by jeffwidman** [comment]
No problem thanks for letting us know
