### ISSUE TITLE
pip-compile is called twice per dependency

### ISSUE THREAD

**Issue by jerbob92** [dependabot/dependabot-core#5903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

I noticed some of our Python pip-compile projects taking a long time to be processed by Dependabot (as in 30+ minutes for a cached install). When looking into it I noticed that pip-compile just seems to be slow in general, it will install all dependencies for every dependency to update (which is slow, even if they are cached). 

Both the file updater as the version resolver will run pip-compile twice:
https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb#L84

https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L83

This was introduced in #961 because pip-compile added something that made the header added by pip-compile be changed by Dependabot. 

The header without the change in #961 will have looked something like this:

```
pip-compile --allow-unsafe --output-file=requirements.txt --resolver=backtracking -P {dependency-name} requirements.in
```

Where `{dependency-name}` is the name of the dependency it just tried to update.

I think running pip-compile twice just to fix the header is a bit overkill, as it basically doubles the runtime that is needed for dependabot, and when there is an update it takes even longer.

Suggested fix: pip-compile adds ` -P {dependency-name}` to the header, we can just remove ` -P {dependency-name}` from the resulting .txt file with a replace.

Another fix could be to copy the header from the old .txt, and build the new .txt with the `--no-header` option and then prepend the old header in the resulting .txt file, in that way we don't mess with the header at all, but that requires more work and might be a ticket on it's own.

**Comment by deivid-rodriguez** [comment]
Thanks for opening an issue about this and starting a potential fix 👏

**Comment by jerbob92** [comment]
I tried to fix it but:
 - It's really hard to get the CI tests running locally apparently (no docs on it?)
 - The code does some pretty odd stuff that's not documented well enough to understand it

**Comment by jerbob92** [comment]
Thanks, I did have the dev shell running, but could not figure out how to run the test suits, I used `bin/ci-test` but the tests always succeeded.

For the odd stuff, it's basically all in the running pip-compile twice to "correct" stuff, but the comments give no real indication of what it fixes. It also writes back the original files with `write_original_manifest_files unless dependency.top_level?`, without saying why it does that nor why it matters if it's top level or not. 

Having the tests running locally helps a lot though because then I can actually inspect the resulting pip compile files, so thanks, trying that now!

**Comment by deivid-rodriguez** [comment]
Oh, ok so the odd stuff is precisely what we're trying to fix here 👍.

As per the specs, great. Beware that the python suite is pretty slow at the moment (probably the issue you're trying to fix here contributes to that 😅), so I would recommend focusing on running the test files relevant to the part of the code you are updating.

**Comment by jerbob92** [comment]
Yeah it helps a lot that you can run a specific spec file and even a specific line in that spec. 

So what seems to happen is this:
 - There was a dependency in the original compile txt (`requests==2.18.0`)
 - It was said to be requested by `mock`, but is not needed anymore (in the requested version of mock?)
 - After the update, it's not in the requirements file anymore
 - For some reason a test was added that tests to update a dependency (requests) that is not in the .in file 
 - Of course, pip-compile then adds it to the resulting .in and .txt file, which makes the test fail, because it expects `requests` not to be in the generated .txt file
 - It then writes back the original .in files and runs pip-compile again to remove it again from the .txt file, which works since `requests` is not in the original .in file
 - I don't really know why this was added like this, is it possible that it will try to update dependencies that do not appear in the .in files? It kinda looks like this logic was only added to satisfy an unneeded test.

It was added in this change: https://github.com/dependabot/dependabot-core/commit/53b172861c8fca48a5e5ae57c21116dc80370fc4

and this change is also related: https://github.com/dependabot/dependabot-core/commit/eb4e80dbc7b2457cbaf8776d57f71fd23c4d800c

The changes/tests feel wrong to me but since it's not really clear why it was added I'm a bit scared to change anything to fix it.

Do you know if it's possible that it tries to update non-direct dependencies (so not from the .in file)?

**Comment by deivid-rodriguez** [comment]
I think updating a dependency that's not in the `.in` file is actually a supported scenario, which you get by configuring 

```
allow:
  - dependency-type: indirect
```

in your `dependabot.yml` file.

Does that make sense?

**Comment by jerbob92** [comment]
Yeah I think you are right. It seems to load in all dependencies, so from the .in file and from the .txt file.

When I remove the double pip-compile and the test at https://github.com/dependabot/dependabot-core/blob/main/python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb#L260 everything passes.

If a requirement is actually not needed anymore, it would just be removed from the MR in another dependency update right?

When I try that locally, so with the files:
`python/spec/fixtures/pip_compile_files/unpinned.in` as `requirements.in`
`python/spec/fixtures/requirements/pip_compile_unpinned_rogue.txt` as `requirements.txt`

When I run `pip-compile -v --build-isolation --allow-unsafe --resolver backtracking --output-file=requirements.txt -P mock requirements.in` it will actually remove `requests` from the resulting `requirements.txt`.

Do you know if it's possible to run the dry-run on a folder, that makes it a lot easier to test out different combinations and check the full logic of Dependabot in those cases.

**Comment by deivid-rodriguez** [comment]
> If a requirement is actually not needed anymore, it would just be removed from the MR in another dependency update right?

If that's the starting point, that would be my expectation, yeah. Worth a try though. What I think is more important, is that a pull/merge request to upgrade dependency "foo" from version A to B, where foo-A depends on "bar", but foo-B no longer depends on "bar", correctly removes "bar" from the `.txt` file.

> Do you know if it's possible to run the dry-run on a folder, that makes it a lot easier to test out different combinations and check the full logic of Dependabot in those cases.

That would be great and I really want to feature too, but it's not possible yet out of the box. You have to use a real test repository for testing these things for now.

**Comment by Nishnha** [comment]
> Do you know if it's possible to run the dry-run on a folder, that makes it a lot easier to test out different combinations and check the full logic of Dependabot in those cases.

You might be able to use the `--cache=files` flag on the dry-runner and then modify the cached files locally (which are stored in `/tmp`)

**Comment by jerbob92** [comment]
Ok, so I have tested this locally, it automatically removes the `requests` dependency in every MR it would create:

<details>
<summary>Output without any changes</summary>
=> parsing dependency files
=> updating 5 dependencies: attrs, flaky, mock, pytest-xdist, pytest

=== attrs (17.3.0)
 => checking for updates 1/5
🌍 https://pypi.org/simple/attrs/
 => latest available version is 22.1.0
 => latest allowed version is 22.1.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating attrs from 17.3.0 to 22.1.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== flaky (3.4.0)
 => checking for updates 2/5
🌍 https://pypi.org/simple/flaky/
 => latest available version is 3.7.0
 => latest allowed version is 3.7.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating flaky from 3.4.0 to 3.7.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10c10
    < flaky==3.4.0
    ---
    > flaky==3.7.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== mock (2.0.0)
 => checking for updates 3/5
🌍 https://pypi.org/simple/mock/
 => latest available version is 4.0.3
 => latest allowed version is 4.0.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating mock from 2.0.0 to 4.0.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    11c11
    < mock==2.0.0
    ---
    > mock==4.0.3
    13d12
    < pbr==4.0.2
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pytest-xdist (1.22.2)
 => checking for updates 4/5
🌍 https://pypi.org/simple/pytest-xdist/
 => latest available version is 2.5.0
 => latest allowed version is 1.24.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-xdist from 1.22.2 to 1.24.1

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==0.2
    > pytest-xdist==1.24.1
    ~~~

=== pytest (3.5.1)
 => checking for updates 5/5
🌍 https://pypi.org/simple/pytest/
 => latest available version is 7.1.3
 => latest allowed version is 5.4.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest from 3.5.1 to 5.4.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    12a13
    > packaging==21.3
    14c15
    < pluggy==0.6.0
    ---
    > pluggy==0.13.1
    15a17,18
    > pyparsing==3.0.9
    > pytest==5.4.3
    18,19d20
    < pytest==3.5.1
    < requests==2.18.0
    20a22
    > wcwidth==0.2.5
    ~~~
🌍 Total requests made: '5'
</details>

Time to process: 1m26s

<details>
<summary>Output with my changes</summary>
=> parsing dependency files
=> updating 5 dependencies: attrs, flaky, mock, pytest-xdist, pytest

=== attrs (17.3.0)
 => checking for updates 1/5
🌍 https://pypi.org/simple/attrs/
 => latest available version is 22.1.0
 => latest allowed version is 22.1.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating attrs from 17.3.0 to 22.1.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== flaky (3.4.0)
 => checking for updates 2/5
🌍 https://pypi.org/simple/flaky/
 => latest available version is 3.7.0
 => latest allowed version is 3.7.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating flaky from 3.4.0 to 3.7.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10c10
    < flaky==3.4.0
    ---
    > flaky==3.7.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== mock (2.0.0)
 => checking for updates 3/5
🌍 https://pypi.org/simple/mock/
 => latest available version is 4.0.3
 => latest allowed version is 4.0.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating mock from 2.0.0 to 4.0.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    11c11
    < mock==2.0.0
    ---
    > mock==4.0.3
    13d12
    < pbr==4.0.2
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pytest-xdist (1.22.2)
 => checking for updates 4/5
🌍 https://pypi.org/simple/pytest-xdist/
 => latest available version is 2.5.0
 => latest allowed version is 1.24.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-xdist from 1.22.2 to 1.24.1

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==0.2
    > pytest-xdist==1.24.1
    ~~~

=== pytest (3.5.1)
 => checking for updates 5/5
🌍 https://pypi.org/simple/pytest/
 => latest available version is 7.1.3
 => latest allowed version is 5.4.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest from 3.5.1 to 5.4.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    12a13
    > packaging==21.3
    14c15
    < pluggy==0.6.0
    ---
    > pluggy==0.13.1
    15a17,18
    > pyparsing==3.0.9
    > pytest==5.4.3
    18,19d20
    < pytest==3.5.1
    < requests==2.18.0
    20a22
    > wcwidth==0.2.5
    ~~~
🌍 Total requests made: '5'
</details>

Time to process: 1m12s

As you can see, the requests dependency was removed in both cases, but it's faster without the double pip-compile call.
I have compared both outputs, and they are exactly the same. The time difference doesn't seem that big, but that's only because of the small amount of dependencies, in a real project the difference is much bigger.

I can't really test the `dependency-type: indirect` with the dry-run I think, but I tried to change the dry-run so that it doesn't only run on top level dependencies. You can see the output here:

<details>
<summary>Output without any changes</summary>
=> parsing dependency files
=> updating 14 dependencies: apipkg, attrs, execnet, flaky, mock, more-itertools, pbr, pluggy, py, pytest-forked, pytest-xdist, pytest, requests, six

=== apipkg (1.4)
 => checking for updates 1/14
🌍 https://pypi.org/simple/apipkg/
 => latest available version is 3.0.1
 => latest allowed version is 3.0.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating apipkg from 1.4 to 3.0.1

    ± requirements/test.txt
    ~~~
    7,8c7,8
    < apipkg==1.4
    < attrs==17.3.0
    ---
    > apipkg==3.0.1
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== attrs (17.3.0)
 => checking for updates 2/14
🌍 https://pypi.org/simple/attrs/
 => latest available version is 22.1.0
 => latest allowed version is 22.1.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating attrs from 17.3.0 to 22.1.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== execnet (1.5.0)
 => checking for updates 3/14
🌍 https://pypi.org/simple/execnet/
 => latest available version is 1.9.0
 => latest allowed version is 1.9.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating execnet from 1.5.0 to 1.9.0

    ± requirements/test.txt
    ~~~
    7,9c7,8
    < apipkg==1.4
    < attrs==17.3.0
    < execnet==1.5.0
    ---
    > attrs==22.1.0
    > execnet==1.9.0
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== flaky (3.4.0)
 => checking for updates 4/14
🌍 https://pypi.org/simple/flaky/
 => latest available version is 3.7.0
 => latest allowed version is 3.7.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating flaky from 3.4.0 to 3.7.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10c10
    < flaky==3.4.0
    ---
    > flaky==3.7.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== mock (2.0.0)
 => checking for updates 5/14
🌍 https://pypi.org/simple/mock/
 => latest available version is 4.0.3
 => latest allowed version is 4.0.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating mock from 2.0.0 to 4.0.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    11c11
    < mock==2.0.0
    ---
    > mock==4.0.3
    13d12
    < pbr==4.0.2
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== more-itertools (4.1.0)
 => checking for updates 6/14
🌍 https://pypi.org/simple/more-itertools/
 => latest available version is 9.0.0
 => latest allowed version is 9.0.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating more-itertools from 4.1.0 to 9.0.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    12c12
    < more-itertools==4.1.0
    ---
    > more-itertools==9.0.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pbr (4.0.2)
 => checking for updates 7/14
🌍 https://pypi.org/simple/pbr/
 => latest available version is 5.10.0
 => latest allowed version is 5.10.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pbr from 4.0.2 to 5.10.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    13c13
    < pbr==4.0.2
    ---
    > pbr==5.10.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pluggy (0.6.0)
 => checking for updates 8/14
🌍 https://pypi.org/simple/pluggy/
 => latest available version is 1.0.0
 => latest allowed version is 0.6.0
 => requirements to unlock: update_not_possible
 => requirements update strategy: bump_versions
    (no update possible 🙅‍♀️)

=== py (1.5.3)
 => checking for updates 9/14
🌍 https://pypi.org/simple/py/
 => latest available version is 1.11.0
 => latest allowed version is 1.11.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating py from 1.5.3 to 1.11.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15c15,16
    < py==1.5.3
    ---
    > py==1.11.0
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pytest-forked (0.2)
 => checking for updates 10/14
🌍 https://pypi.org/simple/pytest-forked/
 => latest available version is 1.4.0
 => latest allowed version is 1.2.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-forked from 0.2 to 1.2.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==1.2.0
    > pytest-xdist==1.22.2
    ~~~

=== pytest-xdist (1.22.2)
 => checking for updates 11/14
🌍 https://pypi.org/simple/pytest-xdist/
 => latest available version is 2.5.0
 => latest allowed version is 1.24.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-xdist from 1.22.2 to 1.24.1

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==0.2
    > pytest-xdist==1.24.1
    ~~~

=== pytest (3.5.1)
 => checking for updates 12/14
🌍 https://pypi.org/simple/pytest/
 => latest available version is 7.1.3
 => latest allowed version is 7.1.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest from 3.5.1 to 7.1.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10a11
    > iniconfig==1.1.1
    12c13
    < more-itertools==4.1.0
    ---
    > packaging==21.3
    14,15c15,18
    < pluggy==0.6.0
    < py==1.5.3
    ---
    > pluggy==1.0.0
    > py==1.11.0
    > pyparsing==3.0.9
    > pytest==7.1.3
    18,19d20
    < pytest==3.5.1
    < requests==2.18.0
    20a22
    > tomli==2.0.1
    ~~~

=== requests (2.18.0)
 => checking for updates 13/14
🌍 https://pypi.org/simple/requests/
 => latest available version is 2.28.1
 => latest allowed version is 2.18.0
 => requirements to unlock: update_not_possible
 => requirements update strategy: bump_versions
    (no update possible 🙅‍♀️)

=== six (1.11.0)
 => checking for updates 14/14
🌍 https://pypi.org/simple/six/
 => latest available version is 1.16.0
 => latest allowed version is 1.16.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating six from 1.11.0 to 1.16.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,20c19
    < pytest==3.5.1
    < requests==2.18.0
    < six==1.11.0
    ---
    > six==1.16.0
    ~~~
🌍 Total requests made: '14'
</details>


Time to process: 3m42s

<details>
<summary>Output with my changes</summary>
=> parsing dependency files
=> updating 14 dependencies: apipkg, attrs, execnet, flaky, mock, more-itertools, pbr, pluggy, py, pytest-forked, pytest-xdist, pytest, requests, six

=== apipkg (1.4)
 => checking for updates 1/14
🌍 https://pypi.org/simple/apipkg/
 => latest available version is 3.0.1
 => latest allowed version is 3.0.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating apipkg from 1.4 to 3.0.1

    ± requirements/test.txt
    ~~~
    7,8c7,8
    < apipkg==1.4
    < attrs==17.3.0
    ---
    > apipkg==3.0.1
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== attrs (17.3.0)
 => checking for updates 2/14
🌍 https://pypi.org/simple/attrs/
 => latest available version is 22.1.0
 => latest allowed version is 22.1.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating attrs from 17.3.0 to 22.1.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== execnet (1.5.0)
 => checking for updates 3/14
🌍 https://pypi.org/simple/execnet/
 => latest available version is 1.9.0
 => latest allowed version is 1.9.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating execnet from 1.5.0 to 1.9.0

    ± requirements/test.txt
    ~~~
    7,9c7,8
    < apipkg==1.4
    < attrs==17.3.0
    < execnet==1.5.0
    ---
    > attrs==22.1.0
    > execnet==1.9.0
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== flaky (3.4.0)
 => checking for updates 4/14
🌍 https://pypi.org/simple/flaky/
 => latest available version is 3.7.0
 => latest allowed version is 3.7.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating flaky from 3.4.0 to 3.7.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10c10
    < flaky==3.4.0
    ---
    > flaky==3.7.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== mock (2.0.0)
 => checking for updates 5/14
🌍 https://pypi.org/simple/mock/
 => latest available version is 4.0.3
 => latest allowed version is 4.0.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating mock from 2.0.0 to 4.0.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    11c11
    < mock==2.0.0
    ---
    > mock==4.0.3
    13d12
    < pbr==4.0.2
    15a15
    > pytest==3.5.1
    18,19d17
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== more-itertools (4.1.0)
 => checking for updates 6/14
🌍 https://pypi.org/simple/more-itertools/
 => latest available version is 9.0.0
 => latest allowed version is 9.0.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating more-itertools from 4.1.0 to 9.0.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    12c12
    < more-itertools==4.1.0
    ---
    > more-itertools==9.0.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pbr (4.0.2)
 => checking for updates 7/14
🌍 https://pypi.org/simple/pbr/
 => latest available version is 5.10.0
 => latest allowed version is 5.10.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pbr from 4.0.2 to 5.10.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    13c13
    < pbr==4.0.2
    ---
    > pbr==5.10.0
    15a16
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pluggy (0.6.0)
 => checking for updates 8/14
🌍 https://pypi.org/simple/pluggy/
 => latest available version is 1.0.0
 => latest allowed version is 0.6.0
 => requirements to unlock: update_not_possible
 => requirements update strategy: bump_versions
    (no update possible 🙅‍♀️)

=== py (1.5.3)
 => checking for updates 9/14
🌍 https://pypi.org/simple/py/
 => latest available version is 1.11.0
 => latest allowed version is 1.11.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating py from 1.5.3 to 1.11.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15c15,16
    < py==1.5.3
    ---
    > py==1.11.0
    > pytest==3.5.1
    18,19d18
    < pytest==3.5.1
    < requests==2.18.0
    ~~~

=== pytest-forked (0.2)
 => checking for updates 10/14
🌍 https://pypi.org/simple/pytest-forked/
 => latest available version is 1.4.0
 => latest allowed version is 1.2.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-forked from 0.2 to 1.2.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==1.2.0
    > pytest-xdist==1.22.2
    ~~~

=== pytest-xdist (1.22.2)
 => checking for updates 11/14
🌍 https://pypi.org/simple/pytest-xdist/
 => latest available version is 2.5.0
 => latest allowed version is 1.24.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest-xdist from 1.22.2 to 1.24.1

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    16,17d15
    < pytest-forked==0.2
    < pytest-xdist==1.22.2
    19c17,18
    < requests==2.18.0
    ---
    > pytest-forked==0.2
    > pytest-xdist==1.24.1
    ~~~

=== pytest (3.5.1)
 => checking for updates 12/14
🌍 https://pypi.org/simple/pytest/
 => latest available version is 7.1.3
 => latest allowed version is 7.1.3
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating pytest from 3.5.1 to 7.1.3

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    10a11
    > iniconfig==1.1.1
    12c13
    < more-itertools==4.1.0
    ---
    > packaging==21.3
    14,15c15,18
    < pluggy==0.6.0
    < py==1.5.3
    ---
    > pluggy==1.0.0
    > py==1.11.0
    > pyparsing==3.0.9
    > pytest==7.1.3
    18,19d20
    < pytest==3.5.1
    < requests==2.18.0
    20a22
    > tomli==2.0.1
    ~~~

=== requests (2.18.0)
 => checking for updates 13/14
🌍 https://pypi.org/simple/requests/
 => latest available version is 2.28.1
 => latest allowed version is 2.28.1
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating requests from 2.18.0 to 2.28.1

    ± requirements/test.txt
    ~~~
    8c8,10
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    > certifi==2022.9.24
    > charset-normalizer==2.1.1
    10a13
    > idna==3.4
    15a19
    > pytest==3.5.1
    18,19c22
    < pytest==3.5.1
    < requests==2.18.0
    ---
    > requests==2.28.1
    20a24
    > urllib3==1.26.12
    ~~~

=== six (1.11.0)
 => checking for updates 14/14
🌍 https://pypi.org/simple/six/
 => latest available version is 1.16.0
 => latest allowed version is 1.16.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating six from 1.11.0 to 1.16.0

    ± requirements/test.txt
    ~~~
    8c8
    < attrs==17.3.0
    ---
    > attrs==22.1.0
    15a16
    > pytest==3.5.1
    18,20c19
    < pytest==3.5.1
    < requests==2.18.0
    < six==1.11.0
    ---
    > six==1.16.0
    ~~~
🌍 Total requests made: '14'
</details>

Time to process: 3m11s

Here it also removes `requests` in the MR. The only difference is that it also makes a MR request for requests itself when there is an update for it, but that's only when you do `dependency-type: indirect` I guess, and in that case it makes sense, but it will also be removed by any other MR.

Let me know what you think :)

**Comment by jerbob92** [comment]
Thanks, will check tomorrow!
Another question: when the latest version available is already the current version, it still does all the pip-compile logic, would that really be necessary?

```
=== black (22.10.0)
 => checking for updates 1/33
🌍 https://pypi.org/simple/black/
 => latest available version is 22.10.0
 => latest allowed version is 22.10.0  < It runs pip-compile to determine this, but it doesn't really matter anyway
    (no update needed as it's already up-to-date)
```

**Comment by deivid-rodriguez** [comment]
That's a good point, and I think there may be room for improvement there because the real updater does something similar. And I believe that's an optimization that would apply to more ecosystems and dependency managers, not only python + pip-compile?

**Comment by jerbob92** [comment]
Yeah that's right, it would apply to any ecosystem, but it wouldn't really make any sense for any ecosystem to do more work when it already knows that you are on the latest version.

**Comment by jerbob92** [comment]
@deivid-rodriguez Is it possible to run this CLI with my changes?

**Comment by deivid-rodriguez** [comment]
Yes! If you install the CLI and then run the [dependabot script](https://github.com/dependabot/dependabot-core/blob/eaf59fba24777fc015d8ad0888aebd65ca14056e/script/dependabot) in this repo, it will automatically mount your local tree into the CLI container.

**Comment by jerbob92** [comment]
I have just tested it out with the CLI and it will indeed create an update for `requests`, even though that dependency would be removed in other PR's. My problem with this is that this will only happen if you have superfluous dependencies in your requirement txt file. But those would already be removed by other Dependabot MR's, so it would be pretty weird if you actually have them.

I don't really think there is a right or wrong here, it's just a decision to make, and that decision isn't up to me. I only know that a lot of time can be saved if pip-compile would not be called twice. The original comments don't really say why it is done, so we can only guess. The original author also doesn't remember.

**Comment by deivid-rodriguez** [comment]
Right, thanks for verifying all this.

So indeed we have a decision to make, it seems like a too tiny feature to block speeding up things like this. However, I wonder if we can modify your patch to be zero controversial, like this:

```diff
diff --git a/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb b/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
index 401a20155..6dcfb911d 100644
--- a/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
+++ b/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
@@ -80,7 +80,12 @@ module Dependabot
                   run_pip_compile_command(
                     "pyenv exec pip-compile -v #{pip_compile_options(filename)} -P #{dependency.name} #{filename}"
                   )
-                  write_original_manifest_files unless dependency.top_level?
+                  next if dependency.top_level?
+
+                  write_original_manifest_files
+                  run_pip_compile_command(
+                    "pyenv exec pip-compile #{pip_compile_options(filename)} #{filename}"
+                  )
                 end
 
                 # Remove any .python-version file before parsing the reqs
```

Namely, only run this extra `pip-compile` when updating indirect dependencies. This way, most project will get this speed up, and we can move the discussion of whether to remove this feature to a separate place. Makes sense?

**Comment by jerbob92** [comment]
@deivid-rodriguez nice, just tested that out, that seems to work! :smile: I have updated the PR and also improved the comment about the second `pip-compile` run.
