### ISSUE TITLE
Revisit how responsibilities are split up between `UpdateChecker` and `Version` in docker ecosystem

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#5911]
Currently version parsing logic is split between these two classes, and it feels like it should probably be unified into the `Version` class. It should be reviewed at some point.

_Originally posted by @mattt in https://github.com/dependabot/dependabot-core/pull/5886#discussion_r995981733_

**Comment by jeffwidman** [comment]
I was chatting with @pavera about this last week and he mentioned something that's probably related to this refactoring.

Essentially that many ecosystems do a "find if there's a valid update available"  which then passes to the next stage in the pipeline "yes, we should update"... so then the next step does a "okay, we know we can update, so now go lookup what version we should update to and then perform the update"... so we end up repeating the update lookup twice, which is network intensive + resolver intensive, both of which can be very slow.
