### ISSUE TITLE
Unrelated libraries are updated with bundler

### ISSUE THREAD

**Issue by t-tiger** [dependabot/dependabot-core#5926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

bundler `2.2.32`

### Language version

Ruby `2.7.2`

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

```yaml
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  target-branch: develop
```

### Updated dependency

When updating [warning](https://github.com/jeremyevans/ruby-warning) from 1.2.1 to 1.3.0, the followings are also updated while only warning should be updated.

- [apollo-gateway](https://github.com/Gusto/apollo-federation-ruby) from 3.0.0 to 3.3.0
- [ddtrace](https://github.com/DataDog/dd-trace-rb) from 0.54.2 to 1.1.0.
- [google-protobuf](https://rubygems.org/gems/google-protobuf) from 3.20.0 to 3.21.7
- [haml-rails](https://github.com/haml/haml-rails) from 2.0.1 to 2.1.0
- [listen](https://github.com/guard/listen) from 3.2.1 to 3.7.1
- [nokogiri](https://github.com/sparklemotion/nokogiri/releases) from 1.36.6 to 1.36.8

Above libraries are not related to the original gem, they should be updated with other PRs.

### What you expected to see, versus what you actually saw

**Expected**
Only [warning](https://github.com/jeremyevans/ruby-warning) is updated from 1.2.1 to 1.3.0, which is the result when I manually execute `bundle update warning`.

**Actual**
Other libraries are also updated as `Updated dependency` section shows.

It seems to start last week. Our team has been using dependabot for a long time.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting.

I guess related to the upgrade of Bundler at https://github.com/dependabot/dependabot-core/pull/5509.

Can you share a public repository that reproduces this?

**Comment by t-tiger** [comment]
Thank you for quick response.

> Can you share a public repository that reproduces this?

Sorry, this case is inside private repository at my work 🙇

**Comment by t-tiger** [comment]
I made a public repository that extracts a subset of libraries. As a result, dependabot works as expected 🤔 
https://github.com/t-tiger/dependabot-test/pull/1

After I created a PR, I found other repositories in the company don't have the same problem. 
One repository which has the most complex dependency shows the issue.

**Comment by deivid-rodriguez** [comment]
That's too bad. One question, was the PR created with unrelated dependencies up to date with your default branch?

**Comment by t-tiger** [comment]
Sorry for the late response.

> was the PR created with unrelated dependencies up to date with your default branch?
Yes. 

Currently, I'm trying to find the condition how to reproduce by increasing/decreasing libraries in Gemfile..

**Comment by deivid-rodriguez** [comment]
Actually I think this is expected. Dependabot's behavior is "non conservative", namely, when updating a dependency, it also updates indirect dependencies of it. And I believe `nokogiri` is an indirect dependency of `rspec-rails` (rspec-rails > actionpack > rails-dom-testing > nokogori).

The above behavior is intentional, see https://github.com/dependabot/dependabot-core/issues/2246.

However, I do agree that:

* PR should probably mention the transitive dependencies upgraded together with the direct dependency.
* It should probably NOT be the default in updating indirect dependencies is explicit if configuration.
* We may want to allow configuring this behavior.

**Comment by mloberg** [comment]
I'm having a similar issue, but I'm getting a downgrades from unrelated libraries.

I can't share the repository, but the PR is updating aws-sdk-core from 3.160.0 to 3.164.0. As part of this, it's downgrading an unrelated kubeclient library along with others.

![dependabot-pr](https://user-images.githubusercontent.com/159041/197789413-059b0047-3fb6-48b2-9bd2-43e28cbcb4d0.png)

**Comment by mloberg** [comment]
mloberg/dependabot-bundler-downgrade-issue#2 matches the issue I mentioned exactly. The other PRs that were created also match the PRs that were generated and have the same issue where a bunch of unrelated libraries are being changed

**Comment by deivid-rodriguez** [comment]
Thank you! I'll have a look!

**Comment by ashkulz** [comment]
@deivid-rodriguez any luck with figuring this out? We too have the same issue.

**Comment by deivid-rodriguez** [comment]
Hei @ashkulz, I didn't have time yet, hope to look at this tomorrow.

**Comment by deivid-rodriguez** [comment]
I pushed a fix for this issue. Commenting `@dependabot recreate` on the incorrect PRs should now fix things. Let me know how that goes!

**Comment by mloberg** [comment]
@deivid-rodriguez Things are looking good. Thanks!

**Comment by ashkulz** [comment]
Same here, dependabot was timing out for us for one repo which seems to have been fixed by this as well 🎉

**Comment by t-tiger** [comment]
@deivid-rodriguez Thank you so much for the effort!!

**Comment by deivid-rodriguez** [comment]
No problem! :)
