### ISSUE TITLE
[Composer] constraint on php 7.1

### ISSUE THREAD

**Issue by codisart** [dependabot/dependabot-core#593]
I see that the composer.json in the php helpers has a constraint on php 7.1.
Is it a deliberate choice ?

Could it be possible to have the choice between 7.0, 7.1 and 7.2 ?

**Comment by greysteil** [comment]
Not really - it’s `^7.1`, and I think may need 7+, but Dependabot runs the update process in a container that uses 7.2. Why?

**Comment by codisart** [comment]
Because this constraint block the version usable on the container that runs dependabot and the version on the container has a influence on the computation on version compatibility of composer dependencies. So some tests will always fail on some project on 7.1 because the computation was made with 7.2.

**Comment by greysteil** [comment]
But that won't be the case if the user specifies their PHP version as a platform configuration, and if they set it as a requirement in their `composer.json` then Dependabot will error with a helpful message (asking them to add it as a platform requirement). Did you see [this issue](https://github.com/dependabot/dependabot-core/issues/394)?

I don't think that relaxing the version in Dependabot's own `composer.json` is particularly going to help here, unless you have a specific need to do so for a script you're running or something like that?

**Comment by greysteil** [comment]
Closing as I think this is answered. Happy to continue the conversation, though.
