### ISSUE TITLE
Infinite loop when resolving npm dependency 

### ISSUE THREAD

**Issue by leoamigood** [dependabot/dependabot-core#5945]
### Package ecosystem

npm

### What you expected to see, versus what you actually saw

Somehow when there is an infinite loop when dependabot tries to resolve [this repo](https://github.com/rodcisal/meteor-react-native-simple-boilerplate) dependencies.

Looks like it's stuck in a loop here:
https://github.com/dependabot/dependabot-core/blob/e7c93f9d89d191cfd75bf0fe4288c51d3010ae13/npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb#L184

**Comment by leoamigood** [comment]
Same issue with [this repo](https://github.com/zhwei820/rnNavExample)

**Comment by jeffwidman** [comment]
We should try to repro this using the dry-run script against both those repos... if it doesn't reproduce, then close for the reasons outlined here:
* https://github.com/dependabot/dependabot-core/issues/5824#issuecomment-1302396988

**Comment by deivid-rodriguez** [comment]
It does reproduce, will try to fix it at #6616.
