### ISSUE TITLE
Link to PR in release note doesn't use github-redirect.dependabot.com

### ISSUE THREAD

**Issue by mueller-ma** [dependabot/dependabot-core#597]
See first PR (`#392`) in https://github.com/openhab/openhab-android/pull/963

**Comment by greysteil** [comment]
Good catch! Fixing now.

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/b66c7b725e4d37c2df2778ad955310f7234f5b64 🙈.
