### ISSUE TITLE
Dependabot not ignoring version that not follow semvers semantics

### ISSUE THREAD

**Issue by xsalefter** [dependabot/dependabot-core#5976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

maven 3.x

### Language version

java 11

### dependabot.yml content

https://github.com/killbill/killbill-oss-parent/blob/work-for-release-0.23.x/.github/dependabot.yml#L61

### Updated dependency

dependency name: apache derby
group/artifact: `org.apache.derby:derby`, `org.apache.derby:derbytools`
version: `10.16.1.1` (but doesn't really matter)

### What you expected to see, versus what you actually saw

We configured dependabot to [ignore derby and derbytools](https://github.com/killbill/killbill-oss-parent/blob/work-for-release-0.23.x/.github/dependabot.yml#L61) from upgrading to `10.16.x.x`. 

But dependabot [keep](https://github.com/killbill/killbill-oss-parent/pull/618) send us PR to upgrade that dependency.

Maybe the reason because the fact that derby not following semvers semantics (`10.16.x.x`) ? We raise this concern because for other libraries/jars, ignoring works fine.

Or do we missing something? Any feedback are welcome.

### Images of the diff or a link to the PR, issue, or logs

We provide link above, but will repeated here to make it clear:

Our dependabot.yml: https://github.com/killbill/killbill-oss-parent/blob/work-for-release-0.23.x/.github/dependabot.yml#L61
Dependabot PR (that ignoring `ignore`): https://github.com/killbill/killbill-oss-parent/pull/618

### Smallest manifest that reproduces the issue

Link above will be sufficient, but let us know if you want more information.

**Comment by jakecoffman** [comment]
Dependabot is using the dependabot.yml from the default branch which doesn't have the ignore for derby in it: https://github.com/killbill/killbill-oss-parent/blob/master/.github/dependabot.yml

**Comment by xsalefter** [comment]
Ah, Ok thanks.. I'll close this.
