### ISSUE TITLE
Ignore path-based gems

### ISSUE THREAD

**Issue by mlarraz** [dependabot/dependabot-core#5989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In a monorepo, you can have a number of gems that are linked to an app via symlink.

Since these gems are effectively unversioned, checking for updates is a waste of time. Given a large enough number of these, checking for updates on these can lead to Dependabot timing out and not getting to more versioned gems.

This can be improved by manually adding each gem to the ignore file, but ideally the code would be smart enough to figure out it doesn't need to waste time checking these gems.

**Comment by deivid-rodriguez** [comment]
Hei @mlarraz, thanks for this feature request!

Can you elaborate a bit more on this? How do you link gems to an app via symlink? Normally you would use `gem "foo", path: "path/to/gem"` for this, but I'm not aware of performance issues for this kind of dependencies.

**Comment by mlarraz** [comment]
I actually have an old sample repo set up: https://github.com/mlarraz/dependabot_symlink_test

The app depends on the vendored `foo` gem, which it links to using a symlinked path: https://github.com/mlarraz/dependabot_symlink_test/blob/b1bd1f77e338e98927e6a610d400969c1d1d78a7/app/Gemfile#L3

Dependabot errors on it like so: 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/2575714/200657196-a1cccb2a-5e77-40a7-9924-a91287973b84.png">

due to this line https://github.com/mlarraz/dependabot_symlink_test/blob/b1bd1f77e338e98927e6a610d400969c1d1d78a7/gems/foo/foo.gemspec#L1

While this can be worked around by removing the `require_relative`, this is the default for new gems so it's kind of annoying to have to do it every time a new internal gem is created.

**Comment by mlarraz** [comment]
Seperate, but related issue, is that by default Dependabot will error here: 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/2575714/200657196-a1cccb2a-5e77-40a7-9924-a91287973b84.png">

due to this line https://github.com/mlarraz/dependabot_symlink_test/blob/b1bd1f77e338e98927e6a610d400969c1d1d78a7/gems/foo/foo.gemspec#L1

While this can be worked around by removing the `require_relative`, this is the default for new gems so it's kind of annoying to have to do it every time a new internal gem is created

**Comment by deivid-rodriguez** [comment]
> Dependabot will check for updates to foo on every run, as if it were a remote gem, even though by definition it's always on the latest version. When you have dozens and dozens of path-based gems like this, a Dependabot run can time out before it gets to check for updates to other, non-path-based gems.

I understand. I guess we need to check why that's so slow because even if the dependency is checked, it should be fast for Dependabot to see that there's nothing to do there.

**Comment by deivid-rodriguez** [comment]
Had a closer look and it seemed easy enough to fix, actually! See #6084.
