### ISSUE TITLE
Missing loading `project.optional-dependencies` from `pyproject.toml`

### ISSUE THREAD

**Issue by My-MC** [dependabot/dependabot-core#6001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

Files that do not load: [pyproject.toml](https://github.com/My-MC/ffmpegwithpy-rust/blob/master/pyproject.toml)

### dependabot.yml content

[dependabot.yml](https://github.com/My-MC/ffmpegwithpy-rust/blob/master/.github/dependabot.yml)

### What you expected to see, versus what you actually saw

It is expected that the dev dependencies in [project.optional-dependencies] will be loaded, but they are not.

### Images of the diff or a link to the PR, issue, or logs

```
  proxy | time="2022-10-31T10:01:04Z" level=info msg="proxy starting" commit=4216c65543e4c05c0989a39f3c0f0b9928f1e5ff
  proxy | 2022/10/31 10:01:04 Listening (:1080)
updater | 2022-10-31T10:01:04.404611544 [495672831:main:WARN:src/devices/src/legacy/serial.rs:214] Detached the serial input due to peer close/error.
updater | time="2022-10-31T10:01:06Z" level=info msg="guest starting" commit=cf35ebb71bdca36547054e75ad92fb9bdecdb94c
updater | time="2022-10-31T10:01:06Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=495672831 updater_timeout=45m0s updater_version=af823ec7b3a541e4210840bf82e0d9e7fc660883
updater | I, [2022-10-31T10:01:07.674968 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_495672831> Starting job processing
  proxy | 2022/10/31 10:01:09 [002] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust
  proxy | 2022/10/31 10:01:09 [002] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [002] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust
  proxy | 2022/10/31 10:01:10 [004] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/git/refs/heads/master
  proxy | 2022/10/31 10:01:10 [004] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [004] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/git/refs/heads/master
  proxy | 2022/10/31 10:01:10 [006] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [006] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [006] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [008] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/pyproject.toml?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [008] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [008] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/pyproject.toml?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [010] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/.github?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [010] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [010] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/.github?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [012] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/python?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [012] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [012] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/python?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [014] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/src?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [014] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [014] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/src?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [016] GET https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/tests?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
  proxy | 2022/10/31 10:01:10 [016] * authenticating github api request
  proxy | 2022/10/31 10:01:10 [016] 200 https://api.github.com:443/repos/My-MC/ffmpegwithpy-rust/contents/tests?ref=5b408ecf031d9b57a2dbe8d91870e931d8b212fe
updater | INFO <job_495672831> Finished job processing
updater | time="2022-10-31T10:01:10Z" level=info msg="task complete" container_id=job-495672831-file-fetcher exit_code=0 job_id=495672831 step=fetcher
updater | I, [2022-10-31T10:01:11.729728 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_495672831> Starting job processing
updater | INFO <job_495672831> Starting update job for My-MC/ffmpegwithpy-rust
updater | INFO <job_495672831> Finished job processing
updater | time="2022-10-31T10:01:14Z" level=info msg="task complete" container_id=job-495672831-updater exit_code=0 job_id=495672831 step=updater
```

**Comment by jeffwidman** [comment]
Thanks for the report.

Quick question: How do you know the `project.optional-dependencies` aren't loaded? Is there one that is known to be outdated that Dependabot didn't open a PR for?

We only recently merged the PR that added `pyproject.toml` support, so my guess is this isn't so much a bug as simply something that hasn't been added yet, but I wasn't closely involved with that PR so not sure. 

But we'd happily merge a PR if you want to add support for this.

**Comment by My-MC** [comment]
Thanks for the reply.

It can be seen from the following picture that `project.optional-dependencies` is not loaded.
![image](https://user-images.githubusercontent.com/84212641/199182801-e9e4b068-23ce-41ae-9cbb-7976462f73d5.png)

I considered the possibility that I was not following `PEP 621`, but I was able to install it using pip and was able to confirm that the syntax was not there.

I can't program with Ruby. So I can't contribute. I'm sorry.

I'm a Japanese student. so I may not be able to reply soon.

**Comment by jeffwidman** [comment]
Thanks. I don't doubt you're following `PEP 621`, but we may not yet support this part of it, I don't know.

The screenshot you posted is from the Dependency Graph, which is generated by a completely different code base within GitHub, so we can't use it to ascertain whether Dependabot version update checker is loading the `project.optional-dependencies` bit.

**Comment by My-MC** [comment]
> The screenshot you posted is from the Dependency Graph, which is generated by a completely different code base within GitHub, so we can't use it to ascertain whether Dependabot version update checker is loading the `project.optional-dependencies` bit.

Oh, that's right.

I checked and there are updates on maturin and pytest.

Package name | Currently installed version | Latest Version
|-|-|-|
[maturin](https://pypi.org/project/maturin/#history) | 0.13.6 | 0.13.7
[pytest](https://pypi.org/project/pytest/7.2.0/#history) | 7.1.3 | 7.2.0

There is an update like this, but it has not been detected.

**Comment by jeffwidman** [comment]
Thanks. I just checked, and it looks like we _do_ attempt to support `project.optional-dependencies`: 
https://github.com/dependabot/dependabot-core/blob/868ef7dc2d8d81348626b374a0d2aaf14927e9d9/python/helpers/lib/parser.py#L57-L66

IF you do have interest, the quick thing would be to add a `puts group_dependencies` statement right after line 66 there...  and then run this using the `dry-run` script: https://github.com/dependabot/dependabot-core#dry-run-script

It should be pretty quick to do locally within the docker container, and that will let you see if the optional dependencies are getting included or skipped.

**Comment by My-MC** [comment]
I see. So it's not supported by the GitHub bot yet?

Until it is supported, I will try to run it locally using Docker.

**Comment by jeffwidman** [comment]
It is supported just for some reason it's not working on your repository.
Not sure why. You are welcome to investigate it if you want using the dry
run script I mentioned above.

**Comment by deivid-rodriguez** [comment]
I had a look at this and it was indeed a bug when we were failing to recognize projects as following PEP621 when they only have optional dependencies. It should be fixed by #6032!

**Comment by My-MC** [comment]
Oh. Thank you very much.
I hope this PR will be MERGE!

**Comment by deivid-rodriguez** [comment]
@My-MC Can you try checking for updates now?
