### ISSUE TITLE
Dependabot created a PR that says it fixes a vulnerability but actually updates no versions

### ISSUE THREAD

**Issue by pimterry** [dependabot/dependabot-core#6023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

Dependabout attempted to update async from 2.6.3 to 2.6.4 in my repo.

I expected to receive a PR with a commit making this change to package-lock.json. Instead I received a PR ([here](https://github.com/httptoolkit/httptoolkit-server/pull/60)) containing just [this commit](https://github.com/httptoolkit/httptoolkit-server/pull/60/commits/665c8e0b678e321ff65e94f601e797a24be0eadb) which doesn't bump any versions at all. It only updates the package-lock.json integrity hashes with no version changes.

Note that on the [resulting updated file](https://github.com/httptoolkit/httptoolkit-server/blob/665c8e0b678e321ff65e94f601e797a24be0eadb/package-lock.json#L15359-L15366) I do still depend on the vulnerable package version - dependabot has told me it's fixed a vulnerability that is actually still present. In this case it doesn't affect my application, but in other cases this could be a very serious problem!

This seems like a clear bug in PR generation - the PR should bump the version of the target package, and in general no PRs should be created that don't bump versions.

**Comment by jeffwidman** [comment]
There were some bug fixes that shipped in just the last few days with how dependencies are parsed, which would in turn affect how alerts are generated and possibly (doubtful but possibly) changed how security PR's for this scenario are generated.

So wanted to doublecheck: is this still happening?

**Comment by pimterry** [comment]
I haven't seen this again, but I only saw it the one time in the past so it's hard to know exactly what triggered this or whether it's fixed I'm afraid.

**Comment by deivid-rodriguez** [comment]
Let close it for now and try to triage this immediately if it happens again.

@pimterry Please do reopen if it reappears, and thanks for reporting it in the first place (too bad we got here late).
