### ISSUE TITLE
Dependabot run failing on updater

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6024]
The `omnibus` `bundler` Dependabot run: 
https://github.com/dependabot/dependabot-core/blob/da8c81fc6c82b76e2371f7578f1b5f879519c824/.github/dependabot.yml#L65-L68

Is currently failing with the following error:
https://github.com/dependabot/dependabot-core/network/updates/495511889

```
Dependabot encountered the following error:

Bundler::Dsl::DSLError with message: [!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `dependabot-bundler.gemspec`: Illformed requirement [">= 1.0.0, <= 1.6.3"]. Bundler cannot continue.

 #  from /home/dependabot/dependabot-updater/dependabot_tmp_dir/bundler/dependabot-bundler.gemspec:31
 #  -------------------------------------------
 #    common_gemspec.development_dependencies.each do |dep|
 >      spec.add_development_dependency dep.name, dep.requirement.to_s
 #    end
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/dependabot/dependabot-updater/dependabot_tmp_dir/omnibus/Gemfile:6
 #  -------------------------------------------
 #  
 >  gemspec path: "../bundler"
 #  gemspec path: "../cargo"
 #  -------------------------------------------
```

The pins were a little tricky to track down because they're coming in via chained inheritance, but I _think_ it's these pins on the `debug` gem:
https://github.com/dependabot/dependabot-core/blob/da8c81fc6c82b76e2371f7578f1b5f879519c824/common/dependabot-common.gemspec#L38
https://github.com/dependabot/dependabot-core/blob/da8c81fc6c82b76e2371f7578f1b5f879519c824/updater/Gemfile#L30

**Comment by deivid-rodriguez** [comment]
Found this same error while working on something else. #6070 should fix it!
