### ISSUE TITLE
Provide docs about how to setup yarn/berry with dependabot

### ISSUE THREAD

**Issue by yarinsa** [dependabot/dependabot-core#6027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

Our workflow fails since dependabot is trying to change the lockfile. 
I ended up adding to the code something like 

```
    if: ${{ github.actor != 'dependabot[bot]' }}
	run: yarn config set enableImmutableInstalls false
```

Will be nice to know what is the best practice here

**Comment by pavera** [comment]
I deployed #6017 yesterday which includes making the same `config set` call before running any `yarn` commands. Can you try again without your change and see if it's working now?

**Comment by jeffwidman** [comment]
@yarinsa nudge re: ☝️ ... does this now work as expected for you?

**Comment by yarinsa** [comment]
@jeffwidman didnt got a chance to check it, I will check it today and let you know

**Comment by yarinsa** [comment]
Looks good!
