### ISSUE TITLE
Rebase makes title and diff different

### ISSUE THREAD

**Issue by nwtgck** [dependabot/dependabot-core#6039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### dependabot.yml content

https://github.com/nwtgck/piping-server/blob/a539b15922fa729ea531b7d5228fe5d0877c5201/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Here is the actual title and diff.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/10933561/199858294-78faeb77-0be2-48bf-bad1-82b7afa52b81.png">

<https://github.com/nwtgck/piping-server/pull/727/files>

As you can see, the titile says "16.18.0-alpine" but the diff shows "19.0.0-alpine".
Before "@dependabot rebase", the title and the diff was correct: https://github.com/nwtgck/piping-server/commit/339d999edf077e4065c78974d409a98b02e2b648.

https://github.com/dependabot/dependabot-core/issues/5890 might be related.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

This is clearly a bug, but it'd most likely be in our back-end infra, not the code here in `dependabot-core`. Unfortunately at this point the logs are long-gone and it will be hard to recreate exactly what happened given that this only happened on a `@dependabot rebase`, and the node version is newer, and also I see newer PR's getting opened correctly on your repo:
* https://github.com/nwtgck/piping-server/pull/736

So if you see it again, please file a an issue or comment on this one with an example and we can re-open... we'd need to jump on it fairly quickly to debug what exactly happened... we try to do that but no guarantees if we're in the middle of a ship and no one has cycle to debug, but generally we do try to reserve a little slack across the team to investigate race conditions in the back end for stuff like this.

Sorry I can't be more helpful.
