### ISSUE TITLE
Get rid of hardcoded list of python versions

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

From https://github.com/dependabot/dependabot-core/pull/6043#discussion_r1013705132

There's a hardcoded list of supported python versions here:
https://github.com/dependabot/dependabot-core/blob/69e45277160d970846b3a55cc8429d10c5fd25d0/python/lib/dependabot/python/python_versions.rb#L12-L20 

Although it's nice to have an allow list, that's still annoying to have to keep up to date. 

Here's the commit that added this: https://github.com/dependabot/dependabot-core/commit/e43c80f6e4521fbf59b01c6b97ea8071c359dead

So when this note was added, the vulnerable versions were in the 3.5.x series... 3.6 is now EOL from upstream Python, although we're unofficially made a number of choices to continue to support it until Ubuntu 18.04 goes EOL this coming April.

Before that, there was a note about poetry not supporting python versions, which got added way back here: https://github.com/dependabot/dependabot-core/commit/6f734df0ef3be4f1881080084e80bfad8bb68206#diff-fcc7191de583ab48f2202111f3076e45200c2ff6b83bb4b3f88425a81ee604e4R3-R8

I assume this meant that at the time Poetry couldn't parse the python version requirements?? But a quick google shows that now it can... 

Anyway, need to do some more code spelunking... I assume this is likely completely unnecessary now, especially as our security model is a good deal tighter.

**Comment by pavera** [comment]
I've been looking at reducing our python version matching to just `major.minor` to mostly eliminate the need to install python on the fly. I think this work will also remove the need to track all these python versions, at most we would need to preserve the `major.minor` versions we support if we want to quickly fail for repos that have fallen out of support.

**Comment by pavera** [comment]
Now that we've deployed pre-compiled python, the next step would be to reduce or eliminate this list. I intend to refactor a good bit of the python version detection logic as it's repeated across the various package managers, once this logic is consolidated it should be easy to update any "is this python version supported" check in 1 place. Again I think we would maintain a list of `major.minor` versions we support so we can quickly report a useful error.

**Comment by jeffwidman** [comment]
Resolved by:
* https://github.com/dependabot/dependabot-core/pull/7615
