### ISSUE TITLE
Yarn v2/v3 zero-install file permissions are changed

### ISSUE THREAD

**Issue by agrobbin** [dependabot/dependabot-core#6081]
When doing zero-installs on Yarn v2/v3, the `.pnp.cjs` file permission is changed by Dependabot from `755` to `644`.

@pavera to ensure this subtle bug is not lost, I thought it'd make sense to create a separate issue for it.

_Originally posted by @agrobbin in https://github.com/dependabot/dependabot-core/issues/5946#issuecomment-1303986157_

**Comment by pavera** [comment]
Some but not all? That would seem to indicate that our detection of zero installs is non-deterministic somehow. If we detect zero-install (by the presence of a .pnp.cjs file in the repo) we use `skip-build` otherwise we do fall back to using the `enableScripts` setting. I'll need to investigate further how this might be failing.

**Comment by agrobbin** [comment]
Sorry, what I meant to say was "in all Dependabot PRs issued this morning". My use of the word "some" was meant to indicate that I got several Dependabot PRs, all of which had this issue. Sorry for the confusion!

**Comment by pavera** [comment]
OK, so `skip-build` doesn't seem to preserve the permissions in that case. I'll have to test more and try to find a solution, thanks for creating this issue so it's not lost.

**Comment by pavera** [comment]
I've found the issue here, we set the mode on all files as part of the [PR creation](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/github.rb#L196). 

Working on a solution now.

**Comment by pavera** [comment]
I've deployed the fix for this and verified it works in our test repos. Closing this issue, but if this is still occurring please reopen.

**Comment by agrobbin** [comment]
Thanks @pavera! I will confirm the next time Dependabot updates a Yarn dependency.

**Comment by agrobbin** [comment]
@pavera just to confirm, this seems to have done the trick! Really appreciate all of your follow-up work on Yarn Berry Dependabot support.

**Comment by agrobbin** [comment]
@pavera I'm sorry to resurrect this issue, but I have started seeing this issue again on one of my repositories. I haven't been able to deduce a pattern, yet, but if there's anything I can do to help debug it, please let me know!
