### ISSUE TITLE
vgo support

### ISSUE THREAD

**Issue by jbreitbart** [dependabot/dependabot-core#609]
As a followup to #449. `vgo` support would also be great once it gets widely adopted.

Thanks for the dep support 😄, just opening this now to be able to get notified once `vgo` is also available.

**Comment by homme** [comment]
The recently released Go 1.11 [includes support](https://github.com/golang/go/wiki/Modules) as an experimental opt in feature. It would be great if this could be supported by dependabot to help in the migration to and experimentation with go modules.

**Comment by greysteil** [comment]
We're working on it! @hmarr has it on a branch locally, and we should have something for you in the next week or so. 😎
