### ISSUE TITLE
./bin/docker-dev-shell error: "ERROR: '~ondrej' user or team does not exist."

### ISSUE THREAD

**Issue by rafalp** [dependabot/dependabot-core#6125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

MacOS/Docker

### What you expected to see, versus what you actually saw

`./bin/docker-dev-shell` runs without errors.

**Comment by rafalp** [comment]
I'm trying to dry-run dependabot locally on my MacOS to debug why it's no longer detecting dependencies for my python package. Readme says to run [bin/docker-dev-shell](https://github.com/dependabot/dependabot-core#dry-run-script) before running the dry-run script, but that one fails on docker image build:

```
 => ERROR [10/40] RUN add-apt-repository ppa:ondrej/php   && apt-get update   && apt-get install -y --no-ins  25.1s
------
 > [10/40] RUN add-apt-repository ppa:ondrej/php   && apt-get update   && apt-get install -y --no-install-recommends     php7.4     php7.4-apcu     php7.4-bcmath     php7.4-cli     php7.4-common     php7.4-curl     php7.4-gd     php7.4-geoip     php7.4-gettext     php7.4-gmp     php7.4-imagick     php7.4-imap     php7.4-intl     php7.4-json     php7.4-ldap     php7.4-mbstring     php7.4-memcached     php7.4-mongodb     php7.4-mysql     php7.4-redis     php7.4-soap     php7.4-sqlite3     php7.4-tidy     php7.4-xml     php7.4-zip     php7.4-zmq     php7.4-mcrypt   && rm -rf /var/lib/apt/lists/*:
#14 25.01 Cannot add PPA: 'ppa:~ondrej/ubuntu/php'.
#14 25.01 ERROR: '~ondrej' user or team does not exist.
------
executor failed running [/bin/bash -o pipefail -c add-apt-repository ppa:ondrej/php   && apt-get update   && apt-get install -y --no-install-recommends     php7.4     php7.4-apcu     php7.4-bcmath     php7.4-cli     php7.4-common     php7.4-curl     php7.4-gd     php7.4-geoip     php7.4-gettext     php7.4-gmp     php7.4-imagick     php7.4-imap     php7.4-intl     php7.4-json     php7.4-ldap     php7.4-mbstring     php7.4-memcached     php7.4-mongodb     php7.4-mysql     php7.4-redis     php7.4-soap     php7.4-sqlite3     php7.4-tidy     php7.4-xml     php7.4-zip     php7.4-zmq     php7.4-mcrypt   && rm -rf /var/lib/apt/lists/*]: exit code: 1
```

**Comment by jeffwidman** [comment]
@rafalp Are you still hitting this? What shell are you running this under?

The `ondrej` is coming from the ppa name that we use to install php... very weird that the `~` is creeping in... I cannot repro this at all, I'm using `zsh` myself and everything working fine.

**Comment by rafalp** [comment]
I haven't tried. I wanted to run Dependabot locally to debug why it claims that my Python library has no dependencies and I've worked around this issue by removing PHP dependency from Docker image altogether.

**Comment by deivid-rodriguez** [comment]
Here it's suggested that this is a server side issue: https://askubuntu.com/questions/1112174/why-cannot-use-ppaondrej.

We may consider installing php different if this is not very reliable. It seems the same version we're installing from the PPA is already available by default? https://packages.ubuntu.com/focal/php7.4

**Comment by jeffwidman** [comment]
I'm going to close as unable to repro, but if someone starts hitting this again please comment and we can re-open.

We're also in the middle of bumping PHP versions, so not sure we should switch to Ubuntu default PHP version right now.

**Comment by deivid-rodriguez** [comment]
I actually hit this again very recently 😬

I did try this diff

```diff
diff --git a/Dockerfile b/Dockerfile
index 19811c503..7cd3b374b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -158,8 +158,7 @@ RUN [ "$TARGETARCH" != "amd64" ] \
 
 # Install PHP and Composer
 ENV COMPOSER_ALLOW_SUPERUSER=1
-RUN add-apt-repository ppa:ondrej/php \
-  && apt-get update \
+RUN apt-get update \
   && apt-get install -y --no-install-recommends \
     php7.4 \
     php7.4-apcu \
@@ -187,7 +186,6 @@ RUN add-apt-repository ppa:ondrej/php \
     php7.4-xml \
     php7.4-zip \
     php7.4-zmq \
-    php7.4-mcrypt \
   && rm -rf /var/lib/apt/lists/*
 
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer1 --version=1.10.26
```

And it worked flawlessly, but it would require rolling back https://github.com/dependabot/dependabot-core/pull/4170. We never knew why it was added so I guess it wouldn't be a big deal, but I only run into this once, so no big deal either if we do nothing about this.
