### ISSUE TITLE
Audit code for use of `Open3.capture2e()`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

From https://github.com/dependabot/dependabot-core/pull/6103

I've only seen `stdout, _, process = Open3.capture3(env, command)` used in our code, but we should audit the code for any other usages of `Open3.capture2e` to see if we have risks of hitting this in other envs... and if so, why are we using `capture2e` rather than `capture3`?

**Comment by deivid-rodriguez** [comment]
I actually opened #6110 which is basically the same thing?

**Comment by jeffwidman** [comment]
Ha, so you did! I'm still catching up on notifications and hadn't seen that. Thank you!
