### ISSUE TITLE
Directory.Build.props with 'PrivateAssets' set to 'all' raises exception

### ISSUE THREAD

**Issue by Tripletri** [dependabot/dependabot-core#6133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### What you expected to see, versus what you actually saw

I am receiving exception while updating dependency.
```
undefined method `attribute' for nil:NilClass
 
node_name = node.attribute("Include")&.value&.strip ||
                               ^^^^^^^^^^
```

### Smallest manifest that reproduces the issue

1. In repo root directory place `Directory.Build.props` with `<PrivateAssets>All</PrivateAssets>` for `PackageReference`
```
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
```
2. Run update

Repo I'm testing on https://gitlab.com/Tripletri/build-props-bug

**Comment by jeffwidman** [comment]
👋 Sorry to hear you're having problems.

Unfortunately that traceback doesn't include any line numbers, so it's unclear which section of code is throwing problems. 

Additionally, you're running this against `gitlab`... we're thrilled that that others are able to derive value from this, but support for GitLab is community driven and not something we can invest time into beyond reviewing PR's submitted by external folks such as yourself. 

I'm not sure how you're running this, but if you're using https://gitlab.com/dependabot-gitlab/dependabot you might check with them there?

**Comment by Tripletri** [comment]
I reproduced this bug using GitHub-dependabot #6139

**Comment by jeffwidman** [comment]
Thank you! That's much more helpful/clear, especially with the test repo.
