### ISSUE TITLE
Registries AWS

### ISSUE THREAD

**Issue by vgpastor** [dependabot/dependabot-core#6187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In order to update the security requirements , i propose that Dependantbot can use roles to connect to AWS not only secret_id and secret_key, because the use of shared secrets are a vulnerability.

Here you can see how AWS config works https://github.com/aws-actions/configure-aws-credentials

**Comment by jeffwidman** [comment]
I'm unclear what registries you're asking for... AWS has multiple.

However, there's already a few similar requests, pretty sure you want one of these so closing as a duplicate:
* https://github.com/dependabot/dependabot-core/issues/1009
* https://github.com/dependabot/dependabot-core/issues/6580

**Comment by vgpastor** [comment]
Sorry @jeffwidman i don't find the issue opened for this.
I move my comments to #1009
