### ISSUE TITLE
[Suggestion] Update the current PR instead of superseeding it

### ISSUE THREAD

**Issue by KingDGrizzle** [dependabot/dependabot-core#620]
Hello.

One of the more... not annoying but slightly annoying things about dependabot is how it handles certain bumps.

Say we are on version 5.0.0. 5.1.0 gets released, and dependabot makes a PR. then 5.2.0 gets released. dependabot superseeds the old PR and creates a new one instead of editing the existing PR and making a comment saying `Version x.x.x has been released. This PR is now updated for that version. Heres the difference between old x.x.x and current x.x.x`, where old x.x.x is 5.1.0 in this example.

So, my suggestion was basically what I typed up above. In my opinion it would keep repositories cleaner, especially for GitHub based modules (see: npm with a github module installed)

Although this might break the reopen command... Or maybe make a comment saying the new version was released, type `atdependabot some command name` to bring this PR up to date with that version.

Maybe this is impossible due to the way dependabot works right now, I frankly don't know. But I believe this would be nice to consider.

Let me know your thoughts!

**Comment by greysteil** [comment]
I think this makes a tonne of sense. It's not trivial to implement, but I agree it would be an improvement. There's an issue on dependabot/feedback tracking it [here](https://github.com/dependabot/feedback/issues/14), so I'm going to close this as a dupe, but thanks for raising it.

**Comment by KingDGrizzle** [comment]
Woops. I forgot to double check all repos before submitting. My bad.

I'll keeo track on the issue there then. :smiley:
