### ISSUE TITLE
Dependabot fails to update same dependency in same pull request

### ISSUE THREAD

**Issue by glensc** [dependabot/dependabot-core#6200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, pipenv

### What you expected to see, versus what you actually saw

Dependabot created two PR's for same dependency update:
- https://github.com/Taxel/PlexTraktSync/pull/1209/files - updates requirements.txt
- https://github.com/Taxel/PlexTraktSync/pull/1216/files - updates Pipfile.lock, and `python_version < '4'` to `python_version < '4.0'` changes already reported as https://github.com/dependabot/dependabot-core/issues/6091

it used to manage this nicely and update both files in same pull request. sometimes it fails, i have not yet determined the pattern.

**Comment by deivid-rodriguez** [comment]
Looking at your dependency files, I think there's two issues here:

* In presence of `Pipfile` and `Pipfile.lock` file, a `requirements.txt` file should be considered just as another lock file, and don't get updated directly, but just be updated to follow `Pipfile.lock` changes. So no PRs should be proposed for you unless you [configure](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) `allow: [{ dependency-type: "indirect" }]` in your `dependabot.yml` file.

* If `allow: [{ dependency-type: "indirect" }]` was configured, you should indeed get just one PR with both updates included, not two.

**Comment by glensc** [comment]
@deivid-rodriguez so, if I got you correctly, do I need to do this?:
- https://github.com/Taxel/PlexTraktSync/pull/1218

**Comment by glensc** [comment]
i'll  go with `all` then. thanks

**Comment by glensc** [comment]
I've merged that, but now it still updated only one file, requirements.txt this time:
- https://github.com/Taxel/PlexTraktSync/pull/1226

**Comment by glensc** [comment]
oh, wow, it created the second PR already so soon:
- https://github.com/Taxel/PlexTraktSync/pull/1232

**Comment by pavera** [comment]
I started looking at this in the debugger and it looks like it's possibly an issue in the `resolver_type` method which basically picks which package manager we think is being used. In my tests it keeps picking plain `pip` based on the fact that it is finding a possible update in `requirements.txt` before finding the `Pipfile` update.

I'll keep pulling on this thread and see if I can come up with a solution.

**Comment by jeffwidman** [comment]
This is not the first time we've run into problems with trying to guess which package manager is being used within an ecosystem. From a product perspective IMO we should reconsider if it might be more straightforward for us to ask users to specify the specific manager for any ecosystem with more than one possible package manager. We probably could pick a default for every ecosystem. This would also pet users specify more than one package manager if they wanted to track updates multiple paths. Anyway, a discussion beyond the scope of this particular issue but wanted to mention as a recurring thread I've seen.

**Comment by jeffwidman** [comment]
(the other recurring thread I've seen is the confusion resulting from python treating `requirements.txt` as both a manifest and a lockfile. Life would be simpler if they had an officially-blessed lockfile that all package managerd generate towards...)

**Comment by glensc** [comment]
Another example:
- https://github.com/Taxel/PlexTraktSync/pull/1259
- commit: [Taxel/PlexTraktSync@`e39cddf` (#1259)](https://github.com/Taxel/PlexTraktSync/pull/1259/commits/e39cddfc2799d06e88425dbd644881f7c53452da)
- `requirements.txt` bumped 3.0.33 to 3.0.36
- `Pipfile.lock` - stayed at 3.0.33: https://github.com/Taxel/PlexTraktSync/blob/e39cddfc2799d06e88425dbd644881f7c53452da/Pipfile.lock#L136

**Comment by pavera** [comment]
Yeah, our logic here is a little fuzzy and doesn't really work for transitive dependencies. Basically since `prompt-toolkit` is a transitive dependency, we don't see that it needs to be updated in the pipenv environment because it is not in the `Pipfile`. When we're detecting which package manager we're operating as we only consider the "manifest" files currently, which we classify `requirements.txt` as a manifest file. Since the dependency doesn't occur in `Pipfile` we choose pip instead of pipenv and perform the update only on `requirements.txt` instead of choosing pipenv which would then updated both.

I'm attempting to improve this logic to prefer pipenv over pip in the presence of a `Pipfile` even if the dependency doesn't occur in said `Pipfile`. Hopefully will have a PR in the next day or so. Basically the current assumption is if there is a `Pipfile` and a `requirements.txt` the `requirements.txt` is probably managed directly with pip and not generated from the `Pipfile`. My approach is going to be to change this assumption to be if there are both files in the repository, assume the `requirements.txt` is generated from pipenv until shown otherwise.

**Comment by glensc** [comment]
ok, so for me workaround is to just add all dependencies to both files. the requrements.txt is just a dump of pipfile.lock anyway in that project.

**Comment by glensc** [comment]
And now there's another problem: It updates other unrelated dependencies as well:
- https://github.com/Taxel/PlexTraktSync/pull/1266/files 

The PR is about "Bump certifi from 2022.9.24 to 2022.12.7", which it happens to update Pipfile, Pipfile.lock, requirements.txt. so far so good.

but it also updates `prompt-toolkit==3.0.36; python_full_version >= '3.6.2'`, which there was prior PR already:
- https://github.com/Taxel/PlexTraktSync/pull/1259

**Comment by pavera** [comment]
I'm not seeing the `prompt-toolkit` update in that PR? In `requirements.txt` it just seems to be removing the `python_full_version` from the `prompt-toolkit` line not changing the version? So it seems this is just another example of your issue https://github.com/dependabot/dependabot-core/issues/6091? Or am I missing another update to `prompt-toolkit` in that PR?

**Comment by glensc** [comment]
it was in the previous push:
> @[dependabot](https://github.com/apps/dependabot) dependabot bot [force-pushed](https://github.com/Taxel/PlexTraktSync/compare/36243f32c168147757b5dc935c760e4b59d2e345..8e5462ca3deec155ef53a092c6ea65c02ae2028f) the dependabot/pip/certifi-2022.12.7 branch from [36243f3 ](https://github.com/Taxel/PlexTraktSync/commit/36243f32c168147757b5dc935c760e4b59d2e345)to [8e5462c ](https://github.com/Taxel/PlexTraktSync/commit/8e5462ca3deec155ef53a092c6ea65c02ae2028f)[1 hour ago](https://github.com/Taxel/PlexTraktSync/pull/1266#event-7992943137)

**Comment by glensc** [comment]
How do I add items with markers to Pipfile?

i.e requirements has:
```
attrs==22.1.0; python_version >= '3.5'
```

I'm trying to work around that dependabot updates Pipenv files as well files in this PR:
- [Taxel/PlexTraktSync@`022256a` (#1301)](https://github.com/Taxel/PlexTraktSync/pull/1301/commits/022256a26196ea086d5b789b169f051302b1579a)

**Comment by glensc** [comment]
Since there was already marker in Pipfile.lock:
- https://github.com/Taxel/PlexTraktSync/blob/3f5fa8b8be02d4613304c233af138ba58f43ac6f/Pipfile.lock#L27-L34

I only added line to Pipfile without markers
- https://github.com/Taxel/PlexTraktSync/commit/f3a5e2de7373b592767f34b13740df398210e0a9

**Comment by abdulapopoola** [comment]
Closing out as stale

**Comment by glensc** [comment]
Some kind of problem still there. Need to add all packages to Pipenv to avoid some buggy behavior:
- https://github.com/Taxel/PlexTraktSync/pull/1983
