### ISSUE TITLE
Custom labels do not work for Azure DevOps

### ISSUE THREAD

**Issue by mburumaxwell** [dependabot/dependabot-core#6231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

n/a

### Package manager version

n/a

### Language version

n/a

### What you expected to see, versus what you actually saw

I expect PRs created for Azure to have custom labels that I specified but they are not present because Azure does not have centralized tags/labels.

**Comment by jeffwidman** [comment]
👋 Sorry for the delay on this one, and I appreciate the nudge on the PR. I left a comment on it.
