### ISSUE TITLE
YAML parser for github-actions tries to symbolize strings starting with :

### ISSUE THREAD

**Issue by MeneDev** [dependabot/dependabot-core#6236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### What you expected to see, versus what you actually saw

I expect a string ":foo" to be parsed as ":foo", e.g. in the yaml

```yaml
mykey: :foo
```

actually saw:

/usr/local/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Symbol (Psych::DisallowedClass)

Note that I only see this when using `docker-dev-shell`, in github (under `Insights > Dependency graph > Dependabot`) I only saw

Header (red):

> ⚠️ Dependabot can't parse your integration.yml
> Dependabot failed to update your dependencies because there was an error parsing the integration.yml found at /.github/workflows/workflow.yml.
>
> Dependabot encountered the following error:
>
> Dependabot::DependencyFileNotParseable
> [Learn more](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)

The "log" below contains no useful information regarding the source of the error, all I get is

> updater | INFO Results:
> updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.

### Smallest manifest that reproduces the issue

```yaml
name: :foo
```

**Comment by jeffwidman** [comment]
👋 thanks for the report.

This looks like a duplicate of https://github.com/dependabot/dependabot-core/issues/5453#issuecomment-1205481750.
