### ISSUE TITLE
Confusing message in dependabot vul. alerts when package-lock.json contain multiple versions of the same dependency

### ISSUE THREAD

**Issue by nt-gt** [dependabot/dependabot-core#6288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm

### Language version

node.js

### Updated dependency

Project was using loader-utils/1.4.2 (as the lastest possible version of Dependabot)

Dependabot wanted to upgrade to 2.0.3 due to a vulnerability in 2.0.0

### What you expected to see, versus what you actually saw

I got this warning about a vulnerability (see screenshot)

![image](https://user-images.githubusercontent.com/70640050/206695958-8ee6f9ee-72e5-4185-b290-83aaed821724.png)

As I read the vulnerability, my project is unaffected and cannot be affected, because it is using a "too old" version to be affected.  Therefore, I expected **not** to get a security vulnerability for issue at this time.

**Comment by nt-gt** [comment]
Hi,

The repo is hosted on github but it is private, so I am not sure it helps.

Do you have a non-public way I can transmit the actual details to you?  We do have some unresolved and presumably real dependabot security issues next to this false report.  As I understand it, the requested files would expose those details along with the project that contains them.

**Comment by jamestran201** [comment]
In that case, you can open a ticket through [support.github.com](https://support.github.com/contact) and include the info about your repository, your manifest files, and that you're using github.com. Our support team will help you investigate the issue.

**Comment by nt-gt** [comment]
Thanks, I have created a ticket now (#1951187). :)

**Comment by nt-gt** [comment]
As clarified in the support ticket, I have two versions of `loader-utils` in my `.lock` file.  The line saying `The latest possible version of loader-utils that can be installed is ...` was making  me believe otherwise.

I think the root cause of this issue is that the dependabot security is providing confusing information when this case happens.

I think having a "There are multiple versions of this dependency in the .lock file of this project and at least one of these versions are in the range of affected versions" would have prevented me from thinking this was a false-positive.  Alternatively, removing the `The latest possible version of X that can be installed is ...` when there are multiple versions of the dependency would probably have worked as well in this case (where it is an transitive dependency)

**Comment by jamestran201** [comment]
@nt-gt Thank you for your feedback 🙇 . We'll make a note of this for future improvements. cc: @jeffwidman

**Comment by jeffwidman** [comment]
Thanks @jamestran201 for chiming in here.

@nt-gt sorry about this, completely agree it's painful, I know it's on our radar as we do get regular bug reports of this issue/confusion. I should have realized right away that was the underlying issue here, sorry about that.

**Comment by jeffwidman** [comment]
Related:
* #4222
* https://github.com/dependabot/dependabot-core/issues/5741
