### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6299]
Python 3.6 was [EOL'd in Dec 2021](https://endoflife.date/python). However, we've continued to support it because the Ubuntu LTS `18.04` release installed it by default and `18.04` isn't EOL until April 2023:
https://github.com/dependabot/dependabot-core/blob/cf448a99d35d7956f4c64b8249029324c9627a91/python/lib/dependabot/python/python_versions.rb#L18-L19

But we're starting to run into various issues where `3.6` is forcing us to include hacky workarounds:
* latest versions of most of the python package managers break on `3.6`, including `poetry`, `pip`, `pipenv` and `pip-tools`.
* [Bumping to `22.04` is blocked because `3.6` conflicts with its `openssl` version](https://github.com/dependabot/dependabot-core/pull/5030)

So this is a placeholder ticket to track any discussions around timing, things that we'll need to update/remove, etc.

If you're a user of Dependabot who is still on Python 3.6 and you cannot upgrade for some reason, please chime in here explaining your use case.

**Comment by jeffwidman** [comment]
Before we commit to a timeline on this, we'd like to measure how frequently users are running Dependabot against `python 3.6` repos.

However, the new ["pause for inactivity" feature](https://github.blog/changelog/2023-01-12-dependabot-pull-requests-pause-for-inactivity/) is still gradually rolling out... and that will impact these metrics pretty drastically because abandoned repos that are still running Dependabot are the most likely to have never moved beyond `3.6`.

We expect that rollout to finish in the next few weeks, after which we plan to gather metrics and then work with some other internal stakeholders to decide on the actual date we'll drop support.

**Comment by edgarrmondragon** [comment]
Are there any updates on this? I think this is blocking support for Poetry 1.4.x

**Comment by grski** [comment]
This is a necessary change for https://github.com/dependabot/dependabot-core/pull/6758 AFAIK, or updating Poetry to 1.4.x 
ANy update here or how can one help to make it move faster?

**Comment by jeffwidman** [comment]
Thanks for letting us know you want it, we've been a little hesitant to drop it because we know some users are probably still on `3.6` and we haven't yet had time to pull metrics to see how many users will get left behind when we drop it... so knowing we've got users that are blocked on us upgrading is good to know as a counterpoint.

What we're actually planning to do very soon is try to formalize some deprecation policies for our different ecosystems. That way we not only fix this immediate problem, but also have clear timelines for everyone to see of when we will be deprecating and/or completely dropping support for old versions so there's no surprises for anyone. This is a priority for us this quarter.

Anyway, hope to have you unblocked soonish.

**Comment by phillipuniverse** [comment]
@jeffwidman where are we on those metrics?

Poetry 1.5.1 is out and [1.5.0 has new options for different `sources`](https://github.com/python-poetry/poetry/releases/tag/1.5.0) that are not backwards-compatible with Poetry 1.3.x. Plus some of the existing changes where the lock file can change (the header) when a developer might add a new dependency locally with Poetry 1.5 and Dependabot uses 1.3. There also isn't a great way I know of to lint contributions to ensure local Poetry usage is the same as Dependabot.

**Comment by jeffwidman** [comment]
You'll be happy to know I've got some time booked the next few weeks to work on this... we'll need to post a note on our blog with a deprecation date, so actually merging it may take a little longer. But expect to see PR's from me arriving in the next few weeks to make this happen.

**Comment by jeffwidman** [comment]
We are currently planning to drop support for 3.6 later this month, we'll post an official announcement on the GitHub changelog when we do, but you'll also see it here because once that goes out I'll start merging PR's to remove support for it and then close this issue.

We will also be dropping `3.7` soon after as it's also now EOL:
* https://github.com/dependabot/dependabot-core/issues/7677

**Comment by jeffwidman** [comment]
Deprecation date is August 17th: https://github.blog/changelog/2023-08-02-deprecation-notice-dependabot-to-drop-support-for-python-3-6-and-3-7/

**Comment by grski** [comment]
Thank you!
