### ISSUE TITLE
Option to not display Changelog

### ISSUE THREAD

**Issue by chammik** [dependabot/dependabot-core#6337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a Webhook connecting our GitHub repo to a Microsoft Teams channel, to post in notifications for new Pull Requests. We've noted that some of the notifications don't get posted. Going down the rabbit hole, it appears that there's a limitation on Teams end, where the number of characters in the notification body, can't exceed a certain limit. (I believe it's 50,000). All the notifications that fail to be posted seem to exceed this value.

Would it be possible to implement a feature to choose if we want certain comments to be posted with the Pull Request. For example, not to post in the full Changelog. This way, we can keep the limit under 50,000, for packages that have very long Changelogs.

![image](https://user-images.githubusercontent.com/87511715/208563563-539fa623-8060-44ab-b0a8-8080d92b46c9.png)

**Comment by jeffwidman** [comment]
Hmm... we already truncate the changelog, see this PR for example: https://github.com/dependabot/dependabot-core/pull/6349

And the total number of characters on that changelog subsection is quite low. The entire PR notification including the other metadata sections is only ~20K characters.

Is the changelog on these PR's not getting truncated for some reason? Are you running the native Dependabot on GitHub.com or running `dependabot-core` yourself some other way?

**Comment by chammik** [comment]
> Hmm... we already truncate the changelog, see this PR for example:
> 
> * [Bump rubocop from 1.39.0 to 1.41.0 in /updater #6349](https://github.com/dependabot/dependabot-core/pull/6349)
> 
> And the total number of characters on that changelog subsection is quite low. The entire PR notification including the other metadata sections is only ~20K characters.
> 
> Is the changelog on these PR's not getting truncated for some reason? Are you running the native Dependabot on GitHub.com or running `dependabot-core` yourself some other way?

Thanks for the response @jeffwidman 

It does truncate the comment a fair bit. But still, what's left is quite a lot. I checked the number of characters in the request payload and it's around 50k. Fails when it's over 50k and succeeds when it's just under 50k.

![image](https://user-images.githubusercontent.com/87511715/209236589-4fd41c74-5937-460f-9c45-cb0d2c6d0647.png)

The response body shows this.
![image](https://user-images.githubusercontent.com/87511715/209236691-730ab838-fa95-4ec2-939c-3b87a0e9db54.png)
