### ISSUE TITLE
Dependabot is not updating package-lock when bumping dependencies in a monorepo

### ISSUE THREAD

**Issue by Th3S4mur41** [dependabot/dependabot-core#6346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 8.19.3

### Language version

node 16.19.0

### Manifest location and content before the Dependabot update

package.json
```json
{
	"name": "@atos-parallel/web",
	"private": "true",
	"engines": {
		"node": ">= 16.0.0",
		"npm": ">= 8.0.0"
	},
	"workspaces": [
		"packages/docs"
	],
	"scripts": {
	},
	"devDependencies": {
		"@atos-parallel/release-config": "^1.2.3",
		"@atos-parallel/stylelint-config": "^1.2.0",
		"@babel/core": "^7.20.5",
		"@commitlint/cli": "^17.3.0",
		"@commitlint/config-conventional": "^17.3.0",
		"@percy/cli": "^1.16.0",
		"@typescript-eslint/eslint-plugin": "^5.47.0",
		"@typescript-eslint/parser": "^5.47.0",
		"autoprefixer": "^10.4.13",
		"concurrently": "^7.6.0",
		"cssnano": "^5.1.14",
		"eslint": "^8.30.0",
		"hint": "^7.1.3",
		"husky": "^8.0.2",
		"lint-staged": "^13.1.0",
		"postcss": "^8.4.20",
		"postcss-nesting": "^10.2.0",
		"postcss-preset-env": "^7.8.3",
		"prettier": "^2.8.1",
		"pretty-quick": "^3.1.0",
		"rimraf": "^3.0.2",
		"typedoc": "^0.23.23",
		"typedoc-plugin-markdown": "^3.14.0"
	}
}

```

/packages/docs/package.json

```json
{
	"name": "@atos-parallel/docs",
	"version": "1.4.0",
	"private": true,
	"scripts": {
	},
	"dependencies": {
		"@atos-parallel/icons": "^1.2.12",
		"lit": "^2.5.0"
	},
	"devDependencies": {
		"@babel/core": "^7.20.5",
		"@percy/storybook": "^4.3.4",
		"@storybook/addon-a11y": "^6.5.14",
		"@storybook/addon-actions": "6.5.14",
		"@storybook/addon-docs": "6.5.14",
		"@storybook/addon-essentials": "6.5.14",
		"@storybook/addon-links": "6.5.14",
		"@storybook/addon-postcss": "^2.0.0",
		"@storybook/addons": "6.5.14",
		"@storybook/builder-vite": "^0.2.6",
		"@storybook/theming": "6.5.14",
		"@storybook/web-components": "6.5.14",
		"babel-loader": "^9.1.0",
		"postcss": "^8.4.20",
		"storybook-addon-designs": "^6.3.1"
	},
	"peerDependencies": {
		"@atos-parallel/components": "1.1.1"
	}
}

```

### dependabot.yml content

```yaml
version: 2

registries:
  github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DEPENDABOT_TOKEN}}

updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    registries: '*'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Europe/Berlin'
```

### Updated dependency

@storybook/builder-vite from 0.2.5 to 0.2.6

### What you expected to see, versus what you actually saw

Dependabot should update @storybook/builder-vite to version 0.2.6 in package.json in the 'docs' workspace and the package-lock.json in the root of the monorepo.
The package-lock.json is not updated though

### Native package manager behavior

package-lock.json in the root of the monorepo is updated too.

### Images of the diff or a link to the PR, issue, or logs

![image](https://user-images.githubusercontent.com/5543595/208656997-ae51b9bc-e6ac-44d1-8bcb-0ff739982909.png)

https://github.com/atos-parallel/web/pull/699

**Comment by deivid-rodriguez** [comment]
@Th3S4mur41 Would it be possible for you to create an open source repo with this problem? That would make it easier to fix.

**Comment by Th3S4mur41** [comment]
@deivid-rodriguez I tried to reproduce the issue in [another monorepo](https://github.com/Th3S4mur41/demo-monorepo/pull/38)
Unfortunately, in this case it worked as expected.

Is there anything else I can provide to help you investigate what might have been a glitch?

**Comment by Th3S4mur41** [comment]
Facing the issue again in the same repo with the [next update of same dependency](https://github.com/atos-parallel/web/pull/729) 🤔

![image](https://user-images.githubusercontent.com/5543595/212058447-9b8e7e94-639f-40e4-a2ee-0fbda9f7697c.png)

I tried `dependabot recreate` but the outcome is the same...

Running `npm i` on the dependabot branch in my codespaces makes the update to package-lock.json

[Same update on the demo monorepo](https://github.com/Th3S4mur41/demo-monorepo/pull/42) went through and updated both 😒

**Comment by deivid-rodriguez** [comment]
I have little experience with npm so my intuition in this ecosystem is low. But I guess I would try figuring out the differences between the demo monorepo. For example, it seems that your public demo does not use registries in dependabot configuration, could that be related?

**Comment by Th3S4mur41** [comment]
Good point, let me try to add that to the demo.
However, this is not a global issue... All other dependencies in the problem repo are updated by dependabot just fine.
So far this happend twice, each time only with the one dependency

**Comment by Th3S4mur41** [comment]
@deivid-rodriguez [demo repo updated](https://github.com/Th3S4mur41/demo-monorepo/commit/e538cd362ae44af77b927cd2c308485031a06823) to reflect also this aspect:

**Comment by Th3S4mur41** [comment]
Even with the added dependencies from a different registry and dependabot also using GitHub package registries, the issue is still not reproducible.
[bump @storybook/builder-vite from 0.2.7 to 0.3.0](https://github.com/Th3S4mur41/demo-monorepo/pull/53) worked fine in the demo repo, but still missed to update the package lock in the private repo 🤔

**Comment by deivid-rodriguez** [comment]
That's too bad 😢. There must be something different between those setups that's triggering the issue, we need to figure out what that is 🤔.

**Comment by azuwey** [comment]
I ran into the same issue, here is my repository: https://github.com/azuwey/supreme-memory

A potential solution could be to specify the lock file location, because it is different than the `package.json` file's location, because I think the problem is that dependabot doesn't find the lock file in the project.

**Comment by Th3S4mur41** [comment]
Right, the [jsdom PR](https://github.com/azuwey/supreme-memory/pull/4) looks very similar to what I'm seeing.
@deivid-rodriguez is there a way to pull logs or something that would be helpful?

**Comment by deivid-rodriguez** [comment]
Now that we have open source repositories reproducing this, it should be easier to figure out. In any case you should be able to see logs at the "Insights > Dependency Graph > Dependabot" page.

**Comment by azuwey** [comment]
@deivid-rodriguez Okay, I checked it, and the `package-lock.json` is not there, it does detected the `package.json` in the root.

**Comment by azuwey** [comment]
@deivid-rodriguez So I checked it, and it seems that, it doesn't detect the dependencies in the `package-lock.json`, `Insights > Dependency Graph > Dependencies > package-lock.json` says: `package-lock.json has no dependencies or is too large to display`, under the `Dependabot` tab I can see  the `package-lock.json` by clicking on the three dot next to the `package.json` label (`Monitored dependency files`).

What should I look for in the logs?

**Comment by deivid-rodriguez** [comment]
I'm not sure, I tried this locally and the logs don't tell me much. But at least I can reproduce things locally now.

**Comment by Th3S4mur41** [comment]
This time it happend in my [demo repo](https://github.com/Th3S4mur41/demo-monorepo/pull/61) too

**Comment by svenjacobs** [comment]
I'm facing the same issue. Unfortunately this is a commercial project so I can't share any code.

We have the following monorepo structure utilizing [npm workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces)

```
project-1/package.json
project-2/package.json
package.json
package-lock.json
```

so there is only one `package-lock.json` at the root of the repo.

This is our `.github/dependabot.yml`:

```yaml
version: 2
updates:
    - package-ecosystem: 'npm'
      directory: 'project-1'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '09:00'
          timezone: 'Europe/Berlin'
      versioning-strategy: increase
      labels:
          - 'dependencies'
      ignore:
          - dependency-name: '@types/node'
      assignees:
          - 'dev1'
          - 'dev2'

    - package-ecosystem: 'npm'
      directory: 'project-2'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '09:00'
          timezone: 'Europe/Berlin'
      versioning-strategy: increase
      labels:
          - 'dependencies'
      assignees:
          - 'dev1'
          - 'dev2'
```

I think it would help if Dependabot performs a `npm install --package-lock-only` after modifying any `package.json` and adding the modified `package-lock.json` to the commit afterwards.

**Comment by SpiritusDeos** [comment]
Is someone success to setup dependabot with a monorepo and to update the correct yarn.lock (regarding which directory the package is updated) ?

**Comment by Develliot** [comment]
I have a monorepo using NPM workspaces, with a similar set up to @svenjacobs but with 4 packages. 
My dependabot.yml targets the route directory `directory: '/'` for NPM updates. 
Some workspaces have no issues, when a dependencies are bumped the  in a workspace package.json file the shared repo lockfile gets bumped too. However with 4th and last listed workspace dependabot bumps the deps in the workspace package.json but the shared repo lockfile never updates.
I can't see any obvious differences in the workspace package.json files. All workspaces were created with the `npm init -w` command. 
In the shared package.json file I can see all workspaces listed in the same manor. At the moment I'm not sure why dependabot has an issue with the last work space.

**Comment by Snailedlt** [comment]
Happens to me too here: https://github.com/Snailedlt/Markdown-Videos/pull/132

Though I'm using pnpm instead of npm

**Comment by logseq-cldwalker** [comment]
@deivid-rodriguez Hi. We're also experiencing this on a public, monorepo project. We don't have a dependabot.yml. https://github.com/logseq/logseq/pull/10079 is an example of a PR that didn't update yarn.lock

**Comment by deivid-rodriguez** [comment]
Thank you. This issue is actionable now since several repros have been shared. Only thing needed is someone to work on it.

We have not prioritized this internally yet but anybody interested on a fix is welcome to get the repo setup for development and investigate.

**Comment by tunessofia** [comment]
i have been also experiencing this issue in a project where we currently upgraded to node 20.x. does this might be due to dependabot using node 16 and the lock file is generated with another npm version? and cannot upgrade it? looking at the logs it doesnt display any errors or warnings

**Comment by DerTimonius** [comment]
I looked into this a bit, since we are facing this issue on a closed source project. I noticed that the updates of the lockfiles are happening if one of the following conditions are true:
- the package is found in the root `packagen.json`
- the package is used in multiple subdirectories of the monorepo

If the package is found in something like `apps/web/package.json` the lockfile is not updated.

I would be open to help with this issue, but I never used Ruby before. So the members might have to be patient with me 🙂

**Comment by DerTimonius** [comment]
So, I ran the dry-run script on the provided monorepos, but it only recognized the root package.json file, it did not go deeper

**Comment by deivid-rodriguez** [comment]
Cool. Can you show how workspaces are setup?

**Comment by thavaahariharangit** [comment]
Started Analyzing

**Comment by thavaahariharangit** [comment]
TODO: 28112024

1. Recreate the above issue
2. [Verify this PR updates fixes the issue](https://github.com/dependabot/dependabot-core/pull/10806)
3. If yes Deploy and merge the PR
4. Close the ticket

###  Recreate the above issue

**Comment by thavaahariharangit** [comment]
@deivid-rodriguez Based on my analysis this is default behavior of the pnpm install, Why this should be updated.

In a pnpm monorepo setup, the pnpm-lock.yaml file is created at the root of the repository by design. This is because pnpm uses a single lockfile to manage dependencies for the entire monorepo, ensuring consistency and avoiding duplication of dependencies across different workspaces.  

If you want to understand or change this behavior, you can refer to the pnpm documentation on monorepos and lockfiles. However, it is generally recommended to keep the lockfile at the root for the reasons mentioned above.  

Here is a brief explanation of the pnpm monorepo setup:  

1. **Root pnpm-lock.yaml:** This lockfile ensures that all workspaces in the monorepo use the same versions of dependencies, which helps in maintaining consistency and reducing disk space usage.  
2. **Workspace Configuration**: The pnpm-workspace.yaml file at the root defines the structure of the monorepo and lists the workspaces.  

Example **pnpm-workspace.yaml**:
```
packages:
  - 'packages/*'
  - 'workspaces/*'
```

FYI @abdulapopoola

**Comment by thavaahariharangit** [comment]
Below are steps verify the pnpm default behavior.

1. Initialize the root project:  
```
mkdir my-monorepo
cd my-monorepo
pnpm init
```
2. Create a pnpm-workspace.yaml file:  
```
packages:
  - 'packages/*'
 ```
3. Add workspaces:  
```
mkdir -p packages/project-a
mkdir -p packages/project-b
cd packages/project-a
pnpm init
cd ../project-b
pnpm init
cd ../../
```
4. Install dependencies:  
```pnpm install```

This will create a pnpm-lock.yaml file at the root and manage dependencies for all workspaces defined in the pnpm-workspace.yaml file.

**Comment by thavaahariharangit** [comment]
> Sorry, I completely lost track of this now, of course. From a quick diagonal reading, my understanding is that Dependabot was not updating the root lockfile, and that seemed like a valid bug to me. And it sounds like a few repros where shared, but I cannot add much to the discussion, really.

As per my reading they are saying other way around, root pnpm-lock.yaml file is being updated But internal project pnpm-lock.yml is not. But anyway I got another update here https://github.com/dependabot/dependabot-core/pull/10806#issuecomment-2506345133 I will check that and see what I can do on that.

**Comment by mattiasw** [comment]
@thavaahariharangit I think @deivid-rodriguez is correct in that it's the root lock file that is not updated. The description of this issue states "Dependabot should update [...] the package-lock.json in the root of the monorepo. The package-lock.json is not updated though", and that is what I'm experiencing too.

**Comment by thavaahariharangit** [comment]
TODO: 29112024

Recreate this for PNPM - In Progress
In dependabot config, directory should point to the workspace instead of root
dependabot.yml
```
directories:
      - /apps/*
```

**Comment by mattiasw** [comment]
@thavaahariharangit My problem is not with pnpm, and not for the reporter of this issue either as I understand it from the description, but with npm and `package-lock.json`.  I will try to get some time the coming week and see if I can create a repro. I noticed that all the dependabot PRs that were created this morning in my monorepo project failed so I can probably use that as a start (private repo unfortunately).

**Comment by thavaahariharangit** [comment]
@mattiasw and @Th3S4mur41 

I have tested the same with npm repo and it's working as same as pnpm.

https://github.com/dsp-testing/npm_monorepo_sample

I am trying to understand the problem to fix. Please review my repo and let me know what am I missing here.

**Comment by Th3S4mur41** [comment]
> @mattiasw and @Th3S4mur41
> 
> I have tested the same with npm repo and it's working as same as pnpm.
> 
> https://github.com/dsp-testing/npm_monorepo_sample
> 
> I am trying to understand the problem to fix. Please review my repo and let me know what am I missing here.

There should not be a `package-lock.json` under packages/package-a, only in the root of your project.
Otherwise, it looks correct.

At least in my case, this issue was not easy to reproduce either.
It only happend with certain PRs, but definitely not all.

The following was e.g. one PR where the issue happend and the package-lock was not updated as expected:
https://github.com/Th3S4mur41/demo-monorepo/pull/61 

I haven't seen the error in my demo repo for quite some time now.
The only things that changed are:
- grouped dependabot update: the one dependency that seem to regularly trigger the issue is now being updated together with other storybook dependencies
- NodeJS: at the time of the report, it was using Node 16, LTS is now 20
- **Dependabot on Actions runners** is now active

**Comment by thavaahariharangit** [comment]
I am closing this, as it won't reproducible and it can be reopened if it occurs again in the future.

**Comment by chrisvander** [comment]
@mattiasw I've been wondering why it wasn't working. I also have "packageManager" set, as Nx looks for it. Why would that impact Dependabot's ability to update lockfiles?

**Comment by mattiasw** [comment]
@chrisvander I have no idea. But the solution for me was to remove the `^` at the beginning of the string. It's not allowed according to the specs, it should be an exact version, e.g. `npm@10.8.2`.

**Comment by zimeg** [comment]
👋 We're running into this issue with https://github.com/slackapi/slack-health-score/pull/97 when attempting to [update](https://github.com/slackapi/slack-health-score/blob/6b4792ed6b3ae0a8e852c93bdecd2e57d0a48e35/.github/dependabot.yml#L3-L9) a package from within nested `directories` while using the `increase` versioning strategy:

```yaml
- package-ecosystem: "npm"
  directories:
    - "/"
    - "/.api/apis/codecov"
  schedule:
    interval: "monthly"
  versioning-strategy: increase
```

🤖 When running the `npm install` command after the current [updater](https://github.com/slackapi/slack-health-score/actions/runs/15376840209/job/43262579933#step:3:754) command of that PR the following `diff` appears:

<details>
<summary>diff</summary>

```diff
diff --git a/package-lock.json b/package-lock.json
index 1a7aa69..f5df97d 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -32,7 +32,7 @@
       "dependencies": {
         "api": "^6.1.3",
         "json-schema-to-ts": "^3.1.1",
-        "oas": "^27.0.0"
+        "oas": "^27.0.1"
       }
     },
     ".api/apis/codecov/node_modules/@readme/better-ajv-errors": {
@@ -56,12 +56,12 @@
       }
     },
     ".api/apis/codecov/node_modules/@readme/openapi-parser": {
-      "version": "4.0.0",
-      "resolved": "https://registry.npmjs.org/@readme/openapi-parser/-/openapi-parser-4.0.0.tgz",
-      "integrity": "sha512-TYeEjSYGCmaBjvQA+BcQYjfv4k+02oychlRHShj/3Iwm2s+a+isENeJU/HPgxIZqtKuP2JZ0gJTvBXo9ci4NEg==",
+      "version": "4.1.0",
+      "resolved": "https://registry.npmjs.org/@readme/openapi-parser/-/openapi-parser-4.1.0.tgz",
+      "integrity": "sha512-zZaGaOJ+0bYPGkPK4ekspE1BoO1iifxe5d3rsAE6AqFCoyHCjt/xMDtmJpy4slFdd1YtEv/VHhBpB1FlNClCNw==",
       "license": "MIT",
       "dependencies": {
-        "@apidevtools/json-schema-ref-parser": "^12.0.1",
+        "@apidevtools/json-schema-ref-parser": "^13.0.1",
         "@readme/better-ajv-errors": "^2.3.2",
         "@readme/openapi-schemas": "^3.1.0",
         "@types/json-schema": "^7.0.15",
@@ -107,12 +107,12 @@
       }
     },
     ".api/apis/codecov/node_modules/oas": {
-      "version": "27.0.0",
-      "resolved": "https://registry.npmjs.org/oas/-/oas-27.0.0.tgz",
-      "integrity": "sha512-5ibKLmhWytJhi/ZIPUfFu3aSTH4LSE4zLAe/uWUSWbI6ijz/BqMKgnelpwPffJDAooWcJ0pP7KjskB/MNDhCGg==",
+      "version": "27.1.0",
+      "resolved": "https://registry.npmjs.org/oas/-/oas-27.1.0.tgz",
+      "integrity": "sha512-K1qOiNguPMTRG52pboD1xyNPvdg1DImxjKXDjSTXe/4NVzXosYrLsDw9T3N82HFSlsGqOyXNAfPpZ80VYcDedw==",
       "license": "MIT",
       "dependencies": {
-        "@readme/openapi-parser": "^4.0.0",
+        "@readme/openapi-parser": "^4.1.0",
         "@types/json-schema": "^7.0.11",
         "json-schema-merge-allof": "^0.8.1",
         "jsonpath-plus": "^10.0.0",
@@ -201,12 +201,11 @@
       "link": true
     },
     "node_modules/@apidevtools/json-schema-ref-parser": {
-      "version": "12.0.1",
-      "resolved": "https://registry.npmjs.org/@apidevtools/json-schema-ref-parser/-/json-schema-ref-parser-12.0.1.tgz",
-      "integrity": "sha512-D3n3T19ly/RYyEvsrqKa/cSAlzQF8KXj1o0XLTI+9GKnJvdHT3WW50yZYCf+4JU7+pLlhXZVV1q1AJ0SPN/pmw==",
+      "version": "13.0.5",
+      "resolved": "https://registry.npmjs.org/@apidevtools/json-schema-ref-parser/-/json-schema-ref-parser-13.0.5.tgz",
+      "integrity": "sha512-xfh4xVJD62gG6spIc7lwxoWT+l16nZu1ELyU8FkjaP/oD2yP09EvLAU6KhtudN9aML2Khhs9pY6Slr7KGTES3w==",
       "license": "MIT",
       "dependencies": {
-        "@jsdevtools/ono": "^7.1.3",
         "@types/json-schema": "^7.0.15",
         "js-yaml": "^4.1.0"
       },
```

</details>

Which seems to show the top-level `package-lock.json` file isn't included in the created PR? Related [logs](https://github.com/slackapi/slack-health-score/actions/runs/15376840209/job/43262579933#step:3:733) for this job appear here:

<details>
<summary>logs</summary>

```txt
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Requirements to unlock own
2025/06/01 15:53:16 INFO <job_1025324069> Requirements update strategy bump_versions
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Updating oas from 27.0.0 to 27.0.1
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2143 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/tmp/20250601-1647-1b26je/dependabot_20250601-1647-8bojor/git.store' {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2143 completed with status: pid 2143 exit 0
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.01 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2151 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2151 completed with status: pid 2151 exit 0
2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2158 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2158 completed with status: pid 2158 exit 0
2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2164 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2164 completed with status: pid 2164 exit 0
2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2171 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2171 completed with status: pid 2171 exit 0
2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2178 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Process PID: 2178 completed with status: pid 2178 exit 0
2025/06/01 15:53:16 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:16 INFO <job_1025324069> Started process PID: 2185 with command: {} npm install oas@27.0.1 --force --dry-run false --ignore-scripts --package-lock-only {}
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Process PID: 2185 completed with status: pid 2185 exit 0
2025/06/01 15:53:17 INFO <job_1025324069> Total execution time: 0.61 seconds
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Started process PID: 2197 with command: {} git status --untracked-files all --porcelain v1 .api/apis/codecov {}
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Process PID: 2197 completed with status: pid 2197 exit 0
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Total execution time: 0.01 seconds
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Started process PID: 2204 with command: {} git status --untracked-files all --porcelain v1 .api/apis/codecov/.yarn/cache {}
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Process PID: 2204 completed with status: pid 2204 exit 0
2025/06/01 15:53:17 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Started process PID: 2211 with command: {} git status --untracked-files all --porcelain v1 .api/apis/codecov/.yarn/install-state.gz {}
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Process PID: 2211 completed with status: pid 2211 exit 0
2025/06/01 15:53:17 INFO <job_1025324069> Total execution time: 0.0 seconds
updater | 2025/06/01 15:53:17 INFO <job_1025324069> Submitting oas pull request for creation
  proxy | 2025/06/01 15:53:17 [165] GET [https://api.github.com:443/repos/slackapi/slack-health-score/commits?per_page=100](https://api.github.com/repos/slackapi/slack-health-score/commits?per_page=100)
2025/06/01 15:53:17 [165] 200 [https://api.github.com:443/repos/slackapi/slack-health-score/commits?per_page=100](https://api.github.com/repos/slackapi/slack-health-score/commits?per_page=100)
  proxy | 2025/06/01 15:53:17 [167] GET https://registry.npmjs.org/oas/latest
  proxy | 2025/06/01 15:53:17 [167] 200 https://registry.npmjs.org/oas/latest
  proxy | 2025/06/01 15:53:17 [169] GET [https://api.github.com:443/repos/readmeio/oas/releases?per_page=100](https://api.github.com/repos/readmeio/oas/releases?per_page=100)
2025/06/01 15:53:17 [169] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:18 [169] 200 [https://api.github.com:443/repos/readmeio/oas/releases?per_page=100](https://api.github.com/repos/readmeio/oas/releases?per_page=100)
  proxy | 2025/06/01 15:53:18 [171] GET [https://api.github.com:443/repos/readmeio/oas/contents/packages/oas](https://api.github.com/repos/readmeio/oas/contents/packages/oas)
2025/06/01 15:53:18 [171] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:18 [171] 200 [https://api.github.com:443/repos/readmeio/oas/contents/packages/oas](https://api.github.com/repos/readmeio/oas/contents/packages/oas)
  proxy | 2025/06/01 15:53:18 [173] GET [https://api.github.com:443/repos/readmeio/oas/contents/](https://api.github.com/repos/readmeio/oas/contents/)
  proxy | 2025/06/01 15:53:18 [173] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:18 [173] 200 [https://api.github.com:443/repos/readmeio/oas/contents/](https://api.github.com/repos/readmeio/oas/contents/)
  proxy | 2025/06/01 15:53:18 [175] GET https://github.com/readmeio/oas.git/info/refs?service=git-upload-pack
  proxy | 2025/06/01 15:53:18 [175] 200 https://github.com/readmeio/oas.git/info/refs?service=git-upload-pack
  proxy | 2025/06/01 15:53:18 [177] GET [https://api.github.com:443/repos/readmeio/oas/contents/packages/oas?ref=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/contents/packages/oas?ref=oas%4027.0.1)
  proxy | 2025/06/01 15:53:18 [177] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:18 [177] 200 [https://api.github.com:443/repos/readmeio/oas/contents/packages/oas?ref=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/contents/packages/oas?ref=oas%4027.0.1)
  proxy | 2025/06/01 15:53:18 [179] GET [https://api.github.com:443/repos/readmeio/oas/contents/?ref=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/contents/?ref=oas%4027.0.1)
2025/06/01 15:53:18 [179] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:18 [179] 200 [https://api.github.com:443/repos/readmeio/oas/contents/?ref=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/contents/?ref=oas%4027.0.1)
  proxy | 2025/06/01 15:53:18 [181] GET https://github.com/readmeio/oas.git/info/refs?service=git-upload-pack
2025/06/01 15:53:18 [181] 200 https://github.com/readmeio/oas.git/info/refs?service=git-upload-pack
  proxy | 2025/06/01 15:53:19 [183] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
2025/06/01 15:53:19 [183] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:19 [183] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
  proxy | 2025/06/01 15:53:19 [185] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
2025/06/01 15:53:19 [185] * authenticating github api request with token for api.github.com
  proxy | 2025/06/01 15:53:19 [185] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
  proxy | 2025/06/01 15:53:19 [187] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
2025/06/01 15:53:19 [187] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
  proxy | 2025/06/01 15:53:19 [189] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
2025/06/01 15:53:19 [189] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
  proxy | 2025/06/01 15:53:19 [191] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
2025/06/01 15:53:19 [191] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.0)
  proxy | 2025/06/01 15:53:19 [193] GET [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
2025/06/01 15:53:19 [193] 200 [https://api.github.com:443/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1](https://api.github.com/repos/readmeio/oas/commits?path=packages%2Foas&sha=oas%4027.0.1)
  proxy | 2025/06/01 15:53:20 [195] GET https://registry.npmjs.org/oas
2025/06/01 15:53:20 [195] 200 https://registry.npmjs.org/oas
  proxy | 2025/06/01 15:53:20 [197] POST /update_jobs/1025324069/create_pull_request
  proxy | 2025/06/01 15:53:20 [197] 204 /update_jobs/1025324069/create_pull_request
  proxy | 2025/06/01 15:53:20 [199] POST /update_jobs/1025324069/record_ecosystem_meta
2025/06/01 15:53:20 [199] 204 /update_jobs/1025324069/record_ecosystem_meta
```

</details>

👾 Right now this causes our CI tests to fail when using `npm clean-install` even without a set `packageManager` though we do have these [`engines`](https://github.com/slackapi/slack-health-score/blob/6b4792ed6b3ae0a8e852c93bdecd2e57d0a48e35/package.json#L30-L33) set:

```json
{
  "engines": {
    "node": ">=20.0.0",
    "npm": ">=10.2.0"
  }
}
```

**Comment by marcomura** [comment]
@thavaahariharangit Here's another repro for this:
https://github.com/atlassian/atlascode/pull/908

**Comment by spuxx-dev** [comment]
> [@chrisvander](https://github.com/chrisvander) I have no idea. But the solution for me was to remove the `^` at the beginning of the string. It's not allowed according to the specs, it should be an exact version, e.g. `npm@10.8.2`.

This is sadly not always helping, as seen [here](https://github.com/spuxx-dev/jslibs/pull/513/changes).

I still randomly bump into this issue on maybe 20% of Dependabot PRs and I kinda fail to see a pattern.

**Comment by spuxx-dev** [comment]
@thavaahariharangit can we please re-open? I think there's plenty of repros mentioned in this thread.
