### ISSUE TITLE
 Unexpected update strategy: bump_versions_if_necessary with pyproject.toml

### ISSUE THREAD

**Issue by jenshnielsen** [dependabot/dependabot-core#6371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Python

### Language version

3.8->3.11

### Manifest location and content before the Dependabot update

In out project https://github.com/QCoDeS/Qcodes we have the dependencies specified in pyproject.toml pep621 + requirements.txt that we use as a constraint file. Here https://github.com/QCoDeS/Qcodes/blob/master/pyproject.toml and here https://github.com/QCoDeS/Qcodes/blob/master/requirements.txt

### dependabot.yml content

version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  rebase-strategy: "disabled"
  versioning-strategy: increase-if-necessary
- package-ecosystem: github-actions
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: "daily"

### Updated dependency

pyvisa pinned to <1.13 in pyproject.toml and specified as 1.12.0 in requirements.txt which we use as a constraint file

`pip install . -c reqirements.txt`

On the release of pyvisa 1.13 we are seeing the error below.

### What you expected to see, versus what you actually saw

I would expect dependabot to generate a pr updating the version of pyvisa to <1.14 in pyproject.toml and ~= 1.14.0 in requirements.txt instead I see the error below. 

### Native package manager behavior

N/A this requires manual editing of the pyproject.toml file

### Images of the diff or a link to the PR, issue, or logs

Error message
```
updater | ERROR <job_566012759> Error processing pyvisa (RuntimeError)
updater | ERROR <job_566012759> Unexpected update strategy: bump_versions_if_necessary
updater | ERROR <job_566012759> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:91:in `updated_pyproject_requirement'
updater | ERROR <job_566012759> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:36:in `block in updated_requirements'
updater | ERROR <job_566012759> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:33:in `map'
updater | ERROR <job_566012759> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:33:in `updated_requirements'
updater | ERROR <job_566012759> /home/dependabot/python/lib/dependabot/python/update_checker.rb:96:in `updated_requirements'
updater | ERROR <job_566012759> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:292:in `changed_requirements'
updater | ERROR <job_566012759> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:306:in `requirements_can_update?'
updater | ERROR <job_566012759> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:49:in `can_update?'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:486:in `requirements_to_unlock'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:259:in `check_and_create_pull_request'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_566012759> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_566012759> bin/update_files.rb:23:in `<main>'
```

full log is here 
https://github.com/QCoDeS/Qcodes/network/updates/566012759

**Comment by deivid-rodriguez** [comment]
Hi @jenshnielsen, thanks for the report!

Apparently the `increase-if-necessary` strategy is not yet supported for PEP621 projects. I'm not sure why we did not add support for it from the very beginning but I suspect it's because we started that feature _before_ support for the `increase-if-necessary` strategy for Python landed.

Anyways, it should not be hard to add I believe, stay tuned!
