### ISSUE TITLE
Remote - Containers extension is now called Dev Containers

### ISSUE THREAD

**Issue by adrianferenc** [dependabot/dependabot-core#6374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

In the readme the "Remote - Containers extension" is mentioned. It is now called Dev Containers. References to Remote - Containers should be changed to Dev Containers. cf https://code.visualstudio.com/docs/devcontainers/containers

**Comment by jeffwidman** [comment]
Sounds reasonable, care to submit a PR?
