### ISSUE TITLE
Label development dependencies

### ISSUE THREAD

**Issue by Borewit** [dependabot/dependabot-core#6378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Provide the means to assign an extra, or different label to dependencies in the development group.

This enables to easily differentiate between PR's created by Dependabot.

This could be very handy to exclude development dependency updates from the release notes generated by the [release-drafter plugin](https://github.com/release-drafter/release-drafter)

Similar request, but not exactly the same as  #3647

**Comment by jeffwidman** [comment]
Does the solution described here work for you? https://github.com/dependabot/dependabot-core/issues/2294#issuecomment-854841028

That's probably the most flexible way to handle this...

**Comment by Borewit** [comment]
> Does the solution described here work for you? https://github.com/dependabot/dependabot-core/issues/2294#issuecomment-854841028

It does! Thank you so much @jeffwidman.

Using the https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs I could replace the "dependenies" tag with a "dev-dependencies" tag for non-production dependencies.

Change reflecting that implementation: https://github.com/Borewit/music-metadata/commit/be7a11a634ab690508b3a2fd42647f9584df789a
