### ISSUE TITLE
Nullpointer in Multi-Module Gradle project

### ISSUE THREAD

**Issue by sconvent** [dependabot/dependabot-core#6384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

7.6

### Manifest location and content before the Dependabot update

`/settings.gradle.kts`
`/top-level-module/settings.gradle.kts`
`/sub-module/settings.gradle.kts`

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
 ```

### What you expected to see, versus what you actually saw

That Dependabot does not run into a Nullpointer

### Smallest manifest that reproduces the issue

A simple demonstration can be found here: https://github.com/sconvent/dependabot-issue-demonstrator/tree/addf67d1aa51dade24e47d1043abbd0baa54332a

It is a multi-module setup (no source code for simplicity, just the Gradle scripts).

### Further comments

An excerpt from the Dependabot logs: 

```
updater | ERROR <job_569618656> undefined method `name' for nil:NilClass
updater | <job_569618656> 
updater | <job_569618656>           return @properties[buildfile.name] if @properties[buildfile.name]
updater | <job_569618656>                                                                      ^^^^^
updater | ERROR <job_569618656> /home/dependabot/gradle/lib/dependabot/gradle/file_parser
```

The problem seems to be that the Dependabot wants to look into a file that doesn't exist. And it's probably the 'build.gradle.kts' in the root folder. This repo without that file is definitely a valid Gradle setup, however.

There are two possible workarounds:
One is to just add an empty 'build.gradle.kts' at the root level. See here: https://github.com/sconvent/dependabot-issue-demonstrator/tree/ee9a20024f19216dd036dc9edfa8b6991e4c80ee
The Dependabot output is fine then.

The other workaround is to remove a Kotlin-style reference to a constant string in a dependency string.
See here for the setup: https://github.com/sconvent/dependabot-issue-demonstrator/commit/a4f2683b6f40939228a0f04b277f26bdbf949745
Again, Dependabot output is fine

Would be great if someone could look into this. I guess its fine if Dependabot cannot work with certain Kotlin features but should not cause a nullpointer.

**Comment by jeffwidman** [comment]
Makes sense, we've got some edge-case gaps in our Gradle / Java coverage. Thanks for the detailed demonstration plus suggesting a couple of solutions... we're not always experts in all the various ecosystems we support, so we really appreciate it.

**Comment by jeffwidman** [comment]
Fixed by https://github.com/dependabot/dependabot-core/pull/6392
