### ISSUE TITLE
Monkey patching docker_registry2 not needed anymore

### ISSUE THREAD

**Issue by vpereira** [dependabot/dependabot-core#6386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

Looking through dependabot-core code base, i found this https://github.com/dependabot/dependabot-core/blob/0603ec94756a975b2ea928acf7a74213198599be/docker/lib/dependabot/docker/update_checker.rb#L13

which isn't necessary anymore since this PR that I pushed upstream:

https://github.com/deitch/docker_registry2/pull/73/files#diff-961c38a1acd96d2d05d53ecbf841e7366cffc4691e0a33edf6ab38fc1b45b8fe

Happy hacking 🚀

**Comment by jeffwidman** [comment]
Awesome, well done!

Care to submit a PR? Should be trivial since you're super familiar with this code already.
