### ISSUE TITLE
Wrong sha256 hash in Pipfile.lock 

### ISSUE THREAD

**Issue by cponfick-bhs** [dependabot/dependabot-core#6407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

Python 3.9

### What you expected to see, versus what you actually saw

If a dependency is updated in the Pipfile.lock only that dependency is updated. The meta information is not updated. Hence, the _meta.hash.sha256 hash stays the same. I would expect a new sha256 hash.

**Comment by deivid-rodriguez** [comment]
Hello @cponfick-bhs, thanks for reporting this. Can you share a public repository or some example `Pipfifle` and `Pipfile.lock` file that exhibit this issue? I did some simple tests and hashes were correctly updated.

**Comment by cponfick-bhs** [comment]
@deivid-rodriguez Sry, I just checked pipenv seems like the _meta hash is based on the Pipfile. I thought it is based on the package hashes.
