### ISSUE TITLE
Ruby/Bundler ecosystem checks for development dependencies in gems

### ISSUE THREAD

**Issue by brcarp** [dependabot/dependabot-core#6411]
### Package ecosystem

Bundler

### Package manager version

2.3

### What you expected to see, versus what you actually saw

When Dependabot was checking for updates, it produced a `Dependabot can't resolve your Ruby dependency files` error. More specifically: `Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "rails"`.

However, it was complaining because a gem depended on an older version of `rails` _for development_, in other words there was a pinned version of `rails` in the `gemspec`  but as `add_development_dependency`, and that version didn't resolve with the version of `rails` in the application that included that gem. But it's irrelevant: if I'm using the gem but not developing for it, I don't care what the development dependencies are. This feels like a bug in the dependency check.

**Comment by deivid-rodriguez** [comment]
Hi @brcarp, thanks for reporting this.

Can you share some dependency files to illustrate the issue, i.e., contents of gemspec file, Gemfile file and (if any) Gemfile.lock file. And also a diff of the update you would've expected.

Thanks!

**Comment by brcarp** [comment]
Hi @deivid-rodriguez, in this case the gem in question includes the following in its `gemspec` file:

```ruby
Gem::Specification.new do |gem|
  # [...]

  gem.add_dependency 'activesupport'
  # [... more dependencies]

  gem.add_development_dependency 'simplecov'
  gem.add_development_dependency 'rake'
  gem.add_development_dependency 'rails', '~> 3.2'
  # [... more _development_ dependencies]

end
```

That development dependency is likely outdated and ignore by the developers, but if I'm including that gem, I shouldn't have to care about that! When I ran Dependabot checker through the web UI, I got the following error:

```
Dependabot encountered the following error (for a Rails 5 app that itself needs updating to a newer version of Rails, but that's also besides the point):

Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (>= 5.1.7, <= 7.0.4)

    gem_in_question (= 0.0.15) was resolved to 0.0.15, which depends on
      rails (~> 3.2)
```

**Comment by andreas-venturini** [comment]
This is actually a pretty significant bug of the GitHub package registry, not Dependabot.

This just happens to break Dependabot in cases where the development dependencies of multiple gems (to be bundled from the GitHub package registry) are incompatible (e.g. one gem that dependabot checks could declare `spec.add_development_dependency "rake", "~> 10.0"` and another `spec.add_development_dependency "rake", "~> 13.0"`)

**Comment by brcarp** [comment]
> This is actually a pretty significant bug of the GitHub package registry, not Dependabot.

Interesting. Should I have created this issue elsewhere? I'm not sure where it goes from here.

**Comment by andreas-venturini** [comment]
I assume you are using the GitHub package registry for Ruby gems? In this case you can verify my assumption by running `bundle update` locally - this should also result in the above error

> Should I have created this issue elsewhere? I'm not sure where it goes from here.

I don't know, I think GitHub staff might be able to forward this to the GitHub package registry team.

**Comment by brcarp** [comment]
> I assume you are using the GitHub package registry for Ruby gems? In this case you can verify my assumption by running `bundle update` locally - this should also result in the above error

You're right! Specifically trying to update the gems from the package registry produces this error. Yikes!

**Comment by brcarp** [comment]
Already a discussion on the topic:

https://github.com/orgs/community/discussions/43861

**Comment by jeffwidman** [comment]
Thanks for the heads up / deeper digging. I pinged the packages team with a link to the community discussion ☝️.

There's nothing we can really do on the Dependabot side, so closing this, please follow that community discussion for updates.
