### ISSUE TITLE
How to use dependabot to run pre-script

### ISSUE THREAD

**Issue by YangJiao0817** [dependabot/dependabot-core#6414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I setup Dependabot using this [yml](https://github.com/goharbor/harbor/blob/main/.github/dependabot.yml),where package-ecosystem: "github-actions" part it works fine, but package-ecosystem: "gomod" part doesn't work.

The root cause is that some libraries are missing in the source code and the dependency verification fails. These libraries are generated by scripts, so I need to run the pre-script to generate these libraries, but I did not find the relevant Configuration options in the [doc](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).

Is there any way to get dependabot to work properly in this case? Thank you!

**Comment by jeffwidman** [comment]
That's not possibly for the native Dependabot provided by default on GitHub cloud.

Since `dependabot-core` is a library, you could run it yourself using github actions + an entrypoint like https://github.com/dependabot/dependabot-script/, and then run a custom action as the first step in the pipeline before triggering Dependabot... It's a bit more work unfortunately to wire all that up.

Otherwise you'll need to find a way to build those libraries w/o scripts.

As an aside, it's a little weird to me that you're generating `go` libs using a script... I've seen that in other ecosystems, but never `go` before...

**Comment by YangJiao0817** [comment]
@jeffwidman Thank you for your reply. I have tried referring to [manual-github-actions.yaml](https://github.com/dependabot/dependabot-script/blob/main/manual-github-actions.yaml), but I don’t know how to configure it, such as [ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore), [labels](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels), [open-pull-requests-limit](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit), [vendor](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#vendor), [assignees](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#assignees), how should I configure it in [dependabot-script](https://github.com/dependabot/dependabot-script/)? I didn't find the relevant documentation, can you tell me how to configure it? thanks!

**Comment by YangJiao0817** [comment]
@jeffwidman  do you have any updates on this?

**Comment by jeffwidman** [comment]
I'm afraid right now spelunking in the source code is the best option for understanding `dependabot-script`... later this quarter we plan to improve some of our developer docs, and if there's time I'll try to include some stuff about `dependabot-script` (or the CLI if we use that instead), but no promises it will make it. Sorry that isn't more helpful.
