### ISSUE TITLE
How is the release cycle/process for this project?

### ISSUE THREAD

**Issue by MounirMesselmeni** [dependabot/dependabot-core#6416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is there an automated release process or it this done manually?

If so when do you generate a new release for gemfiles, currently it's 0.215.0 but it's from 07 December 22.

Thank you!

**Comment by jeffwidman** [comment]
We currently do it manually, but plan to switch to an automated release cadence sometime this quarter. I'll be writing up an issue / more details in the next few weeks.

**Comment by MounirMesselmeni** [comment]
Thank for your feedback!
