### ISSUE TITLE
Cannot use private npm registry for all npm manifest files in monorepo

### ISSUE THREAD

**Issue by brentufkes** [dependabot/dependabot-core#6490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm

### Language version

Node 18

### Manifest location and content before the Dependabot update

/service-1
/service-2
/service-...
/service-n

### What you expected to see, versus what you actually saw

I am using private packages on https://registry.npmjs.org/ and attempting to leverage Dependabot to perform updates for me.  Given the `directory` attribute only supports a string, this does not work well with monorepos where you have a large number of manifest files spread across the repository.  I expected some sort of global definition of allowing the all my instances of npm manifests to pull from a private repo

**Expected:**
```...
updates:
  - package-ecosystem: "npm"
    directory: 
      - "/"
      - "/service-1"
      - "/service-2"
      -" /service-..."
      - "/service-n"
    registries:
      - npm-npmjs
...
```
or even better yet:
```...
updates:
  - package-ecosystem: "npm"
    directory: 
      - "*"           # Denoting all  npm packages can use the credentials for the private repository
    registries:
      - npm-npmjs
...
```

**Workaround:**
To actually achieve this, it just requires the duplication of a number of attributes, and looks something like this: 
``````version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org/
    token: ${{secrets.MY_PERSONAL_NPM_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/service-1"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/service-2"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/service-..."
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/service-n"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

**Comment by deivid-rodriguez** [comment]
I think this is essentially a duplicate https://github.com/dependabot/dependabot-core/issues/2824. Let me know if I didn't get that right!
