### ISSUE TITLE
Python versioning-strategy of `increase` does not raise lower version in range

### ISSUE THREAD

**Issue by edmorley** [dependabot/dependabot-core#6519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip 22.3.1

### Language version

Python 3.11

### Manifest location and content before the Dependabot update

`/tmpl/python/requirements.txt`

```
salesforce-functions>=0.1.0,<1.0.0
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tmpl/python"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
```

### What you expected to see, versus what you actually saw

The latest version of the `salesforce-functions` package currently published to PyPI is `0.3.0`.

Therefore, with `versioning-strategy: increase` I expected Dependabot to update `requirements.txt` from:

```
salesforce-functions>=0.1.0,<1.0.0
```

To:

```
salesforce-functions>=0.3.0,<1.0.0
```

ie: To increase the lower bound, per the requested versioning strategy. (Given there is the alternate strategy of `increase-if-needed`, then the whole point of `increase` is to increase even if the new version is in-range, surely?)

However, Dependabot reports no update possible:

```
updater | INFO <job_588818757> Checking if salesforce-functions  needs updating
  proxy | 2023/01/25 12:16:42 [014] GET https://pypi.org:443/simple/salesforce-functions/
  proxy | 2023/01/25 12:16:42 [014] 200 https://pypi.org:443/simple/salesforce-functions/
updater | INFO <job_588818757> Latest version is 0.3.0
  proxy | 2023/01/25 12:16:42 [016] GET https://pypi.org:443/simple/salesforce-functions/
  proxy | 2023/01/25 12:16:42 [016] 200 https://pypi.org:443/simple/salesforce-functions/
updater | INFO <job_588818757> Requirements to unlock update_not_possible
updater | INFO <job_588818757> Requirements update strategy bump_versions
updater | INFO <job_588818757> No update possible for salesforce-functions 
```
(https://github.com/heroku/sf-functions-core/network/updates/588818757)

**Comment by deivid-rodriguez** [comment]
Your reasoning makes sense to me, and the current behavior "no update possible" makes little sense. Feel free to investigate what's going on here, using the [dry-run script](https://github.com/dependabot/dependabot-core/blob/6e72b1e591f2ba67c0ec153e3c8bc86ea34f5d18/README.md#dry-run-script), or the [dependabot CLI](https://github.com/dependabot/cli) this should be easy to reproduce locally.

**Comment by deivid-rodriguez** [comment]
@edmorley We have recently gained more understanding of the current situation with respect to versioning strategies in Python, and I ended up opening a slightly broader issue about this problem. Let's unify the resolution of this problem at #6631. Please subscribe to that ticket, and of course, feel free to investigate :)
