### ISSUE TITLE
Error running terraform tests in devcontainer

### ISSUE THREAD

**Issue by mkemmerz** [dependabot/dependabot-core#6534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

Hello,

this issue is rather about some personal support. 

I am trying to contribute to one of the issues here in this repo but I am simply not getting the devcontainer running correctly. I oriented on the [Contributing Guidelines](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md) and the [dependabot-script](https://github.com/dependabot/dependabot-script) repo for setting up the helpers.

The devcontainer is build, I run the `bundle install` in the container, all Gems are correctly setup ( at least I think so). As I want to work on a terraform language feature I have also setup the terraform helper + the required hcl2json for the tests cases.

I try to execute the "Debug dry run" or "Debug tests" (on terraform - spec) but I always get the following error message:

```
/usr/local/rvm/gems/ruby-3.1.3/gems/bundler-2.4.5/lib/bundler/rubygems_integration.rb:304:in `block in replace_bin_path': can't find executable rdebug-ide for gem ruby-debug-ide. ruby-debug-ide is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /usr/local/rvm/gems/ruby-3.1.3/gems/bundler-2.4.5/lib/bundler/rubygems_integration.rb:332:in `block in replace_bin_path'
	from /usr/local/rvm/gems/ruby-3.1.3/bin/rdebug-ide:32:in `<main>'
```

The error still occurs even after I explictily ran `gem install ruby-debug-ide`. The test execution works if I run `cd terraform && bundle exec rspec spec`, sadly I am not sure how to attach a debugger with this command. The execution still fails with 210 examples, 35 failures on testcases so even this setup is not working 100%.

Other packages (like maven) throws a different error:

```
/usr/local/rvm/gems/ruby-3.1.3/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide.rb:9:in `require': cannot load such file -- debase (LoadError)
	from /usr/local/rvm/gems/ruby-3.1.3/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide.rb:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.1.3/gems/ruby-debug-ide-0.7.3/bin/rdebug-ide:8:in `require_relative'
	from /usr/local/rvm/gems/ruby-3.1.3/gems/ruby-debug-ide-0.7.3/bin/rdebug-ide:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.1.3/bin/rdebug-ide:25:in `load'
	from /usr/local/rvm/gems/ruby-3.1.3/bin/rdebug-ide:25:in `<main>'
	from /usr/local/rvm/gems/ruby-3.1.3/bin/ruby_executable_hooks:22:in `eval'
	from /usr/local/rvm/gems/ruby-3.1.3/bin/ruby_executable_hooks:22:in `<main>'
```

This definetly blocks me from getting deeper into the project so I am happy about any help!

**Comment by jeffwidman** [comment]
👋 sorry for the headache here. `dependabot-script` is in limbo mode as it needs some cleanup work on both docs and code... it's on my plate to tackle this quarter, but I won't get there for a while yet.

We also _just_ merged some major changes to our dockerfiles at the end of last week, so haven't had a chance to update the readme on this repo... but hopefully we can knock that out this coming week.

In the meantime, your best bet is to run the `bin/docker-dev-shell` script with an ecosystem argument, which in this case is `terraform`, which will build the container locally and then drop you in... from there, you can run [the dry-run script](https://github.com/dependabot/dependabot-core#dry-run-script) or run tests by going `cd terraform && rspec`.

The docker image that gets built mounts your local copy of the code, so you can edit it locally, then immediately re-run dry-run or unit tests to play with stuff. You'll also want to checkout [the tips on debugging native helpers](https://github.com/dependabot/dependabot-core#debugging-native-helpers).

Hopefully that gets you pointed in the right direction, if you need more info just holler is your best bet until we get our docs updated to reflect our recent changes.

We gladly welcome PR's, although if it's a bigger change I suggest opening an issue to confirm we're onboard with the product direction before spending a bunch of time on a PR we can't accept.

**Comment by mkemmerz** [comment]
Thanks a lot for taking your time and pointing me into the right direction @jeffwidman ! 😁 Failing to setup the environment was driving me a bit crazy but seems like I was only having a very bad timing 👍 I am definetly looking forward to the new docs :)
