### ISSUE TITLE
Support terragrunt configurations the same as terraform modules

### ISSUE THREAD

**Issue by lorengordon** [dependabot/dependabot-core#654]
[Terragrunt](https://github.com/gruntwork-io/terragrunt) is a wrapper around terraform and uses the same syntax for module `source`. But the specification is in a `terraform.tfvars` file rather than `.tf` file, and it's in a `terragrunt.terraform` dictionary instead of `module`.

Something like this:

```
terragrunt = {
  terraform {
    source = "<repo_url>//<path/to/module>?ref=<semver>"
```

**Comment by greysteil** [comment]
Ah, interesting. Any open-source repos you can point me to that use it, so I've got some fixtures to work with?

**Comment by lorengordon** [comment]
Here's one of mine, https://github.com/plus3it/wrangler-watchmaker/blob/master/release/salt-yum-defs/terraform.tfvars

Here's one from the gruntwork team, https://github.com/gruntwork-io/terragrunt-infrastructure-live-example

**Comment by greysteil** [comment]
👍, this looks pretty easy. Working on a PR for it [here](https://github.com/dependabot/dependabot-core/pull/655).

**Comment by greysteil** [comment]
This is done (I just forgot to close this issue!)
