### ISSUE TITLE
Please clarify commercial licence for use in ADO via Tingle Software extension

### ISSUE THREAD

**Issue by Grant-MMT** [dependabot/dependabot-core#6594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi, we'd like to use Dependabot in a commercial organisation which uses ADO.  It will be used to manage dependencies on one of the company's websites, which has nothing to do with developer tooling.  This would be done via the[ Tingle Software Extension](https://github.com/tinglesoftware/dependabot-azure-devops), which uses the Dependabot-core Docker image.

Dependabot-core uses a Prosperity Public License 2.0.0 which indicates that it can only be used commercially for a trial period:
**From** [https://github.com/dependabot/dependabot-core/blob/master/LICENSE]( https://github.com/dependabot/dependabot-core/blob/master/LICENSE) You must limit use of this software in any manner primarily intended for or directed toward commercial advantage or private monetary compensation to a trial period of 32 consecutive calendar days.

There was a [clarification in 2019](https://github.com/dependabot/feedback/issues/569) which stated:
`the license on Dependabot Core is for using that library to self-host a dependency updating tool - it doesn't apply to using the hosted Dependabot service.`

It seems like the intention of that was to allow use of Dependabot in a commercial environment but prevent development of a commercial tool based on it.  However, strictly speaking I don't believe the Tingle extension is using the hosted Dependabot service.

Can you clarify whether use of Dependabot-core is allowed without time restriction in a commercial environment when it's run in a Docker image locally, used to manage dependencies (and not as part of a commercial developer tool)?

The Tingle extension is using an MIT licence.

**Comment by jeffwidman** [comment]
https://github.com/dependabot/dependabot-core/issues/3645#issuecomment-839916100 should address your concern. 

As long as you're just using it as part of your own team's CI to bump packages, and not re-selling it as a product, then you should be fine.

Closing, but if for some reason you still have questions comment and we can reopen.
