### ISSUE TITLE
Can support scan connected local vulnerability database？

### ISSUE THREAD

**Issue by msk666666** [dependabot/dependabot-core#6607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Can support scan connected local vulnerability database？

**Comment by jeffwidman** [comment]
See https://github.com/dependabot/dependabot-core/issues/1857#issuecomment-1326334334 and https://github.com/dependabot/dependabot-core/issues/4437.

Dependabot on native GitHub only looks at the cloud Vulnerability database.

If you want to use a local source for vulnerabilities, then see the issues above for more context... the short answer is you'll have to implement the advisory pipeline to get data into the format that `dependabot-core` expects for the vulnerable versions.

Here's an example command using the `dry-run.rb` script:
```
# fake a security advisory in a direct dep of a pub-based repo
SECURITY_ADVISORIES='[{"dependency-name":"buffer","patched-versions":[],"unaffected-versions":[],"affected-versions":["<= 2.0.0"]}]' bin/dry-run.rb pub dart-lang/pub-dev --dir "/app" --cache=files --dep="buffer"
```
