### ISSUE TITLE
Log / error when `git` missing when running `pip-tools`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6617]
See discussion here: https://github.com/dependabot/dependabot-core/pull/6609#discussion_r1098377937

> What happens if `git` isn't present? 
> If an error in creating a git repo results in `pip-tools` updates completely breaking, then it'd be nice to at least have an `info` log for easier debugging... don't have to capture the full subprocess, but instead we could log saying "couldn't create git repo, all pip-tools jobs will fail"...
> 
> And we probably should just outright bail here, no point in continuing the job if we know `pip-tools` will fail.

This was added in https://github.com/dependabot/dependabot-core/commit/4e72d4ed1345e0be604b578e206559a421f1a827 which thankfully included a spec for the behavior.

Currently exists two places:

https://github.com/dependabot/dependabot-core/blob/f11c364fb91c7fafef532d9c6699631a658bc9c1/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb#L316-L321

and

https://github.com/dependabot/dependabot-core/blob/f11c364fb91c7fafef532d9c6699631a658bc9c1/python/lib/dependabot/python/file_updater/pipfile_file_updater.rb#L201-L203

The second usage is surprising because it's in `file_updater/pipfile_file_updater.rb`, whereas `pip-tools` is actually `pip-compile` so I'd expect it to use [`file_updater/pip_compile_file_updater.rb`](https://github.com/dependabot/dependabot-core/blob/f11c364fb91c7fafef532d9c6699631a658bc9c1/python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb) instead. So possibly we don't need `git` there at all`, or possibly we do need it, but the code comment is wrong.

For the first one, we should also check if this is even still needed, as it may not be.

**Comment by jeffwidman** [comment]
The root need for this might have been removed as part of:
* https://github.com/jazzband/pip-tools/pull/385
 
I'll try it and see 😁

**Comment by jeffwidman** [comment]
Looks like removal breaks CI over in:
* #6619

This isn't a super high risk issue and it's very approachable for someone new to the project, so i'm going to tag it as a "good first issue" and leave it for a potential contributor. You can use this PR as an example of how to add a new log line:
* https://github.com/dependabot/dependabot-core/pull/6601

**Comment by jeffwidman** [comment]
I ran across this again in the source code, so this time reached out to the `pip-tools` maintainers:
* https://github.com/dependabot/dependabot-core/issues/7612
* https://github.com/jazzband/pip-tools/issues/1931

I also re-opened:
* https://github.com/dependabot/dependabot-core/pull/6619

**Comment by GarryHurleyJr** [comment]
Please leave this one for new joining person as it should be simple

**Comment by sachin-sandhu** [comment]
After team discussion, As Dependabot is distributed as a docker image. The image comes up with git installed in already. So changes of git not being available are exponentially lower. Hence marking issue as won't fix. Please feel free to discuss on this if needed.
