### ISSUE TITLE
Dependabot is not recreate my PR

### ISSUE THREAD

**Issue by ydainna** [dependabot/dependabot-core#6623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm yarn

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"

### What you expected to see, versus what you actually saw

I am opening this issue because I have a problem with dependabot.
I'm not sure if I'm going to be able to use it again, but I'm sure I will.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/ydainna/saigyou-ayakash/pull/17

**Comment by jeffwidman** [comment]
It looks like it's working looking at that PR. The recreate/rebase actions are an asynchronous job, so may take some time to happen depending on how backed up the job queue is.
