### ISSUE TITLE
Python: dependabot refuses to bump requirements.txt for non-poetry pyproject.toml projects

### ISSUE THREAD

**Issue by sanderr** [dependabot/dependabot-core#6625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

3.9

### Manifest location and content before the Dependabot update

`/pyproject.toml`:
```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lorem"
version = "2.5.0"
requires-python = ">=3.9,<4.0"
description = "Generator for random text that looks like Latin."
dependencies = [
	"more-itertools>=8",
]
```

`/requirements.txt`:
```
more-itertools==8.14.0
```

Full reproductive project: https://github.com/sanderr/inmanta-module-factory/ (commit 0463a45). Simply fork it and enable dependabot to reproduce.

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
    # Allow both direct and indirect updates for all packages
    - dependency-type: "all"
```

### What you expected to see, versus what you actually saw

I expected dependabot to open a pull request for `more-itertools==9.0.0` in `requirements.txt`.

I had a look at the source code and I believe there's a reasoning error where dependabot refuses to continue if the dependency is both constrained in `pyproject.toml` and in pinned in `requirements.txt`. I found the following related commits (in chronological order):
- ae9658c1146f29db504952ccd1cb65eff29ae766: for poetry projects, use the `widen_ranges` update strategy.
- 4dc71870ea8a05699d229a5fc05a143f372bf63c: extend this to any project with a `pyproject.toml` file
- 132c4c29df17484f5890eaa48a51fb64f081c57d: when `widen_ranges` strategy is picked and the dependency exists in `requirements.txt` as well, abort

I sort of get the reasoning of these changes for poetry based projects: they have their own lock file so having a separate `requirements.txt` doesn't makes sense. However, with [PEP518](https://peps.python.org/pep-0518/) `pyproject.toml` is used for more than just poetry projects.

I'm not sure what `widen_ranges` means, but from the name I get the impression it would indeed apply to any `pyproject.toml` project (unless this is specific to the `requirements.txt` update, which is a plain bump?). Therefore I am inclined to believe that the first two commits mentioned above are valid, but the third should not abort based on the update strategy but rather on whether it's a poetry project or not.

I would be willing to implement a fix if consensus is reached on what the desired behavior would look like.

### Images of the diff or a link to the PR, issue, or logs

```

updater | INFO <job_599690860> Checking if more-itertools 8.14.0 needs updating
  proxy | 2023/02/08 13:48:31 [016] GET https://pypi.org:443/simple/more-itertools/
  proxy | 2023/02/08 13:48:31 [016] 200 https://pypi.org:443/simple/more-itertools/
updater | INFO <job_599690860> Latest version is 9.0.0
  proxy | 2023/02/08 13:48:31 [018] GET https://pypi.org:443/pypi/lorem/json/
  proxy | 2023/02/08 13:48:31 [018] 301 https://pypi.org:443/pypi/lorem/json/
  proxy | 2023/02/08 13:48:31 [020] GET https://pypi.org:443/pypi/lorem/json
  proxy | 2023/02/08 13:48:31 [020] 200 https://pypi.org:443/pypi/lorem/json
updater | INFO <job_599690860> Requirements to unlock update_not_possible
  proxy | 2023/02/08 13:48:32 [022] GET https://pypi.org:443/pypi/lorem/json/
  proxy | 2023/02/08 13:48:32 [022] 301 https://pypi.org:443/pypi/lorem/json/
  proxy | 2023/02/08 13:48:32 [024] GET https://pypi.org:443/pypi/lorem/json
  proxy | 2023/02/08 13:48:32 [024] 200 https://pypi.org:443/pypi/lorem/json
updater | INFO <job_599690860> Requirements update strategy widen_ranges
updater | INFO <job_599690860> No update possible for more-itertools 8.14.0
```

### Smallest manifest that reproduces the issue

See "manifest location and content before the Dependabot update" section.

**Comment by deivid-rodriguez** [comment]
Hi @sanderr! Thanks for your report, makes sense!

The `widen_ranges` strategy is a strategy used for updating dependency manifest files, where we will relax the range of accepted version so that it includes the version that we want to update to. See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy (the `widen_ranges` internal name corresponds to the `widen` strategy there).

In this situation, the `requirements.txt` file is acting as a lockfile, so it makes sense to bump the pin in there, regardless of the strategy configured.

In the mean time, I guess you can workaround this issue by configuring an strategy that's not the default (`widen`)?

**Comment by sanderr** [comment]
Thanks for your response. I noticed there was a way to configure it but I hadn't gotten around to look for it yet. I must confess I am confused as to the exact semantics of these options and how they affect the bumping. Based on this code I would think that the default strategy for Python packages that don't use `pyproject.toml` as a manifest would be `:bump_versions` (`increase`?). But we don't have an explicit strategy configured on any of our repos and yet dependabot manages to widen the ranges (e.g. [this PR last month](https://github.com/inmanta/inmanta-core/pull/5345)).

I assume there's a gap in my understanding. How comes ranges are widened even though the second commit I linked above would decide on the `:bump_versions` strategy? Don't get me wrong, this is exactly the behavior we want, and I think it's the sane default behavior, but I don't see how it matches with the implementation. What am I missing?

**Comment by deivid-rodriguez** [comment]
The default strategy is `widen` if Dependabot detects that the target repository is a library. Otherwise (if it thinks it's an end application), the default strategy is `increase`. Does that make sense?

**Comment by sanderr** [comment]
That part makes sense to me, but as far as I can see it will only decide it's a library if the manifest is `pyproject.toml` (and some other conditions apply). From the second commit I linked:
```ruby
      def library?
        return unless updating_pyproject?
        ...
```

What I'm trying to say is that when I reason about the code, the documented options and the observed behavior from two different directions, they don't add up:
1. From the implementation of the `library?` method I would conclude that for a project that doesn't use the `pyproject.toml` as a manifest, dependabot would always conclude it's an end application. Therefore it would choose the `increase` strategy.
2. From the fact that dependabot does manage to widen ranges on our repos that don't have an explicit strategy configured, I would conclude that dependabot somehow does conclude that it's a library. This conflicts with the reasoning in 1. Furthermore, if it did, I would think the same bug that arises for `pyproject.toml` projects would cause the bump to be aborted, but this isn't the case.

Since the observed behavior clashes with 2, I'm inclined to think my reasoning in 1 is correct. But then how comes dependabot manages to bump e.g. `"crontab~=0.23"` to `"crontab>=0.23,<2.0"` in `setup.py`? This is a range widening, isn't it?

Do you see what I mean? I feel like I'm missing the full picture in what's going on here, which makes it difficult to reason on what exactly is the root cause for this bug, as well as what strategy is actually the right pick for a given use case.

**Comment by sanderr** [comment]
I should say I'm not familiar with Ruby at all. I might be missing something obvious in that regard.

**Comment by deivid-rodriguez** [comment]
Yes, what you say makes sense, but that project where Dependabot widened ranges in `setup.py` has a `pyproject.toml` file, right?

**Comment by sanderr** [comment]
It does but it doesn't have any dependencies in there. Those are all in `setup.py`. So I would think that `updating_pyproject?` would return false there. And that assumption seems to be backed up by the fact that dependabot does still open PRs for this repo, which differs from the behavior on the example project in my initial post. Perhaps I need to do some further testing to gather more data.

**Comment by deivid-rodriguez** [comment]
Yeah, well reading through the code, I would expect Dependabot to actually crash in your situation, because [your `pyproject.toml` file](https://github.com/inmanta/inmanta-core/blob/5f13a10cb2062d2f32b6fd7494c0796ca2acfba9/pyproject.toml) does not look like anything dependabot expects (it expects a tool file with either a `tool.poetry` or `project` section).

Feel free to do some further testing, yeah. We have a [dry-run.rb script](https://github.com/dependabot/dependabot-core/blob/84446abf981e5ebe2ee18cae0728aac486bcbc08/README.md#dry-run-script) that could help you testing different things and even potential patches. We're willing to help out with Ruby!

**Comment by sanderr** [comment]
Thanks, that looks useful.

I think I misunderstood the documentation with regards to `increase`. I just tried setting the strategy to `increase` for the [dummy reproductive project](https://github.com/sanderr/inmanta-module-factory/) and it did open [a pull requests that widens the constraint](https://github.com/sanderr/inmanta-module-factory/pull/7/files).

So I would conclude that
1. I still don't fully understand the difference between `widen` and `increase`. `increase` seems widen the constraint in the manifest by keeping the lower bound and increasing the upper bound. This is what I understood `widen` meant. That said, I don't think this is terribly important for this issue. It suffices that I now know `increase` corresponds to this behavior.
2. In case of non-poetry projects with `pyproject.toml` manifests, I think `increase` remains the appropriate strategy, contrary to what I assumed in my initial report. Concretely, I think that means that 4dc71870ea8a05699d229a5fc05a143f372bf63c should be mostly reverted. Do you agree with this assessment?

**Comment by sanderr** [comment]
> Can you explain this in more detail? Why is this particular setup different from other library setups?

My statement here was based on the assumption that the behavior in 1 was in fact the intended behavior. If it's not, then I withdraw this suggestion (though I find the deciding factors in what differs an application from a library somewhat strange). But in that case, how should you configure dependabot explicitly so that it would bump to `>=8,<10`? `widen` does not seem to be an accepted option for the pip ecosystem.

**Comment by deivid-rodriguez** [comment]
I the criteria comes from the assumption that when dependabot proposes updates, library authors generally don't want to drop support for versions of dependencies, but to add support for the latest versions. On the other hand, applications normally support just a single version of each dependency so a strategy that just moves forward fits better.

> `widen` does not seem to be an accepted option for the pip ecosystem.

Interesting, did you try it and you got an error? In that case, we should enable it as an option and document, because we do have at least some support implemented (since we assume it's the default strategy for libraries).

**Comment by sanderr** [comment]
I follow the reasoning for why you would want to treat libraries and applications differently, but I don't follow why a package that uses a `pyproject.toml` and happens to be on PyPi is supposedly a library, and packages without `pyproject.toml` are always considered an application.

> Interesting, did you try it and you got an error?

Indeed I did. I added it to `.github/dependabot.yml` and got this error: `The property '#/updates/0/versioning-strategy' value "widen" did not match one of the following values: lockfile-only, auto, increase, increase-if-necessary`

**Comment by deivid-rodriguez** [comment]
> I follow the reasoning for why you would want to treat libraries and applications differently, but I don't follow why a package that uses a pyproject.toml and happens to be on PyPi is supposedly a library, and packages without pyproject.toml are always considered an application.

Happy to listen to other ideas, I'm personally to a Python expert so if you have a better definition, I'm all ears!

> Indeed I did. I added it to .github/dependabot.yml and got this error: The property '#/updates/0/versioning-strategy' value "widen" did not match one of the following values: lockfile-only, auto, increase, increase-if-necessary

Ok, that makes two issues/TODOs apart from the one reported here! :) I'll reticket those!

**Comment by sanderr** [comment]
> Happy to listen to other ideas, I'm personally not a Python expert so if you have a better definition, I'm all ears!

I wouldn't call myself an expert either, but I have gathered some quite some experience with the ecosystem. I'll give it some thought and report back.

> Ok, that makes two issues/TODOs apart from the one reported here! :) I'll reticket those!

Indeed. One other very minor thing is that I think the docs could be more clear on the exact difference between `increase` and `widen`: `increase` also increases the lower bound, while `widen` only increases the upper bound. I might create a small PR for that when I've got some spare time.

As to resolution order, I think this ticket should probably be a blocker for #6630 because it would not work without fixing this issue. And the fix of the `increase` mode should probably block on the introduction of `widen`, because otherwise projects might not be able to configure the behavior they're currently getting.

**Comment by sanderr** [comment]
Thanks for the support on this one. I think the bulk of it is actionable now.

**Comment by deivid-rodriguez** [comment]
No problem, #6632 should fix this!

**Comment by jeffwidman** [comment]
Let me see if I can also get https://github.com/github/docs/pull/20732 pushed across the line, that may help here on the docs side.
