### ISSUE TITLE
Minimum Python version not detected if .python-version contains comments

### ISSUE THREAD

**Issue by aciba90** [dependabot/dependabot-core#6650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

https://github.com/canonical/pycloudlib/blob/b02ba24b214ddf922491ee711b4ffe382c450da7/dev-requirements.txt

### dependabot.yml content

https://github.com/canonical/pycloudlib/blob/b02ba24b214ddf922491ee711b4ffe382c450da7/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I expected `dependabot` to correctly detect the minimum Python version defined in `.python-version` and issue upgrades with correct python dependencies' versions.

If `.python-version` contains comments, then the suggested dependecies' versions were always the newest one.

Not working configuration: https://github.com/canonical/pycloudlib/blob/b02ba24b214ddf922491ee711b4ffe382c450da7/

Working configuration: https://github.com/canonical/pycloudlib/pull/275

### Images of the diff or a link to the PR, issue, or logs

This PR tried to bump `flake8` to a version that was not compatible with python 3.6 (defined in `.python-version`):

https://github.com/canonical/pycloudlib/pull/274

### Smallest manifest that reproduces the issue

`dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
```

`.python-version`:

```
3.6.5
# Specifies the python version that dependabot should use
# Note: The version must specify major.minor.patch components
# and be supported on:
# https://github.com/dependabot/dependabot-core/blob/7822f07e76cab9be6eca86a91aafc8d72bc42536/python/lib/dependabot/python/python_versions.rb
```

**Comment by mohammadalizabihitari** [comment]
Hi, I am working on this issue, will keep you updated as I progress
