### ISSUE TITLE
Private pip registries not working

### ISSUE THREAD

**Issue by DanielKnutsen** [dependabot/dependabot-core#6676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content

version: 2
registries:
  pip-azure-artifacts:
    type: 'python-index'
    url: 'https://pkgs.dev.azure.com/removed_org/removed_project_id/_packaging/removed_feed_name/pypi/simple'
    token: 'PAT:${{SYSTEM_TOKEN}}'
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    registries:
      - pip-azure-artifacts
    open-pull-requests-limit: 5
    target-branch: 'main'
    versioning-strategy: 'auto'
    insecure-external-code-execution: allow

### What you expected to see, versus what you actually saw

I'm using the Azure Devops extension, but I suspect the problem is located in this code base (feel free to dismiss this if I'm wrong). As you can see from the attached dependabot.yml content I have specified my private pip registry as described in the documentation. More specifically I'm using the `url` key as opposed to `index-url` that was used previously. However, when I run the pipeline, all packages in the private registry fails to update with the error message highlighted in the logs below.

[Here](https://github.com/dependabot/dependabot-core/blob/ba3d13afd51eb5a703ba3543f8fa226cc9d3e50a/python/lib/dependabot/python/authed_url_builder.rb#L8) the code asks for `index-url`, should this maybe be `url` with the new config version?

### Images of the diff or a link to the PR, issue, or logs

![image](https://user-images.githubusercontent.com/37139920/219128599-4e430c72-66c1-4aef-b37c-b507b3381e66.png)

**Comment by deivid-rodriguez** [comment]
Hi @DanielKnutsen!

I know this is confusing but while the publicly facing setting is `url`, Dependabot internally expects `index-url` as you observed. We have this discrepancy between publicly exposed names through config and internal namings in other places, and we should eventually reconcile things, but it is what it is now.

I think the easiest way to fix this for the moment would be at https://github.com/tinglesoftware/dependabot-azure-devops. In particular, properly a new special case around here: https://github.com/tinglesoftware/dependabot-azure-devops/blob/ea2ebb92e0d880e37752a5a428f42c65102d739e/extension/task/utils/parseConfigFile.ts#L281-L295.

Feel free to open an issue at https://github.com/tinglesoftware/dependabot-azure-devops and reference this ticket, so we can figure this out together.

**Comment by mburumaxwell** [comment]
This should now fixed in the extension repo via https://github.com/tinglesoftware/dependabot-azure-devops/pull/526.

@deivid-rodriguez is there a place where this translations/transforms/mappings are documented or can be extracted?

**Comment by deivid-rodriguez** [comment]
Thanks for the fix @mburumaxwell! Unfortunately no, I'm finding about these discrepancies myself through issues like this one. We do plan to publish the [configuration schema](https://github.com/dependabot/dependabot-core/issues/1927) and eventually reconcile internal naming to match that, but not sure how we'll be able to get to that, so super appreciated that you fixed this on your side for now 🙏.

I'll close this, if something is not yet working for you @DanielKnutsen feel free to reach out!

**Comment by mburumaxwell** [comment]
Hopefully, it will be clearer some day.

**Comment by deivid-rodriguez** [comment]
Definitely!
