### ISSUE TITLE
Dependabot can't find all vulns in big repos

### ISSUE THREAD

**Issue by Guisch** [dependabot/dependabot-core#6683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

yarn lockfile v1

### Language version

nodejs 12.14.1

### Manifest location and content before the Dependabot update

Can't give the full path but here is a close one:
`/src/services/aaa-aaa/bbb-bbb-bbb/yarn.lock`

### dependabot.yml content

No dependabot config file

### What you expected to see, versus what you actually saw

Hello 👋🏻 

We have a mono-repo (not strictly speaking a mono-repo but it's a big one with 1+GB).
On that mono-repo, dependabot seems to work fine pretty much everywhere except in one sub-directory.
On that sub-directory, dependabot fails to scan manifests files (`package.json` & `yarn.lock`) and doesn't raise security alerts.

To confirm that these manifests files are correct, I copied them inside a newly created repository with the same folder architecture. Dependabot immediately found 100+ vulnerabilities.

Some guess that might help ?
- Does Dependabot have some kind of recursion limit and cannot scan more than X sub-directory ?
- Both manifests files last commit date is 2020-06-20, I might be wrong but I believe yarn was added to Dependabot after that date. Does Dependabot ignores all files prior that date ?

Please let me know if you need more details 🙏🏻 Thanks

**Comment by deivid-rodriguez** [comment]
I have no idea what could be causing this. Can you see anything suspicious in the logs regarding this folder? Can you create a public repository with the same structure, even if it does work there? I did not fully understand the difference between these two projects, is the only difference between them the presence of files unrelated to dependency management? 🤔

**Comment by Guisch** [comment]
Hey thanks for answering that fast.

>  Can you see anything suspicious in the logs regarding this folder? 

Can you guide me where to find the logs ? I know where I can find Dependabot Updates Logs, but Dependabot Scanning Logs aren't available, are they ?

> Can you create a public repository with the same structure, even if it does work there?

Sorry It's hard for me to put anything public. Maybe I could create a private one and add you as contributor if it's ok for you ?

I did some more tests and I have the feeling that there's a limit in the number of vulns that the dependabot can scans.
I have that big repo X with 1GB+ of files in it (20k files) with this folder architectures:

```
[folders]/
    [more folders]
src/
    services/
        service1/
        service2/
        service.../
        serviceN/
        service.../
        serviceNotDetected/
            package.json
            yarn.lock
        service.../
        serviceN/
[even more folders]/
```
_Each services as its own manifests files but I'm only showing the not detected ones here to increase readibility_

The first thing I did is to create a new repo (`test-X`) with only the manifests files:
```
src/
    services/
        serviceNotDetected/
            package.json
            yarn.lock
```

In the `test-X` repo, Dependabot immediately found and reported vulns.

I then create another new repo (`clone-X`) where I cloned the entire content of `X`. In `clone-X`, Dependabot reported the exact same vulnerabilities than in `X`. Thus `serviceNotDetected` was not reporting any vulns either.
I waited few hours to confirm Dependabot was not reporting any new vulns. I then removed a manifest file from the service with most reported vulns (not `serviceNotDetected`). In Github I could see the Dependabot alerts of that services disappearing, but quickly after a bunch of new alerts appeared. I can confirm from the dependabot alert that they have been raised because of the manifest file deletion, eventhough they are not for the same service (not even in the same parent folder).
So I had 150 vulns, I remove the manifest file with most reported vulns (not `serviceNotDetected`), I went from 150 to 100, then quickly back to 145 or something. 
I kept going and removed all manifests files (main & lock) with open vulns in `clone-X`, 75 new vulns (new as never seen before) were reported for the remaining manifests files (the ones with previously no reported vulns).

I renamed this issue to better match the problem.

Thanks.

**Comment by Guisch** [comment]
FYI I ran dependabot-cli on `serviceNotDetected` this weekend, the command took 13h to complete. And this is on only 1 service.

**Comment by Guisch** [comment]
Yes I figured this out and opened alrady opened a ticket. Thanks for you time !
