### ISSUE TITLE
Support Maven Plugin version upgrades (works for some, but misses others)

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#671]
I've been using Dependabot on a number of FLOSS projects using Java for a little while now, some Gradle based, most using Maven, and believe that it misses proposing upgrades to Maven plugins (not regular dependencies) some times, but not always.

For example, it did propose https://github.com/vorburger/odlparent/pull/216 (and earlier https://github.com/vorburger/odlparent/pull/46), even recognizing the indirection via the property (nice!); as well as https://github.com/m2e-code-quality/m2e-code-quality/pull/132/files or e.g. https://github.com/m2e-code-quality/m2e-code-quality/pull/133/files.

It however missed https://github.com/m2e-code-quality/m2e-code-quality/pull/138, or https://git.opendaylight.org/gerrit/#/c/76158/ (with maven-dependency-plugin 3.1.0 > 3.0.2 [having been out since April](https://blog.soebes.de/blog/2018/04/06/apache-maven-dependency-plugin-version-3-dot-1-0-released/), not very recent release); similarly https://git.opendaylight.org/gerrit/#/c/76157/ or https://git.opendaylight.org/gerrit/#/c/76156/.

@greysteil filing this not to stress but just as feedback in case you weren't aware there's a gap here.

Thank you again for Dependabot, and for making it available for free to other opensource projects!!

**Comment by greysteil** [comment]
Super useful - thanks for filing @vorburger! I wasn't aware of those misses and will take a look.

**Comment by greysteil** [comment]
OK, just dug into why Dependabot didn't generate m2e-code-quality/m2e-code-quality#138 and it looks like it's because it couldn't find `org.eclipse.tycho:maven-osgi-lifecycle-plugin` on the registry - the dependencies in that group are [here](http://repo.maven.apache.org/maven2/org/eclipse/tycho/). Dependabot has a check when it's updating properties that affect multiple dependencies that all of the dependencies being updated have to have the version that it's updating to.

@vorburger - any idea what I'm missing here? How should Dependabot have got the versions for `org.eclipse.tycho:maven-osgi-lifecycle-plugin`, or is there some way that it should have known to ignore it?

**Comment by greysteil** [comment]
FYI, I've created https://github.com/dependabot/dependabot-core/pull/674, which would allow Dependabot to still create PRs in the above case. Would love your insight before I consider merging it!

**Comment by vorburger** [comment]
> because it couldn't find org.eclipse.tycho:maven-osgi-lifecycle-plugin on the registry
> @vorburger - any idea what I'm missing here? How should Dependabot have got the versions for org.eclipse.tycho:maven-osgi-lifecycle-plugin, or is there some way that it should have known to ignore it?

you had me puzzled there for a moment as well.. I couldn't find a `maven-osgi-lifecycle-plugin` in my `~/.m2` nor on Maven central nor on http://repository.sonatype.org/content/groups/sonatype-public-grid, which is a `<pluginRepository>` used in this project. It's also nowhere to be found in [the Tycho sources](https://github.com/eclipse/tycho).

The reason, I realized after scratching my head, is that `maven-osgi-lifecycle-plugin` is in `<pluginManagement>` - but not used anywhere in `<plugins>`. It means "if this plugin is used anywhere, here is the version (and configuration) to use for it". But it's not used. So it can be non-existant (I suspect that this is a VERY, as in 8 years old, Tycho thing which is no longer relevant). It can even be completely wrong, Maven doesn't complain  - I tested.

BTW: I suspect (not tested) that <[dependencyManagement](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management)> would be exactly the same.

Just ignoring anything you can't find in `<pluginManagement>` and `<dependencyManagement>`, as you seem to have done in #674 (from what little Ruby I understand) is probably fair. In an ideal world, you could perhaps even somehow notify projects (provide more details than currently on that dependabot dashboard? or even open an issue, that would be fancy, and useful!). Because any stuff like this should be fixed by being removed - as in https://github.com/m2e-code-quality/m2e-code-quality/pull/152! :smile_cat: 

I even considered for a minute that in an ideal world you could raise PRs to remove anything in `<pluginManagement>` and `<dependencyManagement>` which isn't used in `<plugins>` or `<dependencies>`, but of course you cannot - it may be used in other projects.

> or https://git.opendaylight.org/gerrit/#/c/76158/ (with maven-dependency-plugin 3.1.0 > 3.0.2 having been out since April, not very recent release); similarly https://git.opendaylight.org/gerrit/#/c/76157/ or https://git.opendaylight.org/gerrit/#/c/76156/.

Just FYI these cannot be due to the same problem (I just had a look), will you check those out as well, some time?

**Comment by greysteil** [comment]
Great, thanks @vorburger. Looking at those separately!

**Comment by greysteil** [comment]
OK, looking through those other missed dependencies, it looks like they're all `<pluginManagement>` specifications that specified a `<groupId>`. As a result, Dependabot's parsing isn't picking them up.

What should Dependabot be doing here? If a dependency is specified `<pluginManagement>` without a `<groupId>` is it valid?

**Comment by vorburger** [comment]
Oh! I hadn't noticed the missing `<groupId>` ... AFAIK Maven has a notion of hard-coded backed in default groupId _org.apache.maven.plugins_ for a [bunch of core plugins](https://maven.apache.org/plugins/). Can you just default to that, if there is none?

BTW: This actually isn't really related to `<pluginManagement>` , it would also apply in a simple:

```xml
<build>
  <plugins>
    <plugin>
      <artifactId>maven-dependency-plugin</artifactId>
      <version>3.0.2</version>
```

**Comment by greysteil** [comment]
You're totally right, and it's invaluable advice, as usual!

**Comment by vorburger** [comment]
> and it's invaluable advice, as usual!

just giving back to a service that provides me real value!

but when you IPO Dependabot via an ICO (ROTFL) you can still throw me some crypto... just joking! :smile_cat: 

#openSourceWorks

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/compare/v0.73.0..v0.73.1, and #674 is merged so I think this is now resolved. Thanks again, and I'll make sure those tokens find their way to you. 🤣
