### ISSUE TITLE
Dependabot can't parse your global.json with an UTF-8 BOM

### ISSUE THREAD

**Issue by hhyyrylainen** [dependabot/dependabot-core#6711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.NET 7

### Manifest location and content before the Dependabot update

[/global.json](https://github.com/Revolutionary-Games/RevolutionaryGamesCommon/blob/3e2973d1c72807e1bb17061295a26b2ba3191240/global.json)

### dependabot.yml content

https://github.com/Revolutionary-Games/RevolutionaryGamesCommon/blob/3e2973d1c72807e1bb17061295a26b2ba3191240/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I expect dependabot to keep working even after adding a `global.json` file to specify which .NET SDK version I want to use with my project. Instead what happens is that dependabot fails with:
```
Dependabot can't parse your global.json

Dependabot failed to update your dependencies because there was an error parsing the global.json found at /global.json.

Dependabot encountered the following error:

Dependabot::DependencyFileNotParseable
```

And at least my eyes can't spot any of the error messages that are supposedly in the log that Github shows as extra details.

Update: a while later I realized the problem is that if there is an UTF-8 BOM in the file, *then* dependabot fails. So the failure reason is not the JSON data but the file starting with a BOM marker.

~~Experimenting randomly, I found out that if I remove the "allowPrerelease" part from my `global.json` file it starts working again. However, that should not be required as that is part of the `global.json` file specification since .NET Core 3.0: https://learn.microsoft.com/en-us/dotnet/core/tools/global-json~~

### Native package manager behavior

I have not seen any `dotnet` commands failing since adding my `global.json` file. So I think I got the syntax right. I tried switching `latestMajor` to `latestMinor` but that did not make dependabot work. Only after removing the `allowPrerelease` part did it suddenly start working.

**Comment by deivid-rodriguez** [comment]
Thanks for the report @hhyyrylainen, trying to fix this at #6714, it seems to work!
