### ISSUE TITLE
Github Enterprise Server Does Not Support Kubernetes and Helm Files

### ISSUE THREAD

**Issue by imRentable** [dependabot/dependabot-core#6720]
Hello,

I am trying to use Dependabot to update Docker image references in Kubernetes Deployment manifests as well as Helm values files. This works like a charm with repositories created under my private `github.com` but fails at my company that uses GitHub Enterprise Server 3.7.5. I am using a setup that is identical to my own private repositories which consists of a dummy Kubernetes Deployment manifest as well as a dummy Helm `values.yaml` at root level. The `dependabot.yml` is configured as follows:

```
version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/"
    schedule:
      interval: "weekly"
```

Now, it complains about a `Dockerfile` being missing:

![image](https://user-images.githubusercontent.com/12008255/221135636-c54a2d89-968d-4819-8b61-87f8a1e58a37.png)

Well, this is not wrong but this is not a problem in my `github.com` repo. If I add a `Dockerfile`, it won't complain anymore but will only update image references in said `Dockerfile` and completely ignores the Kubernetes manifest as well as the values file. 

It seems to somehow use a Dependabot version that does not provide Kubernetes and Helm file support (yet). Naturally, I contacted my system administrators and they triple-checked every setting and they look correctly. GitHub Connect is also enabled to ensure access to the latest actions. So, why does the behaviour of our GHES Dependabot differs so much from the one used in my private cloud account? Additionally am unable to find out which exact Dependabot Core version is used under the hood. How/where to get this information?

We are using runner version `2.296.2`.

**Comment by deivid-rodriguez** [comment]
Hei @imRentable!

This is more of a customer support question, than an issue with the dependabot-core open source library, so you will get better answers by going [through support](https://support.github.com) and the support team will be better equipped to help you.

I _think_ getting a newer version of `dependabot-action` on your server may help with this. You can do that using [actions-sync](https://docs.github.com/en/enterprise-server@3.7/admin/github-actions/managing-access-to-actions-from-githubcom/manually-syncing-actions-from-githubcom). But again, if you need help with any of this, please contact support and they'll be happy to get you up and running :smile:

**Comment by imRentable** [comment]
@deivid-rodriguez Thank you, will do.
