### ISSUE TITLE
Github Actions: Unexpected change of branch

### ISSUE THREAD

**Issue by LingMan** [dependabot/dependabot-core#6739]
### Package ecosystem

Github Actions

### Updated dependency

dtolnay/rust-toolchain

### What you expected to see, versus what you actually saw

Dependabot sent a PR to change `dtolnay/rust-toolchain@stable` to `dtolnay/rust-toolchain@master` in a Github Actions workflow. These are two different branches doing different things and this PR would break the workflow.
The same setup worked fine for many months now, so it must be a recent regression, presumably introduced in https://github.com/dependabot/dependabot-core/pull/6082.

cc @deivid-rodriguez

### Images of the diff or a link to the PR, issue, or logs

https://github.com/rust-lang/cargo-bisect-rustc/pull/259

**Comment by deivid-rodriguez** [comment]
Thanks for the quick report, let me look into this now.
