### ISSUE TITLE
Do you have any set release schedule?

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6745]
Hey there! 

I have a private fork of dependabot-core and I have been using tags/released versions to determine when to update my fork. 

In the past, you used to do at least one monthly release, but it seems that you changed the schedule recently considering that your last release was [almost 3 months ago](https://github.com/dependabot/dependabot-core/releases/tag/v0.215.0)

Should I be aware of any recent changes to your release schedule? Do you have any set release schedule?

I am not trying to rush you in any way as releases should be out when they are ready. I am just curious :) 

Thank you!

**Comment by deivid-rodriguez** [comment]
Have a look at #6670. I plan to get to it soon!
