### ISSUE TITLE
Inconsistent dependency labels

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

all

### What you expected to see, versus what you actually saw

I expect that all pull requests are labelled consistently 

Some pull requests are labelled as "dependencies" and ecosystem while others are labels as "dependency" and ecosystem

Examples: 

https://github.com/bigdaz/android-cache-fix-gradle-plugin/pull/22
https://github.com/DataBiosphere/terra-billing-profile-manager/pull/157

**Comment by deivid-rodriguez** [comment]
@yeikel This is because the second repository has explicit labels configured through `.github/dependabot.yml`. Let me know if that makes sense!

**Comment by yeikel** [comment]
> @yeikel This is because the second repository has explicit labels configured through `.github/dependabot.yml`. Let me know if that makes sense!

It makes sense in this scenario, but I have seen this inconsistency as well running dependabot-core directly 

Also in this example  https://github.com/24pullrequests/24pullrequests/blob/main/.github/dependabot.yml I do not see any mention to the "dependency" label but see https://github.com/24pullrequests/24pullrequests/pull/3916 

Another example: https://github.com/nimiq/core-rs-albatross/blob/albatross/.github/dependabot.yml

Please let me know if I am missing anything!

**Comment by deivid-rodriguez** [comment]
I don't have an explanation for that, so let me reopen this!

**Comment by yeikel** [comment]
Not stale
