### ISSUE TITLE
Handle submodule updates when creating GitLab PRs

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#676]
Hi @greysteil!

I'm having a problem when updating submodules, not sure if I'm doing anything wrong. In [this PR](https://gitlab.com/deivid-rodriguez/nipanipa/merge_requests/381/diffs), the submodule is being updated to a commit reference that I don't think it exists in the target repository? The submodule referenced in the diff should match the "target_reference" in the PR title ("Bump <repository> from `<source_reference>` to `<target_reference>`"), I think.

Not sure if the fact that I'm using "dependabot-script" to update itself might be a factor here, and whether the issue could be actually there and not in dependabot-core?

**Comment by greysteil** [comment]
That... looks really weird. Let me take a closer look.

**Comment by deivid-rodriguez** [comment]
Thanks! :heart:

**Comment by greysteil** [comment]
Ah, this is a problem with GitLab. Their API doesn't support pushing updated submodules (see https://gitlab.com/gitlab-org/gitlab-ce/issues/41213). I'm slightly amazed the script didn't blow up here - there's a note in Dependabot Core that submodules for GitLab are a TODO ([here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/gitlab.rb#L91-L92)) and I wasn't expecting the script to be successful at updating them.

I'll have a dig to see if there's any workaround here.

**Comment by deivid-rodriguez** [comment]
I see! Thanks @greysteil! Watching the Gitlab issue :)

**Comment by deivid-rodriguez** [comment]
Related gitlab issue got closed, apparently!

**Comment by greysteil** [comment]
I saw! Looks like they've implemented some entirely separate API for it 🤦‍♂️.

We need to wait for 11.5 to be released, but once that's out we should be able to get this closed 🎉

**Comment by connorshea** [comment]
11.5 is out now, fyi

**Comment by connorshea** [comment]
and now it's supported in the `master` branch of the gitlab gem :) https://github.com/NARKOZ/gitlab/pull/450

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/7b5e933097a63660c46cc529c0f54ed8c205a95d 🎉 

Thanks for everyone's help on this one. Can one of you verify that everything works as expected? I've just released `v0.86.20`, which includes that commit.
