### ISSUE TITLE
Add support for Salesforce packages, including private registries

### ISSUE THREAD

**Issue by AllanOricil** [dependabot/dependabot-core#6762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Salesforce packages are published in private registries and its package manifest is different than any other package manager. I would like to create a connector that would work with salesforce packages. Is it possible? if yes, how can I enable Dependabot in Github to use it?

You can find examples for salesforce manifests in this [link](https://developer.salesforce.com/docs/atlas.en-us.242.0.sfdx_dev.meta/sfdx_dev/sfdx_dev2gp_config_file.htm)

**Comment by jeffwidman** [comment]
> Salesforce packages are published in private registries and its package manifest is different than any other package manager. 

To clarify: you're saying they have a custom registry format for an existing language that we already support, or they have an entirely different language altogether? IIRC, they have their own DSL so it's essentially the latter, but I could be wrong...

> I would like to create a connector that would work with salesforce packages. Is it possible? if yes, how can I enable Dependabot in Github to use it?

Adding new ecosystems is currently [on pause](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems), but it's something we're having conversations about internally for the path forward, so we're closer than we were the last two years when we were simply buried. However, it's not clear yet how we'll handle support for package managers that are popular enough that someone wants to add support, but not popular enough for us the core team to commit to maintaining them. This would fit into that bucket. 

In the meantime, `dependabot-core` itself is structured in such a way that each ecosystem is it's own ruby gem. And you can run Dependabot standalone using an entry point like `dependabot-script`. So in the meantime you could absolutely write your own gem and then use it with `dependabot-core`. But to be clear, it wouldn't be pulled into the Dependabot service that GitHub runs. But if we did ever want to pull it in, having the standalone gem would make that much easier.

**Comment by AllanOricil** [comment]
Salesforce packages contain more than just a programming language. It has "metadata" that describes configurations for a Salesforce instance. 

I thought about creating dummy/empty npm/mvn packages and publish them in a public registry. This would make dependabot open a PR
