### ISSUE TITLE
Does dependabot-core support ssh-key authentication? 

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6793]
Does `dependabot-core` support `ssh-key` (deployment key) authentication? 

The events triggered from `GITHUB_TOKEN` do not create a new workflow run. and while a **personal access token**  is an option, that's not always desirable

related docs: https://docs.github.com/en/enterprise-server@3.5/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow and https://github.com/orgs/community/discussions/27028#discussioncomment-3254360 

Context: 

I am running [dependabot-script](https://github.com/dependabot/dependabot-script) using `GITHUB_TOKEN`  from Github Actions

**Comment by jeffwidman** [comment]
How would you want to use `ssh-key`? What ecosystems?

**Comment by yeikel** [comment]
> How would you want to use `ssh-key`? What ecosystems?

To clarify, I am referring to dependabot-core (and not the bot)

Currently, I am creating a new client using the following snippet: 

```ruby
credentials << {
  "type" => "git_source",
  "host" => ENV["GITHUB_ENTERPRISE_HOSTNAME"],
  "username" => "x-access-token",
  "password" => ENV["GITHUB_ENTERPRISE_ACCESS_TOKEN"]
}

source = Dependabot::Source.new(
  provider: "github",
  hostname: ENV["GITHUB_ENTERPRISE_HOSTNAME"],
  api_endpoint: "https://#{ENV['GITHUB_ENTERPRISE_HOSTNAME']}/api/v3/",
  repo: PROJECT_PATH,
  directory: DIRECTORY_PATH,
  branch: BRANCH == "" ? nil : BRANCH,
)

```

Rather than passing a `ENV["GITHUB_ENTERPRISE_ACCESS_TOKEN"]` we would be passing ssh-key and possibly ssh-known-hosts

Example : 

https://github.com/actions/checkout/blob/main/action.yml#L25-L47
https://github.com/actions/checkout/blob/ac593985615ec2ede58e132d2e21d2b1cbd6127c/src/url-helper.ts#L14-L16

**Comment by yeikel** [comment]
> Ah, I see what you're trying to do.
> 
> A few followup questions:
> 
>     1. What language / package manager ecosystem are you using Dependabot for?
> 
>     2. It looks like you're targeting a GHES instance... are you also running Dependabot from the GHES host or somewhere else? Curious why you're doing that rather than running Dependabot Service? It's totally cool to do that, I'm just curious to learn more about your use case to understand why Dependabot Service doesn't meet your needs, as it helps us better understand where to invest time into Dependabot Service vs Standalone.
> 
> 
> Currently we've limited the auth to HTTPS because in Dependabot Service we run a sidecar proxy for security so that untrusted code in repos/package managers never gets access to the creds... to them they're always talking to unauthenticated endpoints. We are currently thinking through the tradeoffs of using that proxy for all Dependabot entrypoints (including standalone via dependabot-script or CLI), vs the simplicity of not having the proxy... that's a larger conversation, but wanted to give you some details why right now we stick with HTTPS... While I understand your use case, supporting SSH would be a larger lift, so I don't forsee that happening.
> 
> But I'll leave open for now as I'd really like to better understand your use case around why using Dependabot standalone rather than Service.

Thank you for the detailed response. 

> What language / package manager ecosystem are you using Dependabot for?

We're currently running it for Docker, Gradle, Maven, NPM and Github Actions

>  2. It looks like you're targeting a GHES instance... are you also running Dependabot from the GHES host or somewhere else? Curious why you're doing that rather than running Dependabot Service? It's totally cool to do that, I'm just curious to learn more about your use case to understand why Dependabot Service doesn't meet your needs, as it helps us better understand where to invest time into Dependabot Service vs Standalone.

I have been running a modified version of  `dependabot-script` for over a year now. First we started using Jenkins, but we're currently migrating to GH Actions. We noticed the problem because of how the built in `GITHUB_TOKEN`  behaves

I appreciate your explanation and it seems that we're better off using our Personal Access tokens for now

> Curious why you're doing that rather than running Dependabot Service

The only reason we are doing this is because the internal support for Dependabot is not there yet. Ultimately, the goal is to move to the built in service but the timeline for that is beyond my control

I made a few internal enhancements to make it work within our network and at some point we even had our own version of Gradle Catalog support  (currently targeted with #6249). At the moment we have a version of core that pulls #6249 plus a few internal changes that I am currently working to extract them out to see if they can be incorporated within core

**Comment by jeffwidman** [comment]
Awesome, thanks for clarifying. Really useful info for us.

We are def open to PR's, although as you mentioned for any behavior changes generally most efficient to open an issue first to ensure we're open to the change.
