### ISSUE TITLE
[Github Actions] Update version reference from previous line

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, dependabot support the following syntax : 

```diff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 1683a447..6ceacb9d 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ jobs:
     steps:
       - name: gradle
-        uses: org/action@597dd3af9e492b8b4a6e58ac3755a433985277c0 # v1.0.2
+        uses: org/action@c84eb9737b59b6a7610591901fdaa85af4c11cbd # v1.0.4
```

In this case, it updates the action AND the version common within the same line

Ideally, it should also support this: 

```diff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 3646c5d7..af2b8bbc 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -279,8 +279,8 @@ jobs:
       - name: Deploy
-        # https://github.com/org/action/releases/tag/v2.3.0
-        uses: org/action/deploy@7c5bc97cdabac783604444fde5085aeed9735bd2
+        # https://github.com/org/action/releases/tag/v3.0.0
+        uses: org/action/deploy@6176534fe8f66142dddf4534cd27d3788082b210
```

Where the version is added in a previous line as a comment with format :  https://host/action/releases/tag/{tag}

**Comment by jeffwidman** [comment]
This one seems like it'd be tricky to get right, and there's a whole host of variations folks could use that are obvious to a human but not to a regex... and sometimes users may be specifically linking to an old version as part of a code comment.

I suggest you instead use the following syntax which is a combo of the two:
```
# See release notes here: https://github.com/org/action/releases
uses: org/action/deploy@6176534fe8f66142dddf4534cd27d3788082b210  # v2.3.0
```

I'm going to close as I don't see us building out further support for this. If it's something you feel strongly on such that you're interested in putting together a PR, let me know as I'd be open to discussing the specific logic you have in mind to avoid the edge cases.
