### ISSUE TITLE
Remove these hacks once we've deprecated npm 6 support as it no longer

### ISSUE THREAD

**Issue by lilsunny243** [dependabot/dependabot-core#6805]
https://github.com/lilsunny243/dependabot-core/blob/30f9e404c832253c2da6f61d73f6c51a6d96984e/updater/config/.yarnrc#L1

**Comment by jeffwidman** [comment]
Can you clarify?

**Comment by yeikel** [comment]
I think he is referring to TODO the file itself is declaring 

https://github.com/dependabot/dependabot-core/blob/main/updater/config/.yarnrc#L1-L6

**Comment by jeffwidman** [comment]
Yeah, i'm going to close for now, as the issue isn't super specific and the code TODO is probably good enough for now... we'll see it / clean it up when we bump NPM versions.
