### ISSUE TITLE
Fails to locate a version that satisfies the requirement

### ISSUE THREAD

**Issue by stumpylog** [dependabot/dependabot-core#6818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pipenv

### Language version

3.8.15

### Manifest location and content before the Dependabot update

https://github.com/paperless-ngx/paperless-ngx/blob/dev/Pipfile

https://github.com/paperless-ngx/paperless-ngx/blob/dev/Pipfile.lock

### dependabot.yml content

https://github.com/paperless-ngx/paperless-ngx/blob/main/.github/dependabot.yml

### Updated dependency

scipy == 1.8.1.  This version does exist on PyPI: https://pypi.org/project/scipy/#history

### What you expected to see, versus what you actually saw

I expect dependabot to handle a package being locked to a specific version and update other, not locked packages.  This is the behavior when running `pipenv lock` locally with Python 3.8.15 as the virtual environment creator.

Instead, it claims `dependency_file_not_resolvable` during updates to some (but not all) packages.  [Example](https://gist.github.com/stumpylog/77caeddf279c78fc167c1736ce269feb#file-dependabot-log-L8861).  It does appear to properly handle and ignore further update to the locked package, as seen [on this line](https://gist.github.com/stumpylog/77caeddf279c78fc167c1736ce269feb#file-dependabot-log-L8880)

### Native package manager behavior

Running `pipenv lock` manually with Python 3.8.15 works without issue.

### Images of the diff or a link to the PR, issue, or logs

Full logs: https://gist.github.com/stumpylog/77caeddf279c78fc167c1736ce269feb

**Comment by jeffwidman** [comment]
Relevant code here: https://github.com/dependabot/dependabot-core/blob/6c0e30514c92c336dcca9715ee387ea3a35a50fd/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb

Looks like you might be hitting this issue:
https://github.com/dependabot/dependabot-core/blob/6c0e30514c92c336dcca9715ee387ea3a35a50fd/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb#L22-L30

Are these errors only showing up in the log file, or in the summary of the Dependabot job? Because if the former, then it's just catching/logging errors as it processes stuff... confusing but I'm not sure we can do better w/o `pipenv` itself making changes, but if the latter than we're exposing those errors in a way that's confusing.

**Comment by stumpylog** [comment]
> Are these errors only showing up in the log file, or in the summary of the Dependabot job?

I'm not sure what the difference is.  The only view I have is from the Insights tab of the repo.  It seems much longer than a summary, so I'm guessing that's the logs.

**Comment by jeffwidman** [comment]
Is there an error visible above your logs?

Example of an error that's highlighted front and center like this:
![Screenshot 2023-03-14 at 12 39 14 PM](https://user-images.githubusercontent.com/483314/225118228-b143ffa8-0ded-4971-b360-121b6ba19e65.png)

**Comment by deivid-rodriguez** [comment]
We just updated the pipenv version we're running. Could you double check whether this is still an issue? Thanks!

**Comment by stumpylog** [comment]
Assuming running via Github's dependency page is the latest, dependabot still fails to resolve the lock file, while pipenv itself has no issues locking the packages.  The particular dependency of scipy==1.8.1 has been updated, but it still fails

A log from today: https://gist.github.com/stumpylog/4360c009b3872cba5dc8350bc0c339e1

**Comment by deivid-rodriguez** [comment]
I just noticed that your repo is public, and tried to update scipy there and it all went fine (No updates needed). Can you still reproduce this error? Maybe it was locking the python version that fixed it.

**Comment by stumpylog** [comment]
Never can manually reproduce the resolution failure.  Dependabot tried a couple days ago and failed:
![image](https://github.com/dependabot/dependabot-core/assets/797416/cf2057b8-b8b3-4805-a55d-8ed63ddbeeec)

The log looks essentially the same as the one above

**Comment by deivid-rodriguez** [comment]
Thanks, this seems specific to group updates.

**Comment by stumpylog** [comment]
It actually ran today and everything seems to be updating.  Thanks for the fix
