### ISSUE TITLE
Question/Heads-Up: Travis CI Deprecating Commit Status API

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/dependabot-core#683]
According to: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

> We will no longer deliver GitHub Commit Status API updates for repositories managed by GitHub Apps starting October 4th, 2018.

I'm not sure if you're already using the Github Checks API when determining the compatibility score in Dependabot, but just wanted to give you a heads up in case you're still reliant on the Commit Status API. Since Travis CI is so widely used in OSS, it might mean your compatibility scores have less data.

**Comment by greysteil** [comment]
Wow, hadn’t realised they were deprecating that aggressively! We already use them :-)
