### ISSUE TITLE
Dependabot ignores private Maven registry

### ISSUE THREAD

**Issue by timpeeters** [dependabot/dependabot-core#6842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### dependabot.yml content

```version: 2
registries:
  nexus:
    type: maven-repository
    url: https://<redacted>
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    registries:
      - nexus
    reviewers:
      - "<redacted>"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "Europe/Brussels"
```

### What you expected to see, versus what you actually saw

Expected:
- I expect Dependabot to check my private Maven registry for potential updates.
- Given there are newer versions available in the private Maven registry I expect Dependabot to create bumps for these

Actual:
- Dependabot does not find any potential updates
- Dependabot logging contains no reference to my private Maven registry and only fetches from `repo.maven.apache.org`

We have been using this functionality for several months already without issues. The dependabot.yml file has not been changed. The Maven registry is accessible. We suspect something might have broken with a recent update.

**Comment by brrygrdn** [comment]
Hi @timpeeters, this regression was introduced yesterday in https://github.com/dependabot/dependabot-core/pull/6810 and should be resolved by #6843 that just merged.

I'm waiting on some internal verification checks to complete before confirming.

**Comment by brrygrdn** [comment]
This issue should now be resolved, please re-open if you experience any further issues with this!

**Comment by timpeeters** [comment]
I can confirm that this now works. Thanks for the quick fix.
