### ISSUE TITLE
Dependabot producing ususable PRs for Gradle version catalogues and plugins

### ISSUE THREAD

**Issue by alsutton** [dependabot/dependabot-core#6863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

gradle 8.02

### Language version

Kotlin DSL

### Manifest location and content before the Dependabot update

/gradle/libs.versions.toml

### What you expected to see, versus what you actually saw

The PR produced was on build.gradle.kts and was;

```
-    id("com.google.protobuf") version libs.versions.protoPlugin apply false
+    id("com.google.protobuf") version 0.9.2 apply false
```

There are two issues with this;

* The version number increment should go in the version catalogue (gradle/libs.versions.toml), not the top level build file.
* The change fails to compile because the version number needs to be quoted.

### Images of the diff or a link to the PR, issue, or logs

<img width="976" alt="Screenshot 2023-03-17 151546" src="https://user-images.githubusercontent.com/430714/225946284-83f857dc-1bd9-4387-8227-7cad787c199e.png">

**Comment by deivid-rodriguez** [comment]
Hello @alsutton, thanks for reporting.

Can you share a small public project that reproduces the problem?

**Comment by alsutton** [comment]
I've put up https://github.com/alsutton/dependabot-issue-6863

When dependabot runs across it, what I'm expecting to happen, due to this issue, is an unusable diff on https://github.com/alsutton/dependabot-issue-6863/blob/main/build.gradle.kts changing `libs.versions.protoPlugin` to be `0.9.2` (unquoted)

**Comment by deivid-rodriguez** [comment]
Thanks for the repro @alsutton!

In the first version of Gradle Version Catalog support the we shipped, you need to keep your dependencies/plugins & versions in the catalog to get PRs. Keeping versions in the catalog, but plugins outside and referencing them like in that sample project is not supported.

But of course, creating an unusable PR is definitely a bug which I'm fixing at #6878.
