### ISSUE TITLE
Dependabot recreate / rebase not working

### ISSUE THREAD

**Issue by jack-berg** [dependabot/dependabot-core#6886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

maven

### What you expected to see, versus what you actually saw

I expected rebase / recreate to rebase / recreate the PR respectively. Instead, no updates are made to the PR commits. The PR description is temporarily changed to indicate some work is happening, but nothing is changed when the description returns to normal.

### Images of the diff or a link to the PR, issue, or logs

The commands recreate and rebase don't do anything. When I comment with those commands, dependabot adds a 👍 emoji, the PR temporarily has its description changed to:

> ⚠️ Dependabot is rebasing this PR ⚠️
Rebasing might not happen immediately, so don't worry if this takes some time.
Note: if you make any changes to this PR yourself, they will take precedence over the rebase.

Eventually, the description is restored, but no changes have be applied. I'm forced to manually resolve conflicts.

Examples:

- https://github.com/open-telemetry/opentelemetry-java/pull/5315
- https://github.com/open-telemetry/opentelemetry-java/pull/5316
- https://github.com/open-telemetry/opentelemetry-java/pull/5310

Many more examples available upon request.

Seems to be a duplicate of #1645 but the advice in that issue is that "catch all" issues aren't helpful and I should open a new issue.

**Comment by jeffwidman** [comment]
Hmm... I'm not seeing any conflicts on those PR's?

**Comment by jack-berg** [comment]
They need to rebase to incorporate updates to the target branch required for the build to pass. See [this other PR](https://github.com/open-telemetry/opentelemetry-java/pull/5316) where I manually merged main into the dependabot branch and the build now passes. I should be able to rebase or recreate to achieve the same affect.

**Comment by rturner3** [comment]
I am also seeing the same issue on several PRs:
https://github.com/spiffe/spire/pull/4015
https://github.com/spiffe/spire/pull/4016

**Comment by ikisler** [comment]
I am also running into this issue in multiple JS repos, but unfortunately they are all private so I can't share examples.

**Comment by nibynool** [comment]
Like @ikisler I'm also experiencing this on some JS/TS private repos.  About 95% of the time asking dependabot to close the PR and then asking it to reopen it, then requesting a recreate or rebase will get things moving again.  In the other 5% of cases I will wait for my team to push some additional changes to master/main and that will get the rebase going.

**Comment by jeffwidman** [comment]
Yeah, this unfortunately isn't one we can just ask you to repro on a public repository because it's a non-deterministic issue of some kind related to the :dependabot: service that GitHub runs.

I think the best thing to do here is to create a GitHub support ticket so you can point to the specific examples in your private repo, feel free to link specifically to this issue, and then one of us can dig into it to see if there's a race or some infra / DB flake that we're not properly recovering from.

I'm going to close as this isn't one we can really address via the public issue tracker.

**Comment by jack-berg** [comment]
@jeffwidman can you clarify why this is closed? The original issue I posted was reproducible on a public repo. Was this not an appropriate forum?

**Comment by jeffwidman** [comment]
Ah yeah, I missed that sorry. Let me re-open this one.

We will almost certainly end up having an internal ticket on our side to track the investigation and any internal facing notes about DB/service, and using the support ticket that we get is a good placeholder for that conversation, but there's nothing needed more from you, so no need for you to jump through the hoops necessary for that.

For anyone else who comes along, please open separate tickets... a public ticket linking to a publicly reproducible repository is preferred, but for something like this where it may only manifest on your private repo, then an internal support ticket is okay.

**Comment by jakecoffman** [comment]
I can see in the server logs that Dependabot ran the rebase, but when it posted the PR update to GitHub, it went silent. I'm adding additional logging on the server-side to get a better idea of what is happening. We need to capture what the error is from GitHub in order to address it.

Let me know if it happens again to another PR.

**Comment by jack-berg** [comment]
> Let me know if it happens again to another PR.

Will do! Thanks for the update.

**Comment by jack-berg** [comment]
Just ran it.

**Comment by jakecoffman** [comment]
Thanks I was able to capture the error with the new logging: `422 - At least 1 approving review is required by reviewers with write access.`

It looks like that repo has a wildcard branch protection rule. I think it is preventing Dependabot from force pushing to the branch it created.

**Comment by jack-berg** [comment]
Removed that setting and it worked. Thanks for looking into that @jakecoffman! I didn't se anything like that in the docs, but maybe I missed something. If not, would be good to add it so folks like me that self help. Thanks again! 🙂

**Comment by asbjornu** [comment]
Please allow me to echo @jack-berg's request:

> I didn't se anything like that in the docs, but maybe I missed something. If not, would be good to add it so folks like me that self help.

I just ran into this problem myself, where `@dependabot rebase` and `@dependabot recreate` caused Dependabot to thumbs up my comment and mark the original pull request message with:

>  ⚠️ Dependabot is rebasing this PR ⚠️

However, no force-push was performed by Dependabot no matter how long I waited (over 24 hours for a particular pull request). I'm not sure how to tweak the branch protection rules in my repositories to allow Dependabot to do its thing.

I would expect Dependabot to respond to the pull request with a comment explaining why it was unable to update it. Isn't that a reasonable thing to expect, @jakecoffman?

**Comment by srittau** [comment]
I have a few more (private) PRs that show the problem if it help to debug it: zfutura/office-iot#47, where I tried lots of different things, and zfutura/ferrum#268. I'm not sure it's related, but dependabot should actually have recognized the need to rebase itself. But for some reasons for pyproject.toml/poetry.lock changes this is flaky, while it works flawlessly for package.json/yarn.lock.

**Comment by NatoBoram** [comment]
* https://github.com/NatoBoram/lmgtfy/pull/60

![image](https://github.com/dependabot/dependabot-core/assets/10495562/09f9b6d3-9f79-4551-9c48-92839a8bb16a)

Got a :+1:, it put the rebase emoji, then nothing happened.

* https://github.com/NatoBoram/eldarya-enhancements/pull/11

![image](https://github.com/dependabot/dependabot-core/assets/10495562/e93f043f-819f-4720-88c2-a146f1407e05)

Got a :+1:, it put the rebase emoji, then nothing happened.


It's been happening all day with multiple PRs in multiple repos. I had to manually rebase them.

I understand that there's a lot of dependabot activity on the first of the month, but it would be nice if this could be tracked somehow and to not have a rebase end with no action when there's clearly actions to be done

**Comment by dylan-smith** [comment]
another public example, tried a bunch of dependabot commands to try to get it to process. Can't get it to rebase.
https://github.com/dylan-smith/DiveIntelligence/pull/248

**Comment by dotLou** [comment]
It seems to work fine for regular bump PRs but doesn't action the group ones, as far as I can tell (as well as the provided examples above)

**Comment by makskustomer** [comment]
> another public example, tried a bunch of dependabot commands to try to get it to process. Can't get it to rebase. [dylan-smith/DiveIntelligence#248](https://github.com/dylan-smith/DiveIntelligence/pull/248)

Seeing the same on a bunch of private repos and am frustrated on how to resolve this.

**Comment by PatrickTulskie** [comment]
I am also seeing this quite often on private repos. I will issue a `rebase` and nothing happens. Hours go by, I check again and it's still dormant. Dependabot puts a 👍 on my command though, so that part works. I've also tried recreate when it doesn't do a rebase and that seems to have no effect as well.

If there is going to be a super long delay after issuing a command, then some other indication that something is happening would be nice. Instead it looks like dependabot gave me a sarcastic thumbs up and then left for the day.

**Comment by ryanleecode** [comment]
Definately seems to be an issue in private repos

**Comment by fallemand** [comment]
Same problem on a private repo. No logs or info.

**Comment by tlkops** [comment]
Seeing the same on a private repo
