### ISSUE TITLE
Run cargo audit on Rust projects

### ISSUE THREAD

**Issue by mcandre** [dependabot/dependabot-core#6898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

You are neglecting to run the standard `cargo audit` tool for Rust projects.

https://crates.io/crates/cargo-audit

This is critical for catching CVE's in more Rust projects.

**Comment by jeffwidman** [comment]
That's a great suggestion, but not really what _this_ issue tracker is about. 

See https://github.com/dependabot/dependabot-core/issues/6800#issuecomment-1460735091 for why/where to report this suggestion.
