### ISSUE TITLE
API rate limit exceeded - describe how to perform authenticated request

### ISSUE THREAD

**Issue by laeubi** [dependabot/dependabot-core#6912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm try to do some coding with dependabot and followed the instructions on the page, but performing the "dry run" instantly lets me run into "API rate limit exceeded"

I found an old issue, but that was about running dependabot in production and its quite vague:
- https://github.com/dependabot/dependabot-core/issues/3024

so I wonder if it would be possible to enhance the current readme with a section how one has to configure the development dev docker container with a user token e.g. 

- what permissions must be granted?
- where to configure the token so it is used by dependabot dry_run script?

**Comment by jeffwidman** [comment]
Thanks @laeubi great questions.

I put up https://github.com/dependabot/dependabot-core/pull/7020 which addresses how to pass the token to the script.

As far as what permissions are needed, that depends on what repositories you're trying to access. For public repos, the base PAT with no additional permissions will suffice for getting a higher rate limit. For accessing private repositories, you'll need to ensure the PAT is authorized to read from those repositories.

Dry run doesn't actually create PR's, it emits the output it would use to create the PR, so no need for write permissions.

I thought ☝️ was a little more detail than needed in the README given that it just _works_ with the default perms, so for now only documented how to pass in the token, along with links to more docs on configuring PATs.

**Comment by laeubi** [comment]
@jeffwidman thanks I think this already helps, and most of the time a public repository is fine for testing anyways :+1:
