### ISSUE TITLE
Dependabot 'fixes' alert when an unrelated PR is merged

### ISSUE THREAD

**Issue by MonkeyDo** [dependabot/dependabot-core#6928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, npm

### Manifest location and content before the Dependabot update

https://github.com/metabrainz/listenbrainz-server/blob/7c28fb6d305b4b38fbd1ff39b1bbfd5bab65c686/requirements.txt

### Updated dependency

redis 4.3.3 > 4.5.3 

### What you expected to see, versus what you actually saw

Two Dependabot alerts are marked as "Fixed" and point to a pull request that is unrelated, while the actual PR that fixes the alert is unmerged.

See https://github.com/metabrainz/listenbrainz-server/security/dependabot/55 and https://github.com/metabrainz/listenbrainz-server/security/dependabot/54 , which at the time of writing are marked as "Fixed" and point to this (merged) PR: https://github.com/metabrainz/listenbrainz-server/pull/2395 (an unrelated PR which does not update the dependency in question)
![image](https://user-images.githubusercontent.com/6179856/228305296-ce1bd07f-fab9-4f53-800f-68446872a03f.png)
The alert concerns a python server dependency, while the linked PR concerns only frontend JS code.

However, Dependabot did correctly create a new PR with the required python dependency update: https://github.com/metabrainz/listenbrainz-server/pull/2428
On that PR 2428, the info bubble does point to the correct Dependabot alert:

```Merging this pull request will resolve a high severity [Dependabot alert](https://github.com/metabrainz/listenbrainz-server/security/dependabot/55) on redis.```

![image](https://user-images.githubusercontent.com/6179856/228305479-ea02066d-ea22-483a-9899-aba37a9909dd.png)

For reference, we also use Dependabot to update front-end dependencies, using npm as the package manager and a [package-lock.json](https://github.com/metabrainz/listenbrainz-server/blob/master/package-lock.json) lockfile.
The mistaken PR 2395 does update a front-end dependency and the lockfile, and the PR was merged.
Somehow this triggered Dependabot to mark the two alerts as Fixed despite the merged PR being unrelated.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/metabrainz/listenbrainz-server/security/dependabot/54
https://github.com/metabrainz/listenbrainz-server/security/dependabot/55
https://github.com/metabrainz/listenbrainz-server/pull/2428

And the unrelated PR:
https://github.com/metabrainz/listenbrainz-server/pull/2395

**Comment by deivid-rodriguez** [comment]
I suspect this already been fixed, so let me close this and open [a support ticket](https://support.github.com) if still not working.

The reason to go through a support ticket is that this repository only powers the generation of security updates, but not any behavior related to opening or closing the Dependabot alerts themselvees. That's responsability of another Github team, and you'll get to the through support 👍.

Thanks!
