### ISSUE TITLE
Add a `latest` tag for dependabot docker image

### ISSUE THREAD

**Issue by LeoColomb** [dependabot/dependabot-core#698]
Would be useful (and more standard compliant) if a `latest` tag is added to the lastest tag for the [dependabot/dependabot-core](https://hub.docker.com/r/dependabot/dependabot-core/) image.

**Comment by greysteil** [comment]
Good shout - done!

**Comment by LeoColomb** [comment]
@greysteil The `latest` tag disappeared. Normal?

**Comment by greysteil** [comment]
I.... have no idea how that happened. Let me get it fixed.

**Comment by greysteil** [comment]
Fixed. Sorry about that!

**Comment by LeoColomb** [comment]
No worry, thanks a lot! 👍
