### ISSUE TITLE
YAML file with dot in their name aren't detected by Dependabot::Docker::FileFetcher

### ISSUE THREAD

**Issue by negrel** [dependabot/dependabot-core#7008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

NA

### Language version

NA

### Manifest location and content before the Dependabot update

/deployment.abc.yaml

### dependabot.yml content

NA

### Updated dependency

NA

### What you expected to see, versus what you actually saw

FileFetcher.files doesn't contain `deployment.abc.yaml`

File and any file containing a dot doesn't match the following YAML regex:
```ruby
      YAML_REGEXP = /^[^\.]+\.ya?ml$/i.freeze
```
https://github.com/dependabot/dependabot-core/blob/HEAD/docker/lib/dependabot/docker/file_fetcher.rb#L11

### Native package manager behavior

NA

### Images of the diff or a link to the PR, issue, or logs

NA

### Smallest manifest that reproduces the issue

NA

**Comment by jeffwidman** [comment]
Makes sense.

Want to submit a PR fixing it?

**Comment by negrel** [comment]
Yes sure !
