### ISSUE TITLE
Update `dependabot-core/.devcontainer`/`core-dev/devcontainer.json` to remove old / outdated gems and extensions.

### ISSUE THREAD

**Issue by dwc0011** [dependabot/dependabot-core#7017]
### Code improvement description

ruby-debug-ide relies on debase, that is problematic for getting tests running and debugging via vscode

While trying to debug, the error below is triggered.  You can edit the Gemfile and manually run bundle again to install debase and have it work, but then you have to remember to remove it and not commit it etc.  If it is present in the Gemfile before building the devcontainer, the devcontainer will fail to build.  Removing ruby-debug-ide which hasnt been updated since  September 20, 2021, will prevent these errors.
```
bundler: failed to load command: rdebug-ide (/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/bin/rdebug-ide)
/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide.rb:9:in `require': cannot load such file -- debase (LoadError)
```
In order to continue to support debugging, I propose changing the ruby-debug-ide in ominbus Gemfile to the debug gem
`gem "ruby-debug-ide", group: :development `
to 
`gem  "debug", group: :development `

To support debugging in the devcontainer a new extension is also required ("koichisasada.vscode-rdbg")
The misogi.ruby-rubocop vscode extension is no longer maintained and has been abandonedd should be replaced by the replacement ("LoranKloeze.ruby-rubocop-revived").

The new extensions would be :
```
"extensions": [
        "rebornix.ruby",
        "castwide.solargraph",
        "LoranKloeze.ruby-rubocop-revived",
        "groksrc.ruby",
        "hoovercj.ruby-linter",
        "miguel-savignano.ruby-symbols",
        "koichisasada.vscode-rdbg"
      ]
```

I am willing to create a PR for this, please let me know.

**Comment by jeffwidman** [comment]
Sounds reasonable. 👍

PR's would be appreciated, it sounds like at least 2 and possibly 3 different PR's?

**Comment by dwc0011** [comment]
> Sounds reasonable. 👍
> 
> PR's would be appreciated, it sounds like at least 2 and possibly 3 different PR's?

Yes I would say, one for the omnibus gemfile, one for the extensions, and one for the instructions.

I will have them submitted Monday at the latest, thanks!

**Comment by jeffwidman** [comment]
Re-opening as #7040 also needs to merge before this can be closed.
