### ISSUE TITLE
Dependabot recreate / rebase not working

### ISSUE THREAD

**Issue by wmitsuda** [dependabot/dependabot-core#7018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

This seems similar to https://github.com/dependabot/dependabot-core/issues/6886 , I'm opening this ticket because the last comment on that issue is asking to do so.

Dependabot apparently got stuck for some old PRs with conflicts in my repo. Apparently new dependency PRs are not affected, i.e., I could merge them.

My project is opensource, so I'm posting some public links to PRs that got stuck:

https://github.com/otterscan/otterscan/pull/769
https://github.com/otterscan/otterscan/pull/774

There are a few ones that I simply closed hoping that next dependency increase will "ressurrect" them.

Not sure if it has something to do with this issue, but the repo was moved into an organization (it was previously under my personal github username) two days ago, all stuck PRs are from before the move.

**Comment by jakecoffman** [comment]
> Not sure if it has something to do with this issue, but the repo was moved into an organization (it was previously under my personal github username) two days ago, all stuck PRs are from before the move.

That's probably exactly what happened. I see we have two entries in the database for that repo, one is deleted and the other was created on 2023-04-03 19:19:08 UTC. Is that about the time it was moved?

We have a current known issue where if you delete a section of your dependabot.yml, the PRs stay up but Dependabot basically ignores them. This is an interesting new twist on that issue.

I'm going to add this to our internal tracking issue to help address this better in the future, thanks for posting it. Fell free to 
close those PRs and see if Dependabot puts up some new ones after the next run.

**Comment by wmitsuda** [comment]
It’s the exact timestamp the repo was moved.

I think I’ll just close the remaining PRs pre move, and update their  versions manually using npm then.

**Comment by jakecoffman** [comment]
@wmitsuda I just recreated the issue and verified that if you close the PRs and run Dependabot manually it will recreate the PRs correctly. It will comment that it is ignoring that dependency, but that refers to the data object that is "deleted" and not the current one, so you can ignore it. 

Thanks again for reporting this, it brings a lot of new information to this problem!

**Comment by wmitsuda** [comment]
It seems the manual recreation workaround works, thanks!
