### ISSUE TITLE
combine similar modules in one bump

### ISSUE THREAD

**Issue by punkratz312** [dependabot/dependabot-core#7021]
### What you expected to see, versus what you actually saw

combine similar modules in one bump

chore(deps): bump io.quarkus from 2.16.5.Final to 2.16.6.Final in /02_Software/TherapyExecutor
chore(deps): bump io.quarkus.platform:quarkus-bom from 2.16.5.Final to 2.16.6.Final in /02_Software/TherapyExecutor

these guys work together a seperste bump works but is actually not intended:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/8830888/230522504-6e59152f-613f-4615-9f0a-baf504d46dc2.png">

same here with even more modules:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/8830888/230522836-52fe10cb-fbe6-46ae-b91f-c96698a85995.png">

they can be bumped seperatly but have the same root package or company so it could be matched and bumped as batch:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/8830888/230522708-a775745c-1415-49aa-8a80-70d0586d4b95.png">

thanks for the great project 

a simple matching for

package-path
id
version 

is a 100% match its the same thing and can be packed as one bump. this state is acquired by dependa at the moment to but with baby steps for each module wich is maybe find of nice as an configureable switch, but as default, would be desired to be combined as one bump.

**Comment by yeikel** [comment]
This is a duplicated and discussed here https://github.com/dependabot/dependabot-core/issues/1190

**Comment by yeikel** [comment]
For your specific scenario, you can easily fix this if you create a property for the version as dependabot will update the version and gradle will detect the update for all of them. 

Please note that this only works if the version is always exactly the same for the dependency

**Comment by yeikel** [comment]
I double checked this project https://github.com/serenity-bdd/serenity-core

And it seems to be a monorepo with single release for all the modules. If that's the case, you should definitely define a property as you should never update these separately

**Comment by punkratz312** [comment]
> never update these separately

yes just like the quarkus bom is a platform provider so it makes no sense to bump these separately as well, but thats how it is.

convention over configuration. the desired (since 2019) behaviour should be default and the prop should disable it not otherwise. whats the issue? 

there can be made a good match making to find similar modules/packages, so whats the issue? wont fix? 

i like dependa so much is it hard to implement? if not i might create an mr.


thanks for the quick reply.

**Comment by punkratz312** [comment]
@yeikel would it be possible to add and auto merge option as well? we want this as a team and its possible in gitlab to set the merge_when_pipeline_succeeds switch, but i have no clue how to tell dependa to add this param. can you please help me out? thanks and happy easter 🐣 


<img width="1285" alt="image" src="https://user-images.githubusercontent.com/8830888/230657864-036bdf4c-81dd-4eed-86ef-5082d4752e71.png">

**Comment by yeikel** [comment]
> > never update these separately
> 
> yes just like the quarkus bom is a platform provider so it makes no sense to bump these separately as well, but thats how it is.
> 
> convention over configuration. the desired (since 2019) behaviour should be default and the prop should disable it not otherwise. whats the issue?
> 
> there can be made a good match making to find similar modules/packages, so whats the issue? wont fix?
> 
> i like dependa so much is it hard to implement? if not i might create an mr.
> 
> thanks for the quick reply.

I do not understand what you're trying to say here. To clarify, dependabot does not support the "grouped feature" natively for all the package managers, but it does allow updating a variable that directly translates to a grouped upgrade if you follow that pattern

In your scenario, all you need to do is to create a new constant to store the version and to use that constant while defining the dependency within your gradle build. Example : 
Rather than : 


```

  testImplementation("net.serenity-bdd:serenity-core:3.6.22")
  testImplementation("net.serenity-bdd:serenity-junit:3.6.22")
  testImplementation("net.serenity-bdd:serenity-cucumber:3.6.22")

```

You can define your dependencies like : 


```

buildscript {
    ext {
        serenityVersion= '3.6.22'
    }

}

dependencies {
    testImplementation("net.serenity-bdd:serenity-core:${serenityVersion}")
  testImplementation("net.serenity-bdd:serenity-junit:${serenityVersion}")
  testImplementation("net.serenity-bdd:serenity-cucumber:${serenityVersion}")
```

This way: 
- Gradle will resolve `serenityVersion` to `3.6.22` at build time
- Dependabot will detect that `serenityVersion` refers to more than one dependency, so when it sends the pull request it will be a single pull request that will effectively upgrade all the dependencies in one single pull request. Dependabot will also collect separate changelogs and commits for each one

Let me know if you have any other question about this



> @yeikel would it be possible to add and auto merge option as well? we want this as a team and its possible in gitlab to set the merge_when_pipeline_succeeds switch, but i have no clue how to tell dependa to add this param. can you please help me out? thanks and happy easter 🐣
> 
> then the whole issue would be acceptable for as as its kind of extra secure to check every single bump on the other hand, even tho there can be some incompatible, if so the mr fails like intendet and then the manual inclusion works as well.
> 
> thanks
> 
> <img alt="image" width="1285" src="https://user-images.githubusercontent.com/8830888/230657864-036bdf4c-81dd-4eed-86ef-5082d4752e71.png">

I am not familiar with the dependabot integration in Gitlab. Is this what you're using? 

https://gitlab.com/dependabot-gitlab/dependabot

If so, that project is not affiliated with this repository(or team) and you should reach out to them about that option. It should be double to enable that flag or to build a gitlab pipeline to do so. 




Happy Easter!  🐣

**Comment by punkratz312** [comment]
@yeikel can you plz help me out here:

we have like 10 modules and all work pretty much the same. gradle and docker works fine but npm and pub not.



<img width="1437" alt="image" src="https://user-images.githubusercontent.com/8830888/230781502-33fa344c-e2fb-4641-aab4-84822ff256ea.png">



<img width="1073" alt="image" src="https://user-images.githubusercontent.com/8830888/230781608-6df5a3c2-4f44-4d96-b78d-803e34210ced.png">


always like RepoNotFound.




we have a very old npm version (14) current is 19. 

maybe thats an issue? 


<img width="647" alt="image" src="https://user-images.githubusercontent.com/8830888/230782005-3784bb36-4ea4-43d2-b7f0-46df75a2fb00.png">


here yml is not supported:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8830888/230781800-fdfd4dff-0ef6-4c52-9ce8-b622ce8afc5d.png">




actually strange why the other does not throw the issue:

as the porjects are the same and have no "default" docker file:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/8830888/230781857-5366cd8e-6595-49b0-b517-ec3e8e3d4f6f.png">


<img width="377" alt="image" src="https://user-images.githubusercontent.com/8830888/230781873-5ddfc181-4549-499f-9bc0-e750a11dc943.png">



will .yml files will be suported soon too? 

we have need for bumping these version as well:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/8830888/230781921-e523ce1d-4458-47fe-b973-2d0163a2cec4.png">

**Comment by yeikel** [comment]
> @yeikel can you plz help me out here:
> 
> we have like 10 modules and all work pretty much the same. gradle and docker works fine but npm and pub not.
> 
> 
> 
> <img width="1437" alt="image" src="https://user-images.githubusercontent.com/8830888/230781502-33fa344c-e2fb-4641-aab4-84822ff256ea.png">
> 
> 
> 
> <img width="1073" alt="image" src="https://user-images.githubusercontent.com/8830888/230781608-6df5a3c2-4f44-4d96-b78d-803e34210ced.png">
> 
> 
> always like RepoNotFound.
> 
> 
> 
> 
> we have a very old npm version (14) current is 19. 
> 
> maybe thats an issue? 
> 
> 
> <img width="647" alt="image" src="https://user-images.githubusercontent.com/8830888/230782005-3784bb36-4ea4-43d2-b7f0-46df75a2fb00.png">
> 
> 
> here yml is not supported:
> 
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/8830888/230781800-fdfd4dff-0ef6-4c52-9ce8-b622ce8afc5d.png">
> 
> 
> 
> 
> actually strange why the other does not throw the issue:
> 
> as the porjects are the same and have no "default" docker file:
> 
> <img width="1425" alt="image" src="https://user-images.githubusercontent.com/8830888/230781857-5366cd8e-6595-49b0-b517-ec3e8e3d4f6f.png">
> 
> 
> <img width="377" alt="image" src="https://user-images.githubusercontent.com/8830888/230781873-5ddfc181-4549-499f-9bc0-e750a11dc943.png">
> 
> 
> 
> will .yml files will be suported soon too? 
> 
> we have need for bumping these version as well:
> 
> <img width="1136" alt="image" src="https://user-images.githubusercontent.com/8830888/230781921-e523ce1d-4458-47fe-b973-2d0163a2cec4.png">
> 
> 
> 
> 

This is a different problem. Please create a new issue and also share more information. We need at least a minimum reproducible code. If you can please share the dependency manifests instead of screenshots

**Comment by yeikel** [comment]
Also, would you be ok if we closed this one? 

As suggested, using the property should help with your original problem

**Comment by punkratz312** [comment]
@yeikel yes no worry. the property is a workaround that is fine and common to combine multiple modules with an simle variable and bump this instead of every item itself. we want simpler code that tells everything instead of splitting the info. therfore we keep the bump item for item, its no problem.

thanks for the support as well.

**Comment by punkratz312** [comment]
@yeikel thanks as the single ones causing merge issues evertime this is the best solution thank you 
<img width="903" alt="image" src="https://user-images.githubusercontent.com/8830888/230901829-0f54f687-7481-44f2-9b8d-19ce51a7a9a7.png">
