### ISSUE TITLE
How do I get dependabot to download dependencies from "pub.dev"?

### ISSUE THREAD

**Issue by kanari3** [dependabot/dependabot-core#7047]
### Code improvement description

dependabot downloads dependencies from "pub.dartlang.org"
But in the local environment, dependencies are downloaded from "pub.dev".
How can I get it to download dependencies from "pub.dev"?

Is there a dependabot settings for this problem?

```
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-x64, locale ja-JP)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/kanari3/fvm/versions/3.7.7. Consider adding /Users/kanari3/fvm/versions/3.7.7/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

I would like to have a flutter version of dependabot and a local flutter version.

Where can I find the flutter version of dependabot?

Is the following correct?
https://github.com/dependabot/dependabot-core/blob/main/pub/Dockerfile#L9

**Comment by jakecoffman** [comment]
My understanding is pub.dev and pub.dartlang.org are the same server.

The current Dart version Dependabot runs is 2.19.0. You might find [this README](https://github.com/dependabot/dependabot-core/blob/main/pub/README.md) informative, it states:

> The pub dependabot integration supports the flutter releases on the stable and beta [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels). Each Flutter release comes with a matching Dart release.

Hope this helps!
