### ISSUE TITLE
Inline component alert suppression

### ISSUE THREAD

**Issue by huornlmj** [dependabot/dependabot-core#7049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In certain situations, bumping a component version is not technically possible.  To avoid recurring alerts I would like a feature that allows suppression at either the per-line level or component version level.  This would be more granular than excluding entire manifest files.

**Comment by yeikel** [comment]
Can you share the manifest, and how the exclusion would look like?

**Comment by jeffwidman** [comment]
Closing due to lack of user response. If you care to provide the details @yeikel requested, happy to reopen.
