### ISSUE TITLE
Gemspec updating does not respect symlinks

### ISSUE THREAD

**Issue by mlarraz** [dependabot/dependabot-core#7071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### What you expected to see, versus what you actually saw

After https://github.com/dependabot/dependabot-core/pull/7051, path-based gems that are installed via symlink are having the symlink to their gemspec deleted and replaced with the a file with the updated contents.

Instead, Dependabot should respect the symlink, not delete it, and update the original gemspec at its source.

**Comment by deivid-rodriguez** [comment]
Thanks for the notice @mlarraz!

I suspect this is an issue symlinks in general, just showed up for you  after we introduced #7051 because you symlink gemspecs.

Can you post an example public project reproducing the issue, so that I can use it to reproduce this and fix it?

**Comment by laboone** [comment]
Hi, I am also experiencing the same issue.
Since there is no public repository that reproduces the problem, I will post if I am able to create a repository that can reproduce the issue.

**Comment by laboone** [comment]
@deivid-rodriguez @jakecoffman 
I have created a repository that reproduces the issue: https://github.com/laboone/monorepo-for-dependabot
In this repository, Dependabot creates a PR that removes the symlink, as shown in https://github.com/laboone/monorepo-for-dependabot/pull/1.

I have also created a PR https://github.com/dependabot/dependabot-core/pull/7352 that reverts the changes made in https://github.com/dependabot/dependabot-core/pull/7051.
I would appreciate it if you could merge https://github.com/dependabot/dependabot-core/pull/7352 :pray:

**Comment by laboone** [comment]
@deivid-rodriguez 
I believe this fix (https://github.com/dependabot/dependabot-core/pull/7411) is necessary. Could you please merge and release it?

**Comment by deivid-rodriguez** [comment]
Sorry for the delay @laboone. Fix is live now, let me know how it's working!
