### ISSUE TITLE
Support arbitrary version of pipenv

### ISSUE THREAD

**Issue by jxltom** [dependabot/dependabot-core#715]
The pipenv is still not stable. It will be nice to support arbitrary version of pipenv or at least some recently major versions.

If it takes too much effort to implement this, just ignore this issue. 😄 Let's hope next release of pipenv will be much better.

**Comment by jxltom** [comment]
Oh I didn't know there are workarounds for pipenv bugs in dependabot. That's perfect!

```2018.10.13``` has a bug with extras which is very annoying. But it is fine since I think there will be a release soon which fixes this.

Supporting latest (or most stable) pipenv version + workaround for bugs (if there are any) satisfies me. 
 I'm closing this. 🎉

**Comment by greysteil** [comment]
Yeah, we tend to notice any bugs pretty early, and try to patch them in Dependabot or Pipenv as quickly as we can. We're far from perfect, but we're doing what we can!

**Comment by jxltom** [comment]
This is so great. Will continue using dependabot for sure 😄
