### ISSUE TITLE
Would you be open to integrate with Sonarcloud?

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#7150]
Hey there

Did you ever consider integrating with [Sonar](https://sonarcloud.io/welcome) for additional code quality scans?

I think that it could be a nice addition(maybe as an optional check to start) as it is free for open source projects

It supports [Ruby ](https://rules.sonarsource.com/ruby) as well as most(if not all) of all the other Native Helpers

**Comment by Nishnha** [comment]
As far as I can tell, we don't use Sonar at GitHub. We will probably have to get an approval from legal to use this tool even though we are open source.

Taking a look at the rules that it supports, I think most of these are covered by our linter, [rubocop](https://github.com/dependabot/dependabot-core/blob/f06cf6032456cefdb03e4708f78551d49fe18a1b/omnibus/.rubocop.yml)?

It could be nice for helpers though.
