### ISSUE TITLE
Should Only lockfile updates (ignore updates that require Pipfile changes) be the default option?

### ISSUE THREAD

**Issue by jxltom** [dependabot/dependabot-core#716]
If I pin package with specific version in Pipfile as following, the dependabot will still open PR for updating that.

Will it be better to set only updating lockfile as the default option? since that is the most use cases.

I'm a new user of dependabot which is cool for me. Just to share a few thoughts. :D

```
[packages]
celery = "==3.1.25"
```

**Comment by greysteil** [comment]
👋 @jxltom, and thanks for giving Dependabot a try!

A lot of users pin but still want updates, so we update both the `Pipfile` and the `Pipfile.lock` by default. There's a setting to only update the lockfile if you'd rather, or if you'd like Dependabot to ignore a specific dependency you can comment `@dependabot ignore this dependency`.

Keep the feedback coming!

**Comment by jxltom** [comment]
OK, thanks for the reply. 😄
