### ISSUE TITLE
[java] dependabot is confused by inconsistent version numbering of `com.google.template:soy`

### ISSUE THREAD

**Issue by dpursehouse** [dependabot/dependabot-core#718]
The latest version of [this artifact](https://search.maven.org/search?q=g:com.google.template%20AND%20a:soy&core=gav) is `2018-03-14`.

Most of the versions follow the same convention (`YYYY-MM-DD`), however there is one version from a couple of years ago with the version `v20160111`.  Dependabot detected that as the latest version and submitted a PR: https://github.com/dpursehouse/java-deps/pull/18

My wild guess is that it sorted the versions alphanumerically, which results in `v20160111` coming after `2018-03-14`.

The Maven Central search page (see the first link) correctly lists the versions by date.

**Comment by greysteil** [comment]
Interesting. Our Java version sorting uses the Macon comparison definitions, but it looks like we might want to special case situations like this more pragmatically. I’ll take a look tomorrow (it’s late here in the U.K.).

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/e00ea5009c718c45c2dca28e55ce80bca02881ca. Thanks for the heads up!

**Comment by dpursehouse** [comment]
Thanks! 🍻
