### ISSUE TITLE
Dependabot fails when including a git submodule Gradle project using Gradle includeBuild feature

### ISSUE THREAD

**Issue by Thomas-Vos** [dependabot/dependabot-core#7201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

Gradle 7.6

### Language version

Kotlin 1.8.20

### Manifest location and content before the Dependabot update

/build.gradle.kts
/settings.gradle.kts

/somemodule1/build.gradle.kts
/somemodule2/build.gradle.kts
/subproject/build.gradle.kts
/subproject/settings.gradle.kts

> This is the git submodule folder pointing to a different GitHub repository, which should be ignored by Dependabot:

/CommonLibraries

> (in the submodule):

/CommonLibraries/commonGradleConfiguration/build.gradle.kts

and some more files

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
    open-pull-requests-limit: 50
```

### What you expected to see, versus what you actually saw

Error provided by GitHub:

```
Dependabot couldn't find a build.gradle.

Dependabot requires a build.gradle to evaluate your Java dependencies. It had expected to find one at the path: /CommonLibraries/commonGradleConfiguration/build.gradle.

If this isn't a Java project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.
```

It seems Dependabot cannot read git submodules. The CommonLibraries folder is a git submodule pointing to another  (private) GitHub repository. That repository contains another (standalone) Gradle project, which has its own Dependabot configuration in that repository.

I think Dependabot should just ignore the gradle files in that submodule, as it can't even update them even if it could read them. The reason Dependabot is looking for gradle files in that directory is probably because the CommonLibraries project is included using the Gradle `includeBuild` feature. Is there a way to exclude this from Dependabot? Currently I cannot get it working due to this issue.

The file `/subproject/settings.gradle.kts` contains the following which references the git submodule:
includeBuild("../CommonLibraries/commonGradleConfiguration")

### Images of the diff or a link to the PR, issue, or logs

Private repository

**Comment by patari** [comment]
https://github.com/dependabot/dependabot-core/pull/7078 should fix this, not pretty but effective.

**Comment by Thomas-Vos** [comment]
Does anyone know of a workaround for this issue?

**Comment by patari** [comment]
> Does anyone know of a workaround for this issue?

I didn't test it but you should be able to move `includeBuild("../CommonLibraries/commonGradleConfiguration")` to a file Dependabot doesn't scan, e.g.

1. Move `includeBuild("../CommonLibraries/commonGradleConfiguration")` line from `/subproject/settings.gradle.kts` to `/subproject/hidden_from_dependabot.gradle.kts` and
2. Add `apply(from = "hidden_from_dependabot.gradle.kts")` to `/subproject/settings.gradle.kts`.

**Comment by vitorhugods** [comment]
> > Does anyone know of a workaround for this issue?
> 
> I didn't test it but you should be able to move `includeBuild("../CommonLibraries/commonGradleConfiguration")` to a file Dependabot doesn't scan, e.g.
> 
>     1. Move `includeBuild("../CommonLibraries/commonGradleConfiguration")` line from `/subproject/settings.gradle.kts` to `/subproject/hidden_from_dependabot.gradle.kts` and
> 
>     2. Add `apply(from = "hidden_from_dependabot.gradle.kts")` to `/subproject/settings.gradle.kts`.

Just adding my testimony here, that this works flawlessly.

Here's a commit showing the work-around:
https://github.com/wireapp/wire-android-reloaded/commit/0c79cbe0d75fd76674815a0b0627fdda9778b881
