### ISSUE TITLE
pip & pip-tools incompatibility

### ISSUE THREAD

**Issue by paddycarey** [dependabot/dependabot-core#7226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Python

### Language version

Python 3.9

### What you expected to see, versus what you actually saw

We're seeing failures to update any of our Python dependencies for the past several weeks. We use `pip-tools` to manage our lock files and it seems that dependabot is getting tripped up on a recently introduced incompatibility between `pip-tools` and `pip` itself.

We're seeing the following traceback for each dependency in the dependabot log:

```
updater | 2023/05/03 13:56:45 ERROR <job_656628458> Error processing importlib-metadata (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/05/03 13:56:45 ERROR <job_656628458> Using indexes:
updater |   https://<redacted>/python/simple/
updater |   https://pypi.python.org/simple
updater | Traceback (most recent call last):
updater |   File "/usr/local/.pyenv/versions/3.9.16/bin/pip-compile", line 8, in <module>
updater |     sys.exit(cli())
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
updater |     return self.main(*args, **kwargs)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1055, in main
updater |     rv = self.invoke(ctx)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
updater |     return ctx.invoke(self.callback, **ctx.params)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 760, in invoke
updater |     return __callback(*args, **kwargs)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
updater |     return f(get_current_context(), *args, **kwargs)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/piptools/scripts/compile.py", line 589, in cli
updater |     results = resolver.resolve(max_rounds=max_rounds)
updater |   File "/usr/local/.pyenv/versions/3.9.16/lib/python3.9/site-packages/piptools/resolver.py", line 545, in resolve
updater |     wheel_cache = WheelCache(
updater | TypeError: __init__() takes 2 positional arguments but 3 were given
```

This appears to be the same issue as described here: https://github.com/jazzband/pip-tools/issues/1854

We had been seeing this locally too and upgrading `pip-tools` to 6.13.0 fixed it for us in our local environments.

From a quick look it seems that dependabot pins the versions of these tools here: https://github.com/dependabot/dependabot-core/blob/main/python/helpers/requirements.txt and that `pip` was updated just last week here: https://github.com/dependabot/dependabot-core/pull/7097/files

Is it possible the pip update triggered the incompatibility? AFAIK upgrading pip-tools to `6.13.0` _should_ resolve the issue.

**Comment by paddycarey** [comment]
I missed this issue in my initial search, but there's an open PR that i think would fix the issue (and another report) over at https://github.com/dependabot/dependabot-core/pull/7034

**Comment by jakecoffman** [comment]
#7034 is merged and deployed. Looks like it fixed similar issues for other folks so I'll close this, but let us know if you're still having issues.
