### ISSUE TITLE
Commit message formatting

### ISSUE THREAD

**Issue by mrwilson** [dependabot/dependabot-core#725]
Hi!

Love this project, we're making heavy use of it on our [WhereDoIVote-Widget](https://github.com/DemocracyClub/WhereDoIVote-Widget) which powers an election-information widget.

I try to style my commit messages like [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) (also called Angular/Karma/Semantic commits) when I write code.

How easy would it be to optionally format the commit messages from Dependabot to resemble the above?

Something like

`chore(dependabot): Bump react-scripts from 1.1.5 to 2.0.5`

Thanks!

**Comment by greysteil** [comment]
Hey, sorry for the slow reply on this one. Busy day!

Dependabot should automatically detect if you're using conventional commits, and adjust its style accordingly. You'll get PRs like [these ones](https://github.com/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+org%3Awireapp) when it does. The logic it uses to do so is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb#L625-L633) - basically if 30% or more of your last 30 commits use conventional commits, Dependabot will. I've just noticed that Dependabot was counting merge commits in there though, which is what will have been causing the issues - that's now fixed!
