### ISSUE TITLE
Publish dependabot-core on dockerhub again

### ISSUE THREAD

**Issue by zbynek** [dependabot/dependabot-core#7294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The docker image https://hub.docker.com/r/dependabot/dependabot-core disappeared -- can you please put it back?

**Comment by zbynek** [comment]
Apparently the docker image can be still obtained from https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-core and/or https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-core-development

**Comment by jeffwidman** [comment]
Yep, see more context here: https://github.com/dependabot/dependabot-script/pull/917

Sorry for the breaking change in some ways, I couldn't find an easy way to notify folks of the new location, and we haven't been publishing it for 3+ months, so decided while I was doing some other cleanup on our Dockerhub account to remove that as well.

**Comment by zbynek** [comment]
Hopefully if someone else is trying to find it they will stumble upon this issue :)

**Comment by lorengordon** [comment]
How do you specify the FROM source for the new location?

**Comment by lorengordon** [comment]
Ok, not quite there yet. How do we pull from that? I just get a 401 unauthorized error?
