### ISSUE TITLE
Resolve Maven group id and artifact id from Maven properties

### ISSUE THREAD

**Issue by michalvavrik** [dependabot/dependabot-core#7309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have got BOM like this

https://github.com/quarkus-qe/quarkus-test-framework/blob/692b6ed2f55d4a3258625c7b814a19f0ad8586f8/pom.xml#L78

```
<dependency>
    <groupId>${quarkus.platform.group-id}</groupId>
    <artifactId>${quarkus.platform.artifact-id}</artifactId>
    <version>${quarkus.platform.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

as very often, we need to be able to use project with different Quarkus versions and make this change from CLI like this `mvn clean verify -Dquarkus.platform.version=3.0.1.Final -Dquarkus.platform.artifact-id=io.quarkus.platform` etc. It really depends on situation. However I didn't find a way to tell Dependabot to update Maven properties

```
<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
<quarkus.platform.version>3.0.3.Final</quarkus.platform.version>
```

It would be nice if Dependabot could automate this bump for us (it can be optional behavior in case you sense some troubles doing this be default...).

**Comment by michalvavrik** [comment]
That is, dependabot doesn't update `quarkus.platform.version`.

**Comment by edeandrea** [comment]
Hi @michalvavrik I don't really understand what the issue is here? Are you saying that Dependabot doesn't update this? I have lots of Quarkus projects set up that way and Dependabot updates them just fine.

See https://github.com/quarkusio/quarkus-super-heroes/pull/507

**Comment by michalvavrik** [comment]
> Hi @michalvavrik I don't really understand what the issue is here?

Issue is that Dependabot didn't create single bump for this very dependency.

> Are you saying that Dependabot doesn't update this?

Yes.

> I have lots of Quarkus projects set up that way and Dependabot updates them just fine.
> See [quarkusio/quarkus-super-heroes#507](https://github.com/quarkusio/quarkus-super-heroes/pull/507)

I didn't know that, opened issue because I assumed that Dependabot doesn't handle this. In that case my only explanation is this line

https://github.com/quarkus-qe/quarkus-test-framework/blob/a64ea18a5aac85fcde4e21dc37d42d562b9fab03/.github/dependabot.yml#L10

which makes sense (and I didn't mention it till now) and I'll close this issue if dropping it fixes the problem. Thanks for the link and info.

**Comment by edeandrea** [comment]
You can see the `dependabot.yml` that we use here: https://github.com/quarkusio/quarkus-super-heroes/blob/main/.github/dependabot.yml

**Comment by michalvavrik** [comment]
> You can see the `dependabot.yml` that we use here: https://github.com/quarkusio/quarkus-super-heroes/blob/main/.github/dependabot.yml

no worry, that was the first thing I checked, thanks!

**Comment by michalvavrik** [comment]
Alright, we have it working now https://github.com/quarkus-qe/quarkus-test-framework/pull/1001 (removing the ignore rule for plugin helped), sorry for the fuss and thank you for help.
