### ISSUE TITLE
Two different dependencies being updated if version is the same

### ISSUE THREAD

**Issue by bbednarek** [dependabot/dependabot-core#734]
Our `build.gradle` looks like this
```
allprojects {

    dependencyManagement {
        overriddenByDependencies = false

        dependencies {

            dependencySet(group: 'ca.uhn.hapi.fhir', version: '3.2.0') {
                entry 'hapi-fhir-server'
                entry 'hapi-fhir-structures-dstu3'
            }

            dependency 'io.rest-assured:rest-assured:3.2.0'
        }
    }
}
```

Dependabot created PR to update `ca.uhn.hapi.fhir` to version `3.5.0`, but in the same PR `io.rest-assured:rest-assured` got updated to `3.5.0` which doesn't exist.

**Comment by greysteil** [comment]
Ooh, that's not good. Can you ping the URL of the bad PR to support@dependabot.com and I'll take a look?

**Comment by bbednarek** [comment]
This is unfortunately private repo. Screenshots would be sufficient?

**Comment by greysteil** [comment]
It's OK - I took a look in our DB and we've only done that update for one repo. i'm working through replicating now and will have a fix out in the next hour or so. Apologies for the bug!

**Comment by bbednarek** [comment]
Thank you very much for such quick help!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/87cb62fca83f53a277c1f339dee48d109c5e2083, which is deploying now. Apologies for taking a couple of days to get to this one, and thanks for reporting it!
