### ISSUE TITLE
Exclude reverted commits from the release notes

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#7366]
This issue refers to the release notes of **dependabot-core** (as opposed to the metadata added in pull requests)

### improvement description

If a commit is reverted, it should not be included in the release notes

See : https://github.com/dependabot/dependabot-core/pull/7145 and https://github.com/dependabot/dependabot-core/releases/tag/v0.218.0

**Comment by jurre** [comment]
We use GitHub's automated "Generate release notes" feature for this, so other than manually editing it, there's not much we can do right now to facilitate automation of this 🤔
