### ISSUE TITLE
Add support for package.json.tpl in NPM projects

### ISSUE THREAD

**Issue by yiqing-zhao** [dependabot/dependabot-core#7367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We currently have lots of templates of `package.json` file (e.g. https://github.com/OfficeDev/TeamsFx/blob/dev/templates/scenarios/ts/workflow/package.json.tpl) in our project. We are trying to update these template files by using dependabot. However, it seems that current NPM file-ecosystem only support `package.json` and `package-lock.json`. It would be a great help if the file extension `package.json.tpl` is included npm system as well.

**Comment by jurre** [comment]
Can you provide a bit more context about `package.json.tpl`, it's not something that I'm familiar with. Is it something that's supported by npm, I can't find any documentation about it.

**Comment by jurre** [comment]
Ah, I see, there's currently no way to update those files with Dependabot, as we try to stick to supporting the formats provided by the package managers that we support.
