### ISSUE TITLE
[github-actions] dependabot not updating https://github.com/Swatinem/rust-cache

### ISSUE THREAD

**Issue by tamird** [dependabot/dependabot-core#7384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

There are a few affected manifests in aya-rs/aya: https://github.com/search?q=repo%3Aaya-rs%2Faya%20Swatinem%2Frust-cache&type=code, and one in aya-rs/bpf-linker: https://github.com/aya-rs/bpf-linker/blob/7847c0b2959ca517779ff569ef0d231e6734fad8/.github/workflows/build-test.yml#L39-L40

### dependabot.yml content

https://github.com/aya-rs/aya/blob/main/.github/dependabot.yml

### Updated dependency

https://github.com/Swatinem/rust-cache (v1 vs v2)

### What you expected to see, versus what you actually saw

I expected an update, but none happened.

**Comment by Drarig29** [comment]
We have a similar issue, where we recently set up dependabot to work on 2 repositories with the exact same `dependabot.yml` file, and only one repository had dependabot pull requests opened.

This file was recently updated with `v3` for `checkout` and `setup-node`:

https://github.com/DataDog/datadog-ci-azure-devops/blob/25703a397130d0ff50bac161eb0f49574fe1aac5/.github/workflows/unit-tests.yml

But this file (in a different repository) did not, although they are very similar:

https://github.com/DataDog/synthetics-ci-github-action/blob/dd7049d88a128ad2c01fe567792ab2a25f918eef/.github/workflows/unit-tests.yml

Is there a way to see dependabot's debug logs?

**Comment by tamird** [comment]
@Drarig29 I think your issues are caused by a separate problem (which I also have seen in https://github.com/aya-rs/bpf-linker/pull/47): your repo contains multiple different workflows, and some of them reference `checkout@v2` while others reference `checkout@v3`: https://github.com/search?q=repo%3ADataDog%2Fsynthetics-ci-github-action%20actions%2Fcheckout&type=code.

You can see the dependabot logs for your repo at https://github.com/DataDog/datadog-ci-azure-devops/network/updates - click on the "last checked ..." link.

It's probably worth finding that log (it will contain some errors) and reporting a separate bug. I should have done that - now that I manually bumped the dep in https://github.com/aya-rs/bpf-linker/pull/47, my old log is gone.

**Comment by Drarig29** [comment]
> You can see the dependabot logs for your repo at https://github.com/DataDog/datadog-ci-azure-devops/network/updates - click on the "last checked ..." link.

Oh, thanks I would never have found it! I'll open an issue.

**Comment by deivid-rodriguez** [comment]
This should be fixed now. If you have not workaround this issue, feel free to check for updates now and it should properly create PRs 👍.

**Comment by Drarig29** [comment]
@deivid-rodriguez it worked, thank you!

**Comment by deivid-rodriguez** [comment]
Thanks for letting us know @tamird. #7494 should fix this.
