### ISSUE TITLE
There is a difference between `go mod tidy` on Dependabot and `go mod tidy` on CI

### ISSUE THREAD

**Issue by ono-max** [dependabot/dependabot-core#7385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Language version

1.20.4

### Manifest location and content before the Dependabot update

https://github.com/bucketeer-io/bucketeer/blob/main/go.mod

### dependabot.yml content

https://github.com/bucketeer-io/bucketeer/blob/main/.github/dependabot.yaml

### Updated dependency

The following PRs have the same problem. 

Expected: `google.golang.org/genproto/googleapis/api` should be added in direct dependencies. When running `go mod tidy` on CI or on the local environment, `google.golang.org/genproto/googleapis/api` is added as a direct dependency in go.mod.
Actual: `google.golang.org/genproto/googleapis/api` is added as an indirect dependency in go.mod when creating PR from Dependabot.

https://github.com/bucketeer-io/bucketeer/pull/387
https://github.com/bucketeer-io/bucketeer/pull/384
https://github.com/bucketeer-io/bucketeer/pull/375

### What you expected to see, versus what you actually saw

There should be no difference between `go mod tidy` on Dependabot and `go mod tidy` on CI.

### Images of the diff or a link to the PR, issue, or logs

Here is a Dependabot PR

https://github.com/bucketeer-io/bucketeer/pull/387/files

I got a diff after running `go mod tidy` on CI:

```diff
diff --git a/go.mod b/go.mod
index ab59bef..319b2ab 100644
--- a/go.mod
+++ b/go.mod
@@ -38,6 +38,7 @@ require (
        golang.org/x/time v0.3.0
        google.golang.org/api v0.124.0
        google.golang.org/genproto v0.0.0-20230530153820-e85fd2cbaebc
+       google.golang.org/genproto/googleapis/api v0.0.0-20230530153820-e85fd2cbaebc
        google.golang.org/genproto/googleapis/rpc v0.0.0-20230530153820-e85fd2cbaebc
        google.golang.org/grpc v1.55.0
        google.golang.org/protobuf v1.30.0
@@ -114,7 +115,6 @@ require (
        golang.org/x/tools v0.6.0 // indirect
        golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2 // indirect
        google.golang.org/appengine v1.6.7 // indirect
-       google.golang.org/genproto/googleapis/api v0.0.0-20230530153820-e85fd2cbaebc // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
 )
```

**Comment by jakecoffman** [comment]
The issue seems to be that the CI is generating code from the proto files before it runs `go mod tidy`. Since Dependabot doesn't do that, it's correct that `google.golang.org/genproto/googleapis/api` is indirect since Dependabot does not generate code first.

Go's recommendation is to check in generated code to source control to make it go-gettable: https://go.dev/blog/generate

>Also, if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients.

That would fix this issue with Dependabot as well so I would suggest doing that. Otherwise, I'm not sure how Dependabot will be able to succeed here.

**Comment by ono-max** [comment]
We can solve the problem based on your advice! Thank you!
