### ISSUE TITLE
^ appears before version number

### ISSUE THREAD

**Issue by mrmajik45** [dependabot/dependabot-core#740]
![screenshot 2018-11-02 at 10 02 15 am](https://user-images.githubusercontent.com/35823544/47919838-d5473e00-de86-11e8-9c57-53c535f6b57b.png)

A ^ character appears before the version number.

**Comment by greysteil** [comment]
That's by design as it's updating the requirement (in JS the caret is the SemVer operator). If you have a lockfile then Dependabot will know exactly which version you're using, but without one it can only update the requirement.
