### ISSUE TITLE
Support for C, C++, C#, etc.

### ISSUE THREAD

**Issue by mrmajik45** [dependabot/dependabot-core#743]
Alot of the github projects I do have mostly C in them. (Idk if C can have dependencies.

**Comment by RohanNagar** [comment]
C# (.NET) already has beta support: https://dependabot.com/dotnet/

**Comment by mrmajik45** [comment]
I mean I mostly use C. But why not get the other ones too.

**Comment by greysteil** [comment]
As I understand it there's no dominant package manager in C or C++. If folks tell me different and they want Dependabot to work on their repos I'll certainly consider adding it, though 🙂 

Thanks for the feedback!
