### ISSUE TITLE
Packages aren't updated if in npm workspaces, but more up to date in root

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#7460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 9.7.1

### Language version

node 18.16.0

### Manifest location and content before the Dependabot update

https://github.com/broksonic21/xstate-dependabot/blob/main/package.json

https://github.com/broksonic21/xstate-dependabot/blob/main/packages/wrapper/package.json

### dependabot.yml content

https://github.com/broksonic21/xstate-dependabot/blob/main/.github/dependabot.yml

### Updated dependency

xstate "^4.37.1" should be ^4.37.2 

### What you expected to see, versus what you actually saw

in the workspace/packages package.json, it has "^4.37.1"

in the root package-lock it has 4.37.2

but Dependabot doesn't think there's an update (when it should update ^4.37.1 to ^4.37.2)

It does update this fine if there's an update to the root package-lock.json, but not if there's not.

Logs are:
```
updater | 2023/06/20 21:11:51 INFO <job_681398619> Checking all dependencies for version updates...
updater | 2023/06/20 21:11:51 INFO <job_681398619> Checking if xstate 4.37.2 needs updating
  proxy | 2023/06/20 21:11:51 [014] GET https://registry.npmjs.org:443/xstate
  proxy | 2023/06/20 21:11:51 [014] 200 https://registry.npmjs.org:443/xstate
  proxy | 2023/06/20 21:11:52 [016] GET https://registry.npmjs.org:443/xstate/4.37.2
  proxy | 2023/06/20 21:11:52 [016] 200 https://registry.npmjs.org:443/xstate/4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> Latest version is 4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> No update needed for xstate 4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> Finished job processing
```

### Native package manager behavior

in the wrapper package (in the workspace): https://github.com/broksonic21/xstate-dependabot/blob/main/packages/wrapper/package.json

```
(main ✔) npx npm-check-updates
Need to install the following packages:
  npm-check-updates@16.10.12
Ok to proceed? (y) Y
Checking /Users/REDACTED/xstate-dependabot/packages/wrapper/package.json
[====================] 1/1 100%

 xstate  ^4.37.1  →  ^4.37.2

Run npx npm-check-updates -u to upgrade package.json
```

### Images of the diff or a link to the PR, issue, or logs

```
updater | 2023/06/20 21:11:51 INFO <job_681398619> Checking all dependencies for version updates...
updater | 2023/06/20 21:11:51 INFO <job_681398619> Checking if xstate 4.37.2 needs updating
  proxy | 2023/06/20 21:11:51 [014] GET https://registry.npmjs.org:443/xstate
  proxy | 2023/06/20 21:11:51 [014] 200 https://registry.npmjs.org:443/xstate
  proxy | 2023/06/20 21:11:52 [016] GET https://registry.npmjs.org:443/xstate/4.37.2
  proxy | 2023/06/20 21:11:52 [016] 200 https://registry.npmjs.org:443/xstate/4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> Latest version is 4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> No update needed for xstate 4.37.2
updater | 2023/06/20 21:11:52 INFO <job_681398619> Finished job processing
```

### Smallest manifest that reproduces the issue

https://github.com/broksonic21/xstate-dependabot

**Comment by Nishnha** [comment]
Hi I took a look at the repo you linked and I think Dependabot is behaving correctly here.

In your package-lock.json, `xstate` is listed with version `4.37.2`.

The package.json in your packages/wrapper workspace requires `xstate` `^4.37.1`, which the installed version satisfies. 

Dependabot did not modify your package.json since the requirement is satisfied and does not need to be updated.

If you want to see the package.json always update when the lockfile version changes, you can use the `increase` [Dependabot versioning-strategy](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy).

Hope this helps!

**Comment by broksonic21** [comment]
@Nishnha not sure that's exactly right -- we are using increase --- see https://github.com/broksonic21/xstate-dependabot/blob/main/.github/dependabot.yml#L5
