### ISSUE TITLE
Grouped updates did not upgrade everything

### ISSUE THREAD

**Issue by bmulholland** [dependabot/dependabot-core#7471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.4.10

### Language version

Ruby 3.2.2

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

```
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      timezone: "Europe/Berlin"
      time: "19:45"
    groups:
      # Dependabot grouped updates:
      # Docs at https://gist.github.com/brrygrdn/0dac4e16c68898fda33d8fa81d575e1a
      # This is the name of your group, it will be used in PR titles and branch
      # names
      dependencies:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

I'm evaluating Dependabot grouped updates. During this period, I have both Depfu and Dependabot generating PRs on my repo. This week, Dependabot generated a PR about 5 hours after the Depfu one (we hadn't merged Depfu in the meantime). I'd have expected the Dependabot PR to be the same as (or a superset of) the Depfu upgrades. However, the upgrades were a subset: some upgrades were missed.

### Images of the diff or a link to the PR, issue, or logs

Here's a diff from the Dependabot PR to the Depfu one (added = Depfu had it, Dependabot didn't).

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 998c7b39..a878b30b 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -154,7 +154,7 @@ GEM
       aws-partitions (~> 1, >= 1.651.0)
       aws-sigv4 (~> 1.5)
       jmespath (~> 1, >= 1.6.1)
-    aws-sdk-dynamodb (1.85.0)
+    aws-sdk-dynamodb (1.87.0)
       aws-sdk-core (~> 3, >= 3.174.0)
       aws-sigv4 (~> 1.1)
     aws-sdk-kms (1.67.0)
@@ -172,10 +172,10 @@ GEM
       aws-sdk-core (~> 3, >= 3.174.0)
       aws-sdk-kms (~> 1)
       aws-sigv4 (~> 1.4)
-    aws-sdk-ses (1.50.0)
+    aws-sdk-ses (1.51.0)
       aws-sdk-core (~> 3, >= 3.174.0)
       aws-sigv4 (~> 1.1)
-    aws-sdk-sesv2 (1.34.0)
+    aws-sdk-sesv2 (1.35.0)
       aws-sdk-core (~> 3, >= 3.174.0)
       aws-sigv4 (~> 1.1)
     aws-sdk-sqs (1.58.0)
@@ -265,9 +265,9 @@ GEM
       google-apis-core (>= 0.11.0, < 2.a)
     google-apis-gmail_v1 (0.29.0)
       google-apis-core (>= 0.11.0, < 2.a)
-    google-protobuf (3.23.2-arm64-darwin)
-    google-protobuf (3.23.2-x86_64-darwin)
-    google-protobuf (3.23.2-x86_64-linux)
+    google-protobuf (3.23.3-arm64-darwin)
+    google-protobuf (3.23.3-x86_64-darwin)
+    google-protobuf (3.23.3-x86_64-linux)
     googleapis-common-protos-types (1.6.0)
       google-protobuf (~> 3.14)
     googleauth (1.5.2)
@@ -331,7 +331,7 @@ GEM
     msgpack (1.7.1)
     multi_json (1.15.0)
     multi_xml (0.6.0)
-    net-imap (0.3.4)
+    net-imap (0.3.6)
       date
       net-protocol
     net-pop (0.1.2)
@@ -497,7 +497,7 @@ GEM
     opentelemetry-instrumentation-racecar (0.2.1)
       opentelemetry-api (~> 1.0)
       opentelemetry-instrumentation-base (~> 0.22.1)
-    opentelemetry-instrumentation-rack (0.23.1)
+    opentelemetry-instrumentation-rack (0.23.2)
       opentelemetry-api (~> 1.0)
       opentelemetry-common (~> 0.19.3)
       opentelemetry-instrumentation-base (~> 0.22.1)
@@ -543,7 +543,7 @@ GEM
       opentelemetry-api (~> 1.0)
       opentelemetry-instrumentation-base (~> 0.22.1)
       opentelemetry-semantic_conventions (>= 1.8.0)
-    opentelemetry-registry (0.2.0)
+    opentelemetry-registry (0.3.0)
       opentelemetry-api (~> 1.1)
     opentelemetry-sdk (1.2.1)
       opentelemetry-api (~> 1.1)
@@ -770,7 +770,7 @@ GEM
       unf_ext
     unf_ext (0.0.8.2)
     unicode-display_width (2.4.2)
-    unparser (0.6.7)
+    unparser (0.6.8)
       diff-lcs (~> 1.3)
       parser (>= 3.2.0)
     vcr (6.1.0)
```

**Comment by bmulholland** [comment]
Here's the Dependabot logs. For security reasons, I'd prefer not to have the full BOM public, so let me know when you've received and saved the logs so I can delete it: https://gist.github.com/bmulholland/ab729d14f07f0dacf1dfb568607fa292

I note that there is no entry saying "Checking if xxx needs updating" for the missing packages.

**Comment by bmulholland** [comment]
It looks like these are all transitive dependencies...

**Comment by brrygrdn** [comment]
Thanks for this report, we'll have a look at the job and figure out what is going on. 

It looks like you have not specified an `allow` [rule](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) so we should be using the default strategy of `all` rather than `direct` and including transitive dependencies, so this seems like a bug in grouped behaviour.

**Comment by Nishnha** [comment]
Hi @bmulholland I started taking a look at this and since your repo is private, we will need to request access to it in order to investigate why the update did not upgrade everything. 

If you are okay with this let me know and I can request access.

My initial suspicious is that there is some direct dependency that is locking these transitive dependencies from upgrading to the latest version. I do find it odd that some of the transitive dependencies were unable to upgrade to the latest patch version though, so there may be something else going on here.

If you would like to delete the gist I have downloaded the job logs.

Thanks!

**Comment by bmulholland** [comment]
Hi @Nishnha thanks for looking into this. I just got back from PTO. Sure, happy to grant you access to investigate. FYI, we have essentially zero pinned versions in our Gemfile.

**Comment by Nishnha** [comment]
Hi @bmulholland, I took a shot at recreating and debugging this issue.

Something that stood out to me is that in the original grouped update, Dependabot only attempted to update ~10 dependencies, and some dependencies were skipped altogether.

I noticed that in a more recent grouped update on your repository, Dependabot is attempting to update ~80 dependencies.

Have you updated your dependabot.yaml file or group configuration since then? I wonder if this was a temporary issue that may have been resolved by https://github.com/dependabot/dependabot-core/pull/7358 or another bug fix?

**Comment by bmulholland** [comment]
I did update my dependabot.yml, changing just the commit prefix. But I'm also not seeing the 80 updates you're talking about?

<img width="715" alt="Screenshot 2023-07-10 at 13 28 42" src="https://github.com/dependabot/dependabot-core/assets/247713/46569ece-6a5b-4913-9d86-287762260e7d">

**Comment by bmulholland** [comment]
Today's weekly update included most updates that I see in the Depfu PR, but not all. It's missing e.g. [aws-sdk-ses 1.53.0, which came out on the 6th.](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-ses/CHANGELOG.md#1530-2023-07-06)

**Comment by jbergstroem** [comment]
I have a similar case.

#### Config

```yaml
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint-plugin-storybook"
```

#### `package.json` in `main`
```json
{
    "@storybook/addon-essentials": "^7.0.18",
    "@storybook/addon-interactions": "^7.0.26",
    "@storybook/addon-links": "^7.0.26",
    "@storybook/blocks": "^7.0.18",
    "@storybook/nextjs": "^7.0.18",
    "@storybook/react": "^7.0.18",
    "@storybook/testing-library": "^0.2.0",
    "storybook": "^7.0.26"
}
```

#### `package.json` in dependency PR
```json
{
    "@storybook/addon-essentials": "^7.0.27",
    "@storybook/addon-interactions": "^7.0.27",
    "@storybook/addon-links": "^7.0.27",
    "@storybook/blocks": "^7.0.18",
    "@storybook/nextjs": "^7.0.27",
    "@storybook/react": "^7.0.18",
    "@storybook/testing-library": "^0.2.0",
    "storybook": "^7.0.27"
}

#### Log for failed updates
```
<snip>
updater | 2023/07/12 16:20:22 INFO <job_693270112> Updating @storybook/addon-links from 7.0.26 to 7.0.27
updater | 2023/07/12 16:20:39 INFO <job_693270112> Checking if @storybook/blocks 7.0.27 needs updating
  proxy | 2023/07/12 16:20:39 [156] GET https://registry.npmjs.org:443/@storybook%2Fblocks
  proxy | 2023/07/12 16:20:39 [156] 200 https://registry.npmjs.org:443/@storybook%2Fblocks
  proxy | 2023/07/12 16:20:40 [158] GET https://registry.npmjs.org:443/@storybook%2Fblocks/7.0.27
  proxy | 2023/07/12 16:20:40 [158] 200 https://registry.npmjs.org:443/@storybook%2Fblocks/7.0.27
updater | 2023/07/12 16:20:40 INFO <job_693270112> Latest version is 7.0.27
updater | 2023/07/12 16:20:40 INFO <job_693270112> No update needed for @storybook/blocks 7.0.27
<snip>
updater | 2023/07/12 16:21:02 INFO <job_693270112> Requirements to unlock own
updater | 2023/07/12 16:21:02 INFO <job_693270112> Requirements update strategy bump_versions
updater | 2023/07/12 16:21:02 INFO <job_693270112> Updating @storybook/nextjs from 7.0.18 to 7.0.27
updater | 2023/07/12 16:21:22 INFO <job_693270112> Checking if @storybook/react 7.0.27 needs updating
  proxy | 2023/07/12 16:21:22 [368] GET https://registry.npmjs.org:443/@storybook%2Freact
  proxy | 2023/07/12 16:21:22 [368] 200 https://registry.npmjs.org:443/@storybook%2Freact
  proxy | 2023/07/12 16:21:23 [370] GET https://registry.npmjs.org:443/@storybook%2Freact/7.0.27
  proxy | 2023/07/12 16:21:23 [370] 200 https://registry.npmjs.org:443/@storybook%2Freact/7.0.27
updater | 2023/07/12 16:21:23 INFO <job_693270112> Latest version is 7.0.27
updater | 2023/07/12 16:21:23 INFO <job_693270112> No update needed for @storybook/react 7.0.27
<snip>
```

**Comment by jakecoffman** [comment]
@jbergstroem I think that issue should be fixed by https://github.com/dependabot/dependabot-core/pull/7561. Open a new issue if it's still broken, I'd be happy to look into it more.

@bmulholland I may have addressed this issue in https://github.com/dependabot/dependabot-core/pull/7561 and https://github.com/dependabot/dependabot-core/pull/7621. Would you mind trying again and see if it's fixed?

**Comment by jbergstroem** [comment]
> @jbergstroem I think that issue should be fixed by https://github.com/dependabot/dependabot-core/pull/7561. Open a new issue if it's still broken, I'd be happy to look into it more.

Will monitor the coming days and comment if required.

**Comment by bmulholland** [comment]
@jakecoffman I just tried rebasing our weekly upgrade PRs from Depfu and Dependabot within a few minutes of each other. The one from Dependabot included all changes that were in Depfu, except two transitive dependencies. I checked the Dependabot logs and, notably, did not see a line that says "Checking if <package> <version> needs updating" for those two. That seems to suggest that, for at least two packages, we'd never get updates.

**Comment by jakecoffman** [comment]
Per https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow, you have to add an `allow` entry for `dependency-type: all` to get updates to transitive dependencies. That would explain why it didn't check it for updates.

**Comment by bmulholland** [comment]
This weeks updates have run, including my dependabot.yml which specifies allowing all, and all dependencies were correctly updated. I'd say that this is fixed -- thank you!
