### ISSUE TITLE
Dependabot opens PR even though I completely removed it

### ISSUE THREAD

**Issue by l3d00m** [dependabot/dependabot-core#7489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

I've deleted the dependabot.yml a few weeks ago. The commit where I deleted it can be found here: https://github.com/reims2/reims2-frontend/commit/0d3b15a07c942d20321e57f5052041b447918fd5

### What you expected to see, versus what you actually saw

I've deleted the dependabot.yml a few weeks ago and disabled security updates. Alerts are enabled.

I still get PRs for version updates (even without security issues). That should not happen as I deleted the dependabot.yml and it shows as disabled in the GitHub settings.

Here is my repo: https://github.com/reims2/reims2-frontend/ and here is an example PR that should not have been opened: https://github.com/reims2/reims2-frontend/pull/89

### Images of the diff or a link to the PR, issue, or logs

https://github.com/reims2/reims2-frontend/pull/89

And this one as well https://github.com/reims2/reims2-frontend/pull/70

**Comment by stinodego** [comment]
I had the same thing happen when I fully commented out all contents of the `dependabot.yml`. I still got pull requests, according to the settings that were commented out (weekly on Monday).

**Comment by l3d00m** [comment]
There's also #7361 and #5486. It seems to require manual intervention, so I might just open a GitHub support ticket

**Comment by l3d00m** [comment]
Has been resolved with GitHub Support.
