### ISSUE TITLE
`quarterly` option for `schedule.interval`

### ISSUE THREAD

**Issue by rafalh** [dependabot/dependabot-core#7552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to run Dependabot once per quarter (3 months) for rarely updated repositories. It should be pretty simple to add support for a new value in [schedule.interval](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval) configuration key and also simpler than adding support for cron expressions that was proposed in #6339.

**Comment by nvictor** [comment]
I also think that this is simpler.
