### ISSUE TITLE
Dependabot (gomod) update job fails when a dependency has empty or no requirements

### ISSUE THREAD

**Issue by julio-lopez** [dependabot/dependabot-core#7588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Package manager version

1.20

### Language version

1.20

### Manifest location and content before the Dependabot update

[/go.mod](https://github.com/kopia/kopia/blob/master/go.mod)

### dependabot.yml content

https://github.com/kopia/kopia/blob/master/.github/dependabot.yml

### Updated dependency

Fails when scanning the htmluibuild dependency at
https://github.com/kopia/htmluibuild/blob/master/go.mod , which has no requirements

```
module github.com/kopia/htmluibuild

go 1.20
```

### What you expected to see, versus what you actually saw

# Observed

For either automatic or manual checks of the dependencies for the `gomod` ecosystem in the github.com/kopia/kopia repository results in a run warning / error.

See https://github.com/kopia/kopia/network/updates/696945271 apparently due to a dependency github.com/kopia/htmluibuild that has no dependencies itself, it only uses packages from the Go Standard Library.

Below is a log excerpt.

# Expected

For the check (execution) to complete without errors. It seems that having a Go module with no dependencies is a valid use case, for those packages or repos that only rely on the Go Standard Library.

---

```
updater | 2023/07/19 00:43:32 ERROR <job_696945271> Error processing github.com/kopia/htmluibuild (ArgumentError)
updater | 2023/07/19 00:43:32 ERROR <job_696945271> blank strings must not be provided as requirements
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/dependency.rb:272:in `check_requirement_fields'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/dependency.rb:249:in `check_values'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/dependency.rb:59:in `initialize'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:177:in `new'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:177:in `updated_dependency_with_own_req_unlock'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:59:in `updated_dependencies'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:97:in `check_and_create_pull_request'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:106:in `run_ungrouped_dependency_updates'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:59:in `perform'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `run'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/07/19 00:43:32 ERROR <job_696945271> bin/update_files.rb:23:in `<main>'
```

### Native package manager behavior

`go get -u ./...` returns with no error and updates all outdated dependencies. Notice this diff though, it seems relevant:

```diff
-        github.com/kopia/htmluibuild v0.0.0-20230714030926-ff7ed652d883
+        github.com/kopia/htmluibuild v0.0.0
```

### Images of the diff or a link to the PR, issue, or logs

Failed dependabot update job/run: https://github.com/kopia/kopia/network/updates/696945271

### Smallest manifest that reproduces the issue

Probably something like, but I have not tried reproducing the issue this way.

```go
module github.com/kopia/kopia

go 1.20

require (
	github.com/kopia/htmluibuild v0.0.0
)
```

**Comment by jakecoffman** [comment]
Seems like the issue is that an empty string matches `v0.0.0`:

```
irb(main):010:0> Dependabot::GoModules::Version.new("v0.0.0") == ""
=> true
irb(main):011:0> Dependabot::GoModules::Version.new("v0.0.1") == ""
=> false
```

Another possible issue is it looks like github.com/kopia/htmluibuild doesn't have any [tags](https://github.com/kopia/htmluibuild/tags). Dependabot runs this command to list versions:

```console
$ go list -m -versions -json github.com/kopia/htmluibuild
{
        "Path": "github.com/kopia/htmluibuild",
        "Versions": [
                "v0.0.0-0c800bbb791f443ccc73839477ec47461dd153e5",
                "v0.0.0"
        ]
}
```

Looks like the GOPROXY sees some versions that aren't tagged in the repo:

```console
GOPROXY=direct go list -m -versions -json github.com/kopia/htmluibuild
{
        "Path": "github.com/kopia/htmluibuild",
        "Origin": {
                "VCS": "git",
                "URL": "https://github.com/kopia/htmluibuild",
                "TagSum": "t1:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
        }
}
```

Not sure if that matters for Dependabot purposes, but just a heads up.

**Comment by jakecoffman** [comment]
@deivid-rodriguez In your expert Ruby opinion, how would the best way to fix this be? It's not returning [here](https://github.com/dependabot/dependabot-core/blob/e19b4ab43cd87ce5f7ddc25a489a9f2b1c9e0907/common/lib/dependabot/dependency.rb#L270) since `Dependabot::GoModules::Version.new("v0.0.0") == ""`, but `v0.0.0` is technically a valid semver.

Would it be updating the version class to handle this or change `check_requirements_fields` to not compare to `""`?

**Comment by julio-lopez** [comment]
We worked around the issue by adding an ignore rule for that particular dependency in the `dependabot.yml` config.

Thanks for looking into it. I'm going to close the issue since we have a solution (work around) feel free to re-open it if you believe it needs to be addressed. Thanks again folks.
