### ISSUE TITLE
Increase Version-Strategy is ignored with Grouped Beta for NPM

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#7606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

 npm 9.8.0

### Language version

node 18.16.1

### Manifest location and content before the Dependabot update

https://github.com/broksonic21/repro-increase-dependabot-grouped/blob/main/package.json

### dependabot.yml content

https://github.com/broksonic21/repro-increase-dependabot-grouped/blob/main/.github/dependabot.yml

### Updated dependency

"@next/env": "^13.4.10"

should go to 

"@next/env": "^13.4.11",

### What you expected to see, versus what you actually saw

"@next/env": "^13.4.10" is in my package.json

It's also transitively loaded via other next dependencies. It is in fact updated in the package-lock.json, but not package.json.

Given we have "increase" version strategy turned on, I would have expected to get an update notification from Dependabot.

```
~/testrepo (main ✔) npm ls @next/env
next-test@1.0.0 /Users/me/testrepo
├── @next/env@13.4.11
├─┬ next-sitemap@4.1.8
│ └── @next/env@13.4.11 deduped
└─┬ next@13.4.11
  └── @next/env@13.4.11 deduped
```

Dependabot logs thing it's up to date:

```
updater | 2023/07/21 14:53:03 INFO <job_698761792> Checking if @next/env 13.4.11 needs updating
  proxy | 2023/07/21 14:53:03 [018] GET https://registry.npmjs.org:443/@next%2Fenv
  proxy | 2023/07/21 14:53:03 [018] 200 https://registry.npmjs.org:443/@next%2Fenv
  proxy | 2023/07/21 14:53:03 [020] GET https://registry.npmjs.org:443/@next%2Fenv/13.4.11
  proxy | 2023/07/21 14:53:03 [020] 200 https://registry.npmjs.org:443/@next%2Fenv/13.4.11
updater | 2023/07/21 14:53:03 INFO <job_698761792> Latest version is 13.4.11
updater | 2023/07/21 14:53:03 INFO <job_698761792> No update needed for @next/env 13.4.11
```

which, again - it is in the lock , but not in the package.json itself.

### Native package manager behavior

npm-check-updates shows an update to do:

```
~/testrepo (main ✔) npx npm-check-updates @next/env
Checking /Users/me/testrepo/package.json
[====================] 1/1 100%

 @next/env  ^13.4.10  →  ^13.4.11

Run npx npm-check-updates @next/env -u to upgrade package.json
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/broksonic21/repro-increase-dependabot-grouped/network/updates/698761792

### Smallest manifest that reproduces the issue

https://github.com/broksonic21/repro-increase-dependabot-grouped shows this

seems only to happen if:

* package is both a direct and transitive dependency
* up to date in the lock , but not in the package.json itself
* use increase strategy

**Comment by broksonic21** [comment]
Note: if the packages are all versioned as "13.4.10", it works fine.

issue is when they are "^13.4.10" - it doesn't bump all of them.

**Comment by jakecoffman** [comment]
I think this was fixed by https://github.com/dependabot/dependabot-core/pull/7561

I forked the repro and rolled back to the first commit, this PR looks correct to me https://github.com/jakecoffman/repro-increase-dependabot-grouped/pull/1

@broksonic21 do you agree?

**Comment by broksonic21** [comment]
That looks great - thanks!
