### ISSUE TITLE
Dependabot stopped sending version updates for several repos; appears unconfigured despite unchanged dependabot.yml file

### ISSUE THREAD

**Issue by netdpb** [dependabot/dependabot-core#7608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Manifest location and content before the Dependabot update

https://github.com/google/truth/blob/master/pom.xml for example.

### dependabot.yml content

https://github.com/google/truth/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Dependabot PRs have stopped being created on several of our repos starting around the end of June. Repos are within https://github.com/google, including https://github.com/google/truth, https://github.com/google/auto, https://github.com/google/compile-testing for example.

Our `dependabot.yml` files have not changed at all.  The GitHub settings page looks as if Dependabot hasn't been set up ("Dependabot version updates aren't configured yet") but clicking the link to create the config file simply takes me to the existing, unchanged, config file.

I tried using the CLI to test, and I noticed that it tries to `GET https://api.github.com:443/repos/google/truth/contents/pom.xml?ref=` and receives a 404 response. That is true for that URL in the browser as well, but if I change it to https://api.github.com:443/repos/google/truth/contents/pom.xml?ref=master or https://api.github.com:443/repos/google/truth/contents/pom.xml it works. Maybe Dependabot used to omit the `ref=` parameter if it was empty?

**Comment by jakecoffman** [comment]
We're still looking to why, but on June 22 Dependabot was briefly disabled and then re-enabled on the entire `google` account. This deactivated all of the repos and they didn't get re-enabled properly.

I ran a process to resync all the repos again, looks like they're good now so you should start getting PRs again.

**Comment by netdpb** [comment]
Thanks!

**Comment by jakecoffman** [comment]
@Chartman123 Yes, looks like a similar thing has happened. I've resynced the Nextcloud reops.

**Comment by cpovirk** [comment]
We indeed got PRs on Google repos again... but it appears only for a few days. After https://github.com/google/truth/pull/1152 or so, we've seen nothing, even though I again see some dependencies in that project that had releases early next week and that have had Dependabot PRs created for usages in non-`google` repos.

Might we need another resync?

**Comment by jakecoffman** [comment]
Yes looks like some repos were disabled again. We have a fix in place now, but I guess it disabled again before we could get the fix in. I resynced all the repos, let me know if it happens again, but it should be good now.
