### ISSUE TITLE
Ignore doesn't ignore

### ISSUE THREAD

**Issue by elgohr** [dependabot/dependabot-core#7651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "xyz/*"

### What you expected to see, versus what you actually saw

At the moment the dependencies are still checked and appear in the logs as
```
updater | 2023/07/19 09:16:17 INFO <job_697229887> Checking if xyz latest needs updating
updater | 2023/07/19 09:16:17 INFO <job_697229887> Ignored versions:
updater | 2023/07/19 09:16:17 INFO <job_697229887>   >= 0 - from .github/dependabot.yml
updater | 2023/07/19 09:16:17 INFO <job_697229887> Latest version is latest
 proxy | 2023/07/19 09:16:17 [020] HEAD xyz
```
As the check might fail intentionally (let's say because of a dependency in a private repository), the dependency would still fail the dependabot task (and count for the 30 trials until dependabot refuses to work).

I would expect them to be ignored without a check and error.

**Comment by jakecoffman** [comment]
This should be working as expected now.

**Comment by elgohr** [comment]
@jakecoffman should it also respect wildcards (like shown above)?
If yes, it doesn't work...
