### ISSUE TITLE
Dependabot groups with a single package update don't show current -> updated version

### ISSUE THREAD

**Issue by 23pointsNorth** [dependabot/dependabot-core#7662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

When only a single package is updated within a dependabot group, the PR text doesn't show the version update (from/to).

E.g. 
A new PR:
Subject: Bump the types-dependencies group in /client with 1 update
Body: Bumps the types-dependencies group in /client with 1 update: [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node).

Commits <expand button>

Expected behavior:
Similar to multi-package group updates, or single non-group version bumps, post the version change in the body or subject.
E.g. 
Subject: Bump jasmine-core from 5.0.1 to 5.1.0 in /client
Body: Bumps [jasmine-core](https://github.com/jasmine/jasmine) from 5.0.1 to 5.1.0.

Release notes <expand button>

**Comment by jakecoffman** [comment]
Another report of this here with repro: https://github.com/dependabot/dependabot-core/issues/7840#issuecomment-1686232556

**Comment by ghjm** [comment]
Came here to report this.  My suggestion is to add a `minimum_updates` field to the `groups` definition.  Personally, I'd set this to about 4.  If there are only one, two or (maybe) three updates, I'd like to see individual ungrouped PRs.

I guess this gets complicated if you have 2 updates still pending and 2 more updates come in.  At that point do you close the original ungrouped PRs and add them to a new group?  I'm not sure what the correct behavior is in all cases.

My goal is to have the PRs show the individual versions most of the time, but use groups to reduce the pain when something broke the unit tests, didn't get looked at for a while, and now there's a logjam of dozens of updates that need to go through.

**Comment by joaorosado** [comment]
Was changing my repos to also use this new group feature and hit exactly the same issue.
On PRs where only one of the dependencies needs to be updated there is no information anywhere about what is being changed.

Ideally I would like the title to actually be as it was before using the groups, but at the very least it should keep the same format / table with the from / to version numbers in the description of the PR **and on the commit message details**.

**Comment by huehnerlady** [comment]
@jakecoffman [my issue](https://github.com/dependabot/dependabot-core/issues/7840) was marked as a duplicate, but unfortunately this is still not working.

My issue was about the "old" title of a group update as long as it is just 1 dependency update...

**Comment by jakecoffman** [comment]
@huehnerlady Ah, let me reopen that as a feature request then and we can have a discussion there.
