### ISSUE TITLE
Add limit for BitBucket PR description length

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#7678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We recently landed a PR that makes it easy to configure the length of the PR description:
* https://github.com/dependabot/dependabot-core/pull/7487

However, that still needs to be updated with a limit for BitBucket:
https://github.com/dwc0011/dependabot-core/blob/ef7e8728ae9a7013815ced67402c96e8a75c88d0/common/lib/dependabot/pull_request_creator.rb#L225-L233

Creating this issue in case anyone in the open source community wants to take a stab at it.

**Comment by jeffwidman** [comment]
@stefangr any interest in tackling this?

Keep in mind the limit that Google/BitBucket docs show may be incorrect per this comment:
* https://github.com/dependabot/dependabot-core/pull/7487#issuecomment-1648010762

**Comment by stefangr** [comment]
Sure.

I can try to find the limit.

**Comment by stefangr** [comment]
@jeffwidman 
I went up to a PR description with 1,310,720 characters, which was accepted by bitbucket (cloud) without any problem.

The UX on the PR page is bad with such a large PR description, so I suggest to limit it to something like 262,144 (4 x 65,536)

**Comment by jeffwidman** [comment]
Want to submit that as a PR?

Truncating shorter than the "real" limit makes sense to me... perhaps include a clarifying code comment?
```
# BitBucket Cloud accepts > 1MB characters, but they display poorly in the UI, so limiting to 4x 65,536
...
```
