### ISSUE TITLE
Bump `pip-tools` to latest major (7.*)

### ISSUE THREAD

**Issue by gmcrocetti** [dependabot/dependabot-core#7685]
### Code improvement description

A new major version of `pip-tools` has been released and introduced backwards incompatible changes. The changelog of the release is available [here](https://github.com/jazzband/pip-tools/releases/tag/7.0.0).

I can work on it but before that hearing from the maintainers is a must as there are  important implications with this bump.

**Comment by jeffwidman** [comment]
We def want it, but it's blocked by these first:
* #7610 
* #7677 

I'm actually working on those this week, although the deprecation notice won't go out on the blog until later this month, so can't merge until then.

Once I've got the `3.7`-drop PR in mergable shape, be great if you want to take a crack at a PR updating `pip-tools` that's based off the `3.7`-drop PR branch.

**Comment by gmcrocetti** [comment]
> I'm actually working on those this week, although the deprecation notice won't go out on the blog until later this month, so can't merge until then.

Oh, alright. It definitely requires wide communication o/.

>Once I've got the 3.7-drop PR in mergable shape, be great if you want to take a crack at a PR updating pip-tools that's based off the 3.7-drop PR branch.

Sure thing. Just let me know :muscle:

**Comment by sir-sigurd** [comment]
isn't this done in https://github.com/dependabot/dependabot-core/pull/7711?

**Comment by jeffwidman** [comment]
Yes it was, thank you @sir-sigurd for pointing that out!
