### ISSUE TITLE
npm grouping never creates a PR, but creates a branch with commit

### ISSUE THREAD

**Issue by KyleSanderson** [dependabot/dependabot-core#7743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm

### Language version

18

### Manifest location and content before the Dependabot update

https://github.com/autobrr/autobrr/commit/e0459d5a297f8aaad5f9f33557fe4006f3cddcb9

### dependabot.yml content

https://github.com/autobrr/autobrr/pull/1028

### What you expected to see, versus what you actually saw

Records there's 35 updates - where's the PR?

### Native package manager behavior

Reasonable, working behaviour.

**Comment by jakecoffman** [comment]
Thanks for reporting this. A recent PR changed truncation behavior, so large PR bodies were not getting truncated. I made a change in the Dependabot service that added truncation back and I was able to get a PR from a fork: https://github.com/jakecoffman/autobrr/pull/4

**Comment by KyleSanderson** [comment]
Thank you very much
