### ISSUE TITLE
dependabot closed grouped PR incorrectly on "@dependabot recreate"

### ISSUE THREAD

**Issue by snesm** [dependabot/dependabot-core#7765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 9.5.0, yarn 3.6.1

### Language version

Node.js v18.15.0

### Manifest location and content before the Dependabot update

https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/package.json
https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/yarn.lock

### dependabot.yml content

https://github.com/CDCgov/prime-reportstream/blob/master/.github/dependabot.yml

### Updated dependency

[Updates @typescript-eslint/eslint-plugin from 6.2.1 to 6.3.0
Updates @typescript-eslint/parser from 6.2.1 to 6.3.0](https://github.com/CDCgov/prime-reportstream/pull/10809)

### What you expected to see, versus what you actually saw

I expected the [PR](https://github.com/CDCgov/prime-reportstream/pull/10809) to stay open and be re-created against the latest yarn.lock

Instead the [PR](https://github.com/CDCgov/prime-reportstream/pull/10809) was closed claiming it was "_up-to-date now_"

### Native package manager behavior

```
$ yarn outdated --check @typescript-eslint/eslint-plugin @typescript-eslint/parser
➤ YN0000: ┌ Checking for outdated dependencies
➤ YN0000: └ Completed in 2s 753ms

➤ YN0000: Package                            Current   Latest   Package Type   
➤ YN0000: @typescript-eslint/eslint-plugin   6.2.1     6.3.0    devDependencies
➤ YN0000: @typescript-eslint/parser          6.2.1     6.3.0    devDependencies

➤ YN0000: 2 dependencies are out of date
➤ YN0000: Failed with errors in 2s 758ms
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/CDCgov/prime-reportstream/pull/10809

**Comment by jakecoffman** [comment]
This should be fixed by https://github.com/dependabot/dependabot-core/pull/9371. 

It looks like the job errored updating each dependency and so it incorrectly assumed the PR was up-to-date. Going forward it should have a more accurate message that the dependencies were not updatable.

If it's a transient issue then the next time Dependabot runs it will create a new PR.
