### ISSUE TITLE
Dependabot was not able to determine that CI was successful.

### ISSUE THREAD

**Issue by KyleSanderson** [dependabot/dependabot-core#7805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

all

### dependabot.yml content

https://github.com/KyleSanderson/upgraderr/pull/1

### What you expected to see, versus what you actually saw

Dependabot seems to post some unhelpful information after a command is taken.

The quote is `@dependabot squash and merge will squash and merge this PR after your CI passes on it`
If you use the command, before CI completes, it posts the below message(?).

> Dependabot was not able to determine that CI was successful.
> 
> Please try again once CI has succeeded.

This feels very silly, and should instead post if the command action fails, which is scheduled properly on action completion and behaves as expected.

**Comment by LeoMcA** [comment]
I don't believe we've made any change in our repo, and we're suddenly seeing [dependabot PRs *filled* with these "Dependabot was not able to determine that CI was successful." messages](https://github.com/mdn/yari/pulls?q=is%3Apr+%22Dependabot+was+not+able+to+determine+that+CI+was+successful.%22), in [this case](https://github.com/mdn/yari/pull/9491) commenting 8 times before merging the PR.

**Comment by JasonGross** [comment]
This did not used to be the case, but when [dependabot comments 16+ times on every PR before merging](https://github.com/mit-plv/fiat-crypto/pull/1624#issuecomment-1681613694), it severely clutters PR discussions.

**Comment by landongrindheim** [comment]
👋 We've just shipped a fix for this issue so that should prevent Dependabot from commenting when a merge has been requested. Thanks for reporting! 😄

**Comment by tamird** [comment]
Would you mind referencing the fix?

**Comment by landongrindheim** [comment]
@tamird The fix was made to the Dependabot service, which is hosted in an internal, private, repo.

The summary of the fix is that Dependabot will retry a merge request when CI status requirements have not been met and the commenting behavior was not accounting for this.

**Comment by KyleSanderson** [comment]
Nice - thank you
