### ISSUE TITLE
Changelog sourced from wrong branch

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#786]
I released activeadmin 1.4.0 and I noticed that dependabot sourced master's unreleased changelog section instead of the 1.4.0 changelog from the 1-4-stable master branch. See https://gitlab.com/deivid-rodriguez/nipanipa/merge_requests/515 for an example.

Now I've merged the 1.4.0 changelog [back into master](https://github.com/activeadmin/activeadmin/pull/5576), so I assume PRs from now on will display the right changelog. A simple solution for the future would be to cut the upcoming release in master's changelog before the upcoming release, but I wonder if dependabot can do better here.

Thanks!

**Comment by greysteil** [comment]
Thanks for the heads up @deivid-rodriguez. I reckon we can do better here - let me have a go at improving our changelog detection to pull in from a branch / tag if it can't find details on master.

**Comment by deivid-rodriguez** [comment]
Thank you @greysteil!

**Comment by greysteil** [comment]
Done! Turned out to be quite a lot of work, but there are a few other improvements in there too. https://github.com/dependabot/dependabot-core/compare/v0.75.94...v0.75.95.

Thanks for the prod on this one.

**Comment by deivid-rodriguez** [comment]
This is great @greysteil, thanks!
