### ISSUE TITLE
Multiple PRs are opened for the same group

### ISSUE THREAD

**Issue by xxchan** [dependabot/dependabot-core#7900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### What you expected to see, versus what you actually saw

https://github.com/risingwavelabs/risingwave/pull/11883
https://github.com/risingwavelabs/risingwave/pull/11679
https://github.com/risingwavelabs/risingwave/pull/11858

<img width="825" alt="image" src="https://github.com/dependabot/dependabot-core/assets/37948597/0fc6a5b0-3802-42f8-a3d9-c577e968270b">

**Comment by coderroggie** [comment]
I'm now seeing grouped dependency PR's reference and close previously opened grouped dependency PR's appropriately.  Seems to be working now in our Repo.

**Comment by jurre** [comment]
^ is the intended behavior. I see that grouping was turned off on the risingwave repo, I'm going to keep this issue open for a bit to check if others are running into this as well and see if we can find a way to reproduce it

**Comment by jakecoffman** [comment]
Seems to be working correctly now, I don't see any duplicates: https://github.com/risingwavelabs/risingwave/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

We've made a lot of changes since August to prevent duplications so I am confident this is fixed.
