### ISSUE TITLE
dependabot losing markers in requirements.txt files

### ISSUE THREAD

**Issue by glensc** [dependabot/dependabot-core#7909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, pipenv

### What you expected to see, versus what you actually saw

dependabot started losing markers in generated requirements.txt:
- https://github.com/Taxel/PlexTraktSync/pull/1558 (restored manually https://github.com/Taxel/PlexTraktSync/commit/2ddc216b8e018f130851e9779cbb61a931c269a4)
- https://github.com/Taxel/PlexTraktSync/pull/1553 (restored manually https://github.com/Taxel/PlexTraktSync/commit/846d2e0131616da377fd05d280722272a4cb64db)

```diff
...
-idna==3.4; python_version >= '3.5'
-importlib-metadata==6.8.0; python_version >= '3.8'
+idna==3.4
+importlib-metadata==6.8.0
```

**Comment by glensc** [comment]
Another examples:
- [Taxel/PlexTraktSync@`4b799d0` (#1563)](https://github.com/Taxel/PlexTraktSync/pull/1563/commits/4b799d076b44b91cfa0c2904c65d7258fb6e54a8)
- [Taxel/PlexTraktSync@`7a89229` (#1564)](https://github.com/Taxel/PlexTraktSync/pull/1564/commits/7a892299a19b0bec4e3ec92d85c1108bd3832a5e)

**Comment by glensc** [comment]
anyone even recognizing this as a bug?

**Comment by deivid-rodriguez** [comment]
We just updated the pipenv version used by Dependabot. Can you verify whether the problem is fixed, or still present?

**Comment by glensc** [comment]
it's not removing them anymore it seems, but sort order seems different:
- [Taxel/PlexTraktSync@`ed42141` (#1600)](https://github.com/Taxel/PlexTraktSync/pull/1600/commits/ed4214178409a9c80146bcea33e135864a0f8244)

and why it's removing now `"index": "pypi"` from `Pipfile.lock`?

**Comment by glensc** [comment]
I guess the original problem is resolved.
