### ISSUE TITLE
Grouped updates GA but relying on experimental feature tags?

### ISSUE THREAD

**Issue by lorengordon** [dependabot/dependabot-core#7917]
Hello, we started looking into how we might run the grouped updates feature via a dependabot-script, and noticed in the core code that the feature is gated by an "experimental" feature flag. However, it was claimed that the grouped updates feature is GA. Can someone please clarify whether it is GA or experimental?

Relevant code search: https://github.com/search?q=repo%3Adependabot%2Fdependabot-core%20Dependabot%3A%3AExperiments.enabled%3F(%3Agrouped_updates_prototype)&type=code

> Good news! Grouped updates for Dependabot version updates is officially generally available 🥳 
> 
> Read our blog post here: https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
See the docs here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
>
>With that, we will close this issue. Thanks everyone for your feedback!
>
>_Originally posted by @carogalvin in https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1693360104_

**Comment by jakecoffman** [comment]
The feature is released, the Dependabot service always sets the experiment to enabled and we won't disable it again. 

We're open to removing those experiment flags from core. We will get around to that soon, or if someone wants to put up a PR to remove it that is welcome.

**Comment by lorengordon** [comment]
@jakecoffman Thanks for that. I don't suppose you might have any insight or pointers you can share on how to utilize the grouped updates feature via dependabot-script?

**Comment by jakecoffman** [comment]
feature flags removed in https://github.com/dependabot/dependabot-core/pull/8123

Unfortunately I don't have any advice for getting it to work in dependabot-script.
