### ISSUE TITLE
Dependabot group update doesn't work on dockerfile

### ISSUE THREAD

**Issue by ying-jeanne** [dependabot/dependabot-core#7938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

The related log is https://github.com/ying-jeanne/mimir/network/updates/716250888

### dependabot.yml content

here https://github.com/ying-jeanne/mimir/blob/test_group_update/.github/dependabot.yml

### Updated dependency

any dependency in dockerfile, including the ones in the log
updater | +-------------------------------------+
updater | |    Dependencies failed to update    |
updater | +---------------------+---------------+
updater | | kustomize/kustomize | unknown_error |
updater | | alpine/helm         | unknown_error |
updater | | golang              | unknown_error |

### What you expected to see, versus what you actually saw

dependency update for dockerfile works and one PR raised per dockerfile.

### Native package manager behavior

this is not applied

### Images of the diff or a link to the PR, issue, or logs

The related log is https://github.com/ying-jeanne/mimir/network/updates/716250888

### Smallest manifest that reproduces the issue

you should be able to reproduce it with the same dependabot.yml by fork grafana/mimir repo

**Comment by Nishnha** [comment]
Adding some context from the logs

```
updater | ERROR undefined method `segments' for "1.21.0-bullseye":String
updater | 
updater |           major: version.segments[0] || 0,
updater |                         ^^^^^^^^^
updater | ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:233:in `semver_segments'
updater | ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:221:in `semver_rules_allow_grouping?'
```

This same error actually shows up in the logs twice:

```
updater | ERROR undefined method `segments' for "3.12.3":String
```

**Comment by Nishnha** [comment]
These dependencies should now be able to update correctly https://github.com/dependabot/dependabot-core/pull/7984

![Screenshot 2023-09-08 at 12 46 08 PM](https://github.com/dependabot/dependabot-core/assets/12107187/0d5ece45-94e5-4c95-bb8a-dc9119fd7c72)
