### ISSUE TITLE
Grouped updates for (too many) poetry dependencies times out

### ISSUE THREAD

**Issue by domsj** [dependabot/dependabot-core#7967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Language version

python

### Manifest location and content before the Dependabot update

not sure if I can really provide this file, but suffice to know that there are 274 dependencies in total

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    registries:
      - gemfury
    allow:
      - dependency-type: all
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "plotly"
registries:
  gemfury:
    type: python-index
    url: https://pypi.fury.io/XXX/
    token: ${{secrets.GEMFURY_DEPLOY_TOKEN}}
```
(simplified; just showing that grouped updates are configured)

### What you expected to see, versus what you actually saw

I expect to see dependabot open a new PR for a group (set) of updated dependencies.
Instead it times out.

```
  proxy | 2023/09/05 07:13:40 proxy starting, commit: 93c4a893d794d736d84e940a79420e8d1180c0bd
  proxy | 2023/09/05 07:13:40 Listening (:1080)
updater | 2023-09-05T07:13:41.251184460 [718073042:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-09-05T07:13:45Z" level=info msg="guest starting" commit=b073e069d366dc2f68bb8ef0134feb3c29cacadd
updater | time="2023-09-05T07:13:45Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=718073042 updater_timeout=45m0s updater_version=bdf8bde0f98374d0af14e957de005d2bf71e4912-pip
updater | 2023/09/05 07:13:49 INFO Raven 3.1.2 ready to catch errors
updater | 2023/09/05 07:13:52 INFO <job_718073042> Starting job processing

...

updater | 2023/09/05 07:13:58 INFO <job_718073042> Finished job processing
updater | time="2023-09-05T07:13:58Z" level=info msg="task complete" container_id=job-718073042-file-fetcher exit_code=0 job_id=718073042 step=fetcher
updater | 2023/09/05 07:14:00 INFO Raven 3.1.2 ready to catch errors
updater | 2023/09/05 07:14:02 INFO <job_718073042> Starting job processing
updater | 2023/09/05 07:14:22 INFO <job_718073042> Starting grouped update job for foodpairing/engineering-cfi
updater | 2023/09/05 07:14:22 INFO <job_718073042> Found 2 group(s).
updater | 2023/09/05 07:14:22 INFO <job_718073042> Starting update group for 'dev-dependencies'
updater | 2023/09/05 07:14:35 INFO <job_718073042> Checking if pytest 7.4.1 needs updating
  proxy | 2023/09/05 07:14:36 [050] GET https://pypi.org:443/simple/pytest/
  proxy | 2023/09/05 07:14:36 [050] 200 https://pypi.org:443/simple/pytest/
  proxy | 2023/09/05 07:14:37 [052] GET https://pypi.fury.io:443/foodpairing/pytest/
  proxy | 2023/09/05 07:14:37 [052] * authenticating python index request (host: pypi.fury.io)
  proxy | 2023/09/05 07:14:37 [052] 404 https://pypi.fury.io:443/foodpairing/pytest/
updater | 2023/09/05 07:14:37 INFO <job_718073042> Latest version is 7.4.1
updater | 2023/09/05 07:14:37 INFO <job_718073042> No update needed for pytest 7.4.1
updater | 2023/09/05 07:14:50 INFO <job_718073042> Checking if coverage 7.3.0 needs updating
  proxy | 2023/09/05 07:14:50 [054] GET https://pypi.org:443/simple/coverage/
  proxy | 2023/09/05 07:14:50 [054] 200 https://pypi.org:443/simple/coverage/
  proxy | 2023/09/05 07:14:53 [056] GET https://pypi.fury.io:443/foodpairing/coverage/
  proxy | 2023/09/05 07:14:53 [056] * authenticating python index request (host: pypi.fury.io)
  proxy | 2023/09/05 07:14:53 [056] 404 https://pypi.fury.io:443/foodpairing/coverage/
updater | 2023/09/05 07:14:53 INFO <job_718073042> Latest version is 7.3.0
updater | 2023/09/05 07:14:53 INFO <job_718073042> No update needed for coverage 7.3.0
updater | 2023/09/05 07:15:08 INFO <job_718073042> Checking if pytest-mock 3.11.1 needs updating

....

updater | 2023/09/05 07:58:09 INFO <job_718073042> Checking if dbt-extractor 0.4.1 needs updating
  proxy | 2023/09/05 07:58:10 [134] GET https://pypi.org:443/simple/dbt-extractor/
  proxy | 2023/09/05 07:58:10 [134] 200 https://pypi.org:443/simple/dbt-extractor/
  proxy | 2023/09/05 07:58:12 [136] GET https://pypi.fury.io:443/foodpairing/dbt-extractor/
  proxy | 2023/09/05 07:58:12 [136] * authenticating python index request (host: pypi.fury.io)
  proxy | 2023/09/05 07:58:12 [136] 404 https://pypi.fury.io:443/foodpairing/dbt-extractor/
updater | 2023/09/05 07:58:12 INFO <job_718073042> Latest version is 0.5.0
  proxy | 2023/09/05 07:58:51 [138] GET https://pypi.org:443/simple/dbt-extractor/
  proxy | 2023/09/05 07:58:51 [138] 200 https://pypi.org:443/simple/dbt-extractor/
  proxy | 2023/09/05 07:58:51 [140] GET https://pypi.org:443/pypi/dbt-extractor/0.5.0/json
  proxy | 2023/09/05 07:58:51 [140] 200 https://pypi.org:443/pypi/dbt-extractor/0.5.0/json
  proxy | 2023/09/05 07:58:51 [142] GET https://files.pythonhosted.org:443/packages/90/3c/3572e10db3fc6aa5505752c685214526000b23b8f7fc98b4a44ea2a781a8/dbt_extractor-0.5.0-cp38-abi3-macosx_10_7_x86_64.whl
  proxy | 2023/09/05 07:58:51 [142] 200 https://files.pythonhosted.org:443/packages/90/3c/3572e10db3fc6aa5505752c685214526000b23b8f7fc98b4a44ea2a781a8/dbt_extractor-0.5.0-cp38-abi3-macosx_10_7_x86_64.whl
updater | time="2023-09-05T07:58:58Z" level=info msg="task complete" container_id=job-718073042-updater exit_code=137 job_id=718073042 step=updater
updater | time="2023-09-05T07:58:59Z" level=warning msg="timeout running job" error="waiting for updater: waiting for container: context deadline exceeded" job_id=718073042
```

So for each dependency it takes about 15 to 20 seconds to process it.
Multiplied by 274 dependencies amounts to e.g. 75-90 minutes.
While the dependabot job seems to be configured with a timeout of 45 minutes.

Maybe it's possible to get the time to check for updates per dependency down?

**Comment by domsj** [comment]
Seems like today things did work a bit faster, the job finished (with another error 😅) after 38 minutes.
What previously took 15-20 seconds now only took 5-7 seconds.
Given the output I see I can't say why that is ... maybe pypi is faster than a couple of days ago?

**Comment by abdulapopoola** [comment]
@domsj what was the new error this time? Could you share please?

**Comment by domsj** [comment]
@abdulapopoola apologies but I don't recall. did not capture it and can access those logs anymore.
still stuck with this problem if all dependencies are in a single group, could work around it by splitting up into e.g. a dev and prod dependencies group.

**Comment by domsj** [comment]
just a thought: maybe it makes sense for github to host an internal mirror of pypi?
this would probably speed up dependabot updates a lot and to a large degree eliminate the problem here.

**Comment by domsj** [comment]
Just as an fyi, for now I've started using https://github.com/MousaZeidBaker/poetry-plugin-up for this repository (as manual periodic task).
Their approach appears to be a lot faster, so there might be something to learn there.

**Comment by abdulapopoola** [comment]
Would you be willing to have your repository moved to the Actions beta as a fix for the timeouts?

cc: @honeyankit and @carogalvin as fyi

**Comment by domsj-foodpairing** [comment]
> Would you be willing to have your repository moved to the Actions beta as a fix for the timeouts?

@abdulapopoola how does (github) actions beta help here? is the idea to run dependabot ourselves using a github action (with a larger timeout) configured as part of this repository?

**Comment by abdulapopoola** [comment]
Tagging @honeyankit to help with this.

**Comment by honeyankit** [comment]
@domsj-foodpairing : Could you share the repo name? Also make sure Action is enabled for that repo. 

Note: The Dependabot jobs running on Actions are not billed (they are free).

**Comment by domsj-foodpairing** [comment]
@honeyankit the repo name is foodpairing/engineering-cfi

iiuc actions are enabled:
![image](https://github.com/dependabot/dependabot-core/assets/157424857/744241b0-9f95-4dc0-a849-5d2da681c97e)

note that no (self hosted) runners are configured

**Comment by domsj-foodpairing** [comment]
Thanks @honeyankit. the Action works great, we're back to receiving dependabot grouped updates PRs.

(There is an error occuring for 1 specific dependency, but I'll log an issue for that later - if it's not yet a known problem)

**Comment by honeyankit** [comment]
@domsj : Thanks for the update, I am going to close this issue.

**Comment by paulclarkaranz** [comment]
Is there a ticket to track the new action being released from beta? I was subscribed to this issue in the hopes that it would resolve our dependabot grouped update runs from timing out, now I'm not sure where to go for updates.

**Comment by abdulapopoola** [comment]
Tagging @carogalvin for @paulclarkaranz 's question.

**Comment by carogalvin** [comment]
@paulclarkaranz you can follow the GitHub roadmap issue for this here: https://github.com/github/roadmap/issues/913

**Comment by domsj-foodpairing** [comment]
dependabot worked for a while on actions, but now it's also timing out there after 55 minutes, and afaict there is currently no way to increase this timeout
