### ISSUE TITLE
Grouped Updates list inaccurate, containing packages that weren't upgraded (twice!)

### ISSUE THREAD

**Issue by bmulholland** [dependabot/dependabot-core#7970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### What you expected to see, versus what you actually saw

The weekly package upgrade created by Dependabot Grouped Updates always has incorrect, duplicate entries.

The table of updates includes six packages that weren't updated. Those packages are listed twice, and the "From" is listed as a commit instead of a version number. That's probably all related. That makes this a superset of https://github.com/dependabot/dependabot-core/issues/7695

It has always been like this with grouped updates, even from the closed beta.

For example:

rspec-sidekiq does not appear in "Files changed", not even in the diff's context.

Package | From | To
-- | -- | --
more packages here | ... | ...
[rspec-sidekiq](https://github.com/recitalsoftware/rspec-sidekiq) | 93e9b1d | 3.1.1
more packages here | ... | ...
[rspec-sidekiq](https://github.com/recitalsoftware/rspec-sidekiq) | 93e9b1d | 3.1.1
more packages here | ... | ...

Also, below, listed twice:

Updates rspec-sidekiq from 93e9b1d to 3.1.1
\> Commits

Updates rspec-sidekiq from 93e9b1d to 3.1.1
\> Commits

### Images of the diff or a link to the PR, issue, or logs

https://github.com/recitalsoftware/recital-backend/pull/2186

**Comment by bmulholland** [comment]
Hi :). Hope you're well.

How recently were those duplication issues fixed? We only turned out Dependabot a couple weeks ago, and were still seeing these issues at that time. Also note that this issue isn't just duplication: the package versions are also reported incorrectly (as commit hashes).

**Comment by Nishnha** [comment]
Hi @bmulholland it was merged on Oct 2nd. This is the PR we're referencing: https://github.com/dependabot/dependabot-core/pull/8106

Another user pointed out [similar sounding-issues](https://github.com/dependabot/dependabot-core/issues/8149) and was able to get non-broken PRs by 
- first running `@dependabot recreate` on the dependabot PRs with the duplication issues to close them out
- then triggering a new version update which opened PRs with the correct dependency updates

**Comment by bmulholland** [comment]
Thanks @Nishnha! We're trying this out and will report back

**Comment by deivid-rodriguez** [comment]
@bmulholland That sounds like #8195? If that's the case, I think we can close this issue and move the discussion about that there?

**Comment by bmulholland** [comment]
Yep, looks like it. Thank you all! Closing out.
