### ISSUE TITLE
Grouped updates using `update-types` result in error "undefined method `segments'"

### ISSUE THREAD

**Issue by lorengordon** [dependabot/dependabot-core#7978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker, github-actions

### dependabot.yml content

https://github.com/plus3it/spel-repo-builder/commit/90c40175bb3e4d316074d64681115ae356d339e7

### What you expected to see, versus what you actually saw

Expected Dependabot to create a grouped update for only patch and minor versions. Instead, it generated an error:

```
updater | 2023/09/05 15:29:04 ERROR <job_718292262> undefined method `segments' for "0.24.11":String
updater | 
updater |           major: version.segments[0] || 0,
updater |                         ^^^^^^^^^
updater | 2023/09/05 15:29:04 ERROR <job_718292262> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:233:in `semver_segments'
updater | 2023/09/05 15:29:04 ERROR <job_718292262> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:221:in `semver_rules_allow_grouping?'
```

### Smallest manifest that reproduces the issue

See other references claiming the same problem:

* https://github.com/dependabot/dependabot-core/issues/7795#issuecomment-1682224134
* https://github.com/dependabot/dependabot-core/issues/7795#issuecomment-1705112805
* https://github.com/dependabot/dependabot-core/issues/7795#issuecomment-1706944982

**Comment by jurre** [comment]
This seems very similar to https://github.com/dependabot/dependabot-core/issues/7961, very likely to be the same root cause, but I'll keep both open since in that case it's `nil`, and here it's a string

**Comment by jakecoffman** [comment]
I think I fixed the issue if you want to try again and let us know how it goes?
