### ISSUE TITLE
Pipenv updates pinned packages in Pipfile.lock when there is an editable git dependency with unpinned sub-deps

### ISSUE THREAD

**Issue by weiji14** [dependabot/dependabot-core#805]
Hi there,

First off, great work on dependabot, it's really awesome being able to keep my packages up to date easily, and have the changelogs documented in Pull Requests :smile:

Anyways, I'm just reporting a strange issue with how dependabot handles the update of 'dev-packages' for Python pipenv packages. This commit https://github.com/weiji14/deepbedmap/commit/59c7e58121b7d83090572a5997e053ac55b5dbb3 which bumps `pytest` from 3.10.0 to 4.0.1 also updates some of my other non-dev 'packages' in the Pipenv.lock file. It's currently trying to update `numpy` from 1.14.5 to 1.15.4 and `netcdf4` from 1.4.1 to 1.4.2 even though those two packages are **pinned** in the [Pipfile](https://github.com/weiji14/deepbedmap/blob/59c7e58121b7d83090572a5997e053ac55b5dbb3/Pipfile)!

Normally I'm all good with having the latest and greatest, but this seems to be unexpected behaviour that might affect others. Expected behaviour should be that the pull request respects the pinned non-dev packages in the Pipfile.

I.e. a Pipfile.lock like [this](https://github.com/weiji14/deepbedmap/pull/57/commits/3ee2c6bfcc2cd10153921aaeff16d62d80feac6a#diff-46bb8405eeb4d8a11deb635f562f7c48) instead of [this](https://github.com/weiji14/deepbedmap/commit/59c7e58121b7d83090572a5997e053ac55b5dbb3). This [diff between the two](https://github.com/weiji14/deepbedmap/compare/59c7e58121b7d83090572a5997e053ac55b5dbb3..3ee2c6bfcc2cd10153921aaeff16d62d80feac6a) should show how the `numpy` and `netcdf4` package versions are preserved.

Happy to provide further information if needed :grin:

**Update**: Upstream issue with pipenv, see comments below.

**Comment by greysteil** [comment]
Thanks for reporting - that's definitely a bug! I'll take a look now.

**Comment by weiji14** [comment]
Cool, I'm gonna manually update those packages for now :)

**Comment by greysteil** [comment]
👍 , or if you give me 10 minutes I can probably get it fixed and rebase them from my side.

**Comment by weiji14** [comment]
No rush, it's close to midnight on my end and I just wanted to kick off some CI builds before bed :smiley:

**Comment by greysteil** [comment]
Perhaps for the best. I'd assumed this was a bug in the way Dependabot was preparing Pipfiles for updates, but it looks more likely it's a Pipenv issue. I'll get to the bottom of it and get it fixed either way.

**Comment by greysteil** [comment]
Yeah, this is a Pipenv bug. I'll give the team a heads up and put together a replication case. I think it's struggling with resolution for dependencies that are sub-deps of the git dependency you have in your Pipfile (as well as top-level dependencies).

**Comment by greysteil** [comment]
FYI, I've replicated and created [this issue](https://github.com/pypa/pipenv/issues/3296). Hopefully we can get it fixed quickly. Thanks for making Dependabot and Pipenv better!

**Comment by weiji14** [comment]
> Yeah, this is a Pipenv bug. I'll give the team a heads up and put together a replication case. I think it's struggling with resolution for dependencies that are sub-deps of the git dependency you have in your Pipfile (as well as top-level dependencies).

Ah yes, I think I saw a pipenv issue related to that a little while back, but can't seem to find it anymore. Just noticed it's not restricted to dev-packages, this new `Cython` bump commit https://github.com/weiji14/deepbedmap/pull/60/commits/4cace4f6bfea08d37714c12c7859b718dde4fb74 is also bumping up `numpy` and `netcdf4`. So you're right that it is to do with the git dependency not having pinned sub-dependencies

> FYI, I've replicated and created [this issue](https://github.com/pypa/pipenv/issues/3296). Hopefully we can get it fixed quickly. Thanks for making Dependabot and Pipenv better!

I'll close this since it's an upstream issue. Will take extra care with my python packages in the meantime. Thanks for the the quick feedback!

**Comment by weiji14** [comment]
Just noting that https://github.com/pypa/pipenv/issues/3296 has been closed with https://github.com/pypa/pipenv/pull/3297 and [pipenv v2018.11.26](https://github.com/pypa/pipenv/releases/tag/v2018.11.26) has been released.

**Comment by greysteil** [comment]
Yes! Should be working just fine now. https://github.com/pypa/pipenv/pull/3304 will bring even more improvements here as it will stop Dependabot from updating unrelated sub-dependencies. 🎉

**Comment by techalchemy** [comment]
as a related FYI that branch will be kept up with master because I use it all the time...
