### ISSUE TITLE
Dependabot error on Swift 5.9

### ISSUE THREAD

**Issue by soumyamahunt** [dependabot/dependabot-core#8072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

swift

### Package manager version

5.9

### Language version

5.9

### Manifest location and content before the Dependabot update

https://github.com/SwiftyLab/MetaCodable/blob/main/Package.swift

### dependabot.yml content

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(Deps): '

 - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '

### What you expected to see, versus what you actually saw

Expected dependabot to be able to analyze dependencies, but dependabot is giving error for Swift 5.9 package manifest:

> proxy | 2023/09/21 14:03:18 proxy starting, commit: 93c4a893d794d736d84e940a79420e8d1180c0bd
  proxy | 2023/09/21 14:03:18 Listening (:1080)
updater | 2023-09-21T14:03:19.626368513 [724721815:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-09-21T14:03:25Z" level=info msg="guest starting" commit=b073e069d366dc2f68bb8ef0134feb3c29cacadd
updater | time="2023-09-21T14:03:25Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=724721815 updater_timeout=45m0s updater_version=35e67411da961f13974a64b67cf540ce878b2ec7-swift
updater | 2023/09/21 14:03:31 INFO Raven 3.1.2 ready to catch errors
updater | 2023/09/21 14:03:37 INFO <job_724721815> Starting job processing
  proxy | 2023/09/21 14:03:38 [002] GET https://github.com:443/SwiftyLab/MetaCodable/info/refs?service=git-upload-pack
  proxy | 2023/09/21 14:03:38 [002] * authenticating git server request (host: github.com)
  proxy | 2023/09/21 14:03:38 [002] 200 https://github.com:443/SwiftyLab/MetaCodable/info/refs?service=git-upload-pack
  proxy | 2023/09/21 14:03:38 [004] POST https://github.com:443/SwiftyLab/MetaCodable/git-upload-pack
  proxy | 2023/09/21 14:03:38 [004] * authenticating git server request (host: github.com)
  proxy | 2023/09/21 14:03:38 [004] 200 https://github.com:443/SwiftyLab/MetaCodable/git-upload-pack
  proxy | 2023/09/21 14:03:38 [006] POST https://github.com:443/SwiftyLab/MetaCodable/git-upload-pack
  proxy | 2023/09/21 14:03:38 [006] * authenticating git server request (host: github.com)
  proxy | 2023/09/21 14:03:38 [006] 200 https://github.com:443/SwiftyLab/MetaCodable/git-upload-pack
updater | 2023/09/21 14:03:38 INFO <job_724721815> Finished job processing
updater | time="2023-09-21T14:03:39Z" level=info msg="task complete" container_id=job-724721815-file-fetcher exit_code=0 job_id=724721815 step=fetcher
updater | 2023/09/21 14:03:43 INFO Raven 3.1.2 ready to catch errors
updater | 2023/09/21 14:03:48 INFO <job_724721815> Starting job processing
updater | 2023/09/21 14:03:52 ERROR <job_724721815> error: 'repo': package 'repo' is using Swift tools version 5.9.0 but the installed version is 5.8.1
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/common/lib/dependabot/shared_helpers.rb:344:in `run_shell_command'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:39:in `formatted_deps'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:25:in `block (2 levels) in parse'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/common/lib/dependabot/shared_helpers.rb:195:in `with_git_configured'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:24:in `block in parse'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/common/lib/dependabot/shared_helpers.rb:42:in `block in in_a_temporary_repo_directory'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/common/lib/dependabot/shared_helpers.rb:42:in `chdir'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/common/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_repo_directory'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:21:in `parse'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/swift/lib/dependabot/swift/file_parser.rb:18:in `parse'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:100:in `parse_files!'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:89:in `initialize'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:22:in `new'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:22:in `create_from_job_definition'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/09/21 14:03:52 ERROR <job_724721815> bin/update_files.rb:24:in `<main>'
updater | 2023/09/21 14:03:52 INFO <job_724721815> Sending event 962baa22301943459721798e85bc7a10 to Sentry
  proxy | 2023/09/21 14:03:52 [008] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/09/21 14:03:52 [008] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/09/21 14:03:53 INFO <job_724721815> Finished job processing
updater | 2023/09/21 14:03:53 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
updater | time="2023-09-21T14:03:53Z" level=info msg="task complete" container_id=job-724721815-updater exit_code=0 job_id=724721815 step=updater

From the error:

> updater | 2023/09/21 14:03:52 ERROR <job_724721815> error: 'repo': package 'repo' is using Swift tools version 5.9.0 but the installed version is 5.8.1

it seems like dependabot is using swift 5.8.1 toolchain which requires to be updated to 5.9.

**Comment by deivid-rodriguez** [comment]
Thanks for the report!

We need to update the version of Swift Dependabot is running. Can you help? It should be a matter of bumping the version in `swift/Dockerfile`.

**Comment by soumyamahunt** [comment]
> Thanks for the report!
> 
> We need to update the version of Swift Dependabot is running. Can you help? It should be a matter of bumping the version in `swift/Dockerfile`.

Thanks for the response @deivid-rodriguez, I can definitely help with this. Will create PR with the changes shortly.

`swift-org` started maintaining released snapshots versions [here](https://github.com/apple/swift-org-website/blob/main/_data/builds/swift_releases.yml), which can be used to get latest swift version. I think for long-term this can be used to get latest Swift version instead of maintaining static version. What do you think?

**Comment by deivid-rodriguez** [comment]
Thanks a lot!

That's an interesting idea. It could be handy but I wouldn't like that Dependabot suddenly stops working for older Swift versions because a newer version has some incompatibility or bug. I think I'd stick with adding support explicitly (and be confident about it through our CI), at least for now.

**Comment by soumyamahunt** [comment]
@deivid-rodriguez PR #8073 created to fix this issue.
