### ISSUE TITLE
Support running dependabot on private runners

### ISSUE THREAD

**Issue by kuhnroyal** [dependabot/dependabot-core#8081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

GHES supports configuring runners for dependabot (https://docs.github.com/en/enterprise-server@3.10/admin/github-actions/enabling-github-actions-for-github-enterprise-server/managing-self-hosted-runners-for-dependabot-updates#about-self-hosted-runners-for-dependabot-updates).

I think the same should be possible for the (enterprise) cloud.

We only use private runners on our own infrastructure and all our private registries are only available inside a VPN.
Currently there seems to be no way for dependabot to run inside the VPN except for starting experimenting with dependabot-script.

**Comment by carogalvin** [comment]
@kuhnroyal thanks for your input! We have some work on this happening and have a private beta for this feature running right now. If you're interested in participating in the private beta, please email me at carogalvin(at)github.com!

**Comment by jmax01** [comment]
This would be great, every time keycloak updates our dependabot updates crash with timeouts

**Comment by kuhnroyal** [comment]
@jmax01 My organization is part of the closed beta now for about 2 month. I can confirm that this is working on premise for GHEC, at least for GH-Actions/Java/Kotlin/Ruby/Dart/Node ecosystems.

If you are a GHEC customer, maybe try mailing Caro.

**Comment by ikalnytskyi** [comment]
@carogalvin Is there any plans to make this available for everyone on GHEC?

**Comment by kuhnroyal** [comment]
FYI https://github.com/github/roadmap/issues/929

**Comment by carogalvin** [comment]
@ikalnytskyi you can expect this to be available to GHEC in April! You can refer to the roadmap issue linked by `@kuhnroyal` to keep track of any changes.

**Comment by ikalnytskyi** [comment]
Great, thank you!

**Comment by professor** [comment]
Check out the feature here: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-dependabot-on-self-hosted-runners
