### ISSUE TITLE
Dependabot not detecting yarn workspaces

### ISSUE THREAD

**Issue by molant** [dependabot/dependabot-core#809]
Hello,

I've installed dependabot in [this project](https://github.com/molant/hint/) where I'm using yarn workspaces (no lerna) but it has only detected the files in the root:

![image](https://user-images.githubusercontent.com/606594/49128714-799f8300-f281-11e8-8491-e74a57970b76.png)

And that's what's happening with its PRs so far. In https://github.com/molant/hint/commit/d5ab8b48f7f75e3706647d6595140bb2d4d0893b there should be more packages updated.

After going through the issues in this repo it seems like this should just work without having to use lerna but I haven't found a definitive answer.

Thank you

**Comment by greysteil** [comment]
Thanks for the heads up. Looks like Dependabot is getting confused by the `"packages/!(connector-edge)"` specification. Let me take a look at fixing that.

**Comment by greysteil** [comment]
This should now be fixed. Thanks again!

**Comment by molant** [comment]
Thanks a lot!
