### ISSUE TITLE
Rename java_script to javascript

### ISSUE THREAD

**Issue by lipis** [dependabot/dependabot-core#812]
My OCD hit me, when I was browsing the repo.

Is it too late to rename the folder [`java_script`](https://github.com/dependabot/dependabot-core/tree/master/spec/dependabot/file_fetchers/java_script) to `javascript`? When having the `_` int the snake name means that there is a space.. and there is no space in JavaScript :)

**Comment by greysteil** [comment]
Haha, we're going to do a *big* move on this repo to namespace everything by language. We'll change it when we do 🙂

**Comment by lipis** [comment]
thanks

**Comment by greysteil** [comment]
Well it was my bad insisting we used `java_script` so as Ruby would autoload `JavaScript`. Been taking shit for that for the last 18 months...!

**Comment by lipis** [comment]
it's never too late to fix it :)
