### ISSUE TITLE
grouped refresh causes dependency duplication

### ISSUE THREAD

**Issue by jakecoffman** [dependabot/dependabot-core#8149]
> We're still seeing duplication [...]
> 
> For example, this grouped PR includes the `libcnb-data` and `libcnb-package` packages:
https://github.com/heroku/languages-github-actions/pull/152
> 
> ...even though they are covered by this (earlier in the Dependabot config definition) group:
https://github.com/heroku/languages-github-actions/pull/148
> 
> Our Dependabot config is here:
> https://github.com/heroku/languages-github-actions/blob/main/.github/dependabot.yml
> 
> And I reported this originally here:
> https://github.com/dependabot/dependabot-core/issues/7939
> 
> Which was then marked as a duplicate of #7915 (which this PR closed).

_Originally posted by @edmorley in https://github.com/dependabot/dependabot-core/issues/8106#issuecomment-1750275326_

**Comment by jakecoffman** [comment]
@edmorley Thanks for reporting that!

I forked the repo and Dependabot correctly created PRs with no duplication so it looks like #8106 was successful in that regard.

However once I ran the `@dependabot recreate` command on the rust-dependencies group PR it recreated and added back in the libcnb-data and libcnb-package dependencies.

I think I know what to do here, I'll try to get that fixed up today!

**Comment by jakecoffman** [comment]
@edmorley This is fixed now. Since the repo is in a weird state, I suggest commenting `@dependabot recreate` on https://github.com/heroku/languages-github-actions/pull/152 which should close the PR and put a new one up without duplication.

**Comment by edmorley** [comment]
I am seeing some old/superseded PRs not being closed though - for which I've filed #8162.
