### ISSUE TITLE
Update of sentry gems tries to update git sources

### ISSUE THREAD

**Issue by robbevp** [dependabot/dependabot-core#8195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

2.4.10

### Language version

3.2.2

### Manifest location and content before the Dependabot update

https://github.com/robbevp/dependabot-bundler-sentry-reproduction/blob/main/Gemfile

### dependabot.yml content

https://github.com/robbevp/dependabot-bundler-sentry-reproduction/blob/main/.github/dependabot.yml

### Updated dependency

* sentry-rails: 5.10 -> 5.12
* sentry-ruby: 5.10 -> 5.12

(I've also seen this happen for other versions of the sentry gems)

### What you expected to see, versus what you actually saw

When updating the sentry gems (which happens together, regardless of whether a group was created), dependabot will also update the gems which have git sources. These other dependencies should not be touched or mentioned.

If the git source can also be updated, dependabot will update it (see mocha in my reproduction).
If the git source is up to date, dependabot will still mention it in the PR title and description.

I've noticed this problem in my actual projects (with a lot more dependencies) and:
* It consistently happens for the sentry gems
* Update the sentry gems will pull in all gems with a git source

### Images of the diff or a link to the PR, issue, or logs

https://github.com/robbevp/dependabot-bundler-sentry-reproduction/pull/1
https://github.com/robbevp/dependabot-bundler-sentry-reproduction/pull/2

### Smallest manifest that reproduces the issue

See this repo for the smallest possible reproduction: https://github.com/robbevp/dependabot-bundler-sentry-reproduction

**Comment by vassyz** [comment]
I have exactly the same issue. And because the branch names it creates goes ofer the CI limit, the build fails.

**Comment by fcheung** [comment]
I’m seeing the same thing too (for me it also happens with the flipper family of gems as well as sentry)

**Comment by deivid-rodriguez** [comment]
#8267 should hopefully fix this!

**Comment by robbevp** [comment]
Thanks for the quick fix @deivid-rodriguez ! When trigger new dependabot updates, the incorrect PRs are closed and correct PRs are created
