### ISSUE TITLE
Dependabot ran out of disk space during its update

### ISSUE THREAD

**Issue by Th3S4mur41** [dependabot/dependabot-core#8245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

lts

### Language version

lts

### dependabot.yml content

https://github.com/Th3S4mur41/mh-photography.com/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Dependabot has no issues updating actions but fails when updating npm dependencies with the following error:

```sh
proxy | 2023/10/20 09:55:19 proxy starting, commit: 177b79b3279d896f40d0106a42f112a74926e34e
  proxy | 2023/10/20 09:55:19 Listening (:1080)
updater | 2023-10-20T09:55:20.317465694 [738542567:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-10-20T09:55:22Z" level=info msg="guest starting" commit=e75527fd04f889bbb6beb6fe359fa9ae5657ef2e
updater | time="2023-10-20T09:55:22Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=738542567 updater_timeout=45m0s updater_version=1d5b6488ed9dd0227d254f64d9bfe4748993af18-npm
updater | 2023/10/20 09:55:24 INFO Raven 3.1.2 ready to catch errors
updater | 2023/10/20 09:55:26 INFO <job_738542567> Starting job processing
  proxy | 2023/10/20 09:55:26 [002] GET https://github.com:443/Th3S4mur41/mh-photography.com/info/refs?service=git-upload-pack
  proxy | 2023/10/20 09:55:26 [002] * authenticating git server request (host: github.com)
  proxy | 2023/10/20 09:55:26 [002] 200 https://github.com:443/Th3S4mur41/mh-photography.com/info/refs?service=git-upload-pack
  proxy | 2023/10/20 09:55:26 [004] POST https://github.com:443/Th3S4mur41/mh-photography.com/git-upload-pack
  proxy | 2023/10/20 09:55:26 [004] * authenticating git server request (host: github.com)
  proxy | 2023/10/20 09:55:26 [004] 200 https://github.com:443/Th3S4mur41/mh-photography.com/git-upload-pack
  proxy | 2023/10/20 09:55:26 [006] POST https://github.com:443/Th3S4mur41/mh-photography.com/git-upload-pack
  proxy | 2023/10/20 09:55:26 [006] * authenticating git server request (host: github.com)
  proxy | 2023/10/20 09:55:27 [006] 200 https://github.com:443/Th3S4mur41/mh-photography.com/git-upload-pack
updater | 2023/10/20 09:59:34 ERROR <job_738542567> Error during file fetching; aborting
updater | 2023/10/20 09:59:34 INFO <job_738542567> Finished job processing
updater | 2023/10/20 09:59:34 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------+
updater | |   Errors    |
updater | +-------------+
updater | | out_of_disk |
updater | +-------------+
updater | time="2023-10-20T09:59:34Z" level=info msg="task complete" container_id=job-738542567-file-fetcher exit_code=0 job_id=738542567 step=fetcher
updater | time="2023-10-20T09:59:35Z" level=warning msg="failed during fetch, skipping updater" job_id=738542567
```

**Comment by lukehsiao** [comment]
It would seem more discussion is happening in #8613, perhaps these two tickets should be merged (or this one marked a dupe).

**Comment by dannyrb** [comment]
#8613 has been marked as `closed`, but the solution appears to be tied to the "Dependabot on Action (private beta)". It looks like "anyone can join" the private beta. The information requested for enrollment is:

> - Repository names
> - Will onboarding be on Github hosted runner or self-hosted runner?
> 
> Note: Make sure, that the GitHub actions is enabled on the repo before we do the onboarding. 

The folks doing the enrollment appear to be:

- @honeyankit 
- @jakecoffman

The last response from them in that thread was on Jan 16th 2024

**Comment by Th3S4mur41** [comment]
Sounds indeed like the same issue...
@honeyankit  @jakecoffman would you be so nice to enable the beta where Dependabot jobs run on Actions for the following repository? 
https://github.com:443/Th3S4mur41/mh-photography.com

**Comment by honeyankit** [comment]
@Th3S4mur41 : I will enable the repo `Th3S4mur41/mh-photography.com` the on Dependabot on actions (private beat) for GitHub hosted runners.

**Comment by honeyankit** [comment]
Repo `Th3S4mur41/mh-photography.com` is onboarded to Depebdabot on actions (private beta)

**Comment by Th3S4mur41** [comment]
Thanks @honeyankit I'm no longer getting the issue 👍

**Comment by dannyrb** [comment]
@honeyankit and @jakecoffman could I trouble you to do the same for the following repositories?

- `teamupstart/typescript-platform`
- `teamupstart/upstart-web-frontend`
