### ISSUE TITLE
Python: Updating a specific package `flask-cors` incorrectly updates the Python version

### ISSUE THREAD

**Issue by amotl** [dependabot/dependabot-core#8250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Python / pip / Poetry

### Package manager version

Poetry 1.6.1

### Language version

Python 3.11

### Manifest location and content before the Dependabot update

https://github.com/wireviz/wireviz-web/blob/8f1b3c65c03fc0a947765f63f36305fafa7bf86c/pyproject.toml

### dependabot.yml content

https://github.com/wireviz/wireviz-web/blob/8f1b3c65c03fc0a947765f63f36305fafa7bf86c/.github/dependabot.yml

### Updated dependency

Bump flask-cors from 3.0.10 to 4.0.0.

#### Expected
Only to bump `flask-cors`, as announced.

#### Actual
Bumps `flask-cors` _and_ Python.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/wireviz/wireviz-web/pull/40

**Comment by deivid-rodriguez** [comment]
Hello! This is a recent regression. I'm deploying a fix right now through #8263.

**Comment by deivid-rodriguez** [comment]
Can you run `@dependabot recreate` now on an incorrect PR and see if it's amended correctly?

**Comment by amotl** [comment]
Dear David,

thanks for the quick reply. The `recreate` command has been invoked [^1], but it looks like it does not resolve the problem yet.

With kind regards,
Andreas.

[^1]: https://github.com/wireviz/wireviz-web/pull/40#issuecomment-1775688665

**Comment by deivid-rodriguez** [comment]
I think I got a proper fix now, let me deploy it and I'll let you know when you can retry.

**Comment by deivid-rodriguez** [comment]
Could you try again now @amotl?
