### ISSUE TITLE
Dependabot updates to non-existent version in `pyproject.toml`

### ISSUE THREAD

**Issue by levrik** [dependabot/dependabot-core#8259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Poetry

### Package manager version

Poetry 1.6.1

### Manifest location and content before the Dependabot update

Repository reproducing the issue: https://github.com/levrik/dependabot-poetry-bug

### What you expected to see, versus what you actually saw

When 2 dependencies happen to be on the same version within `pyproject.toml`, the version number is replaced for both dependencies by the version number of the dependency the PR is created for. This leads to `pyproject.toml` being out-of-sync with `poetry.lock` and more importantly reference to non-existent versions. Further automatic rebases by Dependabot also fail due to the non-existent version within `pyproject.toml`.

Broken example PRs:

https://github.com/levrik/dependabot-poetry-bug/pull/1/files#r1368464320
https://github.com/levrik/dependabot-poetry-bug/pull/2/files#r1368464579

I wonder if it broke due to the recent regex changes done in https://github.com/dependabot/dependabot-core/pull/8190.

**Comment by deivid-rodriguez** [comment]
Oops, let me have a look at this!

**Comment by deivid-rodriguez** [comment]
Can you run `@dependabot recreate` now on an incorrect PR and see if it's amended correctly?

**Comment by levrik** [comment]
@deivid-rodriguez Will run it on one of my example PRs linked above.

**Comment by deivid-rodriguez** [comment]
Thanks! Since I was not sure if you'd be available immediately, I went ahead and verified it on a fork. It seems to have done the trick! https://github.com/dsp-testing/dependabot-poetry-bug/pull/1

**Comment by deivid-rodriguez** [comment]
Oh, but https://github.com/dsp-testing/dependabot-poetry-bug/pull/2 still did not work! Will have another look.

**Comment by levrik** [comment]
@deivid-rodriguez Also still broken here: https://github.com/levrik/dependabot-poetry-bug/pull/3/files

**Comment by deivid-rodriguez** [comment]
Ok, I pushed some more changes which should fix the issue now. Currently deploying them, I'll let you know when I'm done so you can retry 👍.

**Comment by deivid-rodriguez** [comment]
Could you try again now @levrik?

**Comment by levrik** [comment]
@deivid-rodriguez https://github.com/levrik/dependabot-poetry-bug/pull/3 looks good now!
