### ISSUE TITLE
Dependabot for Swift stopped working

### ISSUE THREAD

**Issue by MahdiBM** [dependabot/dependabot-core#8295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Swift

### Package manager version

Swift Package Manager - Swift 5.9

### Language version

Swift 5.9

### Manifest location and content before the Dependabot update

[vapor/penny-bot/Package.resolved](https://github.com/vapor/penny-bot/blob/main/Package.resolved)

### dependabot.yml content

[vapor/penny-bot/.github/dependabot.yml](https://github.com/vapor/penny-bot/blob/main/.github/dependabot.yml)

### Updated dependency

No dependencies are no longer updated.
One example, `Package.resolved` specifies `swift-nio` `version` [`2.60.0`](https://github.com/vapor/penny-bot/blob/b69f0412a004cc4e85263772721adfbdb7188fb2/Package.resolved#L233), but [`2.61.0`](https://github.com/apple/swift-nio/releases/tag/2.61.0) has been out for 3+ days.
The schedule is set to daily, so the update-dependencies-PR should have already happened.

### What you expected to see, versus what you actually saw

Dependabot still updates `github-actions` based on the configuration file, but doesn't update the Swift dependencies anymore. It should update the Swift dependencies as well.

### Native package manager behavior

SPM - `swift package update`: Just works and updates package per usual of the last year or more.

### Smallest manifest that reproduces the issue

~~I have a theory that Dependabot is incompatible with Swift 5.9 and that's why it's failing, but just a guess.
`gh-codeql` also doesn't work on Swift 5.9 for reasons i don't recall, which makes me think the same thing might be true for Dependabot.~~

Nevermind, there has been a [Dependabot PR](https://github.com/vapor/penny-bot/pull/122) on Oct 6th after [we moved to Swift 5.9](https://github.com/vapor/penny-bot/commit/05f2749e70cecd47567bfeb6bade188c64a54fa4) on Sep 24th.

**Comment by MahdiBM** [comment]
After more investigations, it appears the updates are unrelated to Swift 5.9 (updated the description). They have stopped right after [Add GH actions to Dependabot config](https://github.com/vapor/penny-bot/commit/a923cf64e3896e26591334fb5fc30a171ec73e9b) PR. 
The PR adds `github-actions` to be updated by dependabot. Basically:
```diff
version: 2
enable-beta-ecosystems: true
updates:
+  - package-ecosystem: "github-actions"
+    directory: "/"
+    schedule:
+      interval: "daily"
+    groups:
+     dependencies:
+        patterns:
+         - "*"
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
```
After this we're seeing no updates to Swift packages.

**Comment by deivid-rodriguez** [comment]
Sounds like the PR arrived [15' ago](https://github.com/vapor/penny-bot/pull/133)? Not sure if you did something there or the PR look a bit longer to show up? The [daily schedule](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval) does not apply to weekends, so that's probably why?

**Comment by MahdiBM** [comment]
> Sounds like the PR arrived https://github.com/vapor/penny-bot/pull/133

yeah we did notice, we removed "gh-actions" from Dependabot just to test, might be related.

> Not sure if you did something there

We're investigating this on our own side, i'll keep you updated again.

> The [daily schedule](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval) does not apply to weekends

That's good to know, didn't know about that.

**Comment by deivid-rodriguez** [comment]
Removing another ecosystem from the configuration should be unrelated, but it should've triggered Dependabot to run on your repo, since currently Dependabot reacts to any configuration change and re-runs everything.

But even if you had not changed the configuration, the PR should've arrived during the day anyways.

I think there's no issue here, but feel free to run more investigations on your side and let us know!

**Comment by MahdiBM** [comment]
> I think there's no issue here

The thing is Penny and SwiftNIO were just an example. I have other private projects that aren't being updated too.

**Comment by deivid-rodriguez** [comment]
Ah ok, I'll wait for more information/examples then!

**Comment by MahdiBM** [comment]
To be clear, i'm still trying 🙂 I'll let you know when i have updates, at worst in the next 2 weeks.

**Comment by MahdiBM** [comment]
@deivid-rodriguez It appears that Dependabot is only updating the packages that are explicitly defined in `dependencies` of the top-level `package` declaration in `Package.swift` (those with URLs). Is there a way i can tell Dependabot to go for _all_ dependencies of the whole package instead? We do commit `Package.resolved`s, so i would expect Dependabot to be able to read the dependencies off of that?

**Comment by deivid-rodriguez** [comment]
You probably want to configure [`allow.dependency-type`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)?

**Comment by MahdiBM** [comment]
Thanks for the pointer, that solves the problem.

This was quite confusing just because this wasn't the behavior from the beginning, but i notice that swift-support is still in beta and this behavior will match other ecosystem supports more closely, so it's understandable.

Thanks again for the debugging session.
