### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by Kurt-von-Laven** [dependabot/dependabot-core#8348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We pin Python 3.12.0 in our `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = "==3.12.0"
```

We encounter the following error message from Dependabot:

```
Dependabot does not support your Python version
Dependabot detected the following Python requirement for your project: '==3.12.0'.

Currently, the following Python versions are supported in Dependabot: 3.11.*, 3.10.*, 3.9.*, 3.8.*.
```

This is an ongoing issue for us, because we try to keep the Python version in sync with the version on the GitHub-hosted runner images. A significant percentage of the time we either lag the version of Python in the runner image or Dependabot can't run. It would be helpful to have greater visibility into which Python versions Dependabot supports, although I realize it is possible to determine this by inspecting Dependabot's source code.

**Comment by Kurt-von-Laven** [comment]
I mean documentation. The copy and formatting of the error message is great, but users don't see that until after they have already merged the pull request that upgrades them to an incompatible version of Python. Alternatively, there may be some way of running some Dependabot checks on pull requests that I'm unaware of.

Excited to hear Python 3.12 support is in progress.

**Comment by deivid-rodriguez** [comment]
Oh I see, that's right! We should probably find a good way to document supported language versions.

**Comment by sunil-enable** [comment]
hey @deivid-rodriguez do you know if  support for 3.12 python will be possible soon.The PR #8227 mentioned above has not moved for last 2 months. 
This prevents projects from upgrading to python 3.12 and use dependabot updates.
