### ISSUE TITLE
Nuget - No project file or packages.config!

### ISSUE THREAD

**Issue by thomhurst** [dependabot/dependabot-core#8398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget 

### Language version

.NET 6/7

### dependabot.yml content

https://github.com/thomhurst/ModularPipelines/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Any updates to be successfully detected and pull requests raised

What actually happened was dependabot fails to run. This has only started today. Runs prior to today were passing fine.

It states no project, but I'm using a working directory with a solution file in it, so it should pick that up.

The error being shown in logs is:
updater | 2023/11/14 22:02:54 INFO <job_749952138> Starting grouped update job for thomhurst/ModularPipelines
updater | 2023/11/14 22:02:54 INFO <job_749952138> Found 3 group(s).
updater | 2023/11/14 22:02:54 INFO <job_749952138> Starting update group for 'aws-dependencies'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> No project file or packages.config!
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:113:in `check_required_files'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/common/lib/dependabot/file_parsers/base.rb:18:in `initialize'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `new'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `dependency_file_parser'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:41:in `block in compile_all_dependency_changes_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:114:in `run_update_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:96:in `block in run_grouped_dependency_updates'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `each'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `run_grouped_dependency_updates'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:45:in `perform'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> bin/update_files.rb:24:in `<main>'
updater | 2023/11/14 22:02:54 INFO <job_749952138> Sending event b818f5783a3942009aa32f616433a7f5 to Sentry
  proxy | 2023/11/14 22:02:55 [144] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/14 22:02:55 [144] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/14 22:02:55 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
updater | time="2023-11-14T22:02:55Z" level=info msg="task complete" container_id=job-749952138-updater exit_code=0 job_id=749952138 step=updater

**Comment by jakecoffman** [comment]
This is fixed now, sorry for the regression!

**Comment by thomhurst** [comment]
No worries! Just got a bunch of PR raised just now. Thanks for fixing!
