### ISSUE TITLE
Inconsistency with grouped updates formatting

### ISSUE THREAD

**Issue by jacobbednarz** [dependabot/dependabot-core#8481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.20

### dependabot.yml content

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

When a single grouped update is performed, the PR body is

```
Bumps the aws group with 1 update: github.com/aws/aws-sdk-go-v2/service/s3.

> Commits

... snip
```

Example: https://github.com/cloudflare/terraform-provider-cloudflare/pull/2966

Whereas when the grouped update is > 1, the PR body is 

```
Bumps the aws group with 3 updates: [github.com/aws/aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2), [github.com/aws/aws-sdk-go-v2/config](https://github.com/aws/aws-sdk-go-v2) and [github.com/aws/aws-sdk-go-v2/service/s3](https://github.com/aws/aws-sdk-go-v2).

Updates github.com/aws/aws-sdk-go-v2 from 1.23.1 to 1.23.2

> Commits

... snip
```

Example: https://github.com/cloudflare/terraform-provider-cloudflare/pull/2968

The `Updates ... from ... to ...` is missing in the single grouped update version.

It would be great if these were consistent to clearly show the version changes in the PR body.

### Smallest manifest that reproduces the issue

- Use the dependabot config (https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/.github/dependabot.yml)
- Have part of the AWS SDK packages bump a *single* package version
- You'll see the single grouped update output missing the `Updates ...` line.
- Have part of the AWS SDK packages bump a *multiple* package version
- You'll see the multiple grouped update output with the `Updates ...` line included for each dependency.

**Comment by jakecoffman** [comment]
Fixed by https://github.com/dependabot/dependabot-core/pull/8478

**Comment by jacobbednarz** [comment]
thank you @jakecoffman! legendary effort 🙇
