### ISSUE TITLE
update private packages from npmjs suddenly stop working

### ISSUE THREAD

**Issue by mla-v-office** [dependabot/dependabot-core#8544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

9.8.1

### Language version

18.18.2

### dependabot.yml content

`version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_SECRET}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-npmjs
    schedule:
      interval: 'daily'
      time: '04:30'
    open-pull-requests-limit: 20`

### What you expected to see, versus what you actually saw

Suddenly it stopped working for the dependencies from our private organization dependencies in npmjs.

auth token is fine, packages are fine, local install works, no config changes but from one day to another this week it stopped working.

` proxy | 2023/12/06 08:42:00 [110] GET https://registry.npmjs.org:443/@myorga%2Fmypackage
  proxy | 2023/12/06 08:42:00 [110] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 08:42:01 [110] 200 https://registry.npmjs.org:443/@myorga%2Fmypackage
  proxy | 2023/12/06 08:42:01 [112] HEAD https://registry.npmjs.org:443/@myorga%2Fmypackaget/-/mypackage-0.385.0.tgz
  proxy | 2023/12/06 08:42:01 [112] * authenticating npm registry request (host: registry.npmjs.org, token auth)

  proxy | 2023/12/06 08:42:02 [112] 404 https://registry.npmjs.org:443/@myorga%2Fmypackage/-/mypackage-0.385.0.tgz`
  
 auth seems fine but get 404 while try downloading

**Comment by mla-v-office** [comment]
I think something changed or broke with `proxy | 2023/12/06 08:42:01 [112] * authenticating npm registry request (host: registry.npmjs.org, token auth)`.
Because the token is fine, I tested it and even created a new token.

**Comment by mla-v-office** [comment]
> Hi, thanks for reporting!
> 
> Sounds like #8489 could be related. There's a duplicated `2F` in those links that seems wrong, can you verify whether removing that duplication from those links, the link is no longer 404?

Sorry, the double "2F" was just copy error.
It looks like this, it tries to get any version and goes down to version 1. This makes the dependabot run very long as well if there are a lot versions or multiple packages from a private repo

`proxy | 2023/12/06 13:37:53 [022] GET https://registry.npmjs.org:443/@v-office%2Fprettier-config
  proxy | 2023/12/06 13:37:53 [022] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 13:37:54 [022] 200 https://registry.npmjs.org:443/@v-office%2Fprettier-config
  proxy | 2023/12/06 13:37:54 [024] HEAD https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz
  proxy | 2023/12/06 13:37:54 [024] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 13:37:54 [024] 404 https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz
  proxy | 2023/12/06 13:37:54 [026] HEAD https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.27.0.tgz
  proxy | 2023/12/06 13:37:54 [026] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 13:37:55 [026] 404 https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.27.0.tgz
  proxy | 2023/12/06 13:37:55 [028] HEAD https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.26.0.tgz`

**Comment by mla-v-office** [comment]
> Interesting. And do those URLs actually exist, in order words, is the `.tgz` file there?

yes, works all fine in codespaces. And gh actions with npm ci working (without cache) fine as well).

**Comment by mla-v-office** [comment]
Only Dependabot has a problem. Worked fine for over a year and we changed nothing. Suddenly about 5 days ago it stopped working.

**Comment by deivid-rodriguez** [comment]
Yes, I understand that this is a regression in Dependabot. I'm trying to learn why #8489 caused an issue. So, if I'm understanding well, `https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz` is the correct URL for the package's tarball. But for some reason our HEAD request is incorrectly returning 404.

That sounds like an issue with the npm registry, but we'll need to workaround it somehow. Some ideas:
* Just use a GET request and download the whole tarball (but may get slow).
* Use a streaming GET request and just look at the response headers without downloading the whole tarball.

If I temporarily deploy a solution for this, would you be able to try it?

**Comment by mla-v-office** [comment]
I can try it out.

**Comment by deivid-rodriguez** [comment]
I'll be deploying a [potential fix](https://github.com/dependabot/dependabot-core/pull/8546) in about 10 minutes, would you be able to manually run Dependabot to see if that did the trick?

**Comment by mla-v-office** [comment]
yes, i can

**Comment by mla-v-office** [comment]
runs now

**Comment by mla-v-office** [comment]
nothing changed. Logs is the same
  proxy | 2023/12/06 15:34:28 [154] GET https://registry.npmjs.org:443/@v-office%2Fprettier-config
  proxy | 2023/12/06 15:34:28 [154] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 15:34:28 [154] 200 https://registry.npmjs.org:443/@v-office%2Fprettier-config
  proxy | 2023/12/06 15:34:29 [156] GET https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz
  proxy | 2023/12/06 15:34:29 [156] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 15:34:29 [156] 404 https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz
  proxy | 2023/12/06 15:34:29 [158] GET https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.27.0.tgz
  proxy | 2023/12/06 15:34:29 [158] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 15:34:30 [158] 404 https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.27.0.tgz
  proxy | 2023/12/06 15:34:30 [160] GET https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.26.0.tgz
  .....
  proxy | 2023/12/06 15:34:47 [226] * authenticating npm registry request (host: registry.npmjs.org, token auth)
  proxy | 2023/12/06 15:34:47 [226] 404 https://registry.npmjs.org:443/@v-office%2Fprettier-config/-/prettier-config-0.0.1.tgz
updater | 2023/12/06 15:34:47 INFO <job_759206794> Latest version is 
  proxy | 2023/12/06 15:34:47 [228] GET https://registry.npmjs.org:443/@v-office%2Fjstools

**Comment by deivid-rodriguez** [comment]
Ok, so that's not it then. Are tarball URLs present in your lockfile. If yes, what do they look like, in particular, what does the tarball URL for prettier-config look like?

**Comment by mla-v-office** [comment]
It's "lockfileVersion": 3 for a month and I have already tried it with "lockfileVersion":2, which has the same result.

**Comment by deivid-rodriguez** [comment]
I'm really confused, I'm not sure why `https://registry.npmjs.org/@v-office%2Fprettier-config/-/prettier-config-0.28.0.tgz` results in 404, while `https://registry.npmjs.org/@v-office/prettier-config/-/prettier-config-0.28.0.tgz` is the right URL for the tarball.

I guess we can try without escaping the slash for the scope.

**Comment by danielclausmeyer** [comment]
I think there where some changes made to code regarding this in the last release: https://github.com/dependabot/dependabot-core/pull/8324

**Comment by deivid-rodriguez** [comment]
I also thought your token could be expired, but the `https://registry.npmjs.org/@v-office%2Fprettier-config` request is authenticating just fine, so that should not be it.

**Comment by deivid-rodriguez** [comment]
Are you still available to try again @mla-v-office?

**Comment by mla-v-office** [comment]
ok:  <img width="945" alt="image" src="https://github.com/dependabot/dependabot-core/assets/107429332/cd576236-8018-437d-b6f6-f8f2912f4098">
not found: <img width="945" alt="image" src="https://github.com/dependabot/dependabot-core/assets/107429332/7eaf9078-fb8c-4ca0-90a8-e93532dbfec2">

**Comment by deivid-rodriguez** [comment]
Nice, then I think my change this time is going to fix it but let's make sure. Can you try again?

**Comment by mla-v-office** [comment]
yes, just let me know when to do it

**Comment by mla-v-office** [comment]
yes, that did the trick. thank you very much :)

**Comment by deivid-rodriguez** [comment]
Ok, great, I'd still need you to try one more version. I'd like to keep HEAD requests if possible, so I'll remove that from my PR and ask you to recheck?

**Comment by mla-v-office** [comment]
okay

**Comment by deivid-rodriguez** [comment]
Ok, can you try one last time now?

**Comment by mla-v-office** [comment]
sure

**Comment by mla-v-office** [comment]
still works. thank you 👍
