### ISSUE TITLE
Error: "Malformed version number string"

### ISSUE THREAD

**Issue by snesm** [dependabot/dependabot-core#8550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

https://github.com/CDCgov/prime-reportstream/blob/master/.github/dependabot.yml#L24

### Updated dependency

[Bump tj-actions/branch-names from 7.0.6 to 7.0.7](https://github.com/CDCgov/prime-reportstream/pull/12493)

### What you expected to see, versus what you actually saw

Expected: no action since tj-actions/branch-names was already updated

Actual: a dependabot alert was created and dependabot failed to create a PR (probably because it was already fixed)

### Images of the diff or a link to the PR, issue, or logs

updater | 2023/12/06 13:41:39 INFO <job_759167763> Starting security update job for CDCgov/prime-reportstream
updater | 2023/12/06 13:41:39 INFO <job_759167763> Checking if tj-actions/branch-names 7.0.7 needs updating
  proxy | 2023/12/06 13:41:39 [232] GET https://github.com:443/tj-actions/branch-names.git/info/refs?service=git-upload-pack
  proxy | 2023/12/06 13:41:39 [232] * authenticating git server request (host: github.com)
  proxy | 2023/12/06 13:41:40 [232] 200 https://github.com:443/tj-actions/branch-names.git/info/refs?service=git-upload-pack
updater | 2023/12/06 13:41:40 INFO <job_759167763> Latest version is 7.0.7
updater | 2023/12/06 13:41:40 INFO <job_759167763> Sending event 426ec230d3e245618d1b5e8d3f4b705a to Sentry
  proxy | 2023/12/06 13:41:40 [234] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/06 13:41:40 [234] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/06 13:41:40 ERROR <job_759167763> Error processing tj-actions/branch-names (ArgumentError)
updater | 2023/12/06 13:41:40 ERROR <job_759167763> Malformed version number string 
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/common/lib/dependabot/version.rb:9:in `initialize'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/github_actions/lib/dependabot/github_actions/version.rb:12:in `initialize'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:65:in `block in active_advisories'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:64:in `select'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:64:in `active_advisories'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:142:in `vulnerable?'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:86:in `check_and_create_pull_request'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `block in perform'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `each'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `perform'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/06 13:41:40 ERROR <job_759167763> bin/update_files.rb:24:in `<main>'
updater | 2023/12/06 13:41:40 INFO <job_759167763> Finished job processing
updater | 2023/12/06 13:41:40 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------------+
updater | |      Dependencies failed to update      |
updater | +-------------------------+---------------+
updater | | tj-actions/branch-names | unknown_error |
updater | +-------------------------+---------------+

**Comment by martincostello** [comment]
Just found this one myself, appears to be erroring updating `uses: github/codeql-action/init@v3`.

```
updater | 2024/03/12 01:15:30 INFO <job_798767160> Updating github/codeql-action from 2.22.11 to 3.24.6
  proxy | 2024/03/12 01:15:30 [062] GET https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2024/03/12 01:15:30 [062] * authenticating git server request (host: github.com)
  proxy | 2024/03/12 01:15:30 [062] 200 https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
updater | 2024/03/12 01:15:30 ERROR <job_798767160> Error processing github/codeql-action (ArgumentError)
updater | 2024/03/12 01:15:30 ERROR <job_798767160> Malformed version number string 
updater | 2024/03/12 01:15:30 ERROR <job_798767160> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize'
updater | 2024/03/12 01:15:30 ERROR <job_798767160> /home/dependabot/common/lib/dependabot/version.rb:19:in `initialize'
updater | 2024/03/12 01:15:30 ERROR <job_798767160> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:1547:in `bind_call'
updater | 2024/03/12 01:15:30 ERROR <job_798767160> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:1547:in `block in create_validator_procedure_medium1'
updater | 2024/03/12 01:15:30 ERROR <job_798767160> /home/dependabot/github_actions/lib/dependabot/github_actions/version.rb:17:in `initialize'
```

**Comment by thavaahariharangit** [comment]
@martincostello @snesm 

Hey guys in our dev environment things are working as expected. We are unable recreate the malformed version error that you have reported above.

Local dev logs FYC
```terminal
updater | 2024/07/04 09:42:03 INFO Checking if github/codeql-action 3 needs updating
  proxy | 2024/07/04 09:42:04 [243] GET https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2024/07/04 09:42:04 [243] 200 https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
updater | 2024/07/04 09:42:04 INFO Latest version is 3
updater | 2024/07/04 09:42:04 INFO No update needed for github/codeql-action 3
updater | 2024/07/04 09:42:04 INFO Checking if actions/dependency-review-action 4.3.3 needs updating
  proxy | 2024/07/04 09:42:04 [245] GET https://github.com:443/actions/dependency-review-action.git/info/refs?service=git-upload-pack
  proxy | 2024/07/04 09:42:04 [245] 200 https://github.com:443/actions/dependency-review-action.git/info/refs?service=git-upload-pack
updater | 2024/07/04 09:42:04 INFO Latest version is 4.3.3
updater | 2024/07/04 09:42:04 INFO No update needed for actions/dependency-review-action 4.3.3
```

Are we still having this error. If yes could you please provide us the steps to reproduce.

Thanks.

FYI @amazimbe

**Comment by amazimbe** [comment]
As mentioned earlier, we are not able to reproduce this locally and as we haven't received any feedback that it is still an issue, I'm closing it and will reopen if necessary.

**Comment by snesm** [comment]
@amazimbe

I have not experienced this issue since I first reported it.  Thanks for checking.
