### ISSUE TITLE
github_action  malformed version number string, when no associated tag with old sha, but there is a comment.

### ISSUE THREAD

**Issue by MichielJazzy1** [dependabot/dependabot-core#8559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

don't know

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps): update "
```

### Updated dependency

Before:
```
uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203 # ratchet:dorny/test-reporter@v1
```
new sha: 6a1c2425d8b9d402c42e6128950575e8ba67ad38

### What you expected to see, versus what you actually saw

I noticed that  in
`updated_version_comment`  as part of dependabot-core/github_actions/lib/dependabot/github_actions/file_updater.rb

``` 
previous_version_tag = git_checker.most_specific_version_tag_for_sha(old_ref)
previous_version = version_class.new(previous_version_tag).to_s
```
previous_version_tag is empty, because there is no tag associated with the old_ref sha.
The code shouldn't raise an error here.

Some extra logs that show the local_tags in git_commit_checker:
``` 
updater | 2023/12/07 14:18:57 INFO MICHIEL tags: [#<Dependabot::GitRef:0x00007f2e239463c8 @name="v1.0.0", @commit_sha="71f2f95ef0c4a3656e44272deca4a1efe096628a", @ref_sha="71f2f95ef0c4a3656e44272deca4a1efe096628a", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e2394cc28 @name="v1.1.0", @commit_sha="603e84536d4c09f9486956466e0a3ca7e847cb3b", @ref_sha="603e84536d4c09f9486956466e0a3ca7e847cb3b", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e239514a8 @name="v1.2.0", @commit_sha="f285c4c6d79d7e6630b0d6f37f06e77641e9dafb", @ref_sha="f285c4c6d79d7e6630b0d6f37f06e77641e9dafb", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e4fd70 @name="v1.3.0", @commit_sha="51956bab1c0d5107c4f16628b19ac384ab040405", @ref_sha="51956bab1c0d5107c4f16628b19ac384ab040405", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e52958 @name="v1.3.1", @commit_sha="2c87efac073270a76b2a8c81d9b1e3b082f245c8", @ref_sha="2c87efac073270a76b2a8c81d9b1e3b082f245c8", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e56710 @name="v1.4.0", @commit_sha="0c4e1654a1218dbe3f08e376b1a103c72dd713ef", @ref_sha="0c4e1654a1218dbe3f08e376b1a103c72dd713ef", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e54848 @name="v1.4.1", @commit_sha="4fcb1ce90b8db576ae97ba5252038065e98d83f3", @ref_sha="4fcb1ce90b8db576ae97ba5252038065e98d83f3", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e5a630 @name="v1.4.2", @commit_sha="cbdb21833647b50f5d422cb5d514a2d6f7680dae", @ref_sha="cbdb21833647b50f5d422cb5d514a2d6f7680dae", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e58858 @name="v1.4.3", @commit_sha="6969ae6af5efb4ddb55b1e5aa1e1198de99e191c", @ref_sha="6969ae6af5efb4ddb55b1e5aa1e1198de99e191c", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e5dc40 @name="v1.5.0", @commit_sha="0d00bb14cb0cc2c9b8985df6e81dd333188224e1", @ref_sha="0d00bb14cb0cc2c9b8985df6e81dd333188224e1", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e63410 @name="v1.6.0", @commit_sha="c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226", @ref_sha="c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>, #<Dependabot::GitRef:0x00007f2e22e61ed0 @name="v1.7.0", @commit_sha="afe6793191b75b608954023a46831a3fe10048d4", @ref_sha="c0c07982a537cb3ffeeb3818036022e8b97197ac", @tag_sha=nil, @ref_type=#<Dependabot::RefType::Tag>>]

updater | 2023/12/07 14:18:57 INFO MICHIEL: previous_version_tag: , old_ref: e9fa2f582c0ebbe2e263fd18fad744d52e0b0203, new_ref: 6a1c2425d8b9d402c42e6128950575e8ba67ad38

```

https://github.com/dorny/test-reporter

### Images of the diff or a link to the PR, issue, or logs

  proxy | 2023/12/07 14:09:05 [108] 200 http://host.docker.internal:63775/update_jobs/cli/record_update_job_error
updater | 2023/12/07 14:09:05 ERROR Error processing dorny/test-reporter (ArgumentError)
updater | 2023/12/07 14:09:05 ERROR Malformed version number string
updater | 2023/12/07 14:09:05 ERROR /usr/local/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/common/lib/dependabot/version.rb:9:in `initialize'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/version.rb:12:in `initialize'
updater | 2023/12/07 14:09:05 ERROR /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/12/07 14:09:05 ERROR /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:103:in `updated_version_comment'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:85:in `block (2 levels) in updated_workflow_file_content'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:80:in `gsub'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:80:in `block in updated_workflow_file_content'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:59:in `each'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:59:in `updated_workflow_file_content'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:24:in `block in updated_dependency_files'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:18:in `each'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:18:in `updated_dependency_files'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:89:in `generate_dependency_files'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/07 14:09:05 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/07 14:09:05 ERROR bin/update_files.rb:24:in `<main>'

**Comment by jakecoffman** [comment]
This should no longer raise an exception, complete the update successfully, and leave the comment as-is.
