### ISSUE TITLE
Support automatic PRs for updating `rust-toolchain.toml` nightly timestamps

### ISSUE THREAD

**Issue by Qix-** [dependabot/dependabot-core#8591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

If the rust-roolchain.toml file uses a date-pinned nightly (e.g. `"nightly-2023-12-08"`) it'd be great to periodically have PRs from dependabot to bump this date and open a PR to see if it breaks anything.

**Comment by jtran** [comment]
Possibly a duplicate of #1702.

**Comment by Qix-** [comment]
Indeed, thank you!
