### ISSUE TITLE
Authentication not working against azure repositories with the nuget v3 using the query2 urls

### ISSUE THREAD

**Issue by joaorosado** [dependabot/dependabot-core#8600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

version: 2
registries:
  nuget-feed-pkgs-dev-azure-com-redactedorg-packaging-artifactrep:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
    username: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_REDACTEDORG_PACKAGING_ARTIFACTREP_USERNAME}}"
    password: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_REDACTEDORG_PACKAGING_ARTIFACTREP_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
  open-pull-requests-limit: 25
  rebase-strategy: disabled
  registries:
    - nuget-feed-pkgs-dev-azure-com-redactedorg-packaging-artifactrep

### What you expected to see, versus what you actually saw

While it is able to authenticate the call to the nuget/v3/index.json url. it appears it's not doing the same for the following requests.

This is the last **successful** logs from **some weeks ago** for comparison (from another repo, not the one I used for the replication below). Nothing changed on the auth tokens configuration and they are still current valid:
```
updater | 2023/11/24 19:26:27 INFO <job_754141353> Checking if Newtonsoft.Json 13.0.3 needs updating
  proxy | 2023/11/24 19:26:27 [376] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:27 [376] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:27 [376] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:28 [378] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/24 19:26:28 [378] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:28 [378] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
updater | 2023/11/24 19:26:28 INFO <job_754141353> Latest version is 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> No update needed for Newtonsoft.Json 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> Finished job processing
```

On these we could see the "authenticating nuget feed request" lines after each request. Something that no longer currently happens and requests fail with a 401.

### Images of the diff or a link to the PR, issue, or logs

```
  proxy | 2023/12/12 12:26:38 proxy starting, commit: 02a8910b917eff32ef3fe812e35a131d6286bc20
  proxy | 2023/12/12 12:26:38 * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/12/12 12:26:38 Listening (:1080)
updater | 2023-12-12T12:26:38.895753474 [761373615:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-12-12T12:26:40Z" level=info msg="guest starting" commit=eb5aa56302357f07a0e790713fa099f11a1af831
updater | time="2023-12-12T12:26:40Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=761373615 updater_timeout=45m0s updater_version=f7c9d9070e7f43d0d59e0692019a0537d3449f4b-nuget
updater | 2023/12/12 12:26:42 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/12 12:26:43 INFO <job_761373615> Starting job processing
  proxy | 2023/12/12 12:26:44 [002] GET https://github.com:443/RedactedOrg/jmr-dependabot/info/refs?service=git-upload-pack
  proxy | 2023/12/12 12:26:44 [002] * authenticating git server request (host: github.com)
  proxy | 2023/12/12 12:26:44 [002] 200 https://github.com:443/RedactedOrg/jmr-dependabot/info/refs?service=git-upload-pack
  proxy | 2023/12/12 12:26:44 [004] POST https://github.com:443/RedactedOrg/jmr-dependabot/git-upload-pack
  proxy | 2023/12/12 12:26:44 [004] * authenticating git server request (host: github.com)
  proxy | 2023/12/12 12:26:44 [004] 200 https://github.com:443/RedactedOrg/jmr-dependabot/git-upload-pack
  proxy | 2023/12/12 12:26:44 [006] POST https://github.com:443/RedactedOrg/jmr-dependabot/git-upload-pack
  proxy | 2023/12/12 12:26:44 [006] * authenticating git server request (host: github.com)
  proxy | 2023/12/12 12:26:44 [006] 200 https://github.com:443/RedactedOrg/jmr-dependabot/git-upload-pack
updater | 2023/12/12 12:26:44 INFO <job_761373615> Finished job processing
updater | time="2023-12-12T12:26:44Z" level=info msg="task complete" container_id=job-761373615-file-fetcher exit_code=0 job_id=761373615 step=fetcher
updater | 2023/12/12 12:26:45 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/12 12:26:46 INFO <job_761373615> Starting job processing
  proxy | 2023/12/12 12:26:47 [008] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/12/12 12:26:47 [008] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/12/12 12:26:47 [008] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/12/12 12:26:47 [010] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/query2/?q=newtonsoft.json&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/12 12:26:47 [010] 401 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/query2/?q=newtonsoft.json&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/12 12:26:47 [010] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/12/12 12:26:48 INFO <job_761373615> Starting update job for RedactedOrg/jmr-dependabot
updater | 2023/12/12 12:26:48 INFO <job_761373615> Checking all dependencies for version updates...
updater | 2023/12/12 12:26:48 INFO <job_761373615> Finished job processing
updater | time="2023-12-12T12:26:48Z" level=info msg="task complete" container_id=job-761373615-updater exit_code=0 job_id=761373615 step=updater
```

### Smallest manifest that reproduces the issue

[jmr-dependabot.zip](https://github.com/dependabot/dependabot-core/files/13648720/jmr-dependabot.zip)

My repositories and azure org are private so cannot share them here.
The zip has all the contents of the repository I used to replicate the issue, only with the name or the org replaced with "RedactedOrg"

**Comment by asos-lewish** [comment]
This has also been causing issues in my organisation for a few weeks now. No dependabot nuget updates are working. They all finish running with no PR raised. The error is the same as listed here, a 401 response when trying to authenticate with a private Artefacts Nuget feed. Our PAT token is valid and dependabot config has not been updated since the errors started.

We would really appreciate this issue being prioritised as it is having a big impact on our company. 

More info here also. 
https://github.com/dependabot/dependabot-core/issues/8475#issuecomment-1843721828

**Comment by joaorosado** [comment]
Is there any way to for dependabot (using the automatic service on github) to use the an older version? or at least opt out of these nuget url/auth changes?

:( this is breaking any dependency updates on all our repositories, as all use private assets

**Comment by manelpvoxel** [comment]
We had the same problem with azure repositories and is working now. Thank you!

**Comment by joaorosado** [comment]
yup no more 401authentication failures after these merges

now just lots of timeouts everywhere 🤕 but those are a separate issue

**Comment by asos-lewish** [comment]
Yes I can confirm we are no longer getting 403 errors when trying to connect to our private Azure Artifacts feed and I am now getting PRs raised for NuGet updates by dependabot. Many thanks for fixing this.
