### ISSUE TITLE
Dependabot ran out of disk space during its update

### ISSUE THREAD

**Issue by ahimelman** [dependabot/dependabot-core#8613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.20

### Manifest location and content before the Dependabot update

/go.mod
/go.sum

### What you expected to see, versus what you actually saw

Dependabot update jobs are consistently failing with the error `Dependabot ran out of disk space during its update`. An example failure includes the output 
```
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------+
updater | |   Errors    |
updater | +-------------+
updater | | out_of_disk |
updater | +-------------+
updater | time="2023-12-14T15:19:42Z" level=info msg="task complete" container_id=job-762355317-updater exit_code=0 job_id=762355317 step=updater
```

**Comment by jakecoffman** [comment]
We can put the repo on a beta where Dependabot jobs run on Actions and will have more space for the update. That should fix the problem. Let me know if that is ok and I can do it.

**Comment by ahimelman** [comment]
thanks @jakecoffman, is there any reason we wouldn't want to do that? if not, running on a beta should be fine.

**Comment by jakecoffman** [comment]
Not really, the experience is slightly different, but it's the only way we have to fix out of disk issues for now. Eventually all jobs will be running on Actions.

**Comment by ahimelman** [comment]
sounds good, let's try running on Actions then.

**Comment by jakecoffman** [comment]
I looked up the repo by the job ID in your log message and enabled Actions. If you start a new run now it should work.

**Comment by jakecoffman** [comment]
I've disabled the feature until we can figure out what is happening.

Does your organization use self-hosted runners? If so there is a little bit more setup that's needed, like adding a `dependabot` label so the job will be picked up. 

Here's more information: https://docs.github.com/en/enterprise-server@3.7/admin/github-actions/enabling-github-actions-for-github-enterprise-server/managing-self-hosted-runners-for-dependabot-updates

Let me know if you'd like me to enable it again. Sorry for the trouble!

**Comment by ahimelman** [comment]
no, I do not believe we are using self-hosted runners here

**Comment by jakecoffman** [comment]
The issue seems to be that Actions is disabled for that repo. Currently in the beta, Dependabot needs Actions enabled to work, but we are planning a feature to get around that since Dependabot's use of Actions is not billed.

So if you can enable Actions on that repo we can try again, otherwise please wait for us to implement that feature 🙂

**Comment by MattSkala** [comment]
We are experiencing a similar issue with swift dependencies:

```
Error Domain=NSCocoaErrorDomain Code=640 "There isn’t enough space."
```

```
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | update_files_error |
updater | +--------------------+
updater | time="2024-01-03T22:50:03Z" level=info msg="task complete" container_id=job-769696199-updater exit_code=0 job_id=769696199 step=updater
```

**Comment by ahimelman** [comment]
unfortunately I'm not able to activate Actions on this repo because of an org-wide policy. do you have a rough ETA for implementing this feature, or any other recommendations on how to resolve this in the meantime?

**Comment by samrayner** [comment]
Hey @jakecoffman. We're running into this issue on waveremit/remit-ios. We have Actions enabled on the repo. Any chance we could get in on the beta?

**Comment by jakecoffman** [comment]
@samrayner done

@MattSkala would you like to try the Actions beta? Make sure Actions is enabled on the repo.

@ahimelman Hopefully this quarter. Unfortunately there's no way to increase disk space besides the Actions beta.

**Comment by jakecoffman** [comment]
@MattSkala done

**Comment by samrayner** [comment]
Thank you @jakecoffman ! No more disk space issues now using Actions 🎉 
Opened [a new issue](https://github.com/dependabot/dependabot-core/issues/8753) for what we ran into next 😝

**Comment by MattSkala** [comment]
> @MattSkala done

@jakecoffman We are now seeing "Dependabot encountered an unknown error", there is no log available:

<img width="932" alt="image" src="https://github.com/dependabot/dependabot-core/assets/1122874/b5e280f5-05b7-4499-a8f8-ff9ec751bf85">

**Comment by lukehsiao** [comment]
@jakecoffman who is eligible to try the beta? We are also running out of space in one of our private repos. Would it be possible for us to try the beta?

**Comment by honeyankit** [comment]
@lukehsiao : 

I will be the below info for onboarding the repo to private beta:
1. Repo name ?
2. Onboarding will for Github hosted runner or self-hosted runner?


Make sure, that the GitHub actions is enabled before we do the onboarding. Thank you.

**Comment by lukehsiao** [comment]
> I will be the below info for onboarding the repo to private beta:
> 
> 1. Repo name ?

https://github.com/NumbersStationAI/hive

> 2. Onboarding will be on Github hosted runner or self-hosted runner?
> 
> Make sure, that the GitHub actions is enabled before we do the onboarding. Thank you.

We use GitHub Actions. We use both GitHub- and self-hosted runners. Is that OK?

**Comment by honeyankit** [comment]
I can onboard on either GitHub hosted runner or self-hosted. Let me know where you want to run your Dependabot jobs? If you choose self-hosted runner then you also need to add label `dependabot` to those runners. To start with I would suggest just run it on the GitHub hosted runner.

**Comment by lukehsiao** [comment]
> I can onboard on either GitHub hosted runner or self-hosted. Let me know where you want to run your Dependabot jobs? If you choose self-hosted runner then you also need to add label dependabot to those runners. To start with I would suggest just run it on the GitHub hosted runner.

Sounds good, GitHub-hosted runners would work fine for us :)

**Comment by honeyankit** [comment]
The task is completed. Now the Dependabot jobs should run on GitHub hosted Action runner. I am closing this issue.

**Comment by samrayner** [comment]
@jakecoffman @honeyankit 24 hours after being added to the beta our CI (Bitrise) has suddenly become unable to communicate with Github. I've tried redoing the connection but it says there's a problem with our repo. As it's not affecting any other repos in our org I can only assume it's related to the beta.

Please can we be removed from the beta asap? Our CI being down is a major problem for us. We can wait for the public release to try Dependabot again :)

**Comment by jakecoffman** [comment]
@samrayner it's disabled.

@honeyankit something to look into!

**Comment by honeyankit** [comment]
@samrayner: Could you share more detail of the issue? Any error screenshot or error logs from Action tab will help as well? 

Do you know what was the state of the Action runner when communication failed?

**Comment by lukehsiao** [comment]
> The task is completed. Now the Dependabot jobs should run on GitHub hosted Action runner. I am closing this issue.

Just wanted to follow up that this _does_ appear to resolve the issue for us! We are seeing dependabot PRs now. Thank you!

**Comment by samrayner** [comment]
Hey @honeyankit. It's been a confusing 48 hours for me but we've narrowed down the issue and I'm fairly convinced it's nothing to do with the Actions beta now. Bitrise (our CI - we don't use Actions for CI - sorry for any confusion) seems to have suddenly decided my account doesn't have the permissions it needs (it does). The timing was coincidental.

Please can https://github.com/waveremit/remit-ios be re-added to the beta? Sorry to mess you around! It did fix the issue we were facing to begin with :)

**Comment by honeyankit** [comment]
> Hey [@honeyankit](https://github.com/honeyankit). It's been a confusing 48 hours for me but we've narrowed down the issue and I'm fairly convinced it's nothing to do with the Actions beta now. Bitrise (our CI - we don't use Actions for CI - sorry for any confusion) seems to have suddenly decided my account doesn't have the permissions it needs (it does). The timing was coincidental.
> 
> Please can https://github.com/waveremit/remit-ios be re-added to the beta? Sorry to mess you around! It did fix the issue we were facing to begin with :)

@samrayner : No worries, glad it was not Dependabot on Actions issue. I have onboarded the repo https://github.com/waveremit/remit-ios back to Dependabot on Actions.

**Comment by samrayner** [comment]
Thanks @honeyankit! Dependabot has worked well a few times (on the Actions beta) but our job this morning ran out of space again unfortunately:
https://github.com/waveremit/remit-ios/actions/runs/7780569833/job/21213471287

**Comment by mlarraz** [comment]
We started seeing this same error about a week ago. We have Github Actions enabled. Sample job ID is 784799430

**Comment by JohnnyQQQQ** [comment]
Can you please activate the beta for `https://github.com/grafana/grafana-ruler`, it's using GitHub-hosted runners.
