### ISSUE TITLE
RubyGems profile no longer displays the Dependabot avatar

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#8625]
https://rubygems.org/profiles/dependabot used to display the :dependabot: avatar, but no more.

Pretty sure this worked fine a few months ago before I left, not sure what might have changed.

**Comment by jeffwidman** [comment]
Hmm... that sounds reasonable, but when I clicked now, the avatar is showing up. So I guess this is now working as expected...

**Comment by deivid-rodriguez** [comment]
Yes, the rubygems.org team managed to satisfy both concerns recently (email privacy and cute avatar) in https://github.com/rubygems/rubygems.org/pull/4599 :tada:

**Comment by jeffwidman** [comment]
Clever!
