### ISSUE TITLE
NuGet update failes when project path contains spaces.

### ISSUE THREAD

**Issue by TomW-Skyline** [dependabot/dependabot-core#8633]
The command arguments need to be surrounded by quotes, because otherwise there are problems when they contain spaces.

https://github.com/dependabot/dependabot-core/blob/89ebc55dac8630574301a10917425f80a56e4763/nuget/lib/dependabot/nuget/native_helpers.rb#L57

**Comment by abdulapopoola** [comment]
Sorry to hear that; will reopen the issue and tagging @brettfo for awareness

**Comment by brettfo** [comment]
@TomW-Skyline Do you have a recent log file you can share?  There are likely more places we need to surround arguments.

**Comment by brettfo** [comment]
@TomW-Skyline Added PR #9092 to allow proper execution of the tool with spaces in the command line.

**Comment by brettfo** [comment]
@TomW-Skyline I created a repo with a space in the path and did a full dependabot update run to verify the path fix.  I've also just submitted #9104 which will fail a unit test on a malformed path so we can detect this faster.
