### ISSUE TITLE
Grouped version updates don't have changelogs/commits for Bundler

### ISSUE THREAD

**Issue by enescakir** [dependabot/dependabot-core#8634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

2.4.10

### Language version

3.2.2

### Manifest location and content before the Dependabot update

https://github.com/ubicloud/ubicloud/blob/main/Gemfile

### dependabot.yml content

https://github.com/ubicloud/ubicloud/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I expected to see a changelogs/commits for the updated packages. However, the PR description doesn't contain any information about these updates.
The PR with this issue: https://github.com/ubicloud/ubicloud/pull/1024

Previously, it was putting changelogs/commits for the updated package. We have a PR with details from two weeks ago: https://github.com/ubicloud/ubicloud/pull/961

It look like that dependabot can't generate the PR description for `addressable` gem.

It appears that when dependabot cannot generate a PR description for a dependency in the group, it prevents dependabot from generating PR descriptions for all packages.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/ubicloud/ubicloud/pull/1024

### Smallest manifest that reproduces the issue

https://github.com/enescakir/ruby-dependabot-test/pulls

**Comment by enescakir** [comment]
Here's the dependabot logs.
[dependabot-logs.log](https://github.com/dependabot/dependabot-core/files/13693939/dependabot-logs.log)

These lines appear suspicious to me:

```
  proxy | 2023/12/16 21:01:43 [293] 200 https://api.github.com:443/repos/sporkmonger/addressable/contents/CHANGELOG.md?ref=main
updater | 2023/12/16 21:01:43 ERROR <job_762978551> Error while generating PR message: undefined method `name' for [:name, "CHANGELOG.md"]:Array
updater | 
updater |             tmp_files.find { |f| f.name == filename }
updater |                                   ^^^^^
  proxy | 2023/12/16 21:01:43 [295] GET https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [295] 404 https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [297] GET https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [297] 404 https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [299] GET https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [299] 404 https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [301] GET https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [301] 404 https://roda.jeremyevans.net:443/status
  proxy | 2023/12/16 21:01:43 [303] GET https://api.github.com:443/repos/sporkmonger/addressable/contents/CHANGELOG.md?ref=main
  proxy | 2023/12/16 21:01:43 [303] * authenticating github api request with token for api.github.com
  proxy | 2023/12/16 21:01:43 [303] 200 https://api.github.com:443/repos/sporkmonger/addressable/contents/CHANGELOG.md?ref=main
updater | 2023/12/16 21:01:43 ERROR <job_762978551> Error while generating commit message: undefined method `name' for [:name, "CHANGELOG.md"]:Array
updater | 
updater |             tmp_files.find { |f| f.name == filename }
updater |                                   ^^^^^
updater | 2023/12/16 21:01:44 INFO <job_762978551> Finished job processing
updater | 2023/12/16 21:01:44 INFO Results:

```

**Comment by enescakir** [comment]
It looks like there is a problem with either dependabot or roda's changelog. The issue is preventing dependabot from generating the PR description for all packages.

**Comment by enescakir** [comment]
I created a test repository with only `roda` and `addressable` gems. Dependabot created 2 PRs. https://github.com/enescakir/ruby-dependabot-test/pulls

The PR for `roda` has changelogs/commits in the description. The PR for `addressable` doesn't have changelogs/commits in the description.

It shows that the dependabot can`t generate PR description for `addressable` gem.

**Comment by enescakir** [comment]
It appears that when dependabot cannot generate a PR description for a dependency in the group, it prevents dependabot from generating PR descriptions for all packages.

**Comment by Nishnha** [comment]
Hi I think https://github.com/dependabot/dependabot-core/pull/9429 should fix this
