### ISSUE TITLE
Dependabot could not fetch go module as organization name of the go modules changed

### ISSUE THREAD

**Issue by babu-izhan-5001312** [dependabot/dependabot-core#8653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Language version

1.17

### Manifest location and content before the Dependabot update

```
module github.com/org1/mainpkg

go 1.17

require (
	github.com/org2/pkg1 v0.0.1
	github.com/org1/pkg2 v0.0.1
	github.com/org1/pkg3 v0.0.1
)
```

### dependabot.yml content

```
version: 2

updates:
  - package-ecosystem: gomod
    directory: /

    schedule:
      interval: daily

    allow:
      - dependency-name: "github.com/org1/*"
      - dependency-name: "github.com/org2/*"

```

### Updated dependency

Dependabot should update pkg1 and pkg2 from 0.0.1 to 0.0.2, but that is not happening.

```
module github.com/org1/mainpkg

go 1.17

require (
	github.com/org1/pkg2 v0.0.2
	github.com/org1/pkg3 v0.0.2
)
```

### What you expected to see, versus what you actually saw

We updated the organization name of pkg1 from org1 to org2 in github, but are still using `github.com/org1/pkg1` as the module name. 

Dependabot should update pkg1 from 0.0.1 to 0.0.2, but that is not happening. 

Instead it's giving 404 error in 
`404 https://github.com:443/org1/pkg1`

But doing `go get github.com/org1/pkg2` works and is able to fetch the module.

These are all private modules so the names are replaced.

### Native package manager behavior

`go get github.com/org1/pkg2 `

This works and is able to update pkg2 even though the org name is changed from org1 to org2.

### Images of the diff or a link to the PR, issue, or logs

```
proxy | 2023/12/15 13:58:42 [039] GET https://proxy.golang.org:443/github.com/org1/pkg1/@v/list
proxy | 2023/12/15 13:58:43 [039] 404 https://proxy.golang.org:443/github.com/org1/pkg1/@v/list
proxy | 2023/12/15 13:58:43 [041] GET https://github.com:443/org1/pkg1/info/refs?service=git-upload-pack
proxy | 2023/12/15 13:58:43 [041] * authenticating git server request (host: github.com)
proxy | 2023/12/15 13:58:44 [041] 404 https://github.com:443/org1/pkg1/info/refs?service=git-upload-pack
proxy | 2023/12/15 13:58:44 [041] * auth'd git request returned 404, retrying without auth
proxy | 2023/12/15 13:58:44 [041] * de-auth'd request returned 401, replacing response
proxy | 2023/12/15 13:58:44 [043] GET https://github.com:443/org1/pkg1
proxy | 2023/12/15 13:58:44 [043] * authenticating git server request (host: github.com)
proxy | 2023/12/15 13:58:44 [043] 404 https://github.com:443/org1/pkg1
proxy | 2023/12/15 13:58:44 [043] * auth'd git request returned 404, retrying without auth
proxy | 2023/12/15 13:58:44 [043] * de-auth'd request returned 404, ignoring response
proxy | 2023/12/15 13:58:44 [045] GET https://proxy.golang.org:443/github.com/org1/pkg1/@v/list
proxy | 2023/12/15 13:58:44 [045] 404 https://proxy.golang.org:443/github.com/org1/pkg1/@v/list
proxy | 2023/12/15 13:58:44 [047] GET https://github.com:443/org1/pkg1/info/refs?service=git-upload-pack
proxy | 2023/12/15 13:58:44 [047] * authenticating git server request (host: github.com)
proxy | 2023/12/15 13:58:44 [047] 404 https://github.com:443/org1/pkg1/info/refs?service=git-upload-pack
proxy | 2023/12/15 13:58:44 [047] * auth'd git request returned 404, retrying without auth
proxy | 2023/12/15 13:58:44 [047] * de-auth'd request returned 401, replacing response
proxy | 2023/12/15 13:58:44 [049] GET https://github.com:443/org1/pkg1
proxy | 2023/12/15 13:58:44 [049] * authenticating git server request (host: github.com)
proxy | 2023/12/15 13:58:44 [049] 404 https://github.com:443/org1/pkg1
proxy | 2023/12/15 13:58:44 [049] * auth'd git request returned 404, retrying without auth
proxy | 2023/12/15 13:58:45 [049] * de-auth'd request returned 404, ignoring response
updater | 2023/12/15 13:58:45 INFO <job_762772350> Handled error whilst updating github.com/org1/pkg1: git_dependencies_not_reachable {:"dependency-urls"=>["github.com/org1/pkg1"]}
```

**Comment by jakecoffman** [comment]
I recommend updating references to use org2 as it seems someone could create an org with the name of your previous org:

> After changing your organization's name, your old organization name becomes available for someone else to claim.

https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization#what-happens-when-i-change-my-organizations-name

Dependabot also runs `go list -m -versions -json github.com/org1/pkg1` to get the list of available versions. It looks like that might be the command that is failing.

But based on the potential name-squatting/dependency confusion attack mentioned above I don't think we want to support this use-case.
