### ISSUE TITLE
Add command or option for "merge and delete branch" to PR's

### ISSUE THREAD

**Issue by deiga** [dependabot/dependabot-core#866]
I don't like to keep merged branches hanging around and thus always have to manually delete PR's branches after merge. 

It would be great if I could either set an global option for dependabot to deleter merged PR's branches or if I could say `@dependabot merge and delete` etc to make this happen for me :)

**Comment by greysteil** [comment]
Thanks for the feedback @deiga. Dependabot will already automatically delete its branches for you as soon as they're merged - it just waits 10 seconds to do so to ensure it doesn't clash with any user actions 🙂

**Comment by deiga** [comment]
@greysteil Oh, cool! Could that be more prominent in the help dependabot adds to it's PR's?

**Comment by greysteil** [comment]
We could, but we try to keep the text there as short as possible (otherwise folks don’t read it). If I get lots of reports from others who are confused on this one I’ll change it.

Thanks again for the feedback!
