### ISSUE TITLE
Add global whitelist of dependencies setting

### ISSUE THREAD

**Issue by deiga** [dependabot/dependabot-core#867]
There are a few dependencies which I always want the newest version of no matter what, because they don't have any settings or code related to them in the repo.

It would be awesome if I could have a global language specific whitelist where I could specify which dependencies get auto-merged

**Comment by greysteil** [comment]
I'm up for this in principle, but the language-specific nature of it is going to make it quite a complicated setting. Perhaps it would be better solved by using config files, where you can then have a template file used everywhere (or included as a submodule)?

**Comment by greysteil** [comment]
I'm pretty confident that config files are the way to go here, so am going to close. Shout if you disagree! https://dependabot.com/blog/introducing-config-files/
