### ISSUE TITLE
Use dry-run on a Repository

### ISSUE THREAD

**Issue by karinarastsinskagia** [dependabot/dependabot-core#8688]
Hello,

Does anyone know how I can check version & security updates for my own repository, using the dependapot-core locally? 

Actually, on a previous dependabot-core release (`0.215.0`), I used to do the debugging running the `dry-run` as explained on the `Readme` with the `DEBUG_HELPERS=true` set and I received all the relevant messages.
Specifically, I was following the steps below : 
1. Clone the `dependabot-core` package
2. Run the command : `DEBUG_HELPERS=true bin/dry-run.rb composer --clone SSH URL`
3. Provide Username & Git Access Token

However, in the current version, after I create the development environment (`composer`), I cannot use the option `--clone` (since it's not supported anymore) to get my repository, in which I want to test the dependabot updates.

So, has anyone faced a similar problem or know the process to debug the dependabot's dependencies updates locally for a repository?

Thanks in advance!

**Comment by jakecoffman** [comment]
Can you use the [Dependabot CLI](https://github.com/dependabot/cli)? The basic usage would be `dependabot update composer <org>/<repo>`.
