### ISSUE TITLE
Cargo: do not update `Cargo.toml` when dependency version differs from `Cargo.lock`

### ISSUE THREAD

**Issue by clechasseur** [dependabot/dependabot-core#8689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Package manager: `cargo`

Currently, when dependabot creates a PR to update a project dependency using `cargo`, it updates both `Cargo.toml` and `Cargo.lock`. This is true _even_ if the current version of the dependency specified in `Cargo.toml` and `Cargo.lock` differ. Example:

https://github.com/clechasseur/mini_exercism/pull/73/files

In the PR above, dependabot wants to update the `thiserror` crate from version 1.0.53 to 1.0.56. However, in `Cargo.toml`, the version specified for `thiserror` is 1.0.2. This is intentional: because the project is a lib crate, `Cargo.toml` uses the minimum version of the `thiserror` crate that can be used. Furthermore, `Cargo.lock` is committed in source control simply to have reproducible builds, but it is not published with the crate.

It seems reasonable to think that if the version of a dependency differs between `Cargo.toml` and `Cargo.lock`, they are purposefully kept separate for that project. Consequently, dependabot could simply bump the version in `Cargo.lock` and not touch `Cargo.toml`.

If this is too much of a breaking change, maybe add it as an option? (I don't know if it's possible to do that when configuring dependabot currently.)

#### Side note

In the past, the Cargo book recommended that for lib crates, `Cargo.lock` should not be checked into source control. The current version of the Cargo book no longer suggest that (the reasoning on whether to check `Cargo.lock` into source control is more nuanced). I think, however, that this feature request stands regardless of one's opinion on whether or not `Cargo.lock` should be checked in.

**Comment by jakecoffman** [comment]
There's a setting to have Dependabot only update lockfiles: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

**Comment by clechasseur** [comment]
Thanks! From reading the docs, I think what I'd like is to use `increase-if-necessary`, but that's currently not supported for `cargo`. There's an issue for it, though: #4009 

I'll close this, since it's a duplicate (looks like I didn't search existing issues well enough).
