### ISSUE TITLE
GHE 3.10.3 / pnpm monorepo / only root package.json dependencies are updated

### ISSUE THREAD

**Issue by m2hd1** [dependabot/dependabot-core#8690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

8.7.6

### Language version

Node.js  v20.8.1

### Manifest location and content before the Dependabot update

package.json
pnpm-lock.yaml
pnpm-workspace.yaml
apps/myapp1/package.json
apps/myapp2/package.json

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: increase

### What you expected to see, versus what you actually saw

I'm expecting the myapp1 and myapp2 dependencies to be updated

**Comment by THE-RDEV** [comment]
> Pay 10 Eth to 0xbB422Eafc1a7998C4Fc8c7E08bd60D870DE48152

**Comment by m2hd1** [comment]
not sure what happened, but it's working now 🤷‍♂️ 
closing this.
