### ISSUE TITLE
Grouped nuget dependencies not all updated

### ISSUE THREAD

**Issue by dagstuan** [dependabot/dependabot-core#8740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

https://github.com/dagstuan/skredvarselGarmin/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I have a setup where I group nuget dependencies together. Dependabot creates a PR and seemingly identifies all outdated dependencies, yet not all `.csproj`-files are updated. See example-PR from dependabot here: https://github.com/dagstuan/skredvarselGarmin/pull/133/

In this case, most of the updated dependencies are contained in SkredvarselGarminWeb.csproj in another folder, yet the only changed file in the PR is the [SkredvarselGarminWeb.Tests.csproj](https://github.com/dagstuan/skredvarselGarmin/pull/133/files#diff-5df4244aebddddc3c95380dbcdf1ac75316582ed90e8a98e81d4ab7f1e86f1c4) even though the description says that dependabot has updated dependencies in the other `.csproj` as well.

**Comment by hwoodiwiss** [comment]
I'd like to add a +1 to this, only one of the three updates that should have been in [this](https://github.com/hwoodiwiss/HwoodiwissHelper/pull/30) group update were in the final commit.
The dependabot.yml with group for the above PR is [here](https://github.com/hwoodiwiss/HwoodiwissHelper/blob/main/.github/dependabot.yml)

**Comment by kmcc049** [comment]
This is a duplicate of https://github.com/dependabot/dependabot-core/issues/8576

**Comment by sebasgomez238** [comment]
@dagstuan and @hwoodiwiss The fix for this was merged yesterday (#9228). Let us know if this fixes your issue. Thanks!

**Comment by dagstuan** [comment]
@sebasgomez238 It seems to be working fine now. Thanks!
