### ISSUE TITLE
Dependabot no longer supports Ruby < 3?

### ISSUE THREAD

**Issue by airdrummingfool** [dependabot/dependabot-core#8756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler 2.4.22

### Language version

Ruby 2.7.8

### Manifest location and content before the Dependabot update

`/Gemfile`

### dependabot.yml content

```yml
---
version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
```

### What you expected to see, versus what you actually saw

I expected Dependabot to correctly resolve Bundler dependencies in a project that uses Ruby `2.7.8`. Instead, Dependabot reported `Dependabot can't resolve your Ruby dependency files`:

```
 Dependabot can't resolve your Ruby dependency files
Dependabot failed to update your dependencies because there was an error resolving your Ruby dependency files.

Dependabot encountered the following error:

Bundler::SolveFailure with message: Could not find compatible versions

Because rails >= 5.1.3.rc1, < 6.1.0.rc1 depends on bundler >= 1.3.0
  and every version of bundler depends on Ruby >= 3.0.0,
  rails >= 5.1.3.rc1, < 6.1.0.rc1 requires Ruby >= 3.0.0.
So, because Gemfile depends on rails ~> 5.2
  and current Ruby version is ~> 2.7.8,
  version solving has failed.
```

It seems that Dependabot is deciding that "every version of bundler depends on Ruby >= 3.0.0", which is not correct (unless it is applying additional constraints that I am unaware of). The first version of Bundler to depend on Ruby >= 3 is [Bundler `2.5.0`](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.5.0), and we use Bundler `2.4.22`.

I can see in the Dependabot logs that it successfully access the Bundler versions manifest:
```
  proxy | 2024/01/10 20:56:56 [476] GET https://index.rubygems.org:443/info/bundler
  proxy | 2024/01/10 20:56:56 [476] 200 https://index.rubygems.org:443/info/bundler
```

This manifest lists many versions of Bundler that do not require Ruby >= 3, and a handful that do:
```
---
0.3.1 |checksum:46ee4daadda796c1e9433b45015ff43f67ea47c8cf10e6f224ff5d87126d3302
0.3.0 |checksum:c90db69e215d0caa267149111284bb35558cf9640bfa03c73317218397df2363
[snip]
2.4.21 |checksum:017ae71a7b0a3024c614e344cd0cc56a16cb34afc53ada1899fb379d26624c91,ruby:>= 2.6.0,rubygems:>= 3.0.1
2.4.22 |checksum:747ba50b0e67df25cbd3b48f95831a77a4d53a581d55f063972fcb146d142c5f,ruby:>= 2.6.0,rubygems:>= 3.0.1
2.3.27 |checksum:dde4820453502e6cba55723d1376ccd6d2da049a7bbb922e3e7355cc7601034b,ruby:>= 2.3.0,rubygems:>= 2.5.2
2.5.0 |checksum:8952136f2d10816c73def0e8bc4b25c8f3fec9d4a58d571516e923b7cd2ed6c2,ruby:>= 3.0.0,rubygems:>= 3.2.3
2.5.1 |checksum:6b63f1bb4aedcde7fa2be3b309db7cb897170e9b4c09ad30314d50001b37b117,ruby:>= 3.0.0,rubygems:>= 3.2.3
2.5.2 |checksum:4f41bc156623cc0a99bbf21a03475982bfa27dad6d8d31aa93b90752e7a255db,ruby:>= 3.0.0,rubygems:>= 3.2.3
2.5.3 |checksum:249cd075ac4f335ae70f788c9be0f4c188093a4da7d05bd53be2baef3f25e7cb,ruby:>= 3.0.0,rubygems:>= 3.2.3
2.5.4 |checksum:f7b9f08c47e8c665613a668aa1b633df63f818b99183cee4b797704a816edefe,ruby:>= 3.0.0,rubygems:>= 3.2.3
```

**Comment by airdrummingfool** [comment]
This problem started sometime within the last few weeks (unfortunately I haven't been able to narrow it down more than that). It looks like Dependabot was recently [updated to Bundler 2.5.3](https://github.com/dependabot/dependabot-core/pull/8619), so if that's used in current Dependabot runs it could be related.

There's a [Bundler update (`3.5.4`)](https://github.com/rubygems/rubygems/releases/tag/v3.5.4) that addresses one instance of [older-Ruby incompatibility](https://github.com/rubygems/rubygems/issues/7329), but I'm not sure if Dependabot using that would be enough to fix the problem I've run into.

**Comment by toby-brilliant** [comment]
This started failing for us as well, same symptom: 
```
dependency_file_not_resolvable {:message=>"Bundler::SolveFailure with message: Could not find compatible versions\n\nBecause rails >= 6.1.0.rc1 depends on bundler >= 1.15.0\n  and every version of bundler depends on Ruby >= 3.0.0,\n  rails >= 6.1.0.rc1 requires Ruby >= 3.0.0.\nSo, because Gemfile depends on rails ~> 6.1\n  and current Ruby version is = 2.7.8,\n  version solving has failed."}
```

**Comment by deivid-rodriguez** [comment]
Do you have a public repository where this issue can be reproduced?

**Comment by toby-brilliant** [comment]
Yeah - I think anything with Ruby < 3 will break. E.g. I created a brand new templated Rails application here: https://github.com/toby-brilliant/dependabot-test

<img width="966" alt="image" src="https://github.com/dependabot/dependabot-core/assets/99420996/591a0edd-1f3a-4808-b2fb-dada5b167592">

**Comment by rhombl4** [comment]
Is it possible to specify the version of Bundler that Dependabot should use?

**Comment by jdelStrother** [comment]
Being able to specify the Ruby/bundler version might help this issue that appears to require Ruby >= 3.2 : https://github.com/dependabot/dependabot-core/issues/8731

**Comment by pavera** [comment]
Ruby [no longer supports Ruby 2.7](https://www.ruby-lang.org/en/downloads/branches/) so yes, this is no longer supported by Dependabot. As more and more packages remove Ruby 2.7 support (it has been EOL for a year now) it will become increasingly impossible for Dependabot to do its job of updating packages on this language version, which is why we only officially support language versions that are supported upstream.
