### ISSUE TITLE
Ignoring version in update, recreates the update, but does not account for grouping settings

### ISSUE THREAD

**Issue by osj2507** [dependabot/dependabot-core#8802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm / yarn

### Package manager version

yarn 1.x

### Language version

Node js 18 latest, React 18 latest

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
      timezone: "Europe/Copenhagen"
    groups:
      dev-dependencies-eslint:
        patterns:
          - "caniuse-lite"
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "@typescript-eslint/*"
      dev-dependencies-gatsby:
        patterns:
          - "gatsby"
          - "gatsby-plugin-*"
          - "gatsby-source-*"
      dev-dependencies:
        patterns:
          - "*"

### What you expected to see, versus what you actually saw

Dependabot creates the grouped PRs once a week, they look as they should, following my grouping rules in the yml file shown above.

If I ignore one of the updates, dependabot will recreate that PR without that update, but is then not following the grouped rules and will include a package that is not in the group.

This is the initial Dependabot PR
![Screenshot 2024-01-15 at 15 37 31](https://github.com/dependabot/dependabot-core/assets/1698496/0df595fd-c9e6-41ae-b14c-c7a5496f85ac)

Here I am ignoring the one update and dependabot closes this PR and recreates it
![Screenshot 2024-01-15 at 15 37 45](https://github.com/dependabot/dependabot-core/assets/1698496/bc000873-fbcf-4238-835f-0dd78153f6dc)

In the new PR prettier is now part of the updates, but it doesn't belong to this group of updates
![Screenshot 2024-01-15 at 15 38 04](https://github.com/dependabot/dependabot-core/assets/1698496/373601f1-6133-4353-94d4-221b796c1a27)

**Comment by Nishnha** [comment]
This should work correctly now. Can you update your dependabot.yml (adding or removing a newline works) and then try ignoring a dependency?

**Comment by abdulapopoola** [comment]
tagging @osj2507 ; thanks @Nishnha !

**Comment by abdulapopoola** [comment]
@osj2507 ; @Nishnha already fixed this; please feel free to reopen if this still happens.

**Comment by osj2507** [comment]
Hi @Nishnha and @abdulapopoola 
This seems to be fixed, so all is good, thank you
