### ISSUE TITLE
Document how to enable via yaml "support for reading the directories option when performing grouped version updates"

### ISSUE THREAD

**Issue by jzabroski** [dependabot/dependabot-core#8808]
>  @brbayes-msft Is https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request updated with an example for how this works?

_Originally posted by @jzabroski in https://github.com/dependabot/dependabot-core/issues/8541#issuecomment-1885191535_
            
See also: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups - does not mention anything about being to configure a group with multiple directories.

**Comment by carogalvin** [comment]
@jzabroski thanks for reaching out! This feature actually hasn't been "released" yet, we're still considering it "in development", so we haven't updated the documentation. You're welcome to poke around with it, but note that it's not yet officially supported. We'll get the documents updated once it's ready for prime time!

I'm going to close this issue in the meantime, as we have other processes at GitHub for getting the docs updated. If you think this is in error, feel free to re-open and we can chat about it.
