### ISSUE TITLE
Feature request: open issue when composer.json requires an end-of-life PHP version

### ISSUE THREAD

**Issue by GKFX** [dependabot/dependabot-core#881]
https://github.com/camdram/camdram had `composer.json` set `config.platform.php` to `7.0.30`. Since PHP 7.0 hit end of security support on 3 Dec 2018, I feel like we should have been warned by Dependabot that for the last month we've been running an unsupported version of PHP. I'm not certain what the best way to warn us would have been: perhaps Dependabot should open an issue 60 days before end-of-life of the version in `config.platform.php`? End of life for PHP versions is tabulated years in advance at https://secure.php.net/supported-versions.php.

This has the knock-on effect that Composer and Dependabot silently won't offer updates to any package versions that require PHP ^7.1 so there really is no indication that we're being left behind.
Many thanks!

**Comment by greysteil** [comment]
Interesting suggestion! I'd really like to support that, but it would be a bit of a deviation from the way our system works now, and there are a bunch of other PHP improvements I want to focus on first (ensuring update runs don't time out is top of the list).

I'm going to close this for now as I don't think we're going to get to it in the next 6 months, but I'm very happy to revisit it later, and appreciate the suggestion.

**Comment by greysteil** [comment]
Also, a privilege to be helping with Camdram in any way 🙂
