### ISSUE TITLE
Bundler updated in gemspec, but not in lock file

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#885]
In [this PR](https://github.com/deivid-rodriguez/byebug/pull/525), dependabot updated the bundler development dependency in the gemspec, but not the lock file. I think it should've updated the lock file as well, with a diff like:

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index d2199716..07a622ed 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -69,7 +69,7 @@ PLATFORMS
   ruby
 
 DEPENDENCIES
-  bundler (~> 1.7)
+  bundler (~> 2.0)
   byebug!
   chandler (= 0.7.0)
   mdl (= 0.5.0)
@@ -82,4 +82,4 @@ DEPENDENCIES
   yard (= 0.9.16)
 
 BUNDLED WITH
-   1.17.3
+   2.0.1
```

**Comment by greysteil** [comment]
Interesting. I agree, but we'd need to special case that. From memory there's some special casing around the way Bundler handles itself in the lockfile (and definitely is for the `BUNDLED WITH` line. Leave it with me.

**Comment by greysteil** [comment]
Hmm, yeah. The special thing appears to be that the locked version doesn't appear in the `GEM` section.

**Comment by deivid-rodriguez** [comment]
Indeed :+1:.

**Comment by jurre** [comment]
Hey, we just released better support for bundler 2. I think this should now be resolved, but please feel free to re-open this if that's not the case.
