### ISSUE TITLE
Improve README packages/gems documentation

### ISSUE THREAD

**Issue by LeoColomb** [dependabot/dependabot-core#899]
As many helpers and languages scripts have been moved during the repo reorganization, I would like to suggest a README edition (bellow).
This change also follow the want to make things generic.

Before opening a PR I need your review on this change first and also your answer regarding helpers:
* What about promoting `[manager]/helper/build`?
  * This would make things more generic and simplify overall installation.
  * This would allow managing environment more precisely, and for example avoid dev dependencies inclusion in "production" docker image.
* What about moving helper documentations (basically the `cd helper && install && cd -`) into their respective manager package?
  * This would help documenting their usage, like in [dependabot/dependabot-script](https://github.com/dependabot/dependabot-script/blob/master/README.md) (now outdated).

---

[![CircleCI](https://img.shields.io/circleci/project/github/dependabot/dependabot-core/master.svg)](https://circleci.com/gh/dependabot/dependabot-core) [![Ruby Gem](https://img.shields.io/gem/v/dependabot-core.svg)](https://rubygems.org/gems/dependabot-core) [![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-core.svg)](https://hub.docker.com/r/dependabot/dependabot-core)

## What's in this repo?

Dependabot Core is a collection of helper classes for automating dependency
updating. Highlights include:

- Logic to check for the latest version of a dependency *that's resolvable given
  a project's other dependencies*
- Logic to generate updated manifest and lockfiles for a new dependency version
- Logic to find changelogs, release notes, and commits for a dependency update
- Support for multiple languages and dependency managers

Language|Manager|Package|Custom Environment<sup>[1]()</sup>|Native Helpers<sup>[2]()</sup>|Docker Image
---|---|---|:-:|:-:|---
None|None|[![Ruby Gem][common_gem_img]][common_gem_url]|||[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-common.svg)](https://hub.docker.com/r/dependabot/dependabot-common)
All|All|[![Ruby Gem][omnibus_gem_img]][omnibus_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-omnibus.svg)](https://hub.docker.com/r/dependabot/dependabot-omnibus)
|||||
[Ruby](https://dependabot.com/ruby/)|bundler|[![Ruby Gem][bundler_gem_img]][bundler_gem_url]||
[Python](https://dependabot.com/python/)|pip|[![Ruby Gem][pip_gem_img]][pip_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-python.svg)](https://hub.docker.com/r/dependabot/dependabot-python)
[JavaScript](https://dependabot.com/javascript/)|npm/yarn|[![Ruby Gem][npm_and_yarn_gem_img]][npm_and_yarn_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-npm_and_yarn.svg)](https://hub.docker.com/r/dependabot/dependabot-npm_and_yarn)
[Java](https://dependabot.com/java/)|maven|[![Ruby Gem][maven_gem_img]][maven_gem_url]||
[Java](https://dependabot.com/java/)|gradle|[![Ruby Gem][gradle_gem_img]][gradle_gem_url]||
[Rust](https://dependabot.com/rust/)|cargo|[![Ruby Gem][cargo_gem_img]][cargo_gem_url]|✅||[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-cargo.svg)](https://hub.docker.com/r/dependabot/dependabot-cargo)
[Elixir](https://dependabot.com/elixir/)|hex|[![Ruby Gem][hex_gem_img]][hex_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-hex.svg)](https://hub.docker.com/r/dependabot/dependabot-hex)
[PHP](https://dependabot.com/php/)|composer|[![Ruby Gem][composer_gem_img]][composer_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-composer.svg)](https://hub.docker.com/r/dependabot/dependabot-composer)
[.NET](https://dependabot.com/dotnet/)|nuget|[![Ruby Gem][nuget_gem_img]][nuget_gem_url]||
[Go](https://dependabot.com/go/)|go_modules|[![Ruby Gem][go_modules_gem_img]][go_modules_gem_url]|✅|✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-go_modules.svg)](https://hub.docker.com/r/dependabot/dependabot-go_modules)
[Elm](https://dependabot.com/elm/)|elm|[![Ruby Gem][elm_gem_img]][elm_gem_url]|✅||[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-elm.svg)](https://hub.docker.com/r/dependabot/dependabot-elm)
[Git Submodules](https://dependabot.com/submodules/)|git_submodules|[![Ruby Gem][git_submodules_gem_img]][git_submodules_gem_url]||
[Docker](https://dependabot.com/docker/)|docker|[![Ruby Gem][docker_gem_img]][docker_gem_url]||
[Terraform](https://dependabot.com/terraform/)|terraform|[![Ruby Gem][terraform_gem_img]][terraform_gem_url]||✅|[![Docker Pulls](https://img.shields.io/docker/pulls/dependabot/dependabot-terraform.svg)](https://hub.docker.com/r/dependabot/dependabot-terraform)

[common_gem_img]: https://img.shields.io/gem/v/dependabot-common.svg
[common_gem_url]: https://rubygems.org/gems/dependabot-common
[omnibus_gem_img]: https://img.shields.io/gem/v/dependabot-omnibus.svg
[omnibus_gem_url]: https://rubygems.org/gems/dependabot-omnibus
[bundler_gem_img]: https://img.shields.io/gem/v/dependabot-bundler.svg
[bundler_gem_url]: https://rubygems.org/gems/dependabot-bundler
[pip_gem_img]: https://img.shields.io/gem/v/dependabot-python.svg
[pip_gem_url]: https://rubygems.org/gems/dependabot-python
[npm_and_yarn_gem_img]: https://img.shields.io/gem/v/dependabot-npm_and_yarn.svg
[npm_and_yarn_gem_url]: https://rubygems.org/gems/dependabot-npm_and_yarn
[maven_gem_img]: https://img.shields.io/gem/v/dependabot-maven.svg
[maven_gem_url]: https://rubygems.org/gems/dependabot-maven
[gradle_gem_img]: https://img.shields.io/gem/v/dependabot-gradle.svg
[gradle_gem_url]: https://rubygems.org/gems/dependabot-gradle
[cargo_gem_img]: https://img.shields.io/gem/v/dependabot-cargo.svg
[cargo_gem_url]: https://rubygems.org/gems/dependabot-cargo
[hex_gem_img]: https://img.shields.io/gem/v/dependabot-hex.svg
[hex_gem_url]: https://rubygems.org/gems/dependabot-hex
[composer_gem_img]: https://img.shields.io/gem/v/dependabot-composer.svg
[composer_gem_url]: https://rubygems.org/gems/dependabot-composer
[nuget_gem_img]: https://img.shields.io/gem/v/dependabot-nuget.svg
[nuget_gem_url]: https://rubygems.org/gems/dependabot-nuget
[go_modules_gem_img]: https://img.shields.io/gem/v/dependabot-go_modules.svg
[go_modules_gem_url]: https://rubygems.org/gems/dependabot-go_modules
[elm_gem_img]: https://img.shields.io/gem/v/dependabot-elm.svg
[elm_gem_url]: https://rubygems.org/gems/dependabot-elm
[git_submodules_gem_img]: https://img.shields.io/gem/v/dependabot-git_submodules.svg
[git_submodules_gem_url]: https://rubygems.org/gems/dependabot-git_submodules
[docker_gem_img]: https://img.shields.io/gem/v/dependabot-docker.svg
[docker_gem_url]: https://rubygems.org/gems/dependabot-docker
[terraform_gem_img]: https://img.shields.io/gem/v/dependabot-terraform.svg
[terraform_gem_url]: https://rubygems.org/gems/dependabot-terraform

#### Notes
1. To run all of Dependabot Core, you'll need these languages installed. However, if you just wish to run it for a single language you can get away with just having that language and Ruby.
2. Before running these Dependabot modules, you'll need to install their respective helpers.

**Comment by LeoColomb** [comment]
Sure, no problem! 👍

**Comment by LeoColomb** [comment]
Following #982, what is the status for this?

**Comment by feelepxyz** [comment]
@LeoColomb definitely 👍 on improving the readme. Sorry for the slow response times, we're stretched pretty thin so taking a while to get back to issues.

**Comment by LeoColomb** [comment]
No problem, let me know when you're ready.

**Comment by LeoColomb** [comment]
Still relevant 🙂

**Comment by LeoColomb** [comment]
Still still relevant 🙂

**Comment by jeffwidman** [comment]
Hey @LeoColomb 👋 Sorry for the glacially slow response. We are just starting to dig through some of the backlog.

Is this still relevant? I wasn't around for the repo re-org, so don't have full context here... I see a lot of Readme's so not sure if that covers what you planned or if there are other thigns you're thinking of? Regardless, we def welcome PR help with docs/code improvements.

**Comment by LeoColomb** [comment]
Well @jeffwidman, with all due respect, do you really expect me to have stayed on top of things for 3 long years?
No, my motivation to contribute to this project has gone, I'm afraid.
Is it still relevant? Probably, as the README looks quite complexe right now, and does not highlight current versions of packages, as oss community usually do.

**Comment by jeffwidman** [comment]
I'm going to be revamping a bunch of our open source docs / readme later this quarter, so will take a deeper look at this then.

For now I'm going to close this though, because I'm pretty sure I'll forget to circle back to close this otherwise and there's already an internal ticket tracking cleaning up this stuff.
