### ISSUE TITLE
Missing require statement - "uninitialized constant Dependabot::Credential::Forwardable"

### ISSUE THREAD

**Issue by fnoGematik** [dependabot/dependabot-core#9053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler version 2.5.3

### Language version

Ruby 3.1.4

### Manifest location and content before the Dependabot update

source "https://rubygems.org"
gem "irb"
gem "dependabot-omnibus", "~> 0.239.0"

### Updated dependency

dependabot-omnibus from 0.239.0 to 0.243.0

### What you expected to see, versus what you actually saw

Starting an update.rb file gives the following stacktrace since v0.243.0.
(Related pull request is #8995 )

/home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/credential.rb:9:in `<class:Credential>': uninitialized constant Dependabot::Credential::Forwardable (NameError)

    extend Forwardable
           ^^^^^^^^^^^
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/credential.rb:7:in `<module:Dependabot>'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/credential.rb:6:in `<top (required)>'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/file_fetchers/base.rb:10:in `require'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/file_fetchers/base.rb:10:in `<top (required)>'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/file_fetchers.rb:5:in `require'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.243.0/lib/dependabot/file_fetchers.rb:5:in `<top (required)>'
	from ./update.rb:4:in `require'
	from ./update.rb:4:in `<main>'

**Comment by fnoGematik** [comment]
It is obvious that the require statement (require "forwardable") is missing for extend statement of Forwardable class.

https://github.com/dependabot/dependabot-core/blob/v0.243.0/common/lib/dependabot/credential.rb#L9

**Comment by honeyankit** [comment]
Fix the PR marked in the issue
