### ISSUE TITLE
Dependabot sees updates but does not create PRs

### ISSUE THREAD

**Issue by LionZXY** [dependabot/dependabot-core#9199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### dependabot.yml content

https://github.com/flipperdevices/Flipper-Android-App/blob/dev/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Create a PR with an offer to upgrade dependencies

### Images of the diff or a link to the PR, issue, or logs

"No PRs affected", but:

```
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin ( from 1.9.22-1.0.17 to 1.9.22-1.0.18 ), com.google.dev... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | time="2024-02-29T15:15:21Z" level=info msg="task complete" container_id=job-794059466-updater exit_code=0 job_id=794059466 step=updater
```

**Comment by LionZXY** [comment]
@abdulapopoola This looks like a problem not in gradle but in general dependabot, what do you think?

**Comment by Laurie-Enveil** [comment]
having this issue with maven dependencies also
```
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | org.postgresql:postgresql ( from 42.7.2 to 42.7.3 ), com.fas... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | time="2024-03-21T11:34:26Z" level=info msg="task complete" container_id=job-803388645-updater exit_code=0 job_id=803388645 step=updater
```

Javascript and terraform PRs are getting created just fine for the same repository

**Comment by LionZXY** [comment]
@Laurie-Enveil Did you find some kind of workaround?

**Comment by Laurie-Enveil** [comment]
> @Laurie-Enveil Did you find some kind of workaround?

I undid the grouping configuration and am now seeing individual PRs get created successfully.

**Comment by jakecoffman** [comment]
@LionZXY in the dependabot.yml, can you try setting the last ignore to `"com.squareup.anvil:*"`?

**Comment by LionZXY** [comment]
Same thing :(
https://gist.github.com/LionZXY/cca4095f513a0d820e8904024f968fe5

**Comment by jakecoffman** [comment]
There's an ignore condition for `com.arkivanov.decompose:decompose`, but not `com.arkivanov.decompose:extensions-compose`, so when it goes to up that it also. updates `com.arkivanov.decompose:decompose`:

```
Updating com.arkivanov.decompose:decompose, com.arkivanov.decompose:extensions-compose
```

The root issue here is that the Updater that makes the change and the API which posts the PR are both enforcing ignores slightly differently. When the API enforces it, it just silently drops the PR. I've got a PR up internally to remove the ignore check from the API so we can have ignores in one place.

If you want to fix this in the meantime you can unignore `com.arkivanov.decompose:decompose` or change it to `com.arkivanov.decompose:*`

**Comment by LionZXY** [comment]
Same thing :(
Dependabot file: https://github.com/flipperdevices/Flipper-Android-App/blob/9215236db86f4b1d3a442e05581f2e619b6d78e8/.github/dependabot.yml
Full log: https://gist.github.com/LionZXY/cca4095f513a0d820e8904024f968fe5

**Comment by Nishnha** [comment]
Hi this should be fixed now. Can you try again?

**Comment by Laurie-Enveil** [comment]
it worked for me. Thanks!
