### ISSUE TITLE
Nuget update timeout caused by too many requests to https://dc.services.visualstudio.com:443/v2/track

### ISSUE THREAD

**Issue by TomW-Skyline** [dependabot/dependabot-core#9261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### What you expected to see, versus what you actually saw

Dependabot updates fail on our solution with "Dependabot timed out during its update". In the logging I see thousands of POST requests to "https://dc.services.visualstudio.com:443/v2/track". These request take a lot of time. What are they used for, and how can this be solved?

 proxy | 2024/03/11 02:01:37 [623] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [623] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [625] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [625] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [627] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [627] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [629] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:37 [629] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:39 Posting metrics to remote API endpoint
  proxy | 2024/03/11 02:01:39 Successfully posted metrics data via api client
  proxy | 2024/03/11 02:01:41 [632] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:41 [633] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:41 [633] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:41 [632] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [635] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [635] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [637] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [637] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [639] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:43 [639] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:44 [641] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:44 [641] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:48 [643] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:48 [643] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:49 [645] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/11 02:01:49 [645] 200 https://dc.services.visualstudio.com:443/v2/track

**Comment by JamieMagee** [comment]
@TomW-Skyline are you able to share a job id or which repository this is occurring on?

**Comment by JamieMagee** [comment]
@TomW-Skyline I understand that you can't post the full logs here, but if you're able to share just the job ID from the logs I can look into it from our side. The job ID appears in the logs as `job_xxxxxxxxx`. Without more information I can't debug further.

**Comment by JamieMagee** [comment]
Actually, this appears in a lot of job logs. Digging into it, it appears to be coming from Nuget. We use [`NuGet.Client`][1], and [posts telemetry][2] using [`Microsoft.VisualStudio.Telemetry`][3].

I can't immediately see a way to disable that.

[1]: https://github.com/dependabot/dependabot-core/tree/main/nuget/helpers/lib
[2]: https://github.com/NuGet/NuGet.Client/blob/2fdd0d41e33c3354de2750fe154b56751a6682aa/src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/TelemetrySession.cs#L26-L29
[3]: https://www.nuget.org/packages/Microsoft.VisualStudio.Telemetry

**Comment by JamieMagee** [comment]
Thanks for that. I dug into it, and reached out to someone on the NuGet team, and it doesn't appear that they are sending the telemetry. I'll need to investigate further.

**Comment by benmccallum** [comment]
I think this might be crippling our ability to get updates in our rather large mono repo.

Our setup is:
* NuGet
  * Centralised package versioning (Directory.Packages.props)
  * ~200 .csproj project files
  * ~10 solution files (are these crawled? because I do want to go to 1 sln with x slnf files)
* Yarn
* GitHub Actions 

Logs:
* Version update 814783535
* Version update 811869810 (this one managed to create 2 PRs)

**Comment by brettfo** [comment]
The extra telemetry calls have been removed but there are still likely some timeout issues.  Consolidating the timeout investigation to #9375.
