### ISSUE TITLE
yarn with github URL: losing the range specifier

### ISSUE THREAD

**Issue by SethDavenport** [dependabot/dependabot-core#932]
Not sure if this is an issue if I just have things set up wrong.

We're using some URLs in our `package.json` with `yarn`, and specifying that minor versions are ok. 

For example:
```
    "@my-company/advice-ui": "git+ssh://git@github.com/my-company/cards-ui.git#^1.0.8",
```

note the`^`.  Yarn interprets this using the normal semantic versioning rules, which is great. However when dependapot makes a PR, it drops the `^`:

 ```
"@my-company/advice-ui": "git+ssh://git@github.com/my-company/cards-ui.git#1.0.9",
```

Is that expected? Is there some configuration I can use to end up with `"@my-company/advice-ui": "git+ssh://git@github.com/my-company/cards-ui.git#^1.0.9",` ?

**Comment by greysteil** [comment]
That's definitely a bug! I've fixed it in [this PR](https://github.com/dependabot/dependabot-core/pull/938), which I'll get deployed tonight. Thanks for the heads up!
