### ISSUE TITLE
support a new poetry 1.8 `package-mode` option

### ISSUE THREAD

**Issue by freenoth** [dependabot/dependabot-core#9362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

poetry 1.8.2

### Language version

python 3.11.8

### Manifest location and content before the Dependabot update

`/pyproject.toml`

```yaml
[tool.poetry]
package-mode = false
name = "***"
version = "1.0.0"
description = "***"
authors = ["***"]
license = "***"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
sentry-sdk = "^1.42.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

### What you expected to see, versus what you actually saw

Dependabot doesn't create a PR with dependency updates

```
Dependabot encountered an unknown error

Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.
```

Part of error log:
```txt
updater | 2024/03/25 06:06:34 ERROR <job_804605593> Error processing sentry-sdk (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/03/25 06:06:34 ERROR <job_804605593> The Poetry configuration is invalid:
updater |   - Additional properties are not allowed ('package-mode' was unexpected)
```

### Native package manager behavior

poetry 1.8.2 not complaining about new option
```yaml
[tool.poetry]
package-mode = false
```

**Comment by onlined** [comment]
I think this error is not related to #9323, but it's related to Poetry version specified at `python/helpers/requirements.txt` (1.7.1, which is <1.8).

**Comment by abdulapopoola** [comment]
@freenoth ; this should be fixed now.

**Comment by freenoth** [comment]
yes, everything works perfect now, thanks!
