### ISSUE TITLE
Dependabot only updating `// indirect` Go modules in `go.mod`

### ISSUE THREAD

**Issue by jaypipes** [dependabot/dependabot-core#9370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

Go 1.19+

### Manifest location and content before the Dependabot update

https://github.com/k8snetworkplumbingwg/accelerated-bridge-cni/commit/c0b96256bb1c7dd8ca2be0d682e8e960897424c1

### What you expected to see, versus what you actually saw

I expect Dependabot PRs for Go projects to update only *direct* dependencies in the `go.mod` file, then run `go mod tidy` which will update the `go.mod` file for any *indirect* dependencies.

However, from the commit listed above, you can see that Dependabot manually changed *only indirect* dependencies in the `go.mod` file and then ran `go mod tidy` to update the `go.sum` file.

AFAIU, this should not be done (because the version of direct dependencies that depended on the indirect dependency versions has not been changed and therefore there is no uplifting of the indirect dependency used by those direct dependencies.

In the commit shown above, you see this:

![image](https://github.com/dependabot/dependabot-core/assets/265023/a0f2a726-c316-410c-88cb-6b1fb2f8d0a1)

which shows me Dependabot didn't determine *where* those indirect dependencies were coming from. It uplifted the indirect dependency versions but didn't uplift the version of the direct dependencies that brought in the old versions of the indirect dependencies... I would have expected to see one or more lines changed in the `go.mod` file that *did not* have `// indirect` after them.

**Comment by jakecoffman** [comment]
Per the Minimal Version Selection doc: https://research.swtch.com/vgo-mvs

> Minimal version selection assumes that each module declares its own dependency requirements: a list of minimum versions of other modules. Modules are assumed to follow the [import compatibility rule](https://research.swtch.com/vgo-import)—packages in any newer version should work as well as older ones—so a dependency requirement gives only a minimum version, never a maximum version or a list of incompatible later versions.

So it should be acceptable to bump an indirect version in Go without bumping the direct version, as long as it isn't a major bump.

With a v0 dependency, it's possible there may be a breaking change so we recommend having continuous integration.

**Comment by k37y** [comment]
@jakecoffman, does that mean Dependabot will not bump an indirect dependency if it involves a major version change?
