### ISSUE TITLE
Go toolchain gets removed

### ISSUE THREAD

**Issue by janisz** [dependabot/dependabot-core#9422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Package manager version

1.21

### Language version

1.21

### What you expected to see, versus what you actually saw

In PR https://github.com/stackrox/stackrox/pull/10604/files the toolchain was removed

### Native package manager behavior

Toolchain is not removed

**Comment by jakecoffman** [comment]
I can reproduce this behavior using the Go CLI directly. In a docker container:

```sh
docker run -it --rm golang:1.22.1
```

Run:

```sh
git clone https://github.com/stackrox/stackrox
cd stackrox
go get github.com/Shopify/toxiproxy/v2@v2.9.0
```

It seems the behavior is improved in Go 1.22.2, it leaves the toolchain directive, so this will be improved by by #9449. But it's native package manager behavior so there's nothing we can do about it here.
