### ISSUE TITLE
dependabot create wrong PR for actions

### ISSUE THREAD

**Issue by Omico** [dependabot/dependabot-core#9456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

actions

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

### What you expected to see, versus what you actually saw

See https://github.com/OmicoDev/fonts/pull/1
Why it can `Bump gradle/actions from 3 to 321`
There is no such `321` but have `v3.2.1`

**Comment by bigdaz** [comment]
The https://github.com/gradle/actions repository _temporarily_ had a `v321` tag. This was never intended as a release.

Is there a way for Dependabot to realize that this version no longer exists, and that `v3` and `v3.2.1` are the highest versions?
Hopefully users _will_ get a Dependabot update when `v4` is released later this year :).

**Comment by Omico** [comment]
> Is there a way for Dependabot to realize that this version no longer exists, and that `v3` and `v3.2.1` are the highest versions? 

Seem Dependabot already supports that https://github.com/OmicoDev/fonts/pull/1#issuecomment-2048602043. I think the issue can be closed.
