### ISSUE TITLE
Filing batch PRs

### ISSUE THREAD

**Issue by Pomax** [dependabot/dependabot-core#949]
Would it be possible to add an option to dependabot to file a "batched" PR?

For example, it would be super beneficial to get a single batched PR every Monday that uplifts every python dependency for a project that tangentially relies on Django and for which it's much easier to just accept a single PRs with 10 uplifts, rather than having to approve things one by one, approving a PR, waiting for the next PR to rebase, approving that, waiting for the next PR to rebase, approving that, etc ten times in a row while blocking other people from landing regular code changes because of the constant rebases invalidating their merge state on github.

**Comment by greysteil** [comment]
Thanks for the feedback! We've got a (sadly long-running) issue tracking this one at https://github.com/dependabot/feedback/issues/5. It's a big improvement we'd love to make, but we're a small team!
