### ISSUE TITLE
Can't fetch metadata from hidden repositories

### ISSUE THREAD

**Issue by lenntt** [dependabot/dependabot-core#952]
I've sources on GHE (private) and dependencies in artifactory (private). The pull requests Dependabot generates don't contain the commit logs etc.

Digging a bit further...
it gets into `MetadataFinder#find_source_from_registry`, which calls `latest_version_listing`. This does a request, which fails with a 403.

I think it uses different authentication. I see a response `Bad props auth token: basictoken=some:token`, while in other places, that token was encoded.
(`MetadataFinder#registry_auth_headers` vs `RegistryFinder#auth_header_for`)

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.
