### ISSUE TITLE
Config file dependency_type

### ISSUE THREAD

**Issue by cihati** [dependabot/dependabot-core#953]
First of all, great work for launching the config files!

What actually is the `dependency_type` parameter? It is used in https://dependabot.com/blog/introducing-config-files/ quite a bit, but not explained.

**Comment by greysteil** [comment]
Ah, sorry, I guess we were hoping that would be self-explanatory!

`dependency_type` is meant to mean what category of dependency something is - generally `production` or `development`. So in JS, a dependency declared in `devDependencies` in your `package.json` would have the type `development`, and one declared in `dependencies` would have the type `production`.

Is that clearer?

**Comment by cihati** [comment]
Yep -- definitely cleaner but I highly suggest documenting it somewhere (in general, the config file documentation should probably not live in a blogpost = )

**Comment by greysteil** [comment]
Great!

Yes - proper docs coming soon, just wanted to make sure we had something to ship for v1!

**Comment by SeanFeldman** [comment]
> proper docs coming soon

How soon is "soon"? 😂 
I've just run into this in the documentation and could find any documentation about `dependency_type`.

**Comment by mikedotexe** [comment]
Ran into this today, too. Looking forward to documentation. Great product! Keep up the good work.

**Comment by hashier** [comment]
Ran into it today.
Is `dependency_type` only supported for `javascript`?
