### ISSUE TITLE
Support for updating existing Pull Requests

### ISSUE THREAD

**Issue by lenntt** [dependabot/dependabot-core#954]
I believe once a PR created by dependabot exists, it doesn't get updated at all.
 
Use cases:
* New information may get available about the release 
* Resolve conflicts, e.g. when someone bumps a minor manually (so the lock file cant be merge automatically anymore).

**Comment by greysteil** [comment]
The backend app for Dependabot (i.e., the hosted https://dependabot.com service) already handles the above - I'm guessing what you want is for the example update script we've written for using dependabot-core to also do so?

I'd happily accept community contributions to dependabot-script to do the above, but I can't prioritize it from Dependabot's side - it undermines the paid version of Dependabot's value add.
