### ISSUE TITLE
Provide list or dashboard of Dependabot findings per team

### ISSUE THREAD

**Issue by alekgosk** [dependabot/dependabot-core#9599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,

I know Dependabot currently provides an option to see open Security Advisories for a particular GitHub repository. I also know it's possible to group them per ecosystem (for example Ruby bundler, javascript, etc.)

For us however, it would be super beneficial to group open Security Advisories per teams within Github.

For context - we are currently looking into improving our Operational Excellence and want to have a generic dashboard within DataDog, that includes open security vulnerabilities. We want to have those operational excellence dashboards per team, with their own business metrics but also having some generic bits all teams should have - like open Security Advisories being one of them. 

Having a link for example like this, that we could put into our DataDog dashboard: 

https://github.com/[organisation]/[team]/security/dependabot

with a list of open Dependabot issues grouped per team in Github, would be greatly beneficial!

I hope what I wrote and described makes sense, please let me know if further clarification is needed!

**Comment by jeffwidman** [comment]
Great feedback, but this is the wrong place to post this request... this shows the better place to request it: https://github.com/dependabot/dependabot-core?tab=readme-ov-file#dont-file-issues-about-security-alerts-or-dependency-graph

See also the one exception we've made so folks have a centralized place to discuss:
* https://github.com/dependabot/dependabot-core/issues/2936
