### ISSUE TITLE
SAST

### ISSUE THREAD

**Issue by mcandre** [dependabot/dependabot-core#9608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add SAST support, in order to proactively address first party vulnerabilities with automated scans before human researchers manually publish formal CVE reports.

For example, report unsanitized SQL query strings passed to well known SQL drivers and ORM library raw query functions.

**Comment by martincostello** [comment]
Isn't what your asking for just [CodeQL](https://codeql.github.com/) and [Dependabot security alerts](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates)?

**Comment by martincostello** [comment]
> Is CodeQL automatically enabled for all FOSS GitHub.com repositories like Dependabot?

No, you need to turn it on, and then possibly configure it, depending on which language(s) you use.

> Does CodeQL come with any stock rules?

Yes it does - I refer you to their documentation on how to use it: [Configuring default setup for code scanning](https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning)

**Comment by JamieMagee** [comment]
+1 to @martincostello. SAST is outside the scope of dependabot, but in scope for CodeQL.

@mcandre if you have never received any alerts from CodeQL double check your configuration, and maybe enable the extended ruleset. The documentation @martincostello explains how to do that.

**Comment by mcandre** [comment]
Why not enable CodeQL by default, just like Dependabot?

Just assume that millions of repos are needlessly vulnerable.

**Comment by JamieMagee** [comment]
I see your point, but unfortunately, it's not related to Dependabot.

Can you open an issue in the CodeQL repository? https://github.com/github/codeql
