### ISSUE TITLE
RSPEC files failing across the core ecosystem

### ISSUE THREAD

**Issue by GarryHurleyJr** [dependabot/dependabot-core#9750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

all

### What you expected to see, versus what you actually saw

Expected: rspec files to run properly.

What we saw:  Gem file "dependabot-common" is missing.  When it is installed/updated, other failures are present with missing or incorrect version info.

**Comment by GarryHurleyJr** [comment]
rspec spec                          

An error occurred while loading ./spec/dependabot/npm_and_yarn/dependency_files_filterer_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/sub_dependency_files_filterer_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/dependency_files_filterer_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_parser_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_parser_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_parser_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_parser_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/package_json_preparer_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/package_json_preparer_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/package_json_preparer_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/file_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_parser_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/file_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/helpers_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/version_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_parser_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because json-2.7.2 conflicts with json (< 2.7)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/helpers_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/metadata_finder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/package_name_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/metadata_finder_spec.rb:5:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/package_name_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/metadata_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/package_name_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/requirement_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/version_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/requirement_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/sub_dependency_files_filterer_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/dependency_files_filterer_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/sub_dependency_files_filterer_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/library_detector_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/update_checker_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_updater_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/update_checker_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn/version_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/file_parser_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn/version_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/dependabot/npm_and_yarn_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn/version_spec.rb
                    rspec ./spec/dependabot/npm_and_yarn/helpers_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/dependabot/npm_and_yarn_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'

An error occurred while loading ./spec/npm_and_yarn_config_spec.rb. - Did you mean?
                    rspec ./spec/dependabot/npm_and_yarn_spec.rb

Failure/Error: require "#{common_dir}/spec/spec_helper.rb"

Gem::ConflictError:
  Unable to activate dependabot-common-0.257.0, because faraday-2.9.0 conflicts with faraday (= 2.7.11), faraday-retry-2.2.1 conflicts with faraday-retry (= 2.2.0), json-2.7.2 conflicts with json (< 2.7), octokit-8.1.0 conflicts with octokit (>= 4.6, < 7.0)
# ./spec/spec_helper.rb:12:in `<top (required)>'
# ./spec/npm_and_yarn_config_spec.rb:4:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- dependabot/dependency_file
#   ./spec/spec_helper.rb:12:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 7.86 seconds to load)
0 examples, 0 failures, 30 errors occurred outside of examples

Coverage report generated for RSpec to /Users/garryleehurleyjr/Documents/GitHub/dependabot-core/npm_and_yarn/coverage. 0 / 0 LOC (100.0%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
garryleehurleyjr@Garrys-MacBook-Pro npm_and_yarn

**Comment by thavaahariharangit** [comment]
Unable to reproduce in local environment

## Testing npm_and_yarn test failure reported by Garry

1. Ensure you have up todate code
```
$ git checkout main
$ git pull
$ bin/docker-dev-shell npm_and_yarn --rebuild
```
2. In dev shell
```
[dependabot-core-dev] ~ $ cd npm_and_yarn/
[dependabot-core-dev] ~/npm_and_yarn $ rspec spec
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.

Randomized with seed 865
....

Finished in 11 minutes 0 seconds (files took 3.92 seconds to load)
1193 examples, 0 failures, 2 pending

Randomized with seed 865

Coverage report generated for RSpec to /home/dependabot/npm_and_yarn/coverage. 3786 / 3914 LOC (96.73%) covered.
[dependabot-core-dev] ~/npm_and_yarn $ 

```

**Comment by GarryHurleyJr** [comment]
Rebuilt and deployed version 0.258.0 of dependabot gems.
