### ISSUE TITLE
Add support for Appraisal

### ISSUE THREAD

**Issue by hlascelles** [dependabot/dependabot-core#978]
If a ruby project is using [Appraisal](https://github.com/thoughtbot/appraisal), it would be convenient if the necessary lock files were updated.

Essentially, this would involve calling `bundle exec appraisal install`. An example would have been [this PR](https://github.com/hlascelles/que-scheduler/pull/51) that would have resulted in 3 files being changed.

I'm not sure if you would see this as a thin end of the wedge to adding a whole load of build tool chains?

**Comment by greysteil** [comment]
Thanks for this @hlascelles, and sorry for the slow reply.

I'd really like to support Appraisal. I need to look into exactly what happens when appraisal install is called, but can see us working something out here.

**Comment by hlascelles** [comment]
Wonderful. Thanks very much!

**Comment by hlascelles** [comment]
Still valid.

**Comment by infin8x** [comment]
Closing this as we don't think we'll support it directly in Dependabot. You could do this with an Action that runs on Dependabot PRs.
