### ISSUE TITLE
Opt out security label and vulnarability information from PRs

### ISSUE THREAD

**Issue by bhathiya** [dependabot/dependabot-core#980]
First of all, thanks for the great bot. 

I have a question. Is the $subject possible with some configuration? I basically want to make sure there is no difference between a security PR and a non-security PR. This is due to security reasons. 

Thanks.

**Comment by greysteil** [comment]
Not that the moment. I think the right solution here might be to have the option to opt-out of security vulnerability details on public repos, probably at the account level. I'll have a think, and if it fits nicely in the UI will get that implemented today.

**Comment by bhathiya** [comment]
That would be great. Thank you. One more related question.

I need to remove `security` label and `[security]` part from the title as well. 

I think the former can be done with `@dependabot use these labels`. Is there a way to configure the latter?

**Comment by greysteil** [comment]
No, but I think a better solution is to have them connected. I've just added a new toggle at the account level (deploying now). If you switch it off, Dependabot won't mention anything about PRs being security related on public repos:

![image](https://user-images.githubusercontent.com/1144873/52342796-3cd4d280-2a0e-11e9-9892-0fbe1c7f28b5.png)

**Comment by dulanjal** [comment]
How can we configure this through the config.yml [1]?

[1] https://dependabot.com/docs/config-file/

**Comment by greysteil** [comment]
Not possible at the moment - this is an account level setting, rather than a repo-level one. If you configure it in your account settings at https://app.dependabot.com then it will apply to all your repos.

We'll likely add it at the repo level, and therefore config file level, in the next few weeks.

**Comment by dulanjal** [comment]
Thanks @greysteil.
