### ISSUE TITLE
Dependabot creates "---" as commit message

### ISSUE THREAD

**Issue by glensc** [dependabot/dependabot-core#9825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, pipenv

### What you expected to see, versus what you actually saw

See example commits:
- https://github.com/Taxel/PlexTraktSync/commit/386accbca6a6e641e2f2affff4a45d8b3412aac4
- https://github.com/Taxel/PlexTraktSync/commit/c17a733fdb2cce458075f4023115a91dad863e7d

They were both merged with `@dependabot squash and merge`:
- https://github.com/Taxel/PlexTraktSync/pull/1958#issuecomment-2123288196
- https://github.com/Taxel/PlexTraktSync/pull/1956#issuecomment-2122541656

**Comment by TonyRL** [comment]
Duplicate of #9784
