### ISSUE TITLE
Dependabot reporting invalid gemspec metadata incorrectly

### ISSUE THREAD

**Issue by olivierlacan** [dependabot/dependabot-core#983]
Hi there,

As you can see in https://github.com/olivierlacan/etalon/issues/1#issue-407948239 it seems like Dependabot is choking on dynamic gemspec entries that refer to other gemspec entries. This seems like a bug because gemspecs are Ruby and should be interpreted, not just taken as final data. 

```
Gem::InvalidSpecificationException with message: The gemspec at /home/dependabot/dependabot-updater/dependabot_tmp_dir/etalon.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata values must be a String'
```

You can find the offending lines here: 
https://github.com/olivierlacan/etalon/blob/86b88a64013beb30f677b4ae278fd7fa1faa7c72/etalon.gemspec#L19-L23

```ruby
  if spec.respond_to?(:metadata)
    spec.metadata["homepage_uri"] = spec.homepage
    spec.metadata["source_code_uri"] = spec.homepage
    spec.metadata["changelog_uri"] = "#{spec.homepage}/blob/master/CHANGELOG.md"
  end
```

I think the solution would be to ensure dependabot properly runs the gemspec code before evaluating its validity.

**Comment by greysteil** [comment]
Let me take a look. We do a _lot_ of gemspec sanitizing, because Dependabot doesn't clone your repo, so it will be that that's going wrong...

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/3776dd4c6f79dc4cbdc5394f433894d64f4397ce, which I'll release and deploy now.

**Comment by greysteil** [comment]
(And thanks masses for reporting this!)
