### ISSUE TITLE
[Gitlab] : Error when trying to create the dependencies label

### ISSUE THREAD

**Issue by codisart** [dependabot/dependabot-core#985]
When the bot try to create the dependencies label on gitlab, it query first the list of labels to check if it exists. But the labels endpoint of the gitlab api is paginated.
So if the dependencies label exist but is not on the first page, the bot will believe it doesn't exist and the creation will fail.

**Comment by greysteil** [comment]
Thanks for the heads up. We handle that for GitHub - sounds like we need to handle it for GitLab too. I'll take a look.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/519ae3e3590c4583576b6a2ec86b5d17b13c0848, which is tagged as `0.95.5`. Thanks again for the feedback!

**Comment by codisart** [comment]
Nice and fast work !! No problem ! It was a fun bug to find.
