### ISSUE TITLE
Fail to identify the latest version for the dependencies which are hosted in custom maven repository repository

### ISSUE THREAD

**Issue by mathuriga** [dependabot/dependabot-core#993]
I'm using some java third-party dependencies which are hosted in Maven central and some are hosted in custom maven repository [WSO2 Public Maven Repo](http://maven.wso2.org/nexus/content/repositories/public/).

I could observe that Dependabot fails to identify the third party dependencies which are hosted in the above URL. (Note that I have configured this URL in config variable)

Eg: [org.wso2.orbit.com.fasterxml.jackson.core](https://mvnrepository.com/artifact/org.wso2.orbit.com.fasterxml.jackson.core/jackson-databind)

I'm not sure whether I have to any other configuration. Could you please Advise on this?

**Comment by greysteil** [comment]
Hi @mathuriga,

It looks to me like Dependabot *is* finding that dependency at the URL you've passed as a config variable, it's just that no update is available. Can this be closed?

**Comment by mathuriga** [comment]
Hi @greysteil ,

I'm have mentioned version 2.6.1.wso2v1 in the pom, but the latest version is 2.6.1.wso2v3 as per [1].

[1]

**Comment by greysteil** [comment]
Awesome, thanks for using Dependabot, and don't ever hesitate to open issues if it can be better in any way 🙂
